### ISSUE TITLE
Review and Document Dockerfiles

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falco#1019]
**Motivation**

After mentioning deprecating docker images in #1015 I think this merits a holistic review of our Dockerfiles. 

**Feature**

Can we please audit, and document which container images we are supporting, how each of them should be used, and assign owner(s) for them?

**Alternatives**

**Additional context**

**Comment by kris-nova** [comment]
From @mstemm in Slack :+1: 

> a tailored build suitable for alpine linux would help a lot with making the container smaller and with a smaller potential set of dependencies. We’d have to build an .apk from source that links against musl libc, but once you had that, creating the image would be as simple as changing the base image to some alpine image and doing an apk add instead of dpkg -i

**Comment by kris-nova** [comment]
Another quick note, as https://github.com/falcosecurity/falco/issues/1024 starts to ramp up, we in theory should be able to drastically simplify our Dockerfiles 

I think in a perfect world all a Falco dockerfile will do is use the in-house package manager to install Falco as it would on any other operating system.

**Comment by leodido** [comment]
Now that the main docker images have been refactored (PR #1059, #1063, #1069, #1076, etc) let's recap the current situation so to highlight what we still could/should do about them.

| name (falcosecurity:...)                                                                                | directory                 | scope                                                                              | auto build & push |
|---------------------------------------------------------------------------------------------------------|---------------------------|------------------------------------------------------------------------------------|-------------------|
| [falco-builder:latest](https://hub.docker.com/repository/docker/falcosecurity/falco-builder)            | docker/builder            | use it to build Falco (CI)                                                         |                   |
| [falco-tester:latest](https://hub.docker.com/repository/docker/falcosecurity/falco-tester)              | docker/tester             | use it to run Falco integration tests (CI)                                         |                   |
| to not be published                                                                                     | docker/local              | built on-the-fly and used by falco-tester                                          |                   |
| [falco:latest](), falco:\<tag\>, [falco:master]()                                                       | docker/stable             | Falco (DEB built from git tag or from the master) with all the building toolchain  | :white_check_mark: |
| [falco:latest-minimal](), [falco:master-minimal]()                                                      | docker/minimal            | Falco (TGZ built from git tag or from the master) without the building toolchain   | :white_check_mark: |
| [falco:latest-slim](), [falco:master-slim]()                                                            | docker/slim               | Falco (DEB build from git tag or from the master) without the building toolchain   | :white_check_mark: |
| not able to find where it has been published                                                            | docker/rhel               |                                                                                    |                   |
| [falco-event-generator:latest]()                                                                        | docker/event-generator    | Event generator tool to simulate events Falco catches                              |                   |
| [probe-linuxkit-4.9.184](https://hub.docker.com/repository/docker/falcosecurity/probe-linuxkit-4.9.184) | docker/kernel/linuxkit    | to build and to insert the Falco kernel module on linuxkit kernel 4.19.184         |                   |
| [probeloader:latest](https://hub.docker.com/repository/docker/falcosecurity/probeloader)                | docker/kernel/probeloader | to install the Falco kernel module by the mean of `falcoctl install probe` command |                   |

**Comment by fntlnz** [comment]
I agree with everything !! @leodido let's make it happen

**Comment by kris-nova** [comment]
I agree - like we said in slack I think we need to be aware of what we keep in the repository as we stage for our first `LTS` release of Falco

Also we mentioned renaming the probeloader on the last call - we should probably consider that as well as here.

**Comment by leodido** [comment]
We need to review [this](https://github.com/falcosecurity/falco/blob/master/docker/README.md#falco-dockerfiles) page, and maybe merge in it what I wrote two comments above.

After that, I think we'll be able to close this.

**Comment by leodido** [comment]
FYI @Issif

**Comment by leogr** [comment]
I totally agree too. Furthermore, `probeloader:latest` might not work anymore because of falcoctl, and [here](https://github.com/falcosecurity/falcoctl/issues/86) we are discussing what falcoctl will do.
I will take care of fixing this asap
/assign
