### ISSUE TITLE
Reduce docker build time in circleci 

### ISSUE THREAD

**Issue by rajibmitra** [falcosecurity/falco#1023]
**Motivation**
When small things are changed which doesn't require full docker build , in those cases we can use previous build's layer to have faster build time. 

**Feature**
add docker cache layer option to reduce build time 

Add option in circleci config file so that the cache layer is enabled. 

**Alternatives**

**Additional context**

**Comment by rajibmitra** [comment]
#1022

**Comment by leodido** [comment]
Closing this for now as we are not using any paid plan for CircleCI.
