### ISSUE TITLE
Installing Falco locally

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falco#1024]
**Motivation**

A little known caveat of Falco (until you are deeply involved in the project, or using Falco) is that by definition it only works on systems using a Linux kernel. That is how the system event parsing from the kernel works. Using Linux features :smile: 

Right now installing Falco is a bit fragmented, and could be much more seamless. We need help and owners if we are lucky to manage a few different ways of managing Falco.

**Feature**

Can we please support the following ways of Installing Falco (not in a container) but rather locally on a Linux system. 

_Note_: This might imply either working with official repositories or creating our own. All of which is possible, and if anyone needs guidance on how to do this please let me or the rest of the community know. Feel free to message in slack or email the mailing list. 

 - [ ] Debian/Ubuntu like systems `apt-get install falco`
 - [ ] Archlinux like systems `pacaur -S falco` _Note_: We probably should add a package to [AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository) 
 - [ ] RPM like systems `yum install falco` 
 - [ ] RHEL like systems `yum install falco`
 - [ ] Suse like systems `zypper install tree`

---

Other things to consider:

 - There might be existing work here, but we should review it, document it, and collaborate all of this work with he new [build/release working group](https://lists.cncf.io/g/cncf-falco-dev/topic/build_release_infrastructure/69990725). 

 - We should open issues for each of the items above, so that they serve as documentation for the project. There is a good chance if somebody Googles `installing falco on archlinux` that the github issue created for that effort will be the first result, for example. 

**Alternatives**

**Additional context**

Adding an **expert mode** section here. 

It might be worthwhile to start thinking about ways of installing falco on other commonly used architectures. This will be much more challenging, as Falco is so dependent on the linux kernel, and depends directly on having kernel headers in place.

 - [ ] Darwin (OSx) like systems `brew install falco`
 - [ ] Windows like systems `double click on a wizard or something, I have no idea` 
 - [ ] WSL (Windows subsytem for Linux) again this might be a pain, because we need the kernel, and the kernel headers. But it might be possible with running a conainer.

More context to start thinking about, there is [this great blog](https://t.co/cbYpJN4Yxc?amp=1) on running Falco on Mac/Windows

**Comment by kris-nova** [comment]
Also check out this issue I opened https://github.com/falcosecurity/falco/issues/1024

There is a lot to consider here, and I think having the operating system logic to install Falco should live in a place that users of the operating system would expect it to be.

Note: If we had Falco supported in many different operating systems natively, building a Falco container would be as simple as doing something like `apt-get install falco` 

Furthermore all `falcoctl` would have to do would be exactly the same thing `apt-get install Falco`

**Comment by kris-nova** [comment]
One of these days I might be crazy enough to add and maintain a package to freshports for our FreeBSD friends.

But the internet seems like to sign me up for a lot of the FreeBSD container things so I am not promising anything (yet).

**Comment by mohitgoyal2011** [comment]
I had a question. Doesn't apt-get install falco already exist ? I took a look at the bash script mentioned in the installing falco docs. It seems to take care of adding a repo and installing the headers then the package. I'm dead sure I'm missing something here :)

**Comment by kris-nova** [comment]
Hey @mohitgoyal2011,

So yes - the [documentation](https://falco.org/docs/installation/ ) has examples of downloading repository lists and gpg keys for both yum and apt-get.

We need all of the packages up to a certain standard however, and neither of this are at that standard. In fact I’m fairly certain that hosting gpg keys and repository information and artificacts as they are now is not only bad practice - but could also very well be illegal. 

Here is what we need for every OS level package we chose to support 

 - Documentation on how the packages are built 
 - A build pipeline hosted by the CNCF, that allows for community members to get involved 
 - Documentation on our support and release guarantees and goals 
 - Probably some sort of testing 
 - Maintainers in charge of each supported OS

**Comment by mohitgoyal2011** [comment]
So referring back to falcoctl, the user experience of installing Falco should ideally be just googling "install Falco", go to the link, get falcoctl and type in falcoctl install falco --local or kubernetes. This should take care of the installation directly without exposing GPG keys or requiring any hard-coding.

**Comment by kris-nova** [comment]
Yes exactly,

But I also think that we need to be very clear of the following

 - ALL logic to go from _nothing_ to a working Falco installation should live in an OS level repository 
 - The `falcoctl` CLI tool would simply wrap that logic, and offer other utilities to getting Falco set up the way you prefer 
 - So even if to start all that `falcoctl install falco --local` does is run `apt-get install falco` that is totally okay

**Comment by kris-nova** [comment]
In my mind,

If a user wanted to set up Falco and a tool like Prometheus locally the user experience might look something like this:

```bash
falcoctl install falco --local                #This would install the `falco` executable and drop it off somewhere like `/usr/local/bin`
falcoctl install tls --local                    #This would generate and install TLS material and drop it off somewhere like `/etc/falco`
falcoctl install rule <rule1>               #This would install a rule from the hub and drop it off somewhere like `/etc/falco/rules.d/`
falcoctl install rule <rule2>               #This would install another rule from the hub and drop it off somewhere like `/etc/falco/rules.d`
falcoctl install prom                          #This would install the `falco-exporter` tool, and Prometheus and configure the local filesytem to make everything work
```
