### ISSUE TITLE
Falco build service

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falco#1027]
**Motivation**

As discussed in the build and release infrastructure call we decided to build a service that will allow people to:

- Download deb/rpm packages
- Download probes and kernel modules

When a probe or kernel module is required by a user for a specific combination of kernel version + falco version + kernel config flags, that triggers a build for that combination that will result in an artifact. That artifact will be available at the same url after.

@kris-nova and @fntlnz are going to make a proposal for this with more details.

**Alternatives**

- The s3 we have now

**Additional context**

Look here https://hackmd.io/ub_t_KqlSzS4Gc_e3r1oOQ?both

**Comment by kris-nova** [comment]
Link to repository to track this work: https://github.com/falcosecurity/build-service

We can open issues there
