### ISSUE TITLE
Ban additional functions

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falco#1035]
**Motivation**

Now that we have https://github.com/falcosecurity/falco/pull/1031 - we want to consider banning additional functions that are unsafe in C/C++ to mitigate human error while merging future PRs.

**Feature**

Possible functions (please add more if needed):

- vsprintf()
- sprintf()
- strcat()
- strncat()
- strncpy()

**Alternatives**
None

**Additional context**

Read the original issue: https://github.com/falcosecurity/falco/issues/788

**Comment by vrongmeal** [comment]
Also, I was wondering if we should add this in the documentation to include `"banned.h"` if a new file is created in `userspace`.

**Comment by leodido** [comment]
@vrongmeal yes, I'd like to have it documented.

**Comment by leodido** [comment]
I would add also add the following to the list:

* swprintf
* vswprintf

We want `snprintf()` (or one of the specialized non-varg versions to be used, instead.
