### ISSUE TITLE
memory leak while processing the audit endpoint

### ISSUE THREAD

**Issue by iverberk** [falcosecurity/falco#1040]
**Describe the bug**

Falco is not releasing memory when it is processing events on the k8s audit endpoint. We are running several Falco pods and one of them is processing the Kubernetes audit events, which are provided via this project: https://github.com/xebia/falco-eks-audit-bridge. We notice that all pods are fine, except the one that is receiving all the audit events. Below is graph of the memory usage:

<img width="1604" alt="Screenshot 2020-02-06 at 11 52 52" src="https://user-images.githubusercontent.com/2798710/73935671-5b9bcc80-48e1-11ea-9a01-978c7ebd85dd.png">

As you can see there is clear pattern where the pod gets OOM-killed after 1.5-2 hours. At the end we switched our falco-eks-audit-bridge to a different node and then we saw the exact same pattern with the Falco pod that is running on that node (it is offering the audit events via a localhost connection). 

**How to reproduce it**

We're still running some tests to confirm, but it should be easy to reproduce by just load-testing the audit endpoint with audit json logs.

**Expected behaviour**

Memory usage should remain stable, as it did in previous versions of Falco.

**Environment**

- Falco version:
0.19.0 with a 'minimal' build and ebpf probe.

- System info: release":"4.14.154-128.181.amzn2.x86_64"
- Cloud provider or hardware configuration: AWS
- Installation method: Kubernetes

**Comment by fntlnz** [comment]
More analysis of this problem in #1041 

PR that introduced the leak: https://github.com/falcosecurity/falco/pull/826/

Affected Falco versions: 0.18.0, 0.19.0

**Comment by iverberk** [comment]
Thanks for the quick response and analysis! 👍

**Comment by fntlnz** [comment]
Thanks @iverberk for bringing this to our attention. Now that 0.20.0 is released, this fix is included.

https://falco.org/blog/falco-0-20-0/
