### ISSUE TITLE
Unable to install Falco by applying DaemonSet

### ISSUE THREAD

**Issue by rashmi43** [falcosecurity/falco#1043]
**Describe the bug**
Issue with installing Falco using DaemonSetCondition manifests

**How to reproduce it**

kubectl apply -f k8s-with-rbac/falco-daemonset-configmap.yaml

**Expected behaviour**

kubectl apply daemonset config should work.

**Screenshots**

kubectl apply -f k8s-with-rbac/falco-daemonset-configmap.yaml 
error: unable to recognize "k8s-with-rbac/falco-daemonset-configmap.yaml": no matches for kind "DaemonSet" in version "extensions/v1beta"

After changing it to v1/apps:
kubectl apply -f k8s-with-rbac/falco-daemonset-configmap.yaml 
error: error validating "k8s-with-rbac/falco-daemonset-configmap.yaml": error validating data: ValidationError(DaemonSet.spec.selector): unknown field "app" in io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector; if you choose to ignore these errors, turn validation off with --validate=false

**Environment**

- Falco version:
git clone https://github.com/falcosecurity/falco/
- System info:

- Cloud provider or hardware configuration:
- OS: ubuntu
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel:

Linux frivol1.fyre.ibm.com 4.4.0-166-generic #195-Ubuntu SMP Tue Oct 1 09:35:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Installation method: 
Kubernetes --> 1.17.1

**Comment by maxgio92** [comment]
The same for me running Kubernetes 1.16.2 on minikube 1.5.2. The issue I think is for [deprecations](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md#deprecations-and-removals)  introduces with the 1.16

**Comment by robotica72** [comment]
I had this issue as well, you can get past the error by changing the YAML before deploying:

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco-daemonset
  labels:
    app: falco-example
    role: security
spec:
  selector:
    matchLabels:
      app: falco-example

This works on the newest kind that is running K8s 1.17

**Comment by maxgio92** [comment]
Hi @robotica72 you can follow my PR https://github.com/falcosecurity/falco/pull/1044

**Comment by ssurovich** [comment]
@maxgio92 - Cool, will do - Thanks for the link
