### ISSUE TITLE
Enable output of Mitre Att&ck tags

### ISSUE THREAD

**Issue by rbytheway** [falcosecurity/falco#1046]
**Motivation**

It would great to be able to output the Mitre Att&ck tags when a Falco alert gets generated.  

**Feature**

For any Falco rule, its output should include the Mitre Att&ck tag(s) by default

**Alternatives**

**Additional context**

**Comment by leodido** [comment]
It sounds like a suitable and cool idea to me.

Could you just provide an example output line for this?

**Comment by rbytheway** [comment]
>   - rule: Write below monitored dir
    desc: an attempt to write to any file below a set of binary directories
    condition: >
      ...
    output: >
      File below a monitored directory opened for writing (user=%user.name
      command=%proc.cmdline file=%fd.name parent=%proc.pname pcmdline=%proc.pcmdline 
      gparent=%proc.aname[2] container_id=%container.id image=%container.image.repository
      **tag_mitre=%tags.mitre tag_category=%tags.category**)
    priority: ERROR
    tags: [filesystem, mitre_persistence]

on rules with more than 1 mitre tag, return it as an array or kv or ?.  shouldn't be too hard for json parsers :)

In this example, `filesystem` would be the category.
just a rough idea, but being able to access any of the tags would be useful.

**Comment by leogr** [comment]
I believe we want to keep this

**Comment by leogr** [comment]
@fntlnz Do we need to add a label for this so the stale bot will not touch this anymore?

**Comment by leodido** [comment]
Yes, done.
