### ISSUE TITLE
not able see falco service in falco helm chart 

### ISSUE THREAD

**Issue by psingh-xav** [falcosecurity/falco#1053]
i m not able to see service falco-service

when i m  run falco helm chart 

https://hub.helm.sh/charts/stable/falco/1.1.0 

follow from here 

```
NAME:   my-release
LAST DEPLOYED: Tue Feb 18 08:01:12 2020
NAMESPACE: default
STATUS: DEPLOYED
RESOURCES:
==> v1/ConfigMap
NAME              AGE
my-release-falco  1s
==> v1/DaemonSet
NAME              AGE
my-release-falco  1s
==> v1/Pod(related)
NAME                    AGE
my-release-falco-68s5h  1s
my-release-falco-6gzvk  1s
==> v1/ServiceAccount
NAME              AGE
my-release-falco  1s
==> v1beta1/ClusterRole
NAME              AGE
my-release-falco  1s
==> v1beta1/ClusterRoleBinding
NAME              AGE
my-release-falco  1s
NOTES:
Falco agents are spinning up on each node in your cluster. After a few
seconds, they are going to start monitoring your containers looking for
security issues.
No further action should be required.
```

**Comment by Issif** [comment]
Hi,

As you can see there : https://github.com/helm/charts/blob/master/stable/falco/templates/service.yaml#L1 the `Service` is only deployed if `auditLog.enabled = true` (default is `false`).

Remember that `Service` is for now only used to gather `audit logs` from k8s API server.

**Comment by psingh-xav** [comment]
can you help me how to enable audit log i tried audit -policy but I did not get success 

https://github.com/falcosecurity/falco/issues/1052  i raise the issue for same
