### ISSUE TITLE
When Falco Rule Is Missing Fields, Only One Missing Property Is Reported At A Time

### ISSUE THREAD

**Issue by ykcilborw** [falcosecurity/falco#1060]
**Describe the bug**
 
When multiple required fields are missing in a Falco rule, Falco only returns with an error message about one of the missing fields instead of enumerating all the missing required fields.

**How to reproduce it**

1. Create a rule with the following properties:

rule, desc, condition

and that is missing 

priority, output

Example:

---
- rule: Blacklist commands
  desc: Blacklist specific commands
  condition: evt.type in (mkdir, mkdirat)

**Expected behaviour**

Actual response:
Runtime error: Rule must have property output

Expected response:
Runtime error: Rule must have property output and Rule must have have property priority

**Screenshots**

**Environment**

- Falco version:
Falco version: 0.1.2701dev

- OS:
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

Linux vagrant-ubuntu-trusty-64 3.13.0-163-generic #213-Ubuntu SMP Thu Nov 15 02:19:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fntlnz** [comment]
We still want this, thanks stale bot

Thanks for opening @ykcilborw - this is something that can be improved.

**Comment by leogr** [comment]
keep, pls
