### ISSUE TITLE
Publish packages to public/open repositories

### ISSUE THREAD

**Issue by leodido** [falcosecurity/falco#1062]
**Motivation**

As said during various community calls, meetings, issues, etc., we need to have Falco packages published in the open, via a public and auditable mechanism.
At the same time, we also need to sign the packages with a falcosecurity (org) GPG key.

This is a vital piece towards a new and truly open release process for Falco (various references in the issue history (eg., #726).

**Feature**

1. Instruct our CI to publish DEB and RPM packages built from master to a public repository.
2. Instruct our CI to publish DEB and RPM packages built from git tags to a public repository.

During a brainstorming session between @fntlnz and I, we came up with a solution that's easy peasy lemon squeeze: https://bintray.com/falcosecurity 🍋 

In fact using bintray we have the following advantages:

1. no need to build own our packages hosting infrastructure
2. no need to build an API for our own packages hosting infrastructure
3. no need to build a client for our own packages hosting infrastructure
4. login and privileges via GitHub
5. CHANGELOG and README import for packages from GitHub
6. existing API and existing client for bintray
7. bintray plan for open-source projects
8. automatic signing using our own falcosecurity GPG key
9. easy integration with our CI

**Alternatives**

Creating and host own our hosting infrastructure for repositories and packages.
Plus all the remaining pieces to integrate it with the repository, the pieces in place, the CI, etc.

**Additional context**

**Comment by kris-nova** [comment]
Hey - can we get a demo of this on one of the upcoming Wed calls? This is very exciting for us.
