### ISSUE TITLE
Publish pre-built kernel modules to the new repositories on bintray

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falco#1066]
**Motivation**

While on one side we have  #1062 to publish build/release artifacts to new repositories we also want to have a new mechanism to publish pre-built kernel modules and eBPF probes to the bintray repositories.

In this way we can achieve the following:

- We bring back, prebuilt modules (we don't have them since 0.18.0)
- Builds of kernel modules and eBPF probes are public and everyone can contribute
- Builds are auditable
- When a new kernel/OS comes up the process for adding it is public and clear (because it's 100% OSS and Community owned)

**Feature**

We are going to build the modules and have a mechanism for contributors to contribute the ones they want to build using [driverkit](https://github.com/falcosecurity/driverkit).

**Alternatives**

**Additional context**

**Comment by leodido** [comment]
This is now done (into `driverkit` directory of https://github.com/falcosecurity/test-infra).

Although it **only** ships prebuilt drivers for debian, amazonlinux2, ubuntu-aws, ubuntu-generic

/close
