### ISSUE TITLE
Install on CentOS 8 does not always install kernelmodule correct

### ISSUE THREAD

**Issue by kommulu** [falcosecurity/falco#1072]
**Describe the bug**

Hi,
installed Falco on two machines running CentOS 8.1 (all updates installed) with nor problems. Falco runs on these machines just fine.

Now, I have four other CentOS 8.1 machines. They are all setup the same, I  am using Ansible for that.
I am using the Ansible-Role you mention in the docs to setup falco.
What happens is, on two hosts Falco works without a problem.
On the other four, the kernel-module does not seem to get loaded/installed.
When I do a `lsmod | grep falco` on these machines, I get an empty response.
Doing `modprobe falco_probe` on these machines, loads the module successful and falco starts.
I do not understand at the moment what the problem might be here, as these machines all look the same.

**How to reproduce it**

Fire up a few CentOS 8 machines and install Falco via Ansible.
See if on any machine the kernel module is not loaded and Falco therefor does not start.

**Expected behaviour**

Falco is successfully installed on every system via the rpm-package. Kernelmodule is loaded automatically, beyond reboots.

**Environment**

- Falco version:
falco-0.20.0+d77080a-1.x86_64
- Cloud provider or hardware configuration:
- OS:
CentOS 8.1
- Kernel:
4.18.0-147.5.1.el8_1.x86_64
- Installation method:
RPM

Any help is very much appreciated.

**Comment by leodido** [comment]
/keep

We are still investigating this.
L.

**Comment by leogr** [comment]
Hey @kommulu 

Could you try to run `falco-driver-loader` manually, then attach the output here?

Thanks in advance

**Comment by kommulu** [comment]
Hi @leogr ,
I got a mail, saying you commented on this issue, but the comment is not here. Weird.
Anyways, thanks for investigating this.
The mail said you wanted me to run `falco-driver-loader`.

I fired up a testing system, which has the described problem and ran the command.
Here is the output:
```
* Unloading falco-probe, if present
* Running dkms install for falco

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...(bad exit status: 127)
make -j4 KERNELRELEASE=4.18.0-147.8.1.el8_1.x86_64 -C /lib/modules/4.18.0-147.8.1.el8_1.x86_64/build M=/var/lib/dkms/falco/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/build...(bad exit status: 127)
Error! Bad return status for module build on kernel: 4.18.0-147.8.1.el8_1.x86_64 (x86_64)
Consult /var/lib/dkms/falco/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/build/make.log for more information.
* Running dkms build failed, dumping /var/lib/dkms/falco/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/build/make.log
DKMS make.log for falco-a259b4bf49c3330d9ad6c3eed9eb1a31954259a6 for kernel 4.18.0-147.8.1.el8_1.x86_64 (x86_64)
Sun May 17 15:38:01 CEST 2020
/sbin/dkms: line 80: make: command not found
* Trying to load a system falco-probe, if present
* Trying to find precompiled falco-probe for 4.18.0-147.8.1.el8_1.x86_64
Found kernel config at /boot/config-4.18.0-147.8.1.el8_1.x86_64
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-a259b4bf49c3330d9ad6c3eed9eb1a31954259a6-x86_64-4.18.0-147.8.1.el8_1.x86_64-ea6bf7ba7bc281b199cd7bd0fb7866f3.ko
curl: (22) The requested URL returned error: 404 Not Found
Download failed, consider compiling your own falco-probe and loading it or getting in touch with the Falco community
```
This is a completely fresh installed system. Falco was installed using this role:
https://github.com/juju4/ansible-falco

Falco is not starting on this system.

**Comment by leogr** [comment]
Hi @kommulu 

I deleted the comment after I had realized that the installation method was RPM - so I thought that `falco-driver-loader` could not help. My fault, I should have just edited it.

Anyway, thanks to your comment I've noticed right now this:
```
/sbin/dkms: line 80: make: command not found
```
cc @leodido Maybe does RPM installation not work because of `make` is missing?

@kommulu thanks again for reporting this

**Comment by leogr** [comment]
I believe that the missing `make` is the only problem here.
Recently, we added a note to the [CentOS installation instructions](https://falco.org/docs/installation/#centos-rhel) regarding `make`. So, it should be fixed.

Awaiting confirmation.

**Comment by kommulu** [comment]
Hi @leogr ,
I am not sure about that.
My machine for testing was still running, so I installed `make` and updated falco, which went great. No errors, upgrade worked.
But after a reboot the module for falco was not loaded, which of course caused falco to crash.
Running `falco-driver-loader` fixes will successfuly load the module and falco can start. After that.

To check if a reinstall fixes the problem, I reinstalled falco, which did not help.
I mean, I could of course run the driver-loader before starting falco via systemd.
But I think this should work out of the box.

Besides: thanks a lot for still looking into this.

**Comment by leogr** [comment]
Hi @kommulu 

I'm not sure if there was any problem with the `falco-0.20.0+d77080a-1.x86_64` that you reported. I guessed about `make` because of this:
```
/sbin/dkms: line 80: make: command not found
```

Anyhow, with the latest version `0.24.0`, it should work out of the box. The RPM installs the kernel module using `dkms` and also installs the `init.d` unit (that should work with `systemd` too, see [here](https://falco.org/docs/running/)). AFAIK, when the service starts it loads the kernel module too, so you should not need to run `falco-driver-loader` before starting Falco via `systemd`.

Is this problem still present in `0.24.0` ?

**Comment by kommulu** [comment]
Hi @leogr ,
I can confirm that this works now with 0.24.0.
Thanks again for your help.
