### ISSUE TITLE
Falco fails to come up Error loading module: open /falco-probe.ko: no such file or directory 

### ISSUE THREAD

**Issue by saiharshitachava** [falcosecurity/falco#1079]
HI Team..
Im trying to install falco in kubernetes using helm..It was a sucecss but falco never comes up
Building images from source files and used those as well..Nothing works..

I also tried to spin probe-loaded as the initcontainer and that also fails with Error loading module: open /falco-probe.ko: no such file or directory
Please help below is the error I see for falco and probe-loader
ln: failed to create symbolic link '/usr/src//host/usr/src/packages': No such file or directory
* Setting up /usr/src links from host
* Unloading falco-probe, if present
* Running dkms install for falco
Error! echo
Your kernel headers for kernel 4.12.14-95.45-default cannot be found at
/lib/modules/4.12.14-95.45-default/build or /lib/modules/4.12.14-95.45-default/source.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/0.20.0+d77080a/build/make.log
* Trying to load a system falco-probe, if present
* Trying to find precompiled falco-probe for 4.12.14-95.45-default
Found kernel config at /proc/config.gz
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.20.0%2Bd77080a-x86_64-4.12.14-95.45-default-fce608f58cf010b5b5d11717aea9cf11.ko
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
Download failed, consider compiling your own falco-probe and loading it or getting in touch with the Falco community
Thu Mar  5 13:09:56 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Thu Mar  5 13:09:56 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Thu Mar  5 13:09:57 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Thu Mar  5 13:09:58 2020: Unable to load the driver. Exiting.
Thu Mar  5 13:09:58 2020: Runtime error: error opening device /dev/falco0. Make sure you have root credentials and that the falco-probe module is loaded.. Exiting.

kubectl logs audit-test-falco-rsdd9 -c initcontainer
2020-03-05T13:04:19Z [â¿]  FALCO_VERSION: 0.17.1
2020-03-05T13:04:19Z [â¿]  FALCO_PROBE_URL:
2020-03-05T13:04:19Z [â¿]  FALCO_PROBE_REPO: https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/
2020-03-05T13:04:19Z [â¿]  KERNEL_VERSION: 4.12.14-95.45-default
2020-03-05T13:04:19Z [â¿]  KERNEL_CONFIG_HASH: fce608f58cf010b5b5d11717aea9cf11
2020-03-05T13:04:19Z [â¿]  Downloading kernel module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.17.1-x86_64-4.12.14-95.45-default-fce608f58cf010b5b5d11717aea9cf11.ko
2020-03-05T13:04:19Z [â]  Error fetching module: Get "https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.17.1-x86_64-4.12.14-95.45-default-fce608f58cf010b5b5d11717aea9cf11.ko": x509: certificate signed by unknown authority
2020-03-05T13:04:19Z [â]  Error opening kernel module: /falco-probe.ko
2020-03-05T13:04:19Z [â]  Error loading module: open /falco-probe.ko: no such file or directory

**Comment by saiharshitachava** [comment]
Please let me know how do I build my own probe and change the values of this amazon link..
* Trying to find precompiled falco-probe for 4.12.14-95.45-default
Found kernel config at /proc/config.gz
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.19.0-x86_64-4.12.14-95.45-default-fce608f58cf010b5b5d11717aea9cf11.ko

I tried giving FALCOCTL_FALCO_PROBE_REPO in the env varibales of falco pod and doesnt seem to work clearly

**Comment by nibalizer** [comment]
I believe I have the same issue. Comes up fine with 0.19, fails with 0.20 (installed via helm)

0.20 run:

```
nibz@nuc:~/projects/falco/helm/charts/stable/falco$ kubectl logs x-falco-6c62d
* Setting up /usr/src links from host
ln: failed to create symbolic link '/usr/src//host/usr/src/linux-headers-4.15.0-88': No such file or directory
ln: failed to create symbolic link '/usr/src//host/usr/src/linux-headers-4.15.0-88-generic': No such file or directory * Unloading falco-probe, if present
* Running dkms install for falco
Error! echo
Your kernel headers for kernel 4.15.0-88-generic cannot be found at
/lib/modules/4.15.0-88-generic/build or /lib/modules/4.15.0-88-generic/source.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/0.20.0+d77080a/build/make.log
* Trying to load a system falco-probe, if present
* Trying to find precompiled falco-probe for 4.15.0-88-generic
Found kernel config at /host/boot/config-4.15.0-88-generic
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.20.0%2Bd77080a-x86_64-4.15.0-88-generic-9be178907bab2d3ed55177058501653b.ko
curl: (22) The requested URL returned error: 404 Not Found
Download failed, consider compiling your own falco-probe and loading it or getting in touch with the Falco community   Mon Mar  9 16:10:45 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Mon Mar  9 16:10:45 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Mon Mar  9 16:10:46 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Mon Mar  9 16:10:47 2020: Unable to load the driver. Exiting.
Mon Mar  9 16:10:47 2020: Runtime error: error opening device /dev/falco0. Make sure you have root credentials and that the falco-probe module is loaded.. Exiting.
```


0.19 run:

```
nibz@nuc:~/projects/falco/helm/charts/stable/falco$ kubectl logs x-falco-4mj8j
* Setting up /usr/src links from host
* Unloading falco-probe, if present
* Running dkms install for falco

Creating symlink /var/lib/dkms/falco/0.19.0/source ->
                 /usr/src/falco-0.19.0

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make -j4 KERNELRELEASE=4.15.0-88-generic -C /lib/modules/4.15.0-88-generic/build M=/var/lib/dkms/falco/0.19.0/build.............
cleaning build area....

DKMS: build completed.

falco-probe.ko:
Running module version sanity check.
modinfo: ERROR: missing module or filename.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.15.0-88-generic/kernel/extra/
mkdir: cannot create directory '/lib/modules/4.15.0-88-generic/kernel/extra': Read-only file system
cp: cannot create regular file '/lib/modules/4.15.0-88-generic/kernel/extra/falco-probe.ko': No such file or directory 
depmod...

DKMS: install completed.
* Trying to load a dkms falco-probe, if present
falco-probe found and loaded in dkms
Mon Mar  9 16:12:29 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Mon Mar  9 16:12:29 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Mon Mar  9 16:12:30 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Mon Mar  9 16:12:32 2020: Starting internal webserver, listening on port 8765
16:17:35.197941255: Critical Falco internal: syscall event drop. 1 system calls dropped in last second. (ebpf_enabled=0 n_drops=1 n_drops_buffer=1 n_drops_bug=0 n_drops_pf=0 n_evts=4535)
16:18:38.266212729: Critical Falco internal: syscall event drop. 1 system calls dropped in last second. (ebpf_enabled=0 n_drops=1 n_drops_buffer=1 n_drops_bug=0 n_drops_pf=0 n_evts=7954)
16:24:38.696088641: Critical Falco internal: syscall event drop. 2 system calls dropped in last second. (ebpf_enabled=0 n_drops=2 n_drops_buffer=2 n_drops_bug=0 n_drops_pf=0 n_evts=7808)
16:28:38.987648286: Critical Falco internal: syscall event drop. 1 system calls dropped in last second. (ebpf_enabled=0 n_drops=1 n_drops_buffer=1 n_drops_bug=0 n_drops_pf=0 n_evts=4558)
nibz@nuc:~/projects/falco/helm/charts/stable/falco$ kubectl get pod
NAME            READY   STATUS    RESTARTS   AGE
x-falco-4mj8j   1/1     Running   0          41m
x-falco-v7b9c   1/1     Running   0          41m
x-falco-x2w84   1/1     Running   0          41m
nibz@nuc:~/projects/falco/helm/charts/stable/falco$ kubectl exec -it x-falco-4mj8j /bin/bash
uroot@x-falco-4mj8j:/# uname -a
Linux x-falco-4mj8j 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 GNU/Linux
root@x-falco-4mj8j:/# exit```

**Comment by saiharshitachava** [comment]
My issue is different ..It dosnt come up in 0.19.0 as well..
I guess I need to build my custom probe..Could someone help with the steps..
I have already taken the file underkernel/probeloader and built an image and tried and that doesnt seem to work as well..

**Comment by fntlnz** [comment]
@saiharshitachava Hi, thanks for opening this! Please take a look at this comment here https://github.com/falcosecurity/falco/issues/1078#issuecomment-596676168

If that doesn't work, here are the instructions to build a custom probe falco.org/docs/source/

**Comment by leodido** [comment]
The current _development_ version of Falco (the one which commits are on the master) branch does not have anymore the bug about symbolic linking (ie. `ln: failed to create symbolic link '/usr/src//host/usr/src/packages'`).

Could you please try it?

Those _development_ versions can be found [here for deb packages](https://bintray.com/falcosecurity/deb-dev) or [here for rpm packages](https://bintray.com/falcosecurity/rpm-dev). Installation instructions [here](https://falco.org/docs/installation/#centos-rhel-amazon-linux).



Otherwise, you can use the `falcosecurity/falco:master` docker image.

**Comment by vanneback** [comment]
The master branch fixed this problem for me. Any plan to release a patch or when is the next release planned?

**Comment by fntlnz** [comment]
@vanneback @saiharshitachava   0.22.0 was just released containing the fix for this issue
