### ISSUE TITLE
Invalid Field Used in Rules File (tag -> tags)

### ISSUE THREAD

**Issue by ossie-git** [falcosecurity/falco#1082]
I noticed that there are 7 rules in [falco_rules.yaml](https://github.com/falcosecurity/falco/blob/dev/rules/falco_rules.yaml) that use the **tag** field instead of **tags**. For example:

![screen](https://user-images.githubusercontent.com/25382296/76283931-055ee680-62f0-11ea-80a3-919a88a7b8b5.png)

I'm guessing that this wasn't intended as it makes no sense to have both tag and tags fields and the [official documentation](https://falco.org/docs/rules/) only mentions the **tags** field. This also probably means that if a user uses the -T or -t options when running Falco, this won't impact these rules (I haven't had the time to verify this)

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by fntlnz** [comment]
Thanks for your contribution  @ossie-git !!

Looks like @vicenteherrera was already working on this and fixed it in #1081 - closing this since it’s fixed but feel free to continue the discussion and reopen  if anything comes up 

/close

**Comment by vicenteherrera** [comment]
I wasn't aware of this issue, checked them before it was posted. Grateful to finally have sent the PR, just in time ;-)
