### ISSUE TITLE
Rename kernel module from falco-probe.ko to falco.ko

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco#1083]
**Motivation**

Due to the [branding changes clarification](https://github.com/falcosecurity/falco/tree/master/brand#module), the kernel module should be renamed to `falco.ko` instead of the current `falco-probe.ko`. 
Furthermore, new tools like [driverkit](https://github.com/falcosecurity/driverkit) are already using the new name. cc @leodido @fntlnz 

**Feature**

Rename the kernel module from `falco-probe.ko` to `falco.ko`.

**Alternatives**

**Additional context**

**Comment by leodido** [comment]
Done by #1158 

/close
