### ISSUE TITLE
Instructions for building release branches are incomplete

### ISSUE THREAD

**Issue by smijolovic** [falcosecurity/falco#1085]
Instructions work to build the falco binary when pulling from master, but not from stable release branches. When building binaries to use in production environments, it's more appropriate to pull from a stable release branch. The cmake instructions do not cover this scenario.

Recommend adding additional cmake instructions for a build of a release branch (RHEL/CENTOS):

cmake -DFALCO_VERSION=0.20.0 -DFALCO_VERSION_MAJOR=0 -DFALCO_VERSION_MINOR=20 -DFALCO_VERSION_PATCH=0 -DBUILD_BPF=True -DCMAKE_VERBOSE_MAKEFILE=On -DCMAKE_BUILD_TYPE=Release -DUSE_BUNDLED_DEPS=ON ..

In addition, building the bpf driver requires the kernel-devel package which is not clear in the docs - it just shows llvm and clang.

**Comment by fntlnz** [comment]
Stalebot please keep
