### ISSUE TITLE
0.20.0 Probe issue due to typo?  /usr/src//host/usr/src/debug  or   /usr/src//host/usr/src/kernels

### ISSUE THREAD

**Issue by ssurovich** [falcosecurity/falco#1094]
**Describe the bug**

Spinning up a new daemonset on CentOS8 workers.  The probe fails to build due to what appears to be a type in the Falco release.   I could be wrong, but it looks like a space is missing, assuming the output is correct?

ln: failed to create symbolic link '/usr/src//host/usr/src/debug': No such file or directory
ln: failed to create symbolic link '/usr/src//host/usr/src/kernels': No such file or directory

Running a DS using version 0.19.0 works without any issues.

**How to reproduce it**

Deploy a DS using the :latest tag for Falco on CentOS8

**Expected behaviour**

A working pod that creates the probe using the host mounted /usr/src

**Environment**

- Falco version:
0.20.0
- System info:
CentOS8
5.5.4-1.el7.elrepo.x86_64
- Installation method:
K8s

** Additional Information **
The Hosts all have a /usr/src/kernels with the correct header release

[root@home-k8s-worker1 ~]# ls -la /usr/src/kernels/
total 12
drwxr-xr-x.  5 root root  108 Feb 18 09:44 .
drwxr-xr-x.  4 root root   34 Jun 13  2018 ..
drwxr-xr-x. 22 root root 4096 Sep 24 11:15 3.10.0-1062.1.1.el7.x86_64
drwxr-xr-x. 22 root root 4096 Feb 18 09:45 3.10.0-1062.12.1.el7.x86_64
**drwxr-xr-x. 22 root root 4096 Feb 18 09:17 5.5.4-1.el7.elrepo.x86_64**

**Comment by leodido** [comment]
Can you please try with the new 0.21.0 version?

https://github.com/falcosecurity/falco/pull/981 should have solved this issue

**Comment by ssurovich** [comment]
@leodido Looks like it fixed the double / issue - Im failing on the DKMS build now, but Im sure thats a system config on my nodes (Howevere 0.19 runs without any issues) - Ill look into the build issue later today or tomorrow.   But the initial issue is resolved.  Thanks for the update.

**Comment by leodido** [comment]
Closing this since the exact bug is resolved as verified.

Feel free to file a new one if you still have other issues, thanks :)

/close
