### ISSUE TITLE
Falco audit rules not working for Azure kubernetes Service

### ISSUE THREAD

**Issue by prakash1097** [falcosecurity/falco#1095]
We have deployed the Falco k8s_audit_rules.yaml. After the deployment, It seems only the falco_rules.yaml section is working.
These are some falco rules that are working.

1. Log files were tampered
2. Shell history had been deleted or renamed
3. Privileged container started
4. Error File below / or /root opened for writing
5. Notice A shell was spawned in a container with an attached terminal
6. A shell configuration file has been modified
7. Docker or kubernetes client executed in container
8. Unexpected connection to K8s API Server from container

But for K8s-audit rules, the most important rules are as follows and they doesn't seem to be working.

1. Detect any attempt to create a namespace outside of a set of known namespaces
2. Detect any attempt to create a pod in the kube-system or kube-public namespaces
3. Detect any attempt to create a serviceaccount in the kube-system or kube-public namespaces
4. Detect any attempt to modify/delete a ClusterRole/Role starting with system
5. Detect any attempt to create a ClusterRoleBinding to the cluster-admin user
6. Detect any attempt to create a Role/ClusterRole with wildcard resources or verbs
7. Detect any attempt to create a Role/ClusterRole that can perform write-related actions
8. Detect any attempt to create a Role/ClusterRole that can exec to pods
9. Detect any attempt to create a deployment
10. Detect any attempt to delete a deployment
11. Detect any attempt to create a service
12. Detect any attempt to delete a service
13. Detect any attempt to create a configmap
14. Detect any attempt to delete a configmap
15. Detect any attempt to create a namespace
16. Detect any attempt to delete a namespace
17. Detect any attempt to create a service account
18. Detect any attempt to delete a service account
19. Detect any attempt to create a cluster role/role
20. Detect any attempt to delete a cluster role/role
21. Detect any attempt to create a clusterrolebinding
22. Detect any attempt to delete a clusterrolebinding

Provide me some documentations with respect to Azure Kubernetes Service. I've tried to deploy the audit enabling yaml as well as Webhook config. those also doesn't seem to be working.

**Comment by prakash1097** [comment]
How do i add label?

**Comment by pbalajiips** [comment]
Hi @prakash1097 is there any update on this?
