### ISSUE TITLE
Falco gets SIGFPE  when compiled against the system libgrpc in Ubuntu Bionic

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falco#1096]
**Describe the bug**
Originally reported by @ldegio in the Falco slack

```
falco # ./falco -r ../../../rules/falco_rules.yaml 
Sat Mar 14 10:23:54 2020: Falco initialized with configuration file /home/loris/git/falco/falco.yaml
Sat Mar 14 10:23:54 2020: Loading rules from file ../../../rules/falco_rules.yaml:
Floating point exception (core dumped)
```

**How to reproduce it**
- Spawn an Ubuntu Bionic machine or container
- Follow the build instructions on the Falco website https://falco.org/docs/source/
- Start falco

**Expected behaviour**
Falco just works as expected, starts everything and gives outputs on events.

**Screenshots**

**Environment**

**Additional context**

Similar issue about this on the gRPC repo: https://github.com/grpc/grpc/issues/21989

**Comment by pauldotknopf** [comment]
Bump

**Comment by leodido** [comment]
We've verified the build (with system dependencies) of Falco on an Ubuntu Bionic, and we confirm the bug exists.

It depends on the version of gRPC that Ubuntu Bionic ships (1.3.x). At least gRPC 1.8.1 required.

Nevertheless, it should be possible to build Falco on Ubuntu Bionic with (most of) the dependencies statically bundled. To do so use

```
mkdir -p build && cd build
cmake USE_BUNDLED_DEPS=ON ..
make -j16 falco
```

**Comment by fntlnz** [comment]
I would not call this a bug, it's just that the grpc dependencies on Ubuntu 18.04 are too old. There's really nothing we can do, if people want to build Falco on 18.04 they are going to need to build with the flag @leodido was mentioning, otherwise they will need to install a newer gRPC version of their system in an unofficial way.

I'm closing this since there's really nothing we as a project can do for this.

**Comment by brant-ruan** [comment]
> We've verified the build (with system dependencies) of Falco on an Ubuntu Bionic, and we confirm the bug exists.
> 
> It depends on the version of gRPC that Ubuntu Bionic ships (1.3.x). At least gRPC 1.8.1 required.
> 
> Nevertheless, it should be possible to build Falco on Ubuntu Bionic with (most of) the dependencies statically bundled. To do so use
> 
> ```
> mkdir -p build && cd build
> cmake USE_BUNDLED_DEPS=ON ..
> make -j16 falco
> ```

In my envrionment commands above do not make effect, the same floating point exception occurs. So could you please give a recommended developing&building envrionment?

**Comment by leodido** [comment]
@brant-ruan you're right

the command is:

```
cmake -DUSE_BUNDLED_DEPS=ON ...
```

**Comment by brant-ruan** [comment]
> @brant-ruan you're right
> 
> the command is:
> 
> ```
> cmake -DUSE_BUNDLED_DEPS=ON ...
> ```

Thanks :)
