### ISSUE TITLE
Event generator hosted on sysdig image registry

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falco#1108]
**Describe the bug**

Currently according to our [docs](https://falco.org/docs/event-sources/sample-events/#docker-image) and the [image registry itself](https://hub.docker.com/r/sysdig/falco-event-generator/tags) the `events_generator` image lives in the `sysdig` image registry. 

As a CNCF open source project, we should move this image over to the official `falco` registry which is owned and operated by the Falco community. 

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by kris-nova** [comment]
Related to #1019

**Comment by kris-nova** [comment]
Discovered while patching this https://github.com/falcosecurity/falco-website/pull/168

**Comment by leodido** [comment]
It has been moved to https://hub.docker.com/repository/docker/falcosecurity/falco-event-generator by @mstemm if I'm not wrong

Anyway, this whole thing is related to #1089 imho (moving it out of falco repo into another falcosecurity project?)

**Comment by kris-nova** [comment]
Thanks for the info @leodido 

This issue will be closed by falcosecurity/falco-website#168 now
