### ISSUE TITLE
Installing Falco Issue

### ISSUE THREAD

**Issue by JScrivanich** [falcosecurity/falco#1110]
Hi,

So we wanted to test out this released feature: https://github.com/falcosecurity/falco/pull/1099

We followed the install instructions and ran the following commands

```
sudo rpm --import https://falco.org/repo/falcosecurity-3672BA8F.asc
sudo curl -s -o /etc/yum.repos.d/falcosecurity.repo https://falco.org/repo/falcosecurity-rpm-dev.repo
sudo yum -y install kernel-devel-$(uname -r)
sudo yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
sudo yum -y install falco
```

Our issue here is that when we run `yum -y install falco` it tries to install three dependencies.  2 of them get installed successfully but the `falco-0.21.0_7+7b44aaf-1.x86_64` dependency in the path `/usr/src/` does not.

We get this error:
```
Error! Could not find module source directory.
Directory: /usr/src/falco-0.21.0-7+7b44aaf does not exist.
```

So I think I ended up figuring it out.  the directory mentioned in /usr/src/ IS there but it has a different name.  Instead of it being named falco-version (in this case `falco-0.21.0-7+7b44aaf`)  its named `falco-be1ea2d9482d0e6e2cb14a0fd7e08cbecf517f94`.  I believe this is our issue.  its trying to find `/usr/src/falco-0.21.0-7+7b44aaf` when installing but for some reason, that doesn’t exist--instead the directory is `/usr/src/falco-be1ea2d9482d0e6e2cb14a0fd7e08cbecf517f94` which is why this is failing.

So it looks like whatever script pulls down falco and puts it in /usr/src/ names it incorrectly.  Is this something you guys can look into?

**Comment by fntlnz** [comment]
Hey @JScrivanich thanks for bringing this up!

This is going to be solved by https://github.com/falcosecurity/falco/issues/1110

Mind that the program will be called `falco-driver-loader`
