### ISSUE TITLE
Doesn't support Latest EKS 1.15 Amazon Linux 2 Kernel version (4.14.171-136.231.amzn2.x86_64)

### ISSUE THREAD

**Issue by jonahjon** [falcosecurity/falco#1113]
**Describe the bug**
Falco Doesn't have support for newest Amazon Linux 2 Kernel version (4.14.171-136.231.amzn2.x86_64)  on https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/index.html

Falco won't install using newest version of Amazon Linux on EKS 1.15

**How to reproduce it**
`helm install falco`
```
Your kernel headers for kernel 4.14.171-136.231.amzn2.x86_64 cannot be found at
/lib/modules/4.14.171-136.231.amzn2.x86_64/build or /lib/modules/4.14.171-136.231.amzn2.x86_64/source.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/0.17.1/build/make.log
* Trying to load a system falco-probe, if present
* Trying to find precompiled falco-probe for 4.14.171-136.231.amzn2.x86_64
Found kernel config at /host/boot/config-4.14.171-136.231.amzn2.x86_64
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.17.1-x86_64-4.14.171-136.231.amzn2.x86_64-78f4a80ab924074f1be6b2bc0a6cc401.ko
curl: (22) The requested URL returned error: 404 Not Found
Download failed, consider compiling your own falco-probe and loading it or getting in touch with the sysdig community
```

`helm install falco`

**Expected behaviour**
It should launch

**Screenshots**

**Environment**

- Falco version: 0.21.0, 0.18.0, 0.17.1, 0.17.0

- System info: AWS EKS Amazon Linux 2 https://github.com/awslabs/amazon-eks-ami

- Cloud provider or hardware configuration: AWS EKS
- OS: Amazon Linux 2

- Kernel:  4.14.171-136.231.amzn2.x86_64

- Installation method: Helm and manually replicated Dockerfile apt-get steps in seperate container

**Additional context**

**Comment by fntlnz** [comment]
Thanks for opening this issue @jonahjon - having a good user experience on Amazon Linux is very important for Falco. We are now switching from the legacy driver build infrastructure to driverkit, this is why some things are not working well right now and ultimately why you are hitting this issue . @leodido opened an issue on driverkit to fix this so we can prioritize that now https://github.com/falcosecurity/driverkit/issues/41

Moreover, our community expressed a lot of interest in Amazon Linux support in the survey [here](https://docs.google.com/spreadsheets/d/1TKJIXAMWPRTb8x—Kkq17ipee8xvV08LFLfBN3VzLNU) 

Amazon Linux is in the top 4 choices.

**Comment by jonahjon** [comment]
Thanks for the quick response @fntlnz , working on some steps now to make this working by specifying an older Kernel EKS-AMI image... will update with work-around if successful.

**Comment by jonahjon** [comment]
1. Go and find the lowest kernal Version for the EKS version you are using .

1.14.7-20190927 | 1.14.7 | 18.06.1-ce | 4.14.146 | v20190927
-- | -- | -- | -- | --

https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/eks-linux-ami-versions.md
I used kernel version **4.14.146** for version **1.14** of EKS

2. Verify the version is supported on the Falco Probe version you are looking to download
https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/index.html
I found it under listed for 0.17.1
`falco-probe-0.17.1-x86_64-4.14.146-120.181.amzn2.x86_64-78c7dcf4ded9d7112216d1cd3af56c83.ko`

3. find the AMI ID for that image, and make sure your worker nodes are launched with that AMI
```
aws ec2 describe-images \
    --region us-east-2 \
    --filters \
        Name=owner-id,Values=602401143452 \
        Name=is-public,Values=true \
        Name=name,Values=\*eks\* \
    --output table \
    --query 'Images[*].{CreationDate:CreationDate,Name:Name,ID:ImageId}'
```

4. Use the the supported version from Step 2 we verified in your lauch

Add `--set image.tag=0.17.1` to your Helm command 
Change the image in the daemonset.yaml to the tag version you select` falcosecurity/falco:0.17.1`

**Comment by fntlnz** [comment]
Thanks a lot  for sharing the steps @jonahjon - will post here once we have some updates on the driverkit side.

**Comment by sekka1** [comment]
Just ran into this issue as well.  In what release will this update be included in?

**Comment by jonahjon** [comment]
Fixed on https://github.com/falcosecurity/driverkit/pull/44
