### ISSUE TITLE
The root_dir macro matches /root123abc

### ISSUE THREAD

**Issue by sporkmonger** [falcosecurity/falco#1141]
The `root_dir` macro is currently defined as:

```
- macro: root_dir
  condition: ((fd.directory=/ or fd.name startswith /root) and fd.name contains "/")
```

Unfortunately, this matches on any `fd.name` beginning with the word "root", even if that's not a sensitive location. This is triggering a number of alerts for containers that place files in locations like `/rootDir` and similar, causing them to be misclassified as sensitive.

To reproduce, create a container with a directory named `/rootDir` or `/root123abc` and modify a file within one of those locations. Falco will report "File below / or /root opened for writing".

Only files immediately under `/` and `/root` should match this macro.

- Falco version: 0.21.0
- System info:
{
  "machine": "x86_64",
  "nodename": "[redacted]",
  "release": "4.15.0-1065-aws",
  "sysname": "Linux",
  "version": "#69-Ubuntu SMP Thu Mar 26 02:17:29 UTC 2020"
}
- Cloud provider or hardware configuration: AWS
- OS:
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel: 4.15.0-1065-aws
- Installation method: DEB

**Comment by leogr** [comment]
I've made a PR to fix this issue :point_right: #1279
/assign
/milestone 0.24.0
