### ISSUE TITLE
404 on pre~compiled kernel probes

### ISSUE THREAD

**Issue by chan-maddanna** [falcosecurity/falco#1163]
**Describe the bug**

with the recent divorce of falco team with sysdig, all the hosted pre~compiled probes are now gone. This is an existing bug, that has been reported multiple times more or less, for different probes (ex: https://github.com/falcosecurity/falco/issues/1019 ).

Unfortunately We cannot compile these probes in this particular environment, as we are in a very restrictive/secure setup. Hence, being responsible & not to bother you guys too much, I have been waiting and trying week after week. 

Hence, would appreciate making the needed probe (described below) available please. The probe we really need is : https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-a259b4bf49c3330d9ad6c3eed9eb1a31954259a6-x86_64-4.14.171-136.231.amzn2.x86_64-78f4a80ab924074f1be6b2bc0a6cc401.ko  (gives a 404)

**How to reproduce it**

Try your own installation procedure (https://falco.org/docs/installation/) using DaemonSet Manifests on any aws linux node hosted kubernetes pods. I have tried with couple of centos/debian and other pods. The one we really need is for CentOS 7 pod on underlying AWS2 linux X86_64 node

**Expected behaviour**

Would expect a basic clean installation. 

**Screenshots**

![image](https://user-images.githubusercontent.com/34686903/80247791-a7d2ef00-863c-11ea-9433-cdf25f0456aa.png)

![image](https://user-images.githubusercontent.com/34686903/80247275-c684b600-863b-11ea-9e5e-0199548784f6.png)

Amazon Kubernetes cluster - *Nodes* run Amazon Linux 2 (amzn2.x86_64) 
*Centos 7 based pods* on k8s(Docker containers). 

- Falco version:
Failed install - cannot run "falco --version".
- System info:
Failed install - cannot run  "falco --support | jq .system_info" 
- Cloud provider or hardware configuration:
AWS AKS cluster 
- OS:
node : amzn2.x86_64
- Kernel:
4.14.171-136.231.amzn2.x86_64

- Installation method:
https://falco.org/docs/installation/ using DaemonSet Manifests

**Additional context**

**Comment by leodido** [comment]
Hello @chan-maddanna we implemented our own open **drivers build grid** in https://github.com/falcosecurity/test-infra repository.

And started providing again a set of prebuilt kernel modules. They are located at https://dl.bintray.com/falcosecurity/driver/

The `falco-driver-loader script` (entrypoint of the docker images) has already been updated to look for modules and probes at the new location. 

For example this is the module you are looking for: https://dl.bintray.com/falcosecurity/driver/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/:falco_amazonlinux2_4.14.171-136.231.amzn2.x86_64_1.ko

**Comment by leodido** [comment]
Closing this since I think it is resolved.

Feel free to continue the discussion anyway

/close

**Comment by chan-maddanna** [comment]
> Hello @chan-maddanna we implemented our own open **drivers build grid** in https://github.com/falcosecurity/test-infra repository.
> 
> And started providing again a set of prebuilt kernel modules. They are located at https://dl.bintray.com/falcosecurity/driver/
> 
> The `falco-driver-loader script` (entrypoint of the docker images) has already been updated to look for modules and probes at the new location.
> 
> For example this is the module you are looking for: https://dl.bintray.com/falcosecurity/driver/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/:falco_amazonlinux2_4.14.171-136.231.amzn2.x86_64_1.ko

Thanks Leo
