### ISSUE TITLE
ADOPTERS improvements

### ISSUE THREAD

**Issue by leodido** [falcosecurity/falco#1169]
**What to document**

Why already have ADOPTERS documented as a markdown document in [https://github.com/falcosecurity/falco/blob/master/ADOPTERS.md](ADOPTERS.md).

We need to document:
- what classifies someone as an ADOPTER
- what classifies someone as a VENDOR (maybe?)

So, the todo list is:
- [ ] documentation about being list as an ADOPTER here (and, consequently, on the falco.org)
- [ ] translate the MD file to a YAML one to make it more consumable (I hate to say this but I have too)

**Comment by fntlnz** [comment]
Yay! More YAML

**Comment by kris-nova** [comment]
we also need an issue so this will be reflected on the website
