### ISSUE TITLE
Unable to curl or wget binary tarballs

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falco#1179]
**Describe the bug**

Unable to download Falco binaries from bintray using curl or wget

**How to reproduce it**

Going to the falcosecurity org in bintray I navigated to [X86_64 Falco 0.22.1 binary download page](https://dl.bintray.com/falcosecurity/bin/x86_64/).

Find the version of Falco you wish to download and copy the link

```
https://dl.bintray.com/falcosecurity/bin/x86_64/:falco-0.22.1-x86_64.tar.gz
```

Then try to pull down on a server.

```
[novix@novix-alice]: ~/src>$ wget https://dl.bintray.com/falcosecurity/bin/x86_64/:falco-0.22.1-x86_64.tar.gz
--2020-04-25 12:39:52--  https://dl.bintray.com/falcosecurity/bin/x86_64/:falco-0.22.1-x86_64.tar.gz
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving dl.bintray.com (dl.bintray.com)... 52.26.64.218, 52.11.170.179
Connecting to dl.bintray.com (dl.bintray.com)|52.26.64.218|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-04-25 12:39:52 ERROR 404: Not Found.

[novix@novix-alice]: ~/src>$ curl https://dl.bintray.com/falcosecurity/bin/x86_64/:falco-0.22.1-x86_64.tar.gz
The requested path was not found.[novix@novix-alice]: ~/src>$ 
[novix@novix-alice]: ~/src>$ curl -Ssl https://dl.bintray.com/falcosecurity/bin/x86_64/:falco-0.22.1-x86_64.tar.gz
The requested path was not found.[novix@novix-alice]: ~/src>$ curl -Ssl https://dl.bintray.com/falcosecurity/bin/x86_64/falco-0.22.1-x86_64.tar.gz
[novix@novix-alice]: ~/src>$ ls
auracle-git/  pacaur/  zfs-0.8.3/  zfs-0.8.3.tar.gz
[novix@novix-alice]: ~/src>$ ^C

```

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by kris-nova** [comment]
You can adjust the URL by removing the colon in the path.

Change
```
https://dl.bintray.com/falcosecurity/bin/x86_64/:falco-0.22.1-x86_64.tar.gz
```

to

```
https://dl.bintray.com/falcosecurity/bin/x86_64/falco-0.22.1-x86_64.tar.gz
```

**Comment by kris-nova** [comment]
Reopining - wondering if this can be fixed in the build process.

**Comment by leodido** [comment]
This is probably a bug in that bintray UI. Or a change they introduced in the past few days because the colon (:) was not there until two days ago.

Thanks for reporting this.

Anyway, the page for manual downloads is at https://bintray.com/falcosecurity/bin/falco/0.22.1

There you can click on "Files" and on the file and it downloads correctly. Or you can curl/wget https://bintray.com/falcosecurity/bin/download_file?file_path=x86_64%2Ffalco-0.22.1-x86_64.tar.gz

**Comment by leodido** [comment]
Proposed fix:

if the download of the driver from `https://dl.bintray.com/falcosecurity/bin/x86_64/:falco-${FALCO_VERSION}-x86_64.tar.gz` fails, fallback to

`https://bintray.com/falcosecurity/bin/download_file?file_path=x86_64%2Ffalco-${FALCO_VERSION}-x86_64.tar.gz`

**Comment by leodido** [comment]
At the moment, it seems a bintray bug to me because a colon is present before the filename for all the repositories type (deb, rpm, generic, etc.).

**Comment by fntlnz** [comment]
This is out of our control.
