### ISSUE TITLE
Falco JSON logs and forwarding - not working?

### ISSUE THREAD

**Issue by robotica72** [falcosecurity/falco#1194]
**Describe the bug**
Im not sure this has anything to do with Falco, but I have the same issue with two different log forwarding systems - so I wanted to start here for any ideas.

I can forward Falco events without any issues if I do not enable JSON output - but once JSON output is enabled, the events fail to forward to the logging system(s).  The output in the Falco pod looks fine, which is why I cant imagine this is a Falco issue, but as I mentioned, hoping someone has an idea.

One system is a standard EFK and the other is using Splunk (Which essentially uses FluentD as the forwarder, so that is a common link).

Tested using Falco 0.22.1, all the way down to 0.19.0 - the same with all attempts.

Any ideas??  Ive been trying a ton of different things - different FluentD releases / etc ...

Not related, but I have Falcosidekick forwarding the logs to ES without any issue.

Enable JSON output, restart the Falco pods.

Expect to see events in the logging systems that are receiving the forwarded events.

**Comment by leogr** [comment]
Hi @robotica72 

Not sure I understood your issue. 
Could you attach more details pls?
Steps to reproduce the bug, pod logs, OS versions, etc..

Thanks in advance!

**Comment by robotica72** [comment]
Hi @leogr - Sorry about that, didnt want to send too much if it wasnt something that shouldnt be in the Falco issues.

Ok - Running a plain K8s install on 1.18.2, Running on Ubuntu 18.04 - 4.15.0-99-generic.

Falco.yaml is set to output JSON, rest of the file is the source from Git.

Falco does output events as expected:

Thu May  7 19:13:13 2020: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Thu May  7 19:13:14 2020: Starting internal webserver, listening on port 8765
{"output":"19:13:23.640715614: Notice Unexpected connection to K8s API Server from container (command=calico k8s.ns=<NA> k8s.pod=<NA> container=9a3d0ecf2af9 image=<NA>:<NA> connection=172.18.0.3:42084->10.96.0.1:443) k8s.ns=<NA> k8s.pod=<NA> container=9a3d0ecf2af9 k8s.ns=<NA> k8s.pod=<NA> container=9a3d0ecf2af9","priority":"Notice","rule":"Contact K8S API Server From Container","time":"2020-05-07T19:13:23.640715614Z", "output_fields": {"container.id":"9a3d0ecf2af9","container.image.repository":null,"container.image.tag":null,"evt.time":1588878803640715614,"fd.name":"172.18.0.3:42084->10.96.0.1:443","k8s.ns.name":null,"k8s.pod.name":null,"proc.cmdline":"calico"}}

I say as expected but I see a lot of null values, so thats a different question.

FluentD has the standard fluent-elasticsearch config from the K8s repo.

What I see is that ES (through Kibana) that the Falco log output of plain text is in ES - but as soon as the JSON output starts in the logs, there is nothing in ES.

I was going to just implement Falcosidekick for this particular use-case but it didnt seem to have all of the data in the index - But looking at the example output above, It may have been due to the null values.   I can use sidekick, but preferred to see native forwarding working.

If I have to go with sidekick, are the same values sent to ES - So, should I expect to see the same data in my Falco index that I would if forwarding was working with FluentD?

Thanks!

**Comment by leogr** [comment]
Please, keep

**Comment by leodido** [comment]
/help

(this adds "help wanted" label that keeps the stale bot away)

**Comment by roshpr** [comment]
> Hi @leogr - Sorry about that, didnt want to send too much if it wasnt something that shouldnt be in the Falco issues.
> 
> Ok - Running a plain K8s install on 1.18.2, Running on Ubuntu 18.04 - 4.15.0-99-generic.
> Falco: 0.22.1 (Also tried a few versions below, 0.21, 0.20, 0.19)
> 
> Kernel module built using driverkit - no issues.
> 
> Falco.yaml is set to output JSON, rest of the file is the source from Git.
> 
> Falco does output events as expected:
> 
> Thu May 7 19:13:13 2020: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
> Thu May 7 19:13:14 2020: Starting internal webserver, listening on port 8765
> {"output":"19:13:23.640715614: Notice Unexpected connection to K8s API Server from container (command=calico k8s.ns= k8s.pod= container=9a3d0ecf2af9 image=: connection=172.18.0.3:42084->10.96.0.1:443) k8s.ns= k8s.pod= container=9a3d0ecf2af9 k8s.ns= k8s.pod= container=9a3d0ecf2af9","priority":"Notice","rule":"Contact K8S API Server From Container","time":"2020-05-07T19:13:23.640715614Z", "output_fields": {"container.id":"9a3d0ecf2af9","container.image.repository":null,"container.image.tag":null,"evt.time":1588878803640715614,"fd.name":"172.18.0.3:42084->10.96.0.1:443","k8s.ns.name":null,"k8s.pod.name":null,"proc.cmdline":"calico"}}
> 
> I say as expected but I see a lot of null values, so thats a different question.
> 
> FluentD has the standard fluent-elasticsearch config from the K8s repo.
> 
> What I see is that ES (through Kibana) that the Falco log output of plain text is in ES - but as soon as the JSON output starts in the logs, there is nothing in ES.
> 
> I was going to just implement Falcosidekick for this particular use-case but it didnt seem to have all of the data in the index - But looking at the example output above, It may have been due to the null values. I can use sidekick, but preferred to see native forwarding working.
> 
> If I have to go with sidekick, are the same values sent to ES - So, should I expect to see the same data in my Falco index that I would if forwarding was working with FluentD?
> 
> Thanks!

Hi, did you find a fix for this. I'm facing similar issue. Any info will be helpful.
