### ISSUE TITLE
falco-driver-loader and stable docker images need `/etc` to be mounted

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco#1203]
**What to document**

Since [`falco-driver-loader` from current master tries to infer the driver target from various files in `/etc`](https://github.com/falcosecurity/falco/blob/a520a9b666528bd889bcec2666362c0920bbdc9f/scripts/falco-driver-loader#L104), `falcosecurity/falco:lastest` and `falcosecurity/falco-driver-loader` images need the host `/etc` to be mounted to `/host/etc` inside the container (e.g `-v /etc:/host/etc:ro`).

We have to document this.

There's already another issue related to this: https://github.com/falcosecurity/falco/issues/1188#issuecomment-627312495

Furthermore, many installations and third-party integrations may be affected (eg. the [helm chart](https://github.com/helm/charts/blob/11465c8be7ad5bee3b08553038aa5695d444cafd/stable/falco/templates/daemonset.yaml#L118)).
helm chart? cc @nestorsalceda @bencer @nibalizer 
contrib? cc @maxgio92 

TODOs:
- [x] website :point_right: https://falco.org/docs/running/#docker
- [x] former helm chart :point_right: https://github.com/helm/charts/pull/22474
- [x] new helm chart :point_right:  https://github.com/falcosecurity/charts/pull/10
- [x] contrib daemonset privileged :point_right: https://github.com/falcosecurity/contrib/blob/3ca3b9c6f45f6a1d57db51afd38b395c96816c84/deploy/kubernetes/kernel-and-k8s-audit/daemonset.yaml#L53
- [x] contrib daemonset least privileged :point_right: https://github.com/falcosecurity/contrib/blob/master/deploy/kubernetes/kernel-and-k8s-audit/daemonset-least-privilege.yaml#L68

**Comment by maxgio92** [comment]
Thanks @leogr. For the `contrib`, I think the manifests are already up to date (except for the driver loader image which must be updated).

Details [here](https://github.com/falcosecurity/contrib/blob/master/integrations/k8s-using-daemonset/falco-daemonset-configmap-slim.yaml).

**Comment by leogr** [comment]
I believe the current helm chart is really affected by this issue, see referenced issues above.

**Comment by usamaahmadkhan** [comment]
@leogr yes the `/etc` is mounted on `/etc/host` with helm value `Values.ebpf.settings.mountEtcVolume` = true  and i'm still seeing this error

**Comment by leogr** [comment]
> @leogr yes the `/etc` is mounted on `/etc/host` with helm value `Values.ebpf.settings.mountEtcVolume` = true and i'm still seeing this error

Note that `ebpf.settings.mountEtcVolume` is not enough. Both `.Values.ebpf.enabled` and  `.Values.ebpf.settings.mountEtcVolume` have to be enabled (see https://github.com/helm/charts/blob/11465c8be7ad5bee3b08553038aa5695d444cafd/stable/falco/templates/daemonset.yaml#L118). But by doing so, `falco-driver-loader will load the eBPF probe instead of the kernel module.
Have you tried with both enabled?

**Comment by usamaahmadkhan** [comment]
yes both enabled.

**Comment by leogr** [comment]
> yes both enabled.

Hey @usamaahmadkhan 
at this point I'm not sure [your issue](https://github.com/falcosecurity/charts/issues/8) is related to this. I will investigate more.

**Comment by leogr** [comment]
It seems to me all TODOs have been done :point_right:
