### ISSUE TITLE
FPRO: Falco profiler

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falco#1204]
# Motivation

Performance-wise, Falco has two main major areas of improvement:

## Rules parsing/matching

Since the Falco engine is only useful when you load rules into it, many users load as many rules as they want into the Falco engine, however, this can degrade performances in some cases. Understanding what rules/filters create performances problem is a top priority for the Falco project.

Moreover, understanding how default rules changes can impact existing deployments that ships default rules is important for us to help the rules maintainers and the engine maintainers to keep sane defaults for everyone.

## Syscall drops
Falco has a mechanism called [Dropped Events](https://falco.org/docs/event-sources/dropped-events/) that informs the user when the shared buffer (between kernel and userspace) is full.

This mechanism is particularly important because it helps the Falco engine to stay functional and helpful even under adverse circumstances.

Fortunately, since that mechanism was introduced, the visibility it started providing made users and contributors aware of the problem of dropped syscalls even on non-development systems, that's why we have issues like https://github.com/falcosecurity/falco/issues/669 open right now.

The normal flow for a syscall looks like this (very simplistic flow)

```
   +---------+
   | program |
   +----+-+--+
        | ^
        | |
        | |do_syscall()    userspace
+-------------------------------+
        | |                kernelspace
        | |
        | |
        v |
  +-----+-+-----+
  |             |
  |  syscall    |
  |   API       |
  +-------------+
```

On the other hand, while running Falco, in addition to the normal execution, we go and ask to the kernel, hey! What's up? Any syscalls I should know of?

```
   +---------+    +---------+
   | program |    | Falco   |
   +----+-+--+    +----^-+--+
        | ^            | |
        | |            | |
        | |do_syscall()| | userspace
+-------------------------------+
        | |            | | kernelspace
        | |            | |
        | |            | |
        v |            | |
  +-----+-+-----+ +----+-v---+
  |             | |          |
  |  syscall    +->Falco kmod|
  |   API       <-+/ eBPF    |
  +-------------+ +----------+
```

As everyone can imagine, this means that for every interesting syscall we are doing the round-trip from kernel space to user space twice.

That's ultimately why the buffer exists and why the drops are happening.

There is a way to configure the behavior for drops, using the `syscall_event_drops` configuration option, however understanding how to configure it might not be trivial in some scenarios.

## New changes
Whenever a new change happens, understanding its performance impact on our key areas is vital for the project. We also want to be able to advertise what is the performance gain (or loss) between two Falco releases.

**Feature**

To help achieve all the above goals, we want to implement a mechanism in Falco that allows profiling that follows these requirements.

- It's RAII
- Uses a timestamp counter (rdtsc) to get the entry and exit time from the code block
- It's a tracing profiler (we can think about a sampling mechanism later)
- Can correlate callers and callees
- Does not impact much the Falco engine while it's running (need to define what much is, probably using an external profiler)
- It's anonymous, e.g: does not contain any information to identify the instance or who is using it
- Can be executed at runtime in production systems to generate a binary `.fpro` file that can be attached to an issue and analyzed later using an external program

# Alternatives

Go blind

# Additional context

This has been discussed in the Falco community calls and this is the issue wrapping up all the discussions and thoughts. Feel free to comment here.

There is a branch already with work going on this direction here 
https://github.com/falcosecurity/falco/tree/new/profiler

**Comment by fntlnz** [comment]
This is the file layout of a simple profile snapshot, [image courtesy](https://twitter.com/leodido/status/1260526021369004033) of @leodido 
![image](https://user-images.githubusercontent.com/3083633/81805004-65ede800-951a-11ea-9e7f-48168b5530f0.png)

**Comment by victortrac** [comment]
@fntlnz Just to help me understand the issue - is this a performance issue with the instance size, shared buffer, falco resource limits, or ...?  Are there any levers we, as users, can tweak to reduce the likelihood of dropped events?

**Comment by fntlnz** [comment]
@victortrac this is exactly why we are working on this, to be able to answer that kind of questions.

**Comment by leogr** [comment]
keep
