### ISSUE TITLE
Consume ECS Metadata with Falco

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falco#1215]
**Motivation**

Falco can run in ECS Fargate now, can we look at improving our integration?

**Feature**

With the new workaround `pdig` and running falco in ECS Fargate, can we start exploring consuming ECS and Fargate metadata into Falco in the same way we consume container and Kubernetes metadata?

This is relevant because this can be used as our first input plugin that can be built outside of the core Falco engine and use the new inputs API.

**Alternatives**

**Additional context**

**Comment by marcossv9** [comment]
Hi, any update on this thread?

Thanks,

**Comment by nomex** [comment]
Hi folks, any suggestion on how this can be achieved?
