### ISSUE TITLE
Syscall events dropped exceed number of syscall events

### ISSUE THREAD

**Issue by fujin** [falcosecurity/falco#1231]
**Describe the bug**

Falco emits `syscall event drop` messages to report dropped syscalls. In some cases, the output fields payload contain values that doesn't quite make sense to me. Specifically, the `n_drops` field is significantly more than `n_evts`. I would have assumed can only be `n_drops <= n_evts` typically (up to 100% events dropped- more than 100% dropped events seems improbable)

Example:
```
{"output":"Falco internal: syscall event drop. 6315305 system calls dropped in last second.","output_fields":{"ebpf_enabled":"1","n_drops":"6315305","n_drops_buffer":"6315305","n_drops_bug":"0","n_drops_pf":"0","n_evts":"134571"},"priority":"Critical","rule":"Falco internal: syscall event drop","time":"2020-05-20T21:52:47.925065865Z"}
```

**How to reproduce it**

Manifests here: https://gist.github.com/fujin/384b41af022cef939479cbb3ec0c88d6

**Expected behaviour**

n_drops <= n_evts (it does not seem possible to drop more events than have existed)

**Screenshots**

**Environment**

- Falco version:
```
Falco version: 0.23.0
Driver version: 96bd9bc560f67742738eb7255aeb4d03046b8045
```
- System info:
```
{
  "machine": "x86_64",
  "nodename": "gke-gke-stage-general-02-b1d1b568-176z",
  "release": "4.19.102+",
  "sysname": "Linux",
  "version": "#1 SMP Tue Feb 11 05:33:03 PST 2020"
}
```

- Cloud provider or hardware configuration: GKE
- OS: Container-Optimized OS build `12371.175.0`w/ kernel 

- Kernel: `4.19.102+`

- Installation method: Kubernetes, manifests attached in reproduction section.

**Additional context**

- Nodes: 7x n2-standard-32 pools, 1x n2-standard-8
- Cluster: 32 nodes total, 952vCPU/3808GB RAM. 
- Pods: 453~ total.
- Other: gRPC server enabled, Falco Exporter subscribing to events.

**Comment by leogr** [comment]
While doing a bit of investigation on drops, I have realized that `n_evts` is just the number of events that were successfully delivered to the buffer (thus not including dropped ones).

Basically, it seems to me that the implementation (both for the kernel module and the eBPF probe) is NOT incrementing `n_evts` in case of a dropped event. See:
- https://github.com/draios/sysdig/blob/8ccc3d5c27b6cce9f0dde6f9a292626a6ea85952/driver/bpf/plumbing_helpers.h#L465-L470
- https://github.com/draios/sysdig/blob/8ccc3d5c27b6cce9f0dde6f9a292626a6ea85952/driver/main.c#L1591-L1619

That would explain why n_drops > n_evts is possible.

If so, I would not classify this as a bug though it needs to be documented.
