### ISSUE TITLE
Falco segmentation fault `double free or corruption (!prev)`

### ISSUE THREAD

**Issue by fujin** [falcosecurity/falco#1232]
**Describe the bug**

Falco process crashes with segmentation fault and emits these messages:
```
* Setting up /usr/src links from host
* Running falco-driver-loader with: driver=bpf, compile=yes, download=yes
* Mounting debugfs
* Found kernel config at /proc/config.gz
* COS detected (build 12371.175.0), using cos kernel headers
* Downloading https://storage.googleapis.com/cos-tools/12371.175.0/kernel-headers.tgz
* Extracting kernel sources
* Configuring kernel
* Trying to compile the eBPF probe (falco_cos_4.19.102+_1.o)
* Skipping download, eBPF probe is already present in /root/.falco/falco_cos_4.19.102+_1.o
* eBPF probe located in /root/.falco/falco_cos_4.19.102+_1.o
* Success: eBPF probe symlinked to /root/.falco/falco-bpf.o
Thu May 21 05:20:04 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Thu May 21 05:20:04 2020: Configured rules filenames:
Thu May 21 05:20:04 2020:    /etc/falco/falco_rules.yaml
Thu May 21 05:20:04 2020:    /etc/falco/falco_rules.local.yaml
Thu May 21 05:20:04 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Thu May 21 05:20:05 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
double free or corruption (!prev)
```

Frequently it does not emit any message and silently crashes at the same position (seemingly, no syscall events are emitted to the log, as well)

Here is the current count of restarts from my staging environment.
```
NAME          READY   STATUS    RESTARTS   AGE
falco-5jxkz   2/2     Running   3          5h31m
falco-6kqn7   2/2     Running   7          5h35m
falco-6w2wh   2/2     Running   5          5h33m
falco-9ngz6   2/2     Running   7          5h33m
falco-d7t89   2/2     Running   7          5h34m
falco-dvzdm   2/2     Running   3          5h35m
falco-g8bwf   2/2     Running   8          5h33m
falco-jjvwn   2/2     Running   4          5h31m
falco-jxnzf   2/2     Running   3          5h30m
falco-n9njg   2/2     Running   7          5h32m
falco-plk84   2/2     Running   7          5h33m
falco-pv9wz   2/2     Running   0          5h32m
falco-pzhb6   2/2     Running   3          5h31m
falco-v5lhj   2/2     Running   3          5h30m
falco-xvlx8   2/2     Running   4          5h34m
falco-z4dqd   2/2     Running   8          5h35m
falco-zzmql   2/2     Running   1          5h34m
```

**How to reproduce it**

I don't really have minimal/precise steps. The staging environment we are testing on is of considerable scale - we are working through figuring out compute allocation as well as dealing with syscall drops. The configuration is mostly default beyond enabling the gRPC server. I have not yet experimented with disabling rules entirely but am considering it until we can be sure the segmentation faults and syscall drops can be mitigated.

Complete (redacted) manifest here: https://gist.github.com/fujin/384b41af022cef939479cbb3ec0c88d6

I found a one-liner in another issue that prints the last logged line from the previously exited container, thus: 
```
for pod in `kubectl get pods --no-headers -l app=falco -o custom-columns=":metadata.name"`; do echo -n "$pod exited with: "; kubectl logs $pod -c falco --previous | tail -n 1; done
```

**Expected behaviour**

The code, configuration, or environmental condition causing segmentation fault should be isolated and repaired.

**Screenshots**

![image](https://user-images.githubusercontent.com/6873/82545449-ce883500-9baa-11ea-9e5d-9f87f5b44f41.png)

**Environment**

< Falco version:
```
Falco version: 0.23.0
Driver version: 96bd9bc560f67742738eb7255aeb4d03046b8045
```
- System info:
```
{
  "machine": "x86_64",
  "nodename": "gke-gke-stage-general-02-b1d1b568-176z",
  "release": "4.19.102+",
  "sysname": "Linux",
  "version": "#1 SMP Tue Feb 11 05:33:03 PST 2020"
}
```

- Cloud provider or hardware configuration: GKE
- OS: Container-Optimized OS build `12371.175.0`w/ kernel 

- Kernel: `4.19.102+`

- Installation method: Kubernetes, manifests attached in reproduction section.

**Additional context**

- Nodes: 7x n2-standard-32 pools, 1x n2-standard-8
- Cluster: 32 nodes total, 952vCPU/3808GB RAM. 
- Pods: 453~ total.
- Other: gRPC server enabled, [a modified Falco Exporter](https://github.com/falcosecurity/falco-exporter/pull/28/commits) is subscribing to events.

Same environment as #1231

**Comment by leogr** [comment]
Hey @fujin 

Is this issue still present in Falco 0.25.0?
