### ISSUE TITLE
"BPF doesn't have JIT enabled" reported incorrectly when using docker

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco#1233]
**Describe the bug**

Even if JIT is enabled for BPF, both `falcosecurity/falco` and `facosecurity/falco-driver-loader` are reporting the following message when run with `-e FALCO_BPF_PROBE=""`:
```
******************************************************************
** BPF doesn't have JIT enabled, performance might be degraded. **
** Please ensure to run on a kernel with CONFIG_BPF_JIT on.     **
******************************************************************
```

**How to reproduce it**

In a system with a kernel >= 4.15  with CONFIG_BPF_JIT on and docker installed, run:
```shell
docker run --rm -i -t \
    --privileged \
    -v /dev:/host/dev \
    -v /proc:/host/proc:ro \
    -v /boot:/host/boot:ro \
    -v /lib/modules:/host/lib/modules:ro \
    -v /usr:/host/usr:ro \
    -v /etc:/host/etc:ro \
    -e FALCO_BPF_PROBE="" \
    falcosecurity/falco:0.23.0
```

**Expected behaviour**

No "BPF doesn't have JIT enabled, performance might be degraded" banner.

**Screenshots**

**Environment**

- Falco version: `0.23.0`
- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel: `Linux ubuntu-xenial 4.15.0-101-generic #102~16.04.1-Ubuntu SMP Mon May 11 11:38:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Installation method: `docker`

**Additional context**

Because the view of `/proc` inside the container is different, [this check](https://github.com/falcosecurity/falco/blob/d1c9aae8810ee0d21f3bd073dd19ff23288a5d08/scripts/falco-driver-loader#L431) is not working as expected when it runs inside a container. Note that prefixing the path with `${HOST}` will not solve the issue anyway.

**Comment by leogr** [comment]
IIRC, we suppressed the banner. https://github.com/falcosecurity/falco/pull/1811 attempted to re-introduce it, but I had some concern :point_down: 
https://github.com/falcosecurity/falco/pull/1811#pullrequestreview-837474605

cc @LucaGuerra @FedeDP

**Comment by leogr** [comment]
cc @therealbobo @LucaGuerra

**Comment by therealbobo** [comment]
A way to solve this issue is to use the `--net=host` flag but this is a terrible idea from a security standpoint: by giving the container access to the host network stack, it effectively eliminates any network isolation provided by Docker.
The only other way I can think of is to load dynamically a small bpf program and benchmark it: this comes with no guarantee of correctness (given that we have no actual baseline) and it isn't a clean approach.
Otherwise if the `falco-driver-loader` doesn't find the `/proc/sys/net/core/bpf_jit_enable` file we could assume that falco is running inside a container and alert the user to check outside of it.
I'll continue investigating.

**Comment by therealbobo** [comment]
After some more digging I discovered that it's possible to check if the jit is enabled using `bpftool` or writing a small program that essentially does the same of bpftool. I know that this solution is suboptimal but, at the moment, I think it's the only one.

**Comment by leogr** [comment]
> After some more digging I discovered that it's possible to check if the jit is enabled using `bpftool` or writing a small program that essentially does the same of bpftool. I know that this solution is suboptimal but, at the moment, I think it's the only one.

If we directly do that in the eBPF probe, then Falco will be able to emit the warning (rather than falco-driver-loader), which is a superior solution. 
cc @Andreagit97 @FedeDP 

@therealbobo why do you think it is suboptimal? :thinking:

**Comment by therealbobo** [comment]
After some more digging I think there is a way to determine if the JIT is enabled without relying on `/proc/sys/net/core/bpf_jit_enable` (which is not visible inside the container unless the `--net=nost` flag is specified). At runtime if we check `/proc/falco_pid/fdinfo/*` (filled by https://github.com/torvalds/linux/blob/5f63595ebd82f56a2dd36ca013dd7f5ff2e2416a/kernel/bpf/syscall.c#L2170) we'll found some useful info about each ebpf probe. One of these info is `prog_jited` which is actually what we are looking for (it indicates if an ebpf prog is jited or not). I've already tested and I think it's a perfect source of truth: if all probes have the `prog_jited = 0` we can assume that the JIT is disabled.

If all of you agree I can work on integrating this into falco. 😄

**Comment by Andreagit97** [comment]
first of all, thank you for the investigation! Just some random thoughts:
* As far as I know the bpf jit is now a sort of default so I expect it to be enabled unless some real corner cases. At the time the issue was opened probably it was a notable issue but 3 years are passed. WDYT?
* I like the proposed solution, but just out of curiosity how does bpftool detect the jit enabled?

**Comment by therealbobo** [comment]
- As far as I know it's a VERY corner case: I didn't find any distro that permits to disable the JIT... the only way to test my assumptions was to recompile the kernel 🤣 I totally agree that it isn't essential. The only problem, in my opinion, is the misleading error that shows up.
- All the other tools, that I can think of and that I found, only check the value in `/proc/sys/net/core/bpf_jit_enable`

**Comment by Andreagit97** [comment]
>   As far as I know it's a VERY corner case: I didn't find any distro that permits to disable the JIT... the only way to test my assumptions was to recompile the kernel, I totally agree that it isn't essential. 

Uhm so if this is the situation probably I would simply close the issue, keeping in mind that we have a solution in the case. 

> The only problem, in my opinion, is the misleading error that shows up.

Please note that this log is no more present, this is a quite old issue

> All the other tools, that I can think of and that I found, only check the value in /proc/sys/net/core/bpf_jit_enable

Thank you for the research!
