### ISSUE TITLE
falco deployment failing in GKE

### ISSUE THREAD

**Issue by kbojjireddy** [falcosecurity/falco#1238]
**Describe the bug**
Installed Falco on GKE from the Google Cloud Market place. Container crashed with error while trying to compile BPF probe falco-probe-bpyf

**How to reproduce it**
Install Falco on a GKE cluster from the Marketplace

**Expected behaviour**
Falco pod running successfully

**Screenshots**
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/22991586/83227114-03672f80-a149-11ea-88ed-aa5cc066e62d.png">

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
GKE
- OS:
Google Container-Optimized OS

- Kernel:

- Installation method:

GKE - use Google Cloud Marketplace

**Additional context**

**Comment by fntlnz** [comment]
Hi @kbojjireddy - thanks for bringing this to our attention, your contribution is very valuable.
If we are talking about [this one](https://console.cloud.google.com/marketplace/details/sysdig/falco-security)
I think that what you are trying to install is an old artifact (Falco 0.7) from when Falco was a Sysdig and not a CNCF project. Said that, I will need to bring this to our [community call](https://github.com/falcosecurity/community) to discuss what we want to do with it.

In the meanwhile, thanks for your interest in looking into Falco, if you want to install it, you can follow our [installation guide](https://falco.org/docs/installation/) and our [specific documentation section to make it work on GKE](https://falco.org/docs/third-party/#gke).
