### ISSUE TITLE
Falco fails to load prebuilt falco kernel module

### ISSUE THREAD

**Issue by rahul-kr4604** [falcosecurity/falco#1239]
**Describe the bug**
I built the Falco kernel module for kernel 4.18.0-147.8.1.el8_1.x86_64 and I inserted it using 'insmod' command.
But after creation of pod at the node, it removes the falco kernel module as per the 'falco-driver-loader', this is ok. Then after I placed the kernel module at '/root/.falco' with name "falco_rhcos_4.18.0-147.8.1.el8_1.x86_64_1.ko". As per the "falco-driver-loader", the kernel module should be loaded.
As per the below code of 'falco-driver-loader', the prebuilt module should be loaded.

`if [ -f "${HOME}/.falco/${FALCO_KERNEL_MODULE_FILENAME}" ]; then
		echo "* Found a prebuilt module at ${HOME}/.falco/${FALCO_KERNEL_MODULE_FILENAME}, loading it"
		insmod "${HOME}/.falco/${FALCO_KERNEL_MODULE_FILENAME}" && echo "* Success: ${DRIVER_NAME} module loaded"
		exit $?`

Pod log:

* Setting up /usr/src links from host
* Running falco-driver-loader with: driver=module, compile=yes, download=yes
* Unloading falco module, if present
* Trying to dkms install falco module
* Running dkms build failed, couldn't find /var/lib/dkms/falco/96bd9bc560f67742738eb7255aeb4d03046b8045/build/make.log
* Trying to load a system falco driver, if present
* Trying to find locally a prebuilt falco module for kernel 4.18.0-147.8.1.el8_1.x86_64, if present
* Trying to download prebuilt module from https://dl.bintray.com/falcosecurity/driver/96bd9bc560f67742738eb7255aeb4d03046b8045/falco_rhcos_4.18.0-147.8.1.el8_1.x86_64_1.ko
curl: (22) The requested URL returned error: 404 Not Found
Download failed, consider compiling your own falco module and loading it or getting in touch with the Falco community
Tue May 26 04:36:08 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Tue May 26 04:36:08 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Tue May 26 04:36:09 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Tue May 26 04:36:09 2020: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Tue May 26 04:36:10 2020: Unable to load the driver. Exiting.
Tue May 26 04:36:10 2020: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded.. Exiting.

Despite of placing the kernel module at the specified path (mentioned in "falco-driver loader"), it is not loaded, which results the failure of pod.

**How to reproduce it**
Build the falco kernel module, then after place it to the path mentioned in 'falco-driver-loader', and deploy the pod.

**Expected behaviour**
Locally built falco kernel module should be loaded and pod must be up and running.

**Screenshots**

**Environment**

- Falco version: 0.23.0

- OS: RHCOS

- Kernel: 4.18.0-147.8.1.el8_1.x86_64

**Additional context**

**Comment by dinvlad** [comment]
Same issue for us on
OS: Debian 10
Kernel: 4.19.0-9-cloud-amd64

**Comment by rahul-kr4604** [comment]
> Same issue for us on
> OS: Debian 10
> Kernel: 4.19.0-9-cloud-amd64
> 
> > 
> 
> ```
> * Trying to download prebuilt module from https://dl.bintray.com/falcosecurity/driver/96bd9bc560f67742738eb7255aeb4d03046b8045/falco_debian_4.19.0-9-cloud-amd64_1.ko
> curl: (22) The requested URL returned error: 404 Not Found
> ```

Hi dinvlad,

Have you already built the kernel module?

If yes, then make sure you have placed the kernel module at "$HOME/.falco/". Name of kernel module must be same as script "falco-driver-loader" is looking for. To know that what should be the name of kernel module, please look into the logs.
After this, please mount this directory "$HOME/.falco/" to the container using 'Hostpath'. So that it could be found from container.
Also check the SELinux context type of kernel driver (.ko) using below command:
`# ls -Z <name of kernel driver>`

If SELinux context type of kernel driver is "object_t" then change it to "modules_object_t" using below command:
`# chcon -t modules_object_t <name of kernel driver>`

I hope this will work, please let me know further.

**Comment by dinvlad** [comment]
Hi @rahul-kr4604,

This error only occurs when we try to build the module through Docker, using the command from the [docs](https://falco.org/docs/running/#docker):
```
docker run --rm -i -t \
    --privileged \
    -v /root/.falco:/root/.falco \
    -v /proc:/host/proc:ro \
    -v /boot:/host/boot:ro \
    -v /lib/modules:/host/lib/modules:ro \
    -v /usr:/host/usr:ro \
    -v /etc:/host/etc:ro \
    falcosecurity/falco-driver-loader:latest
```

Perhaps this deserves a separate issue, but the error is the same is yours, which indicates it's unable to even download the kernel module. Do you still experience it too?

Thanks

**Comment by rahul-kr4604** [comment]
> Hi @rahul-kr4604,
> 
> This error only occurs when we try to build the module through Docker, using the command from the [docs](https://falco.org/docs/running/#docker):
> 
> ```
> docker run --rm -i -t \
>     --privileged \
>     -v /root/.falco:/root/.falco \
>     -v /proc:/host/proc:ro \
>     -v /boot:/host/boot:ro \
>     -v /lib/modules:/host/lib/modules:ro \
>     -v /usr:/host/usr:ro \
>     -v /etc:/host/etc:ro \
>     falcosecurity/falco-driver-loader:latest
> ```
> 
> Perhaps this deserves a separate issue, but the error is the same is yours, which indicates it's unable to even download the kernel module. Do you still experience it too?
> 
> Thanks

I think, it is better to build the driver from source. I was getting the issue initially then I built it from source.

**Comment by dinvlad** [comment]
Further looking at this error, I do see a file that exists on that host:
```
https://dl.bintray.com/falcosecurity/driver/96bd9bc560f67742738eb7255aeb4d03046b8045/falco_debian_4.19.0-9-amd64_1.ko
```
However, it seems that the installation script incorrectly constructs the URL as follows:
```
https://dl.bintray.com/falcosecurity/driver/96bd9bc560f67742738eb7255aeb4d03046b8045/falco_debian_4.19.0-9-cloud-amd64_1.ko
```
(noticed the extra `-cloud` suffix). I think if we fix that, this should finally succeed.

**Comment by dinvlad** [comment]
And in your case @rahul-kr4604, there's no pre-compiled module at all, it seems.

**Comment by rahul-kr4604** [comment]
I have built the kernel module from source. It is working fine. So closing the issue.

**Comment by rahul-kr4604** [comment]
There was some issue of location of kernel module, and then after I was getting the permission issue, so I updated the SELinux module type of kernel module. It is working fine.
