### ISSUE TITLE
eBPF module fails to load on Fedora 32

### ISSUE THREAD

**Issue by roysjosh** [falcosecurity/falco#1251]
**Describe the bug**
falco fails to start when configured to use the BPF module with a verifier exception.

**How to reproduce it**
```
# FALCO_BPF_PROBE="" falco -v
...
jump out of range from insn 8 to 584
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
jump out of range from insn 8 to 584
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
Thu Jun  4 17:09:56 2020: Runtime error: bpf_load_program() err=22 event=filler/sys_single message=jump out of range from insn 8 to 584
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
. Exiting.
```

**Expected behaviour**
Successful start of falco with eBPF functionality.

**Environment**

- Falco version:
```
Falco version: 0.23.0
Driver version: 96bd9bc560f67742738eb7255aeb4d03046b8045
```
- System info:
```
{
  "machine": "x86_64",
  "nodename": "falco.example.com",
  "release": "5.6.15-300.fc32.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP Fri May 29 14:23:59 UTC 2020"
}
```
- Cloud provider or hardware configuration: KVM VM
- OS:
```
NAME=Fedora
VERSION="32 (Cloud Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Cloud Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Cloud Edition"
VARIANT_ID=cloud
```
- Kernel:
```Linux falco.example.com 5.6.15-300.fc32.x86_64 #1 SMP Fri May 29 14:23:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```
- Installation method:
RPM

**Additional context**

**Comment by fntlnz** [comment]
Thanks a lot for bringing this to our attention! Can you post the clang version ? @roysjosh

**Comment by fntlnz** [comment]
Just noticed again the same again with Clang 10 on Arch Linux.

```
jump out of range from insn 8 to 584
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
jump out of range from insn 8 to 584
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
bpf_load_program() err=22 event=filler/sys_single message=jump out of range from insn 8 to 584
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
```

```bash
clang --version                                                                                                       
clang version 10.0.0 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by leodido** [comment]
I was about to call it a day when I randomly encountered an LLVM BPF backend bug that somehow seems to be possibly related to this issue (the fix is available into LLVM 11 trunk). I'm especially referring to the CORE_MEM pseudo op.

Leave the link here for next week:
https://reviews.llvm.org/D78466

**Comment by fntlnz** [comment]
@leodido when you got some time, can you dump here a bit more information on why you think this is related? It's the generated code? I'd love to see a diff of what the two revisions of the backend generate.

Maybe there's a visualization tool like bpftool for this phase? We can't use bpftool because the program doesn't even get loaded. :/

**Comment by yunbo-xufeng** [comment]
I also met the same problem with LLVM-11

**Comment by fntlnz** [comment]
We are working on this, it seems like with newer kernels and newer versions of clang we jump out of range when we have more than one subprogram.

**Comment by kris-nova** [comment]
See commentary in #1463 for replication steps.

However I was able to remedy to problem by using a different version of `clang` to compile the BPF probe.

### Arch Linux

```
pacaur -R clang
pacaur -S llvm90 clang90 # <--- These packages are installed in /opt/llvm90 
PATH=$PATH:/opt/llvm90/bin
cd ${HOME}
git clone git@github.com:falcosecurity/falco.git
cd falco
mkdir build
cd build
cmake ../ \
      -DBUILD_BPF="ON" \
      -DBUILD_WARNINGS_AS_ERRORS="OFF" \
      -DCMAKE_BUILD_TYPE="Release" \
      -DCMAKE_INSTALL_PREFIX="/usr" \
      -DFALCO_ETC_DIR="/etc/falco" \
      -DUSE_BUNDLED_DEPS=ON
make bpf
make falco
sudo cp driver/bpf/probe.o /root/.falco/falco-bpf.o
sudo cp userspace/falco/falco /usr/bin/falco
sudo FALCO_BPF_PROBE="" falco
```

Works for me on the following kernel

```
Linux emily 5.9.1-arch1-1 #1 SMP PREEMPT Sat, 17 Oct 2020 13:30:37 +0000 x86_64 GNU/Linux
```

With this version of clang

```
clang version 9.0.1 (https://aur.archlinux.org/clang90 27393b8bd3cb3d511808bd0b60f79dd0d2f26286)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/llvm90/bin
```

**Comment by fntlnz** [comment]
Thanks for taking the time to report back what it worked on 5.9 with clang 9.
I didn't try yet on 5.9 but I'll report back some matrix of what works vs what does not when I find some time to follow on this.

Do you mind sending over the output of:

```
llvm-objdump -S /root/.falco/falco-bpf.o
```

Since the code for the eBPF probe still lives in the sysdig repo, I put together some collections there: https://github.com/draios/sysdig/issues/1658

**Comment by kris-nova** [comment]
Dumps for both clang 9.0 and 10.0 on my machine

[clang10.txt](https://github.com/falcosecurity/falco/files/5462099/clang10.txt)
[clang9.txt](https://github.com/falcosecurity/falco/files/5462100/clang9.txt)

**Comment by lumontec** [comment]
Hy guys,
if anyone is interested I have an update on this at [https://github.com/draios/sysdig/issues/1658](https://github.com/draios/sysdig/issues/1658#issuecomment-756623639)

**Comment by fntlnz** [comment]
@leodido and I have a fix ready for this. Will be discussing in today's community call.

**Comment by fntlnz** [comment]
Here's the set of patches to fix this, once they go into the libraries we can update Falco and close this:

- https://github.com/draios/sysdig/pull/1730
- https://github.com/draios/sysdig/pull/1731
- https://github.com/draios/sysdig/pull/1732
- https://github.com/draios/sysdig/pull/1733

**Comment by lumontec** [comment]
Wow great job @fntlnz ! Just for the sake of curiosity do you have any idea why these bugs didn`t show up with older clang versions ?
