### ISSUE TITLE
Running `falco-no-driver` container with least privilege after `falco-driver-loader` fails to create process list

### ISSUE THREAD

**Issue by DrkDigglr** [falcosecurity/falco#1253]
Receive the following when running `falco-no-driver` container on Ubuntu 18.04 LTS host:
```
$ docker run --rm -i -t --cap-add SYS_PTRACE $(ls /dev/falco* | xargs -I {} echo --device {}) --pid=host -v /var/run/docker.sock:/var/run/docker.sock falcosecurity/falco-no-driver:latest

2020-06-10T10:02:14+0000: Falco initialized with configuration file /etc/falco/falco.yaml
2020-06-10T10:02:14+0000: Loading rules from file /etc/falco/falco_rules.yaml:
2020-06-10T10:02:15+0000: Loading rules from file /etc/falco/falco_rules.local.yaml:
2020-06-10T10:02:15+0000: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
2020-06-10T10:02:15+0000: Unable to load the driver. Exiting.
2020-06-10T10:02:15+0000: Runtime error: error creating the process list. Make sure you have root credentials.. Exiting.
```

After running the `falco-driver-loader` image as described in the Falco documentation under "Least Privilege" I get the following which indicates the kernel driver successfully installed:

```
$ docker run --rm -i -t \
>     --privileged \
>     -v /root/.falco:/root/.falco \
>     -v /proc:/host/proc:ro \
>     -v /boot:/host/boot:ro \
>     -v /lib/modules:/host/lib/modules:ro \
>     -v /usr:/host/usr:ro \
>     -v /etc:/host/etc:ro \
>     falcosecurity/falco-driver-loader:latest
* Setting up /usr/src links from host
* Running falco-driver-loader with: driver=module, compile=yes, download=yes
* Unloading falco module, if present
* Trying to dkms install falco module

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j1 KERNELRELEASE=5.3.0-59-generic -C /lib/modules/5.3.0-59-generic/build M=/var/lib/dkms/falco/96bd9bc560f67742738eb7255aeb4d03046b8045/build....
cleaning build area...

DKMS: build completed.

falco.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.3.0-59-generic/kernel/extra/

depmod....

DKMS: install completed.
* falco module installed in dkms, trying to insmod
* Success: falco module found and loaded in dkms
```
I then run the no-driver variant and get the error described at the top of this post.

**In short I followed the instructions here:**
https://falco.org/docs/running/

- Falco version: 0.23.0
- System info: See below
- Cloud provider or hardware configuration: Virtualbox 6.1, 1 CPU, 2GB RAM, 30GB disk space
- OS: 
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel: 
```
Linux tester-VirtualBox 5.3.0-59-generic #53~18.04.1-Ubuntu SMP Thu Jun 4 14:58:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Installation method:
Official Docker containers

I'm testing things out at the moment but I'd like to run this in Kubernetes with least privilege. I've tried running `htop` in a container with the `--pid=host` flag and it works fine. If I remove this flag in the command to run Falco no-driver it works. Adding the flag back results in the error returning regarding the process list.

**Comment by dinvlad** [comment]
Same problem for us:
`falco --version`: 0.20.0+d77080a
`uname -a`: Linux 4.19.0-9-cloud-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux
```
2020-07-01T20:26:20+0000: Falco initialized with configuration file /etc/falco/falco.yaml
2020-07-01T20:26:20+0000: Loading rules from file /etc/falco/falco_rules.yaml:
2020-07-01T20:26:20+0000: Loading rules from file /etc/falco/falco_rules.local.yaml:
2020-07-01T20:26:20+0000: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
2020-07-01T20:26:21+0000: Unable to load the driver. Exiting.
2020-07-01T20:26:21+0000: Runtime error: error creating the process list. Make sure you have root credentials.. Exiting.
```

**Comment by leogr** [comment]
> Same problem for us:
> `falco --version`: `0.20.0+d77080a`
> `uname -a`: `Linux 4.19.0-9-cloud-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux`
> 
> ```
> 2020-07-01T20:26:20+0000: Falco initialized with configuration file /etc/falco/falco.yaml
> 2020-07-01T20:26:20+0000: Loading rules from file /etc/falco/falco_rules.yaml:
> 2020-07-01T20:26:20+0000: Loading rules from file /etc/falco/falco_rules.local.yaml:
> 2020-07-01T20:26:20+0000: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
> 2020-07-01T20:26:21+0000: Unable to load the driver. Exiting.
> 2020-07-01T20:26:21+0000: Runtime error: error creating the process list. Make sure you have root credentials.. Exiting.
> ```

IIRC, `falco-no-driver` was introduced since 0.23.0, so I'm not sure how you installed the driver to work with `0.20.0+d77080a`. Could you share more details?

**Comment by dinvlad** [comment]
@leogr Thanks for pointing that out - indeed, we had to install Falco through the official installation script on Debian, which resulted in this version being installed.

We had to that because at first, we tried to load it through `falco-driver-loader` image, but that's failing for another reason (https://github.com/falcosecurity/falco/issues/1239).

So I'm not sure how we can proceed with `falco-no-driver` if we can't get `falco-driver-loader` to work first..

**Comment by leogr** [comment]
Hi @dinvlad 

You need both `falco-driver-loader` and `falco-no-driver` to be the version 0.23.0 (IIRC the driver version changed from 0.20.0 to 0.23.0). You can find the `.deb` of the 0.23.0 :point_right:  [here](https://falco.org/docs/download/#packages) (it's the official package).

Regarding the need of `--pid=host`, AFAIK it may depend on the system, so in your case might be correct to remove `--pid=host` (as same as @DrkDigglr did, could you confirm that everything works without it?). Please, note that I'm not 100% sure about that and I haven't tested this case deeply, so do not consider my suggestion as "official" :)

**Comment by fntlnz** [comment]
@DrkDigglr that error usually happens when Falco can't traverse and read the proc filesystem mounted at `/proc/`.

That is why we need to do `--cap-add SYS_PTRACE` in the least privileged scenario.

I think that there's something going wrong with the command or we need to figure out if there is anything specific in your system preventing this.

First things first, can you try this command?

```
docker run --cap-add SYS_PTRACE   --pid=host -it alpine cat /proc/1/environ
```

It should output something like

```
TERM=linux/
``

**Comment by fntlnz** [comment]
Interestingly, the command I posted above does not work for me on Ubuntu 18.04

```
docker run --cap-add SYS_PTRACE   --pid=host -it alpine cat /proc/1/environ
cat: can't open '/proc/1/environ': Permission denied
```

**Comment by fntlnz** [comment]
First suspect, apparmor:

```
[ 2055.977977] audit: type=1400 audit(1593780613.624:163): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=10951 comm="cat" requested_mask="trace" denied_mask="trace" peer="unconfined"
```

**Comment by fntlnz** [comment]
Yes it is apparmor

```bash
docker run --security-opt apparmor:unconfined  --cap-add SYS_PTRACE   --pid=host -it ubuntu cat /proc/1/environ

HOME=/init=/sbin/initNETWORK_SKIP_ENSLAVED=recovery=TERM=linuxdrop_caps=BOOT_IMAGE=/boot/vmlinuz-4.15.0-101-genericPATH=/sbin:/usr/sbin:/bin:/usr/binPWD=/rootmnt=/root
```

**Comment by fntlnz** [comment]
So in the case of Ubuntu, there are two ways:

- We write a specific apparmor profile to allow the read of `/proc` and then pass it to the Falco least privileged container
- We suggest to use `--security-opt apparmor:unconfined` 


I confirm that by using apparmor unconfined I can get the least privileged Falco to work without giving full privileges.
 
```bash
docker run --security-opt apparmor:unconfined --rm -i -t --cap-add SYS_PTRACE $(ls /dev/falco* | xargs -I {} echo --device {}) --pid=host -v /var/run/docker.sock:/var/run/docker.sock falcosecurity/falco-no-driver:latest
2020-07-03T12:56:54+0000: Falco initialized with configuration file /etc/falco/falco.yaml
2020-07-03T12:56:54+0000: Loading rules from file /etc/falco/falco_rules.yaml:
2020-07-03T12:56:54+0000: Loading rules from file /etc/falco/falco_rules.local.yaml:
2020-07-03T12:56:54+0000: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
2020-07-03T12:56:55+0000: Starting internal webserver, listening on port 8765

```

**Comment by leogr** [comment]
Hey,

Has this issue been fixed by https://github.com/falcosecurity/falco-website/pull/225 ?

Could anyone confirm?
