### ISSUE TITLE
pre-built eBPF probe seems to be halfway missing for amazonlinux

### ISSUE THREAD

**Issue by timothy-spencer** [falcosecurity/falco#1255]
**Describe the bug**

When I try to run falco on an EKS cluster, it tries to download `https://dl.bintray.com/falcosecurity/driver/96bd9bc560f67742738eb7255aeb4d03046b8045/falco_amazonlinux2_4.14.177-139.254.amzn2.x86_64_1.o`, which does not exist.  However, `https://dl.bintray.com/falcosecurity/driver/96bd9bc560f67742738eb7255aeb4d03046b8045/falco_amazonlinux2_4.14.177-139.254.amzn2.x86_64_1.ko` does, so maybe the build process needs to be fixed?

**How to reproduce it**

```
helm repo add falcosecurity https://falcosecurity.github.io/charts
helm repo update
kubectl config set-context --current --namespace=kube-system
cat <<EOF > falco-values.yml
ebpf:
  enabled: true
  settings:
    mountEtcVolume: false
EOF
helm template --name-template=falco falcosecurity/falco -f falco-values.yml > falco.yml
kubectl apply -f falco.yml
kubectl logs daemonset.apps/falco -n kube-system
```

**Expected behaviour**

I expect the falco image to be able to successfully download the appropriate amazonlinux .o file so that it can load it and run.

**Screenshots**

```
laptop:~$ kubectl logs daemonset.apps/falco -n kube-system 
Found 4 pods, using pod/falco-8xb4p
* Setting up /usr/src links from host
* Running falco-driver-loader with: driver=bpf, compile=yes, download=yes
* Mounting debugfs
* Found kernel config at /host/boot/config-4.14.177-139.254.amzn2.x86_64
* Trying to compile the eBPF probe (falco_amazonlinux2_4.14.177-139.254.amzn2.x86_64_1.o)
make[1]: *** /lib/modules/4.14.177-139.254.amzn2.x86_64/build: No such file or directory.  Stop.
make: *** [Makefile:18: all] Error 2
mv: cannot stat '/usr/src/falco-96bd9bc560f67742738eb7255aeb4d03046b8045/bpf/probe.o': No such file or directory
* Trying to download a prebuilt eBPF probe from https://dl.bintray.com/falcosecurity/driver/96bd9bc560f67742738eb7255aeb4d03046b8045/falco_amazonlinux2_4.14.177-139.254.amzn2.x86_64_1.o
curl: (22) The requested URL returned error: 404 Not Found
Download failed
Wed Jun 10 20:34:47 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Wed Jun 10 20:34:47 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Wed Jun 10 20:34:48 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Wed Jun 10 20:34:49 2020: Unable to load the driver. Exiting.
Wed Jun 10 20:34:49 2020: Runtime error: can't open BPF probe '/root/.falco/falco-bpf.o': Errno 2. Exiting.
laptop:~$ 
```

**Environment**

AWS EKS 1.16

- Falco version:  image: docker.io/falcosecurity/falco:0.23.0
- System info:
- Cloud provider or hardware configuration:
- OS:
- Kernel:  falco_amazonlinux2_4.14.177-139.254.amzn2.x86_64_1
- Installation method:  Kubernetes, from rendered helm template (documented above)

**Additional context**

None that I can think of!  Thanks for your help!

**Comment by kris-nova** [comment]
So if you look at the various objects for the drivers we have 2

### eBPF

which uses the `.o` syntax and is just a good ol' fashioned ELF object that we have all grown to love.

### Kernel Modules

which use the `.ko` syntax (short for kernel object) which is slightly different. 

In your example you have 

```
ebpf:
  enabled: true
```

Probably the quickest fix is to flip that to false.

If for some reason we need the eBPF probe instead of the kernel module (they roughly do the exact same thing but exist for various use cases) we can talk more about getting the `.o` file into the builds. Just let us know.

Typically the eBPF driver (or `.o` file) is reserved for users who run on GKE because of their underlying kernel restrictions. Which would explain why we don't pre-build it for EKS folks :)

**Comment by kris-nova** [comment]
PS: please let us know what happens if you have time. I closed the issue to spare the other maintainers, but you can reopen at any time. :v:

**Comment by leodido** [comment]
Thanks @kris-nova for replying to @timothy-spencer :)

Let me just add that the place for this kind of issues is https://github.com/falcosecurity/test-infra where we have the system that prebuilds drivers (best-effort).
