### ISSUE TITLE
Missing build/release directory when running builder

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falco#1259]
**Describe the bug**

It looks like the `docker/builder` container image is designed to be used for CI for building and compiling Falco.

If you make a code change to Falco locally, build and push the container, and try to run in Kubernetes you can get the following errors

```
Missing /build/release directory: run cmake.
Missing /build/release directory: run cmake.
Missing /build/release directory: run cmake.
```

**How to reproduce it** 

```
git clone git@github.com:falcosecurity/falco.git
cd falco/docker/builder
docker build -t krisnova/falco:latest .
docker push krisnova/falco:latest
helm install falco 
k edit ds # change image to krisnova/falco:latest
k logs -l app=falco 
```

After looking in the container it looks like this container is used for a lot more than just a local dev, so I think this eluding to a dev story.

**Expected behaviour**

A container I can build and push to try local code in Kubernetes.

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by kris-nova** [comment]
Please close this if we have another way of doing this - I am going to get some sleep tonight, but I will probably create a side project with some hacky bash scripts to demonstrate what I would like to do which is basically:

 - make a code change in C++
 - reflect that code in a GKE kubernetes cluster quickly
 - control the driver
 - possibly build the driver 
 - scp the driver to the node

I know it's a lot but just bare with me as I hack on this 

No action needed :) these are just my notes.

**Comment by leodido** [comment]
> Missing /build/release directory: run cmake.
> Missing /build/release directory: run cmake.
> Missing /build/release directory: run cmake.

The builder help and docs tell the user to run it passing the `cmake` command so to be able then to build/test it.

https://github.com/falcosecurity/falco/blob/master/docker/builder/root/usr/bin/usage#L26

**Comment by leogr** [comment]
Also :point_right: [here](https://github.com/falcosecurity/falco/blob/578ef7f64d94408fb2e07d30dd3f7131a054643c/docker/builder/Dockerfile#L4)
