### ISSUE TITLE
Event Generator is not triggering all rules to create those log events.

### ISSUE THREAD

**Issue by kempy007** [falcosecurity/falco#1264]
**Describe the bug**

Event Generator is not triggering all rules to create those log events.

Only these events are logged:
Error Directory below known binary directory created
Error File below /etc opened for writing
Error File below a known binary directory opened for writing
Error File below known binary directory renamed/removed
Error File created below /dev by untrusted program
Error Package management process launched in container
Error Rpm database opened for writing by a non-rpm program
Notice A shell was spawned in a container with an attached terminal
Notice Namespace change
Notice Privileged container started
Notice Setuid or setgid bit is set via chmod
Notice System user ran an interactive command
Notice Unexpected connection to K8s API Server from container
Notice Unexpected setuid call by non-sudo, non-root program
Notice User management binary command run outside of container
Warning Sensitive file opened for reading by non-trusted program

**How to reproduce it**

Installed with helm chart v1.1.7 with image v0.23.0 on AKS v1.16.7 with RBAC.
setup tail with  `kubectl logs falco-<abc123> -f`
generate events with `kubectl run events --image=falcosecurity/falco-event-generator --command -- event_generator syscall all`

**Expected behaviour**

Expect to see shell spawned events on stdout and when running `kubectl -exec -ti falco-<abc123> -- sh`

**Environment**

- Falco version:
falco --version
Falco version: 0.23.0
Driver version: 96bd9bc560f67742738eb7255aeb4d03046b8045

- System info:
falco --support | jq .system_info
Wed Jun 17 13:06:50 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Wed Jun 17 13:06:50 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Wed Jun 17 13:06:51 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Wed Jun 17 13:06:52 2020: Loading rules from file /etc/falco/rules.d/rules-aks.yaml:
{
  "machine": "x86_64",
  "nodename": "falco-7f6r4",
  "release": "4.15.0-1082-azure",
  "sysname": "Linux",
  "version": "#92~16.04.1-Ubuntu SMP Tue Apr 14 22:28:34 UTC 2020"
}

- Cloud provider or hardware configuration:
Azure AKS RBAC Enabled v1.16.7 
- OS:
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Kernel:
uname -a
Linux falco-7f6r4 4.15.0-1082-azure #92~16.04.1-Ubuntu SMP Tue Apr 14 22:28:34 UTC 2020 x86_64 GNU/Linux

- Installation method:
Helm

**Additional context**

**Comment by leogr** [comment]
Hey @kempy007 

`falcosecurity/falco-event-generator` is the old generator, it's not supported anymore.

The new one is here: https://github.com/falcosecurity/event-generator

You can find the list of all supported events in the README, and you can add your own events as explained [here](https://github.com/falcosecurity/event-generator/tree/master/events).

AFAIK all of the `syscall` events should work, some `k8saudit` might not be triggered in the right way (I'm working on that).

Please feel free to open an issue on [event-generator repo](https://github.com/falcosecurity/event-generator) if you found any problem.

Also, notice that for Falco 0.23.0 you need the latest helm chart version (v1.1.9) that we recently moved here: https://github.com/falcosecurity/charts/tree/master/falco
It provides some fixes to make Falco work correctly.

**Comment by kempy007** [comment]
Hi @leogr 

Thanks for your help. 

I normally try to trigger 'Terminal shell in container' but this no longer fires, and with chart 1.1.1 & image .19. it worked Early April, but not any more, so feel like something has regressed but having a hell of a time trying to pinpoint it. Is there a known issue causing rules to not work? The only moving target is the AKS kernel.

**Comment by leogr** [comment]
Not sure about that, but since you are using chart v1.1.7 with image v0.23.0 the issue might be in the chart and not in Falco.
Could you try with the [new helm chart](https://github.com/falcosecurity/charts/tree/master/falco)?

I have tried to trigger it manually in my env and it worked:
```
10:26:33.819438173: Notice A shell was spawned in a container with an attached terminal (user=root k8s.ns=default k8s.pod=falco-krlvx container=d8892e4fde21 shell=sh parent=runc cmdline=sh terminal=34816 container_id=d8892e4fde21 image=docker.io/falcosecurity/falco) k8s.ns=default k8s.pod=falco-krlvx container=d8892e4fde21
```

**Comment by kempy007** [comment]
Hi @leogr 

I'm afraid I have the same result with chart 1.1.9 and image .23.
What was the kernel in your working env? 
It's the only factor I cannot rollback as picking oldest AKS 1.14.7 still gets same version of kernel
```
uname -a
Linux falco-68lmb 4.15.0-1083-azure #93~16.04.1-Ubuntu SMP Thu May 7 18:39:44 UTC 2020 x86_64 GNU/Linux
```

**Comment by leogr** [comment]
My env is `5.7.2-arch1-1` (my local machine),  anyhow I don't believe the kernel version has any effect on this.

How are you triggering the event?

Also, have you checked if the event shows up after a while?  We are noticing a possible log throttling bug, see https://github.com/falcosecurity/falco/issues/1198

In my case, the event showed up in the log after a while, only when a few of other events were triggered.

**Comment by kempy007** [comment]
I ran 
```
kubectl -n kube-system exec -ti falco-abc12 -- bash
```

I have confirmed #1198 is the behaviour i'm seeing!

**Comment by leogr** [comment]
@kempy007 Thank you!

I have marked this issue as dup of #1198 

If you can confirm there're no other bugs related to the event generator, I will close this.

**Comment by kempy007** [comment]
I confirm there are no bugs I am reporting in the event generator and this is a dup and can be closed.
