### ISSUE TITLE
Migrate Debian packages to Systemd

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falco#1265]
**Motivation**

Currently the Falco debian package use an outdated feature to manage the service on Debian systems called `init`. This currently hasn't caused any concern because the new feature `systemd` is smart enough to manage the older `init` style configurations. 

Most `systemd` users aren't even aware that `systemd` is actually referencing the old falco `init` scripts.

In issue https://github.com/falcosecurity/falco/issues/640 we have a very strong use case to migrate from `init` to `systemd` so that the unit file can be configured in such a way that it will automatically be restarted.

**Feature**

Can we please change the debian packaging code in [/scripts](https://github.com/falcosecurity/falco/tree/master/scripts) to support `systemd` instead of `init`?

Can we also craft a unit file for `systemd`? Here is what I am running in production currently.

```
[Unit]
Description=Falco Runtime Security

[Service]
ExecStart=/usr/bin/falco --pidfile=/var/run/falco.pid -c /etc/falco/falco.yaml
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=always

[Install]
WantedBy=multi-user.target
```

**Alternatives**

For #640 we could also bake in a restart feature into `init` but at this point I don't think we should continue to build on top of `init` any more.

**Additional context**

Note: Now that the #1217 Unix Socket work is making it to production, we can configure Falco in Kubernetes to communicate directly with systemd to get meta information about the service and auto-configure Falco read-only pods to listen on the domain socket on the host :nerd_face:

**Comment by kris-nova** [comment]
We could potentially use this library to auto-configure the Falco pods to find and connect to the domain socket on the underlying host https://github.com/coreos/go-systemd

**Comment by jenting** [comment]
Could we also support migrate rpm packages to systemd also?

**Comment by leogr** [comment]
Totally agree. We should migrate both.
