### ISSUE TITLE
Falco rules file should have `required_engine_version: 6`

### ISSUE THREAD

**Issue by mstemm** [falcosecurity/falco#1272]
**Describe the bug**

Hi, I noticed that https://github.com/falcosecurity/falco/commit/70b9bfe1d6bf4d44e7ad000d726603418ad37342#diff-6acd8aa2e534d1ed83e275bf658d936b added a new rule Container Drift Detected (open+create) that requries falco engine version 6. However, the rules file itself doesn’t have any required_engine_version block. There’s a commented out version here: https://github.com/falcosecurity/falco/blob/master/rules/falco_rules.yaml#L26. 

If users tried to load this rules file with older falco versions, they wouldn't be able to load the file, as the new field `evt.is_open_exec` doesn't work with older falco engine versions.

I'd suggest at least updating the required_engine_version to 6 in the rules file.

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by mstemm** [comment]
Btw, here are our docs on falco engine and rules file compatibility: https://falco.org/docs/rules/#versioning.

**Comment by fntlnz** [comment]
I think that it's the time to remove that comment honestly.

**Comment by fntlnz** [comment]
I proposed a change in #1273 - however, as an alternative thing we can do is to create a rules file for every `required_engine_version` depending on what are the supported fields. I don't like this idea however, probably being able to scope the specific rule is a better idea in my opinion.

**Comment by leodido** [comment]
The `required_engine_version` already works at the rule level (we just tested it).

Thus, the best approach is to define it for the Container Drift rule, IMHO. We'll do it into #1273 right now.

**Comment by leogr** [comment]
quick update: the `required_engine_version` does not work at the rule level, see [this comment](https://github.com/falcosecurity/falco/pull/1273#issuecomment-662406908)
