### ISSUE TITLE
Cannot run falco in Minikube

### ISSUE THREAD

**Issue by anxolerd** [falcosecurity/falco#1276]
**Describe the bug**

Falco fails to run in minikube. I have followed the guide https://falco.org/blog/minikube-falco-kernel-module/ and expected to have falco up and running in my minikube VM. However, while `helm install` command worked fine (at least without any errors), daemonset pod is failing to use prebuilt kernel module.

**How to reproduce it**

Follow steps from guide: https://falco.org/blog/minikube-falco-kernel-module/

1. Create minikube `minikube start`. In my case kvm2 driver was used
2. Create separate namespace `kubectl create ns falco`
3. Add helm repository and install `helm --namespace falco install falco falcosecurity/falco`
4. Observe logs from falco pod: `kubectl -n falco logs -l app=falco -f`

Logs say the following:

```
➜ kubectl -n falco logs -l app=falco -f
* Trying to load a system falco driver, if present
* Trying to find locally a prebuilt falco module for kernel 4.19.107, if present
* Trying to download prebuilt module from https://dl.bintray.com/falcosecurity/driver/96bd9bc560f67742738eb7255aeb4d03046b8045/falco_buildroot_4.19.107_1.ko
curl: (22) The requested URL returned error: 404 Not Found
Download failed, consider compiling your own falco module and loading it or getting in touch with the Falco community
Tue Jun 23 12:34:46 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Tue Jun 23 12:34:46 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Tue Jun 23 12:34:47 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Tue Jun 23 12:34:47 2020: Unable to load the driver. Exiting.
Tue Jun 23 12:34:47 2020: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded.. Exiting.
```

Pay attention at lines

```
* Trying to download prebuilt module from https://dl.bintray.com/falcosecurity/driver/96bd9bc560f67742738eb7255aeb4d03046b8045/falco_buildroot_4.19.107_1.ko
curl: (22) The requested URL returned error: 404 Not Found
Download failed, consider compiling your own falco module and loading it or getting in touch with the Falco community
```
 and
```Tue Jun 23 12:34:47 2020: Unable to load the driver. Exiting.
Tue Jun 23 12:34:47 2020: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded.. Exiting.
```

**Expected behaviour**

Pod successfuly ran. Logs are similar to one in blogpost. Module is downloaded and loaded.

**Screenshots**

![Selection_158](https://user-images.githubusercontent.com/6533582/85404915-4d84da80-b568-11ea-88ac-4981b921e33a.png)

**Environment**

- Falco version:

0.23.0

- Cloud provider or hardware configuration:
```$ minikube version
minikube version: v1.11.0
commit: 57e2f55f47effe9ce396cea42a1e0eb4f611ebbd```

- OS:
```$ cat /etc/os-release
NAME=Buildroot
VERSION=2019.02.10
ID=buildroot
VERSION_ID=2019.02.10
PRETTY_NAME="Buildroot 2019.02.10"
```

- Kernel:
```
$ uname -a
Linux minikube 4.19.107 #1 SMP Thu May 28 15:07:17 PDT 2020 x86_64 GNU/Linux
```

- Installation method:
Kubernetes, helm, https://falco.org/blog/minikube-falco-kernel-module/

**Comment by leodido** [comment]
Hey @afbjorklund, I saw your commits ([here](https://github.com/kubernetes/minikube/commit/d1ea9f96fdadbc8b88d2fff017fd279d63f257ab#diff-6a05e0d9b89e3aef833752438f8db228)) in the minikube repo (thanks, btw) to make it support Falco 0.23 and its driver.

Any hints why minikube v1.11 is not able to find a "system" Falco driver?

**Comment by afbjorklund** [comment]
Not really, seemed to work here:

```console
 minikube version
minikube version: v1.11.0
commit: 57e2f55f47effe9ce396cea42a1e0eb4f611ebbd
 minikube ssh
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ sudo modprobe falco-probe
$ lsmod
Module                  Size  Used by
falco_probe           630784  0
...
$ more /etc/os-release 
NAME=Buildroot
VERSION=2019.02.10
ID=buildroot
VERSION_ID=2019.02.10
PRETTY_NAME="Buildroot 2019.02.10"
$ uname -r
4.19.107
$ ls /lib/modules/4.19.107/extra/falco-probe.ko
/lib/modules/4.19.107/extra/falco-probe.ko
```

**Comment by afbjorklund** [comment]
Probably due to 762ef015b80552267013e9988e3f5dd888ffbab0 ?

**Comment by afbjorklund** [comment]
I think I understand what happened.

Minikube v1.11.0 is still using falco-probe 0.21.0, and then it was called "falco-probe.ko"

Minikube v1.12.0 (out next week or so) will use falco 0.23.0, and now it is called "falco.ko".

**Comment by anxolerd** [comment]
@afbjorklund, thanks!

Shell snippet from https://github.com/falcosecurity/falco/issues/1276#issuecomment-648932330 helped to get out of CrashLoopBackoff. I'll proceed evaluating falco then)

**Comment by leogr** [comment]
AFAIK it should work now. Could anybody confirm that, please?

**Comment by afbjorklund** [comment]
minikube version: v1.12.3

name: falco
version: 1.2.2
appVersion: 0.24.0

```
* Setting up /usr/src links from host
* Running falco-driver-loader with: driver=module, compile=yes, download=yes
* Unloading falco module, if present
* Trying to dkms install falco module
* Running dkms build failed, couldn't find /var/lib/dkms/falco/85c88952b018fdbce2464222c3303229f5bfcfad/build/make.log
* Trying to load a system falco driver, if present
* Success: falco module found and loaded with modprobe
```

**Comment by afbjorklund** [comment]
Should update for 1.13
FALCO_MODULE_VERSION = 0.24.0
FALCO_MODULE_SYSDIG_VERSION = 85c88952b018fdbce2464222c3303229f5bfcfad

**Comment by afbjorklund** [comment]
See https://github.com/kubernetes/minikube/pull/9068
