### ISSUE TITLE
Fields by engine version

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falco#1277]
**What to document**

While working on #1273 I noticed that the `required_engine_version` field can be a bit confusing to users due to the fact that we don't two key things:

- We don't know how an engine version is correlated to a Falco version (unless you dig into git)
- We don't have a list of what fields are in what engine version

I'd like to have them documented.

**Comment by leodido** [comment]
Agree.

Just for completeness, about the first bullet point, I opened https://github.com/falcosecurity/falco/issues/1269 2 days ago.

Basically, the Falco Engine version behave like the driver version w.r.t. the Falco version. And we need to expose it in an easier way for users.

About point 2: I also agree. In the comment [here](https://github.com/falcosecurity/event-generator/pull/31#pullrequestreview-434756749) I proposed a mapping Falco Engine version <=> fields <=> rules.
