### ISSUE TITLE
[FeatureRequest] process analysis / device trajectory

### ISSUE THREAD

**Issue by juju4** [falcosecurity/falco#129]
Hello,

It would be nice if falco could produce a full record of applications call.
something that can produce similar view that these products do
https://www.carbonblack.com/2016/05/10/patterns-of-attack-youre-looking-for-answers-not-just-indicators/
http://www.cisco.com/c/en/us/products/collateral/security/fireamp-endpoints/datasheet-c78-733181.html

Thanks

**Comment by ldegio** [comment]
Could you give us a bit more context on what you have in mind? A full sysdig capture around the time an alert is triggered?

**Comment by juju4** [comment]
Not the latter, even if it would be interesting too.

More to have a full record of executables launched on the system with process tree/forest, start/end time, user/group id, arguments.
A classical example is to show an office app or a browser starting a shell, some ifconfig/whoami command and ending with a root user app, shell or others.
Ideally the record is in a format which can be used visually easily (json for d3.js/elk?)

**Comment by ldegio** [comment]
oh, so something similar to the spy_users sysdig chisel https://github.com/draios/sysdig/blob/dev/userspace/sysdig/chisels/spy_users.lua.

Where would you like to store this data?

**Comment by mstemm** [comment]
And just to confirm, you don't want historical information, only a snapshot of the current state? I think with a sysdig capture around the time of the notification, you'd be able to visualize the current state fairly well.

**Comment by juju4** [comment]
spy_users is good but miss some stuff like end time, parent process
For example, I can't tell directly from spy_users if it's from an interactive shell, a cron, a shell trap or anything else
better if customizing output like
```
sysdig -c spy_users -p"%evt.num %evt.outputtime %evt.cpu %proc.name (%thread.tid) %proc.pname %evt.dir %evt.type %evt.info"
```
but -p doesn't seems as customizable as usual for chisel.

Yes, I want history.

A good example would be
http://www.d3noob.org/2014/03/visualize-linux-processes-via.html
with the addition of a time cursor (or play)
In this example, the input is csv format. I didn't found with a quick search if from a performance point of view csv or json is better.
sysdig can already output json but not for this chisel.

I think that's what needed
- able to customize chisel output with more data
- have json output
- after more a d3.js to display either a state/snapshot, either the full history.
- daemonize sysdig to record all the times which is what falco does if I'm not wrong. need to allow sub-tasks to do the chisel and record in specific log files.

is it correct?

**Comment by mstemm** [comment]
I think we'd want to have falco write a trace file (augmented with additional information if necessary) and keep the analysis half confined to a separate program.

So I think this overlaps quite a bit with https://github.com/draios/falco/issues/81, although I'll keep this issue open as well for now.

Generally for chisels the output format is defined by the chisel. the -p argument to sysdg is used when outputting a stream of events.
