### ISSUE TITLE
Does Falco provide debugging and tracing facilities?

### ISSUE THREAD

**Issue by rahul-kr4604** [falcosecurity/falco#1311]
**Motivation**
As we know Falco provides runtime detection mechanism. But apart from this, is it possible to debug the containers with the help of Falco?

**Feature**
Debugging and Tracing

**Comment by fntlnz** [comment]
@rahul-kr4604 can you elaborate a bit more? What kind of debugging are you trying to do?

**Comment by fntlnz** [comment]
Hi @rahul-kr4604 - thanks for reaching out. Can you elaborate a bit more? What kind of debugging are you trying to do?

**Comment by rahul-kr4604** [comment]
Hello @fntlnz,

In this feature we are looking for debugging and tracing options of Falco. As far as I know Falco is a "Runtime" detection tool, but is it possible to trace/debug the system call which triggered the events in Falco when used with eBPF?

Apart from above suppose an event occurs in the container, and I want information like:
How and when event is triggered?
Who triggered the event?
What resources are used by the event? To check the performance of resources.

Is it possible to achieve this from Falco with eBPF?

Thanks,

**Comment by fntlnz** [comment]
@rahul-kr4604 - When you use the eBPF driver Falco uses the same libraries that are used by sysdig OSS to do its detection magic. However, everything that Falco does is security related. If you want to see the syscalls happening, their parameters and the timestamp I think you should check out [sysdig](https://github.com/draios/sysdig) directly.
