### ISSUE TITLE
Deploying falco to AWS EKS managed node group nodes causes - detected an unsupported target system

### ISSUE THREAD

**Issue by tlaukkan** [falcosecurity/falco#1324]
**Describe the bug**

Deploying falco to AWS EKS managed node group nodes causes Detected an unsupported target system, please get in touch with the Falco community. 

* Running falco-driver-loader with: driver=module, compile=yes, download=yes
* Unloading falco module, if present
* Trying to dkms install falco module
* Running dkms build failed, couldn't find /var/lib/dkms/falco/85c88952b018fdbce2464222c3303229f5bfcfad/build/make.log
* Trying to load a system falco driver, if present
* Trying to find locally a prebuilt falco module for kernel 4.14.181-140.257.amzn2.x86_64, if present
Detected an unsupported target system, please get in touch with the Falco community

**How to reproduce it**

Attempt to deploy falco to kubernetes cluster with helm for example.

**Expected behaviour**

The falco module should load automatically from here:
https://dl.bintray.com/falcosecurity/driver/85c88952b018fdbce2464222c3303229f5bfcfad/

**Screenshots**

**Environment**

- Falco version:

docker.io/falcosecurity/falco:0.24.0

- System info:
AWS EKS managed node kernel 4.14.181-140.257.amzn2.x86_64

**Comment by fntlnz** [comment]
Hey @tlaukkan - can you share the actual log that you are getting when trying to download the module?
It should show us what is the link used.

The kernel you are reporting is correctly available from here:

https://dl.bintray.com/falcosecurity/driver/85c88952b018fdbce2464222c3303229f5bfcfad/falco_amazonlinux2_4.14.181-140.257.amzn2.x86_64_1.ko

While we find a solution, you can download that file in `/root/.falco/falco_amazonlinux2_4.14.181-140.257.amzn2.x86_64_1.ko` - then just start Falco again, the loader script will find and insert the module.

**Comment by tlaukkan** [comment]
Hi and thank you

I am running the docker container: docker.io/falcosecurity/falco:0.24.0 for which the console log is: 

    Running falco-driver-loader with: driver=module, compile=yes, download=yes
    Unloading falco module, if present
    Trying to dkms install falco module
    Running dkms build failed, couldn't find /var/lib/dkms/falco/85c88952b018fdbce2464222c3303229f5bfcfad/build/make.log
    Trying to load a system falco driver, if present
    Trying to find locally a prebuilt falco module for kernel 4.14.181-140.257.amzn2.x86_64, if present
    Detected an unsupported target system, please get in touch with the Falco community

As the container fails to start I am not able to do console login to the container and thus it is not easy to extract any other logs. I suppose I could mount log directories if I knew which paths to mount but that will take a little bit of time which I do not have right now. Is this the only way to get this issue forward? If so I can try to get it done tomorrow if you can give me pointers where in container directory structure the logs in question are located.

Kind regards,
Tommi

**Comment by tlaukkan** [comment]
Perhaps related to this: https://github.com/falcosecurity/charts/issues/9

**Comment by tlaukkan** [comment]
I added the etc mounts and this fixed the issue. The root cause was that I copied the kubernetes yaml files from minikube helm deployment and attempted to use them on AWS. I guess do to this the etc mount was not there.
