### ISSUE TITLE
Build Failure on Ubuntu 18.04

### ISSUE THREAD

**Issue by vitt-bagal** [falcosecurity/falco#1325]
**Describe the bug**

Build failure observed while building falco(v0.24.0) [from source](https://falco.org/docs/source/) on ubuntu 18.04.

**How to reproduce it**
```
apt install git cmake build-essential
apt install libssl-dev libyaml-dev libncurses-dev libc-ares-dev libprotobuf-dev protobuf-compiler libjq-dev libyaml-cpp-dev libgrpc++-dev protobuf-compiler-grpc libcurl4-openssl-dev libelf-dev
git clone https://github.com/falcosecurity/falco.git
cd falco && git checkout 0.24.0
mkdir -p build
cd build
cmake ..
make falco
```

**Expected behaviour**

Build should pass successfully.

**Environment**
- Falco version:
v0.24.0
- OS:
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
- Kernel:
Linux d3cd9ad03102 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Installation method:
	from source

Am I missing something here ? Any help would be appreciated.
Thanks...

**Comment by smijolovic** [comment]
Same here with CentOS 8.2....

My educated guess the link is OpenSSL.  Both 18.04 and 8.2 are using OpenSSL 1.1.1 library...clue to the issue:

[100%] Linking CXX executable falco
cd /home/rpmbuild/nimbus8/falco-build/falco-src/falco-0.24.0/build/userspace/falco && /usr/bin/cmake -E cmake_link_script CMakeFiles/falco.dir/link.t
xt --verbose=1
/usr/bin/c++  --std=c++0x -Wall -ggdb  -Wno-class-memaccess -O3 -fno-strict-aliasing -DNDEBUG   CMakeFiles/falco.dir/configuration.cpp.o CMakeFiles/f
alco.dir/logger.cpp.o CMakeFiles/falco.dir/falco_outputs.cpp.o CMakeFiles/falco.dir/event_drops.cpp.o CMakeFiles/falco.dir/statsfilewriter.cpp.o CMak
eFiles/falco.dir/falco.cpp.o CMakeFiles/falco.dir/__/__/sysdig-repo/sysdig-prefix/src/sysdig/userspace/sysdig/fields_info.cpp.o CMakeFiles/falco.dir/
webserver.cpp.o CMakeFiles/falco.dir/grpc_context.cpp.o CMakeFiles/falco.dir/grpc_server_impl.cpp.o CMakeFiles/falco.dir/grpc_request_context.cpp.o C
MakeFiles/falco.dir/grpc_server.cpp.o CMakeFiles/falco.dir/version.grpc.pb.cc.o CMakeFiles/falco.dir/version.pb.cc.o CMakeFiles/falco.dir/outputs.grp
c.pb.cc.o CMakeFiles/falco.dir/outputs.pb.cc.o CMakeFiles/falco.dir/schema.pb.cc.o  -o falco ../engine/libfalco_engine.a ../libsinsp/libsinsp.a ../..
/grpc-prefix/src/grpc/libs/opt/libgrpc.a ../../grpc-prefix/src/grpc/libs/opt/libgrpc++.a ../../grpc-prefix/src/grpc/libs/opt/protobuf/libprotobuf.a -
lyaml ../../yamlcpp-prefix/src/yamlcpp/libyaml-cpp.a ../../civetweb-prefix/src/civetweb//install/lib/libcivetweb.a ../libscap/libscap.a -lelf ../../g
rpc-prefix/src/grpc/libs/opt/libz.a ../../curl-prefix/src/curl/lib/.libs/libcurl.a ../../tbb-prefix/src/tbb/build/lib_release/libtbb.a ../../grpc-pre
fix/src/grpc/libs/opt/libgrpc.a ../../grpc-prefix/src/grpc/libs/opt/libgrpc++.a ../../grpc-prefix/src/grpc/libs/opt/protobuf/libprotobuf.a ../../jq-p
refix/src/jq/.libs/libjq.a ../../b64-prefix/src/b64/src/libb64.a -lrt -lanl ../../openssl-prefix/src/openssl/target/lib/libssl.a ../../openssl-prefix
/src/openssl/target/lib/libcrypto.a ../../luajit-prefix/src/luajit/src/libluajit.a -ldl -lpthread ../../lpeg-prefix/src/lpeg/build/lpeg.a ../../lyaml
-prefix/src/lyaml/ext/yaml/.libs/yaml.a -lyaml 
../../curl-prefix/src/curl/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `Curl_ossl_sha256sum':
openssl.c:(.text+0x12c): undefined reference to `EVP_MD_CTX_new'
openssl.c:(.text+0x167): undefined reference to `EVP_MD_CTX_free'
../../curl-prefix/src/curl/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `Curl_ossl_md5sum':
openssl.c:(.text+0x19c): undefined reference to `EVP_MD_CTX_new'
openssl.c:(.text+0x1d7): undefined reference to `EVP_MD_CTX_free'
../../curl-prefix/src/curl/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `Curl_ossl_version':
openssl.c:(.text+0x1134): undefined reference to `OpenSSL_version_num'
../../curl-prefix/src/curl/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `ossl_connect_step1':
openssl.c:(.text+0x1a91): undefined reference to `TLS_client_method'
openssl.c:(.text+0x1c43): undefined reference to `SSL_CTX_set_options'
openssl.c:(.text+0x1d53): undefined reference to `SSL_CTX_set_ciphersuites'
openssl.c:(.text+0x1e5c): undefined reference to `SSL_CTX_set_keylog_callback'
openssl.c:(.text+0x22bd): undefined reference to `OPENSSL_sk_pop_free'
openssl.c:(.text+0x2d35): undefined reference to `OPENSSL_sk_pop'
openssl.c:(.text+0x2d72): undefined reference to `OPENSSL_sk_num'
openssl.c:(.text+0x2da0): undefined reference to `OPENSSL_sk_pop_free'
../../curl-prefix/src/curl/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function `servercert':
openssl.c:(.text+0x32bb): undefined reference to `X509_get0_notBefore'
openssl.c:(.text+0x3319): undefined reference to `X509_get0_notAfter'
openssl.c:(.text+0x34e5): undefined reference to `OPENSSL_sk_num'
openssl.c:(.text+0x3551): undefined reference to `OPENSSL_sk_value'
openssl.c:(.text+0x3657): undefined reference to `X509_get_X509_PUBKEY'
openssl.c:(.text+0x3695): undefined reference to `X509_get_X509_PUBKEY'
openssl.c:(.text+0x3787): undefined reference to `OPENSSL_sk_num'
openssl.c:(.text+0x37e9): undefined reference to `OPENSSL_sk_value'
openssl.c:(.text+0x38b9): undefined reference to `X509_get_version'
openssl.c:(.text+0x3a4b): undefined reference to `X509_get0_extensions'
openssl.c:(.text+0x3a58): undefined reference to `OPENSSL_sk_num'
openssl.c:(.text+0x3a74): undefined reference to `OPENSSL_sk_num'
openssl.c:(.text+0x3a88): undefined reference to `OPENSSL_sk_value'
openssl.c:(.text+0x3bc2): undefined reference to `OPENSSL_sk_num'
openssl.c:(.text+0x3bdc): undefined reference to `X509_get0_notBefore'
openssl.c:(.text+0x3c34): undefined reference to `X509_get0_notAfter'
openssl.c:(.text+0x412c): undefined reference to `EVP_PKEY_get0_RSA'
openssl.c:(.text+0x414c): undefined reference to `RSA_get0_key'
openssl.c:(.text+0x41f4): undefined reference to `EVP_PKEY_get0_DSA'
openssl.c:(.text+0x421a): undefined reference to `DSA_get0_pqg'
openssl.c:(.text+0x422c): undefined reference to `DSA_get0_key'
openssl.c:(.text+0x42cc): undefined reference to `EVP_PKEY_get0_DH'
openssl.c:(.text+0x42f2): undefined reference to `DH_get0_pqg'
openssl.c:(.text+0x4304): undefined reference to `DH_get0_key'
openssl.c:(.text+0x4685): undefined reference to `ASN1_STRING_get0_data'
openssl.c:(.text+0x46ad): undefined reference to `ASN1_STRING_get0_data'
openssl.c:(.text+0x4735): undefined reference to `ASN1_STRING_get0_data'
openssl.c:(.text+0x4c83): undefined reference to `ASN1_STRING_get0_data'
collect2: error: ld returned 1 exit status
make[3]: *** [userspace/falco/CMakeFiles/falco.dir/build.make:385: userspace/falco/falco] Error 1
make[3]: Leaving directory '/home/rpmbuild/nimbus8/falco-build/falco-src/falco-0.24.0/build'
make[2]: *** [CMakeFiles/Makefile2:7585: userspace/falco/CMakeFiles/falco.dir/all] Error 2
make[2]: Leaving directory '/home/rpmbuild/nimbus8/falco-build/falco-src/falco-0.24.0/build'
make[1]: *** [CMakeFiles/Makefile2:7597: userspace/falco/CMakeFiles/falco.dir/rule] Error 2
make[1]: Leaving directory '/home/rpmbuild/nimbus8/falco-build/falco-src/falco-0.24.0/build'
make: *** [Makefile:2594: falco] Error 2

**Comment by smijolovic** [comment]
The linker is most likely pointing to the wrong version of SSL.

https://stackoverflow.com/questions/46768071/openssl-linking-undefined-reference-evp-md-ctx-new-and-fre

**Comment by smijolovic** [comment]
Yep...

OpenSSL.cmake for build deps pulls openSSL 1.0.2.

To test, prior to cmake, added to test automation:

sed -i 's/URL.*/URL "https:\/\/github.com\/openssl\/openssl\/archive\/OpenSSL_1_1_1c.tar.gz"/g' $FALCO_SRC_DIR/cmake/modules/OpenSSL.cmake
sed -i '/URL_HASH/d' $FALCO_SRC_DIR/cmake/modules/OpenSSL.cmake

To pull 1.1.1c matching my backported SSL from CentOS8. Builds clean.

Good news to report on the 0.24.0 bpf driver - fix works!  Will post there too.

I think if linkage is required....maybe pull version by querying openssl-devel version based on OS type (apt, dnf, etc.), and use that as the OpenSSL.cmake URL field to pull the matching version...works for uniformity, but does complicate the URL_HASH validation. Maybe a BUILD_DEPS way to exclude specifi dependencies like openssl.

**Comment by vitt-bagal** [comment]
@smijolovic Though my error logs are different than yours I tried your fix But it did not work. 
Error logs
```
/home/test/falco/build/userspace/falco/version.pb.h:324:13: warning: In the GNU C Library, "minor" is defined
 by <sys/sysmacros.h>. For historical compatibility, it is
 currently defined by <sys/types.h> as well, but we plan to
 remove this soon. To use "minor", include <sys/sysmacros.h>
 directly. If you did not intend to use a system-defined macro
 "minor", you should undefine it after including <sys/types.h>.
 inline ::google::protobuf::uint32 response::minor() const {
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                                                                              
/home/test/falco/userspace/falco/grpc_server.cpp:56:37: error: variable or field 'gpr_log_dispatcher_func' declared void
 static void gpr_log_dispatcher_func(gpr_log_func_args* args)
                                     ^~~~~~~~~~~~~~~~~
/home/test/falco/userspace/falco/grpc_server.cpp:56:37: error: 'gpr_log_func_args' was not declared in this scope
/home/test/falco/userspace/falco/grpc_server.cpp:56:37: note: suggested alternative: 'gpr_atm_full_cas'
 static void gpr_log_dispatcher_func(gpr_log_func_args* args)
                                     ^~~~~~~~~~~~~~~~~
                                     gpr_atm_full_cas
/home/test/falco/userspace/falco/grpc_server.cpp:56:56: error: 'args' was not declared in this scope
 static void gpr_log_dispatcher_func(gpr_log_func_args* args)
                                                        ^~~~
/home/test/falco/userspace/falco/grpc_server.cpp:56:56: note: suggested alternative: 'abs'
 static void gpr_log_dispatcher_func(gpr_log_func_args* args)
                                                        ^~~~
                                                        abs
/home/test/falco/userspace/falco/grpc_server.cpp: In member function 'void falco::grpc::server::init(std::__cxx11::string, int, std::__cxx11::string, std::__cxx11::string, std::__cxx11::string, std::__cxx11::string)':
/home/test/falco/userspace/falco/grpc_server.cpp:150:25: error: 'GPR_LOG_SEVERITY_ERROR' was not declared in this scope
   gpr_set_log_verbosity(GPR_LOG_SEVERITY_ERROR);
                         ^~~~~~~~~~~~~~~~~~~~~~
/home/test/falco/userspace/falco/grpc_server.cpp:150:25: note: suggested alternative: 'CURLE_WRITE_ERROR'
   gpr_set_log_verbosity(GPR_LOG_SEVERITY_ERROR);
                         ^~~~~~~~~~~~~~~~~~~~~~
                         CURLE_WRITE_ERROR
/home/test/falco/userspace/falco/grpc_server.cpp:150:3: error: 'gpr_set_log_verbosity' was not declared in this scope
   gpr_set_log_verbosity(GPR_LOG_SEVERITY_ERROR);
   ^~~~~~~~~~~~~~~~~~~~~
/home/test/falco/userspace/falco/grpc_server.cpp:150:3: note: suggested alternative: 'gpr_ref_non_zero'
   gpr_set_log_verbosity(GPR_LOG_SEVERITY_ERROR);
   ^~~~~~~~~~~~~~~~~~~~~
   gpr_ref_non_zero
/home/test/falco/userspace/falco/grpc_server.cpp:153:25: error: 'GPR_LOG_SEVERITY_DEBUG' was not declared in this scope
   gpr_set_log_verbosity(GPR_LOG_SEVERITY_DEBUG);
                         ^~~~~~~~~~~~~~~~~~~~~~
/home/test/falco/userspace/falco/grpc_server.cpp:153:25: note: suggested alternative: 'CURL_VERSION_DEBUG'
   gpr_set_log_verbosity(GPR_LOG_SEVERITY_DEBUG);
                         ^~~~~~~~~~~~~~~~~~~~~~
                         CURL_VERSION_DEBUG
/home/test/falco/userspace/falco/grpc_server.cpp:158:25: error: 'GPR_LOG_SEVERITY_INFO' was not declared in this scope
   gpr_set_log_verbosity(GPR_LOG_SEVERITY_INFO);
                         ^~~~~~~~~~~~~~~~~~~~~
/home/test/falco/userspace/falco/grpc_server.cpp:158:25: note: suggested alternative: 'GPR_EVENT_INIT'
   gpr_set_log_verbosity(GPR_LOG_SEVERITY_INFO);
                         ^~~~~~~~~~~~~~~~~~~~~
                         GPR_EVENT_INIT
/home/test/falco/userspace/falco/grpc_server.cpp:161:2: error: 'gpr_log_verbosity_init' was not declared in this scope
  gpr_log_verbosity_init();
  ^~~~~~~~~~~~~~~~~~~~~~
/home/test/falco/userspace/falco/grpc_server.cpp:161:2: note: suggested alternative: 'gpr_event_init'
  gpr_log_verbosity_init();
  ^~~~~~~~~~~~~~~~~~~~~~
  gpr_event_init
/home/test/falco/userspace/falco/grpc_server.cpp:162:23: error: 'gpr_log_dispatcher_func' was not declared in this scope
  gpr_set_log_function(gpr_log_dispatcher_func);
                       ^~~~~~~~~~~~~~~~~~~~~~~
/home/test/falco/userspace/falco/grpc_server.cpp:162:2: error: 'gpr_set_log_function' was not declared in this scope
  gpr_set_log_function(gpr_log_dispatcher_func);
  ^~~~~~~~~~~~~~~~~~~~
/home/test/falco/userspace/falco/grpc_server.cpp:162:2: note: suggested alternative: 'curl_lock_function'
  gpr_set_log_function(gpr_log_dispatcher_func);
  ^~~~~~~~~~~~~~~~~~~~
  curl_lock_function
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-class-memaccess'
userspace/falco/CMakeFiles/falco.dir/build.make:361: recipe for target 'userspace/falco/CMakeFiles/falco.dir/grpc_server.cpp.o' failed
make[3]: *** [userspace/falco/CMakeFiles/falco.dir/grpc_server.cpp.o] Error 1
CMakeFiles/Makefile2:7355: recipe for target 'userspace/falco/CMakeFiles/falco.dir/all' failed
make[2]: *** [userspace/falco/CMakeFiles/falco.dir/all] Error 2
CMakeFiles/Makefile2:7367: recipe for target 'userspace/falco/CMakeFiles/falco.dir/rule' failed
make[1]: *** [userspace/falco/CMakeFiles/falco.dir/rule] Error 2
Makefile:2513: recipe for target 'falco' failed
make: *** [falco] Error 2

```

**Comment by smijolovic** [comment]
Sorry that it didn't work.  I'll create a new issue and remove from here to get focus on this one.

**Comment by fntlnz** [comment]
Hey! @vitt-bagal Thanks for opening  this one, it's very useful to know where Falco cannot be compiled for us to keep the docs and the sources up to date.

I just tested this and confirm that the error happens. Ubuntu 18.04 is a relatively old distribution for the dependencies that Falco uses, this is why just following the Ubuntu guide [here](https://falco.org/docs/source/#debian--ubuntu) does not work for you.

We probably need to have an Ubuntu 18.04 specific guide in the docs, since that version does not work without the bundled deps.


Here are the steps to make it work:

Install some build deps:
```bash
sudo apt install git cmake build-essential autoconf m4 libtool -y
```

Build:
```
cd falco
mkdir build
cd build
cmake -DUSE_BUNDLED_DEPS=On ..
make -j16 falco
```

**Comment by fntlnz** [comment]
Hey @vitt-bagal I have a patch to fix the compilation issues you are seeing, can you please take a look?

https://github.com/falcosecurity/falco/pull/1353

Thank you!

**Comment by vitt-bagal** [comment]
@fntlnz I could build falco successfully. I added one extra dep. `pkg-config` to fix cmake error `pkg-config binary not found`
Thanks...

**Comment by fntlnz** [comment]
Thanks for testing this for pointing that out @vitt-bagal ! I updated the build dependencies documentation here https://github.com/falcosecurity/falco-website/pull/237/files#diff-18e772edba688390ac96942af7ca113cR82

**Comment by dandenkijin** [comment]
I am having this same build issue on my current system. This occurs regardless of using bundled apps or not, it seems. 

```
zsh/2 14216  (git)-[master]-% inxi -S
System:
  Host: grimoire Kernel: 6.13.0-1-cachyos arch: x86_64 bits: 64
  Desktop: Hyprland v: 0.46.2 Distro: Obarun rolling
```

Here is the error:
```bash
[ 78%] Built target falco_engine
[ 78%] Building CXX object userspace/falco/CMakeFiles/falco_application.dir/grpc_server.cpp.o
[ 78%] Building CXX object userspace/falco/CMakeFiles/falco_application.dir/schema.pb.cc.o
/home/denkijin/.cache/paru/clone/falco/src/falco-0.39.2/userspace/falco/grpc_server.cpp:57:13: error: variable or field ‘gpr_log_dispatcher_func’ declared void
   57 | static void gpr_log_dispatcher_func(gpr_log_func_args* args) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~
/home/denkijin/.cache/paru/clone/falco/src/falco-0.39.2/userspace/falco/grpc_server.cpp:57:37: error: ‘gpr_log_func_args’ was not declared in this scope
   57 | static void gpr_log_dispatcher_func(gpr_log_func_args* args) {
      |                                     ^~~~~~~~~~~~~~~~~
/home/denkijin/.cache/paru/clone/falco/src/falco-0.39.2/userspace/falco/grpc_server.cpp:57:56: error: ‘args’ was not declared in this scope
   57 | static void gpr_log_dispatcher_func(gpr_log_func_args* args) {
      |                                                        ^~~~
/home/denkijin/.cache/paru/clone/falco/src/falco-0.39.2/userspace/falco/grpc_server.cpp: In member function ‘void falco::grpc::server::init(const std::string&, int, const std::string&, const std::string&, const std::string&, const std::string&)’:
/home/denkijin/.cache/paru/clone/falco/src/falco-0.39.2/userspace/falco/grpc_server.cpp:142:39: error: ‘GPR_LOG_SEVERITY_ERROR’ was not declared in this scope
  142 |                 gpr_set_log_verbosity(GPR_LOG_SEVERITY_ERROR);
      |                                       ^~~~~~~~~~~~~~~~~~~~~~
/home/denkijin/.cache/paru/clone/falco/src/falco-0.39.2/userspace/falco/grpc_server.cpp:142:17: error: ‘gpr_set_log_verbosity’ was not declared in this scope
  142 |                 gpr_set_log_verbosity(GPR_LOG_SEVERITY_ERROR);
      |                 ^~~~~~~~~~~~~~~~~~~~~
/home/denkijin/.cache/paru/clone/falco/src/falco-0.39.2/userspace/falco/grpc_server.cpp:145:39: error: ‘GPR_LOG_SEVERITY_DEBUG’ was not declared in this scope
  145 |                 gpr_set_log_verbosity(GPR_LOG_SEVERITY_DEBUG);
      |                                       ^~~~~~~~~~~~~~~~~~~~~~
/home/denkijin/.cache/paru/clone/falco/src/falco-0.39.2/userspace/falco/grpc_server.cpp:150:39: error: ‘GPR_LOG_SEVERITY_INFO’ was not declared in this scope
  150 |                 gpr_set_log_verbosity(GPR_LOG_SEVERITY_INFO);
      |                                       ^~~~~~~~~~~~~~~~~~~~~
/home/denkijin/.cache/paru/clone/falco/src/falco-0.39.2/userspace/falco/grpc_server.cpp:153:9: error: ‘gpr_log_verbosity_init’ was not declared in this scope
  153 |         gpr_log_verbosity_init();
      |         ^~~~~~~~~~~~~~~~~~~~~~
/home/denkijin/.cache/paru/clone/falco/src/falco-0.39.2/userspace/falco/grpc_server.cpp:154:30: error: ‘gpr_log_dispatcher_func’ was not declared in this scope
  154 |         gpr_set_log_function(gpr_log_dispatcher_func);
      |                              ^~~~~~~~~~~~~~~~~~~~~~~
/home/denkijin/.cache/paru/clone/falco/src/falco-0.39.2/userspace/falco/grpc_server.cpp:154:9: error: ‘gpr_set_log_function’ was not declared in this scope
  154 |         gpr_set_log_function(gpr_log_dispatcher_func);
      |         ^~~~~~~~~~~~~~~~~~~~
make[3]: *** [userspace/falco/CMakeFiles/falco_application.dir/build.make:828: userspace/falco/CMakeFiles/falco_application.dir/grpc_server.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:1992: userspace/falco/CMakeFiles/falco_application.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2051: userspace/falco/CMakeFiles/falco.dir/rule] Error 2
make: *** [Makefile:722: falco] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by dandenkijin** [comment]
Not trying to resurrect a dead thread with other issues, but I wanted to document the memory issue (seemingly) mentioned in the last comment
```bash
[ 78%] Built target falco_engine
[ 80%] Building CXX object userspace/falco/CMakeFiles/falco_application.dir/app/actions/list_fields.cpp.o
[ 79%] Building CXX object userspace/falco/CMakeFiles/falco_application.dir/app/actions/init_inspectors.cpp.o
[ 80%] Building CXX object userspace/falco/CMakeFiles/falco_application.dir/app/actions/helpers_inspector.cpp.o
[ 80%] Building CXX object userspace/falco/CMakeFiles/falco_application.dir/app/actions/init_outputs.cpp.o
[ 80%] Building CXX object userspace/falco/CMakeFiles/falco_application.dir/app/actions/list_plugins.cpp.o
[ 80%] Building CXX object userspace/falco/CMakeFiles/falco_application.dir/app/actions/init_falco_engine.cpp.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[3]: *** [userspace/falco/CMakeFiles/falco_application.dir/build.make:240: userspace/falco/CMakeFiles/falco_application.dir/app/actions/init_inspectors.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[3]: *** [userspace/falco/CMakeFiles/falco_application.dir/build.make:254: userspace/falco/CMakeFiles/falco_application.dir/app/actions/init_outputs.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:1992: userspace/falco/CMakeFiles/falco_application.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2051: userspace/falco/CMakeFiles/falco.dir/rule] Error 2
make: *** [Makefile:722: falco] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by dandenkijin** [comment]
ok, using clang, it goes to 90% but fails on grpc

```bash
[ 97%] Building CXX object userspace/falco/CMakeFiles/falco_application.dir/version.grpc.pb.cc.o
/home/denkijin/.cache/paru/clone/falco/src/falco-0.39.2/userspace/falco/grpc_server.cpp:57:37: error: unknown type name 'gpr_log_func_args'
   57 | static void gpr_log_dispatcher_func(gpr_log_func_args* args) {
      |                                     ^
/home/denkijin/.cache/paru/clone/falco/src/falco-0.39.2/userspace/falco/grpc_server.cpp:60:7: error: use of undeclared identifier 'GPR_LOG_SEVERITY_ERROR'
   60 |         case GPR_LOG_SEVERITY_ERROR:
      |              ^
1 warning generated.
[ 97%] Building CXX object userspace/falco/CMakeFiles/falco_application.dir/version.pb.cc.o
/home/denkijin/.cache/paru/clone/falco/src/falco-0.39.2/userspace/falco/grpc_server.cpp:63:7: error: use of undeclared identifier 'GPR_LOG_SEVERITY_DEBUG'
   63 |         case GPR_LOG_SEVERITY_DEBUG:
      |              ^
/home/denkijin/.cache/paru/clone/falco/src/falco-0.39.2/userspace/falco/grpc_server.cpp:142:25: error: use of undeclared identifier 'GPR_LOG_SEVERITY_ERROR'
  142 |                 gpr_set_log_verbosity(GPR_LOG_SEVERITY_ERROR);
      |                                       ^
/home/denkijin/.cache/paru/clone/falco/src/falco-0.39.2/userspace/falco/grpc_server.cpp:145:25: error: use of undeclared identifier 'GPR_LOG_SEVERITY_DEBUG'
  145 |                 gpr_set_log_verbosity(GPR_LOG_SEVERITY_DEBUG);
      |                                       ^
/home/denkijin/.cache/paru/clone/falco/src/falco-0.39.2/userspace/falco/grpc_server.cpp:150:25: error: use of undeclared identifier 'GPR_LOG_SEVERITY_INFO'
  150 |                 gpr_set_log_verbosity(GPR_LOG_SEVERITY_INFO);
      |                                       ^
/home/denkijin/.cache/paru/clone/falco/src/falco-0.39.2/userspace/falco/grpc_server.cpp:153:2: error: use of undeclared identifier 'gpr_log_verbosity_init'
  153 |         gpr_log_verbosity_init();
      |         ^
2 warnings generated.
[ 97%] Building CXX object userspace/falco/CMakeFiles/falco_application.dir/outputs.grpc.pb.cc.o
[ 98%] Building CXX object userspace/falco/CMakeFiles/falco_application.dir/outputs.pb.cc.o
[ 98%] Building CXX object userspace/falco/CMakeFiles/falco_application.dir/schema.pb.cc.o
1 warning and 7 errors generated.
make[3]: *** [userspace/falco/CMakeFiles/falco_application.dir/build.make:828: userspace/falco/CMakeFiles/falco_application.dir/grpc_server.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
2 warnings generated.
2 warnings generated.
make[2]: *** [CMakeFiles/Makefile2:1992: userspace/falco/CMakeFiles/falco_application.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2051: userspace/falco/CMakeFiles/falco.dir/rule] Error 2
make: *** [Makefile:722: falco] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```
