### ISSUE TITLE
Falco 0.24.0 build failure on CentOS 8.x using 1.1.x OpenSSL

### ISSUE THREAD

**Issue by smijolovic** [falcosecurity/falco#1328]
CentOS 8.2 build of falco fails with the following error:

[100%] Linking CXX executable falco
cd /home/rpmbuild/nimbus8/falco-build/falco-src/falco-0.24.0/build/userspace/falco && /usr/bin/cmake -E cmake_link_script CMakeFiles/falco.dir/link.t
xt --verbose=1
/usr/bin/c++ --std=c++0x -Wall -ggdb -Wno-class-memaccess -O3 -fno-strict-aliasing -DNDEBUG CMakeFiles/falco.dir/configuration.cpp.o CMakeFiles/f
alco.dir/logger.cpp.o CMakeFiles/falco.dir/falco_outputs.cpp.o CMakeFiles/falco.dir/event_drops.cpp.o CMakeFiles/falco.dir/statsfilewriter.cpp.o CMak
eFiles/falco.dir/falco.cpp.o CMakeFiles/falco.dir///sysdig-repo/sysdig-prefix/src/sysdig/userspace/sysdig/fields_info.cpp.o CMakeFiles/falco.dir/
webserver.cpp.o CMakeFiles/falco.dir/grpc_context.cpp.o CMakeFiles/falco.dir/grpc_server_impl.cpp.o CMakeFiles/falco.dir/grpc_request_context.cpp.o C
MakeFiles/falco.dir/grpc_server.cpp.o CMakeFiles/falco.dir/version.grpc.pb.cc.o CMakeFiles/falco.dir/version.pb.cc.o CMakeFiles/falco.dir/outputs.grp
c.pb.cc.o CMakeFiles/falco.dir/outputs.pb.cc.o CMakeFiles/falco.dir/schema.pb.cc.o -o falco ../engine/libfalco_engine.a ../libsinsp/libsinsp.a ../..
/grpc-prefix/src/grpc/libs/opt/libgrpc.a ../../grpc-prefix/src/grpc/libs/opt/libgrpc++.a ../../grpc-prefix/src/grpc/libs/opt/protobuf/libprotobuf.a -
lyaml ../../yamlcpp-prefix/src/yamlcpp/libyaml-cpp.a ../../civetweb-prefix/src/civetweb//install/lib/libcivetweb.a ../libscap/libscap.a -lelf ../../g
rpc-prefix/src/grpc/libs/opt/libz.a ../../curl-prefix/src/curl/lib/.libs/libcurl.a ../../tbb-prefix/src/tbb/build/lib_release/libtbb.a ../../grpc-pre
fix/src/grpc/libs/opt/libgrpc.a ../../grpc-prefix/src/grpc/libs/opt/libgrpc++.a ../../grpc-prefix/src/grpc/libs/opt/protobuf/libprotobuf.a ../../jq-p
refix/src/jq/.libs/libjq.a ../../b64-prefix/src/b64/src/libb64.a -lrt -lanl ../../openssl-prefix/src/openssl/target/lib/libssl.a ../../openssl-prefix
/src/openssl/target/lib/libcrypto.a ../../luajit-prefix/src/luajit/src/libluajit.a -ldl -lpthread ../../lpeg-prefix/src/lpeg/build/lpeg.a ../../lyaml
-prefix/src/lyaml/ext/yaml/.libs/yaml.a -lyaml
../../curl-prefix/src/curl/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function Curl_ossl_sha256sum': openssl.c:(.text+0x12c): undefined reference to EVP_MD_CTX_new'
openssl.c:(.text+0x167): undefined reference to EVP_MD_CTX_free' ../../curl-prefix/src/curl/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function Curl_ossl_md5sum':
openssl.c:(.text+0x19c): undefined reference to EVP_MD_CTX_new' openssl.c:(.text+0x1d7): undefined reference to EVP_MD_CTX_free'
../../curl-prefix/src/curl/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function Curl_ossl_version': openssl.c:(.text+0x1134): undefined reference to OpenSSL_version_num'
../../curl-prefix/src/curl/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function ossl_connect_step1': openssl.c:(.text+0x1a91): undefined reference to TLS_client_method'
openssl.c:(.text+0x1c43): undefined reference to SSL_CTX_set_options' openssl.c:(.text+0x1d53): undefined reference to SSL_CTX_set_ciphersuites'
openssl.c:(.text+0x1e5c): undefined reference to SSL_CTX_set_keylog_callback' openssl.c:(.text+0x22bd): undefined reference to OPENSSL_sk_pop_free'
openssl.c:(.text+0x2d35): undefined reference to OPENSSL_sk_pop' openssl.c:(.text+0x2d72): undefined reference to OPENSSL_sk_num'
openssl.c:(.text+0x2da0): undefined reference to OPENSSL_sk_pop_free' ../../curl-prefix/src/curl/lib/.libs/libcurl.a(libcurl_la-openssl.o): In function servercert':
openssl.c:(.text+0x32bb): undefined reference to X509_get0_notBefore' openssl.c:(.text+0x3319): undefined reference to X509_get0_notAfter'
openssl.c:(.text+0x34e5): undefined reference to OPENSSL_sk_num' openssl.c:(.text+0x3551): undefined reference to OPENSSL_sk_value'
openssl.c:(.text+0x3657): undefined reference to X509_get_X509_PUBKEY' openssl.c:(.text+0x3695): undefined reference to X509_get_X509_PUBKEY'
openssl.c:(.text+0x3787): undefined reference to OPENSSL_sk_num' openssl.c:(.text+0x37e9): undefined reference to OPENSSL_sk_value'
openssl.c:(.text+0x38b9): undefined reference to X509_get_version' openssl.c:(.text+0x3a4b): undefined reference to X509_get0_extensions'
openssl.c:(.text+0x3a58): undefined reference to OPENSSL_sk_num' openssl.c:(.text+0x3a74): undefined reference to OPENSSL_sk_num'
openssl.c:(.text+0x3a88): undefined reference to OPENSSL_sk_value' openssl.c:(.text+0x3bc2): undefined reference to OPENSSL_sk_num'
openssl.c:(.text+0x3bdc): undefined reference to X509_get0_notBefore' openssl.c:(.text+0x3c34): undefined reference to X509_get0_notAfter'
openssl.c:(.text+0x412c): undefined reference to EVP_PKEY_get0_RSA' openssl.c:(.text+0x414c): undefined reference to RSA_get0_key'
openssl.c:(.text+0x41f4): undefined reference to EVP_PKEY_get0_DSA' openssl.c:(.text+0x421a): undefined reference to DSA_get0_pqg'
openssl.c:(.text+0x422c): undefined reference to DSA_get0_key' openssl.c:(.text+0x42cc): undefined reference to EVP_PKEY_get0_DH'
openssl.c:(.text+0x42f2): undefined reference to DH_get0_pqg' openssl.c:(.text+0x4304): undefined reference to DH_get0_key'
openssl.c:(.text+0x4685): undefined reference to ASN1_STRING_get0_data' openssl.c:(.text+0x46ad): undefined reference to ASN1_STRING_get0_data'
openssl.c:(.text+0x4735): undefined reference to ASN1_STRING_get0_data' openssl.c:(.text+0x4c83): undefined reference to ASN1_STRING_get0_data'
collect2: error: ld returned 1 exit status
make[3]: *** [userspace/falco/CMakeFiles/falco.dir/build.make:385: userspace/falco/falco] Error 1
make[3]: Leaving directory '/home/rpmbuild/nimbus8/falco-build/falco-src/falco-0.24.0/build'
make[2]: *** [CMakeFiles/Makefile2:7585: userspace/falco/CMakeFiles/falco.dir/all] Error 2
make[2]: Leaving directory '/home/rpmbuild/nimbus8/falco-build/falco-src/falco-0.24.0/build'
make[1]: *** [CMakeFiles/Makefile2:7597: userspace/falco/CMakeFiles/falco.dir/rule] Error 2
make[1]: Leaving directory '/home/rpmbuild/nimbus8/falco-build/falco-src/falco-0.24.0/build'
make: *** [Makefile:2594: falco] Error 2

The linker is pointing to an older version of SSL.
In falco-0.24.0/build/openssl-prefix/src:
OpenSSL_1_0_2n.tar.gz

Since the version is < 1.1.0....the linker and headers are mismatched, so it fails to find the 1.1.x references.

OpenSSL.cmake for build deps pulls openSSL 1.0.2.

To test, prior to cmake, added to test automation:

sed -i 's/URL.*/URL "https://github.com/openssl/openssl/archive/OpenSSL_1_1_1c.tar.gz"/g' $FALCO_SRC_DIR/cmake/modules/OpenSSL.cmake
sed -i '/URL_HASH/d' $FALCO_SRC_DIR/cmake/modules/OpenSSL.cmake

To pull 1.1.1c matching my backported SSL from CentOS8. Builds clean.

Good news to report on the 0.24.0 bpf driver - fix works! Will post there too.

I think if linkage is required....maybe pull version by querying openssl-devel version based on OS type (apt, dnf, etc.), and use that as the OpenSSL.cmake URL field to pull the matching version...works for uniformity, but does complicate the URL_HASH validation. Maybe a BUILD_DEPS way to exclude specific dependencies like openssl might make sense.

**Comment by fntlnz** [comment]
@smijolovic can you please test building the changes in my PR here?

https://github.com/falcosecurity/falco/pull/1353

Thank you!
