### ISSUE TITLE
curl: (22) The requested URL returned error: 404 Not Found

### ISSUE THREAD

**Issue by brantcolemanthis** [falcosecurity/falco#1329]
Hi! I was needed to update falco in kubernetes cluster and i get error due to the url link to download prebuilt module is not found. How i can workaround/fix this issue? I deployed falco from yaml and tried several version include latest, 0.17.0, 0.24.0 and etc.
Log output
> * Setting up /usr/src links from host
> * Running falco-driver-loader with: driver=module, compile=yes, download=yes
> * Unloading falco module, if present
> * Trying to dkms install falco module
> * Running dkms build failed, couldn't find /var/lib/dkms/falco/85c88952b018fdbce2464222c3303229f5bfcfad/build/make.log
> * Trying to load a system falco driver, if present
> * Trying to find locally a prebuilt falco module for kernel 5.7.2-050702-generic, if present
> * Trying to download prebuilt module from https://dl.bintray.com/falcosecurity/driver/85c88952b018fdbce2464222c3303229f5bfcfad/falco_ubuntu-generic_5.7.2-050702-generic_202006101934.ko
> curl: (22) The requested URL returned error: 404 Not Found
> Download failed, consider compiling your own falco module and loading it or getting in touch with the Falco community
> Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded.. Exiting.

**Comment by DannyPat44** [comment]
I am getting the same issue trying to deploy this to Minikube. 
![image](https://user-images.githubusercontent.com/11543716/88595716-83b6ed80-d031-11ea-8c7f-9f7724753fb5.png)

**Comment by DannyPat44** [comment]
Actually I fixed my issue by updating the version of mini-kube I was deploying to!

**Comment by brantcolemanthis** [comment]
I resolved this problem by compiling prebuilt falco module my own as described here (https://falco.org/docs/source/), upload it to registry, and have set DRIVERS_REPO env to valid url of *.ko. Then it's works.
```
falco_for_kubernetes$ kubectl logs falco-daemonset-xxxxx falco
* Setting up /usr/src links from host
* Running falco-driver-loader with: driver=module, compile=yes, download=yes
* Unloading falco module, if present
* Trying to dkms install falco module
* Running dkms build failed, couldn't find /var/lib/dkms/falco/85c88952b018fdbce2464222c3303229f5bfcfad/build/make.log
* Trying to load a system falco driver, if present
* Trying to find locally a prebuilt falco module for kernel 5.7.2-050702-generic, if present
* Trying to download prebuilt module from https://my-registry/drivers/85c88952b018fdbce2464222c3303229f5bfcfad/falco_ubuntu-generic_5.7.2-050702-generic_202006101934.ko
* Download succeeded
* Success: falco module loaded
```
