### ISSUE TITLE
Can't load eBPF probe in GKE

### ISSUE THREAD

**Issue by pogao** [falcosecurity/falco#1331]
We are migrating our Falco deployment to version 0.24.0 in GKE running v1.15.11-gke.15 with Ubuntu nodes running the standard kernel for that Kubelet version (5.0.0-1032-gke). Since there's no pre-compiled eBPF probe as it used to be in the earlier version we're running, we are compiling it on the fly when the container starts. The eBPF probe seems to be built correctly by `falco-driver-loader` but Falco errors out and states it can't load the module when it starts up.

**How to reproduce it**
* Create Daemonset with official Falco image (mounting all recommended volumes, according to the documentation).
* Containers should fail with the message below.

**Expected behaviour**
To have the eBPF probe be compiled and loaded correctly.

**Screenshots**
```
# falco-driver-loader
* Running falco-driver-loader with: driver=bpf, compile=yes, download=yes
* Mounting debugfs
* Found kernel config at /host/boot/config-5.0.0-1032-gke
* Skipping compile, eBPF probe is already present in /root/.falco/falco_ubuntu-generic_5.0.0-1032-gke_33.o
* Skipping download, eBPF probe is already present in /root/.falco/falco_ubuntu-generic_5.0.0-1032-gke_33.o
* eBPF probe located in /root/.falco/falco_ubuntu-generic_5.0.0-1032-gke_33.o
* Success: eBPF probe symlinked to /root/.falco/falco-bpf.o

/# FALCO_BPF_PROBE="" falco
2020-07-28T15:23:57+0000: Falco initialized with configuration file /etc/falco/falco.yaml
2020-07-28T15:23:57+0000: Loading rules from file /etc/falco/falco_rules.yaml:
2020-07-28T15:23:57+0000: Loading rules from file /etc/falco/falco_rules.local.yaml:
2020-07-28T15:23:57+0000: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
2020-07-28T15:23:57+0000: Unable to load the driver. Exiting.
2020-07-28T15:23:57+0000: Runtime error: can't create map: Errno 1. Exiting.
```

**Environment**

- Falco version: 0.24.0

- System info:
```
{
  "machine": "x86_64",
  "nodename": "xyz",
  "release": "5.0.0-1032-gke",
  "sysname": "Linux",
  "version": "#33-Ubuntu SMP Tue Mar 3 05:23:54 UTC 2020"
}
```

- Cloud provider or hardware configuration: GKE
- OS: Container: Debian GNU/Linux 10 (buster) // Node: Ubuntu 18.04.04 LTS (GKE version, so different kernel)

- Kernel: Linux gke-nodename-5-4c22c87d-zk53 5.0.0-1032-gke #33-Ubuntu SMP Tue Mar 3 05:23:54 UTC 2020 x86_64 GNU/Linux

- Installation method: Official Falco Docker image with custom entrypoint script.

**Additional context**

**Comment by leodido** [comment]
Unfortunately busy with something else now. But a first pointer for me and other maintainers: https://github.com/draios/sysdig/blob/4790332c24c5c81e168663f9852c5bb738d7d9ae/userspace/libscap/scap_bpf.c#L313

The problem seems to be caused by the BPF_MAP_CREATE not returning a FD referring to the map (EPERM errno?).

**Comment by pogao** [comment]
I've made some more tests and found that this only happens when we have Secure Boot/Shielded Nodes enabled in our K8s cluster running Ubuntu - this issue doesn't happen when we have Shielded Nodes/Secure Boot in COS. When I try to deploy Falco 0.24.0 to a cluster with those two features disabled, things work just fine - the probe is compiled and loaded without a problem.

So, I believe the updated steps to reproduce are:
* Create a cluster in GKE with Secure Boot and Shielded Nodes enabled. Nodes are Ubuntu (COS don't have this problem).
* Try to deploy the official Falco 0.24.0 image to the cluster.
* Make sure env vars `FALCO_BPF_PROBE` and `SKIP_DRIVER_LOADER` are set to `""`.
* You should see the `Runtime error: can't create map: Errno 1. Exiting.`

Let me know if you have trouble reproducing.

**Comment by wyardley** [comment]
@pogao did you ever find a workaround?

Can this issue be reopened?

**Comment by pogao** [comment]
@wyardley sorry - i don't keep up with my gh notifications lol. It looks like this doesn't happen anymore on the latest version using Shielded Nodes. I don't really know why, though - it just worked on my recent tests.
