### ISSUE TITLE
missing prebuilt kernel module (eks1.17.6)

### ISSUE THREAD

**Issue by emcay** [falcosecurity/falco#1345]
Similar to https://github.com/falcosecurity/falco/issues/1335

I have this issue on EKS 1.17.6 GitVersion:"v1.17.6-eks-4e7f64"

**Describe the bug**
Falco pods in CrashLoopBackOff stsate

**How to reproduce it**
`helm install falco falcosecurity/falco --set falco.jsonOutput=true`

**Expected behaviour**
Pods will indicate "running" state

**Environment**
"v1.17.6-eks-4e7f64"

- Falco version:
0.24.0
- Kernel:
4.14.186-146.268.amzn2.x86_64
- Installation method:
helm chart falco-1.2.1

```
 Setting up /usr/src links from host
* Running falco-driver-loader with: driver=module, compile=yes, download=yes
* Unloading falco module, if present
* Trying to dkms install falco module
* Running dkms build failed, couldn't find /var/lib/dkms/falco/85c88952b018fdbce2464222c3303229f5bfcfad/build/make.log
* Trying to load a system falco driver, if present
* Trying to find locally a prebuilt falco module for kernel 4.14.186-146.268.amzn2.x86_64, if present
* Trying to download prebuilt module from https://dl.bintray.com/falcosecurity/driver/85c88952b018fdbce2464222c3303229f5bfcfad/falco_amazonlinux2_4.14.186-146.268.amzn2.x86_64_1.ko
curl: (22) The requested URL returned error: 404 Not Found
Download failed, consider compiling your own falco module and loading it or getting in touch with the Falco community
Tue Aug  4 20:36:39 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Tue Aug  4 20:36:39 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Tue Aug  4 20:36:40 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Tue Aug  4 20:36:41 2020: Unable to load the driver. Exiting.
Tue Aug  4 20:36:41 2020: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded.. Exiting.
```

**Comment by leogr** [comment]
This happens because we still do not have the config for that kernel in our Driver Build Grid (see [here](https://github.com/falcosecurity/test-infra/tree/master/driverkit#faq))

**Comment by ianhundere** [comment]
documentation on how to do this:
how to create config files is explained here :point_right: https://github.com/falcosecurity/driverkit
and here how to put that into the build grid :point_right: https://github.com/falcosecurity/test-infra/tree/master/driverkit#faq

**Comment by emcay** [comment]
Thanks, working now.
