### ISSUE TITLE
Support cURLing remote kernel modules in values.yaml

### ISSUE THREAD

**Issue by jdbohrman** [falcosecurity/falco#1348]
So we've been trying to get Falco running in an edge environment running k3OS for about a month now and running into a host of issues facing getting the kernel module installed. We've considered baking into our custom kernel image but since we are using Helm and Kustomize to template things out, it would be nice to stick with the way we are doing it. I tried getting set up with Helm today and was greeted with this error:

```
│ make: *** No rule to make target 'Makefile'.  Stop.                                                                                                      │
│ make: Leaving directory '/host/usr/src/linux-headers-5.0.0-43-generic'                                                                                   │
│ * Trying to load a system falco driver, if present                                                                                                       │
│ * Trying to find locally a prebuilt falco module for kernel 5.0.0-43-generic, if present                                                                 │
│ * Trying to download prebuilt module from https://dl.bintray.com/falcosecurity/driver/85c88952b018fdbce2464222c3303229f5bfcfad/falco_debian_5.0.0-43-gen │
│ curl: (22) The requested URL returned error: 404 Not Found                                                                                               │
│ Download failed, consider compiling your own falco module and loading it or getting in touch with the Falco community                                    │
│ Fri Aug  7 04:21:49 2020: Falco initialized with configuration file /etc/falco/falco.yaml                                                                │
│ Fri Aug  7 04:21:49 2020: Loading rules from file /etc/falco/falco_rules.yaml:                                                                           │
│ Fri Aug  7 04:21:50 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:                                                                     │
│ Fri Aug  7 04:21:51 2020: Unable to load the driver. Exiting.                                                                                            │
│ Fri Aug  7 04:21:51 2020: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded. │
│ stream closed  
```

So the solution I wanted to explore was to figure out a way to turn this:

```
* Trying to download prebuilt module from https://dl.bintray.com/falcosecurity/driver/85c88952b018fdbce2464222c3303229f5bfcfad/falco_debian_5.0.0-43-gen │
│ curl: (22) The requested URL returned error: 404 Not Found 
```
Into something more GitOps friendly. There's obviously logic in Falco that controls that `cURL`, so would it be at all possible for people to control where the kernel is pulled from in their `values.yaml` file?

**Comment by leogr** [comment]
It is possible to provide a custom driver repository by setting the environment variable `DRIVER_REPO` as described in the [documentation here](https://falco.org/docs/installation/#install-driver).

So what you want to achieve should be possible if you build the kernel module by your self and host it in your repo (for example, `https://your.driver.repo.com/85c88952b018fdbce2464222c3303229f5bfcfad/falco_debian_5.0.0-43-gen.ko` ) and then set the `DRIVER_REPO` env to your repo URL (for example, `https://your.driver.repo.com/`).

If you are using the helm chart, the ENV var can be set here :point_right: https://github.com/falcosecurity/charts/blob/5e4fcea74fab95c5dc5f194334ae43d6bd03c7b4/falco/values.yaml#L63

Note that we use the word "driver" to generically refer to a kernel module or a bpf probe.

I hope this can help. Let me know!
