### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [falcosecurity/falco#1360]
Would you like to [wrap any pointer data members](https://github.com/falcosecurity/falco/blob/e46641d24d74fbe7921039834fdf5b01c4715009/userspace/engine/rules.cpp#L39 "Update candidate: falco_rules class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by elfring** [comment]
I suggest to [achieve safe resource management](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "C++ core guideline “R.11: Avoid calling new and delete explicitly”").

**Comment by fntlnz** [comment]
This looks like a great improvement to our code base. Thanks for bringing this up @elfring - if you have cycles to help on this please let me know so that we can assign this issue to you. In the meanwhile I'm labeling this as help wanted so it does not go stale.
Thanks a lot! 

/help

**Comment by leodido** [comment]
Reopening because  @deepskyblue86 expressed interest to work on this!

**Comment by deepskyblue86** [comment]
@leodido what about this one?
