### ISSUE TITLE
Debug symbol support

### ISSUE THREAD

**Issue by axot** [falcosecurity/falco#1370]
**Motivation**
We found few Falco PODs get high CPU usage,
so I try to use perf to check what happened.
It seems there is no debug symbol in the binary.

**Feature**
https://github.com/falcosecurity/falco/blob/master/CMakeLists.txt#L68
We could consider add `-g` flag to generate debug symbols.

**Alternatives**
This change will increase the binary size.

**Comment by leogr** [comment]
Which Falco version?

**Comment by axot** [comment]
We upgraded from 0.18.0 to 0.24.0.

**Comment by leodido** [comment]
I see your point, and I agree it can be really needed.

There are some points to consider to decide whether we want to implement such a feature or not:

- the `-g` flag (and maybe others related/similar) should be enabled by default in the DEBUG build of Falco
- do we want to distribute also the"debug" build of Falco as packages?
- do we want to distribute also the "debug" container image of Falco?

Honestly, implementing all this can make overkill our release process. But, I'm eager to listen what @falcosecurity/maintainers have in mind.

For sure this is a perfect topic for the next [Community Call](https://github.com/falcosecurity/community).
