### ISSUE TITLE
Falco Provides Unclear Error Message When Kevt in Condition and Source Type is Syscall

### ISSUE THREAD

**Issue by ykcilborw** [falcosecurity/falco#1379]
**Describe the bug**
When parsing certain rules file, Falco can give unclear error messages as to why it failed to parse such as "Error loading rules: parser API error". It is not clear to the end user how to fix this.

**How to reproduce it**
Create a Falco file with the following content:
```
---
- macro: "kevt"
  condition: "(jevt.value[/stage] in (k8s_audit_stages))"
  append: false

- rule: "test"
  desc: "test"
  condition: "kevt"
  output: "output"
  priority: "WARNING"
  tags: []
  source: "syscall"
  append: false
```

Run `falco -V kevt.yaml` or whatever you name the file

Falco outputs:
```
Thu Sep  3 00:10:22 2020: Validating rules file(s):
Thu Sep  3 00:10:22 2020:    kevt.yaml
Rule test: warning (no-evttype):
kevt
         did not contain any evt.type restriction, meaning it will run for all event types.
         This has a significant performance penalty. Consider adding an evt.type restriction if possible.
Error loading rules: parser API error
Thu Sep  3 00:10:22 2020: Runtime error: Error loading rules: parser API error. Exiting.
```

**Expected behaviour**
An informative error message. It is not clear to the user how to fix "parser API error"
 
**Screenshots**
N/A

**Environment**

- Falco version: 0.22.1
"system_info":{"machine":"x86_64","nodename":"vagrant-ubuntu-trusty-64","release":"3.13.0-163-generic","sysname":"Linux","version":"#213-Ubuntu SMP Thu Nov 15 02:19:07 UTC 2018"}
- Kernel: Linux vagrant-ubuntu-trusty-64 3.13.0-163-generic #213-Ubuntu SMP Thu Nov 15 02:19:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Installation method: DEB

**Additional context**
N/A

**Comment by ykcilborw** [comment]
Can this issue please be kept open and addressed? I think it is important to fix the error message

**Comment by sshayb** [comment]
Getting the same error with the following rule on AWS EKS:

- rule: "Kube event on ubuntu"
      desc: "Kube event on ubuntu"
      condition: kevt and pod and ka.req.pod.containers.image. startswith "ubuntu"
      output: Kubernetes audit event (user=%ka.user.name pod=%ka.resp.name ns=%ka.target.namespace images=%ka.req.pod.containers.image volumes=%jevt.value[/requestObject/spec/volumes])
      priority: WARNING
      source: k8s_audit
      tags: []

C:\WINDOWS\system32>helm inspect chart falcosecurity/falco
apiVersion: v1
appVersion: 0.26.2
description: Falco
home: https://falco.org
icon: https://falco.org/images/logos/falco-logo.png
keywords:
- monitoring
- security
- alerting
- metric
- troubleshooting
- run-time
maintainers:
- email: cncf-falco-dev@lists.cncf.io
  name: The Falco Authors
name: falco
sources:
- https://github.com/falcosecurity/falco
version: 1.5.4

**Comment by ykcilborw** [comment]
Can this issue please be kept open and addressed? I think it is important to fix the error message

**Comment by jasondellaluce** [comment]
For more context, can you try to reproduce this in the latest falco version? I'm not able to reproduce this failure anymore in Falco 0.29.1.

Looking at the underlying code, it seems to be caused when the `in` operator is used with a non-substituted macro. The point of failure should be here 👇🏼  https://github.com/falcosecurity/libs/blob/9d2082aa5a84dbd42890c4b5aae73c5ec38e2b65/userspace/chisel/lua_parser_api.cpp#L266

As for the latest version of `libs`, this seems to throw a more informative error now.

**Comment by leogr** [comment]
Hey @ykcilborw 

is this still an issue?

**Comment by jasondellaluce** [comment]
Following up on this. Right now, the rule loader would output the following:
```
Wed Apr  6 15:32:07 2022: Runtime error: Could not load rules file ../rules/falco_rules.yaml: 1 errors:
Rule test: error filter_check called with nonexistent field jevt.value[/stage]
---
- rule: "test"
  desc: "test"
  condition: "kevt"
  output: "output"
  priority: "WARNING"
  tags: []
  source: "syscall"
  append: false
---
```

Which is the correct error message I would expect. In fact what it is saying here is that no field `jevt.value` is available because the rule uses the "syscall" source. By changing the rule source to "k8s_audit" the ruleset is accepted. ykcilborw, WDYT? If you would like the error message to be more explicit, any feedback would be appreciated!
