### ISSUE TITLE
Falco engine version not updated when renameat2 was added

### ISSUE THREAD

**Issue by mstemm** [falcosecurity/falco#1380]
I noticed that this rules change (https://github.com/falcosecurity/falco/commit/1f1f7c16b66b18ab6c3c36f45b1296c2a52b697a#diff-6acd8aa2e534d1ed83e275bf658d936b) added support for the renameat2 syscall, which was added to sysdig in this commit: https://github.com/draios/sysdig/commit/f0bf26959c6a9bd1856d45ee5c80448201124f08#diff-b17bd28471a61e4b30f3c557d17da87a. I think we should have updated the falco engine version from 6 to 7 when falco was updated  to use this sysdig version, as it's a change to the set of fields that the engine supports.

Also, I think at the time the falco_rules file was updated, we should have modified the required_engine_version field in the rules file to set required_engine_version to 7. Also, it doesn't seem like it was updated when an earlier change (https://github.com/falcosecurity/falco/commit/70b9bfe1d6bf4d44e7ad000d726603418ad37342#diff-6acd8aa2e534d1ed83e275bf658d936b) added support for new modes that hadn't been previously allowed in sysdig.

If you try to read the current rules file with falco 0.24.0, you'll get this error:

```
Thu Sep  3 11:33:26 2020: Runtime error: Error loading rules: /usr/share/falco/lua/sinsp_rule_utils.lua:107: Unknown event/syscall "renameat2" in filter: ((open_write and access_repositories) or (modify and modify_repositories)) and not package_mgmt_procs and not package_mgmt_ancestor_procs and not exe_running_docker_save and not user_known_update_package_registry
```

A preferred error would be the one denoting the required engine version. I set the required_engine_version in the rules file as an example.

```
Thu Sep  3 11:36:07 2020: Runtime error: Rules require engine version 7, but engine version is 6
---
- required_engine_version: 7
```

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:
Falco version: 0.24.0
Driver version: 85c88952b018fdbce2464222c3303229f5bfcfad
- System info:
{
  "machine": "x86_64",
  "nodename": "ubuntu",
  "release": "4.15.0-15-generic",
  "sysname": "Linux",
  "version": "#16~16.04.1-Ubuntu SMP Thu Apr 5 12:19:23 UTC 2018"
}
- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by leogr** [comment]
You're totally right. It was my fault.
We have to fix this soon.
/milestone 0.26.0
