### ISSUE TITLE
Does falco support cn_proc? which is more convenient than sysdig.

### ISSUE THREAD

**Issue by wcc526** [falcosecurity/falco#1397]
Does falco support cn_proc? which is more convenient than sysdig.

The sysdig should install kernel mod,but  cn_proc is support by linux kernel from 2.6.32

https://bewareofgeek.livejournal.com/2945.html

**Comment by fntlnz** [comment]
@wcc526 can you please elaborate a bit more on that?
From `cn_proc.h` I can see this

```c
/*
 * cn_proc.h - process events connector
 *
 * Copyright (C) Matt Helsley, IBM Corp. 2005
 * Based on cn_fork.h by Nguyen Anh Quynh and Guillaume Thouvenin
 * Copyright (C) 2005 Nguyen Anh Quynh <aquynh@gmail.com>
 * Copyright (C) 2005 Guillaume Thouvenin <guillaume.thouvenin@bull.net>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of version 2.1 of the GNU Lesser General Public License
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it would be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
#ifndef CN_PROC_H
#define CN_PROC_H

#include <uapi/linux/cn_proc.h>

#ifdef CONFIG_PROC_EVENTS
void proc_fork_connector(struct task_struct *task);
void proc_exec_connector(struct task_struct *task);
void proc_id_connector(struct task_struct *task, int which_id);
void proc_sid_connector(struct task_struct *task);
void proc_ptrace_connector(struct task_struct *task, int which_id);
void proc_comm_connector(struct task_struct *task);
void proc_coredump_connector(struct task_struct *task);
void proc_exit_connector(struct task_struct *task);
#else
static inline void proc_fork_connector(struct task_struct *task)
{}

static inline void proc_exec_connector(struct task_struct *task)
{}

static inline void proc_id_connector(struct task_struct *task,
				     int which_id)
{}

static inline void proc_sid_connector(struct task_struct *task)
{}

static inline void proc_comm_connector(struct task_struct *task)
{}

static inline void proc_ptrace_connector(struct task_struct *task,
					 int ptrace_id)
{}

static inline void proc_coredump_connector(struct task_struct *task)
{}

static inline void proc_exit_connector(struct task_struct *task)
{}
#endif	/* CONFIG_PROC_EVENTS */
#endif	/* CN_PROC_H */
```

I suppose that you are talking about the "syscalls use case here. `cn_proc` does not give any syscalls insights out of those connectors so it's not a viable path for the syscalls use case.

However, I see the different use case here.
Falco recently introduced a new `-u` userspace flag. It allows you to input different types of events by implementing a protocol in userspace. If you want to get only that type of events in and you don't want the rest of the syscalls you could implement a producer that does just that. 
You can find an example here https://github.com/fntlnz/userspace-example

**Comment by leodido** [comment]
@wcc526 replied to you also via Twitter DMs.

**Comment by wcc526** [comment]
The demo like this https://github.com/ggrandes-clones/pmon. the cn_proc get the process pid,then we could get more information from /proc/pid/exe,etc.  it's run on the bypass mode

**Comment by wcc526** [comment]
There is a demo PR. https://github.com/falcosecurity/falco/pull/1398
