### ISSUE TITLE
segmentation fault when using -o and no config file

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco#1406]
**Describe the bug**

Falco crashes when using the `-o` (to override a configuration option) and no configuration file is found.

**How to reproduce it**

- Install Falco using the provided binary package
- Run `sudo falco -o log_level=info` and it works because config file is loaded from `/etc/falco/falco.yaml` (that's OK)
- Run `falco` (without sudo) and it says there's no configuration file (that's OK):
```
Wed Sep 16 15:19:53 2020: Falco version 0.25.0 (driver version ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7)
Wed Sep 16 15:19:53 2020: Falco initialized. No configuration file found, proceeding with defaults
Wed Sep 16 15:19:53 2020: Runtime error: You must specify at least one rules file/directory via -r or a rules_file entry in falco.yaml. Exiting.
```
- Finally, run ` falco -o log_level=info` (without sudo) and it crashes:
```
[1]    71887 segmentation fault (core dumped)  falco -o log_level=info
```

**Expected behaviour**

No segmentation fault.

**Environment**

- Falco version:
```
Falco version: 0.25.0
Driver version: ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7
```
- System info:
```
{
  "machine": "x86_64",
  "nodename": "x1",
  "release": "5.8.9-arch2-1",
  "sysname": "Linux",
  "version": "#1 SMP PREEMPT Sun, 13 Sep 2020 23:44:55 +0000"
}
```
- Cloud provider or hardware configuration:
- OS: Arch Linux 

- Kernel:

- Installation method:
TGZ (binary package)

**Additional context**

**Comment by nibalizer** [comment]
I've been able to reproduce:

```
$ ./falco -o log_level=info
Segmentation fault (core dumped)
```
