### ISSUE TITLE
Runtime error: CPU 1 configuration change detected. Aborting.. Exiting.

### ISSUE THREAD

**Issue by jemc** [falcosecurity/falco#1426]
**Describe the bug**

Falco daemon crashes after some period of time, with the following message logged to `journalctl -fu falco`:

```
Runtime error: CPU 1 configuration change detected. Aborting.. Exiting.
```

**How to reproduce it**

Exact steps are unknown, but it happens regularly.

Install Falco in a similar environment to what is specified in the **Environment** section below, then use the desktop machine as normal, including sometimes suspending/hibernating the machine, while watching `journalctl -fu falco` in an open terminal. I always eventually see the crash.

It's possible that this happens when I suspend/hibernate the machine, but I'm not sure of that yet.

**Expected behaviour**

**Screenshots**

**Environment**

Running Falco as a daemon on a Fedora 31 desktop computer, with a `5.7.8-100` kernel and the following  info:

- Falco version:
```
Falco version: 0.26.0
Driver version: 2aa88dcf6243982697811df4c1b484bcbe9488a2
```

- System info:
```json
{
  "machine": "x86_64",
  "nodename": "localhost-live-19.home",
  "release": "5.7.8-100.fc31.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP Thu Jul 9 15:16:52 UTC 2020"
}
```

- Cloud provider or hardware configuration: Clevo custom-build laptop
- OS: Fedora 31 desktop, with Gnome and Wayland
- Kernel: `5.7.8-100`
- Installation method: RPM, with driver built from source

**Additional context**

**Comment by leogr** [comment]
It should happen when suspending/hibernating the machine because the Falco is not able to handle the CPU configuration change.
Not sure if it should be strictly categorized as a bug.

**Comment by leogr** [comment]
> I'm okay with whatever classification the team prefers. I'd just like to be able to use falco without having to manually restart it every time that it aborts.

That's a good point, I did not considered.

When the installation method is RPM, Falco should run [as a system service](https://falco.org/docs/running/#run-falco-as-a-service). So we could configure the service so that it automatically restarts in case Falco is exited.
WDYT?

PS
Probabily we have to migrate the service to systemd before (see also https://github.com/falcosecurity/falco/issues/1265 ).
