### ISSUE TITLE
CI: pipeline, test and release targets for aarch64 and armv7

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falco#1445]
**Motivation**

Once that https://github.com/falcosecurity/falco/pull/1442 is merged, Falco can be built on aarch64 and armv7 architectures.

For divulgation purposes, we already created a manual build artifact with which @alexellis was able to run Falco on k3s - https://blog.alexellis.io/falco-at-the-edge-arm64/

However, until we don't have the build and test for aarch64 and armv7 in the pipeline we are not producing the artifacts to enable our users to use Falco on ARM in production.

**Feature**

- [ ] CircleCI pipeline to build and test Falco for aarch64
- [ ] CircleCI pipeline to build and test Falco for armv7
- [ ] CircleCI pipeline to release on tag for aarch64
- [ ] CircleCI pipeline to release on tag for armv7
- [ ] CircleCI pipeline to release the development version on master for aarch64
- [ ] CircleCI pipeline to release the development version on master for armv7

See: https://github.com/falcosecurity/falco/blob/master/.circleci/config.yml\

Discussion on how to do ARM builds on CircleCI: https://discuss.circleci.com/t/arm-builds/29102/13

**Additional context**

We have a working group to discuss the points above. 

Working group announcement: https://lists.cncf.io/g/cncf-falco-dev/message/183

**Comment by AGSaidi** [comment]
Circle CI is [planning](https://twitter.com/CircleCI/status/1313594210851803139) arm64 support. In the mean time [Travis](https://blog.travis-ci.com/AWS-Graviton-2-support-comes-to-Travis-CI) has it available.

**Comment by inductor** [comment]
By using buildx you can simply build multi architecture images on anywhere :)

**Comment by adammw** [comment]
@fntlnz is there possibility of cross-compiling using existing x86_64 CI pipeline until your CI tool provides native arm64/aarch64 support?

**Comment by xUnholy** [comment]
Seeing the dependency PR merged is there any update on the progress of this ticket?

**Comment by leodido** [comment]
There has been an initial attempt by @fntlnz and myself using CircleCI and multiarch/qemu in [this branch](https://github.com/falcosecurity/falco/compare/new/ci-build-aarch64).

Anyway, we decided to implement it using our Falco Infra (ARM support is coming there, see [this PR](https://github.com/falcosecurity/test-infra/pull/284)).
