### ISSUE TITLE
Unexpected Kube-Controller process

### ISSUE THREAD

**Issue by zhaocheng173** [falcosecurity/falco#1452]
I deployed using the Kubeadm cluster, and the default Calico comes with a Kube-Controller container, which Falco discovered as an unexpected process

```
root@m1 falco-extras]# kubectl get po -A |grep controller
kube-system         kube-controller-868fbddc9b-snmdg              1/1     Running     0          8d
kube-system         kube-controller-manager-m1                    1/1     Running     2          8d
```

The rule condition includes the kube-Controller process

I don't know whether this question has value or not, so I put it forward, because my cluster encountered it. Should I update the keyword for this rule to avoid the occurrence of valueless alarm

```
# These policies are limited to containers, specifically those where
# the container image name starts with "kube_controller"
- macro: app_kube_controller
  condition: container and container.image contains "kube-controller-manager"
```

**Comment by leogr** [comment]
First of all, thanks for contributing to Falco.

However, it's not clear to me what is the rule you are referring to. And other details are missing (Falco version, OS, installation method, etc..).

To avoid missing details like in this case, we provide a template to be filled in when opening a new issue. Please make use of it. That is not to annoy you but to save everyone's time while dealing with a new request.

**Comment by zhaocheng173** [comment]
Ok, I'm not very familiar with this may, my cluster is the 1.18.8 kubeadm to deploy, use centos - 7.5, use the 3.10 kernel, use https://github.com/falcosecurity/falco/ charts to deploy, falco 0.26.1 use

```
[root@m1 falco]# helm list -n kube-system
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
falco   kube-system     1               2020-10-21 17:59:23.542040576 +0800 CST deployed        falco-1.5.1     0.26.1     
[root@m1 falco]# cat /etc/redhat-release
CentOS Linux Release 7.8.2003 (Core)
[root@m1 falco]# uname -r
3.10.0-1127. El7 x86_64
```
