### ISSUE TITLE
Compile eBPF probe for custom kernel

### ISSUE THREAD

**Issue by soopanova** [falcosecurity/falco#1453]
**Describe the bug**

I need to support multiple OS and Kernels. Some of the kernels have been customized, when i try to install the falco the compiling of the probe fails

**How to reproduce it**
```
# ./falco-driver-loader bpf
* Running falco-driver-loader with: driver=bpf, compile=yes, download=yes
* Mounting debugfs
* Found kernel config at /proc/config.gz
* Trying to compile the eBPF probe (@PROBE_NAME@_rhel_3.10.0-1127.10.1.el7.<CUST>.20200605.60.x86_64_1.o)
make: *** /usr/src/@PROBE_NAME@-@PROBE_VERSION@/bpf: No such file or directory.  Stop.
mv: cannot stat ‘/usr/src/@PROBE_NAME@-@PROBE_VERSION@/bpf/probe.o’: No such file or directory
* Trying to download a prebuilt eBPF probe from @DRIVERS_REPO@/@PROBE_VERSION@/@PROBE_NAME@_rhel_3.10.0-1127.10.1.el7.<CUST>.20200605.60.x86_64_1.o
curl: (6) Could not resolve host: DRIVERS_REPO@; Unknown error
Download failed
```

**Expected behaviour**

The probe will be compiled, since the kernel is custom I dont expect it to be in the bintray directory

**Environment**

- Falco version:
.26.1

- System info:

- Cloud provider or hardware configuration:
hardware
- OS:
```
# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
```

- Kernel:
```
Linux myhost 3.10.0-1127.10.1.el7.<CUST>.20200605.60.x86_64 #1 SMP Fri Jun 5 13:51:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Installation method:
Initially docker container but down to using loader script to test

**Additional context**

**Comment by fntlnz** [comment]
Hi @soopanova - Welcome to the Falco project!

It looks like you are using the `falco-driver-loader` from the source repo, the script changed at compile time when the variables `@PROBE_NAME@`, `@DRIVERS_REPO@` and `@PROBE_VERSION@` are interpolated.

To get a working one you need to look it up under your build folder `build/scripts/falco-driver-loader` 

Feel free to ask if you have any doubt.

**Comment by fntlnz** [comment]
Adding kind documentation since we can probably make this more clear - I bet other users are having the same problem

**Comment by soopanova** [comment]
Tried the fix and still had an issue. To keep debugging I tried to use the official docker image, with a common Kernel and still got the same errors:
- Kernel: 
```
# uname -r
3.10.0-1127.19.1.el7.x86_64
```

Trying kernel module:
```
# docker run --rm -i -t     --privileged     -v /dev:/host/dev     -v /proc:/host/proc:ro     -v /boot:/host/boot:ro     -v /lib/modules:/host/lib/modules:ro     -v /usr:/host/usr:ro     -v /etc:/host/etc:ro     falcosecurity/falco:latest
* Setting up /usr/src links from host
* Running falco-driver-loader with: driver=module, compile=yes, download=yes
* Unloading falco module, if present
* falco module still loaded, waited 5s (max wait 60s)
* falco module still loaded, waited 10s (max wait 60s)
* falco module still loaded, waited 15s (max wait 60s)
* falco module still loaded, waited 20s (max wait 60s)
* falco module still loaded, waited 25s (max wait 60s)
* falco module still loaded, waited 30s (max wait 60s)
* falco module still loaded, waited 35s (max wait 60s)
* falco module still loaded, waited 40s (max wait 60s)
* falco module still loaded, waited 45s (max wait 60s)
* falco module still loaded, waited 50s (max wait 60s)
* falco module still loaded, waited 55s (max wait 60s)
* falco module still loaded, waited 60s (max wait 60s)
* falco module seems to still be loaded, hoping the best
2020-10-22T04:10:43+0000: Falco version 0.26.1 (driver version 2aa88dcf6243982697811df4c1b484bcbe9488a2)
2020-10-22T04:10:43+0000: Falco initialized with configuration file /etc/falco/falco.yaml
2020-10-22T04:10:43+0000: Loading rules from file /etc/falco/falco_rules.yaml:
2020-10-22T04:10:43+0000: Loading rules from file /etc/falco/falco_rules.local.yaml:
2020-10-22T04:10:43+0000: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
2020-10-22T04:10:43+0000: Unable to load the driver.
2020-10-22T04:10:43+0000: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded.. Exiting.
```

Also tried the ebpf:
```
# docker run --rm -i -t \
>     --privileged \
>     -e FALCO_BPF_PROBE="" \
>     -v /dev:/host/dev \
>     -v /proc:/host/proc:ro \
>     -v /boot:/host/boot:ro \
>     -v /lib/modules:/host/lib/modules:ro \
>     -v /usr:/host/usr:ro \
>     -v /etc:/host/etc:ro \
>     falcosecurity/falco:latest
* Setting up /usr/src links from host
* Running falco-driver-loader with: driver=bpf, compile=yes, download=yes
* Mounting debugfs
* Found kernel config at /host/boot/config-3.10.0-1127.19.1.el7.x86_64
* Trying to compile the eBPF probe (falco_centos_3.10.0-1127.19.1.el7.x86_64_1.o)
In file included from /usr/src/falco-2aa88dcf6243982697811df4c1b484bcbe9488a2/bpf/probe.c:9:
/usr/src/falco-2aa88dcf6243982697811df4c1b484bcbe9488a2/bpf/quirks.h:15:2: error: Kernel version must be >= 4.14
      with eBPF enabled
#error Kernel version must be >= 4.14 with eBPF enabled
 ^
In file included from /usr/src/falco-2aa88dcf6243982697811df4c1b484bcbe9488a2/bpf/probe.c:13:
In file included from include/linux/sched.h:33:
include/linux/signal.h:78:11: warning: array index 3 is past the end of the array (which contains 1 element)
      [-Warray-bounds]
                return (set->sig[3] | set->sig[2] |
./arch/x86/include/asm/signal.h:23:2: note: array 'sig' declared here
        unsigned long sig[_NSIG_WORDS];

****snip out errors ****

fatal error: too many errors emitted, stopping now [-ferror-limit=]
50 warnings and 20 errors generated.
make[2]: *** [/usr/src/falco-2aa88dcf6243982697811df4c1b484bcbe9488a2/bpf/Makefile:33: /usr/src/falco-2aa88dcf6243982697811df4c1b484bcbe9488a2/bpf/probe.o] Error 1
make[1]: *** [Makefile:1316: _module_/usr/src/falco-2aa88dcf6243982697811df4c1b484bcbe9488a2/bpf] Error 2
make: *** [Makefile:18: all] Error 2
mv: cannot stat '/usr/src/falco-2aa88dcf6243982697811df4c1b484bcbe9488a2/bpf/probe.o': No such file or directory
* Trying to download a prebuilt eBPF probe from https://dl.bintray.com/falcosecurity/driver/2aa88dcf6243982697811df4c1b484bcbe9488a2/falco_centos_3.10.0-1127.19.1.el7.x86_64_1.o
curl: (22) The requested URL returned error: 404 Not Found
Download failed
2020-10-22T04:11:37+0000: Falco version 0.26.1 (driver version 2aa88dcf6243982697811df4c1b484bcbe9488a2)
2020-10-22T04:11:37+0000: Falco initialized with configuration file /etc/falco/falco.yaml
2020-10-22T04:11:37+0000: Loading rules from file /etc/falco/falco_rules.yaml:
2020-10-22T04:11:37+0000: Loading rules from file /etc/falco/falco_rules.local.yaml:
2020-10-22T04:11:37+0000: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
2020-10-22T04:11:38+0000: Unable to load the driver.
2020-10-22T04:11:38+0000: Runtime error: can't open BPF probe '/root/.falco/falco-bpf.o': Errno 2. Exiting.
```

**Comment by leodido** [comment]
Hello, eBPF can't build on that kernel. See line in the logs: `Kernel version must be >= 4.14 with eBPF enabled`.

> Trying kernel module:
> 
> ```
> # docker run --rm -i -t     --privileged     -v /dev:/host/dev     -v /proc:/host/proc:ro     -v /boot:/host/boot:ro     -v /lib/modules:/host/lib/modules:ro     -v /usr:/host/usr:ro     -v /etc:/host/etc:ro     falcosecurity/falco:latest
> * Setting up /usr/src links from host
> * Running falco-driver-loader with: driver=module, compile=yes, download=yes
> * Unloading falco module, if present
> * falco module still loaded, waited 5s (max wait 60s)
> * falco module still loaded, waited 10s (max wait 60s)
> * falco module still loaded, waited 15s (max wait 60s)
> * falco module still loaded, waited 20s (max wait 60s)
> * falco module still loaded, waited 25s (max wait 60s)
> * falco module still loaded, waited 30s (max wait 60s)
> * falco module still loaded, waited 35s (max wait 60s)
> * falco module still loaded, waited 40s (max wait 60s)
> * falco module still loaded, waited 45s (max wait 60s)
> * falco module still loaded, waited 50s (max wait 60s)
> * falco module still loaded, waited 55s (max wait 60s)
> * falco module still loaded, waited 60s (max wait 60s)
> * falco module seems to still be loaded, hoping the best
> 2020-10-22T04:10:43+0000: Falco version 0.26.1 (driver version 2aa88dcf6243982697811df4c1b484bcbe9488a2)
> 2020-10-22T04:10:43+0000: Falco initialized with configuration file /etc/falco/falco.yaml
> 2020-10-22T04:10:43+0000: Loading rules from file /etc/falco/falco_rules.yaml:
> 2020-10-22T04:10:43+0000: Loading rules from file /etc/falco/falco_rules.local.yaml:
> 2020-10-22T04:10:43+0000: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
> ```

What I suspect here is that the Falco container can't run properly because the kernel module driver is already loaded into your host. Could you retry ensuring that you removed it?

What's the output of `cat /proc/modules | grep falco` before running this container?

---

Anyways, other 3 options to try out come to my mind:

## Tarballs

Have you tried to install Falco using [this](https://dl.bintray.com/falcosecurity/bin/x86_64/:falco-0.26.1-x86_64.tar.gz)?

It contains the `falco-driver-loader` ready to be used, in your binary directory, after installation.

## RPM

Alternatively, you could use our RPM. Instructions [here](https://falco.org/docs/installation/#centos-rhel).

## Driverkit

Since you mentioned different kernels, some of them customized, you could give a try to [driverkit](https://github.com/falcosecurity/driverkit).

It's a nice tool able to prebuild Falco drivers starting from a simple YAML configuration files. Its README contains a lot of examples for inspiration, and it also supports custom Kernel configs.

**Comment by soopanova** [comment]
@leodido After more digging I went back to the kernel module. The reason it keeps thinking that the module is loaded is due to a grep statement in the `falco-driver-loader` hits on a similarly named module and thinks its loaded. After patching the script everyting installed correctly. I will take a look at the Driverkit documentation, i would rather use eBPF over Kernel Module. This issue can be closed.

**Comment by leodido** [comment]
Oh, gotcha!

Would you please indicate to us the exact line you're referring?
Maybe we can make it more solid... :)
