### ISSUE TITLE
Trim repeating alerts which flooding log files and outputs triggered by same action

### ISSUE THREAD

**Issue by TroyPang** [falcosecurity/falco#1456]
Hi,

**Motivation**
In some cases, one action repeating will generate same alerts continuously, and in contents only difference is the timestamp, then alerts will flood log files or other outputs locations, so other alerts may be hidden inside the flood.

e.g. use event-gernerater to simulate a "Write below /etc"
`/bin/event-generator run --loop syscall.WriteBelowEtc`
by default it will happen every 250ms, and in output, it will show same number of alerts there.

**Feature**
Probably we need a feature to trim such logs, e.g. it will only show the first log, then transfer other repeating logs to something like "<short log msg contain key info> happen xx times in last xx mins" or some json keys/values to indicate this

Thanks

**Comment by leogr** [comment]
A [rate-limit mechanism](https://github.com/falcosecurity/falco/blob/294804daf436b4d146731322f46a99e2736feee0/falco.yaml#L90-L104) for alert notifications is already in place. Though sometimes it's not a good thing to have, for example, see https://github.com/falcosecurity/falco/issues/1333.

But your suggestion is going further and makes sense. Moreover, aggregating notifications could be a problem in some use cases. For example, how would one reconstruct the history of a security incident if they don't have the complete list of all separate notifications with precise timestamps? 

It would be a good topic for our community call btw.
