### ISSUE TITLE
Installing falco on CentOS is failing 403 forbidden due to repository

### ISSUE THREAD

**Issue by danieledivito** [falcosecurity/falco#1458]
**Describe the bug**
After the execution of commands in the installation guide I get an error due to repositories. Even a yum update doens't work cause of a forbidden error. This happen on CentOS 7 and CentOS 8.

**How to reproduce it**

```shell
rpm --import https://falco.org/repo/falcosecurity-3672BA8F.asc

curl -s -o /etc/yum.repos.d/falcosecurity.repo https://falco.org/repo/falcosecurity-rpm.repo

yum -y install falco
```

**Expected behaviour**
It should install falco

**Screenshots**
```shell
Loading mirror speeds from cached hostfile
 * base: ftp.antilo.de
 * extras: mirror.23media.com
 * updates: mirror.23media.com
https://dl.bintray.com/falcosecurity/rpm/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden
Connessione ad un altro mirror in corso.
To address this issue please refer to the below wiki article

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.



 One of the configured repositories failed (falcosecurity-rpm),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=falcosecurity-rpm ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable falcosecurity-rpm
        or
            subscription-manager repos --disable=falcosecurity-rpm

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=falcosecurity-rpm.skip_if_unavailable=true

failure: repodata/repomd.xml from falcosecurity-rpm: [Errno 256] No more mirrors to try.
https://dl.bintray.com/falcosecurity/rpm/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden
```

**Environment**
Testing server

- Falco version:
falco-0.26.1-x86_64.rpm

- System info:

- Cloud provider or hardware configuration:
Google cloud.

- OS:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- ALSO TRIED ON:
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

- Kernel:
3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
AND 
4.18.0-193.14.2.el8_2.x86_64 #1 SMP Sun Jul 26 03:54:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Installation method:
yum repositories for RPM

**Additional context**
Environments were fresh deployed, updated and rebooted

**Comment by leodido** [comment]
Thanks for reporting this @danieledivito 

We're aware of the issue. And it should have been fixed now.

Could you please give it another try?

Thanks
