### ISSUE TITLE
Error reporting for output channels

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco#1466]
**Motivation**

Errors that may occur in output channels are not being reported. This behavior can lead users to wrong assumptions.

**Feature**

Add a comprehensive error reporting mechanism to the Falco outputs implementation.
For example, when an output channel cannot write to the configured file or cannot reach the configured HTTP endpoint, Falco should report the error to `stderr` at least.

**Alternatives**

Do nothing is always an alternative, but users have almost no chance to get what is going on without error reporting.

**Additional context**

There could be cases where Falco can't continue to run when one of such error occurs. For example, what to do if Falco cannot write to a file because there's no more space on the disk?

**Comment by MINQ1NG** [comment]
evt.type = write is igored by low-level settings of falco, that's why it doesn't output any error reporting after run falco. So, the left issue is find out how remove the wirte type from ignored list.

**Comment by fntlnz** [comment]
@MINQ1NG you can do that by passing the `-A` flag when starting Falco, however that has a performance penalty.

**Comment by leodido** [comment]
To do not ignore a particular event type (eg. write) we can set its event mask (using the libsinsp interface, `set_eventmask` if I do not recall it wrong).

**Comment by jasondellaluce** [comment]
I don't know if this is outdated, but we seem to cover this right now: 👇🏼 
https://github.com/falcosecurity/falco/blob/b33fb6052a3d4e3b511241911367357a4259a7cf/userspace/falco/falco_outputs.cpp#L336

Falco catches exceptions arising from output channels and logs them with `LOG_ERR` level.

**Comment by leogr** [comment]
> I don't know if this is outdated, but we seem to cover this right now: 👇🏼
> 
> https://github.com/falcosecurity/falco/blob/b33fb6052a3d4e3b511241911367357a4259a7cf/userspace/falco/falco_outputs.cpp#L336
> 
> Falco catches exceptions arising from output channels and logs them with `LOG_ERR` level.

You are right, this issue was fixed. Thank you for noticing that!

/close
