### ISSUE TITLE
falco-driver-loader rmmod check/loop inadvertently finds other modules

### ISSUE THREAD

**Issue by dnwe** [falcosecurity/falco#1468]
**Describe the bug**

The falco-driver-loader script just does a basic `lsmod | grep -q "falco"` so will partially match and can inadvertently think that the falco module is loaded when actually an unrelated "falcon_nf_netcontain" kernel module (e.g.,) happened to be loaded on the host

https://github.com/falcosecurity/falco/blob/294804daf436b4d146731322f46a99e2736feee0/scripts/falco-driver-loader#L223-L238

**How to reproduce it**

Attempt to start falco on a host that has a similarly named "falcon" module and notice that the falco-driver-loader will loop attempting to `rmmod falco` when falco is not loaded.

**Expected behaviour**

falco-driver-loader should inspect only the first column of /proc/modules and require the whole search string to match

i.e.,
```sh
while cut -d' ' -f1 </proc/modules | grep -qx "${KMOD_NAME}" && [ $WAIT_TIME -lt "${MAX_RMMOD_WAIT}" ]; do 
```

**Screenshots**

**Environment**

- Falco version:
- System info: Falco version: 0.23.0
Driver version: 96bd9bc560f67742738eb7255aeb4d03046b8045
- OS: Ubuntu bionic
- Kernel: 4.15.0-122-generic
- Installation method: deb

**Comment by leogr** [comment]
Good catch. 
Would you like to submit a PR?

Btw, I'm not sure we can use `/proc/modules` since it can be not shared with the container in which `falco-driver-loader` is running.

**Comment by dnwe** [comment]
@leogr yeah we can probably do the same thing, just parse `lsmod` output instead. I _think_ /proc/modules should always be available, both kube (containerd) and docker will mount it by default without any user configuration. It's actually the fallback if `lsmod` is run as a non-root user.
