### ISSUE TITLE
What's the best way to disable default rules?

### ISSUE THREAD

**Issue by PhilipSchmid** [falcosecurity/falco#1469]
Hi there,

To me it's not clear how default rules should be disabled. The official documentation only says how to append to existing lists, macros and rules (see https://falco.org/docs/rules/) but not directly how to disable default rules.

I see multiple possibilities (some do not work):

**Option 1:**
For example appending an `enabled: false` to a default rule...
```yaml
- rule: Unexpected UDP Traffic
  append: true
  enabled: false
```
... does not work:
```bash
Wed Nov  4 08:50:34 2020: Loading rules from file /etc/falco/rules.d/rules-disabled-for-example:
Wed Nov  4 08:50:34 2020: Runtime error: Rule must have property condition
---
- rule: Unexpected UDP Traffic
  append: true
  enabled: false
---. Exiting.
```

**Option 2:**
Append a custom `and (never_true)` condition to the default rules could be a generic way to disable specific default rules:
```yaml
- rule: Unexpected UDP Traffic
  append: true
  condition: and (never_true)
```
This works but is also probably not the nicest solution..

**Option 3:**
Override existing `consider_*` macros: https://github.com/falcosecurity/falco/blob/294804daf436b4d146731322f46a99e2736feee0/rules/falco_rules.yaml#L406-L407

The problem here is that not all default rules have such a `consider_*` macro. For example the following one does not: https://github.com/falcosecurity/falco/blob/294804daf436b4d146731322f46a99e2736feee0/rules/falco_rules.yaml#L2612-L2619

Also it's probably not the best solution since every rule would have it's unique enable/disable macro which is quite annoying to figure out and configure. Why not just allow something with `enabled: false`?

How do you guys disable default rules?

Thanks & regards,
Philip

**Comment by leodido** [comment]
Hey Philip,

I like simple ideas, thus I prefer option 1 (ie., `enabled: true|false`).

There goes my vote!

But, let's wait for other maintainers vote!

**Comment by PhilipSchmid** [comment]
Hi @leodido 

Sounds awesome. Thanks for the feedback!

As far as I understand your answer correct, you would prefer a currently not existing possibility via `enabled: true|false` to enable/disable rules. But how do you currently suggest to disabled default rules? I mean something like 
```yaml
- rule: Unexpected UDP Traffic
  append: true
  enabled: false
```
or 
```yaml
- rule: Unexpected UDP Traffic
  enabled: false
```
does not work 😁.

Thanks & regards,

Philip

**Comment by PhilipSchmid** [comment]
Regarding the `Delete Bash History` rule for example. The description of this rule says `This rule is deprecated and will/should never be triggered.`  (see https://github.com/falcosecurity/falco/blob/master/rules/falco_rules.yaml#L2668) but unfortunately it gets tiggered anyway. It also gets triggered even if I modify the rule like the following (option 2 from above):

```yaml
- rule: Delete Bash History
  append: true
  condition: and (never_true)
```

So I guess this is valid falco syntax but does not actually disable the rule. Do you guys see a better (working) solution?

Thanks & regards,
Philip

**Comment by leogr** [comment]
> ```yaml
> - rule: Unexpected UDP Traffic
>   append: true
>   enabled: false
> ```

IIRC, :point_up: should work if the original rule definition has been loaded before (the loading ordering matter).
What's the loading order? I did see it in your log.


> ```yaml
> - rule: Unexpected UDP Traffic
>   enabled: false
> ```

:point_up: should not work since it completely overwrites the rule definition

**Comment by PhilipSchmid** [comment]
Hi @leogr 

Thanks for your input!

**Regarding your code snipped 1**: Makes to me sense now. I didn't know that the loading order matters. I also believe this is not documented in the official documentation. Perhaps you guys would like to add this to https://falco.org/docs/rules/#gotchas-with-rulemacro-append-and-logical-operators?

 **Regarding your code snipped 2**: I've tested it. You are right. This does not work since there is no `append: true` and as such, this definition will override the existing `Unexpected UDP Traffic` default rule definition but also then fails, since it does not specify any `condition` which would be a required field. Just a question for the sake of easiness: Would it be a huge effort to allow this syntax so users are able to disable default rules without complicate syntax and effort?

Thanks & regards,
Philip

**Comment by leogr** [comment]
Hey @PhilipSchmid 

> Thanks for your input!

You are welcome!

> **Regarding your code snipped 1**: Makes to me sense now. I didn't know that the loading order matters. I also believe this is not documented in the official documentation. Perhaps you guys would like to add this to https://falco.org/docs/rules/#gotchas-with-rulemacro-append-and-logical-operators?

I agree the documentation can be improved and any help with that is really appreciated :+1: 

> **Regarding your code snipped 2**: I've tested it. You are right. This does not work since there is no `append: true` and as such, this definition will override the existing `Unexpected UDP Traffic` default rule definition but also then fails, since it does not specify any `condition` which would be a required field. Just a question for the sake of easiness: Would it be a huge effort to allow this syntax so users are able to disable default rules without complicate syntax and effort?

Do you mean disabling a rule without the need of `append: true`? 
IMHO, I just would not introduce a special case that's not consistent with the rest of the syntax. Just my opinion anyway.

Btw, regarding the original question of this issue, have you also evaluated using one of the below command-line options? 
```
 -D <substring>                Disable any rules with names having the substring <substring>. Can be specified mu
ltiple times.
...
-T <tag>                      Disable any rules with a tag=<tag>. Can be specified multiple times.
                               Can not be specified with -t.
 -t <tag>                      Only run those rules with a tag=<tag>. Can be specified multiple times.
                               Can not be specified with -T/-D.
```

**Comment by PhilipSchmid** [comment]
Hi @leogr 

> > **Regarding your code snipped 1**: Makes to me sense now. I didn't know that the loading order matters. I also believe this is not documented in the official documentation. Perhaps you guys would like to add this to https://falco.org/docs/rules/#gotchas-with-rulemacro-append-and-logical-operators?
> 
> I agree the documentation can be improved and any help with that is really appreciated 👍

I will update the documentation in the next few days and create a PR.

> > **Regarding your code snipped 2**: I've tested it. You are right. This does not work since there is no `append: true` and as such, this definition will override the existing `Unexpected UDP Traffic` default rule definition but also then fails, since it does not specify any `condition` which would be a required field. Just a question for the sake of easiness: Would it be a huge effort to allow this syntax so users are able to disable default rules without complicate syntax and effort?
> 
> Do you mean disabling a rule without the need of `append: true`?
> IMHO, I just would not introduce a special case that's not consistent with the rest of the syntax. Just my opinion anyway.

Yes, that's what I meant.. but yes, thinking about it once again, your argument makes absolute sense. So can we then say (and perhaps also add to the documentation 😄) that when someone wants to disable default rules via configuration files, it's officially recommended to do so via a statement like the following:

```yaml
- rule: Unexpected UDP Traffic
  append: true
  enabled: false
```

(Of course with the side note that the user then needs to take care about the rule order (e.g. by naming his custom configuration file `z_disabled_default_rules.yaml`).)

> Btw, regarding the original question of this issue, have you also evaluated using one of the below command-line options?
> 
> ```
>  -D <substring>                Disable any rules with names having the substring <substring>. Can be specified mu
> ltiple times.
> ...
> -T <tag>                      Disable any rules with a tag=<tag>. Can be specified multiple times.
>                                Can not be specified with -t.
>  -t <tag>                      Only run those rules with a tag=<tag>. Can be specified multiple times.
>                                Can not be specified with -T/-D.
> ```

I've seen `-T` and `-t` but since these rules do not have unique tags it's not possible to disable a single default rule via these parameters. I haven't seen `-D` on the other hand so far. So I would have to use `extraArgs` from the Falco helm chart and add something like this to my values file?

```yaml
extraArgs:
  - -D Unexpected UDP Traffic
```

Thansk & regards,
Philip

**Comment by leogr** [comment]
> I've seen `-T` and `-t` but since these rules do not have unique tags it's not possible to disable a single default rule via these parameters. I haven't seen `-D` on the other hand so far. So I would have to use `extraArgs` from the Falco helm chart and add something like this to my values file?
> 
> ```yaml
> extraArgs:
>   - -D Unexpected UDP Traffic
> ```

Yes, it should work too, just perhaps it needs a quoted string.

Also, to add a bit more context, there's also this :point_down: 
https://github.com/falcosecurity/falco/blob/master/falco.yaml#L30
(I have not checked if it affects the loading order, I guess it should)

Btw, thank you again for having started this discussion and for your really detailed investigation. I believe that will help a lot of folks :clap:
