### ISSUE TITLE
High memory utilization of Falco containers in a GKE enviornment

### ISSUE THREAD

**Issue by IanRobertson-wpe** [falcosecurity/falco#1482]
**Describe the bug**

Falco container memory utilization has been observed to dramatically increase as a result of increased server load and alerting in multiple disparate clusters in a GKE environment. Memory utilization as high as 7GB has been observed, and remain high until the pod is recycled. This increase is observed in both non-evictable and evictable memory as reported through GKE's Monitoring metrics.

**How to reproduce it**

1. Launch Falco pods in GKE clusters using provided YAML.
2. Await activity on pods.
3. Observe through GCP Monitoring dashboard increase in memory utilization:
     Resource Type: Kubernetes Container
     Metric: Memory usage
     Filter: namespace_name = "falco"
     Filter: memory_type = "non-evictable" (and separately, through a separate chart, "evictable")
     Aggregator: none
     Period: 1 minute

**Expected behaviour**

Falco memory remains fairly flat and does not exceed some more reasonable amount. Falco's Helm chart specifies a memory request of 512Mi and a limit of 1024Mi (https://github.com/falcosecurity/charts/blob/master/falco/values.yaml).

**Screenshots**

![image](https://user-images.githubusercontent.com/44780116/98831327-0c9b3e80-2401-11eb-8bdb-f5271008d362.png)

![image](https://user-images.githubusercontent.com/44780116/98831415-2b99d080-2401-11eb-919b-f32009184572.png)

![image](https://user-images.githubusercontent.com/44780116/98831972-e1fdb580-2401-11eb-975c-343dbef19f91.png)

**Environment**

All clusters are running in a GKE environment. Clusters are running different but recent versions of OS, which include:
- Container-Optimized OS w/ docker
- Container-Optimized OS w/ containerd
- Container-Optimized OS w/ containerd, gVisor enabled

All clusters are using the eBPF filter. 

Clusters are all running differing workloads.

This has been observed with the following Falco versions:
- Falco version: 0.26.1-43+47fa7d5
- Falco version: 0.26.1-58+294804d

Driver versions are:
- Driver version: 2aa88dcf6243982697811df4c1b484bcbe9488a2 

**Additional context**

While problem exists across multiple clusters of varying types, it appears to be more pronounced across those running on node pools with gVisor enabled. It's unclear if this is a result of gVisor, or if perhaps heavier workloads are running there. Overall the nodes themselves are healthy. While this appears to be related to increased activity on the nodes, the nodes are not anywhere near their capacity limits, with CPU utilization less than 5% and sufficient memory headroom.

**Comment by fntlnz** [comment]
@IanRobertson-wpe thanks for opening this issue and letting us know about this case.
Do you mind sharing a couple of node types you run this into? You said that the node is not near to capacity exhaustion but it will be helpful to try to reproduce.

**Comment by IanRobertson-wpe** [comment]
Here are more details on one of the gVisor nodes and node pool settings:

Kernel version: 5.4.49+
OS image: Container-Optimized OS from Google
Container runtime version: containerd://1.4.0
kubelet version: v1.18.9-gke.801
kube-proxy version: v1.18.9-gke.801
Machine type: n1-standard-4
Boot disk type: Standard persistent disk
Boot disk size (per node): 100 GB
Boot disk encryption: Google-managed
Preemptible nodes: Disabled
Auto-upgrade: Enabled
Auto-repair: Enabled
Surge upgrade: Enabled
Max surge: 1
Max unavailable: 1
Sandbox with gVisor: Enabled
GKE Metadata Server: Enabled

Here is more information on a cluster that contains this node pool:

Intranode visibility: Disabled
Private Cluster: Enabled
Network policy (Calico): Enabled
NodeLocal DNSCache: Disabled
Istio: Disabled

**Comment by leogr** [comment]
Hey @IanRobertson-wpe 

Thanks for this report. I have just a few further questions that may help with debugging this.
- I see you mentioned two development versions of Falco, but did this issue happen with Falco version 0.26.1?
- Which Falco outputs are enabled, and how are configured? Is gRPC enabled?
- Are you using the Kubernetes Audit Log feature?

Thank you.

**Comment by IanRobertson-wpe** [comment]
Yes, this happened with 0.26.1 as well. 

This has been observed with Falco outputs set to the following:

json_output: true
json_include_output_property: true
log_stderr: true
log_syslog: true
log_level: info
priority: deug
buffered_outputs: false
outputs:
  rate: 1
  max_burst: 1000
syslog_output: 
  enabled: false
file_output:
  enabled: false
stdout_output:
  enabled: true
webserver:
  enabled: false
program_output:
  enabled: false
http_output:
  enabled: true
  url: http://localhost:2801
grpc:
  enabled: false
grpc_output:
  enabled: false

In GKE there is no native K8s audit log, as these logs are delivered directly to Stackdriver. My Falco command-line is set to:

falco --cri /host/run/containerd/containerd.sock -K /var/run/secrets/kubernetes.io/serviceaccount/token -k "https://$(KUBERNETES_SERVICE_HOST)" -pk

**Comment by leogr** [comment]
> In GKE there is no native K8s audit log, as these logs are delivered directly to Stackdriver.

Right, sorry for the stupid question :angel: 

> falco --cri /host/run/containerd/containerd.sock -K /var/run/secrets/kubernetes.io/serviceaccount/token -k "https://$(KUBERNETES_SERVICE_HOST)" -pk

Is there any particular reason for the `/host` prefix in the path?
If the env var `HOST_ROOT=/host` (default setting), the correct path should be `--cri /run/containerd/containerd.sock` ([here](https://github.com/falcosecurity/charts/blob/baf725370384774586124e60914507c52d0ae57b/falco/templates/daemonset.yaml#L60) an example).

**Comment by IanRobertson-wpe** [comment]
I found that in the falco container the path /run/containerd/containerd.sock was invalid. I manually adjusted this to add the /host. See below.

![image](https://user-images.githubusercontent.com/44780116/99852004-bab39080-2b45-11eb-83cb-f78fa9b3628a.png)
