### ISSUE TITLE
rules load

### ISSUE THREAD

**Issue by CodingJzy** [falcosecurity/falco#1497]
Do I have to restart falco when loading rules? Or can these configurations only be configured in yaml files? Configuring in the yaml file means that it can only be configured at the first startup, and you cannot add custom rules on the interface or through the http api

**Comment by leogr** [comment]
AFAIK, configuration/rules hot-reloading is supported in this way only:
https://falco.org/docs/getting-started/running/#hot-reload

**Comment by CodingJzy** [comment]
thank you
