### ISSUE TITLE
Cant start Falco container in Helm

### ISSUE THREAD

**Issue by JonLittleIT** [falcosecurity/falco#1508]
jonathanlittle  MacBook-Pro  ~  code  falconcore  %  kubectl logs -l app=falco -f
* Trying to find locally a prebuilt falco module for kernel 5.4.39-linuxkit, if present
* Trying to download prebuilt module from https://download.falco.org/driver/2aa88dcf6243982697811df4c1b484bcbe9488a2/falco_ubuntu-generic_5.4.39-linuxkit_1.ko
curl: (22) The requested URL returned error: 404
Download failed, consider compiling your own falco module and loading it or getting in touch with the Falco community
Mon Dec 14 00:10:34 2020: Falco version 0.26.2 (driver version 2aa88dcf6243982697811df4c1b484bcbe9488a2)
Mon Dec 14 00:10:34 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Mon Dec 14 00:10:34 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Mon Dec 14 00:10:36 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Mon Dec 14 00:10:38 2020: Unable to load the driver.
Mon Dec 14 00:10:38 2020: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded.. Exiting.

**Comment by JonLittleIT** [comment]
I updated my minikube and still got same 404 on driver download. I am using docker desktop on a OSX macbook pro.

  MacBook-Pro  ~  code  falconcore  %  minikube version
minikube version: v1.15.1
commit: 23f40a012abb52eff365ff99a709501a61ac5876
  MacBook-Pro  ~  code  falconcore  %  kubectl logs -l app=falco -f
* Trying to find locally a prebuilt falco module for kernel 5.4.39-linuxkit, if present
* Trying to download prebuilt module from https://download.falco.org/driver/2aa88dcf6243982697811df4c1b484bcbe9488a2/falco_ubuntu-generic_5.4.39-linuxkit_1.ko
curl: (22) The requested URL returned error: **404**
Download failed, consider compiling your own falco module and loading it or getting in touch with the Falco community
Mon Dec 14 03:03:29 2020: Falco version 0.26.2 (driver version 2aa88dcf6243982697811df4c1b484bcbe9488a2)
Mon Dec 14 03:03:29 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Mon Dec 14 03:03:29 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Mon Dec 14 03:03:31 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Mon Dec 14 03:03:33 2020: Unable to load the driver.
Mon Dec 14 03:03:33 2020: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded.. Exiting.
 MacBook-Pro  ~  code  falconcore  % 

**Comment by leogr** [comment]
Unfortunately, linuxkit is not yet supported, AFAIK. See https://github.com/falcosecurity/driverkit/issues/22
@leodido any workaround?
