### ISSUE TITLE
Hostname of alert origin not present in HTTP output

### ISSUE THREAD

**Issue by mhulscher** [falcosecurity/falco#1520]
**Motivation**

When configuring falco to send alerts to falcosidekick using the falco HTTP output the hostname of the originating machine/node is not present. This makes it near impossible to follow-up on alerts that don't have any Kubernetes metadata attached.

I am not sure if the hostname is already sent over the HTTP output and whether it is simply not sent to the destination medium (in my case Slack).

**Feature**

I would like to be able to see the hostname of the machine/node that triggered an alert.

**Alternatives**

N/A

**Additional context**

N/A

**Comment by Issif** [comment]
Hello @mhulscher,

I can confirm than the `hostname` is not sent by `falco`, if it was, I would already added it in `falcosidekick`. The field may be present with `gRPC` but I didn't added this input yet (we need to add a mechanism for auto-discovery of all `falco`, it's more work).

**Comment by jnunezgts** [comment]
This is an important omission, in Falco sidekick there is no way to tell which machine generated an event. So if you are going through a lot of events then you will have to scan each and every server to match the issue. Multiply this by a large number of servers is is time consuming.

**Comment by Milkshak3s** [comment]
I'd also be interested in reopening this issue. The use case for falco + falcosidekick on multiple nodes is diminished if we can't differentiate which nodes alerts come from.

**Comment by tks98** [comment]
> I'd also be interested in reopening this issue. The use case for falco + falcosidekick on multiple nodes is diminished if we can't differentiate which nodes alerts come from.

+1, I also would be interested. For my environment, Falco is generating a lot of alerts where output_field.container.id is set to "host" but it does not specify from which host it was coming from. With many nodes, this is extremely difficult to track down, especially when for these alerts there is no k8s metadata attached to correlate a pod to a specific node.

**Comment by Milkshak3s** [comment]
We use `m_hostname` from `outputs.h` in `outputs_grpc.cpp`, could we include this as a field in `handle_msg`?

Example (not usually a cpp developer, feedback encouraged): https://github.com/falcosecurity/falco/pull/1989/files

**Comment by adnankobir** [comment]
@Milkshak3s did you have luck with this? It looks like that the http json out put still does not include the `hostname`.

**Comment by leogr** [comment]
/reopen

I can confirm it's not working as expected. We will fix it in 0.33.0

Thank you for having reported the problem :pray: 

I will keep you posted

**Comment by adnankobir** [comment]
> /reopen
> 
> I can confirm it's not working as expected. We will fix it in 0.33.0
> 
> Thank you for having reported the problem 🙏
> 
> I will keep you posted

Thank you! In preparation to the fix here to include `hostname` in http_output, I've added the following PR in sidekick: https://github.com/falcosecurity/falcosidekick/pull/355
