### ISSUE TITLE
sensitive_vol_mount Too Permissive 

### ISSUE THREAD

**Issue by ossie-git** [falcosecurity/falco#1532]
**Describe the bug**

While looking at the definition of this in **k8s_audit_rules.yaml**, I noticed it only covers:

- /proc
- /var/run/docker.sock
- /
- /etc
- /root
- /var/run/crio/crio.sock
- /home/admin
- /var/lib/kubelet
- /var/lib/kubelet/pki
- /etc/kubernetes
- /etc/kubernetes/manifests

One of the ways to trivially bypass this is to mount either of these:

- /var
- /var/run

and then use these to access the Docker / CRIO daemon.

Wouldn't it better if we added both of these directories to this list?

**How to reproduce it**

See above

**Expected behaviour**

**Screenshots**

See above

**Environment**

This is applicable to the latest version as of the time fo this writing - https://github.com/falcosecurity/falco/blob/master/rules/k8s_audit_rules.yaml

**Additional context**

**Comment by fntlnz** [comment]
Wdyt @Kaizhe ?

**Comment by Kaizhe** [comment]
thanks @ossie-git , you're right, and definitely there are more sensitive host paths should be added in the rule. Would you like to create a PR to fix it?

**Comment by ossie-git** [comment]
Ok. I'll also add these paths to **sensitive_mount** in **falco_rules.yaml** which also lacks these paths and currently looks like this or you would prefer it as a separate PR?

```yaml
- macro: sensitive_mount
  condition: (container.mount.dest[/proc*] != "N/A" or
              container.mount.dest[/var/run/docker.sock] != "N/A" or
              container.mount.dest[/var/run/crio/crio.sock] != "N/A" or
              container.mount.dest[/var/lib/kubelet] != "N/A" or
              container.mount.dest[/var/lib/kubelet/pki] != "N/A" or
              container.mount.dest[/] != "N/A" or
              container.mount.dest[/home/admin] != "N/A" or
              container.mount.dest[/etc] != "N/A" or
              container.mount.dest[/etc/kubernetes] != "N/A" or
              container.mount.dest[/etc/kubernetes/manifests] != "N/A" or
              container.mount.dest[/root*] != "N/A")
```

**Comment by ossie-git** [comment]
I added a PR. It only touches on sensitive_vol_mount in k8s. I also added the following two directories, in addition to the ones mentioned above:

- /etc/kubernetes/pki
- /etc/kubernetes/pki/etcd
