### ISSUE TITLE
Disabling a rule by using "append" does not work as expected

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco#1537]
**Describe the bug**

Disabling a rule should be possible by just appending `enabled: false` as per the [official documentation](https://falco.org/docs/rules/#via-custom-rule-definition).

Unfortunately, it does not work.

**How to reproduce it**

Add a file under `/etc/falco/rules.d/custom-rules.yaml` with the following content:
```yaml
- rule: Unexpected UDP Traffic
  append: true
  enabled: false
```
Finally, run falco, and you get:

```
Tue Jan 26 15:24:39 2021: Falco version 0.27.0 (driver version 5c0b863ddade7a45568c0ac97d037422c9efb750)
Tue Jan 26 15:24:39 2021: Falco initialized with configuration file /home/leogr/code/github.com/falcosecurity/falco/falco.yaml
Tue Jan 26 15:24:39 2021: Loading rules from file /etc/falco/falco_rules.yaml:
Tue Jan 26 15:24:39 2021: Loading rules from file /etc/falco/falco_rules.local.yaml:
Tue Jan 26 15:24:39 2021: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Tue Jan 26 15:24:39 2021: Loading rules from file /etc/falco/rules.d/custom-rules.yaml:
Tue Jan 26 15:24:39 2021: Runtime error: Rule must have property condition
---
- rule: Unexpected UDP Traffic
  append: true
  enabled: false
---. Exiting.
```
N.B: rule files were loaded in the correct order (that's important to ensure that `append` works).

**Expected behaviour**

No error and the rule being disabled as suggested by the official documentation [here](https://falco.org/docs/rules/#via-custom-rule-definition).

**Environment**

- Falco version: 0.27.0 (previous versions seem to be affected too)

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

Disabling a rule seemed to work, as discussed in the past (see https://github.com/falcosecurity/falco/issues/1469 ).

However, as noticed by a user in the slack channel (original discussion [here](https://kubernetes.slack.com/archives/CMWH3EH32/p1611648695038300)) it doesn't work. 

**Considerations**
Firstly, the rule parser implements a [too strict condition on the existence of the `condition` property](https://github.com/falcosecurity/falco/blob/0.27.0/userspace/engine/lua/rule_loader.lua#L396-L403) that actually disallows this possibility. Secondly, after a quick look, it seems to me that implementation of the `enabled` flag would not work in appending mode even after removing the check on the `condition` property. Further investigation is needed.

**Workaround**
It is still possible to disable a rule using the `never_true` macro, for example:
```yaml
- rule: Unexpected UDP Traffic
  condition: and (never_true)
  append: true
```

**Comment by leogr** [comment]
cc @jasondellaluce

**Comment by jasondellaluce** [comment]
After further investigating this issue, It turns out that the `enabled` field was not overridden on `append`ed rules at all. As such, the value was not updated even if the `condition` field requirement is weakened. I just opened #1775 to fix this problem.
