### ISSUE TITLE
Falco internal: syscall event drop on Amazon Linux 2 for ARM

### ISSUE THREAD

**Issue by bootswithdefer** [falcosecurity/falco#1544]
**Describe the bug**

Falco on Amazon Linux 2 for ARM (aarch64) emits many system call drop events.   Issue does not occur on Amazon Linux 2 for AMD64 when the same steps are followed.

**How to reproduce it**

Build from source (commit b76420fe471f8af220d742543637b5aae02ee556) and run on a AWS EC2 t4g instance using latest Amazon Linux 2 AMI, according to https://falco.org/docs/getting-started/source/.

**Expected behaviour**

Zero to minimal syscall drops.

**Screenshots**

```
Fri Jan 29 10:23:48 2021: Falco internal: syscall event drop. 2 system calls dropped in last second.
10:23:48.788502515: Critical Falco internal: syscall event drop. 2 system calls dropped in last second. (ebpf_enabled=0 n_drops=2 n_drops_buffer=0 n_drops_bug=0 n_drops_pf=2 n_evts=263)
Fri Jan 29 10:23:50 2021: Falco internal: syscall event drop. 8 system calls dropped in last second.
10:23:50.658813438: Critical Falco internal: syscall event drop. 8 system calls dropped in last second. (ebpf_enabled=0 n_drops=8 n_drops_buffer=0 n_drops_bug=0 n_drops_pf=8 n_evts=525)
Fri Jan 29 10:23:51 2021: Falco internal: syscall event drop. 8 system calls dropped in last second.
10:23:51.962007429: Critical Falco internal: syscall event drop. 8 system calls dropped in last second. (ebpf_enabled=0 n_drops=8 n_drops_buffer=0 n_drops_bug=0 n_drops_pf=8 n_evts=461)
Fri Jan 29 10:23:53 2021: Falco internal: syscall event drop. 11 system calls dropped in last second.
10:23:53.647347904: Critical Falco internal: syscall event drop. 11 system calls dropped in last second. (ebpf_enabled=0 n_drops=11 n_drops_buffer=0 n_drops_bug=0 n_drops_pf=11 n_evts=488)
Fri Jan 29 10:23:54 2021: Falco internal: syscall event drop. 8 system calls dropped in last second.
10:23:54.853373017: Critical Falco internal: syscall event drop. 8 system calls dropped in last second. (ebpf_enabled=0 n_drops=8 n_drops_buffer=0 n_drops_bug=0 n_drops_pf=8 n_evts=403)
Fri Jan 29 10:23:56 2021: Falco internal: syscall event drop. 8 system calls dropped in last second.
```

**Environment**

- Falco version: `0.27.0-17+b76420f (driver version 5c0b863ddade7a45568c0ac97d037422c9efb750)`

- System info:
```
  "machine": "aarch64",
  "nodename": "authn-test-vault03",
  "release": "4.14.209-160.339.amzn2.aarch64",
  "sysname": "Linux",
  "version": "#1 SMP Wed Dec 16 22:44:17 UTC 2020"
```

- Cloud provider or hardware configuration: AWS EC2 t4g.large
- OS:
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

- Kernel: `Linux authn-test-vault03 4.14.209-160.339.amzn2.aarch64 #1 SMP Wed Dec 16 22:44:17 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux`

- Installation method: source

**Additional context**

**Comment by leogr** [comment]
I just want to highlight that `n_drops_pf` is a particular kind of syscall drop, and it's not a buffering issue.

`pf` stands for page fault (ie. dropped events caused by invalid memory access). It may happen whenever the memory page (referenced by the syscall) had disappeared before the driver was able to collect information about the event.

**Comment by FedeDP** [comment]
Never encountered that in my tests; i am not sure whether this is fixed or not :(
