### ISSUE TITLE
Can binary files be installed to a user path /home/test/falco, not system root path /?

### ISSUE THREAD

**Issue by swxEmily** [falcosecurity/falco#1554]
Linux generic (binary package)
Download the latest binary:

curl -L -O https://dl.bintray.com/falcosecurity/bin/x86_64/falco-0.27.0-x86_64.tar.gz
Install Falco:

tar -xvf falco-0.27.0-x86_64.tar.gz
cp -R falco-0.27.0-x86_64/* /

The binary installation copy files to the system root path /.

can I set the path in a user path, and add the path the enrionment PATH to let falco command enabled?

**Comment by swxEmily** [comment]
@poiana 
I tried to support type, but it need account, how can I get @get-an-invite-at.slack.kubernetes.io email address?
![image](https://user-images.githubusercontent.com/43984746/107489953-33b20980-6bc4-11eb-9bdf-3ecc9a191e9c.png)

![image](https://user-images.githubusercontent.com/43984746/107489816-0cf3d300-6bc4-11eb-911d-ab69b97c4d0e.png)

**Comment by leodido** [comment]
Hello @swxEmily click [here](https://kubernetes.slack.com/?redir=%2Fmessages%2Ffalco) to get an invite for the Falco channel on the Kubernetes slack!

In the meantime, I'm gonna update the ISSUE template for the support requests. :)
