### ISSUE TITLE
Falco installation on PhotonOS VMWare

### ISSUE THREAD

**Issue by george-lim-sfdc** [falcosecurity/falco#1570]
**Describe the bug**
I am trying to build a Falco driver for VMWare PhotonOS because there is no prebuilt kernel module for the distro.

Kernel version: 4.19.129-1.ph3-esx
Falco version: falco-0.27.0-x86_64.tar.gz

**How to reproduce it**
curl -L -O https://dl.bintray.com/falcosecurity/bin/x86_64/falco-0.27.0-x86_64.tar.gz
tar xvfz falco-0.27.0-x86_64.tar.gz
cp -R falco-0.27.0-x86_64/* /

tdnf install dkms gcc make clang clang-devel linux-esx-devel-4.19.129-1.ph3 binutils

Commands
#1. /usr/bin/falco-driver-loader
#2. /usr/bin/falco-driver-loader bpf

**Expected behaviour**
create the falco driver and load it.

**Screenshots**

**Environment**

- Falco version:
falco-0.27.0-x86_64.tar.gz

- System info:
Mon Mar  8 23:18:18 2021: Falco version 0.27.0 (driver version 5c0b863ddade7a45568c0ac97d037422c9efb750)
Mon Mar  8 23:18:18 2021: Falco initialized with configuration file /etc/falco/falco.yaml
Mon Mar  8 23:18:18 2021: Loading rules from file /etc/falco/falco_rules.yaml:
Mon Mar  8 23:18:18 2021: Loading rules from file /etc/falco/falco_rules.local.yaml:
Mon Mar  8 23:18:18 2021: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
{
  "machine": "x86_64",
  "nodename": "tkg-cluster-1-workers-bmkbv-56764f964-xt4bl",
  "release": "4.19.129-1.ph3-esx",
  "sysname": "Linux",
  "version": "#1-photon SMP Tue Jun 30 02:18:44 UTC 2020"
}

- Cloud provider or hardware configuration:
VMWare Tanzu

- OS:
NAME="VMware Photon OS"
VERSION="3.0"
ID=photon
VERSION_ID=3.0
PRETTY_NAME="VMware Photon OS/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"

- Kernel:
Linux tkg-cluster-1-workers-bmkbv-56764f964-xt4bl 4.19.129-1.ph3-esx #1-photon SMP Tue Jun 30 02:18:44 UTC 2020 x86_64 GNU/Linux

- Installation method:
Linux binary from the tar file.

**Additional context**

falco-driver-loader
* Running falco-driver-loader with: driver=module, compile=yes, download=yes
* Unloading falco module, if present
* Trying to dkms install falco module with GCC /bin/gcc
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'/tmp/falco-dkms-make'....
cleaning build area...

DKMS: build completed.

falco.ko.xz:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.129-1.ph3-esx/kernel/extra/

depmod...

DKMS: install completed.
* falco module installed in dkms, trying to insmod
* Unable to insmod falco module
* Trying to load a system falco driver, if present
* Trying to find locally a prebuilt falco module for kernel 4.19.129-1.ph3-esx, if present
* Trying to download prebuilt module from https://download.falco.org/driver/5c0b863ddade7a45568c0ac97d037422c9efb750/falco_photon_4.19.129-1.ph3-esx_1.ko
curl: (22) The requested URL returned error: 404 Not Found
Download failed, consider compiling your own falco module and loading it or getting in touch with the Falco community

insmod /lib/modules/4.19.129-1.ph3-esx/kernel/extra/falco.ko.xz
insmod: ERROR: could not insert module /lib/modules/4.19.129-1.ph3-esx/kernel/extra/falco.ko.xz: Unknown symbol in module

/usr/bin/falco-driver-loader bpf
* Running falco-driver-loader with: driver=bpf, compile=yes, download=yes
* Mounting debugfs
mount: /sys/kernel/debug: nodev already mounted or mount point busy.
* Found kernel config at /boot/config-4.19.129-1.ph3-esx
* Trying to compile the eBPF probe (falco_photon_4.19.129-1.ph3-esx_1.o)
* Skipping download, eBPF probe is already present in /root/.falco/falco_photon_4.19.129-1.ph3-esx_1.o
* eBPF probe located in /root/.falco/falco_photon_4.19.129-1.ph3-esx_1.o
******************************************************************
** BPF doesn't have JIT enabled, performance might be degraded. **
** Please ensure to run on a kernel with CONFIG_BPF_JIT on.     **
******************************************************************
* Success: eBPF probe symlinked to /root/.falco/falco-bpf.o

**Comment by dirien** [comment]
Hi, 

can we /reopen this again? At my workplace, we run PhotonOS too and want to use Falco

**Comment by strajansebastian** [comment]
The same here. We would like to try to use Falco on PhotonOS
