### ISSUE TITLE
Split main rules file into separate files on platform-basis

### ISSUE THREAD

**Issue by gecube** [falcosecurity/falco#1584]
**Motivation**

Right now Falco main rules (non-application specific) are packed into one big file https://github.com/falcosecurity/falco/blob/master/rules/falco_rules.yaml
It is hell to maintain this set of rules. Also it is non-logical to have rules for different platforms in one bundle. For example, if I am using OpenShift, I don't like to see docker-related rules, because there is no docker daemon in OSCP or OKD. If the docker daemon is run inside of OpenShift - the cluster can be compromised.
The same applies if I am using vanilla kubernetes - it is unlikely that I will have rancher-related images.

Also there definitely  must be correlation between the number of rules and the performance of falco. So it is crucial to lessen the number of rules.

**Feature**

Split rules into small files according to platforms:
1. docker host only
2. pod man host only
3. vanilla kubernetes:
4. openshift 3.xx (& okd)
5. openshift 4.xx (& okd)
6. rancher 2.x (based on rke)
7. distribution of your choice

Also it is wise to split rules into two separate lists: for master-nodes and for worker-nodes, because it is unlikely to see master components on worker nodes, and more - it must be prohibited and it may be compromise sign.

**Comment by omer-sd** [comment]
There is definitely a need to rethink the main rules file. 
Currently it's targeting a broad set of behaviors across different environments, which is great on one hand, but captures too much. 
I suggest we use the collective wisdom of the community and start cleaning up the default file and limit it to a more targeted set of use cases that can be applied across environments, e.g. terminal-shell-in-a-container.

**Comment by gecube** [comment]
@omer-sd thanks for you suggestion. Meanwhile we are trying to make our own rulesets. I hope we will be able to share it with community soon.

**Comment by chirabino** [comment]
I agree with @gecube about splitting the ruleset in multiple files. Not sure about splitting based on platform...

Another thing that makes difficult to maintain the ruleset file is to have macros and lists in the same file.

Personally, I like the way [Wazuh ruleset][1] are classified: they put `decoders` in one place and `rules` in another.

Falco may have something similar: rules, macros and lists can be organized in separated file. 

Falco may have global (apply to all) and local (apply to file) lists and macros.

[1]: https://github.com/wazuh/wazuh/tree/master/ruleset

**Comment by chirabino** [comment]
Falco ruleset files could be enabled/disabled using a suffix so that if the file ends with `_disabled` it will not be used. In this way it is very easy to automate installations and have a easy way to see what is enabled and what is not just listing the ruleset files.

**Comment by chirabino** [comment]
Another thing I like about Wazuh is that each rule has a unique ID. In this way you can overwrite a rule just using the same ID in a custom/local file.

**Comment by matthyx** [comment]
Hi folks, any update on this subject? Do you need some help here?
I am quite interested in evolving these rule sets and especially make sure they work with OpenShift 4.
Thanks in advance for your guidance.

**Comment by gecube** [comment]
Unfortunately, no observed progress :-(

**Comment by omer-sd** [comment]
The plan is to come up with a new proposal and present it to the community. Hopefully this will happen soon.
