### ISSUE TITLE
Add Nomad Orchestrator rules

### ISSUE THREAD

**Issue by monwolf** [falcosecurity/falco#1597]
**Motivation**

I'm using falco to detect suspicious behaviours inside our docker processes. 
Instead of using Kubernetes we are using the hashicorp stack to orchestrate our containers, i would like to see or to know if you have planned to add rules for this platform

Thanks

**Comment by gecube** [comment]
Hi! It's a nice idea!
I'd like to have the separate file for nomad-specific rules too according to #1584
