### ISSUE TITLE
How to run falco on windows based nodepool on k8s

### ISSUE THREAD

**Issue by themonaminor** [falcosecurity/falco#1600]
i am trying to run mixed nodepool in k8s.
for runtime security, falco can be used for linux based nodepool. but as there is windows based nodepool i wanted either to run falco on windows based nodepool or else is there any other tool available.

**Comment by gecube** [comment]
Falco can't be run on windows because it heavy relies on Linux kernel capabilities.
What do you expect from Windows-related security solution?

**Comment by themonaminor** [comment]
I want to know how to do runtime intrusion detection in windows based node as we do runtime intrusion detection for linux nodes.

 

Is there any alternate tool available ??

whether the image that we have as of now can be modified to run on windows nodes as well in k8s?

**Comment by gecube** [comment]
> Is there any alternate tool available ??

https://logz.io/blog/open-source-hids/
Probably you'd like to look into Wazuh solution https://wazuh.com/
Or build something like https://medium.com/@ibrahim.ayadhi/deploying-of-infrastructure-and-technologies-for-a-soc-as-a-service-socass-8e1bbb885149 on your own

**Comment by howardjones** [comment]
Please add something to the Readme to specifically say that Windows K8S nodes are not supported, and won't be, if it's intended not to be. It just says "Kubernetes" everywhere, and mixed-os clusters are a thing in multiple public clouds for a couple of years now. Just spent 10 minutes trying to find something explicitly saying either way.

**Comment by timoguin** [comment]
Microsoft added eBPF support to Windows earlier this year. This is probably worth looking into again.

- https://cloudblogs.microsoft.com/opensource/2021/05/10/making-ebpf-work-on-windows/
- https://github.com/microsoft/ebpf-for-windows
