### ISSUE TITLE
Bintray deb is no longer signed.

### ISSUE THREAD

**Issue by jepperson2** [falcosecurity/falco#1639]
**Describe the bug**

On a recent deployment our attempt to install Falco failed with the following error messages:
```
The repository 'https://dl.bintray.com/falcosecurity/deb stable InRelease' is no longer signed.

Failed to fetch https://dl.bintray.com/falcosecurity/deb/dists/stable/InRelease  403  Forbidden
```

**How to reproduce it**

```
echo "deb https://dl.bintray.com/falcosecurity/deb stable main" | tee -a /etc/apt/sources.list.d/falcosecurity.list
apt-get update -y
```

**Expected behaviour**

Latest deb is pulled down from Bintray

**Environment**

- Falco version:
```
Falco version: 0.21.0
```
- System info:
```
{
  "machine": "x86_64",
  "nodename": "foo-bar",
  "release": "4.15.0-1065-aws",
  "sysname": "Linux",
  "version": "#69-Ubuntu SMP Thu Mar 26 02:17:29 UTC 2020"
}
```
- Cloud provider or hardware configuration:
```
AWS
```
- OS:
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel:
```
Linux foo-bar 4.15.0-1065-aws #69-Ubuntu SMP Thu Mar 26 02:17:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Installation method:
```
Deb
```

**Additional context**

I recognize that the [recommended installation instructions](https://falco.org/docs/getting-started/installation/) currently say to use `https://download.falco.org/packages/deb`, but they used to say `https://dl.bintray.com/falcosecurity/deb`, and we have yet to update.

Is there a chance that falco's bintray set-up could be updated to be functional again?

Thank you in advance for your response!

**Comment by leodido** [comment]
Hello @jepperson2 the Falco package artifacts have been moved to https://download.falco.org because Bintray is going to be shut down ([link](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)).

We had and we have no control over Bintray. Instead, now the Falco packages are completely owned by our community.

**Comment by jepperson2** [comment]
Thank you for the link and for the update.

I'll plan to upgrade our installation process accordingly.
