### ISSUE TITLE
New tags for rules based on the ATT&CK for Containers

### ISSUE THREAD

**Issue by magnologan** [falcosecurity/falco#1646]
**Motivation**

MITRE ATT&CK for Containers official version was released last week (April 29th) and it has many different Tactics and Techniques based on real-world scenarios and attacks in the wild involving containers and clusters.

https://medium.com/mitre-engenuity/att-ck-for-containers-now-available-4c2359654bf1

**Feature**

Add new tags for Falco rules based on the new MITRE ATT&CK for Containers (and K8s) to make it easier to enable and disable those rules based on their common names given by MITRE.

Base on this spreadsheet: https://docs.google.com/spreadsheets/d/1lK2luf4iuOHDJEZ9EGcv3DkuuHeyRJAfeBzQCu2AuUI/edit#gid=1467870057

**Alternatives**

N/A? Maybe an alternative would be the OWASP Docker Top 10: https://owasp.org/www-project-docker-top-10/, but this project is still a work in progress.

**Additional context**

Slack thread on Falco channel: https://kubernetes.slack.com/archives/CMWH3EH32/p1620375559409800

This issue is proposed by @vicenteherrera

**Comment by leodido** [comment]
Thank you @magnologan !

**Comment by vicenteherrera** [comment]
Work for mapping is progressing, you can view it on this spreadsheet (public view, request access if you want to contribute).
https://docs.google.com/spreadsheets/d/1lK2luf4iuOHDJEZ9EGcv3DkuuHeyRJAfeBzQCu2AuUI/edit#gid=0

Also, we can discuss about it in Slack, and join Falco Community Call on 5/19 for more details.
