### ISSUE TITLE
K8s Pod and Namespace are null in events

### ISSUE THREAD

**Issue by CashWilliams** [falcosecurity/falco#1655]
**Describe the bug**

On a standard install from the Falco helm chart, events do not contain the pod or namespace context.

**How to reproduce it**

This was produced in a k3s cluster and using ArgoCD to install the Falco chart from https://github.com/falcosecurity/charts.

**Expected behaviour**

All context of an event would be provided.

**Screenshots**

<img width="986" alt="Screen Shot 2021-05-17 at 10 09 41 AM" src="https://user-images.githubusercontent.com/613573/118512030-124b4700-b6f8-11eb-8963-ada13b8487b3.png">

```
14:56:58.910588102: Error File below /etc opened for writing (user=root user_loginuid=-1 command=touch /etc/test parent=bash pcmdline=bash file=/etc/test program=touch gparent= ggparent= gggparent= container_id=c5790e1182fe image=) k8s.ns= k8s.pod= container=c5790e1182fe k8s.ns= k8s.pod= container=c5790e1182fe k8s.ns= k8s.pod= container=c5790e1182fe
```

**Environment**

- Falco version:

`docker.io/falcosecurity/falco:0.28.1`

- System info:

- Cloud provider or hardware configuration:
- OS:

K3os

- Kernel:

`Linux k3os-12226 5.4.0-72-generic #80 SMP Tue May 4 19:31:44 UTC 2021 x86_64 GNU/Linux`

- Installation method:

ArgoCD to Kubernetes

**Comment by leogr** [comment]
Reference to the slack discussion :point_down: 
https://kubernetes.slack.com/archives/CMWH3EH32/p1621264393102500?thread_ts=1620858347.021000&cid=CMWH3EH32

**Comment by CashWilliams** [comment]
Turns out k3s doesn't provide the `containerd` socket in the traditional place. I'll try to document this better, but for now -

need to tell Falco to get the socket at `/run/k3s/containerd/containerd.sock` instead of the default.

**Comment by CashWilliams** [comment]
I'm going to close this for now to get it off the issues list.
