### ISSUE TITLE
No internet access OKD

### ISSUE THREAD

**Issue by gonzalo-** [falcosecurity/falco#1660]
**No internet access OKD**

Hello, I would like to know if there is any documentation to install Falco without internet access at OKD level, there is any way to build the falco-driver outside of OKD and deploy it with the current charts? Or something similar? 

Cheers,.

**Comment by leogr** [comment]
Internet access is only required if you want to use a prebuilt driver published under download.falco.org.
You can either let `falco-driver-loader` build the driver on the fly or provide your own driver's repo.
See:
- https://github.com/falcosecurity/charts/tree/master/falco#about-the-driver
- https://falco.org/docs/getting-started/installation/#install-driver

**Comment by gonzalo-** [comment]
Nice, what about if I want to do everything out of the host (OKD without internet access and not kernel-headers installed), there is a way to do this? I mean, deploy the driver from my computer or build it in my computer and then deploy it to the OKD host

**Comment by leodido** [comment]
Hello @gonzalo- you may want to look into https://github.com/falcosecurity/driverkit :)
