### ISSUE TITLE
False positive "setuid" notice

### ISSUE THREAD

**Issue by CashWilliams** [falcosecurity/falco#1664]
**Describe the bug**

Running latest version, we are seeing a lot of calls reporting like:

```
Notice Unexpected setuid call by non-sudo, non-root program (user=<NA> user_loginuid=-1 cur_uid=0 parent=umount command=umount /var/lib/kubelet/pods/3630aac9-5810-43a9-8c81-f2ceea6f9888/volume-subpaths/77b0d7f3-62d0-4963-927c-0c680a4a77a4-files/shared-setup/14 uid=<NA> container_id=host image=<NA>) k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host
```

**How to reproduce it**

We're running on EKS, not sure if it happens on other k8s systems. One note: we are running the following patches, which might be causing some meta data to be missing that an existing rule is looking for:

- https://github.com/falcosecurity/charts/pull/226 
- https://github.com/falcosecurity/libs/pull/15
- https://github.com/falcosecurity/libs/pull/40

**Expected behaviour**

These alerts don't happen.

**Environment**

- Falco version: 0.28
- System info:

- Cloud provider or hardware configuration: EKS

**Comment by leodido** [comment]
Hello @CashWilliams, could you please double-check whether @Kaizhe's PR (#1665) solves your issue?
