### ISSUE TITLE
Badges for "dev" package are not reporting the correct version

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco#1672]
**Describe the bug**

As per the title.

**How to reproduce it**

Look at the [README.md](https://github.com/falcosecurity/falco#latest-releases) :point_down: 
![Screenshot from 2021-06-09 17-30-47](https://user-images.githubusercontent.com/3390997/121384375-7ef8e080-c948-11eb-865e-7333fe0f3f25.png)

**Expected behaviour**

Badges should report the latest version on the `master` branch according to the following format:
*x.y.z*-*N*+*hash*

Where:
 - *x.y.z* the latest released version
 - *N* is the number of commit since the latest released version
 - *hash* is the ID of the latest commit on the `master` (first 7 digits)

**Comment by jasondellaluce** [comment]
Hey @leogr, has this been fixed? I see the badges render as expected right now.

**Comment by leogr** [comment]
Hey @jasondellaluce 

IIRC, it's partially fixed. It might not work under some circumstances. Basically, we pick the last version by relying on the S3 bucket ordering which may not reflect the version order.

**Comment by leogr** [comment]
/remove-lifecycle stale

I confirm a similar issue is still present. Basically, it seems to me filenames are ordered lexicographically. 
So `falco-0.30.0-19+f7893fb-x86_64.deb` will come after than `falco-0.30.0-177+f86423d-x86_64.deb` that's not ok for our use case (you can check out the full order list [here](https://falco-distribution.s3-eu-west-1.amazonaws.com/?prefix=packages/deb-dev/stable/falco-)).

**Comment by leogr** [comment]
/remove-lifecycle rotten

cc @FedeDP
