### ISSUE TITLE
http_output to https with valid wildcard certificate won't work "Peer certificate cannot be authenticated with given CA certificates"

### ISSUE THREAD

**Issue by movd** [falcosecurity/falco#1685]
**Describe the bug**

When I set up `http_output` with an https URL like so:

```yaml
http_output:
  enabled: true
  url: https://falcosidekick.apps.k8s-cluster.example.com
```

I'll receive the following errors: `libcurl error: Peer certificate cannot be authenticated with given CA certificates`. 

As the URL states, I deploy a Falcosidekick inside a Kubernetes Cluster, but my Falco lives outside of the cluster and is [installed via apt](https://falco.org/docs/getting-started/installation/). When using unencrypted HTTP, it works just fine. 

It seems like the included `libcurl` does not check `/etc/ssl/certs`. This could be solved by added a feature like `http_output.ca_path = /etc/ssl/certs`.

**How to reproduce it**

Enable `http_output` with a valid https endpoint (see above). Do something to trigger an Falco alert that should get forwarded to your https destination. E. g.:

```sh
root@master01:~# echo "bad file" > /etc/falco_test.sh
```

`falco -v` reports on the alarm but can not forward it via https to my falcosidekick:

```sh
{"output":"11:21:18.715499038: Error File below /etc opened for writing (user=root user_loginuid=1173 command=bash parent=sudo pcmdline=sudo -Hi file=/etc/falco_test.sh program=bash gparent=bash ggparent=sshd gggparent=sshd container_id=host image=<NA>)","priority":"Error","rule":"Write below etc","time":"2021-06-29T09:21:18.715499038Z", "output_fields": {"container.id":"host","container.image.repository":null,"evt.time":1624958478715499038,"fd.name":"/etc/falco_test.sh","proc.aname[2]":"bash","proc.aname[3]":"sshd","proc.aname[4]":"sshd","proc.cmdline":"bash","proc.name":"bash","proc.pcmdline":"sudo -Hi","proc.pname":"sudo","user.loginuid":1173,"user.name":"root"}}
Tue Jun 29 11:21:18 2021: libcurl error: Peer certificate cannot be authenticated with given CA certificates
```

**Expected behaviour**

Event gets forwarded to the https destination

**Environment**

- Falco version:

```sh
~# falco --version
Falco version: 0.29.0
Driver version: 17f5df52a7d9ed6bb12d3b1768460def8439936d
```

- System info:

```sh
# falco --support | jq .system_info
Tue Jun 29 11:46:55 2021: Falco version 0.29.0 (driver version 17f5df52a7d9ed6bb12d3b1768460def8439936d)
Tue Jun 29 11:46:55 2021: Falco initialized with configuration file /etc/falco/falco.yaml
Tue Jun 29 11:46:55 2021: Loading rules from file /etc/falco/falco_rules.yaml:
Tue Jun 29 11:46:55 2021: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Tue Jun 29 11:46:55 2021: Loading rules from file /etc/falco/falco_rules.local.yaml:
{
  "machine": "x86_64",
  "nodename": "master01.k8s-cluster.example.com",
  "release": "4.19.0-17-amd64",
  "sysname": "Linux",
  "version": "#1 SMP Debian 4.19.194-2 (2021-06-21)"
}
````

- Cloud provider or hardware configuration:

- OS:

```sh
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
````

- Kernel:

```sh
# uname -a
Linux master01.k8s-cluster.example.com 4.19.0-17-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64 GNU/Linux
```

- Installation method:
Via offical deb straight like described in the offical docs: <https://falco.org/docs/getting-started/installation>. I added a Drop-In unit so that Falco uses the eBPF driver:

```sh
# systemctl status falco.service
* falco.service - Falco: Container Native Runtime Security
   Loaded: loaded (/lib/systemd/system/falco.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/falco.service.d
           `-ebpf.conf
   Active: active (running) since Tue 2021-06-29 11:44:43 CEST; 4min 37s ago
     Docs: https://falco.org/docs/
  Process: 22992 ExecStartPre=/sbin/modprobe falco (code=exited, status=0/SUCCESS)
 Main PID: 22993 (falco)
    Tasks: 17 (limit: 4915)
   Memory: 32.5M
   CGroup: /system.slice/falco.service
           `-22993 /usr/bin/falco --pidfile=/var/run/falco.pid
```

```sh
$ cat /etc/systemd/system/falco.service.d/ebpf.conf
# Empty FALCO_BPF_PROBE environment variable enables eBPF support
[Service]
Environment=FALCO_BPF_PROBE=""
````

**Additional context**

I need to encrypt the traffic between Falco and Falcosidekick.

The certificate is valid and works fine with plain curl (from same host to the same destination).

```sh
* Connected to falcosidekick.apps.k8s-cluster.example.com (10.1.103.43) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.apps.k8s-cluster.example.com
*  start date: Apr 1 00:00:00 2021 GMT
*  expire date: Apr 2 23:59:59 2022 GMT
*  subjectAltName: host "falcosidekick.apps.k8s-cluster.example.com" matched cert's "*.apps.k8s-cluster.example.com"
*  issuer: C=US; O=DigiCert Inc; CN=GeoTrust TLS DV RSA Mixed SHA256 2020 CA-1
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55a62db72fb0)
> HEAD / HTTP/2
> Host: falcosidekick.apps.k8s-cluster.example.com
> User-Agent: curl/7.64.0
```

<details>
<summary>View full curl log (click to expand)</summary>
<pre lang="sh">
$ curl -vvI 'https://falcosidekick.apps.k8s-cluster.example.com/'
* Expire in 0 ms for 6 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 1 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 2 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 2 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 2 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 2 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 2 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
* Expire in 0 ms for 1 (transfer 0x55a62db72fb0)
*   Trying 10.1.103.43...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55a62db72fb0)
* Connected to falcosidekick.apps.k8s-cluster.example.com (10.1.103.43) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.apps.k8s-cluster.example.com
*  start date: Apr 1 00:00:00 2021 GMT
*  expire date: Apr 2 23:59:59 2022 GMT
*  subjectAltName: host "falcosidekick.apps.k8s-cluster.example.com" matched cert's "*.apps.k8s-cluster.example.com"
*  issuer: C=US; O=DigiCert Inc; CN=GeoTrust TLS DV RSA Mixed SHA256 2020 CA-1
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55a62db72fb0)
> HEAD / HTTP/2
> Host: falcosidekick.apps.k8s-cluster.example.com
> User-Agent: curl/7.64.0
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 400
HTTP/2 400
< date: Tue, 29 Jun 2021 09:25:07 GMT
date: Tue, 29 Jun 2021 09:25:07 GMT
< content-type: text/plain; charset=utf-8
content-type: text/plain; charset=utf-8
< content-length: 34
content-length: 34
< x-content-type-options: nosniff
x-content-type-options: nosniff
< strict-transport-security: max-age=15724800; includeSubDomains
strict-transport-security: max-age=15724800; includeSubDomains

<
* Connection #0 to host falcosidekick.apps.k8s-cluster.example.com left intact
</pre>
</details>

**Comment by movd** [comment]
Unfortunately, there has been no feedback here so far. I have opened the issue again under falcosecurity/libs where it might be more suitable. https://github.com/falcosecurity/libs/issues/64

**Comment by adnankobir** [comment]
I can confirm that this issue is still present. @leogr can we please re-open this issue?

**Comment by leogr** [comment]
> I can confirm that this issue is still present. @leogr can we please re-open this issue?

Sure. Could you specify the Falco version?
/reopen

**Comment by leogr** [comment]
cc @jasondellaluce @FedeDP

**Comment by jasondellaluce** [comment]
According to #2103, this should be fixed in libs and merged in Falco (https://github.com/falcosecurity/falco/issues/2103#issuecomment-1224040650), so I think we're just waiting for the next release to rollout these changes.
