### ISSUE TITLE
Falco crash observed upon startup when using eBPF driver

### ISSUE THREAD

**Issue by simar7** [falcosecurity/falco#1690]
**Describe the bug**

Falco crashed when using eBPF driver

**How to reproduce it**

```
1. Install the eBPF driver. Steps: https://falco.org/docs/getting-started/installation/#install-driver
2. Run Falco: sudo FALCO_BPF_PROBE="" falco
```

**Expected behaviour**

Falco should not crash.

**Environment**

- Falco version:
``` falco --version
Falco version: 0.29.1
Driver version: 17f5df52a7d9ed6bb12d3b1768460def8439936d
```

- System info:
```falco --support | jq .system_info
{
  "machine": "x86_64",
  "nodename": "ubuntu-groovy",
  "release": "5.8.0-59-generic",
  "sysname": "Linux",
  "version": "#66-Ubuntu SMP Thu Jun 17 00:46:01 UTC 2021"
}
```

- Cloud provider or hardware configuration: 
```
Vagrant box VM, 8G mem, 2 CPU cores.
```

- OS:
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.10 (Groovy Gorilla)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.10"
VERSION_ID="20.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
```

- Kernel:
```uname -a
Linux ubuntu-groovy 5.8.0-59-generic #66-Ubuntu SMP Thu Jun 17 00:46:01 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

- Installation method:
https://falco.org/docs/getting-started/installation/#debian

**Additional context**

Full output observed when falco crashed: https://gist.github.com/simar7/4cfac0343a9196f8b035e75fe5ce0743

**Comment by jasondellaluce** [comment]
Hi @simar7, it would be great if you could share the version of clang/llvm you used to compile the eBPF probe. With the most recent updates, we currently support clang/llvm >= 7.0. See this similar issue 👉🏼   #1761

**Comment by simar7** [comment]
> Hi @simar7, it would be great if you could share the version of clang/llvm you used to compile the eBPF probe. With the most recent updates, we currently support clang/llvm >= 7.0. See this similar issue 👉🏼   #1761

Thanks that might have been it. I've updated clang several times so I'm not sure what I was running at the time but version 7 feels a little old to me. Any plans to upgrade to support a more recent version?

**Comment by jasondellaluce** [comment]
AFAIK clang 7.0 is the minimum supported version right now. As for newer versions, me and @FedeDP successfully tested compiling the probe with clang 14.
