### ISSUE TITLE
jsonpointer expression does not support slash escaping

### ISSUE THREAD

**Issue by ThisIsNotTheUserYouAreLookingFor** [falcosecurity/falco#1691]
**Description**

The documentation states that jevt.value uses json pointer expressions. This works for normal cases, but when tilde escaping is required, it throws a syntax error

**Reproduction**

Add the following macro to a rule file:

```
- macro: authzDecision
  condition: (jevt.value["/annotations/authorization.k8s.io~1decision"] in (["allow"]))
```

run the validation command:

```
falco -V your_rule_file.yaml
```

**Expected behaviour**

no validation errors, as ~1 is the official json pointer escape sign for /

**Screenshots**

N/A

**Environment**

- Falco version:
Falco version: 0.28.2
Driver version: 13ec67ebd23417273275296813066e07cb85bc91

- System info:
{
  "machine": "x86_64",
  "nodename": "<removed>",
  "release": "3.10.0-1062.1.2.el7.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP Mon Sep 30 14:19:46 UTC 2019"
}

- Cloud provider or hardware configuration:
- OS:
CentOS Linux 7 (Core)
- Kernel:
3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Installation method:
RPM

**Additional context**

**Comment by ThisIsNotTheUserYouAreLookingFor** [comment]
I have tested a bit further and even simplified the test:

```
- macro: authzDecision
  condition: (jevt.value[/annotations/authorization.k8s.io~1decision]=allow)
```

**Comment by leogr** [comment]
/remove-lifecycle stale
cc @jasondellaluce

**Comment by jasondellaluce** [comment]
I made some additional research, and it turns out our rule language grammar does not support the `~` character inside field arguments. I just opened #1777 to address this issue.
