### ISSUE TITLE
Forwarding audit logs to falco from an AKS cluster using sysdiglabs/aks-audit-log

### ISSUE THREAD

**Issue by thomas-goulet** [falcosecurity/falco#1702]
**Bug**

When trying to forward AKS audit logs to a falco instance using the setup from [sysdiglabs/aks-audit-log](https://github.com/sysdiglabs/aks-audit-log/blob/master/docs/readme-dev.md) the logs indicate all POST requests fail with a 400 code.

`**Error sending POST, retry 1, result: [BadRequest] System.Net.Http.HttpConnectionResponseContent`

**Problem**

The issue is that the falco webserver only accepts requests with the header `application/json` while the audit log forwarder sends requests with the header `application/json; charset=utf-8`. [See webserver.cpp](https://github.com/falcosecurity/falco/blob/46425b392cc949b78d754c71875ad9a9c5121106/userspace/falco/webserver.cpp#L151)

The webserver.cpp file should be modified to accept encoding values in the request headers.

Related issue : https://github.com/sysdiglabs/aks-audit-log/issues/4

**Comment by jemag** [comment]
I think this is a minor change that would help facilitate the auditing of AKS API server logs by using https://github.com/sysdiglabs/aks-audit-log directly, instead of having users maintain a fork modifying the header.
