### ISSUE TITLE
falco probe on 5.4.94 leads to "math between map_value pointer and register with unbounded min value is not allowed"

### ISSUE THREAD

**Issue by jerome-ibanes** [falcosecurity/falco#1707]
Loading the probe on 5.4.94 leads to the following error message:

```
root@hostname:/root#  FALCO_BPF_PROBE=/etc/falco/probe.o /usr/bin/falco --pidfile=/var/run/falco.pid -c /etc/falco/falco.yaml
[...]
regs=1 stack=0 before 969: (bf) r1 = r8
regs=1 stack=0 before 620: (15) if r1 == 0x3 goto pc+348
regs=1 stack=0 before 618: (18) r4 = 0xfffffffd
regs=1 stack=0 before 617: (15) if r1 == 0x2 goto pc+357
regs=1 stack=0 before 616: (15) if r1 == 0x1 goto pc+367
regs=1 stack=0 before 615: (65) if r1 s> 0x3 goto pc+323
regs=1 stack=0 before 614: (79) r0 = *(u64 *)(r10 -48)
regs=0 stack=20 before 613: (65) if r1 s> 0x7 goto pc+307
regs=0 stack=20 before 612: (65) if r1 s> 0x10 goto pc+31
 R0_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_rw=inv(id=0) R2_w=map_value(id=0,off=0,ks=4,vs=1612,umax_value=1519,var_off=(0x0; 0x7ff)) R3_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R4_w=
inv(id=0) R5_w=inv(id=0) R6_r=ctx(id=0,off=0,imm=0) R7_r=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8_r=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R9_w=inv(id=0) R10=fp0 fp-8=mmmmmmmm fp-16=map_value fp-24_w=mmmmmmm
m fp-32_w=mmmmmmmm fp-40_w=mmmmmmmm fp-48_rw=mmmmmmmm
parent already had regs=0 stack=0 marks
math between map_value pointer and register with unbounded min value is not allowed
processed 606 insns (limit 1000000) max_states_per_insn 0 total_states 13 peak_states 13 mark_read 6
Thu Aug 12 19:51:04 2021: Runtime error: bpf_load_program() err=22 event=filler/sys_setns_e message=0: (bf) r6 = r1
1: (b7) r1 = 0
2: (63) *(u32 *)(r10 -8) = r1
last_idx 2 first_idx 0
regs=2 stack=0 before 1: (b7) r1 = 0
3: (bf) r2 = r10
4: (07) r2 += -8
5: (18) r1 = 0xffff8ff1fafc8e00
7: (85) c. Exiting.
```

(Full output attached)

see above.

see above, I'm running 5.4.94 on ubuntu in docker with /proc/sys/kernel/unprivileged_bpf_disabled set to 0

**Screenshots**

[error.txt](https://github.com/falcosecurity/falco/files/6978206/error.txt)

**Environment**

- Falco version: 0.29.1

- System info: Ubuntu 18.04 in docker running kernel 5.4.94

{
  "machine": "x86_64",
  "nodename": "597628fbb370",
  "release": "5.4.94",
  "sysname": "Linux",
  "version": "#1 SMP Tue Feb 16 00:02:51 UTC 2021"
}

- Cloud provider or hardware configuration: aws m5.2xlarge
- OS: 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Kernel: Linux 597628fbb370 5.4.94 #1 SMP Tue Feb 16 00:02:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- 
- Installation method: docker

**Additional context**

**Comment by jibanes** [comment]
fails with clang 10, works fine with clang 6.

**Comment by jerome-ibanes** [comment]
compiler bug, not falco.

**Comment by abroglesc** [comment]
@jerome-ibanes what was the compiler bug and how did you solve it?

**Comment by jerome-ibanes** [comment]
I compiled it with clang/llvm 6 instead
