### ISSUE TITLE
Falco webserver with SSL error: null context when constructing CivetServer

### ISSUE THREAD

**Issue by 97turbotalon** [falcosecurity/falco#1708]
**Describe the bug**
Falco SSL webserver start up error msg
`Runtime error: Could not create embedded webserver: null context when constructing CivetServer. Possible problem binding to port. Exiting.`
This message only appears when setting enable_ssl to true and provide an ssl certificate with key.  Webserver will start properly when ssl is disabled.

**How to reproduce it**
Using latest helm chart with the following values set
  ssl_enabled=true
  certs.server.crt=./falco-cert/server.crt
  certs.server.key=./falco-cert/server.key
Falco secret is created with server.pem and mounted on falco container

**Expected behaviour**
Falco webserver is able to start properly when ssl enabled

**Environment**
- Falco version: 0.29.1
- System info:  k8s: 1.19.14
- Cloud provider or hardware configuration:
- OS:
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
- Kernel:
Linux ip-10-1-3-37 5.8.0-1038-aws #40~20.04.1-Ubuntu SMP Thu Jun 17 13:25:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Installation method:
Kubernetes helm chart installation

**Additional context**

Falco will start and run properly without ssl enabled.
This is not a port issue.  I've verified that the port is not in use but for troubleshooting purposes I tried 3 other non-standard unique port numbers.
I've also tried four different certificates including a sample provided on the CivietServer github repo, self-signed, self-signed with a RootCA, and published CA created cert.
I'm seeing the same problem with ssl enabled webserver on pervious versions of falco versions (0.29.0, 0.28.1).

**Comment by FedeDP** [comment]
Hi!
Sorry for the late reply; a quick search discovered: https://github.com/falcosecurity/falco/issues/860.  
Can you have a look at it? Specially this comment: https://github.com/falcosecurity/falco/issues/860#issuecomment-575087263.  
If the fix works for you, i guess that issue is still valid.

**Comment by marcindulak** [comment]
The issue may be depending on the OS, but it is still present and related to libssl version, on Ubuntu 18.04 and the latest falco

```
falco --version
# Falco version: 0.30.0
# Driver version: 3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4
```

In this case it looks like falco finds a `libcrypto.so`

```
strace falco > falco.txt 2>&1
cat falco.txt
...
stat("/usr/lib/x86_64-linux-gnu/x86_64", 0x7ffde0c7b070) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/libcrypto.so", O_RDONLY|O_CLOEXEC) = 7
read(7, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\200\7\0\0\0\0\0"..., 832) = 832
fstat(7, {st_mode=S_IFREG|0644, st_size=2917216, ...}) = 0
mmap(NULL, 5025632, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 7, 0) = 0x7fc2ccb2f000
mprotect(0x7fc2ccdca000, 2093056, PROT_NONE) = 0
mmap(0x7fc2ccfc9000, 188416, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 7, 0x29a000) = 0x7fc2ccfc9000
mmap(0x7fc2ccff7000, 12128, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fc2ccff7000
close(7)                                = 0
mprotect(0x7fc2ccfc9000, 180224, PROT_READ) = 0
munmap(0x7fc2d9e1a000, 34386)           = 0
fstat(1, {st_mode=S_IFREG|0644, st_size=3644817, ...}) = 0
uname({sysname="Linux", nodename="cp", ...}) = 0
close(3)                                = 0
sendto(4, "<11>Nov  6 19:55:30 falco: Runti"..., 166, MSG_NOSIGNAL, NULL, 0) = 166
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=127, ...}) = 0
write(2, "Sat Nov  6 19:55:30 2021: Runtim"..., 166Sat Nov  6 19:55:30 2021: Runtime error: Could not create embedded webserver: null context when constructing CivetServer. Possible problem binding to port.. Exiting.
) = 166
...
```

but it does not like the `libcrypto.so` version

```
cd /usr/lib/x86_64-linux-gnu
ls -al libcrypto.so
# lrwxrwxrwx 1 root root 16 Nov  6 20:19 libcrypto.so -> libcrypto.so.1.1
dpkg -S /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 
# libssl1.1:amd64: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
```

```
falco
Sat Nov  6 20:19:35 2021: Falco version 0.30.0 (driver version 3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4)
Sat Nov  6 20:19:35 2021: Falco initialized with configuration file /etc/falco/falco.yaml
Sat Nov  6 20:19:35 2021: Loading rules from file /etc/falco/falco_rules.yaml:
Sat Nov  6 20:19:36 2021: Loading rules from file /etc/falco/falco_rules.local.yaml:
Sat Nov  6 20:19:36 2021: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Sat Nov  6 20:19:36 2021: Starting internal webserver, listening on port 8765 (SSL)
truncating vsnprintf buffer: [,]
truncating vsnprintf buffer: [,]
Sat Nov  6 20:19:36 2021: Runtime error: Could not create embedded webserver: null context when constructing CivetServer. Possible problem binding to port.. Exiting.
```

Switching back to the older libssl seems to help

```
cd /usr/lib/x86_64-linux-gnu
rm -f libcrypto.so
ln -s libcrypto.so.1.0.0 libcrypto.so
rm -f libssl.so
ln -s libssl.so.1.0.0 libssl.so  # otherwise Segmentation fault (core dumped)
dpkg -S /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 
# libssl1.0.0:amd64: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
```

```
falco
Sat Nov  6 20:29:10 2021: Falco version 0.30.0 (driver version 3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4)
Sat Nov  6 20:29:10 2021: Falco initialized with configuration file /etc/falco/falco.yaml
Sat Nov  6 20:29:10 2021: Loading rules from file /etc/falco/falco_rules.yaml:
Sat Nov  6 20:29:10 2021: Loading rules from file /etc/falco/falco_rules.local.yaml:
Sat Nov  6 20:29:11 2021: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Sat Nov  6 20:29:11 2021: Starting internal webserver, listening on port 8765 (SSL)
20:29:11.422473000: Notice Privileged container started (user=<NA> user_loginuid=0 command=container:22cd012620b6 k8s_POD_calico-node-989s9_kube-system_651b6470-5d3d-47f4-86c2-6db10c71d81a_0 (id=22cd012620b6) image=k8s.gcr.io/pause:3.4.1)
20:29:11.572843000: Notice Privileged container started (user=<NA> user_loginuid=0 command=container:7e401d53807e k8s_POD_kube-proxy-6dmgn_kube-system_34ef93fa-d617-45a5-9f46-d287800b21e3_0 (id=7e401d53807e) image=k8s.gcr.io/pause:3.4.1)
...
```
