### ISSUE TITLE
Falco Image 0.29.1 apt sources.list expired

### ISSUE THREAD

**Issue by tpang-ameame** [falcosecurity/falco#1709]
**Describe the bug**

One of the path in /etc/apt/sources.list expired, so that `apt update/upgrade/install` will fail.

`deb http://security.debian.org/debian-security stable/updates main`

The folder/path has changed in remote repository, and there's no stable/updates but stable-security/updates exist.

I tried to modify it to `deb http://security.debian.org/debian-security stable-security/updates main`, and `apt update/upgrade` back to normal, but after `apt install` some packages, it will crash the falco probe complie:

./docker-entrypoint.sh
````
* Setting up /usr/src links from host
ln: failed to create symbolic link '/usr/src/linux-azure-5.4-headers-5.4.0-1047/linux-azure-5.4-headers-5.4.0-1047': Read-only file system
ln: failed to create symbolic link '/usr/src/linux-headers-4.15.0-143/linux-headers-4.15.0-143': Read-only file system
ln: failed to create symbolic link '/usr/src/linux-headers-5.4.0-1047-azure/linux-headers-5.4.0-1047-azure': Read-only file system
* Running falco-driver-loader for: falco version=0.29.1, driver version=17f5df52a7d9ed6bb12d3b1768460def8439936d
* Running falco-driver-loader with: driver=bpf, compile=yes, download=yes
* Mounting debugfs
* Trying to download a prebuilt eBPF probe from https://download.falco.org/driver/17f5df52a7d9ed6bb12d3b1768460def8439936d/falco_ubuntu-generic_5.4.0-1047-azure_49.o
curl: (22) The requested URL returned error: 404
Unable to find a prebuilt falco eBPF probe
* Trying to compile the eBPF probe (falco_ubuntu-generic_5.4.0-1047-azure_49.o)
make[2]: clang: No such file or directory
make[2]: *** [/usr/src/falco-17f5df52a7d9ed6bb12d3b1768460def8439936d/bpf/Makefile:33: /usr/src/falco-17f5df52a7d9ed6bb12d3b1768460def8439936d/bpf/probe.o] Error 127
make[1]: *** [Makefile:1760: /usr/src/falco-17f5df52a7d9ed6bb12d3b1768460def8439936d/bpf] Error 2
make: *** [Makefile:18: all] Error 2
mv: cannot stat '/usr/src/falco-17f5df52a7d9ed6bb12d3b1768460def8439936d/bpf/probe.o': No such file or directory
Unable to load the falco eBPF probe
````

Probably I didn't update sources.list to a correct destination, but it do need some fixes.

**Environment**

- Falco version:
0.29.0
- System info:
  "machine": "x86_64",
  "nodename": "",
  "release": "5.4.0-1047-azure",
  "sysname": "Linux",
  "version": "#49~18.04.1-Ubuntu SMP Thu Apr 22 21:28:54 UTC 2021"

- Installation method:
Azure Kubernetes 1.19.9

**Comment by stephanmiehe** [comment]
I ran into this today and I suspect this is related to Bullseye having been released a few days ago https://www.debian.org/releases/bullseye/. Given https://github.com/falcosecurity/falco/blob/master/docker/falco/Dockerfile#L1 stable now refers to Bullseye vs. Buster.

**Comment by holyspectral** [comment]
I saw this issue too and I changed the base image to `debian:10-slim` as a workaround.
