### ISSUE TITLE
Output sometimes missing k8s pod/container information

### ISSUE THREAD

**Issue by TomKeyte** [falcosecurity/falco#1726]
**Describe the bug**
I've installed falco using Helm, to an EKS cluster running k8s 1.21 - Falco is installed to it's own `falco` namespace.
The output is _sometimes_ missing k8s and container information, for example this is one output:
```json
{
    "output": "20:55:40.524063855: Error Package management process launched in container (user=root user_loginuid=-1 command=gem /usr/local/bin/gem contents fluent-plugin-elasticsearch container_id=1c626dd1ab1b container_name=<NA> image=<NA>:<NA>) k8s.ns=<NA> k8s.pod=<NA> container=1c626dd1ab1b k8s.ns=<NA> k8s.pod=<NA> container=1c626dd1ab1b",
    "priority": "Error",
    "rule": "Launch Package Management Process in Container",
    "time": "2021-09-09T20:55:40.524063855Z",
    "output_fields": {
        "container.id": "1c626dd1ab1b",
        "container.image.repository": null,
        "container.image.tag": null,
        "container.name": null,
        "evt.time": 1631220940524063855,
        "k8s.ns.name": null,
        "k8s.pod.name": null,
        "proc.cmdline": "gem /usr/local/bin/gem contents fluent-plugin-elasticsearch",
        "user.loginuid": -1,
        "user.name": "root"
    }
}
```

If I restart the falco pods, everything works again, and the above issue becomes

```json
{
    "output": "08:26:23.338086075: Error Package management process launched in container (user=root user_loginuid=-1 command=gem /usr/local/bin/gem contents fluent-plugin-elasticsearch container_id=2ded43ee4a42 container_name=k8s_fluentd_fluentd-56qhz_kube-system_ac262b2d-df79-4f8b-93e2-e1d9df697177_0 image=<redacted>.amazonaws.com/fluentd:latest) k8s.ns=kube-system k8s.pod=fluentd-56qhz container=2ded43ee4a42 k8s.ns=kube-system k8s.pod=fluentd-56qhz container=2ded43ee4a42",
    "priority": "Error",
    "rule": "Launch Package Management Process in Container",
    "time": "2021-09-10T08:26:23.338086075Z",
    "output_fields": {
        "container.id": "2ded43ee4a42",
        "container.image.repository": "<redacted>.amazonaws.com/fluentd",
        "container.image.tag": "latest",
        "container.name": "k8s_fluentd_fluentd-56qhz_kube-system_ac262b2d-df79-4f8b-93e2-e1d9df697177_0",
        "evt.time": 1631262383338086075,
        "k8s.ns.name": "kube-system",
        "k8s.pod.name": "fluentd-56qhz",
        "proc.cmdline": "gem /usr/local/bin/gem contents fluent-plugin-elasticsearch",
        "user.loginuid": -1,
        "user.name": "root"
    }
}
```

There are currently 2 nodes in the cluster, and if I observe the output for both falco pods, I **can't** see a pattern for this behaviour, such as one pod always showing no output - it's seemingly random

**How to reproduce it**

* Install falco to EKS cluster using helm: `h -n falco install falco falcosecurity/falco --set falco.jsonOutput=true,falco.jsonIncludeOutputProperty=true`

**Expected behaviour**

See all container/pod information in ever output

**Screenshots**

**Environment**

- Falco version:

0.29.1
- System info:

```
{
  "machine": "x86_64",
  "nodename": "falco-27cs6",
  "release": "5.4.129-63.229.amzn2.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP Tue Jul 20 21:22:08 UTC 2021"
}
```
(This was run from execing into a running falco container)
- Cloud provider or hardware configuration: AWS EKS
- OS: 

- Kernel:

- Installation method: Kubernetes (helm)

**Additional context**

**Comment by TomKeyte** [comment]
Just to add, it seems to happen more so if I kill a pod via `kubectl delete pod ...` and an issue occurs in the respawned pod

**Comment by kingcr7** [comment]
I meet the same issue, container info(eg image,name)  sometimes missing in output.   it's seemingly random
falco version:0.29.1 

2021-09-13T07:41:55.400471237+0000: Notice A shell was spawned in a container with an attached terminal (user=<NA> user_loginuid=-1 <NA> (id=xxxx) shell=sh parent=<NA> cmdline=sh terminal=34816 container_id=xxxx image=<NA>)
2021-09-13T07:41:59.153321506+0000: Notice A shell was spawned in a container with an attached terminal (user=<NA> user_loginuid=-1 gallant_benz (id=xxxx) shell=sh parent=<NA> cmdline=sh terminal=34816 container_id=xxxx image=alpine)

**Comment by FedeDP** [comment]
Hi!
It would  be great if you could provide some more context:  
* is this happening right after the start or after some hours of uptime?
* once container info are correctly shown, are they ever disappearing again?

Thank you very much, this will surely help to find the culprit!

**Comment by TomKeyte** [comment]
Hi,

I can't seem to see any trend with it. Sometimes the info is there, and sometimes it is not, that's as much as I can tell I'm afraid

There does seem to be a trend whereby if I
* Start the falco pods, they can produce valid information relating to running pods :heavy_check_mark: 
* If I then kill a pod, say a node microservice and exec into the re-spawned pod, falco is missing the expected properties

But that's not to say I haven't seen cases whereby it produces `N/A` style output for healthy pods that existed before falco

Thanks

**Comment by juris** [comment]
Have the same issue with Falco 0.30 installed via Helm 1.16.0. EKS 1.21 with Bottlerocket 1.1.4.

K8S information is always missing.

Here is an example alert from falcosidekick
```
12:36:19.492067277: Error Package management process launched in container (user=root user_loginuid=-1 command=apk add --no-cache openssh-client curl container_id=62aa023026cf container_name=<NA> image=<NA>:<NA>) k8s.ns=<NA> k8s.pod=<NA> container=62aa023026cf k8s.ns=<NA> k8s.pod=<NA> container=62aa023026cf
```

**Comment by juris** [comment]
However, if I try to launch falco process manually, inside the same pod, it shows all the metadata as it should.

**Comment by juris** [comment]
Turned out, I had to set containerd socket to [/run/dockershim.sock](https://github.com/bottlerocket-os/bottlerocket/commit/91810c85b83ff4c3660b496e243ef8b55df0973b). Metadata now in place for Bottlerocket.

Have no idea why it worked with a manual falco launch inside a pod thogh.

**Comment by henro001** [comment]
I am having same issue, and interestingly with a fluentd image as well. I enabled custom macro using `container.image.repository`, most of the events are matched and filtered, but those without metadata will not.

**Comment by mattups** [comment]
Hi, I'm having the same issue basically, with falco agents installed as container in my kubernetes cluster, when an events is detected on one of the actual hosts instead of a container the `container.id` field comes with just `host` value but not hostname. Is there a way to get it?

```
 {
    "output": "12:36:43.918198999: Error File below a monitored directory opened for writing (user=<NA> user_loginuid=1000 command=sshroot@truncated file=/home/root/.ssh/known_hosts parent=bash pcmdline=bash gparent=sshd container_id=host image=<NA>) k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host",
    "priority": "Error",
    "rule": "Write below monitored dir",
    "time": "2022-04-26T12:36:43.918198999Z",
    "output_fields": {
      "container.id": "host",
      "container.image.repository": null,
      "evt.time": 1650976603918199000,
      "fd.name": "/home/root/.ssh/known_hosts",
      "k8s.ns.name": null,
      "k8s.pod.name": null,
      "proc.aname[2]": "sshd",
      "proc.cmdline": "ssh root@truncated",
      "proc.pcmdline": "bash",
      "proc.pname": "bash",
      "user.loginuid": 1000,
      "user.name": null
    }
```

**Comment by rdubya16** [comment]
@FedeDP What is needed to investigate this issue further? We are also seeing it.

**Comment by alacuku** [comment]
Hi all,
falco populates and maintains a [state](https://github.com/falcosecurity/libs/blob/8f66b87a6768e6575a9f6c4e409d15a7b38ca92d/userspace/libsinsp/k8s_state.h#L37) for the k8s cluster. The state is updated periodically and each time a syscall event is received, it is enriched with the available metadata such as process/thread info, k8s info, etc. It could happen that sometimes a syscall event, generated in a running container, is received  but the related k8s metadata is not available. In that case, Falco just outputs the event and fills the fields with the available data. 
Having rules that use k8s fields as conditions could have the side effect that the rules are not triggered. There is no way to ensure that the k8s metadata fields are cached for each generated event since it would require falco to contact the k8s api server each time an event is received. That would slow down falco causing the drivers to drop the syscalls events.
