### ISSUE TITLE
Can we get a new falco release please?

### ISSUE THREAD

**Issue by Len0k** [falcosecurity/falco#1740]
**Motivation**

The latest Falco release is of 3 months ago, and since then a lot of improvements have been made. In particular [this bug](https://github.com/falcosecurity/falco/issues/778) have been fixed. We are deploying Falco via helm charts in my organisation, and it would be great to have a docker image with some latest fixes available for use.

**Feature**

Please cut a 0.29.2 release that includes [this patch](https://github.com/falcosecurity/falco/pull/1667)

**Alternatives**

We would like to avoid using the `master` build, as it changes often and doesn't provide reliability guaranties.

**Additional context**

None

**Comment by zuc** [comment]
@Len0k also, please bear in mind that we recently changed our release cycle to follow a fixed schedule (see https://github.com/falcosecurity/falco/pull/1711) 😉

**Comment by Len0k** [comment]
Sounds good, thanks!
