### ISSUE TITLE
Cut 0.30.0 release

### ISSUE THREAD

**Issue by araujof** [falcosecurity/falco#1741]
## Scheduled to happen: ~2021-09-30~ 2021-10-01
All targeted pull requests have been merged; waiting for build and tests for release [0.30.0](https://github.com/falcosecurity/falco/milestone/19).

## Release Steps
Process is described in [this document](https://github.com/falcosecurity/falco/blob/master/RELEASE.md).

## Release Blocking PRs
- [x] https://github.com/falcosecurity/falco/pull/1738
- [x] https://github.com/falcosecurity/falco/pull/1744

## Action Items
- [x] Pre-release: Prebuilt drivers publish :point_right: https://github.com/falcosecurity/test-infra/pull/522
- [x] Pre-release: [Milestones](https://github.com/falcosecurity/falco/milestone/19)
- [x] Pre-release: [Changelog](https://github.com/falcosecurity/falco/pull/1745)
- [x] Release: Tag
- [x] Release: GH Release
- [x] Docs: [Meeting-notes](https://github.com/falcosecurity/community/pull/142)
- [x] Announcements: Blog [falco-website](https://github.com/falcosecurity/falco-website/pull/500)
- [x] Announcements: Send [email](https://lists.cncf.io/g/cncf-falco-dev/message/287) to cncf-falco-dev mailing list
- [x] Announcements: [Falco Slack channel](https://kubernetes.slack.com/archives/CMWH3EH32/p1633092598474600)
- [x] Website [snapshot](https://github.com/falcosecurity/falco-website/blob/master/release.md#create-a-new-website-snapshot)
- [x] Website: bump Falco version to 0.30.0 
      https://github.com/falcosecurity/test-infra/pull/523
      https://github.com/falcosecurity/falco-website/pull/501

## Open Questions
/milestone 0.30.0
/assign @araujof @leogr @zuc @jasondellaluce 
/kind documentation

**Comment by jasondellaluce** [comment]
Leaving a comment so that I can be assigned.

**Comment by leogr** [comment]
/assign @zuc @jasondellaluce

@poiana are you happy now? :smile_cat:

**Comment by leogr** [comment]
Update:
- drivers are building (see the CI status on https://github.com/falcosecurity/test-infra - N.B.: one job is broken, we will re-run it when others finish)

**Comment by leodido** [comment]
> /assign @zuc @jasondellaluce
> 
> @poiana are you happy now? 😸

Do not harass my friendly bird please :D

**Comment by leodido** [comment]
@araujof ty for opening this PR. Anyways, the Release PR field is probably wrong. You probably mistyped the PR :)

**Comment by leogr** [comment]
Update:

While extensively testing Falco, we found a last-minute bug (as usual :disappointed:, full details here :point_right: https://github.com/falcosecurity/libs/issues/89). 
We are working on a fix, which should be available soon. But, unfortunately, the fix probably will require changing the driver version and so rebuild pre-builts drivers again. That will probably delay the release a bit.
I will keep you posted.

**Comment by leogr** [comment]
> While extensively testing Falco, we found a last-minute bug (as usual disappointed, full details here point_right [falcosecurity/libs#89](https://github.com/falcosecurity/libs/issues/89)). We are working on a fix, which should be available soon. But, unfortunately, the fix probably will require changing the driver version and so rebuild pre-builts drivers again. That will probably delay the release a bit. I will keep you posted.

The workaround was to downgrade openssl (see https://github.com/falcosecurity/libs/pull/90). A new driver version is now required, so we need to update Falco and re-build drivers. Hopefully, we are still in time for tomorrow's release (otherwise we will just delay a bit).

**Comment by zuc** [comment]
Thanks to everyone who helped (@jasondellaluce @fededp @lucklypse @leogr), we now have:

- https://github.com/falcosecurity/libs/pull/90 (merged)
- https://github.com/falcosecurity/falco/pull/1744 (pending review)
- https://github.com/falcosecurity/test-infra/pull/522 (pending review)

Then we should be finally good!

**Comment by leogr** [comment]
Dev packages are ready to be tested:

- https://download.falco.org/packages/bin-dev/x86_64/falco-0.29.1-30%2B46d5266-x86_64.tar.gz
- https://download.falco.org/packages/deb-dev/stable/falco-0.29.1-30%2B46d5266-x86_64.deb
- https://download.falco.org/packages/rpm-dev/falco-0.29.1-30%2B46d5266-x86_64.rpm

Also, for the latest docker image: `docker pull falcosecurity/falco:master`

**Comment by leogr** [comment]
Note for the release team: since https://github.com/falcosecurity/test-infra/pull/522 got merged, we have to clean up the `5727c45` from S3 because it does not belong to any Falco release. I will take care of that.

**Comment by leodido** [comment]
> Note for the release team: since [falcosecurity/test-infra#522](https://github.com/falcosecurity/test-infra/pull/522) got merged, we have to clean up the `5727c45` from S3 because it does not belong to any Falco release. I will take care of that.

Ty LeoG!

**Comment by leogr** [comment]
> Note for the release team: since [falcosecurity/test-infra#522](https://github.com/falcosecurity/test-infra/pull/522) got merged, we have to clean up the `5727c45` from S3 because it does not belong to any Falco release. I will take care of that.

Done!

**Comment by zuc** [comment]
All pre-build drivers for `3aa7a83` have now been published on S3 📦

**Comment by leogr** [comment]
Release in progress :point_down: 
https://app.circleci.com/pipelines/github/falcosecurity/falco/1685/workflows/48e4da97-6275-4606-8384-4efbbcc62602

**Comment by leogr** [comment]
https://falco.org/blog/falco-0-30-0/ :tada:

**Comment by araujof** [comment]
@leogr motion to close this issue?

**Comment by leogr** [comment]
Just waiting for these two PRs: 
- https://github.com/falcosecurity/falco-website/pull/501
- https://github.com/falcosecurity/test-infra/pull/523

They are needed to complete the website archiving process

**Comment by leogr** [comment]
:partying_face: 
/close
