### ISSUE TITLE
BPF probe on Falco 0.30.0 on 5.4.94 leads to bpf stacktrace

### ISSUE THREAD

**Issue by jerome-ibanes** [falcosecurity/falco#1748]
**Describe the bug**

I've compiled the Falco 0.30.0 bpf probe on ubuntu-18, /usr/bin/falco being the one provided by https://download.falco.org/packages/bin/x86_64/falco-0.30.0-x86_64.tar.gz

Running falco (using the bpf probe) leads to:
Thu Oct  7 04:50:29 2021: Falco version 0.30.0 (driver version 3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4)
Thu Oct  7 04:50:29 2021: Falco initialized with configuration file /etc/falco/falco.yaml
Thu Oct  7 04:50:29 2021: Loading rules from file /etc/falco/falco_rules.yaml:
Thu Oct  7 04:50:30 2021: Loading rules from file /etc/falco/falco_rules.local.yaml:
Thu Oct  7 04:50:30 2021: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
0: (bf) r6 = r1
[full stacktrace attached to this ticket]

**How to reproduce it**

Compile and run the bpf probe on 5.4.94, i.e.

```
cd /usr/src
tar -C / -xzf falco-0.30.0-x86_64.tar.gz --strip-components 1
cd /usr/src/falco-*[0-9a-f]/bpf
KERNELDIR=/usr/src/linux make
cp probe.o /etc/falco/probe.o
FALCO_BPF_PROBE="/etc/falco/probe.o" /usr/bin/falco --pidfile=/var/run/falco.pid -c /etc/falco/falco.yaml
Thu Oct  7 04:50:29 2021: Falco version 0.30.0 (driver version 3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4)
Thu Oct  7 04:50:29 2021: Falco initialized with configuration file /etc/falco/falco.yaml
Thu Oct  7 04:50:29 2021: Loading rules from file /etc/falco/falco_rules.yaml:
Thu Oct  7 04:50:30 2021: Loading rules from file /etc/falco/falco_rules.local.yaml:
Thu Oct  7 04:50:30 2021: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
0: (bf) r6 = r1
1: (b7) r1 = 0
2: (63) *(u32 *)(r10 -80) = r1
last_idx 2 first_idx 0
regs=2 stack=0 before 1: (b7) r1 = 0
[...]
```

full stacktrace attached.

```
sysctl -a | grep bpf
kernel.bpf_stats_enabled = 0
kernel.unprivileged_bpf_disabled = 0
net.core.bpf_jit_enable = 1
net.core.bpf_jit_harden = 0
net.core.bpf_jit_kallsyms = 0
net.core.bpf_jit_limit = 264241152
```

I've ran that same operation (build bpf probe, run it as above) with 0.29.1 and it worked fine, no issue; same os, same kernel, same kernel config.

**Expected behaviour**

Falco running

**Environment**

- Falco version: 0.30.0
- System info: x86_64 ubuntu-18 with kernel 5.4.94 within a docker 19.03 container running with SYS_ADMIN and SYS_RESOURCE (note that 0.29.1 works fine in the exact same environment, under the same docker engine).
- Cloud provider or hardware configuration:
- OS: ubuntu-18
- Kernel: 5.4.94
- Installation method: tgz

Complete bpf stacktrace below.

[bug-1748.txt](https://github.com/falcosecurity/falco/files/7305900/bug-1748.txt)

**Comment by jibanes** [comment]
```
$ clang --version
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by jibanes** [comment]
It worked with clang-12 no problem (on ubuntu 20) closing this issue, hopefully this will help others.

**Comment by FedeDP** [comment]
Hi @jibanes! Recently we added support for clang >= 5 for our eBPF probe. 
It would be great if you could test. Note that you need to build the eBPF from the libs repository, as falcosecurity-libs are not updated yet on falco.
Thank you!

**Comment by jerome-ibanes** [comment]
Thank you Frederico, should I pull from master, or it will be released as
0.30.1?

**Comment by FedeDP** [comment]
The fix should be released as part of falco 0.31.0, ~ end of january. 
You can try it now by cloning the libs repository and manually building the probe; then load the built probe with falco 0.30 should work just fine!

**Comment by jasondellaluce** [comment]
Hey @jibanes, if you don't need any additional help, would you mind closing this issue? Thanks!

**Comment by FedeDP** [comment]
Falco 0.31.0 is now released. @jibanes i think you can test it and eventually close it :) 

Thanks!
