### ISSUE TITLE
Best Practices to overcome issue running falco upon upgrade to latest AWS-AMI 

### ISSUE THREAD

**Issue by jonathang-simplex** [falcosecurity/falco#1749]
Based off of other similar issues from the past - like these:
https://github.com/falcosecurity/falco/issues/1643
https://github.com/falcosecurity/falco/issues/1531
https://github.com/falcosecurity/falco/issues/1644

It seems that every time AWS releases a new AMI that has changes to Kernel, it takes some time until a new kernel module/driver is available for falco - making it unusable in the new AMI.
According to documentation - this process (of new module creation for falco) takes anywhere between 1-2 weeks.

Please specify in documentation - what would be considered best practice approach to running falco in an environment that always installs the latest AMI's from AWS?
We prefer not to hard-code the AMI version for AWS.

A best practice org-wide use case is much welcome.
Thanks!

**Comment by ThibaultLengagne** [comment]
Hello,

I wanted to thank the team for this great product ! 
The only issue we experience is exactly what @jonathang-simplex is describing. This is a real problem for many of our clients who have Falco downtime for several weeks each time.

How could we help you with this issue ?

**Comment by Issif** [comment]
Hello @jonathang-simplex @ThibaultLengagne,

We know this issue and be sure this is one of our top topics for this year. We've several ideas and we'll do our best for improving the UX.

Until that, if you notice a missing driver, you can also help the community by submitting a PR for adding your system in the list of pre-built drivers: https://github.com/falcosecurity/test-infra/tree/master/driverkit

We try to review/merge these PR as fast as possible. 

Thanks.
