### ISSUE TITLE
Add SHA256 Signatures for RPMs

### ISSUE THREAD

**Issue by twa16** [falcosecurity/falco#1751]
Hello, we are attempting to leverage Falco in an environment where SHA256 hashes are required for RPM signatures. 

With the current RPMs, we are unable to install directly from the repository. I should be able to add it to the builds scripts if there is interest.

**Comment by panda** [comment]
👍

**Comment by leodido** [comment]
Hello @twa16 

To me, it sounds like a very good first issue and contribution!

Feel free to send a PR for it 😊

**Comment by twa16** [comment]
Alright! I will open one up here in a next few days!

**Comment by twa16** [comment]
@leodido I opened a PR. Please let me know if I need to correct anything!
