### ISSUE TITLE
Propose log rotation in parameters for falco events stored in falco file output

### ISSUE THREAD

**Issue by mathildeHermet** [falcosecurity/falco#1808]
**Motivation**

In my perception of Falco configuration, file_output consists in Falco log file. This file is never emptied.
We should implement a system  as kubernetes does for [audit-log](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/):
```yaml
--audit-log-maxage     # defined the maximum number of days to retain old audit log files
--audit-log-maxbackup  # defines the maximum number of audit log files to retain
--audit-log-maxsize    # defines the maximum size in megabytes of the audit log file before it gets rotated
```
**Feature**

Having a mechanism as logrotate or a cron job to manage Falco `file_output` to avoid having an infinite size.

**Comment by andreabonanno** [comment]
Thanks for the valid idea!
I provided a possible implementation of this feature with PR #1827

**Comment by nabokihms** [comment]
Hey! The feature is still valid. In my case, I want to store events in files and then send them to the long-term logs storage. It is excessive to keep events forever, but there is no way to configure it with the file_output now.

Is it possible to reopen this issue?
