### ISSUE TITLE
Multi-arch docker image request

### ISSUE THREAD

**Issue by 2Bor2C** [falcosecurity/falco#1813]
**Motivation**

 Our deployment contains a mix of x86 and arm.  Having a single multi-arch Docker image to deploy using helm on both x86 and arm platforms would be really helpful and useful feature for our team.  

**Feature**

Buildx (https://docs.docker.com/buildx/working-with-buildx/ ) - This is the tool used by use for internal images and a possible option.

**Comment by nonamef** [comment]
Linked https://github.com/falcosecurity/falco/issues/1589

**Comment by odidev** [comment]
Hi Team,
Would also love to see multi-arch Docker image release for arm64 and amd64 platform. Would be happy to help with it.

**Comment by baasumo** [comment]
+1
