### ISSUE TITLE
Log rule expansion under log_level=debug upon startup

### ISSUE THREAD

**Issue by josb** [falcosecurity/falco#1814]
**Motivation**
It would be great to have the ability to see rule expansions printed, especially with complex rules using lists, macros and exceptions that are being augmented using `append: true`. This so the author can make sure that they are as desired.

**Feature**

When running `falco` with `--option log_level=debug` I would like `falco` to emit the expanded rules after reading all config files.

**Alternatives**

None?

**Additional context**

None?

**Comment by jasondellaluce** [comment]
Hey @josb, I recently took on refactoring the rule loader, and now it should be quite easier to add a feature like this. Do you think it would make sense to make this available only with the `-v` verbose option? Also, would you prefer this to happen for all rules, or having a selective CLI option to print only one?

**Comment by josb** [comment]
Hi @jasondellaluce , thanks for doing that! I think putting this under `-v` would be fine as it's really a debugging aid.Not sure if the extra effort for a CLI option to print a single rule is needed, your call :-)

**Comment by Andreagit97** [comment]
This will be addressed by this: https://github.com/falcosecurity/falco/pull/2544 :tada:
Moreover, this issue seems already summarized here https://github.com/falcosecurity/falco/issues/2372
Can we close this?
