### ISSUE TITLE
Require Cloudtrail and Json prebuilt plugins for ARM64

### ISSUE THREAD

**Issue by odidev** [falcosecurity/falco#1821]
Hi Team,
I have been working on running and testing Falco on arm64 platform but the `make all` command fails on arm64 platform due to unavailability of prebuilt plugins of `cloudtrail` and `json` for arm64 at https://download.falco.org/?prefix=plugins/dev/ . 
I have successfully built above mentioned plugin locally on arm64 platform and ran `make all` command successfully.
Do you have any plans for uploading prebuilt plugins of `cloudtrail` and `json` for arm64 platform?
It will be very helpful if prebuilt plugins for ARM64 are available.

**Comment by odidev** [comment]
Hi Team,
A gentle reminder to kindly take a look at the above issue and make prebuilt plugins available for arm64.

**Comment by jasondellaluce** [comment]
@odidev I think we can close this since plugins for ARM64 are now published both for dev and stable builds. WDYT?
