### ISSUE TITLE
Falco sends a requests to requestbin.net

### ISSUE THREAD

**Issue by konstantin-921** [falcosecurity/falco#1822]
I have added a new Falco rule in `falco_rules.local.yaml` to trace malicious IPs:

```
- rule: Malicious IPs
  desc: Detect connections to/from a malicious IP
  condition: >
    ((inbound_outbound) and fd.sip in (malicous_ip_list) or
    fd.cip in (malicous_ip_list) or
    fd.cip.name in (log4shell_domains) or
    fd.sip.name in (log4shell_domains) or
    fd.lip.name in (log4shell_domains) or
    fd.rip.name in (log4shell_domains))
  output: Suspicious connection to/from a malicious IP detected (command=%proc.cmdline connection=%fd.name user=%user.name container_id=%container.id)
  priority: WARNING
  tags: [network]
```
The files storing malicous_ip_list and log4shell_domains are updated dynamically 1 time per day. 

After a while I started getting these alerts from Falco:
`{"output":"11:41:04.143970036: Warning Suspicious connection to/from a malicious IP detected (command=falco --pidfile=/var/run/falco.pid connection=10.0.7.27:10360->172.67.190.62:0 user=root container_id=host)","priority":"Warning","rule":"Malicious IPs","source":"syscall","tags":["network"],"time":"2021-12-14T16:41:04.143970036Z", "output_fields": {"container.id":"host","evt.time":1639500064143970036,"fd.name":"10.0.7.27:10360->172.67.190.62:0","proc.cmdline":"falco --pidfile=/var/run/falco.pid","user.name":"root"}}`

I started checking this IP - 172.67.190.62. It turned out that this IP belongs to the domain requestbin.net (from my log4shell_domains list). In the log above, we see that the initiator of the request is Falco himself. Then, using iptraf, I checked whether these requests actually to requestbin.net they go outside. As a result, I could not track any packages to 172.67.190.62 while Falco was sending the appropriate alerts.

My question is why does Falco send (or pretend to send) packages to ip that belongs to the domain requestbin.net?

**Expected behaviour**

Falco should not independently send any requests to requestbin.net or anywhere else.

**Environment**

- Falco version: 0.30.0
- System info:
  "machine": "x86_64",
  "release": "5.4.0-86-generic",
  "sysname": "Linux"
- OS: Ubuntu 18.04
- Kernel: Linux 5.4.0-86-generic 18.04.1-Ubuntu SMP Sat Sep 18 03:11:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Installation method: apt package

**Comment by leogr** [comment]
Falco trying to resolve the DNS? I recall a similar issue https://github.com/falcosecurity/falco/issues/835

**Comment by konstantin-921** [comment]
> 

Yes. You are right. Can be closed.
