### ISSUE TITLE
Unable to "override" k8s audit rules

### ISSUE THREAD

**Issue by tspearconquest** [falcosecurity/falco#1836]
**Describe the bug**
We recently setup k8s audit logging in our dev cluster on AKS and configured the audit log forwarder to forward events to falco.
Upon loading the rules, we saw some outputs that we immediately wanted to customize the rules for, so we proceeded to follow the same strategy we use for the primary falco rules, where we have the default rules from your team and then an override configuration which redefines the same rules with our changes.

So we did this for the k8s audit rules and restarted Falco, but the pod does not start. Instead it runs out of memory.

This happens even if we copy a default rule verbatim into the override config file.

Install falco helm chart with audit logging rules. Must use build 0.31.0 or higher
Ensure to enable the web server.
Ensure to configure reasonable resource limits on the pod.

```
          limits:
            cpu: 700m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
```

Add a new audit logging configmap manifest to override the default k8s audit logging rules, similar to the one used to override the falco rules for syscall and network events, and be sure to add the config file to the falco configmap.
Copy in one of the k8s audit logging rules or a macro or a list to the new configmap, deploy the configmaps and redeploy the pods. You do not need to change the rule, macro, or list in any way to trigger the issue.

In case the loading order matters, we load the standard falco rules, then their overrides, then the k8s audit rules and then finally the k8s audit overrides. We did not test another loading order.

Upon trying to start the pods, falco will be oomkilled. Upon commenting out the new config file in the falco config, falco will start properly again.

Falco should start up and override the default k8s audit rules the same way it does for syscall and network rules

**Environment**

- Falco version: 0.31.0

- Cloud provider or hardware configuration: AKS
- OS: Ubuntu 18.04

- Installation method: Kubernetes, customized from the helm chart templates and using an image built from the above falco dev release.

**Comment by jasondellaluce** [comment]
Hey @tspearconquest, I was wondering if you tried to increase the memory resource limit, and if the issue still occurs even in that case.

**Comment by tspearconquest** [comment]
Hi @jasondellaluce Can you suggest a better limit? It has been running fine with this limit for some time so it's not clear what we should adjust that limit to. The helm chart uses 1024Mi, however that seems excessive for Falco by itself to me.

**Comment by jasondellaluce** [comment]
Oh I was just curious if you could try to increase the memory limit for test purposes in your environment. I'm investigating this issue, and I wanted to understand if your problem was related to a memory abuse or to the rule loader logic! I think 1024Mi could work for this test.

**Comment by jasondellaluce** [comment]
@tspearconquest would you test this with the new Falco 0.32 and see if this is still an issue?
