### ISSUE TITLE
Cut 0.31.0 Release

### ISSUE THREAD

**Issue by jasondellaluce** [falcosecurity/falco#1857]
## Scheduled to happen: ~2022-01-31

All targeted pull requests have been merged; waiting for build and tests for release [0.31.0](https://github.com/falcosecurity/falco/milestone/21).

## Release Steps

Process is described in [this document](https://github.com/falcosecurity/falco/blob/master/RELEASE.md).

## Release Blocking PRs

- [x] https://github.com/falcosecurity/libs/pull/185
- [x] https://github.com/falcosecurity/falco/pull/1863
- [x] https://github.com/falcosecurity/falco/pull/1864
- [x] https://github.com/falcosecurity/falco/pull/1867
- [x] https://github.com/falcosecurity/falco/pull/1868
- [x] https://github.com/falcosecurity/falco/pull/1871
- [x] https://github.com/falcosecurity/falco/pull/1872
- [x] https://github.com/falcosecurity/falco/pull/1873
- [x] https://github.com/falcosecurity/falco/pull/1875
- [x] https://github.com/falcosecurity/plugins/pull/59
- [x] https://github.com/falcosecurity/falco/pull/1878

## Nice-to-have PRs

- [x] https://github.com/falcosecurity/falco/pull/1810
- [x] https://github.com/falcosecurity/falco/pull/1863

## Action Items

- [x] **Pre-Release**
    - [x] Pick a final driver version in Falco: [319368f1ad778691164d33d59945e00c5752cd27](https://github.com/falcosecurity/libs/commit/319368f1ad778691164d33d59945e00c5752cd27) 
    - [x] Release and publish plugins
        - [x] https://github.com/falcosecurity/plugins/releases
        - [x] https://download.falco.org/?prefix=plugins/stable/ 
    - [x] Prebuilt drivers publish 
      - https://github.com/falcosecurity/test-infra/pull/613
    - [x] Milestones: https://github.com/falcosecurity/falco/milestone/21
    - [x] Changelog: https://github.com/falcosecurity/falco/pull/1880
- [x] **Release**
    - [x] Tag: https://github.com/falcosecurity/falco/tree/0.31.0
    - [x] GitHub Release: https://github.com/falcosecurity/falco/releases/tag/0.31.0
- [x] **Docs**
    - [x] Meeting Notes: https://github.com/falcosecurity/community/pull/145
- [x] **Website**
    - [x] Snapshot
        - [x] https://github.com/falcosecurity/falco-website/tree/v0.30
        - [x] https://github.com/falcosecurity/test-infra/pull/616
    - [x] Bump Falco version to 0.31.0: https://github.com/falcosecurity/falco-website/pull/536
    - [x] Updates 
        - [x] https://github.com/falcosecurity/falco-website/pull/493
        - [x] https://github.com/falcosecurity/falco-website/pull/515
        - [x] https://github.com/falcosecurity/falco-website/pull/538
- [x] **Announcements**
    - [x] Blog: https://github.com/falcosecurity/falco-website/pull/537
    - [x] Send email
    - [x] Falco Slack channel
- [x] **Post-Release**
    - [x] Client Go
        - [x] https://github.com/falcosecurity/client-go/pull/56
        - [x] Release new version: https://github.com/falcosecurity/client-go/releases/tag/v0.5.0
    - [x] Falco Exporter
        - [x] https://github.com/falcosecurity/falco-exporter/pull/68
        - [x] Release new version: https://github.com/falcosecurity/falco-exporter/releases/tag/v0.7.0
    - [x] Event Generator
        - [x] https://github.com/falcosecurity/event-generator/pull/58
    - [x] Helm Charts
        - [x] https://github.com/falcosecurity/charts/pull/308
        - [x] Release new charts

## Open Questions

/milestone 0.31.0

/assign @jasondellaluce @terylt @Issif 

/kind documentation

**Comment by leogr** [comment]
Waiting for https://github.com/falcosecurity/libs/pull/185

**Comment by jasondellaluce** [comment]
In the milestone https://github.com/falcosecurity/falco/milestone/21 there are still some open PRs. Those are not blocking, but since the release date is approaching I think we should wait until the end of this week to see if some of them get merged.

Starting from Mon 24th, I would propose to stop merging PRs and start testing what we have for the rest of the week until the release.

**Comment by leogr** [comment]
> Starting from Mon 24th, I would propose to stop merging PRs and start testing what we have for the rest of the week until the release.

Totally agree. :+1: 

I would also pick the driver version within this week.

**Comment by leogr** [comment]
quick update: 
I, @jasondellaluce and @FedeDP  noticed some minor issues (with rule checks on loading) that we're trying to fix.

**Comment by leogr** [comment]
> quick update: I, @jasondellaluce and @FedeDP noticed some minor issues (with rule checks on loading) that we're trying to fix.
Rule loader checks fixed here :point_right: https://github.com/falcosecurity/falco/pull/1864 (plus other small fixes).

We also need to update the cloudtrail plugin (a fix was merged recently) :point_right: https://github.com/falcosecurity/falco/pull/1865

Finally, as nice-to-have: https://github.com/falcosecurity/falco/pull/1863

**Comment by leogr** [comment]
Dev package can be download from here :point_down: 
https://app.circleci.com/pipelines/github/falcosecurity/falco/2007/workflows/cee05a2c-4d58-44f2-b6e3-8c7013cc3fda/jobs/18259/artifacts

I believe it's time to test :angel:

**Comment by leogr** [comment]
Nice-to-have: https://github.com/falcosecurity/falco/pull/1810

**Comment by leogr** [comment]
This https://github.com/falcosecurity/falco/blob/master/rules/aws_cloudtrail_rules.yaml#L23 is out-to-date.
The cloudtrail plugin version must be bumped to 0.3.0, but also the json plugin is required (we have to add it too).

**Comment by jasondellaluce** [comment]
On top of this, we also need to include the newly-merged`execveat` syscall in the Falco ruleset. Apparentely, it `execve` is used at this line, so I think it would make sense to check for `execveat` there too 👉🏼 https://github.com/falcosecurity/falco/blob/2f82a9baa193825337049e4ac69793f3074d6110/rules/falco_rules.yaml#L66

**Comment by FedeDP** [comment]
@leogr  done in https://github.com/falcosecurity/falco/pull/1867!

**Comment by leogr** [comment]
Update:
pre-built drivers in the making :point_down: 
https://github.com/falcosecurity/test-infra/pull/613

**Comment by Andreagit97** [comment]
@jasondellaluce done in #1868 :tada: !

**Comment by jasondellaluce** [comment]
There seem to be an issue with the musl optimized build. The ambiguity is that the `MUSL_OPTIMIZED_BUILD` is the name of the CMake option that triggers the musl build, whereas `MUSL_OPTIMIZED` is the name of the definition expected by `libs`. Falco passes the definition to `libs` in CMake here 👇🏼 
 https://github.com/falcosecurity/falco/blob/7750b6f209fdef7b709e22ee4325797dd01949ba/cmake/modules/falcosecurity-libs.cmake#L46

Falco spreadly uses `MUSL_OPTIMIZED_BUILD` as a code definition to exclude certain features, such as here 👇🏼 https://github.com/falcosecurity/falco/blob/7750b6f209fdef7b709e22ee4325797dd01949ba/userspace/falco/falco.cpp#L140
However, neither `MUSL_OPTIMIZED_BUILD` nor `MUSL_OPTIMIZED` is defined in Falco sources through CMake, which ends up not excluding any feature in musl builds.

**Comment by leogr** [comment]
> There seem to be an issue with the musl optimized build. The ambiguity is that the `MUSL_OPTIMIZED_BUILD` is the name of the CMake option that triggers the musl build, whereas `MUSL_OPTIMIZED` is the name of the definition expected by `libs`. Falco passes the definition to `libs` in CMake here 👇🏼
> 
> https://github.com/falcosecurity/falco/blob/7750b6f209fdef7b709e22ee4325797dd01949ba/cmake/modules/falcosecurity-libs.cmake#L46
> 
> Falco spreadly uses `MUSL_OPTIMIZED_BUILD` as a code definition to exclude certain features, such as here 👇🏼
> 
> https://github.com/falcosecurity/falco/blob/7750b6f209fdef7b709e22ee4325797dd01949ba/userspace/falco/falco.cpp#L140
> 
> 
> However, neither `MUSL_OPTIMIZED_BUILD` nor `MUSL_OPTIMIZED` is defined in Falco sources through CMake, which ends up not excluding any feature in musl builds.

https://github.com/falcosecurity/falco/pull/1871 is trying to fix the issue described above.

Moreover, while discovering the issue, we also realized that after https://github.com/falcosecurity/falco/pull/1853 got merged, the static build is not being published anymore. Since we believe it's still valuable we have decided to publish both the dynamic and the static flavor of the `bin` package (we will just use different file names), here the PR https://github.com/falcosecurity/falco/pull/1873 Thanks to @LucaGuerra for this last-minute effort :pray:

**Comment by leogr** [comment]
Another minor issue found:
Lua files are now embedded into the Falco executable, but we have noticed a leftover: the `--alternate-lua-dir` flag (that cannot work and is not useful anymore). Here the fix https://github.com/falcosecurity/falco/pull/1872 Thanks to @FedeDP

**Comment by Issif** [comment]
I tested the last `master` image. I was able to test monitoring of syscalls and audit logs. I also tested the integration with Falcosidekick and its outputs.
Everything worked as expected :+1: 

![image](https://user-images.githubusercontent.com/4520100/151185038-cb51418f-69ae-4f44-b2da-dedcf4cc4789.png)

![image](https://user-images.githubusercontent.com/4520100/151185063-d80d8467-08ec-447c-8335-6750abee874f.png)

**Comment by terylt** [comment]
I've been testing with the falco libs.  Compiled a version of the sfcollector with it.. and it's passing unit tests, and we are running it through our battery of tests.  Will update if I run into any issues.

**Comment by leogr** [comment]
quick update:
currently, [test-infra](https://prow.falco.org/) is building drivers for the new version and has no more capacity.
for this reason, some PRs already approved are pending (`tide` is temporarily not working).
The issue should be solved once the driver building completes.

**Comment by juris** [comment]
any chance for arm64 in this release?

**Comment by jasondellaluce** [comment]
Hey @juris , unfortunately arm64 support will not be shipped with this release. However I think this is one of the next goals for the near future.

**Comment by jasondellaluce** [comment]
Quick update. We seem to have spotted a bug related to the filterchek system related to these issues:
- https://github.com/falcosecurity/plugins/issues/56
- https://github.com/falcosecurity/plugins/issues/57
We ara investigating a fix and will hopefully open some PRs soon.

**Comment by jasondellaluce** [comment]
Updates: We have fixed all the code issues found in the past few days!

Now, there seems to be a CircleCI problem that causes the `publish/packages-deb-dev` job to fail 👉🏼 https://app.circleci.com/pipelines/github/falcosecurity/falco/2033/workflows/d553bc07-6f2d-4563-b511-9024ce79193c/jobs/18624
However, we didn't introduce any change in that part, so it's unclear why this happens. We are currently investigating.

**Comment by leogr** [comment]
CircleCI functionality restored. We also cleaned up the deprecated `centos::8` build.

All clear now.

We are ready to release once the changelog PR https://github.com/falcosecurity/falco/pull/1880 gets merged. :star_struck:

**Comment by jasondellaluce** [comment]
All the post-release work is finished! Thanks to everybody for the help! 🥳 🦅
