### ISSUE TITLE
Internal syscall drops on self-managed K8s cluster

### ISSUE THREAD

**Issue by sebltm** [falcosecurity/falco#1870]
Seeing lots of internal syscall drops (3,900 individual events over 24 hours). 
The cluster has 119 nodes, it's self managed (AWS) running on Ubuntu with Kubernetes v1.21.5 deployed using kubespray, running Falco 0.30.0 deployed through Helm.
This is one of our integration clusters, but is reproducible across multiple different clusters, cloud service providers, Kubernetes versions.

![image](https://user-images.githubusercontent.com/26392528/151141815-6d9badc0-b031-4a32-9283-83e064c57d82.png)

Falco is running without any additional args (all cri/Kubernetes-related options disabled) and with gRPC as the only output enabled (no stdout or anything else).

Interesting was that disabling ``--cri``, ``-k https://$(KUBERNETES_SERVICE_HOST)``, ``-K`` and ``-pk`` gave a huge performance improvement: before disabling the options, we'd have multiple hundreds of thousands of ``internal syscall drops`` in a 24 hour period; and running with a single rule in the ruleset would give the same result.

**Comment by sebltm** [comment]
Seems like with 0.31.0 there is less problems (although still present) regarding syscall drops, however we're still seeing 10x more CPU usage with the ``--cri`` and ``-k`` flags enabled compared to disabled

**Comment by leogr** [comment]
> Seems like with 0.31.0 there is less problems (although still present) regarding syscall drops, however we're still seeing 10x more CPU usage with the `--cri` and `-k` flags enabled compared to disabled

Happy to hear that 0.31.0 mitigates the syscall drops issue. More CPU usage with `--cri` and `-k` is normal. 
Have you tried to use `--k8s-node`? It should reduce the amount of memory/CPU used for K8s data enrichment.

**Comment by sebltm** [comment]
<img width="2082" alt="image" src="https://user-images.githubusercontent.com/26392528/156334740-e379eed4-c224-4fa6-beeb-6552ee224e1e.png">
Looking at the screenshot above, I'm not actually convinced that there's a big difference in the number of syscall drops (I switched to 0.31.0 on the 21st of February).
This is on a non-production cluster with lighter loads than what we have running in productions, and not a big cluster either (usually around 30-50 nodes)

**Comment by leogr** [comment]
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/26392528/156334740-e379eed4-c224-4fa6-beeb-6552ee224e1e.png">
> 
> Looking at the screenshot above, I'm not actually convinced that there's a big difference in the number of syscall drops (I switched to 0.31.0 on the 21st of February). This is on a non-production cluster with lighter loads than what we have running in productions, and not a big cluster either (usually around 30-50 nodes)

Thank you! Although it's not what I expected :smile_cat: , I appreciated your feedback :pray:
