### ISSUE TITLE
Failed to start daemonset in K8s pod

### ISSUE THREAD

**Issue by az3r0th** [falcosecurity/falco#1881]
**Describe the bug**

I have used minikube cluster and used helm chart to install `falco`. It was successfully deployed  but it was not running. I am pasting the log below for reference:
```
kubectl logs -l app=falco -f
* Trying to dkms install falco module with GCC /usr/bin/gcc-5
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
Consider compiling your own falco driver and loading it or getting in touch with the Falco community
* Running dkms build failed, couldn't find /var/lib/dkms/falco/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/build/make.log (with GCC /usr/bin/gcc-5)
Mon Jan 31 07:26:53 2022: Falco version 0.30.0 (driver version 3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4)
Mon Jan 31 07:26:53 2022: Falco initialized with configuration file /etc/falco/falco.yaml
Mon Jan 31 07:26:53 2022: Loading rules from file /etc/falco/falco_rules.yaml:
Mon Jan 31 07:26:53 2022: Loading rules from file /etc/falco/falco_rules.local.yaml:
Mon Jan 31 07:26:54 2022: Unable to load the driver.
Mon Jan 31 07:26:54 2022: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded.. Exiting.
sourav@Souravs-MacBook-Pro ~ % kubectl logs  app=falco -f
Error from server (NotFound): pods "app=falco" not found
sourav@Souravs-MacBook-Pro ~ % kubectl logs -l  app=falco
* Trying to dkms install falco module with GCC /usr/bin/gcc-5
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
Consider compiling your own falco driver and loading it or getting in touch with the Falco community
* Running dkms build failed, couldn't find /var/lib/dkms/falco/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/build/make.log (with GCC /usr/bin/gcc-5)
Mon Jan 31 07:26:53 2022: Falco version 0.30.0 (driver version 3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4)
Mon Jan 31 07:26:53 2022: Falco initialized with configuration file /etc/falco/falco.yaml
Mon Jan 31 07:26:53 2022: Loading rules from file /etc/falco/falco_rules.yaml:
Mon Jan 31 07:26:53 2022: Loading rules from file /etc/falco/falco_rules.local.yaml:
Mon Jan 31 07:26:54 2022: Unable to load the driver.
Mon Jan 31 07:26:54 2022: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded.. Exiting.

```

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version: Falco version 0.30.0 (driver version 3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4)
- System info:

- Cloud provider or hardware configuration:
- OS: Ubuntu 20.04.2 LTS

- Kernel: Linux minikube 5.10.76-linuxkit SMP Mon Nov 8 10:21:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Installation method: Kubernetes Minikube Guide

**Additional context**

**Comment by FedeDP** [comment]
Hi @az3r0th !
Problem is that Falco is not able to find and load proper kernel module for your kernel; indeed Falco is not releasing a kernel module for your kernel; the nearest one is the `5.10.75-79.358.amzn2.x86_64_1`.  
You can see it here: https://github.com/mmoyerfigma/test-infra/blob/f276ed0340fb3cb8371e9e490bb580a2400d59f5/driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.10.75-79.358.amzn2.x86_64_1.yaml.

Can you open a simple PR to add support for your kernel too? This is a commit that added support for `5.10.68-62.173`:  https://github.com/mmoyerfigma/test-infra/commit/b027794effb082d1a9eb03bb59986a256b407512
Thank you very much!
