### ISSUE TITLE
Changes to package Falco into Debian

### ISSUE THREAD

**Issue by taziden** [falcosecurity/falco#189]
Hello,

I'm working on packaging Falco in Debian (see [#842306](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=842306)). 

In CMakeLists.txt, there is the inclusion of directories from Sysdig :

> CMakeLists.txt:#add_subdirectory("${SYSDIG_DIR}/driver" "${PROJECT_BINARY_DIR}/driver")
> CMakeLists.txt:#add_subdirectory("${SYSDIG_DIR}/userspace/libscap" ${PROJECT_BINARY_DIR}/userspace/libscap")
> CMakeLists.txt:#add_subdirectory("${SYSDIG_DIR}/userspace/libsinsp" ${PROJECT_BINARY_DIR}/userspace/libsinsp")

It would make our life way easier if these files were actually part of Falco itself. I currently don't see any other way around.
Do you think it would be possible ?

Thanks,
Julien

**Comment by mstemm** [comment]
Hi, I don't think we want to have copies of the sysdig source files in the falco repository--both sets of files are changing fairly often and I don't want to have to continually copy them over from sysdig to falco to keep them up to date.

You're right though that it's tacky to pull sysdig source files while doing the falco build. Maybe it's better to change sysdig to have a -dev build variant that has the necessary files as static libraries. Then falco could be configured to depend on the -dev sysdig build. Would that be reasonable? If so, I could start making the necessary changes for that.

**Comment by taziden** [comment]
Hi, I renamed the issue. I spoke with Sysdig maintainers and they think it totally makes sense to change sysdig to have a -dev build variant as you suggested.
Let's go!

**Comment by taziden** [comment]
Any news on this one ?

**Comment by mstemm** [comment]
Hi, unfortunately no update yet. We might also be able to use git submodules to avoid having to do a separate git pull outside the repository, which would be a bit quicker to implement than changing sysdig to export a -dev variant with static libraries.

Let me investigate the submodule thing to see if it will work.
