### ISSUE TITLE
Extra fields added via `falco -p` are tripled in log output

### ISSUE THREAD

**Issue by ubaniabalogun** [falcosecurity/falco#1890]
**Describe the bug**

When using `falco -p "<extra_fields>"` to format Falco's log output ([as described in this doc](https://falco.org/docs/alerts/formatting/)), The <extra_fields>'s are appended to the log output 3 times.

**How to reproduce it**

**Example 1**
```
falco -p "Hello"
touch /etc/test
```

Buggy Log output
```
20:40:31.998247564: Error File below /etc opened for writing <elided output....> Hello Hello Hello
```

**Example 2**
```
falco -p "%proc.cwd %evt.res"
touch /etc/test
```

Buggy Log result
```
20:43:22.667345603: Error File below /etc opened for writing <elided output..> /usr/bin/ SUCCESS /usr/bin/ SUCCESS /usr/bin/ SUCCESS
```

**Expected behaviour**
Extra fields should only be appended once 

```
falco -p "Hello"
touch /etc/test
```

Expected Log output
```
20:40:31.998247564: Error File below /etc opened for writing <elided output....> Hello
```

**Example 2**
```
falco -p "%proc.cwd %evt.res"
touch /etc/test
```

Expected Log result
```
20:43:22.667345603: Error File below /etc opened for writing <elided output..> /usr/bin/ SUCCESS
```

**Environment**

- Falco version: 0.31.0

- System info:
{
  "machine": "x86_64",
  "nodename": "ip-172-31-1-53.us-west-2.compute.internal",
  "release": "5.10.93-87.444.amzn2.x86_64",
  "sysname": "Linux",
  "version": "`#1 SMP Thu Jan 20 22:50:50 UTC 2022`"
}
- Cloud provider or hardware configuration: AWS EC2
- OS:
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="`cpe:2.3:o:amazon:amazon_linux:2`"
HOME_URL="https://amazonlinux.com/"
- Kernel:
`Linux ip-172-31-1-53.us-west-2.compute.internal 5.10.93-87.444.amzn2.x86_64 #1 SMP Thu Jan 20 22:50:50 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Installation method:
[Centos/RHEL/Amazon Linux](https://falco.org/docs/getting-started/installation/#centos-rhel)

**Additional context**
The real problem I'm trying to address that lead me to this error is this: I need to enforce a consistent set of metadata for each log line. I was hoping to do this via configuration file but was told -p is the only supported way right now. See [Kubernetes Slack Thread here](https://kubernetes.slack.com/archives/CMWH3EH32/p1644006568379079)

**Comment by ubaniabalogun** [comment]
Hey, any update on this? I'm currently exploring using Falco at my company and we're very interested in a fix for this. Thanks,

**Comment by jasondellaluce** [comment]
Hi @ubaniabalogun, I can't be totally sure, but this seems to be a duplicate of https://github.com/falcosecurity/falco/issues/1785. By doing some testing, I think your issue should be fixed with https://github.com/falcosecurity/falco/pull/1966.
