### ISSUE TITLE
Falco Driver Loader - 5.4.0-1068-azure #71~18.04.1-Ubuntu 

### ISSUE THREAD

**Issue by PeterThomasAwen** [falcosecurity/falco#1892]
Hi Team, 

My Falco pods are running as a Deamon set in k8s.
Initially it runs as expected it ran for around 14 Days.  
(It ran as expected and provided alerts into slack)

I see all falco deamon set pods are now crashing with CrashBackLoopOff

When checking the logs i see that it fails to find a prebuild falco module: 
https://download.falco.org/driver/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/falco_ubuntu-generic_5.4.0-1068-azure_71.ko
(which results in a 404)

From what I can see it then attempts to build one from a dkms make file this also fails with 
make[2]: *** [scripts/Makefile.build:270: /var/lib/dkms/falco/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/build/main.o] Error 1                                                                          
make[1]: *** [Makefile:1762: /var/lib/dkms/falco/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/build] Error 2                                                                                              
 make[1]: Leaving directory '/host/usr/src/linux-headers-5.4.0-1068-azure'                                                                                                                             
 make: *** [Makefile:16: all] Error 2                                                                                                                                                                  
 * Trying to dkms install falco module with GCC /usr/bin/gcc-8                                                                                                                                         
 DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"      
 
When running the  https://raw.githubusercontent.com/falcosecurity/falco/master/scripts/falco-driver-loader
 I got the following response 
 
 Consider compiling your own @DRIVER_NAME@ driver and loading it or getting in touch with the Falco community.
 
So I'm getting in touch with the Falco community

Falco Chart version: 1.16.4 

Command : 
helm install falco falcosecurity/falco --namespace falco --version 1.16.4  -f file.yaml 

File.yaml
`
metadata:
  namespace: falco 
   
jsonOutput: true
jsonIncludeOutputProperty: true
httpOutput:
  enabled: true
  url: "http://falcosidekick:2801/"

resources:
   requests:
     cpu: 50m
     memory: 256Mi
   limits:
     cpu: 50m
     memory: 300Mi

falcosidekick:
  config:
    slack:
      webhookurl: https://hooks.slack.com/services/
      messageformat: "Alert : Dev UK - rule **{{ .Rule }}** triggered by user **{{ index .OutputFields \"user.name\"}}**"
      minimumpriority: critical
  enabled: true
`
k8s version: 1.21.2

Enviroment:  Azure

uname -rv
5.4.0-1068-azure falcosecurity/community#71~18.04.1-Ubuntu

Can you advise me why this is happening make a drive module available for this release or a way to get around the issue I'm facing?

**Comment by leogr** [comment]
> When running the https://raw.githubusercontent.com/falcosecurity/falco/master/scripts/falco-driver-loader I got the following response

That :point_up: is the script's source code, `@DRIVER_NAME@` and other stuff are replaced at build time. You cannot just download the source code and run it.

The compiled script is already present in the docker image. But usually, you don't need to run it manually.

From what I can see from your logs, you probably need to install the kernel headers on your host (and maybe also to reboot it).
See https://github.com/falcosecurity/charts/tree/master/falco#about-the-driver

**Comment by PeterThomasAwen** [comment]
Hi @leogr, 

Thanks for your response. 
I thought that might be the case, I'm not getting much time to run the script as my kubernetes container restarts as it sees the service not running and reboots the container. 
I did manage to run through the process on one of my host nodes in order to install the kernel headers but again its failing to find the headers as my containers response to uname -r is "5.4.0-1068-azure" so that never going to happen.

I managed to install the keys and then do an apt search im unable to find any thing for "linux-head"
```
root@aks-nodepool1-19900504-vmss0000A0:/# apt search linux-head
Sorting... Done
Full Text Search... Done
```
I confirm on a normal ubuntu system i can see those but not from my k8s node. 
As such I would like to be able to set the download a set of matching headers hence trying to use the 
Yaml flags 
ebpf:
  enabled: true
  path: https://download.falco.org/driver/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/falco_ubuntu-generic_5.4.0-86-generic_97.o
however in the logs i can see its not using that path value.

**Comment by leogr** [comment]
Hey @PeterThomasAwen 

Have you tried :point_down: ?
```
apt-get update -y
apt-get -y install linux-headers-$(uname -r)
```

**Comment by leogr** [comment]
Hey @PeterThomasAwen 

If I understood correctly, you're are trying to install the kernel headers from within the container?
Unfortunately, it cannot work that way.

Kernel headers must be installed directly into the underlying host machine, so you need shell access to the OS of the host directly (I assumed you could, perhaps my assumption was wrong?).

If you don't have shell access to the underlying host, likely the easiest solution is to add the configuration of the driver you need to our infra :point_down: 
You can do that by opening a PR, and we will be happy to accept it :) 
Then, the prebuilt for your configuration will be available for download as a prebuilt driver, and `falco-driver-loader` will download it automatically (and you will not need to install the kernel header on your system).
Is that a viable solution for you?

Let me know!

**Comment by PeterThomasAwen** [comment]
Hey @leogr, 

I was able to use the Kernel module. 
Turned out that when it was building the kernel originally it was exceeding the limit I had set on the CPU.
Hence the pods being taken out when starting up. 
For some reason it didn't seem to happen on their initial start up :S.

If I get some time tomorrow ill send in that PR for you as a thanks anyway.

**Comment by PeterThomasAwen** [comment]
@leogr, 

I've submitted that PR. 
https://github.com/falcosecurity/test-infra/pull/624

**Comment by rubenpetrosyan1** [comment]
hi @PeterThomasAwen 
Thanks for the investigation. Currently, I have the same issue with the Falco helm chart.
Can you please share the limits which worked for you?

**Comment by leogr** [comment]
I guess the original issue has been fixed (@PeterThomasAwen correct me if I'm wrong). So
/close

Regarding the resource limits, I'd be interested in having more feedback. If needed, I'm open to increasing the default values in the chart :point_down: 
https://github.com/falcosecurity/charts/blob/master/falco/values.yaml#L39

Would you like to open a new issue in https://github.com/falcosecurity/charts ?

Thank you
