### ISSUE TITLE
Can't Install Falco in FIPS Enabled Environment

### ISSUE THREAD

**Issue by ccravens** [falcosecurity/falco#1894]
When trying to install Falco using the steps outlined here: https://falco.org/docs/getting-started/installation/#centos-rhel

I get an error about the use of MD5 (not a FIPS compliant algorithm)

Enable FIPS mode on a CentOS 8 / RHEL 8 environment and follow the installation instructions outlined in the link above.

Expectation is that Falco installs on FIPS-enabled environments and that FIPS-compliant algorithms (ie - SHA256) are used to sign and verify Falco installation packages.

- Falco version: `0.29.1-1`

- System info: `CentOS 8 Stream Minimal Install`

- Cloud provider or hardware configuration: AWS EC2
- OS: `CentOS 8 Stream`

- Kernel: `4.18.0-358.el8.x86_64`

- Installation method: `RPM on Host Machines`

**Comment by andreabonanno** [comment]
Hi and thanks for this input.

I assumed that yum parameters such as ` -ivh --nodigest --nofiledigest` are not suitable for your use case, 
so I recreated your setup and indeed SHA256 signing is required for the rpm to be FIPS-compliant and accepted by yum.

SHA256 signing can actually be peformed via `rpmsign` and the usage of specific macros, which unfortunately are not well documented.

These macros adds the SHA256 digest,

`%_source_filedigest_algorithm 8`
`%_binary_filedigest_algorithm 8`

while the following specifies the SHA256 signature method:

`%__gpg_sign_cmd %{__gpg} gpg --force-v3-sigs --batch \`
`--verbose --no-armor --passphrase-fd 3 --no-secmem-warning \`
`-u "%{_gpg_name}" -sbo %{__signature_filename} \`
`--digest-algo sha256 %{__plaintext_filename}'`

Unfortunately the current signing process for Falco packages uses `RPM version 4.11.3`, which **ignores** the macros above.

One possible solution could be to update the `rpm/sign` job, using a different rpm version which is able to sign via SHA256.
