### ISSUE TITLE
Installation painpoints

### ISSUE THREAD

**Issue by nsmith5** [falcosecurity/falco#1895]
**What to document**

Installing Falco on my Fedora laptop I hit a couple pain points in the docs that took a little while to work around:

- DKMS modules will not load on a system with secure boot enabled
- `clang` is a dependency to build the eBPF driver
- The systemd unit needs to be modified to add the `FALCO_BPF_PROBE=""` env var if using the BPF driver

These are just little pain points, but together they made that initial Falco experience just trickier than necessary.

**Comment by jasondellaluce** [comment]
Hey @nsmith5, that's great feedback. Would you consider opening a PR in https://github.com/falcosecurity/falco-website/ to suggest some changes in the doc? This is the official codebase of the website and the doc, and it would be a great addition if you had some corrections.
