### ISSUE TITLE
Create env variable to add options when loading the driver 

### ISSUE THREAD

**Issue by mathildeHermet** [falcosecurity/falco#1896]
**Motivation**

I have a usecase of Falco where I have a workflow that compiles Falco kernel module and upload it in Artifactory. 
When I download it, I have to pass credentials in the header of the request so I need to add options in the curl command in the falco-driver-loader script.

**Feature**

I would like an environment variable to pass options to the curl command that download Falco kernel module

**Alternatives**

Add an environment variable like FALCO_DRIVER_CURL_CUSTOM_OPTIONS because FALCO_DRIVER_CURL_OPTIONS already exists

**Additional context**

**Comment by andreabonanno** [comment]
Thanks for the idea!
I provided a possible solution enabling curl option override.
