### ISSUE TITLE
Handle tmux: client/tmux: server as acceptable shell spawning programs

### ISSUE THREAD

**Issue by mstemm** [falcosecurity/falco#191]
Handle tmux: client/tmux: server as acceptable shell spawning programs.

This is somewhat blocked on https://github.com/draios/sysdig/issues/718, although if necessary it could be handled by a substring match on proc.pname.

**Comment by juju4** [comment]
same issue for screen? doesn't seem so

**Comment by mstemm** [comment]
Shouldn't be, unless screen changes its argv to something that adds spaces.
