### ISSUE TITLE
Memory usage doubled after 1.16.3 -> 1.17.2 upgrade

### ISSUE THREAD

**Issue by mac-chaffee** [falcosecurity/falco#1922]
**Describe the bug**

After upgrading Falco from 1.16.3 to 1.17.2, I noticed that RAM usage for the falco daemonset roughly doubled from ~100MB to ~200MB per pod. I'm mainly filing this bug report to document this since it's not a serious bug unless you have custom RAM limits set, and the pods start killing oomkilled.

If there was some new dependency added in 1.17 that might be eating extra RAM, that might explain it. Just want to make sure I haven't misconfigured falco in some way that makes it use up more RAM.

**How to reproduce it**

Upgrade from 1.16.3 to 1.17.2

**Expected behaviour**

Consistent RAM usage between versions.

**Screenshots**

Top graph is pre-upgrade, bottom graph is post-upgrade.
<img width="1736" alt="image" src="https://user-images.githubusercontent.com/7581860/156425379-a48a0dc1-638c-40d9-b520-c49543e18f8a.png">

**Environment**

- Falco version: 1.17.2
- System info:
```
{
  "machine": "x86_64",
  "nodename": "monitoring-falco-td4qg",
  "release": "4.18.0-348.12.2.el8_5.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP Mon Jan 17 07:06:06 EST 2022"
}
```
- Cloud provider or hardware configuration: Bare-metal, v1.21
- OS: RHEL 8.5
- Kernel: `Linux k8s-node01 4.18.0-348.12.2.el8_5.x86_64 #1 SMP Mon Jan 17 07:06:06 EST 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Installation method: Kubernetes was installed with kubespray. Falco was installed with Helm.

**Additional context**

This cluster is medium-sized: 18 nodes, 500 pods. That might affect things.

**Comment by leogr** [comment]
@mac-chaffee 

Are you referring to the Falco Helm Chart version? https://github.com/falcosecurity/charts/releases

**Comment by mac-chaffee** [comment]
Oh yes, looks like I've mixed up the versions of the helm chart and falco itself.

**Comment by PhilipSchmid** [comment]
We just tested the upgrade from `0.30.0` (Helm chart `1.16.3`) to `0.31.1` (Helm chart `1.17.4`) and run into the same issue - except in our case the Falco DS pods now use more then 10x the memory 😅. From about 150 - 160 MiB to about 2.1 GiB.

Tested on K8s version `v1.22.2` (VMware TKGI).

Regards,
Philip

**Comment by jasondellaluce** [comment]
Hey @mac-chaffee and @PhilipSchmid, the changes of https://github.com/falcosecurity/falco/pull/1965 should fix this! Thanks for reporting 🙏🏼

**Comment by mac-chaffee** [comment]
I'm currently running off the master branch and seeing RAM usage of about 100-180MB depending on the node. So that seems in-line with what I was seeing before that 1.17 upgrade (adjusting for the fact that my cluster is busier than it was then). Thanks!

**Comment by Issif** [comment]
@PhilipSchmid If you can share with us screenshots "before" and "after", it will be amazing, :pray: thanks

**Comment by PhilipSchmid** [comment]
@Issif I'll provide you both outputs as soon as I'm able to fix the syscall detection in version 0.32.0. At the moment I have the issue that no of the syscall rule triggers anymore... Perhaps that's also the reason why it consumes less memory 😅.

**Comment by jasondellaluce** [comment]
@PhilipSchmid please open an issue for this once you find out more. We're also available if you need help with troubleshooting.

**Comment by PhilipSchmid** [comment]
@jasondellaluce Please forget about what I mentioned regarding `no of the syscall rule triggers anymore`. As @leogr just confirmed [in Slack](https://kubernetes.slack.com/archives/CMWH3EH32/p1655209558876649) and stated in the [Falco Helm chart changelog](https://github.com/falcosecurity/charts/blob/master/falco/CHANGELOG.md?plain=1#L26), it's intentional that the syscall source is deactivated as soon as the audit plugin is enabled (which we have). In theory, we would need to have both enabled like it was possible in the past.

So for that reason, I won't be able to provide you an accurate memory resource usage comparison, until a new Falco Helm chart gets released with the support for having both sources enabled at the same time (other ways we wouldn't have a fair comparison).
