### ISSUE TITLE
Cut Falco 0.31.1

### ISSUE THREAD

**Issue by LucaGuerra** [falcosecurity/falco#1924]
## Type

This is a **patch** release.

## Date

We can make the release happen as the features are merged, verified, and the steps below are completed. Targeting the week starting from 07-03-2022.

## Release Steps

Read the [release process](https://github.com/falcosecurity/falco/blob/master/RELEASE.md) for a detailed explanation.

## Release Blocking PRs

- [x] Ensure the driver version has been bumped to `b7eb0dd65226a8dc254d228c8d950d07bf3521d2`. https://github.com/falcosecurity/falco/pull/1923
- [x] https://github.com/falcosecurity/falco/pull/1926

## Action Items

- [x] **Pre-Release**
    - [x] Prebuilt drivers publish https://github.com/falcosecurity/test-infra/pull/647 -> https://github.com/falcosecurity/test-infra/commit/39847b89f0a9d72f470a11d3457c3438e3973ba4
    - [x] Update milestones for [closed issues](https://github.com/falcosecurity/falco/pulls?q=is%3Apr+is%3Amerged+closed%3A%3E2022-01-31) to 0.31.1
    - [x] Changelog https://github.com/falcosecurity/falco/pull/1929
- [x] **Release**
    - [x] Tag
    - [x] GitHub Release
- [x] **Website**
    - [x] Bump Falco version to 0.31.1 https://github.com/falcosecurity/falco-website/pull/565
- [x] **Post-Rlease**
    - [x] Helm Charts https://github.com/falcosecurity/charts/pull/315
 
/assign @LucaGuerra 
/kind documentation

**Comment by LucaGuerra** [comment]
I have done some quick local testing and kubernetes testing with the following configurations:
* vanilla kops, kubernetes 1.21.9, kmod install
* GKE with COS, k8s 1.21.6, eBPF install

**Comment by loresuso** [comment]
I have done some testing by:

- installing Falco RPM package on Amazon Linux, kernel 4.14.198-152.320.amzn2.x86_64, both eBPF and kmod
- running Falco locally with Docker 

Everything seems to be ok

**Comment by Andreagit97** [comment]
I have done some local testing by:

* checking bpf probe and kernel module behaviors on different architectures:
	- Image = amazonlinux-2
	  Kernel = 4.14.198-152.320.amzn2.x86_64
	  clang = clang version 11.1.0

	- Image = debian10
	  Kernel = 4.19.0-18-amd64
	  clang = clang version 7.0.1-8+deb10u2

	- Image = fedora33
	  Kernel = 5.14.18-100.fc33.x86_64
	  clang = clang version 11.0.0 (Fedora 11.0.0-3.fc33)  

	- Image = ubuntu-18.04
	  Kernel = 5.11.0-051100-generic
	  clang = clang version 14.0.0  

* checking Falco installation with `bin` and `bin-static`

* installing Falco `deb` on Ubuntu 21.04, kernel 5.14.0-051400-generic

* installing Falco `rpm` on Fedora33, kernel 5.14.18-100.

* testing new added/modified syscalls `clone3`,`execveat`,`open`,`openat`,`openat2`,`creat`,`connect`

**Comment by LucaGuerra** [comment]
Thanks a lot @loresuso @Andreagit97 🙇

**Comment by leogr** [comment]
https://github.com/falcosecurity/test-infra/pull/647 approved! :sunglasses: 

Still waiting for the CI.

**Comment by leogr** [comment]
Hey @LucaGuerra 

I've opened https://github.com/falcosecurity/charts/pull/315 to upgrade Falco in the Helm Chart.

**Comment by LucaGuerra** [comment]
Released! 🎉
