### ISSUE TITLE
To add dynamic rule management and compilation

### ISSUE THREAD

**Issue by 7bytes** [falcosecurity/falco#1931]
**Motivation**
I want to add dynamic rule management and compilation to falco, can I do this?

**Feature**

**Alternatives**

**Additional context**

**Comment by 7bytes** [comment]
> Hi @7bytes! Would you be more specific on the kind of changes you want to apply? In any case, you are totally free to open a PR so that then we can have a discussion there!

Hi @jasondellaluce , Thank you for reply this issue. I found that the falco rule_engine part is currently managed based on static configuration (i.e. rules_local.yaml) files and compiled through lua.  So, my basic idea is to add dynamic management and compilation functions to it, such as through restful api.

**Comment by jasondellaluce** [comment]
That's a great point. FYI there is an undergoing effort to try making rule hot-reloading and management feasible through the Falco gRPC interface 👉🏼 https://github.com/falcosecurity/falco/pull/1849
I personally think that reusing the gRPC interface is the way to go here. We'd love to hear more suggestions and ideas from you on that matter.
