### ISSUE TITLE
Falco installation on Digital Ocean Kubernetes

### ISSUE THREAD

**Issue by ajinkya1986** [falcosecurity/falco#1934]
While installing falco on Digital Ocean managed kubernetes. I am getting the following error
`Runtime error: can't open BPF probe '/root/.falco/falco-bpf.o': Errno 2. Exiting.`
I know this is caused because the ebpf probe was not installed on the cluster nodes.

But when I try installing without the ebpf probe I get the following error
`Unable to load the driver.
Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded.. Exiting.`

We have to manually install falco and the drivers by sshing into the nodes. After that also we can install only without the ebpf probe, using the kernel module. Has anyone faced with the same issue? Is there any solution to this without doing ssh into the nodes?

- Falco version: latest
- System info: Worker node Debian 10 Linux kernel 5.10.0

- Cloud provider or hardware configuration: 3 vCPU, 6GB Memory, 150 GB Disk
- OS: Debian 10
- Kernel: Linux 5.10.0
- Installation method: from source

**Comment by lucasmellos** [comment]
I've @leogr figure-out what happened to DOKS. It was the lack o support for bpo based kernel. I made a PR that was approved by @maxgio92 which fixes the issue. DOKS is now supported

**Comment by maxgio92** [comment]
Again, thank you @lucasmellos!

**Comment by ajinkya1986** [comment]
Thank you @lucasmellos the issue is now resolved. It can be closed.

**Comment by ajinkya1986** [comment]
Kernel version 6.1.0-10-amd64

**Comment by FedeDP** [comment]
Can you open a new issue?

**Comment by ajinkya1986** [comment]
ok
