### ISSUE TITLE
Runtime error: Argument ‘-DAnonymous Request Allowed’ starts with a - but has incorrect syntax. Exiting.

### ISSUE THREAD

**Issue by developer-guy** [falcosecurity/falco#1942]
**Describe the bug**

I got an error while disabling the rule "Anonymous Request Allowed" via the `-D` flag. It has been working for a while unless we upgrade Falco to v0.31.1.

**How to reproduce it**

Upgrade Falco to v0.31.1 and edit the args of your container by adding "- -DAnonymous Request Allowed" into it.

**Expected behaviour**

It should disable the rule we defined

**Screenshots**

**Environment**

- Falco version: 0.31.1

- System info: 

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by jasondellaluce** [comment]
Hey @developer-guy, out of curiosity, does this happen on Falco 0.31.0 too?

**Comment by jasondellaluce** [comment]
@developer-guy, did you try leaving a space after `-D`? And also, can you report the error message you're getting? My gut feeling is that this derives from the new library we use to implement the CLI (https://github.com/jarro2783/cxxopts). Hope to hear more from you so that we can figure out how to solve this.

**Comment by leogr** [comment]
Unfortunately, `-DAnonymous Request Allowed` is not completely safe to interpret, and the CLI refactor silently fixed that case.
I'd say the previous behavior was buggy, not the current one.

The syntax proposed by @pmusa is correct IMHO.

I believe this is mostly a documentation issue. @developer-guy wdyt?

**Comment by jasondellaluce** [comment]
I endorse Leo's comment. What do you all think, should we close this?
