### ISSUE TITLE
kubectl install failed, falco can't work。

### ISSUE THREAD

**Issue by smarttang** [falcosecurity/falco#1946]
**Which jobs are failing**:
我在部署到k8s的时候发现有异常，这个异常导致没有办法采集到信息，我部署的是最新的yaml文件，主要用kubectl 来进行操作的。

**Which test(s) are failing**:
'''
./include/asm-generic/bug.h:91:19: note: in expansion of macro '__WARN_FLAGS'
 #define __WARN()  __WARN_FLAGS(BUGFLAG_TAINT(TAINT_WARN))
                   ^
./include/asm-generic/bug.h:116:3: note: in expansion of macro '__WARN'
   __WARN();      \
   ^
./include/net/sock.h:695:3: note: in expansion of macro 'WARN_ON'
   WARN_ON(refcount_read(&sk->sk_refcnt) == 1);
   ^
In file included from ./include/linux/bug.h:5:0,
                 from ./include/linux/jump_label.h:250,
                 from ./include/linux/static_key.h:1,
                 from ./arch/x86/include/asm/nospec-branch.h:6,
                 from ./arch/x86/include/asm/irqflags.h:9,
                 from ./include/linux/irqflags.h:16,
                 from ./include/linux/rcupdate.h:26,
                 from ./include/linux/rculist.h:11,
                 from ./include/linux/pid.h:5,
                 from ./include/linux/sched.h:14,
                 from ./arch/x86/include/asm/syscall.h:14,
                 from /var/lib/dkms/falco/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/build/main.c:19:
./arch/x86/include/asm/bug.h:36:22: error: expected identifier or '(' before string constant
  asm_inline volatile("1:\t" ins "\n"    \
                      ^
./arch/x86/include/asm/bug.h:80:2: note: in expansion of macro '_BUG_FLAGS'
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:91:19: note: in expansion of macro '__WARN_FLAGS'
 #define __WARN()  __WARN_FLAGS(BUGFLAG_TAINT(TAINT_WARN))
                   ^
./include/asm-generic/bug.h:116:3: note: in expansion of macro '__WARN'
   __WARN();      \
   ^
./include/net/sock.h:695:3: note: in expansion of macro 'WARN_ON'
   WARN_ON(refcount_read(&sk->sk_refcnt) == 1);
   ^
In file included from <command-line>:0:0:
././include/linux/compiler_types.h:218:24: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 #define asm_inline asm __inline
                        ^
./arch/x86/include/asm/bug.h:36:2: note: in expansion of macro 'asm_inline'
  asm_inline volatile("1:\t" ins "\n"    \
  ^
./arch/x86/include/asm/bug.h:80:2: note: in expansion of macro '_BUG_FLAGS'
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:91:19: note: in expansion of macro '__WARN_FLAGS'
 #define __WARN()  __WARN_FLAGS(BUGFLAG_TAINT(TAINT_WARN))
                   ^
./include/asm-generic/bug.h:116:3: note: in expansion of macro '__WARN'
   __WARN();      \
   ^
./include/net/sock.h:695:3: note: in expansion of macro 'WARN_ON'
   WARN_ON(refcount_read(&sk->sk_refcnt) == 1);
   ^
./include/net/sock.h: In function 'sk_tx_queue_set':
././include/linux/compiler_types.h:218:24: error: expected '(' before '__inline'
 #define asm_inline asm __inline
                        ^
./arch/x86/include/asm/bug.h:36:2: note: in expansion of macro 'asm_inline'
  asm_inline volatile("1:\t" ins "\n"    \
  ^
./arch/x86/include/asm/bug.h:80:2: note: in expansion of macro '_BUG_FLAGS'
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:99:3: note: in expansion of macro '__WARN_FLAGS'
   __WARN_FLAGS(BUGFLAG_ONCE |   \
   ^
./include/net/sock.h:1769:6: note: in expansion of macro 'WARN_ON_ONCE'
  if (WARN_ON_ONCE((unsigned short)tx_queue >= USHRT_MAX))
      ^
In file included from ./include/linux/bug.h:5:0,
                 from ./include/linux/jump_label.h:250,
                 from ./include/linux/static_key.h:1,
                 from ./arch/x86/include/asm/nospec-branch.h:6,
                 from ./arch/x86/include/asm/irqflags.h:9,
                 from ./include/linux/irqflags.h:16,
                 from ./include/linux/rcupdate.h:26,
                 from ./include/linux/rculist.h:11,
                 from ./include/linux/pid.h:5,
                 from ./include/linux/sched.h:14,
                 from ./arch/x86/include/asm/syscall.h:14,
                 from /var/lib/dkms/falco/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/build/main.c:19:
./arch/x86/include/asm/bug.h:36:22: error: expected identifier or '(' before string constant
  asm_inline volatile("1:\t" ins "\n"    \
                      ^
./arch/x86/include/asm/bug.h:80:2: note: in expansion of macro '_BUG_FLAGS'
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:99:3: note: in expansion of macro '__WARN_FLAGS'
   __WARN_FLAGS(BUGFLAG_ONCE |   \
   ^
./include/net/sock.h:1769:6: note: in expansion of macro 'WARN_ON_ONCE'
  if (WARN_ON_ONCE((unsigned short)tx_queue >= USHRT_MAX))
      ^
In file included from <command-line>:0:0:
././include/linux/compiler_types.h:218:24: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 #define asm_inline asm __inline
                        ^
./arch/x86/include/asm/bug.h:36:2: note: in expansion of macro 'asm_inline'
  asm_inline volatile("1:\t" ins "\n"    \
  ^
./arch/x86/include/asm/bug.h:80:2: note: in expansion of macro '_BUG_FLAGS'
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:99:3: note: in expansion of macro '__WARN_FLAGS'
   __WARN_FLAGS(BUGFLAG_ONCE |   \
   ^
./include/net/sock.h:1769:6: note: in expansion of macro 'WARN_ON_ONCE'
  if (WARN_ON_ONCE((unsigned short)tx_queue >= USHRT_MAX))
      ^
./include/net/sock.h: In function 'sk_rx_queue_set':
././include/linux/compiler_types.h:218:24: error: expected '(' before '__inline'
 #define asm_inline asm __inline
                        ^
./arch/x86/include/asm/bug.h:36:2: note: in expansion of macro 'asm_inline'
  asm_inline volatile("1:\t" ins "\n"    \
  ^
./arch/x86/include/asm/bug.h:80:2: note: in expansion of macro '_BUG_FLAGS'
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:99:3: note: in expansion of macro '__WARN_FLAGS'
   __WARN_FLAGS(BUGFLAG_ONCE |   \
   ^
./include/net/sock.h:1795:7: note: in expansion of macro 'WARN_ON_ONCE'
   if (WARN_ON_ONCE(rx_queue == NO_QUEUE_MAPPING))
       ^
In file included from ./include/linux/bug.h:5:0,
                 from ./include/linux/jump_label.h:250,
                 from ./include/linux/static_key.h:1,
                 from ./arch/x86/include/asm/nospec-branch.h:6,
                 from ./arch/x86/include/asm/irqflags.h:9,
                 from ./include/linux/irqflags.h:16,
                 from ./include/linux/rcupdate.h:26,
                 from ./include/linux/rculist.h:11,
                 from ./include/linux/pid.h:5,
                 from ./include/linux/sched.h:14,
                 from ./arch/x86/include/asm/syscall.h:14,
                 from /var/lib/dkms/falco/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/build/main.c:19:
./arch/x86/include/asm/bug.h:36:22: error: expected identifier or '(' before string constant
  asm_inline volatile("1:\t" ins "\n"    \
                      ^
./arch/x86/include/asm/bug.h:80:2: note: in expansion of macro '_BUG_FLAGS'
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:99:3: note: in expansion of macro '__WARN_FLAGS'
   __WARN_FLAGS(BUGFLAG_ONCE |   \
   ^
./include/net/sock.h:1795:7: note: in expansion of macro 'WARN_ON_ONCE'
   if (WARN_ON_ONCE(rx_queue == NO_QUEUE_MAPPING))
       ^
In file included from <command-line>:0:0:
././include/linux/compiler_types.h:218:24: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 #define asm_inline asm __inline
                        ^
./arch/x86/include/asm/bug.h:36:2: note: in expansion of macro 'asm_inline'
  asm_inline volatile("1:\t" ins "\n"    \
  ^
./arch/x86/include/asm/bug.h:80:2: note: in expansion of macro '_BUG_FLAGS'
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:99:3: note: in expansion of macro '__WARN_FLAGS'
   __WARN_FLAGS(BUGFLAG_ONCE |   \
   ^
./include/net/sock.h:1795:7: note: in expansion of macro 'WARN_ON_ONCE'
   if (WARN_ON_ONCE(rx_queue == NO_QUEUE_MAPPING))
       ^
./include/net/sock.h: In function 'sock_graft':
././include/linux/compiler_types.h:218:24: error: expected '(' before '__inline'
 #define asm_inline asm __inline
                        ^
./arch/x86/include/asm/bug.h:36:2: note: in expansion of macro 'asm_inline'
  asm_inline volatile("1:\t" ins "\n"    \
  ^
./arch/x86/include/asm/bug.h:80:2: note: in expansion of macro '_BUG_FLAGS'
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:91:19: note: in expansion of macro '__WARN_FLAGS'
 #define __WARN()  __WARN_FLAGS(BUGFLAG_TAINT(TAINT_WARN))
                   ^
./include/asm-generic/bug.h:116:3: note: in expansion of macro '__WARN'
   __WARN();      \
   ^
./include/net/sock.h:1848:2: note: in expansion of macro 'WARN_ON'
  WARN_ON(parent->sk);
  ^
In file included from ./include/linux/bug.h:5:0,
                 from ./include/linux/jump_label.h:250,
                 from ./include/linux/static_key.h:1,
                 from ./arch/x86/include/asm/nospec-branch.h:6,
                 from ./arch/x86/include/asm/irqflags.h:9,
                 from ./include/linux/irqflags.h:16,
                 from ./include/linux/rcupdate.h:26,
                 from ./include/linux/rculist.h:11,
                 from ./include/linux/pid.h:5,
                 from ./include/linux/sched.h:14,
                 from ./arch/x86/include/asm/syscall.h:14,
                 from /var/lib/dkms/falco/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/build/main.c:19:
./arch/x86/include/asm/bug.h:36:22: error: expected identifier or '(' before string constant
  asm_inline volatile("1:\t" ins "\n"    \
                      ^
./arch/x86/include/asm/bug.h:80:2: note: in expansion of macro '_BUG_FLAGS'
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:91:19: note: in expansion of macro '__WARN_FLAGS'
 #define __WARN()  __WARN_FLAGS(BUGFLAG_TAINT(TAINT_WARN))
                   ^
./include/asm-generic/bug.h:116:3: note: in expansion of macro '__WARN'
   __WARN();      \
   ^
./include/net/sock.h:1848:2: note: in expansion of macro 'WARN_ON'
  WARN_ON(parent->sk);
  ^
In file included from <command-line>:0:0:
././include/linux/compiler_types.h:218:24: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 #define asm_inline asm __inline
                        ^
./arch/x86/include/asm/bug.h:36:2: note: in expansion of macro 'asm_inline'
  asm_inline volatile("1:\t" ins "\n"    \
  ^
./arch/x86/include/asm/bug.h:80:2: note: in expansion of macro '_BUG_FLAGS'
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:91:19: note: in expansion of macro '__WARN_FLAGS'
 #define __WARN()  __WARN_FLAGS(BUGFLAG_TAINT(TAINT_WARN))
                   ^
./include/asm-generic/bug.h:116:3: note: in expansion of macro '__WARN'
   __WARN();      \
   ^
./include/net/sock.h:1848:2: note: in expansion of macro 'WARN_ON'
  WARN_ON(parent->sk);
  ^
./include/net/request_sock.h: In function 'reqsk_free':
././include/linux/compiler_types.h:218:24: error: expected '(' before '__inline'
 #define asm_inline asm __inline
                        ^
./arch/x86/include/asm/bug.h:36:2: note: in expansion of macro 'asm_inline'
  asm_inline volatile("1:\t" ins "\n"    \
  ^
./arch/x86/include/asm/bug.h:80:2: note: in expansion of macro '_BUG_FLAGS'
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:99:3: note: in expansion of macro '__WARN_FLAGS'
   __WARN_FLAGS(BUGFLAG_ONCE |   \
   ^
./include/net/request_sock.h:120:2: note: in expansion of macro 'WARN_ON_ONCE'
  WARN_ON_ONCE(refcount_read(&req->rsk_refcnt) != 0);
  ^
In file included from ./include/linux/bug.h:5:0,
                 from ./include/linux/jump_label.h:250,
                 from ./include/linux/static_key.h:1,
                 from ./arch/x86/include/asm/nospec-branch.h:6,
                 from ./arch/x86/include/asm/irqflags.h:9,
                 from ./include/linux/irqflags.h:16,
                 from ./include/linux/rcupdate.h:26,
                 from ./include/linux/rculist.h:11,
                 from ./include/linux/pid.h:5,
                 from ./include/linux/sched.h:14,
                 from ./arch/x86/include/asm/syscall.h:14,
                 from /var/lib/dkms/falco/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/build/main.c:19:
./arch/x86/include/asm/bug.h:36:22: error: expected identifier or '(' before string constant
  asm_inline volatile("1:\t" ins "\n"    \
                      ^
./arch/x86/include/asm/bug.h:80:2: note: in expansion of macro '_BUG_FLAGS'
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:99:3: note: in expansion of macro '__WARN_FLAGS'
   __WARN_FLAGS(BUGFLAG_ONCE |   \
   ^
./include/net/request_sock.h:120:2: note: in expansion of macro 'WARN_ON_ONCE'
  WARN_ON_ONCE(refcount_read(&req->rsk_refcnt) != 0);
  ^
In file included from <command-line>:0:0:
././include/linux/compiler_types.h:218:24: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 #define asm_inline asm __inline
                        ^
./arch/x86/include/asm/bug.h:36:2: note: in expansion of macro 'asm_inline'
  asm_inline volatile("1:\t" ins "\n"    \
  ^
./arch/x86/include/asm/bug.h:80:2: note: in expansion of macro '_BUG_FLAGS'
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:99:3: note: in expansion of macro '__WARN_FLAGS'
   __WARN_FLAGS(BUGFLAG_ONCE |   \
   ^
./include/net/request_sock.h:120:2: note: in expansion of macro 'WARN_ON_ONCE'
  WARN_ON_ONCE(refcount_read(&req->rsk_refcnt) != 0);
  ^
make[2]: *** [scripts/Makefile.build:262: /var/lib/dkms/falco/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/build/main.o] Error 1
make[1]: *** [Makefile:1734: /var/lib/dkms/falco/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/build] Error 2
make[1]: Leaving directory '/host/usr/src/kernels/5.4.119-19-0009.1'
make: *** [Makefile:16: all] Error 2
* Trying to dkms install falco module with GCC /usr/bin/gcc-8
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'/tmp/falco-dkms-make'....
cleaning build area...

DKMS: build completed.

falco.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.4.119-19-0009.1/kernel/extra/

depmod...

DKMS: install completed.
* falco module installed in dkms
* falco module found: /var/lib/dkms/falco/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/5.4.119-19-0009.1/x86_64/module/falco.ko
* Trying insmod
* Success: falco module found and loaded in dkms
Thu Mar 17 11:36:27 2022: Falco version 0.31.1 (driver version b7eb0dd65226a8dc254d228c8d950d07bf3521d2)
Thu Mar 17 11:36:27 2022: Falco initialized with configuration file /etc/falco/falco.yaml
Thu Mar 17 11:36:27 2022: Loading rules from file /etc/falco/falco_rules.yaml:
Thu Mar 17 11:36:27 2022: Loading rules from file /etc/falco/falco_rules.local.yaml:
Thu Mar 17 11:36:28 2022: Starting internal webserver, listening on port 8765
11:36:28.181973000: Informational Privileged container started (user=root user_loginuid=0 command=container:35403c0b3529 k8s.ns=kube-system k8s.pod=ip-masq-agent-x2qtv container=35403c0b3529 image=ccr.ccs.tencentyun.com/library/ip-masq-agent:v2.6.1-tke.1) k8s.ns=kube-system k8s.pod=ip-masq-agent-x2qtv container=35403c0b3529
11:36:28.184526000: Informational Privileged container started (user=root user_loginuid=0 command=container:f7c9d718da45 k8s.ns=kube-system k8s.pod=tke-monitor-agent-2d574 container=f7c9d718da45 image=ccr.ccs.tencentyun.com/tkeimages/monitor-agent:v1.3.0-cfcacf) k8s.ns=kube-system k8s.pod=tke-monitor-agent-2d574 container=f7c9d718da45
11:36:28.186692000: Informational Privileged container started (user=root user_loginuid=0 command=container:8f59f95bbe64 k8s.ns=kube-system k8s.pod=node-local-dns-tw4zx container=8f59f95bbe64 image=ccr.ccs.tencentyun.com/tcrimages/k8s-dns-node-cache:1.15.13) k8s.ns=kube-system k8s.pod=node-local-dns-tw4zx container=8f59f95bbe64
11:36:28.192224000: Informational Container with sensitive mount started (user=<NA> user_loginuid=0 command=container:fcce6457f3b8 k8s.ns=kube-system k8s.pod=tke-cni-agent-k92vl container=fcce6457f3b8 image=ccr.ccs.tencentyun.com/tkeimages/tke-cni-agent:v0.1.2 mounts=/var/lib/kubelet/pods/4bef31cd-e470-4f70-bb8f-a93bfa50dbef/volumes/kubernetes.io~configmap/tke-cni-agent-conf:/etc/tke-cni-agent-conf:ro:false:rprivate,/var/lib/kubelet/pods/4bef31cd-e470-4f70-bb8f-a93bfa50dbef/volumes/kubernetes.io~secret/tke-cni-token-c6n4g:/var/run/secrets/kubernetes.io/serviceaccount:ro:false:rprivate,/var/lib/kubelet/pods/4bef31cd-e470-4f70-bb8f-a93bfa50dbef/etc-hosts:/etc/hosts::true:rprivate,/var/lib/kubelet/pods/4bef31cd-e470-4f70-bb8f-a93bfa50dbef/containers/tke-cni-agent/9d731336:/dev/termination-log::true:rprivate,/opt/cni/bin:/host/opt/cni/bin::true:rprivate,/etc/cni/net.d:/host/etc/cni/net.d::true:rprivate,/etc/kubernetes:/host/etc/kubernetes::true:rprivate) k8s.ns=kube-system k8s.pod=tke-cni-agent-k92vl container=fcce6457f3b8
11:36:28.194202000: Informational Privileged container started (user=<NA> user_loginuid=0 command=container:dfa9cb7e1e0a k8s.ns=kube-system k8s.pod=kube-proxy-jhhqw container=dfa9cb7e1e0a image=ccr.ccs.tencentyun.com/tkeimages/hyperkube:v1.18.4-tke.23) k8s.ns=kube-system k8s.pod=kube-proxy-jhhqw container=dfa9cb7e1e0a
11:36:28.196265000: Informational Privileged container started (user=<NA> user_loginuid=0 command=container:5bb56a04274c k8s.ns=kube-system k8s.pod=oom-guard-4v4z7 container=5bb56a04274c image=ccr.ccs.tencentyun.com/tkeimages/oomguard:v2.1) k8s.ns=kube-system k8s.pod=oom-guard-4v4z7 container=5bb56a04274c
11:36:28.210731000: Informational Privileged container started (user=<NA> user_loginuid=0 command=container:3eaaaf0ba293 k8s.ns=kube-system k8s.pod=tke-bridge-agent-4mmld container=3eaaaf0ba293 image=ccr.ccs.tencentyun.com/tkeimages/tke-bridge-agent:v0.1.3) k8s.ns=kube-system k8s.pod=tke-bridge-agent-4mmld container=3eaaaf0ba293
11:36:28.233352000: Informational Privileged container started (user=<NA> user_loginuid=0 command=container:e2a31df4274c k8s.ns=kube-system k8s.pod=csi-cosplugin-sjdmf container=e2a31df4274c image=ccr.ccs.tencentyun.com/tkeimages/csi-tencentcloud-cos:v2.0.1) k8s.ns=kube-system k8s.pod=csi-cosplugin-sjdmf container=e2a31df4274c
11:36:28.242569000: Informational Privileged container started (user=<NA> user_loginuid=0 command=container:c1ed67a6bc7c k8s.ns=kube-system k8s.pod=csi-nodeplugin-cfsplugin-99vz9 container=c1ed67a6bc7c image=ccr.ccs.tencentyun.com/tkeimages/csi-tencentcloud-cfs:v2.0.2) k8s.ns=kube-system k8s.pod=csi-nodeplugin-cfsplugin-99vz9 container=c1ed67a6bc7c
11:36:28.245906000: Informational Privileged container started (user=<NA> user_loginuid=0 command=container:198a9ef6e2a6 k8s.ns=kube-system k8s.pod=csi-cbs-node-58qqr container=198a9ef6e2a6 image=ccr.ccs.tencentyun.com/tkeimages/csi-tencentcloud-cbs:v2.0.3) k8s.ns=kube-system k8s.pod=csi-cbs-node-58qqr container=198a9ef6e2a6

'''

**Since when has it been failing**:
deployment之后就失败了，一直无法正常使用，不知道为什么？没看到官方有特别好用的基于kubectl的部署方式，只有helm的部署方式，我这边无法进行helm的安装，只能依赖kubectl。

**Test link**:
git clone  https://github.com/falcosecurity/evolution
cd evolution/deploy/kubernetes/
kubectl apply -k falco

**Reason for failure**:
不清楚
**Anything else we need to know**:
如果可以，最好给一个基于kubectl部署的deployment.yaml的地址或者样例也行，当前无法使用helm部署。

**Comment by changliwei** [comment]
通过SCL源的方式安装使用高版本gcc试试
https://gitee.com/Tencent/tencentos-kernel#%E9%80%9A%E8%BF%87%E8%85%BE%E8%AE%AF%E8%BD%AF%E4%BB%B6%E6%BA%90%E8%8E%B7%E5%8F%96tencentos-server%E8%BD%AF%E4%BB%B6%E5%AE%89%E8%A3%85%E5%8C%85
`# yum -y install tlinux-release-sclo（CentOS 7系统请使用yum -y install centos-release-scl-rh）
# yum -y install devtoolset-8-gcc 
# scl enable devtoolset-8 bash`
