### ISSUE TITLE
Falco alerts are not getting logged in Syslog

### ISSUE THREAD

**Issue by avadhut123pisal** [falcosecurity/falco#1983]
**Describe the bug**

Alerts generated by Falco are not getting logged in the Syslog (/var/log/messages).

**How to reproduce it**

1. Deploy the Falco using helm chart:

 `helm install falco falcosecurity/falco`

2. To generate an alert, exec into the pod running in the same cluster and create a file under /etc directory.

3. Alerts can be seen in the Falco pod logs but even if Syslog output is enabled, no logs related to the Falco events are found in Syslog (/var/log/messages)

**Expected behavior**

Events should be logged in Syslog. 

**Environment**

- Falco version:

  Falco version: 0.31.1
  Driver version: b7eb0dd65226a8dc254d228c8d950d07bf3521d2

- System info:
  {
    "machine": "x86_64",
    "nodename": "falco-dfw68",
    "release": "5.4.181-99.354.amzn2.x86_64",
    "sysname": "Linux",
    "version": "#1 SMP Wed Mar 2 18:50:46 UTC 2022"
  }

- Cloud provider or hardware configuration: AWS (EKS)

- OS:
  PRETTY_NAME="Debian GNU/Linux 10 (buster)"
  NAME="Debian GNU/Linux"
  VERSION_ID="10"
  VERSION="10 (buster)"
  VERSION_CODENAME=buster
  ID=debian
  HOME_URL="https://www.debian.org/"
  SUPPORT_URL="https://www.debian.org/support"
  BUG_REPORT_URL="https://bugs.debian.org/"

- Kernel:
   Linux falco-dfw68 5.4.181-99.354.amzn2.x86_64 #1 SMP Wed Mar 2 18:50:46 UTC 2022 x86_64 GNU/Linux

- Installation method:
  Kubernetes

**Comment by Kaizhe** [comment]
I think writing to syslog works when falco is installing as a daemon service in Linux node, not as k8s workload.  It will be have fix the yaml file to mount on `/dev/log` if `syslog_output` is enabled. cc @leogr

**Comment by leogr** [comment]
> I think writing to syslog only works when falco is installing as a daemon service in Linux node, not as k8s workload. It will be a fix of the deployment yaml file to mount on `/dev/log` if `syslog_output` is enabled. cc @leogr
> 
> A better place file the issue would be in https://github.com/falcosecurity/charts

@Kaizhe is correct. `syslog_output` is intended for host installation. If you run Falco inside a container, it will use the syslog system present in the container (it's up to you to use/forward it, eventually).

This is definitively not a bug, IMHO.

I'm also wondering if there's a compelling use case for using Syslog that way in a cluster? Am I missing something?

**Comment by Issif** [comment]
FYI, since 2.25.0, Falcosidekick is able to forward the events to a remote Syslog server, see https://github.com/falcosecurity/falcosidekick/pull/272
