### ISSUE TITLE
BPF compile under clang 13.x

### ISSUE THREAD

**Issue by dnwe** [falcosecurity/falco#2001]
**Describe the bug**

Similar to https://github.com/falcosecurity/falco/issues/1748, but now with newer clang. If the BPF module is compiled using 
clang 13.x for a 4.15 kernel, then falco crashes with a BPF stacktrace at startup. The same module built using clang 12.x works without issue.

**How to reproduce it**

- compile the BPF module on RHEL 8 using clang 13.0.1 and it crashes at startup with the backtrace
- compile the BPF module on RHEL 8 using clang 12.0.1 again and the module is usable

**Expected behaviour**

BPF module should be usable with either stable compiler version

**Screenshots**

N/A

**Environment**

- Falco version: 0.31.1

- System info: `{"machine":"x86_64","nodename":"XXXXXXXX","release":"4.15.0-176-generic","sysname":"Linux","version":"#185-Ubuntu SMP Tue Mar 29 17:40:04 UTC 2022"}`

- Cloud provider or hardware configuration:
- OS: Ubuntu 18.04.6 LTS

- Kernel: 4.15.0-176-generic

- Installation method: Kubernetes

**Additional context**

Full bpf backtrace: https://gist.github.com/dnwe/35fd1edc7082b61238bd8478524b4797

**Comment by FedeDP** [comment]
Hi @dnwe !
Are you able to test with libs master and its scap open example, following https://github.com/falcosecurity/libs#test-drivers?
This way, we can avoid wasting time on an already-solved issue :)

**Comment by dnwe** [comment]
@FedeDP I can confirm that when I tested with falcosecurity/libs@1be924900a09cf2e4db4b4ae13d03d838959f350 and clang 13.0.1 scap was working. I then built a snapshot of upcoming falco 0.32.0 using falcosecurity/falco@eb9a9c6e (with the same libs as above) and that was able to start in BPF mode without issue for me, so it looks like the problem is already fixed

**Comment by FedeDP** [comment]
Great news! Thank you for taking the time to test it :)

**Comment by dnwe** [comment]
Closing as fixed. Thanks 😊
