### ISSUE TITLE
Use libbpf and CO-RE BPF to build the BPF probe

### ISSUE THREAD

**Issue by ocampeau** [falcosecurity/falco#2003]
**Motivation**
I have a Ubuntu machine with a fresh install of Ubuntu 22.04 LTS (kernel version 5.15). 
The full distro version is `ubuntu-generic_5.15.0-27-generic_28`

I am trying to deploy Falco on my local Kubernetes cluster, and I keep getting the same error when using the BPF probe:

`Runtime error: BPF probe version is b7eb0dd65226a8dc254d228c8d950d07bf3521d2, but running version is 319368f1ad778691164d33d59945e00c5752cd27. Exiting.`

This error is caused by the `driver-loader` container. 

From what I understand, this error is because there is no BPF probe that matches my kernel+distro version available for download in the Falco driver registry. A solution would be to compile the BPF probe at deployment time, but that seems to require some tooling present on the node. This is not a viable solution when deploying to many Kubernetes clusters.

**Feature**
Use libbpf + CO-RE bpf to build the BPF probe. See [libbpf repository](https://github.com/libbpf/libbpf) here.

I am not an expert on BPF, but from what I know using [libbpf](https://github.com/libbpf/libbpf), the generated `vmlinux.h` header file (which removes the dependency on kernel headers for compilation) and the `bpf_core_read.h` header file (which re-aligns on the fly the memory layout of a struct depending on the host's kernel), its possible to build and compile a BPF program once that will work on (almost) any kernel version. 

It seems to me that it would make it possible for Falco to build a BPF probe once, and ship it with the `driver-loader` Docker image. No need for the `falco-driver-loader` script to run and detect the kernel version and distro version anymore; a single pre-built BPF probe for all distros.

I might be wrong on some details. I am appealing to BPF programmers and experts to correct me if I am wrong. But it seems to me that using `libbpf` would make it easier to install Falco with the BPF probe on newer kernel. 

**Alternatives**
Like I said, an alternative seems to provision all nodes of a cluster with the necessary tooling to support compiling the BPF probe on the host (or to compile and load the kernel module). But that solution does not scale well in my opinion.

**Additional context**

**Comment by jasondellaluce** [comment]
Hey @ocampeau, we have a merged proposal for a new eBPF probe with CORE support! The development is a WIP, take a look and let me know what you think! https://github.com/falcosecurity/libs/blob/master/proposals/20220329-modern-bpf-probe.md

**Comment by ocampeau** [comment]
Sorry for my late reply. That's seems really nice I'll take a look for sure. Thanks
