### ISSUE TITLE
Update docs for Puppet module

### ISSUE THREAD

**Issue by genebean** [falcosecurity/falco#2005]
**What to document**

https://forge.puppet.com/modules/sysdig/falco still points to this repo but it seems that something related to https://github.com/falcosecurity/falco/issues/1114 moved it to https://github.com/falcosecurity/evolution/tree/master/integrations/puppet-module/falco. 

That code seems to have been abandoned and is in a non-working state. I have taken the code and created https://github.com/voxpupuli/puppet-falco. I suggest updating your docs to point to it and marking the one in falcosecurity/evolution as depreciated via https://forgeapi.puppet.com/#tag/Module-Operations/operation/deprecateModule

**Comment by genebean** [comment]
https://forge.puppetlabs.com/modules/puppet/falco has been released too

**Comment by maxgio92** [comment]
What do you think about proposing your up-to-date module to be adopted as sandbox project, in [falcosecurity/evolution](https://github.com/falcosecurity/evolution)?

**Comment by genebean** [comment]
Depends on what that means. Puppet modules can't be used effectively when embedded within another repo, but if that isn't a requirement I'd like to know more.
