### ISSUE TITLE
Falco "Terminal shell in container" producing duplicates alerts

### ISSUE THREAD

**Issue by ajinkya1986** [falcosecurity/falco#2008]
**Describe the bug**

The rule "Terminal shell in container" is triggered multiple times

**How to reproduce it**

Open a shell in a container and I get the alert 7 times

**Expected behaviour**

Get only one alert

**Screenshots**

**Environment**

Falco version: 0.30
System info: EKS Kubernetes 1.21
Cloud provider or hardware configuration: AWS
OS: Amazon Linux 2
Kernel: 5.4.188-104.359.amzn2.x86_64
Installation method: Helm Installation

**Additional Context**:
We are trying to set up alert system by installing falco with helm chart. We had 2 node groups with 2 nodes each. But for the above rule we are getting multiple alerts.

**Comment by Issif** [comment]
Hello,

Can you upgrade up to 0.31.0 and check if it sill happens please

**Comment by ajinkya1986** [comment]
We are still getting multiple alerts for the rule even after upgrading to falco 0.31.1.

**Comment by jasondellaluce** [comment]
Closing this as a duplicate of https://github.com/falcosecurity/falco/issues/1854
