### ISSUE TITLE
Return node information in supported fields.

### ISSUE THREAD

**Issue by ajinkya1986** [falcosecurity/falco#2014]
**Motivation**

We want to build a response from falco in which we get the node information (VMs). We will use these VMs info in our rule exceptions

**Feature**

Falco should also have supported fields of node information.

**Alternatives**

**Additional context**

**Comment by jasondellaluce** [comment]
Hi @ajinkya1986, it would be helpful if you could provide explicit examples of information you need and that is not yet supported.

**Comment by ajinkya1986** [comment]
Hi,
 In the supported fields as mentioned in the below documents we can get info of namespace from `k8.ns.name` or image name from `container.image`. Similarly I want info of the node name or node attributes.
https://falco.org/docs/rules/supported-fields/

**Comment by jasondellaluce** [comment]
Does the Falco `-p` work for you? It allows you to append arbitrary formatted strings to every alert output. In that way, you can add metadata info to your alert depending on the machine you are running Falco into.
