### ISSUE TITLE
Falco supported fields now working.

### ISSUE THREAD

**Issue by ajinkya1986** [falcosecurity/falco#2038]
**Describe the bug**

When generating the output for a rule in falco `k8s.deployment.name` returned a `<N/A>` even though a deployment was deployed on the kubernetes cluster.

**How to reproduce it**

1. Create a cluster in any cloud provide.
2. Take any rule from falco rules list and add it to the customRules block in falco
3. Add an output field as deployment=%k8s.deployment.name
4. Run a deployment manifest of your choice.
5. Test the rule so that it fails
6. Check falco logs for failing rules.
7. The output fields should show the deployment name.

**Expected behaviour**

In the output fields of falco logs., using k8s.deployment.name as well as k8s.deployment.id should return something

**Environment**

- Falco version: 0.31.1
- Cloud provider or hardware configuration: AWS
- OS: Amazon Linux 2
- Installation method: Helm

**Comment by jasondellaluce** [comment]
@ajinkya1986 would you consider updating to Falco 0.32 and see if this is still an issue?

**Comment by ajinkya1986** [comment]
Still facing the same issue.

**Comment by alacuku** [comment]
Hi @ajinkya1986, Falco 0.32.1 has been released which should fix this issue. Could you please test it?
