### ISSUE TITLE
Make falco aborts with an error (undefined reference to `gsasl_check_version')

### ISSUE THREAD

**Issue by dadav** [falcosecurity/falco#2040]
**Description**

I'm trying to compile falco from source and during the `Linking CXX executable falco` step the build aborts with an error.

The output looks like this:

```bash
[ 84%] Linking CXX executable falco
/usr/bin/ld: ../../curl-prefix/src/curl/lib/.libs/libcurl.a(libcurl_la-version.o): in function `curl_version':
version.c:(.text+0x92): undefined reference to `gsasl_check_version'
/usr/bin/ld: ../../curl-prefix/src/curl/lib/.libs/libcurl.a(libcurl_la-version.o): in function `curl_version_info':
version.c:(.text+0x19c): undefined reference to `gsasl_check_version'
collect2: error: ld returned 1 exit status
```

**How to reproduce**

```bash
$ cmake .. -DBUILD_BPF=ON -DUSE_BUNDLED_DEPS=ON
$ make -j4 falco
```

**Expected behaviour**

The build should complete successfully.

**Environment**

I'm running the latest archlinux version, but use the `USE_BUNDLED_DEPS` option to compile with the correct dependencies.

```bash
$ uname -r
5.18.1-arch1-1

$ openssl version
OpenSSL 1.1.1o  3 May 2022
```
I'm using the source version tagged with `0.32.0`.

**Comment by dadav** [comment]
> Hey! First time seeing an issue like this, so I'll try my best and see if we can scope it a little. Few questions:
> 
>     * Did this happen on any Falco code tag prior to 0.32.0?
> 
>     * It seems like the linker does't find `gsasl` in your system. Can you make sure it is correctly installed? (Maybe this may serve as reference: https://archlinux.org/packages/extra/x86_64/gsasl/)

Hey, thx for your response. I have gsasl installed and get the same error on the 0.31.1 tag.

**Comment by dadav** [comment]
Ok, I just managed to compile falco with the system dependencies :) I could then run it like this:

`sudo FALCO_BPF_PROBE="$HOME/.falco/probe.o" falco -r all_cmds.yaml`

**Comment by jasondellaluce** [comment]
That's great! Do you mean that you compiled with `-DUSE_BUNDLED_DEPS=OFF`?

Looking forward to hear more, and let me know if you are ok with closing this issue.

**Comment by dadav** [comment]
> That's great! Do you mean that you compiled with `-DUSE_BUNDLED_DEPS=OFF`?
> 
> Looking forward to hear more, and let me know if you are ok with closing this issue.

Exactly! I'm ok with closing the issue :) Thx for your help!

**Comment by NabeelShahid7** [comment]
I would like to work on this enhancement.. Can I please get some kind of an approval from any contributor of this repository?
About Me:
I am a student currently pursuing his Post Graduate in Computer Science. I have been assigned a course component which involves contributing to any open source project. I am liking this repository and would like to start from scratch to try getting this issue fixed. @jasondellaluce @dadav @poiana

**Comment by jasondellaluce** [comment]
> Exactly! I'm ok with closing the issue :) Thx for your help!

/close

@NabeelShahid7 thanks for reaching out. This issue seems to be solved (gonna close it right now), but there's plenty of other issues you can start work on, either in this repository or in any other in the Falcosecurity org. I'd also suggest joining the Wednesday's community call and the Slack channel, introducing yourself and asking if there's anything you can help with!
