### ISSUE TITLE
CircleCI: Add SHA256 signature to aarch64 rpm packages

### ISSUE THREAD

**Issue by vjjmiras** [falcosecurity/falco#2064]
**Describe the bug**

New ARM64 packages don't seem to be processed by the rpm-sign CircleCI job and therefore they are not signed.

**How to reproduce it**

$ rpm -qi -p ./falco-0.32.0-30*rpm | grep -e Name -e Version -e Architecture -e Signature
Name        : falco
Version     : 0.32.0_30+85f91a3
Architecture: aarch64
Signature   : (none)

Name        : falco
Version     : 0.32.0_30+85f91a3
Architecture: x86_64
Signature   : RSA/SHA256, Mon 13 Jun 2022 09:22:35 AM UTC, Key ID 9f76b25b3672ba8f

**Expected behaviour**

Both x86_64 and aarch64  RPM packages should be signed to make possible its verification at installation time.

**Screenshots**

See above

**Environment**

I've tested it on RHEL9 but the same result should be obtained on previous versions.

- Falco version:
0.32.0_30+85f91a3

- System info:

- Cloud provider or hardware configuration: n/a
- OS: n/a
- Kernel: n/a
- Installation method: RPM

**Additional context**

**Comment by vjjmiras** [comment]
My guess is that the newly generated aarch64 .rpm packages are not found in the build/releases that the rpm-sign job is using to look for .rpm packages.

**Comment by leogr** [comment]
> My guess is that the newly generated aarch64 .rpm packages are not found in the build/releases that the rpm-sign job is using to look for .rpm packages.

You're probably right. Good catch. 
cc @FedeDP
