### ISSUE TITLE
Cut Falco 0.32.1 Release

### ISSUE THREAD

**Issue by LucaGuerra** [falcosecurity/falco#2070]
## Type

This is a **patch** release.

## Date

July 11th, 2022

## Release Version

https://github.com/falcosecurity/falco/releases/tag/0.32.1

libs: https://github.com/falcosecurity/libs/tree/0.7.0
drivers: https://github.com/falcosecurity/libs/releases/tag/2.0.0%2Bdriver

## Release Steps

Read the [release process](https://github.com/falcosecurity/falco/blob/master/RELEASE.md) for a detailed explanation.

## Release Blocking PRs

This list will be updated as more issues are addressed.

- https://github.com/falcosecurity/libs/pull/404
- https://github.com/falcosecurity/libs/pull/393
- https://github.com/falcosecurity/libs/pull/385
- https://github.com/falcosecurity/test-infra/pull/734
- https://github.com/falcosecurity/falco/pull/2069
- https://github.com/falcosecurity/falco/pull/2078
- https://github.com/falcosecurity/libs/pull/420
- https://github.com/falcosecurity/libs/pull/421
- https://github.com/falcosecurity/libs/pull/416
- https://github.com/falcosecurity/libs/pull/425
- https://github.com/falcosecurity/libs/pull/418
- https://github.com/falcosecurity/libs/pull/429
- https://github.com/falcosecurity/libs/pull/430
- https://github.com/falcosecurity/libs/pull/438
- https://github.com/falcosecurity/falco/pull/2100
- https://github.com/falcosecurity/libs/pull/445
- https://github.com/falcosecurity/falco/pull/2102
- https://github.com/falcosecurity/libs/pull/458

### Nice to Have

- https://github.com/falcosecurity/falco/pull/2094 (cleanup)
- https://github.com/falcosecurity/falco/pull/2101 (can be done post release but documentation needs to be added!)
- https://github.com/falcosecurity/falco/pull/2099
- https://github.com/falcosecurity/falco/pull/2093
- https://github.com/falcosecurity/libs/pull/463

## Action Items

- [x] **Pre-Release**
    - [x] Prebuilt drivers publish (including ARM)
    - [x] Update milestones for [closed issues](https://github.com/falcosecurity/falco/pulls?q=is%3Apr+is%3Amerged+closed%3A%3E2022-06-03) to 0.32.1
    - [x] Changelog
    - [x] Update and tag plugins
    - [x] Bump plugins in Falco
- [x] **Release**
    - [x] Tag
    - [x] GitHub Release
- [x] **Website**
    - [x] Bump Falco version to 0.32.1
    - [x] Update syscall and supported fields
- [x] **Announcements** 
- [x] **Post-Rlease**
    - [x] Helm Charts
 
## Test checklist

The following items are useful for anyone that wishes to test this release when RC's are out depending on the environment they have available. Help is appreciated as always.

[Installation types](https://falco.org/docs/getting-started/installation/)

* Kubernetes Helm Chart
* Container only (without kubernetes)
* eBPF probe installation
* Local DEB package
* Local RPM package
* Local binary
* Local binary (musl-static)

### 0.32.1 specific checklist

* https://github.com/falcosecurity/libs/pull/395
    * See description in the PR: "When Falco is running with -A option enabled and receives events generated by io_uring_enter and io_uring_register syscalls it crashes"
* Falco-driver-loader recent modifications
    * https://github.com/falcosecurity/falco/pull/2066

/assign @LucaGuerra 
/kind documentation

**Comment by jasondellaluce** [comment]
Thanks @LucaGuerra! I created a [0.32.1 milestone](https://github.com/falcosecurity/falco/milestone/25) and moved there all currently closed PRs.

**Comment by leogr** [comment]
Hey @LucaGuerra 

Thank you! Could you also add :point_down: please?
https://github.com/falcosecurity/falco/pull/2069

**Comment by Andreagit97** [comment]
Hey @LucaGuerra

could you please add PR https://github.com/falcosecurity/libs/pull/418 ?

**Comment by jasondellaluce** [comment]
@LucaGuerra PTAL at these two and see if they could be useful. I think they be good nice-to-haves:
- https://github.com/falcosecurity/falco/pull/2090
- https://github.com/falcosecurity/falco/pull/2093

**Comment by jasondellaluce** [comment]
Another nice-to-have: https://github.com/falcosecurity/falco/pull/2094

**Comment by FedeDP** [comment]
@LucaGuerra can you add #2099 + #2101 as nice-to-have, and #2100 as mandatory (to fix integration tests :/ )

**Comment by wdoekes** [comment]
That libs version change in this patch bump between 0.32.0 and 0.32.1 was quite unexpected. It's not a problem, but I will call it a strange choice.

https://git.osso.nl/pub/docker/falco-ebpf-build/-/commit/76ca2dfff8d2c4835094a346768533cde1172629

**Comment by leogr** [comment]
Hey @LucaGuerra 

The Falco Helm Chart 2.0 is out :point_down: 
https://github.com/falcosecurity/charts/releases/tag/falco-2.0.0

PS I think we can close this issue now :)
