### ISSUE TITLE
Can falco provide ARM execution pkg as default?

### ISSUE THREAD

**Issue by swxEmily** [falcosecurity/falco#2077]
**Motivation**

**Feature**

our system use ARM and AMD64, falco do not support ARM as default, need to build from code which cost many work
**Alternatives**

**Additional context**

**Comment by jasondellaluce** [comment]
Hi @swxEmily! Would you expand on what you mean "by default"? If you are referring to the community releasing ARM artefacts, that's something that's about to happen from the next patch release: https://github.com/falcosecurity/falco/issues/2070

**Comment by swxEmily** [comment]
> Hi @swxEmily! Would you expand on what you mean "by default"? If you are referring to the community releasing ARM artefacts, that's something that's about to happen from the next patch release: #2070

So when will 0.32.1 be released?

**Comment by jasondellaluce** [comment]
Follow that issue for the most up-to-date developments:
```
Targeting the week starting July 4th, 2022
```

**Comment by jasondellaluce** [comment]
Falco now fully supports ARM64 and we regularly distribute builds for that architecture (e.g. https://download.falco.org/?prefix=packages/bin/aarch64/). Closing this.

/close
