### ISSUE TITLE
arm deb package for ubuntu

### ISSUE THREAD

**Issue by grosser** [falcosecurity/falco#2083]
missing from https://download.falco.org/packages/deb 🤷 

FYI building it manually

```
# falco.dockerfile
FROM falco-builder
COPY falco /source/falco
RUN entrypoint cmake
RUN entrypoint package
```

and script:
```
export FALCO_VERSION=0.32.0

# build the builder
git clone https://github.com/falcosecurity/falco.git
cd falco
git checkout ${FALCO_VERSION}
cd docker/builder
docker build . -t falco-builder
cd ../../../

# build the package
docker build -f falco.dockerfile . -t falco-release
deb=$(docker run --entrypoint '' falco-release ls build/release | grep deb)
file=falco-${FALCO_VERSION}-linux-aarch64.deb
id=$(docker create falco-release)
docker cp $id:build/release $deb $file
docker rm -v $id
```

**Comment by jasondellaluce** [comment]
The ARM packages are not released as stable yet. They will come with Falco 0.32.1 (see: https://github.com/falcosecurity/falco/issues/2070). In the meantime, you can find the most up-to-date packages here (gonna link the latest one): https://download.falco.org/packages/deb-dev/stable/falco-0.32.0-41%2B5d10e54-aarch64.deb).

**Comment by grosser** [comment]
awesome, thanks!
