### ISSUE TITLE
README: wrong latest packages versions

### ISSUE THREAD

**Issue by FedeDP** [falcosecurity/falco#2105]
**Describe the bug**

In README file, the list of latest packages version is wrong.
This is perhaps due to the fact that we exceed aws s3 max keys limit in the query:
```
[max-keys](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_RequestSyntax)

    Sets the maximum number of keys returned in the response. By default the action returns up to 1,000 key names. The response might contain fewer keys but will never contain more.
```

**How to reproduce it**

Just look at the README :)

**Expected behaviour**

We should be able to fetch the actual latest packages!
A possible solution would be to force the `falco-$(latest_tag)` prefix (instead of the `falco-` one). But this would introduce the need to automate the "new tag -> bump readme" PR...
Moreover, the higher the pace of development of the project, the more likely to exceed the 1000 limit.

**Comment by FedeDP** [comment]
It seems the issue is that aws s3 returns keys in :
> List results are always returned in UTF-8 binary order. 

https://docs.aws.amazon.com/AmazonS3/latest/userguide/ListingKeysUsingAPIs.html

**Comment by jasondellaluce** [comment]
IMO the `falco-$(latest_tag)` solution might be an easy and yet functional workaround. Bumping the tag might be an additional step of the release process to document in `RELEASE.md`, if doing that automatically is much work. With the new release cycle, this would happen only every 4 months (excluding patch releases).
