### ISSUE TITLE
k8s_audit_rules can't be loaded

### ISSUE THREAD

**Issue by akunafin** [falcosecurity/falco#2110]
**Describe the bug**

Falco can't load the k8s_audit_rules file because of the error:

```
Error: Could not load rules file /etc/falco/k8s_audit_rules.yaml: 1 errors:
Rule Disallowed K8s User: error filter_check called with nonexistent field jevt.value[/stage]
- rule: Disallowed K8s User
  desc: Detect any k8s operation by users outside of an allowed set of users.
  condition: kevt and non_system_user and not ka.user.name in (allowed_k8s_users) and not ka.user.name in (eks_allowed_k8s_users)
  output: K8s Operation performed by user not in allowed list of users (user=%ka.user.name target=%ka.target.name/%ka.target.resource verb=%ka.verb uri=%ka.uri resp=%ka.response.code)
  priority: WARNING
  source: k8s_audit
  tags: [k8s]
```

**How to reproduce it**

Deploy the latest chart from https://github.com/falcosecurity/charts

**Expected behaviour**

Falco loads k8s_audit_rules successfully

**Environment**

- Falco version: 0.32.0

- Cloud provider or hardware configuration: AWS EKS cluster
- Installation method: Helm chart

**Comment by jasondellaluce** [comment]
Hi @akunafin, did you load the `k8saudit` and `json` plugins in your config?

**Comment by jasondellaluce** [comment]
Due to technical constraint, you currently can't have both enabled. This limitation is going to be overcame over the next releases. Follow this issue: https://github.com/falcosecurity/falco/issues/2074
