### ISSUE TITLE
Remove fntlnz from everywhere

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falco#2122]
Hey all,
I've been thinking about this for a very long time and came to a conclusion that it's time
for me to focus on other things and make room for new people here and for other things in my life.

I don't know for what I'll be remembered in this project, if for the features or for the bugs but
I'm grateful for having had the opportunity to work on Falco, especially thanks to @leodido and @ldegio .

My words of gratefulness go also to @kris-nova , to @mstemm  and to @Kaizhe 

I'll follow with a PR to remove myself from all the repos.

- Falco https://github.com/falcosecurity/falco/pull/2123
- charts https://github.com/falcosecurity/charts/pull/363
- community https://github.com/falcosecurity/community/pull/149
- evolution https://github.com/falcosecurity/evolution/pull/153
- falcoctl https://github.com/falcosecurity/falcoctl/pull/112
- libs https://github.com/falcosecurity/libs/pull/471
- go plugin sdk https://github.com/falcosecurity/plugin-sdk-go/pull/61
- test infra https://github.com/falcosecurity/test-infra/pull/761
- client go https://github.com/falcosecurity/client-go/pull/58
- driverkit https://github.com/falcosecurity/driverkit/pull/new/remove-fntlnz
- pdig https://github.com/falcosecurity/pdig/pull/28
- plugins https://github.com/falcosecurity/plugins/pull/130
- client-rs https://github.com/falcosecurity/client-rs/pull/18
- event generator https://github.com/falcosecurity/event-generator/pull/74
- falco website https://github.com/falcosecurity/falco-website/pull/646
- kilt https://github.com/falcosecurity/kilt/pull/53
- plugin-sdk-cpp https://github.com/falcosecurity/plugin-sdk-cpp/pull/7
- template https://github.com/falcosecurity/template-repository/pull/3

I'll remove myself from the organization as well.

It was a good journey, ciao!

Ad maiora

**Comment by jasondellaluce** [comment]
Hi @fntlnz, It's sad to see you go. I didn't have the pleasure to work with you, but I came across your name in many parts of the codebase. Your work speaks by itself, thank you for all you did for the community.

As for next steps of your decision, the DCO checks are failing in all your PR. Would you please proceed and sign-off your commits?
