### ISSUE TITLE
Runtime error: Invalid filler error

### ISSUE THREAD

**Issue by youssufelshall** [falcosecurity/falco#2135]
**Describe the bug**
I am trying to run Falco as a systemd service in Bottlerocket OS using eBPF probe. However, when trying to start the systemd service I get the following error:
```
bash-5.1# /usr/bin/falco -c /etc/falco/falco.yaml
Tue Jul 19 19:37:19 2022: Falco version 0.32.0 (driver version 39ae7d40496793cf3d3e7890c9bbdc202263836b)
Tue Jul 19 19:37:19 2022: Falco initialized with configuration file /etc/falco/falco.yaml
Tue Jul 19 19:37:19 2022: Loading rules from file /etc/falco/falco_rules.yaml:
Rules match ignored syscall: warning (ignored-evttype):
         loaded rules match the following events: access,brk,close,cpu_hotplug,drop,epoll_wait,eventfd,fcntl,fstat,fstat64,futex,getcwd,getdents,getdents64,getegid,geteuid,getgid,getpeername,getresgid,getresuid,getrlimit,getsockname,getsockopt,getuid,infra,io_uring_enter,io_uring_register,io_uring_setup,k8s,llseek,lseek,lstat,lstat64,mesos,mlock,mlockall,mmap,mmap2,mprotect,munlock,munlockall,munmap,nanosleep,notification,page_fault,poll,ppoll,pread,preadv,procinfo,pwrite,pwritev,read,readv,recv,recvmmsg,scapevent,select,semctl,semget,semop,send,sendfile,sendmmsg,setrlimit,shutdown,signaldeliver,splice,stat,stat64,switch,timerfd_create,write,writev;
         but these events are not returned unless running falco with -A
Tue Jul 19 19:37:20 2022: Unable to load the driver.
Tue Jul 19 19:37:20 2022: Runtime error: invalid filler name: sys_dup_e. Exiting.
```
I cannot find anything on sys_dup_e. Also, I assume that after it is not able to load the driver (Kernel module) it uses the probe successfully.

**How to reproduce it**

1. Install Falco v0.32.0 as package in Bottlerocket.
2. Build probe using [Bottlerocket SDK](https://github.com/bottlerocket-os/bottlerocket-sdk).
3. Install probe using Bootstrap Container.

**Expected behaviour**
For Falco to successfully start as a Systemd service.

**Screenshots**

**Environment**

- Falco version: 0.32.0

- System info:
"system_info":
```
    {
      "machine": "x86_64",
      "nodename": "",
      "release": "5.10.118",
      "sysname": "Linux"
    },
```

- Cloud provider or hardware configuration:
- OS: 
```
NAME=Bottlerocket
ID=bottlerocket
VERSION="1.8.0 (aws-k8s-1.22)"
PRETTY_NAME="Bottlerocket OS 1.8.0 (aws-k8s-1.22)"
VARIANT_ID=aws-k8s-1.22
VERSION_ID=1.8.0
BUILD_ID=a0e3782e-dirty
HOME_URL="https://github.com/bottlerocket-os/bottlerocket"
SUPPORT_URL="https://github.com/bottlerocket-os/bottlerocket/discussions"
BUG_REPORT_URL="https://github.com/bottlerocket-os/bottlerocket/issues"
```
- Kernel: Linux 5.10.118 x86_64 GNU/Linux

- Installation method: Prebuilt binary packaged into Bottlerocket OS.

**Additional context**
I am not using any containers to run Falco. I am trying to run on the host OS as a Systemd service. I suspected the issue might be one of two things:
- Using a prebuilt libstdc++.so.6 shared library from Fedora, but then I changed it by using a prebuilt one from Amazon Linux 2.
- Using a prebuilt Falco binary instead of building one from scratch.

**Comment by FedeDP** [comment]
Hi! Thanks for opening this issue!
Are you using by chance a 0.32.1 driver against a 0.32.0 Falco?

**Comment by Andreagit97** [comment]
Hi @youssufelshall, as @FedeDP said probably it is a problem of driver incompatibility... I leave here the link to a conversation in the k8s slack about the same topic:
* https://kubernetes.slack.com/archives/CMWH3EH32/p1658123520322949

**Comment by youssufelshall** [comment]
Turns out this was it. I downloaded Falco 0.32.0 last week but built the probe yesterday. Didn't realize a new version was released. Thanks for the help!

**Comment by FedeDP** [comment]
You're welcome!
