### ISSUE TITLE
Remove nestorsalceda from everywhere

### ISSUE THREAD

**Issue by nestorsalceda** [falcosecurity/falco#2143]
Hey,

Following the good example from @fntlnz on https://github.com/falcosecurity/falco/issues/2122 I decided to do the same thing. Because of the behaviour watched in the following issues:

* https://github.com/falcosecurity/falco/issues/2106
* https://github.com/falcosecurity/evolution/issues/157
* https://github.com/falcosecurity/falco/issues/2132

I disagree with that kind of behaviour and I was forced to step down. Let's say this is not the kind of community nor governance I expected when I joined the project. So I prepared the following PR's to make things easier:

* https://github.com/falcosecurity/evolution/pull/166
* https://github.com/falcosecurity/charts/pull/373
* https://github.com/falcosecurity/test-infra/pull/778

Thank you @fntlnz, @leodido and @kris-nova. As I told you before, the only thing I regret was to not spent more time with you, I think I missed the chance to learn more things from you.

Hasta la vista!

**Comment by jasondellaluce** [comment]
Hi @nestorsalceda, unfortunately we can't merge your PRs unless they're DCO signed. If you're not able to do this, the maintainers of the relevant repos will submit an equivalent PR.

**Comment by leogr** [comment]
Done.

Anyway, thanks for all.

/close
