### ISSUE TITLE
Falco pods crashing with "free(): corrupted unsorted chunks"

### ISSUE THREAD

**Issue by lzaldivarkt** [falcosecurity/falco#2144]
**Describe the bug**
Similar to #1656, we are seeing a high occurrence of segfaults on falco, with the error: 
```
free(): corrupted unsorted chunks
```
and exit code 139.

I managed to get a coredump, you can find it here:
http://motive-shared-public-files.s3-website-us-east-1.amazonaws.com/falco.coredump.gz

We have multiple clusters running on the same configuration, and this is the only one crashing. The main difference is this is a high activity cluster, so maybe it's related to that.

**How to reproduce it**

Falco starts up, and crashes. Here's an example of the full logs: 

```
* Setting up /usr/src links from host
* Running falco-driver-loader for: falco version=0.30.0, driver version=3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4
* Running falco-driver-loader with: driver=module, compile=yes, download=yes
* Unloading falco module, if present
* Trying to load a system falco module, if present
* Looking for a falco module locally (kernel 4.9.0-14-amd64)
* Trying to download a prebuilt falco module from https://download.falco.org/driver/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/falco_debian_4.9.0-14-amd64_1.ko
* Download succeeded
* Success: falco module found and inserted
Sat Jul 23 16:32:04 2022: Falco version 0.30.0 (driver version 3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4)
Sat Jul 23 16:32:04 2022: Falco initialized with configuration file /etc/falco/falco.yaml
Sat Jul 23 16:32:04 2022: Loading rules from file /etc/falco/falco_rules.yaml:
Sat Jul 23 16:32:04 2022: Loading rules from file /etc/falco/falco_rules.local.yaml:
Sat Jul 23 16:32:04 2022: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Sat Jul 23 16:32:04 2022: Loading rules from file /etc/falco/rules.d/rules-kt.yaml:
Sat Jul 23 16:32:05 2022: Starting internal webserver, listening on port 8765
free(): corrupted unsorted chunks
```

**Expected behaviour**

Falco shouldn't crash :)  

**Environment**
- Falco version: 0.30.0
- System info:
```
  "machine": "x86_64",
  "nodename": "falco-xmdnm",
  "release": "4.9.0-14-amd64",
  "sysname": "Linux",
  "version": "#1 SMP Debian 4.9.246-2 (2020-12-17)"
```

- Cloud provider or hardware configuration:
- OS:  Debian GNU/Linux 9.13 (stretch)
- Kernel:  Linux ip-10-0-97-98 4.9.0-14-amd64 # 1 SMP Debian 4.9.246-2 (2020-12-17) x86_64 GNU/Linux

- Installation method:
Kubernetes + Helm, using official images.

**Additional context**

**Comment by FedeDP** [comment]
Hi! Thanks for opening this issue with such details! And of course it's great to have coredump!
I will give it a look asap:)

**Comment by jasondellaluce** [comment]
In the meanwhile, did you try updating Falco to the latest 0.32.1 version?

**Comment by FedeDP** [comment]
Agree with @jasondellaluce , an upgrade might fix it for you :)

**Comment by lzaldivarkt** [comment]
Working on that at the moment, I'll keep you posted.

**Comment by lzaldivarkt** [comment]
We just upgraded and we are not seeing this anymore. I guess technically we can close this.
I'm still a bit puzzled, we have been running with this configuration for a while and it didn't crash for a couple of years and one day it just started. Hopefully, it doesn't happen anymore :shrug:

**Comment by FedeDP** [comment]
Yay that's a great news!

**Comment by jasondellaluce** [comment]
@lzaldivarkt thank you for your feedback! I'm gonna proceed and close this then. Feel free to re-open this if you run into this issue again.

/close
