### ISSUE TITLE
Cut Falco 0.32.2 Release

### ISSUE THREAD

**Issue by Andreagit97** [falcosecurity/falco#2149]
## Type

This is a **patch** release.

## Date

August 10th, 2022

## Release Version

libs: https://github.com/falcosecurity/libs/tree/0.7.0
drivers: https://github.com/falcosecurity/libs/releases/tag/2.0.0%2Bdriver

## Release Steps

Read the [release process](https://github.com/falcosecurity/falco/blob/master/RELEASE.md) for a detailed explanation.

## Release Blocking PRs

This list will be updated as more issues are addressed.

- [x] https://github.com/falcosecurity/falco/pull/2142

## Release branch check-list

- [x] https://github.com/falcosecurity/falco/pull/2142

## Action Items

- [x] **Pre-Release**
    - [x] Craft release branch 
           - upstream: https://github.com/falcosecurity/falco/tree/release/0.32.2
           - fork: https://github.com/Andreagit97/falco/tree/release/0.32.2
    - [x] Update milestones to 0.32.2
    - [x]  Changelog: https://github.com/falcosecurity/falco/pull/2159
- [x] **Release**
    - [x] Sync release branch with upstream one: https://github.com/falcosecurity/falco/pull/2161
    - [x] Tag https://github.com/falcosecurity/falco/tree/0.32.2
    - [x] GitHub Release https://github.com/falcosecurity/falco/releases/tag/0.32.2
    - [x] Set the release branch as protected: https://github.com/falcosecurity/test-infra/pull/801
- [x] **Website**
    - [x] Bump Falco version to 0.32.2: https://github.com/falcosecurity/falco-website/pull/673
    - [x] Falco `0.32.2` blogpost: https://github.com/falcosecurity/falco-website/pull/674
- [x] **Announcements** 
   - [x] Falco slack channel
   - [x] Falco mailing list
- [x] **Post-Rlease**
    - [x] Helm Charts: https://github.com/falcosecurity/charts/pull/394

## Test checklist

The following items are useful for anyone that wishes to test this release when RC's are out depending on the environment they have available. Help is appreciated as always.

[Installation types](https://falco.org/docs/getting-started/installation/)

* Kubernetes Helm Chart
* Container only (without kubernetes)
* eBPF probe installation
* Local DEB package
* Local RPM package
* Local binary
* Local binary (musl-static)

/assign @Andreagit97  
/kind documentation

**Comment by jasondellaluce** [comment]
For this release we'll experiment using a release branch so that we patch the same codebase as the one of version 0.32.1. 

Should this approach work with little friction or overhead, we might consider using it for future releases too so that mainline development doesn't need to be blocked!

**Comment by Andreagit97** [comment]
Hey @jasondellaluce @leogr we did it :tada: Now, this could be closed, WDYT?

**Comment by leogr** [comment]
> Hey @jasondellaluce @leogr we did it tada Now, this could be closed, WDYT?

Sure!
/close

Thank you, @Andreagit97
