### ISSUE TITLE
Missing pre-built falco-driver kernel version 5.4.209-116.363 for EKS AMI

### ISSUE THREAD

**Issue by igoritos22** [falcosecurity/falco#2184]
We run Falco across our environments using EKS. There is a need to upgrade ours EKS AMI to version [v20220824](https://github.com/awslabs/amazon-eks-ami/blob/master/CHANGELOG.md#ami-release-v20220824) with the 5.4.209-116.363.amzn2 kernel version and the falco-driver is not present in the list of avaliable [kernel falco-drivers](https://download.falco.org/?prefix=driver/39ae7d40496793cf3d3e7890c9bbdc202263836b/).

We cannot update our environment until this driver was loaded. There is some prevision to the driver will be avaliable in list of falco's drivers?

**Comment by alan-kea** [comment]
Also waiting for this driver to become available

**Comment by dwgillies-bluescape** [comment]
We are also hoping for a pre-built driver in this version to become availablle :

`* Looking for a falco module locally (kernel 5.4.209-116.363.amzn2.x86_64)`

**Comment by FedeDP** [comment]
The driver is now there: https://download.falco.org/driver/2.0.0%2Bdriver/x86_64/falco_amazonlinux2_5.4.209-116.363.amzn2.x86_64_1.ko :rocket:

**Comment by FedeDP** [comment]
Yep there was a bug in the Arm64 driverkit workflow that prevented Arm64 drivers from being built.
It will be fixed asap!

**Comment by renilthomas** [comment]
Hi @FedeDP, there is a new kernel released: `kernel-5.4.209-116.367.amzn2.x86_64` and we are waiting for the pre-built driver to be available. Thanks!

**Comment by dwgillies-bluescape** [comment]
@renilthomas This ticket is probably superseded by https://github.com/falcosecurity/falco/issues/2273.  There is a new .368. version of the linux kernel that will be a necessary upgrade to patch nessus scan vulnerabilities.  You may want to recompile your kernel and then ask for .368. drivers to solve all your problems (at least until new vulnerabilities are found & patched ...)

**Comment by FedeDP** [comment]
Is this issue still alive? Or can we close this?
