### ISSUE TITLE
Documentation: Falco <-> libs versioning (more details)

### ISSUE THREAD

**Issue by incertum** [falcosecurity/falco#2195]
Based on the discussion in https://github.com/falcosecurity/libs/pull/580 additional documentation in this repo (falco) can help increase technical clarity around versioning.

- https://github.com/falcosecurity/libs/pull/580#discussion_r964497282
- https://github.com/falcosecurity/libs/pull/580#discussion_r964522134

CC @leogr

**Comment by h20220025** [comment]
Hello there, Can I work for this one??

**Comment by jasondellaluce** [comment]
@h20220025 for sure! Any help is welcome. I don't think solid workstream for this has started yet, but I think either this issue or the Slack channel might be the right places to discuss about this.

**Comment by leogr** [comment]
Hey @h20220025 

PR https://github.com/falcosecurity/falco/pull/2205 has already addressed this issue in an excellent way!
@incertum :pray: 

If you think there's more to add, feel free to open a PR.

/close
