### ISSUE TITLE
introduce consistent namespacing in the Falco codebase

### ISSUE THREAD

**Issue by jasondellaluce** [falcosecurity/falco#2207]
**Motivation**

Class names and namespaces are inconsistent in the Falco codebase. We have some definitions under `falco::`, and others without any namespace. This is very confusing and ambiguous towards the role/responsibility of each component of Falco, and makes naming very inconsistent.

**Feature**

Although we have the same problem in libs, and that something we can't change from Falco, a first step forward would be to polish this in the Falco codebase.

We could have everything fit inside `falco::`, then having `falco::engine` for everything concerning the rule engine, `falco::application` for the CLI app, and so on. Any proposal with a clear plan or naming strategy is welcome.

**Comment by incertum** [comment]
Nice, clean up and more consistency is always great! Love your suggestion of doing this first in Falco and then move on to libs.
