### ISSUE TITLE
Support for newer AWS EKS AmazonLinux AMIs/kernels

### ISSUE THREAD

**Issue by navas-gataca** [falcosecurity/falco#2218]
**Describe the bug**
Similar to this issue: https://github.com/falcosecurity/falco/issues/1643
Falco pods are crashing because they are trying to download a prebuilt falco module from download.falco.org/driver that does not exist yet.

**How to reproduce it**
Have EKS cluster version 1.21 (after upgrading from 1.20) with nodes using ami-062db57618f2022a2 (retrieved from https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html). Try to run falco previously installed.

**Expected behaviour**
Falco should be in Running status, but instead it gets stuck in a CrashLoopBackOff

**Screenshots**

**Environment**

- Falco version: 0.31.1

- Cloud provider or hardware configuration: EKS cluster v1.21
- OS:  Amazon Linux 2

- Kernel: 5.4.209-116.367.amzn2.x86_64

- Installation method: Helm

**Additional context**

Logs:

* Setting up /usr/src links from host
* Running falco-driver-loader for: falco version=0.31.1, driver version=b7eb0dd65226a8dc254d228c8d950d07bf3521d2
* Running falco-driver-loader with: driver=module, compile=yes, download=yes
* Unloading falco module, if present
* Looking for a falco module locally (kernel 5.4.209-116.367.amzn2.x86_64)
* Trying to download a prebuilt falco module from https://download.falco.org/driver/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/falco_amazonlinux2_5.4.209-116.367.amzn2.x86_64_1.ko
curl: (22) The requested URL returned error: 404 
Unable to find a prebuilt falco module
* Trying to dkms install falco module with GCC /usr/bin/gcc
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/build/make.log (with GCC /usr/bin/gcc)
* Trying to dkms install falco module with GCC /usr/bin/gcc-8
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/build/make.log (with GCC /usr/bin/gcc-8)
* Trying to dkms install falco module with GCC /usr/bin/gcc-6
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/build/make.log (with GCC /usr/bin/gcc-6)
* Trying to dkms install falco module with GCC /usr/bin/gcc-5
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/build/make.log (with GCC /usr/bin/gcc-5)
* Trying to load a system falco module, if present
Consider compiling your own falco driver and loading it or getting in touch with the Falco community
Wed Sep 21 06:33:15 2022: Falco version 0.31.1 (driver version b7eb0dd65226a8dc254d228c8d950d07bf3521d2)
Wed Sep 21 06:33:15 2022: Falco initialized with configuration file /etc/falco/falco.yaml
Wed Sep 21 06:33:15 2022: Loading rules from file /etc/falco/falco_rules.yaml:
Wed Sep 21 06:33:15 2022: Loading rules from file /etc/falco/falco_rules.local.yaml:
Wed Sep 21 06:33:16 2022: Unable to load the driver.
Wed Sep 21 06:33:16 2022: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded.. Exiting.

Thank you for the support.

**Comment by jasondellaluce** [comment]
Did you try running the latest Falco v0.32.2? Newest version support many more kernels. We are also releasing Falco 0.33.0 in few weeks if you are interested.

**Comment by navas-gataca** [comment]
Thank you jasondellaluce. 
Finally falco was able to download required kernel driver "https://download.falco.org/driver/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/falco_amazonlinux2_5.4.209-116.367.amzn2.x86_64_1.ko". 
Nevertheless we will try with new falco version as suggested. 
Welcome.
