### ISSUE TITLE
Add new CLI for verifying rules and rule files

### ISSUE THREAD

**Issue by mozillazg** [falcosecurity/falco#2228]
**Motivation**

**Feature**

Add new CLI for verifying rules and rule files. We can use it as a pre-commit tool.

User case:

* Pre-checking rules or rule files before adding them as custom rules. 

Use pre-checking to prevent bad rules from causing Falco to be broken.

**Alternatives**

**Additional context**

**Comment by jasondellaluce** [comment]
@mozillazg, can you expand more on what you mean by "pre-checking"? What are the checks that you foresee being applied?

**Comment by mozillazg** [comment]
@jasondellaluce I'd like to use it to find syntax errors, unknown field errors, and other errors that will cause a rule as an invalid rule:

```
$ falco-rule-validation rule.yaml
found invalid rules:
line 29:  condition: evt.type = execve and evt.dir=< and proc.name in [bash]
                                                                      ^-- syntax error
line 30:  output: shell in a container (user=%user.name shell=%proc.xname cmdline=%proc.cmdline)
                                                               ^--- unknown field

or 
$ falco-rule-validation rule.yaml
found invalid rules:
line 27:
- rule: shell_in_container
  desc: notice shell activity within a container
  condition: condition: evt.type = execve and evt.dir=< and proc.name in [bash]
  output: shell in a container (user=%user.name shell=%proc.xname cmdline=%proc.cmdline)
  priority: WARNING
```

**Comment by jasondellaluce** [comment]
Did you try Falco's `-V` option? Starting from the upcoming Falco 0.33, errors will also be more expressive.

**Comment by mozillazg** [comment]
@jasondellaluce Sorry, I didn't know the `-V` option before. Thanks for your tips.
