### ISSUE TITLE
can't update falco (helm) due to new selectorLabels

### ISSUE THREAD

**Issue by alfredomagallon** [falcosecurity/falco#2231]
**Describe the bug**

When trying to update falco using the helm chart, an error is shown as selectorLabels is an immutable field of the DaemonSet, and update can't continue

**How to reproduce it**

Deploy helm chart 1.19.4, then try to update with 2.0.18

**Expected behaviour**

This options shouldn't be changed, or at least there should be a documented option to configure it in a way that update is working.

**Screenshots**

N/A

**Environment**

- Falco version:
0.32.2 (helm chart 2.0.18)
- System info:
N/A

**Comment by AleksVAnd** [comment]
Since version 2.0.0, the [Helm Charts](https://github.com/falcosecurity/charts/releases) rely on the falco-no-driver image by default and use the driver loader as an init container. From what I understand it is a breaking change. 

Now the workload kind is Deployment, not DeamonSet.

**Comment by alacuku** [comment]
Hi @alfredomagallon, we changed the labels and selectors starting from charts version `2.0.0`. The selector labels are an immutable field, that's causing the `helm upgrade` to fail. You need to uninstall the old version of falco and reinstall it with the new version of the Chats.
