### ISSUE TITLE
RelWithDebInfo build

### ISSUE THREAD

**Issue by happy-dude** [falcosecurity/falco#2268]
**Motivation**

Hey team, I realize that Falco has only "Debug" and "Release" build types.
My team and org were wondering if it was possible to enable a `RelWithDebInfo` build?

RelWithDebInfo builds are usually built with all the performance optimizations of the release build, but with debug symbols turned on. This might be possible with `CPACK_STRIP_FILES=Off` and build type release, but I'm otherwise unfamiliar with the available cmake/cpack build options.

**Feature**

RelWithDebInfo build type; release-optimized, but with debug symbols

**Alternatives**

Possibly `CPACK_STRIP_FILES=Off` ? I need to investigate further if this satisfies the requirements of my team.

**Additional context**

https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#default-and-custom-configurations
^ Does this imply that cmake supports `RelWithDebInfo` by default and will compile + build accordingly?

**Comment by FedeDP** [comment]
Moving to next milestone unless someone wants to tackle this! (in case feel free to move it back to 0.35!) :)
/milestone 0.36.0

**Comment by shane-lawrence** [comment]
I'm trying to debug segfaults on under particular circumstances on very busy nodes and having the debug symbols for a release binary would be very helpful!
