### ISSUE TITLE
Driver for x86_64/falco_cos_5.10.133

### ISSUE THREAD

**Issue by llabake** [falcosecurity/falco#2275]
**Describe the bug**

Falco installation keeps crashing after upgrading Kubernetes cluster to 1.24 

**How to reproduce it**
Launch falco 2.0 helm chart on GKE cluster with COS image type
================ Cleaning phase ================

* Looking for a falco module locally (kernel 5.10.133+)
* Trying to download a prebuilt falco module from https://download.falco.org/driver/2.0.0%2Bdriver/x86_64/falco_cos_5.10.133%2B_1.ko
curl: (22) The requested URL returned error: 404 
Unable to find a prebuilt falco module
* Trying to dkms install falco module with GCC /usr/bin/gcc
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"

Creating symlink /var/lib/dkms/falco/2.0.0+driver/source ->
                 /usr/src/falco-2.0.0+driver

DKMS: add completed.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/2.0.0+driver/build/make.log (with GCC /usr/bin/gcc)
* Trying to dkms install falco module with GCC /usr/bin/gcc-8
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/2.0.0+driver/build/make.log (with GCC /usr/bin/gcc-8)
* Trying to dkms install falco module with GCC /usr/bin/gcc-6
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/2.0.0+driver/build/make.log (with GCC /usr/bin/gcc-6)
* Trying to dkms install falco module with GCC /usr/bin/gcc-5
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/2.0.0+driver/build/make.log (with GCC /usr/bin/gcc-5)
* Trying to load a system falco module, if present
Consider compiling your own falco driver and loading it or getting in touch with the Falco community

**Expected behaviour**
Drivers are found after new ones are compiled.

**Screenshots**
<img width="816" alt="Screenshot 2022-10-26 at 14 15 42" src="https://user-images.githubusercontent.com/29184825/198035664-a93fc76f-4398-4874-8c02-ae04ef9dc7d1.png">

**Environment**

Kubernetes 1.24
- Falco version:
Helm chart version: 2.0.12
- System info:

- Cloud provider or hardware configuration: GCP GKE
- OS:

- Kernel:
 x86_64 x86_64 x86_64 GNU/Linux
- Installation method:
Kubernetes Helm chart

**Additional context**

**Comment by FedeDP** [comment]
Hi!
It seems like it is trying to build the kmod on gke; we only support eBPF there; see https://falco.org/docs/getting-started/third-party/production/#gke.
You need to use:
```
helm install falco falcosecurity/falco --set driver.kind=ebpf
```

Let me know if it works!

**Comment by llabake** [comment]
Thank you @FedeDP, changing the driver to `ebpf` fixed my error.

**Comment by xycloops123** [comment]
hey @FedeDP seems like the link is missing the drivers using `ebpf` as an option also doesnt work now.
<img width="494" alt="Screenshot 2022-12-16 at 4 25 25 AM" src="https://user-images.githubusercontent.com/7406483/208097944-9cccd1aa-3f0a-4da3-ae87-367b170e6e5e.png">

**Comment by alacuku** [comment]
Hi @xycloops123, please open a new issue providing more info about your case since this issue has been solved and closed by the author. Thank you!
