### ISSUE TITLE
CrashLoopBackOff 

### ISSUE THREAD

**Issue by jhailsecurity** [falcosecurity/falco#2276]
When deploying Falco in AWS EKS cluster version 1.23 I get a crashloopbackoff error

[cloudshell-user bin]$ kubectl get pods
NAME             READY   STATUS             RESTARTS       AGE
my-falco-52s5z   0/1     CrashLoopBackOff   10 (6s ago)    26m
my-falco-zl5gk   0/1     CrashLoopBackOff   10 (27s ago)   26m

[cloudshell-user bin]$ kubectl logs my-falco-52s5z
* Setting up /usr/src links from host
* Running falco-driver-loader for: falco version=0.30.0, driver version=3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4
* Running falco-driver-loader with: driver=module, compile=yes, download=yes
* Unloading falco module, if present
* Trying to load a system falco module, if present
* Looking for a falco module locally (kernel 5.4.209-116.367.amzn2.x86_64)
* Trying to download a prebuilt falco module from https://download.falco.org/driver/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/falco_amazonlinux2_5.4.209-116.367.amzn2.x86_64_1.ko
curl: (22) The requested URL returned error: 404 
Unable to find a prebuilt falco module
* Trying to dkms install falco module with GCC /usr/bin/gcc
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/build/make.log (with GCC /usr/bin/gcc)
* Trying to dkms install falco module with GCC /usr/bin/gcc-8
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/build/make.log (with GCC /usr/bin/gcc-8)
* Trying to dkms install falco module with GCC /usr/bin/gcc-6
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/build/make.log (with GCC /usr/bin/gcc-6)
* Trying to dkms install falco module with GCC /usr/bin/gcc-5
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/build/make.log (with GCC /usr/bin/gcc-5)
Consider compiling your own falco driver and loading it or getting in touch with the Falco community
Fri Oct 28 20:14:47 2022: Falco version 0.30.0 (driver version 3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4)
Fri Oct 28 20:14:47 2022: Falco initialized with configuration file /etc/falco/falco.yaml
Fri Oct 28 20:14:47 2022: Loading rules from file /etc/falco/falco_rules.yaml:
Fri Oct 28 20:14:47 2022: Loading rules from file /etc/falco/falco_rules.local.yaml:
Fri Oct 28 20:14:47 2022: Unable to load the driver.
Fri Oct 28 20:14:47 2022: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded.. Exiting.

Containers:
  falco:
    Container ID:  docker://7a7f9f87760625453030c7701eaa4c736ad1ef38de936bdf6184f6b2f9b3e384
    Image:         docker.io/falcosecurity/falco:0.30.0
    Image ID:      docker-pullable://falcosecurity/falco@sha256:a1bfd9b976b16991427a0a646a1ad149cf3a3b29e1a9ecac0d57f3f06e33235c
    Port:          <none>
    Host Port:     <none>
    Args:
      /usr/bin/falco
      --cri
      /run/containerd/containerd.sock
      -K
      /var/run/secrets/kubernetes.io/serviceaccount/token
      -k
      https://$(KUBERNETES_SERVICE_HOST)
      --k8s-node="$(FALCO_K8S_NODE_NAME)"
      -pk
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 28 Oct 2022 20:14:46 +0000
      Finished:     Fri, 28 Oct 2022 20:14:48 +0000
    Ready:          False
    Restart Count:  10
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   512Mi
    Liveness:   http-get http://:8765/healthz delay=60s timeout=5s period=15s #success=1 #failure=3
    Readiness:  http-get http://:8765/healthz delay=30s timeout=5s period=15s #success=1 #failure=3
    Environment:
      FALCO_K8S_NODE_NAME:   (v1:spec.nodeName)
    Mounts:
      /etc/falco from config-volume (rw)
      /host/boot from boot-fs (ro)
      /host/dev from dev-fs (ro)
      /host/etc from etc-fs (ro)
      /host/lib/modules from lib-modules (rw)
      /host/proc from proc-fs (ro)
      /host/run/containerd/containerd.sock from containerd-socket (rw)
      /host/usr from usr-fs (ro)
      /host/var/run/docker.sock from docker-socket (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9jm6n (ro)

**Comment by Andreagit97** [comment]
@jhailsecurity could you try to use the latest Falco release `0.33.0` ? You just need to use the latest helm chart if you are using helm as installation method :)

**Comment by jhailsecurity** [comment]
from what I have found out. if running AWS eks 1.20 then falco 1.16 works but if on aws EKS 1.21 falco 1.16 does not work. we have used falco 2.2 on any cluster that is 1.21 and above and it works.

**Comment by jasondellaluce** [comment]
@jhailsecurity by Falco 2.2 you are referring to the Helm Charts version right? Is your issue solved?

**Comment by jhailsecurity** [comment]
ah yes the helm charts. but the falco version is now 0.33.0 and working fine.

**Comment by jasondellaluce** [comment]
That's good! If this issue is addressed I'd propose to close this. Does that work for you? Waiting for your ack.

**Comment by jhailsecurity** [comment]
yes, thank you .
