### ISSUE TITLE
Protocol "https" not supported or disabled in libcurl

### ISSUE THREAD

**Issue by vamshi05** [falcosecurity/falco#2293]
**Protocol "https" not supported or disabled in libcurl**

**While trying to build falco from source https://falco.org/docs/getting-started/source, 

In step 2 of the doc https://falco.org/docs/getting-started/source/ while running the command `*cmake -DUSE_BUNDLED_DEPS=ON ..*`, I'm noticing the following error after several retries
`build]# cmake -DUSE_BUNDLED_DEPS=ON ..
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type: release
-- Falco version: 0.32.1-286+e3dbae3
-- Libs version: dd443b67c6b04464cb8ee2771af8ada8777e7fac
-- Configuring done
-- Generating done
-- Build files have been written to: /root/falco/build/falcosecurity-libs-repo
Scanning dependencies of target falcosecurity-libs
[ 11%] Creating directories for 'falcosecurity-libs'
[ 22%] Performing download step (download, verify and extract) for 'falcosecurity-libs'
-- Downloading...
   dst='/root/falco/build/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/dd443b67c6b04464cb8ee2771af8ada8777e7fac.tar.gz'
   timeout='none'
-- Using src='https://github.com/falcosecurity/libs/archive/dd443b67c6b04464cb8ee2771af8ada8777e7fac.tar.gz'
-- Retrying...
-- Using src='https://github.com/falcosecurity/libs/archive/dd443b67c6b04464cb8ee2771af8ada8777e7fac.tar.gz'
-- Retry after 5 seconds (attempt #2) ...
-- Using src='https://github.com/falcosecurity/libs/archive/dd443b67c6b04464cb8ee2771af8ada8777e7fac.tar.gz'
-- Retry after 5 seconds (attempt #3) ...
-- Using src='https://github.com/falcosecurity/libs/archive/dd443b67c6b04464cb8ee2771af8ada8777e7fac.tar.gz'
-- Retry after 15 seconds (attempt #4) ...
-- Using src='https://github.com/falcosecurity/libs/archive/dd443b67c6b04464cb8ee2771af8ada8777e7fac.tar.gz'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://github.com/falcosecurity/libs/archive/dd443b67c6b04464cb8ee2771af8ada8777e7fac.tar.gz'
CMake Error at falcosecurity-libs-stamp/download-falcosecurity-libs.cmake:159 (message):
  Each download failed!

    error: downloading 'https://github.com/falcosecurity/libs/archive/dd443b67c6b04464cb8ee2771af8ada8777e7fac.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

         --- LOG END ---
         error: downloading 'https://github.com/falcosecurity/libs/archive/dd443b67c6b04464cb8ee2771af8ada8777e7fac.tar.gz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

`

**Expected behaviour**
`cmake -DUSE_BUNDLED_DEPS=ON ..` to be successful

**Environment**

- Falco version: N/A

- System info:
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Linux version 4.14.296-222.539.amzn2.x86_64

**Additional context**

# cmake --version
cmake version 3.12.3

libcurl-7.79.1-6.amzn2.0.1.x86_64

# curl --version
curl 7.79.1 (x86_64-koji-linux-gnu) libcurl/7.79.1 OpenSSL/1.0.2k-fips zlib/1.2.7 libidn2/2.3.0 libssh2/1.4.3 nghttp2/1.41.0 OpenLDAP/2.4.44
Release-Date: 2021-09-22
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL UnixSockets

**Comment by Andreagit97** [comment]
ei @vamshi05 this is quite strange, we use it almost every day, it seems due to the CMake version `CMake version 3.12.3`, try to use CMake `3.22.5` for example or something greater, this should solve the issue :thinking:

**Comment by vamshi05** [comment]
Thanks @Andreagit97 . I got past this issue using cmake version `3.22.5` . Although the doc says the minimum required one is `3.5.1` https://github.com/falcosecurity/falco/blob/master/CMakeLists.txt#L13

**Comment by Andreagit97** [comment]
thank you for reporting this :)
