### ISSUE TITLE
Broken link on k8s_audit_config/README.md

### ISSUE THREAD

**Issue by haugom** [falcosecurity/falco#2297]
[this](https://falco.org/docs/event-sources/kubernetes-audit/#enabling-kubernetes-audit-logs) page has a broken link to

[examle files](https://github.com/falcosecurity/evolution/blob/master/examples/k8s_audit_config/README.md)

Could it please be updated?

**Comment by alacuku** [comment]
Hi @haugom, will fix the broken link. 

In the meantime here you will find step by step guide on how to enable the `audit logs` in minikube and deploy Falco: https://falco.org/docs/getting-started/third-party/learning/#falco-with-multiple-sources.

Thanks!

**Comment by haugom** [comment]
thanks for the fix and link!
