### ISSUE TITLE
Falco monitors container behavior

### ISSUE THREAD

**Issue by Liam929** [falcosecurity/falco#2308]
**Motivation**

I wonder if falco can monitor the behavior inside a pod.
For example ,given a mysql pod and a falco pod in the kubernetes cluster,if I enter a sql statement in the mysql pod,could falco detect this operation and output the corresponding logs?  @sporkmonger @gnosek

**Comment by jasondellaluce** [comment]
Your question is simple but the response is quite articulate.

Falco is able to monitor process activity inside a pod and containers, but it has to be installed in the same node as where the given pod/container is running. This is why we need to install Falco as a DaemonSet in Kubernetes for node-level security.

Falco monitors the communication between processes and the underlying Linux kernel, meaning that it sees and inspects every system call executed. MySQL is not an exception, however, looking at syscalls would not give you specific insights about SQL statements execution or logs. In other words, syscalls provide tons of information about the behavior of a process but is not natively built to consume application-specific data.

This being said, what you described can be implemented with the plugin system. For example you could implement a plugin that consumes MySQL logs, deploying an instance of Falco configured with your plugin on Kubernetes as a Deployment alongside your MySQL installation, and let it consume the logs. That will be come a totally different event source for Falco, with MySQL-specific events and security rules. This is not something we have right now, but it is something that could be useful for many folks. Inspecting database logging activity is a good source of truth for security purposes in general.

**Comment by Liam929** [comment]
@jasondellaluce 
I see what you mean, and your advice provides me with a great direction. But I am not familiar with the plug-in falco, would you mind citing some documentations in this github repository or other tutorials that I can refer to to learn the falco plugin system?

**Comment by jasondellaluce** [comment]
The official documentation is in the website: https://falco.org/docs/plugins/.
Here's an SDK to write plugins in Go, with examples: https://github.com/falcosecurity/plugin-sdk-go.
And here you can find the official plugins, that may be good food for thought: https://github.com/falcosecurity/plugins (we left some best practices docs there too: https://github.com/falcosecurity/plugins/tree/master/docs)

**Comment by JasonBourne1998** [comment]
@jasondellaluce  Hi, Regarding this type of container detection, can we just pass the container/pod logs directly to falco like K8s audit logs?
For K8s-Audit, we could use the kubeconfig to transfer the Audit Logs to falco:
$ cat <<EOF > /etc/kubernetes/audit-webhook-kubeconfig
apiVersion: v1
kind: Config
clusters:
- cluster:
    server: http://<ip_of_falco>:8765/k8s_audit
  name: falco
contexts:
- context:
    cluster: falco
    user: ""
  name: default-context
current-context: default-context
preferences: {}
users: []
EOF

Can we reproduce this in the docker container or k8s pod logs? Thanks in advance.

**Comment by jasondellaluce** [comment]
@JasonBourne1998 Not sure how that solves the general problem, because in that case we'd need to add logic for processing the pod log entries which are not guaranteed to follow a specific schema. In any case, that's something attainable by developing a plugin.
