### ISSUE TITLE
[Request] add editorconfig to automatically configure editors w/ coding standards

### ISSUE THREAD

**Issue by happy-dude** [falcosecurity/falco#2323]
**Motivation**

Encountered this while editing a `.cpp` file and realized that my editor indented via spaces instead of tabs like the rest of the file.

Instead of messing with settings locally, set up an `.editorconfig` for the repo to automatically set settings for specific filetypes.

From the [EditorConfig](https://editorconfig.org/) website:

> What is EditorConfig?
> EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.

Here are a few examples:
* https://github.com/neovim/neovim/blob/master/.editorconfig
* https://github.com/editorconfig/editorconfig-core-c/blob/master/.editorconfig

**Feature**

`.editorconfig` placed at the top-level of the repo to help automatically configure editors/IDEs that understand the settings.

**Comment by jasondellaluce** [comment]
I would say this is related to https://github.com/falcosecurity/libs/issues/381. Once we have a defined standard, then automatic formatters can be run on the code and solve most of these issues.
