### ISSUE TITLE
falco-driver-loader: curl hangs forever and couldn't fallback to `compile` in air-gapped envrionment

### ISSUE THREAD

**Issue by Dentrax** [falcosecurity/falco#2334]
**Describe the bug**

In air-gapped environment, `falco-driver-loader` couldn't access the `falco.org` and hangs forever in the following state:

```
Trying to download a prebuilt falco module from https://download.falco.org/driver/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/falco_ubuntu-generic_5.11.0-38-generic_42.ko
```

It'd be great to pass hardcoded `--connect-timeout` and `--max-time` flags into [FALCO_DRIVER_CURL_OPTIONS](https://github.com/falcosecurity/falco/blob/decabbc519f6a35f1a43d65dbb390d3e2be3c0b3/scripts/falco-driver-loader#L666).

I think that's because:
>  if the connect succeeds then curl seems to wait forever for a response.

I have also tested this case by issuing `$ curl falco.org` on the node; it seems it hangs forever, and doesn't exits.

Ref: https://unix.stackexchange.com/a/94612/300614

**How to reproduce it**

Run `falco` in air-gapped environment with driver-loader `download=true` and `compile=true`.

**Expected behaviour**

It should fallback to compile stage after the given timeout is exceeded. (Like how it behaves if we get 404.)

**Screenshots**

`-`

**Environment**

- Falco version:
```
Falco version: 0.30.0
Driver version: 3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4
```
- System info:

- Cloud provider or hardware configuration:
- OS:
```
20.04.2 LTS
```
- Kernel:
```
Linux REDACTED 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Installation method:
```
Kubernetes
```

**Additional context**

`-`

/cc @developer-guy @ugur99 @yasintahaerol

**Comment by FedeDP** [comment]
Hi! Next Falco release (0.34) will ship a falco-driver-loader with an option to add custom curl options, see #1901 .

It should solve this issue.

**Comment by Dentrax** [comment]
Yep, already saw! I thought maybe we can pass these additional timeout flags to `FALCO_DRIVER_CURL_OPTIONS=-fsS` environment by default. (without having to pass to _custom curl options_.) Which would resulting in a better UX.

**Comment by FedeDP** [comment]
Yep i think a patch in that direction is welcomed :) Can you open it?
@leogr

**Comment by Dentrax** [comment]
Yep! I can submit a PR once we agree on the best values of `--connect-timeout` and `--max-time` flags.

**Comment by leogr** [comment]
/milestone 0.34.0

I think this is very important. @Dentrax let we know if you need any support :)
And thank you for taking care of this :pray: 

cc @jasondellaluce @Andreagit97
