### ISSUE TITLE
[docs website] - Hint that k8s.pod.name and k8s.ns.name work with CRI socket only, no need for k8s plugin

### ISSUE THREAD

**Issue by incertum** [falcosecurity/falco#2335]
**What to document**

Proposal to improve https://falco.org/docs/reference/rules/supported-fields/. Hint that `k8s.pod.name` and `k8s.ns.name` work with CRI socket only, no need for k8s plugin. Place these hints under both `Field Class: k8s` and `Field Class: container` sections, especially under the container one.

@leogr before you shared this secret with me I was not aware of it, perhaps more end users may benefit from such an explicit hint on the website.

**Comment by leogr** [comment]
Although I tried to explain that [here](https://falco.org/docs/reference/rules/supported-fields/#field-class-k8s) :point_down: 
![Screenshot from 2022-12-22 16-45-18](https://user-images.githubusercontent.com/3390997/209171134-c3caa623-277a-4ae7-b4c1-8967082b940e.png)

I agree it's too hidden and too cryptic :sweat_smile: 
Making it explicit and more visible would be a great improvement! :+1: 

cc @vjjmiras

**Comment by incertum** [comment]
Maybe use some style similar to below to make the hints also visually more obvious especially under the `container` fields section?

<img width="746" alt="Screenshot 2022-12-22 at 9 15 30 AM" src="https://user-images.githubusercontent.com/24579375/209190217-e04bcb84-47d5-49d1-b780-eaf7213c8e44.png">

**Comment by vjjmiras** [comment]
I did my best trying to clarify it: https://github.com/falcosecurity/falco-website/pull/781
