### ISSUE TITLE
-DBUILD_FALCO_MODERN_BPF=True fail to build on Debian 11 Bullseye (error: use of unknown builtin '__builtin_preserve_enum_value')

### ISSUE THREAD

**Issue by petterreinholdtsen** [falcosecurity/falco#2343]
**Describe the bug**

I'm trying to build falco with -DBUILD_FALCO_MODERN_BPF=True to test the new BPF module, and the build fail.

**How to reproduce it**

Configure using -DBUILD_BPF=True -DBUILD_FALCO_MODERN_BPF=True and build on Debian 11.

The build rules and code I use to test is available from https://salsa.debian.org/pere/falco.git .  Check out the code and run 'gbp buildpackage' to test.

**Expected behaviour**

Hoped the build would run to completion.

**Screenshots**

This is the build error I get, only including the first few, as the list is very long:

```
/uio/kant/usit-gid-u1/pre/src/falco/obj-x86_64-linux-gnu/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/driver/modern_bpf/helpers/base/read_from_task.h:18:5: error: use of unknown builtin '__builtin_preserve_enum_value' [-Wimplicit-function-declaration]
        if(bpf_core_enum_value_exists(enum bpf_func_id, BPF_FUNC_get_current_task_btf))
           ^
/usr/include/bpf/bpf_core_read.h:168:2: note: expanded from macro 'bpf_core_enum_value_exists'
        __builtin_preserve_enum_value(*(typeof(enum_type) *)enum_value, BPF_ENUMVAL_EXISTS)
        ^
In file included from /uio/kant/usit-gid-u1/pre/src/falco/obj-x86_64-linux-gnu/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/vfork.bpf.c:8:
In file included from /uio/kant/usit-gid-u1/pre/src/falco/obj-x86_64-linux-gnu/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/driver/modern_bpf/helpers/interfaces/fixed_size_event.h:11:
In file included from /uio/kant/usit-gid-u1/pre/src/falco/obj-x86_64-linux-gnu/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/driver/modern_bpf/helpers/store/ringbuf_store_params.h:11:
In file included from /uio/kant/usit-gid-u1/pre/src/falco/obj-x86_64-linux-gnu/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/driver/modern_bpf/helpers/extract/extract_from_kernel.h:12:
/uio/kant/usit-gid-u1/pre/src/falco/obj-x86_64-linux-gnu/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/driver/ppm_flag_helpers.h:123:27: error: function-like macro 'KERNEL_VERSION' is not defined
#if LINUX_VERSION_CODE >= KERNEL_VERSION(3, 11, 0)
                          ^
In file included from /uio/kant/usit-gid-u1/pre/src/falco/obj-x86_64-linux-gnu/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/vfork.bpf.c:8:
In file included from /uio/kant/usit-gid-u1/pre/src/falco/obj-x86_64-linux-gnu/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/driver/modern_bpf/helpers/interfaces/fixed_size_event.h:11:
In file included from /uio/kant/usit-gid-u1/pre/src/falco/obj-x86_64-linux-gnu/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/driver/modern_bpf/helpers/store/ringbuf_store_params.h:11:
/uio/kant/usit-gid-u1/pre/src/falco/obj-x86_64-linux-gnu/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/driver/modern_bpf/helpers/extract/extract_from_kernel.h:47:9: warning: implicit declaration of function 'PT_REGS_PARM1_CORE_SYSCALL' is invalid in C99 [-Wimplicit-function-declaration]
                arg = PT_REGS_PARM1_CORE_SYSCALL(regs);
                      ^
/uio/kant/usit-gid-u1/pre/src/falco/obj-x86_64-linux-gnu/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/driver/modern_bpf/helpers/extract/extract_from_kernel.h:50:9: warning: implicit declaration of function 'PT_REGS_PARM2_CORE_SYSCALL' is invalid in C99 [-Wimplicit-function-declaration]
                arg = PT_REGS_PARM2_CORE_SYSCALL(regs);
                      ^
/uio/kant/usit-gid-u1/pre/src/falco/obj-x86_64-linux-gnu/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/driver/modern_bpf/helpers/extract/extract_from_kernel.h:53:9: warning: implicit declaration of function 'PT_REGS_PARM3_CORE_SYSCALL' is invalid in C99 [-Wimplicit-function-declaration]
                arg = PT_REGS_PARM3_CORE_SYSCALL(regs);
                      ^
/uio/kant/usit-gid-u1/pre/src/falco/obj-x86_64-linux-gnu/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/driver/modern_bpf/helpers/extract/extract_from_kernel.h:56:9: warning: implicit declaration of function 'PT_REGS_PARM4_CORE_SYSCALL' is invalid in C99 [-Wimplicit-function-declaration]
                arg = PT_REGS_PARM4_CORE_SYSCALL(regs);
                      ^
/uio/kant/usit-gid-u1/pre/src/falco/obj-x86_64-linux-gnu/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/driver/modern_bpf/helpers/extract/extract_from_kernel.h:59:9: warning: implicit declaration of function 'PT_REGS_PARM5_CORE_SYSCALL' is invalid in C99 [-Wimplicit-function-declaration]
                arg = PT_REGS_PARM5_CORE_SYSCALL(regs);
                      ^
/uio/kant/usit-gid-u1/pre/src/falco/obj-x86_64-linux-gnu/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/driver/modern_bpf/helpers/extract/extract_from_kernel.h:63:9: warning: implicit declaration of function '__PT_REGS_CAST' is invalid in C99 [-Wimplicit-function-declaration]
                arg = PT_REGS_PARM6_CORE_SYSCALL(regs);
                      ^
/uio/kant/usit-gid-u1/pre/src/falco/obj-x86_64-linux-gnu/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/driver/modern_bpf/helpers/base/common.h:31:39: note: expanded from macro 'PT_REGS_PARM6_CORE_SYSCALL'
#define PT_REGS_PARM6_CORE_SYSCALL(x) PT_REGS_PARM6_CORE(x)
                                      ^
/uio/kant/usit-gid-u1/pre/src/falco/obj-x86_64-linux-gnu/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/driver/modern_bpf/helpers/base/common.h:30:45: note: expanded from macro 'PT_REGS_PARM6_CORE'
#define PT_REGS_PARM6_CORE(x) BPF_CORE_READ(__PT_REGS_CAST(x), __PT_PARM6_REG)
                                            ^
In file included from /uio/kant/usit-gid-u1/pre/src/falco/obj-x86_64-linux-gnu/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/vfork.bpf.c:8:
In file included from /uio/kant/usit-gid-u1/pre/src/falco/obj-x86_64-linux-gnu/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/driver/modern_bpf/helpers/interfaces/fixed_size_event.h:11:
In file included from /uio/kant/usit-gid-u1/pre/src/falco/obj-x86_64-linux-gnu/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/driver/modern_bpf/helpers/store/ringbuf_store_params.h:11:
/uio/kant/usit-gid-u1/pre/src/falco/obj-x86_64-linux-gnu/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/driver/modern_bpf/helpers/extract/extract_from_kernel.h:63:9: error: member reference type 'int' is not a pointer
                arg = PT_REGS_PARM6_CORE_SYSCALL(regs);
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Environment**

- Falco version: 0.33.1
- System info: Debian 11 Bullseye on amd64
- Kernel: Linux 5.10.0-16-amd64
- Installation method: tarball from github

**Comment by Andreagit97** [comment]
Ei @petterreinholdtsen thank you for trying it! This issue is probably due to the fact that you are using a too lower `clang` version. Usually `clang.12` should be enough... These are the requirement to build the modern bpf probe https://github.com/falcosecurity/libs#build-modern-ebpf-probe

**Comment by Andreagit97** [comment]
The good news is that Falco `0.34` (which will be released at the end of January) will ship the modern BPF probe as an experimental feature so you will be able to run it with Falco without compiling it manually :)

**Comment by petterreinholdtsen** [comment]
[Andrea Terzolo]
> Ei @petterreinholdtsen thank you for trying it! This issue is probably
> due to the fact that you are using a too lower `clang`
> version. Usually `clang.12` should be enough... These are the
> requirement to build the modern bpf probe
> https://github.com/falcosecurity/libs#build-modern-ebpf-probe

Aha.  Then I guess cmake should look for and report an error if clang
version is below 12.  I got 11.0.1-2, according to my 'clang --version'.
Will try again with a newer version.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by Andreagit97** [comment]
> Aha. Then I guess cmake should look for and report an error if clang version is below 12

That's a good point we need to improve it :)

**Comment by petterreinholdtsen** [comment]
I tried to install clang 13 and configure using CC=clang-13
CXX=clang++-13 set in environment, but these compiler names did not seem
to be picked up by cmake.  I also tried cmake arguments
-DCMAKE_C_COMPILER=clang-13 -DCMAKE_CXX_COMPILER=clang++-13, which did
not work either, the build is still using the 'g++' and 'clang' names.

What is the supported way to do change the compiler names?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by Andreagit97** [comment]
yeah right now the cmake part is quite rude, we have many different compilers required around the repo, sorry for that :( 
What I usually do is to change the clang compilers through the alternatives

```bash
            sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-14 90
            sudo update-alternatives --install /usr/bin/llvm-strip llvm-strip /usr/bin/llvm-strip-14 90
```

This is an example of how we build Falco with the modern probe in our CI if it could be useful https://github.com/falcosecurity/falco/blob/master/.circleci/config.yml#L11-L42
We use a base Ubuntu 22.04 machine to compile the modern bpf probe and then we pass the bpf skeleton into a centos7 container to build the Falco executable with an old Glibc version

**Comment by petterreinholdtsen** [comment]
[Andrea Terzolo]
> yeah right now the cmake part is quite rude, we have many different
> compilers required around the repo, sorry for that :(

I imagine this make cross compiling quite hard, and hope this can be
changed to respect the CC and CXX environment variables instead.

> What I usually do is to change the clang compilers through the
> alternatives

This mess up the 'clang' package which already proivde the symlinks in
question, and is not a great setup for machine used for other builds as
well.

But it did manage to build the bpf module. Sadly I ran into another
compiler mismatch issue:

llc: error: llc:
/home/user/src/falco/obj-x86_64-linux-gnu/driver-repo/driver-prefix/src/driver/bpf/probe.ll:
error: Unknown attribute kind (70) (Producer: 'LLVM13.0.1' Reader: 'LLVM
11.0.1')


-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
[Andrea Terzolo]
> this is the full script I use to update all the versions of clang/llvm
> tools:

Thank you.  Amazing amount of workaround for the projects inability to
adjust the cmake build rules. :)

I tested building the latest git master repo in a Debian Bookworm
chroot, which clang 14, and the build still fail:

[  2%] Built target tbb
[  4%] Built target b64
[  6%] Built target valijson
[  7%] Built target re2
[  9%] Built target njson
[ 11%] Built target cpp-httplib
[ 12%] Built target cxxopts
[ 14%] Built target k8saudit-plugin
[ 16%] Built target k8saudit-rules
[ 17%] Built target cloudtrail-plugin
[ 19%] Built target cloudtrail-rules
[ 20%] Built target json-plugin
make[4]: *** /lib/modules/5.10.0-16-amd64/build: No such file or directory.  Stop.
make[3]: *** [Makefile:16: all] Error 2
make[2]: *** [driver/CMakeFiles/driver.dir/build.make:70: driver/CMakeFiles/driver] Error 2
make[1]: *** [CMakeFiles/Makefile2:1045: driver/CMakeFiles/driver.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

-- 
Happy hacking
Petter Reinholdtsen

**Comment by FedeDP** [comment]
> make[4]: *** /lib/modules/5.10.0-16-amd64/build: No such file or directory.  Stop.
make[3]: *** [Makefile:16: all] Error 2
make[2]: *** [driver/CMakeFiles/driver.dir/build.make:70: driver/CMakeFiles/driver] Error 2
make[1]: *** [CMakeFiles/Makefile2:1045: driver/CMakeFiles/driver.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

Do you have kernel headers package installed?

**Comment by Andreagit97** [comment]
This is not related to the modern probe, it seems you are trying to build Falco with the kernel mod or bpf build enabled. Could you provide some more info on how you are trying to build Falco?

**Comment by petterreinholdtsen** [comment]
[Federico Di Pierro]
> Do you have kernel headers package installed?

There are no header package for 5.10.0-16 in Debian Bookworm. :/

[Andrea Terzolo]
> This is not related to the modern probe, it seems you are trying to
> build Falco with the kernel mod or bpf build enabled. Could you
> provide some more info on how you are trying to build Falco?

I build a Bookworm chroot on Bullseye using 'debootstrap bookworm
chroot-bookworm-falco'.  Then I chroot into this directory using 'chroot
chroot-bookworm-falco' and install some basic tools (apt install
devscripts git git-buildpackage), move to /root/ and fetch the source
including Debian package build rules using 'gbp clone
https://salsa.debian.org/pere/falco.git', chroot into this directory and
install build dependencies using 'apt build-dep .' and finally try to
build the source using 'gbp buildpackage'.  The latter will run cmake
using -DBUILD_BPF=True and -DBUILD_FALCO_MODERN_BPF=True.  Tried with
BUILD_BPF=False too, but did not make much difference.

This problem seem to be that the build system assume the currently
running kernels source is available, which is not a good assumtion.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by Andreagit97** [comment]
Uhm the kernel module is our default driver so unless you tell CMake to avoid the compilation I will try to build also it. You should also pass to the CMake command the following option `-DBUILD_DRIVER=Off`

A good cmake run could be:

```bash
cmake  -DBUILD_BPF=Off  -DBUILD_DRIVER=Off -DUSE_BUNDLED_DEPS=On -DCREATE_TEST_TARGETS=Off -DBUILD_FALCO_MODERN_BPF=ON ..
make falco
```

BTW if you want to build the modern probe with Falco just to try it, I suggest you to use the dev packages provided by our CI.  [Here](https://app.circleci.com/pipelines/github/falcosecurity/falco/3562/workflows/8afb4089-2e2c-49be-89e9-195b86ff462a/jobs/30614/artifacts) you have `deb` and `tar` packages for `x86` architecture. For sure it would be less painful than a Falco local build with all its options... if you need to build it from source for other reasons we are happy to help you in doing this :)

**Comment by Andreagit97** [comment]
You can also find a blog post that shows you different ways of testing the modern probe :)  https://falco.org/blog/falco-modern-bpf/

**Comment by Andreagit97** [comment]
> Thank you.  This got the build limping along.  Is there a important difference between On/Off and True/False?

No, there is no difference, you can use what you prefer

> [ 41%] [bpftool]  Building BPF unique object file: /root/src/falco-upstream/build/driver/modern_bpf/bpf_probe.o
/bin/sh: 1: BPFTOOL_EXE-NOTFOUND: not found
make[2]: *** [driver/modern_bpf/CMakeFiles/ProbeSkeleton.dir/build.make:162: driver/modern_bpf/bpf_probe.o] Error 127

yeah BPFTOOL is another requirement to build a unique `.o` file and then the modern bpf probe skeleton (https://github.com/falcosecurity/libs#build-modern-ebpf-probe). If the distro doesn't provide a recent version of the BPFTOOL you need to build it from source: https://github.com/libbpf/bpftool/releases/tag/v6.7.0 and these are the instruction to install it https://github.com/libbpf/bpftool/tree/v6.7.0#build

> My goal at the moment is to try to explore and improve the build system
to a point where one in the future do not have to depend on binaries
downloaded from the Internet, and preferably also assist in making the
build reproducable to increase confidence in any binaries used.

> I would also like to help improve the build system to get it to a point
where it could be accepted into Debian.

Wow, it would be amazing!

**Comment by petterreinholdtsen** [comment]
[Andrea Terzolo]
> yeah BPFTOOL is another requirement to build a unique `.o` file and
> then the modern bpf probe skeleton
> (https://github.com/falcosecurity/libs#build-modern-ebpf-probe).

Right, so another hard dependency not enforced by cmake. :(

Got a bit further, next problem is this one...

[ 84%] Generate gRPC API
google/protobuf/timestamp.proto: File not found.
outputs.proto:19:1: Import "google/protobuf/timestamp.proto" was not found or had errors.
outputs.proto:46:3: "google.protobuf.Timestamp" is not defined.
make[2]: *** [userspace/falco/CMakeFiles/falco.dir/build.make:77: userspace/falco/version.grpc.pb.cc] Error 1
make[2]: *** Deleting file 'userspace/falco/version.grpc.pb.cc'
make[1]: *** [CMakeFiles/Makefile2:2263: userspace/falco/CMakeFiles/falco.dir/all] Error 2

> If the distro doesn't provide a recent version of the BPFTOOL you need
> to build it from source:
> https://github.com/libbpf/bpftool/releases/tag/v6.7.0 and these are
> the instruction to install it
> https://github.com/libbpf/bpftool/tree/v6.7.0#build

Version 7.0 seem to be available in Debian Bookworm,
<URL: https://packages.debian.org/testing/bpftool >.

> Wow, it would be amazing!

Given the current state, I agree.  Hopefully the developers can improve
the situation a bit and get us closer to this goal. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by Andreagit97** [comment]
Uhm that is really strange, I've tried these commands on a `debian:bookworm` docker container and it compiles without issues :thinking: 

```bash
apt update
apt install git cmake make build-essential clang-14 libelf-dev bpftool llvm-14
update-alternatives --install /usr/bin/clang clang /usr/bin/clang-14 90
update-alternatives --install /usr/bin/llvm-strip llvm-strip /usr/bin/llvm-strip-14 90
cmake -DBUILD_BPF=Off -DBUILD_DRIVER=Off -DUSE_BUNDLED_DEPS=On -DCREATE_TEST_TARGETS=Off -DBUILD_FALCO_MODERN_BPF=ON ..
make falco
```

**Comment by petterreinholdtsen** [comment]
[Andrea Terzolo]
> Uhm that is really strange, I've tried these commands on a
> `debian:bookworm` docker container and it compiles without issues
> :thinking:

Somehow -I/usr/include is missing from this command:

  cd /root/src/falco-upstream/build/userspace/falco && /usr/bin/protoc \
  -I /root/src/falco-upstream/userspace/falco \
  --cpp_out=. /root/src/falco-upstream/userspace/falco/outputs.proto \
  /root/src/falco-upstream/userspace/falco/schema.proto

If I add it, the command is successful.  The file requested is in the
libprotobuf-dev package under /usr/include/.

I guess cmake failed to understand his include path was needed.  It is
unclear to me where to add it.  The
userspace/falco/CMakeFiles/falco.dir/build.make file do not have the -I
statement in a variable, so I am unsure how to track down the
problematic cmake rule.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
[Petter Reinholdtsen]
> If I add it, the command is successful.  The file requested is in the
> libprotobuf-dev package under /usr/include/.

Not quite sure if it is the correct approach, but with this patch I
managed to run the build to completion.  I configure like this:

  mkdir build && cd build && \
    cmake -DBUILD_BPF=False -DBUILD_DRIVER=False -DUSE_BUNDLED_DEPS=True \
    -DCREATE_TEST_TARGETS=False -DBUILD_FALCO_MODERN_BPF=True ..

diff --git a/userspace/falco/CMakeLists.txt b/userspace/falco/CMakeLists.txt
index 8db16d39..617bdfeb 100644
--- a/userspace/falco/CMakeLists.txt
+++ b/userspace/falco/CMakeLists.txt
@@ -180,14 +180,14 @@ if(NOT MINIMAL_BUILD)
     COMMENT "Generate gRPC API"
     # Falco gRPC Version API
     DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/version.proto
-    COMMAND ${PROTOC} -I ${CMAKE_CURRENT_SOURCE_DIR} --cpp_out=. ${CMAKE_CURRENT_SOURCE_DIR}/version.proto
-    COMMAND ${PROTOC} -I ${CMAKE_CURRENT_SOURCE_DIR} --grpc_out=. --plugin=protoc-gen-grpc=${GRPC_CPP_PLUGIN}
+    COMMAND ${PROTOC} -I/usr/include -I ${CMAKE_CURRENT_SOURCE_DIR} --cpp_out=. ${CMAKE_CURRENT_SOURCE_DIR}/version.proto
+    COMMAND ${PROTOC} -I/usr/include -I ${CMAKE_CURRENT_SOURCE_DIR} --grpc_out=. --plugin=protoc-gen-grpc=${GRPC_CPP_PLUGIN}
     ${CMAKE_CURRENT_SOURCE_DIR}/version.proto
     # Falco gRPC Outputs API
     DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/outputs.proto
-    COMMAND ${PROTOC} -I ${CMAKE_CURRENT_SOURCE_DIR} --cpp_out=. ${CMAKE_CURRENT_SOURCE_DIR}/outputs.proto
+    COMMAND ${PROTOC} -I/usr/include -I ${CMAKE_CURRENT_SOURCE_DIR} --cpp_out=. ${CMAKE_CURRENT_SOURCE_DIR}/outputs.proto
     ${CMAKE_CURRENT_SOURCE_DIR}/schema.proto
-    COMMAND ${PROTOC} -I ${CMAKE_CURRENT_SOURCE_DIR} --grpc_out=. --plugin=protoc-gen-grpc=${GRPC_CPP_PLUGIN}
+    COMMAND ${PROTOC} -I/usr/include -I ${CMAKE_CURRENT_SOURCE_DIR} --grpc_out=. --plugin=protoc-gen-grpc=${GRPC_CPP_PLUGIN}
     ${CMAKE_CURRENT_SOURCE_DIR}/outputs.proto
     WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
   )

-- 
Happy hacking
Petter Reinholdtsen

**Comment by Andreagit97** [comment]
this seems good! Would you mind opening a PR for that?

**Comment by petterreinholdtsen** [comment]
[Andrea Terzolo]
> this seems good! Would you mind opening a PR for that?

Done. <URL: https://github.com/falcosecurity/falco/pull/2349 >.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by incertum** [comment]
@petterreinholdtsen ran into some of what you describe as well. Shared my experience and internal CI here in case it's of interest to you: https://github.com/falcosecurity/falco/issues/2366#issuecomment-1406903498
