### ISSUE TITLE
Only specific rules will be send an Alert

### ISSUE THREAD

**Issue by ariretiarno** [falcosecurity/falco#2360]
**Motivation**

Currently, alerting on Falco is Global Alert, so anything on rules will be alert on 1 Slack Channel.

**Feature**

Only specific rules will be sending an Alert. And the other Rules will be kept on Falco sidekick UI

**Alternatives**

**Additional context**

**Comment by jasondellaluce** [comment]
@ariretiarno I think this issue is mostly suitable for the Falcosidekick repository.
