### ISSUE TITLE
Cut 0.34.0 Release

### ISSUE THREAD

**Issue by LucaGuerra** [falcosecurity/falco#2368]
# Falco 0.34.0 Release

During the community call of 2023-01-11 I proposed myself as a release manager.
Will keep this issue updated with the current status and progress.

## Date

Release date: 2023-02-07

## Current Status

- [x] Code freeze in falcosecurity/libs : version 0.10.x
- [x] Code thaw in falcosecurity/libs
- [x] Release libs v0.10.x  
      - https://github.com/falcosecurity/libs/releases/tag/0.10.3
- [x] Release drivers v4.x.x 
      - https://github.com/falcosecurity/libs/releases/tag/4.0.0%2Bdriver
- [x] Code freeze in falcosecurity/falco
- [x] Open release branch in Falco
- [x] Code thaw in falcosecurity/falco
- [x] Release Falco v0.34.0

## Release Steps

Process is described in [this document](https://github.com/falcosecurity/falco/blob/master/RELEASE.md).

## Release Blocking PRs

If a PR for a specific issue doesn't exist yet I'll link the issue and change it to PR afterwards

* https://github.com/falcosecurity/falco/pull/2345
* https://github.com/falcosecurity/falcoctl/pull/237
* https://github.com/falcosecurity/falco/pull/2386
* https://github.com/falcosecurity/falco/pull/2390
* https://github.com/falcosecurity/falco/pull/2391
* https://github.com/falcosecurity/falcoctl/pull/251
* https://github.com/falcosecurity/falco/pull/2406

## Manual Testing Action Items

- [x] Running Falco on Kubernetes with the official Helm Charts
- [x] Running Falco from RPM and DEB artifacts
- [x] Running Falco in a container with the official images
- [x] Running/fuzzing Falco with multiple event sources active in parallel
- [x] Running/fuzzing Falco with variable syscall buffer dimension
- [x] Running Falco in all officially-supported architectures (x86_64, ARM64)
- [x] Running Falco with the supported drivers (kmod, modern eBPF, eBPF, gVisor, trace files)
- [x] Test Falco with event generator
- [x] Test that plugins are correctly loaded
- [x] Test memory and CPU usage (with Valgrind and other tools)
- [x] Test latest version of driver loader
- [x] Test that k8s metadata enrichment client works as expected
- [x] Test that all Falco CLI options work as expected
- [x] Check that Falco log messages are correct and consistent
- [x] Test that Falco ruleset loading and validation works as expected

## Action Items

- [x] **Pre-Release**
  - [x]  Milestone: https://github.com/falcosecurity/falco/milestone/27
  - [x] Sync with new falcosecurity/libs release v0.10.3
  - [x] Sync with new falcosecurity/libs driver release 4.0.0
  - [x] Release plugins
  - [x] Prebuilt drivers publish
  - [x] Changelog
- [x] **Release**
  - [x] Tag
  - [x] Github Release
- [x] **Website**
  - [x] Create 0.33 snapshot
    - [x] Protect snapshot branch
  - [x] Add Systemd instructions https://github.com/falcosecurity/falco-website/pull/799
  - [x] Add modern eBPF probe instructions https://github.com/falcosecurity/falco-website/pull/800
- [x] **Helm**
  - [x] Update helm charts https://github.com/falcosecurity/charts/pull/453
- [x] **Announcements**
  - [x] mailing list 
  - [x] blog post https://github.com/falcosecurity/falco-website/pull/802
  - [x] slack channel
- [x] **Post-Release**
  - [x] Update helm chart value documentation https://github.com/falcosecurity/charts/pull/453/commits/6a8cd4c880bb78f27880e1ae88e29e2dfefc965a
  - [x] Update supported fields and syscall documentation https://github.com/falcosecurity/falco-website/pull/810
  - [x] Archive community call meeting notes https://github.com/falcosecurity/community/pull/163

## Miscs

/milestone 0.34.0

/assign @LucaGuerra 

/kind documentation

**Comment by FedeDP** [comment]
We already have:
* 0.10.1 libs tag: https://github.com/falcosecurity/libs/releases/tag/0.10.1
* 4.0.0+driver libs tag: https://github.com/falcosecurity/libs/releases/tag/4.0.0%2Bdriver
* 4.0.0 drivers built and uploaded on download.falco.org: https://download.falco.org/driver/site/index.html?lib=4.0.0%2Bdriver&target=amazonlinux2&arch=x86_64&kind=ebpf

**Comment by Andreagit97** [comment]
Documentation:
- systemd:  https://github.com/falcosecurity/falco-website/pull/799
- modern bpf: https://github.com/falcosecurity/falco-website/pull/800

**Comment by Andreagit97** [comment]
we will tag a `0.10.3` with these new patches https://github.com/falcosecurity/libs/pull/850

**Comment by LucaGuerra** [comment]
We're going to be a couple days late to wrap up tests and the final version of falcoctl!

**Comment by leogr** [comment]
We must evaluate if we want this :point_down: to happen before the release.
https://github.com/falcosecurity/charts/pull/453#pullrequestreview-1283565182

Other than that, I believe we are good :+1:

**Comment by LucaGuerra** [comment]
The release is live!
