### ISSUE TITLE
Hey folks,

### ISSUE THREAD

**Issue by Reme240400** [falcosecurity/falco#2370]
Hey folks,

Is this still an issue?

_Originally posted by @leogr in https://github.com/falcosecurity/falco/issues/2172#issuecomment-1386838767_
                      
Hi, I'm still having issues with falco and k8saudit plugin. 
I can't understand how to set up the k8s plugin properly. I have 2 container running that cannot have logs. This is my values.yaml file, used to set up falco: 
[values.txt](https://github.com/falcosecurity/falco/files/10493037/values.txt)

**Comment by Reme240400** [comment]
> /cc @alacuku
This is my file updated.
[values.txt](https://github.com/falcosecurity/falco/files/10494992/values.txt)

**Comment by alacuku** [comment]
Hi @Reme240400, please have a look at this step by step guide how to setup Falco with multiple sources (syscalls + k8saudit): https://falco.org/docs/getting-started/third-party/learning/#falco-with-multiple-sources.
I would suggest you to reproduce the guide using minikube and then adapt the configuration to your environment.

**Comment by Reme240400** [comment]
> Hi @Reme240400, please have a look at this step by step guide how to setup Falco with multiple sources (syscalls + k8saudit): https://falco.org/docs/getting-started/third-party/learning/#falco-with-multiple-sources. I would suggest you to reproduce the guide using minikube and then adapt the configuration to your environment.

Thank you very much, now my container generate the correct logs! Now I have only to understand why my falco-exporter don't take the data. The falco exporter needs 2 pods right?

**Comment by alacuku** [comment]
I think @leogr could help with the `falco-exporter` issue.

**Comment by Reme240400** [comment]
> I think @leogr could help with the `falco-exporter` issue.

Ok, thank you. I can't understand what is wrong in my configuration, I'm using the Unix socket and falco's pods generates the logs correctly, the falco-exporter's pods are listening correctly in the same socket. 
This is my falco values file:
[falco.txt](https://github.com/falcosecurity/falco/files/10499172/falco.txt)
This is my falco exporter values file: 
[falco-exporter.txt](https://github.com/falcosecurity/falco/files/10499173/falco-exporter.txt)

**Comment by leogr** [comment]
I totally agree our documentation lacks some aspects.

IIRC, falco-exporter assumes that Falco has been deployed as a daemonset (so one pod per node) and then grpc socket is shared via the host. That likely can't work with a plugin only configuration. 

I'll dig into that as soon as I find the time (now, we are in a rush because the upcoming release).

Thank you for sharing those details!
