### ISSUE TITLE
[New Feature]: Dry run option that outputs the syscalls used by rules

### ISSUE THREAD

**Issue by incertum** [falcosecurity/falco#2372]
**Motivation + Feature**

As extension to https://github.com/falcosecurity/falco/issues/2371, "Dry run option that outputs the syscalls used by rules" proposed by @Happy-Dude. 

Quote @Happy-Dude from https://github.com/falcosecurity/falco/pull/2361#issuecomment-1399402369

> is it possible to have a "dry-run" option that reads in the ruleset (rules.yaml) and outputs the set of syscalls that will be inspected
> - as part of the Falco state engine
> - from the dynamic set (rules.yaml)
> - and from the additional set?
>This can help for debugging by making it clear what is causing a particular syscall to be inspected.

Quote @jasondellaluce from https://github.com/falcosecurity/falco/pull/2361#issuecomment-1401652172

> Dry run option that outputs the syscalls used by rules: I see this request falling into the umbrella of "printing descriptive information about one or more rules (up until the whole ruleset)". We have other feature requests like this (see: https://github.com/falcosecurity/falco/issues/1814), and I think we should make this happen. In my opinion, enhancing --list-syscalls might not be the right call because it's only supposed to print static data. Instead, we also have -L and -l that are meant to print informations about rules specifically. I think we could enhance the output of those commands to include the set of matching events and other info as well. Plus, I'm recently advocating the idea of making all Falco outputs optionally machine-readable in JSON format in the future (see special notes for your reviewer in: https://github.com/falcosecurity/falco/pull/2351), and in which case we could include extra information in the JSON output compared to the plain-text counterpart.

**Comment by FedeDP** [comment]
@incertum should we close this?

**Comment by Happy-Dude** [comment]
Works for me! I'm wondering if something like that is necessary now after having gained some experience writing rules and with the utility of `base_syscalls` 🤔

But I digress! Feel free to close and I'll open another issue ticket if the need rises 👍
