### ISSUE TITLE
Fail to build on RHEL 8 due to incorrect hash

### ISSUE THREAD

**Issue by petterreinholdtsen** [falcosecurity/falco#2380]
**Describe the bug**

I'm trying to build the latest git source on RHEL 8, but it fail to build.

I am following the instructions on https://vD-26.falco.org/docs/getting-started/source/, and ran into this build error:

```
-- [download 93% complete]
-- [download 94% complete]
-- [download 95% complete]
-- [download 97% complete]
-- [download 98% complete]
-- [download 99% complete]
-- [download 100% complete]
-- verifying file...
       file='/home/pre/src/falco-upstream/build/falcosecurity-rules-falco-prefix/src/falco-rules-0.1.0.tar.gz'
-- SHA256 hash of
    /home/pre/src/falco-upstream/build/falcosecurity-rules-falco-prefix/src/falco-rules-0.1.0.tar.gz
  does not match expected value
    expected: 'f909a996213ab659ef9f958ae64b16c83dca0035525cc044d4dc074250e8b152'
      actual: 'a9ff79af88f76a966299f5808676dc559b02dfcfd278d91277a776c306f94446'
-- Hash mismatch, removing...
CMake Error at falcosecurity-rules-falco-stamp/download-falcosecurity-rules-falco.cmake:170 (message):
  Each download failed!

    
    


make[2]: *** [CMakeFiles/falcosecurity-rules-falco.dir/build.make:99: falcosecurity-rules-falco-prefix/src/falcosecurity-rules-falco-stamp/falcosecurity-rules-falco-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:918: CMakeFiles/falcosecurity-rules-falco.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
%
```

**How to reproduce it**

Dependencies for building source, package and bpf, and run cmake like this:

```
cmake -DBUILD_BPF=ON -DUSE_BUNDLED_DEPS=ON ..
```

**Expected behaviour**

**Environment**

- Falco version: git release 2023-01-26
- System info: RHEL 8 on virtual machine

**Comment by Andreagit97** [comment]
@petterreinholdtsen I'm not able to reproduce the issue with the [latest master commit](https://github.com/falcosecurity/falco/commit/e8d9b5a7e7f01b0c8d4c448586a1e4649bc6ce94)...
Could you try a clean build?
```
rm -rf build
mkdir build && cd build
cmake -DBUILD_BPF=ON -DUSE_BUNDLED_DEPS=ON ..
```

**Comment by petterreinholdtsen** [comment]
Sorry for the late reply.  The new build test took a while. :)

[Andrea Terzolo]
> @petterreinholdtsen I'm not able to reproduce the issue with the
> [latest master
> commit](https://github.com/falcosecurity/falco/commit/e8d9b5a7e7f01b0c8d4c448586a1e4649bc6ce94)...
> Could you try a clean build?

Sure.  I updated git to the latest master commit
e8d9b5a7e7f01b0c8d4c448586a1e4649bc6ce94, and now it fail with a
different and more familiar issue:

-- Using src='https://download.falco.org/rules/application-rules-0.1.0.tar.gz'
-- [download 100% complete]
-- verifying file...
       file='/home/pre/src/falco-upstream/build/falcosecurity-rules-application-prefix/src/application-rules-0.1.0.tar.gz'
-- Downloading... done
-- extracting...
     src='/home/pre/src/falco-upstream/build/falcosecurity-rules-application-prefix/src/application-rules-0.1.0.tar.gz'
     dst='/home/pre/src/falco-upstream/build/falcosecurity-rules-application-prefix/src/falcosecurity-rules-application'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 32%] No update step for 'falcosecurity-rules-application'
[ 33%] No patch step for 'falcosecurity-rules-application'
[ 33%] No configure step for 'falcosecurity-rules-application'
[ 34%] No build step for 'falcosecurity-rules-application'
[ 34%] No install step for 'falcosecurity-rules-application'
[ 34%] No test step for 'falcosecurity-rules-application'
[ 34%] Completed 'falcosecurity-rules-application'
[ 34%] Built target falcosecurity-rules-application
make[4]: *** /lib/modules/4.18.0-425.10.1.el8_7.x86_64/build: No such file or directory.  Stop.
make[3]: *** [Makefile:16: all] Error 2
make[2]: *** [driver/CMakeFiles/driver.dir/build.make:70: driver/CMakeFiles/driver] Error 2
make[1]: *** [CMakeFiles/Makefile2:1206: driver/CMakeFiles/driver.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
%

I got past this by installing the kernel-devel package.  Perhaps it
should be added to the list of packages to install, or I should have
disabled the kernel module build.

Now the build fail like this:

[ 32%] Built target cxxopts
[ 34%] Built target falcosecurity-rules-application
In file included from /home/pre/src/falco-upstream/build/driver/src/ppm_fillers.c:90:
/home/pre/src/falco-upstream/build/driver/src/kernel_hacks.h:33: warning: "copy_from_kernel_nofault" redefined
 #define copy_from_kernel_nofault probe_kernel_read
 
In file included from ./include/linux/crypto.h:26,
                 from ./include/crypto/hash.h:16,
                 from ./include/linux/uio.h:16,
                 from ./include/linux/socket.h:8,
                 from ./include/linux/compat.h:15,
                 from /home/pre/src/falco-upstream/build/driver/src/ppm_fillers.c:12:
./include/linux/uaccess.h:396: note: this is the location of the previous definition
 #define copy_from_kernel_nofault(a,b,c) probe_kernel_read(a,b,c)
 
[ 34%] Built target driver
make[5]: llc: Command not found
make[5]: *** [/home/pre/src/falco-upstream/build/driver-repo/driver-prefix/src/driver/bpf/Makefile:54: /home/pre/src/falco-upstream/build/driver-repo/driver-prefix/src/driver/bpf/probe.o] Error 127
make[4]: *** [Makefile:1585: _module_/home/pre/src/falco-upstream/build/driver-repo/driver-prefix/src/driver/bpf] Error 2
make[3]: *** [Makefile:38: all] Error 2
make[2]: *** [driver/bpf/CMakeFiles/bpf.dir/build.make:70: driver/bpf/CMakeFiles/bpf] Error 2
make[1]: *** [CMakeFiles/Makefile2:1258: driver/bpf/CMakeFiles/bpf.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
%

I got around this one by installing llvm.  Not quite sure why it was not
installed already.

So I guess this was a false alarm or me simply having bad luck with the
git snapshot I was using.  Sorry about that. I am not sure which git
commit I was using ealier, but the latest master is definitely building
for me now.  Sadly it lack a lot of dependencies in RHEL and download
lot of code from the Internet to get going.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by Andreagit97** [comment]
@petterreinholdtsen can we close this?

**Comment by petterreinholdtsen** [comment]
Yeah.
