### ISSUE TITLE
Falco sidekick ui redis uses an image that's not multi-arch (exec format error)

### ISSUE THREAD

**Issue by samip5** [falcosecurity/falco#2402]
**Describe the bug**

The falco sidekick ui defaults to the `docker.io/redislabs/redisearch` image which lacks an arm64 variant.

**How to reproduce it**

Deploy Falco sidekick ui on arm64 nodes, eg Raspberry Pi 4

**Expected behaviour**

I expected it to work.

**Screenshots**

**Environment**

- Falco version: 
```
Falco version: 0.33.1
Libs version:  0.9.2
Plugin API:    2.0.0
Driver:
  API version:    2.0.0
  Schema version: 2.0.0
  Default driver: 3.0.1+driver
  ```
- OS: 
```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

- Kernel: `Linux w2 5.15.0-1023-raspi #25-Ubuntu SMP PREEMPT Fri Jan 6 17:33:55 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux`

- Installation method: Kubernetes via Helm (https://github.com/samip5/k8s-cluster/blob/d4d372b3582fc2f6a09aca11d7680f46a8b35a6f/cluster/apps/security/falco/app/helm-release.yaml)

**Additional context**

Seems to suggest that the docker image is deprecated: https://hub.docker.com/r/redislabs/redisearch

**Comment by Issif** [comment]
Thanks for reporting this issue. I already know it and don't have a solution. As long redislab doesn't provide an arm64 image I can't do anything on my side except rewriting everything to use a different backend (and to be honest I don't want). Could you create an issue in their repo and link this one please?

**Comment by samip5** [comment]
> Could you create an issue in their repo and link this one please?

I did that, but maybe worth noting is that the docker hub readme says that the redisearch container is deprecated and to use redis-stack instead?

**Comment by Issif** [comment]
> > Could you create an issue in their repo and link this one please?
> 
> I did that, but maybe worth noting is that the docker hub readme says that the redisearch container is deprecated and to use redis-stack instead?

Oh I didn't know that, I'll take a look. Thanks

**Comment by samip5** [comment]
> @samip5 can you close this issue and recreate in the [falcosidekic-ui repo](https://github.com/falcosecurity/falcosidekick-ui) please? There's also an issue in [charts](https://github.com/falcosecurity/charts/issues/406) about the same topic, you could just follow in this one.

I think you should be able to move it there from the menu on the right side? If not, I can just subscribe to the chart issue about this and discuss it there.

**Comment by Issif** [comment]
these are 2 different repos, we can't move an issue from on to another. let's continue in the chart issue, makes more sense. thanks

**Comment by samip5** [comment]
True, but Github should have an ability to move issues between the same org's repos. Closing this then.

**Comment by Issif** [comment]
I'm not an owner of the org, I couldn't anyway.
