### ISSUE TITLE
Support for Falco

### ISSUE THREAD

**Issue by Susanta2000** [falcosecurity/falco#2449]
I want to send every falco alerts to a kafka topic. But it's not going to kafka. My helm installation command is:
$ helm upgrade falco falcosecurity/falco \
-n falco \
--set falcosidekick.enabled=true \
--set falcosidekick.webui.enabled=true \
--set auditLog.enabled=true \
--set falcosidekick.config.kafka.async=true \
--set falcosidekick.config.kafka.hostport="http://3.226.98.61:9092" \
--set falcosidekick.config.kafka.topic="falco_topic" \
--set falcosidekick.config.kafka.minimumpriority="debug" 

Was I missed something that I have to provided?

**Comment by FedeDP** [comment]
Hi! This seems most likely an issue with the Falco sidekick config.
Also, are you passing falcosidekick config keys to the Falco chart?
/cc @Issif

**Comment by Susanta2000** [comment]
> Hi! This seems most likely an issue with the Falco sidekick config. Also, are you passing falcosidekick config keys to the Falco chart? /cc @Issif

Hello @FedeDP , No I just passed these configurations. Can you elaborate me? Because I am very new to falco and this is my project requirement also.

**Comment by Issif** [comment]
Hi,

Can you check the Falcosidekick logs to see if the kafka output is correctly enabled and it there are errors.

**Comment by Susanta2000** [comment]
> Hi,
> 
> Can you check the Falcosidekick logs to see if the kafka output is correctly enabled and it there are errors.

Hello @Issif , I can't see any error logs.When I integrate slack with falco, this worked fine.

**Comment by Susanta2000** [comment]
> Nothing in the falcosidekick logs? When Falcosidekick starts, it displays the enabled outputs can you check that please? You may have to kill one pod to force a restart.

Are you want to say this:
Defaulted container "falco" out of: falco, falcoctl-artifact-follow, falco-driver-loader (init), falcoctl-artifact-install (init)
Tue Mar 21 09:25:36 2023: Falco version: 0.34.1 (x86_64)
Tue Mar 21 09:25:36 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
Tue Mar 21 09:25:36 2023: Loading rules from file /etc/falco/falco_rules.yaml
Tue Mar 21 09:25:36 2023: The chosen syscall buffer dimension is: 8388608 bytes (8 MBs)
Tue Mar 21 09:25:36 2023: Starting health webserver with threadiness 2, listening on port 8765
Tue Mar 21 09:25:36 2023: Enabled event sources: syscall
Tue Mar 21 09:25:36 2023: Opening capture with Kernel module

**Comment by Issif** [comment]
These are the Falco pod logs, Falcosidekick runs in its own pod. :wink:

**Comment by Susanta2000** [comment]
> These are the Falco pod logs, Falcosidekick runs in its own pod. wink

2023/03/21 09:22:07 [INFO]  : Falco Sidekick version: 2.27.0
2023/03/21 09:22:07 [INFO]  : Enabled Outputs : [Kafka WebUI]
2023/03/21 09:22:07 [INFO]  : Falco Sidekick is up and listening on :2801
2023/03/21 09:23:48 [ERROR] : WebUI - Post "http://falco-falcosidekick-ui:2802": dial tcp 10.100.33.124:2802: connect: connection refused
2023/03/21 09:23:48 [ERROR] : WebUI - Post "http://falco-falcosidekick-ui:2802": dial tcp 10.100.33.124:2802: connect: connection refused
2023/03/21 09:29:47 [ERROR] : WebUI - Post "http://falco-falcosidekick-ui:2802": dial tcp 10.100.33.124:2802: connect: connection refused
2023/03/21 09:29:47 [ERROR] : WebUI - Post "http://falco-falcosidekick-ui:2802": dial tcp 10.100.33.124:2802: connect: connection refused
2023/03/21 09:30:01 [ERROR] : WebUI - Post "http://falco-falcosidekick-ui:2802": dial tcp 10.100.33.124:2802: connect: connection refused
2023/03/21 09:30:01 [ERROR] : WebUI - Post "http://falco-falcosidekick-ui:2802": dial tcp 10.100.33.124:2802: connect: connection refused
2023/03/21 10:00:23 [ERROR] : WebUI - Post "http://falco-falcosidekick-ui:2802": dial tcp 10.100.33.124:2802: connect: connection refused
2023/03/21 10:00:23 [ERROR] : WebUI - Post "http://falco-falcosidekick-ui:2802": dial tcp 10.100.33.124:2802: connect: connection refused
2023/03/21 10:00:29 [ERROR] : WebUI - Post "http://falco-falcosidekick-ui:2802": dial tcp 10.100.33.124:2802: connect: connection refused
2023/03/21 10:00:29 [ERROR] : WebUI - Post "http://falco-falcosidekick-ui:2802": dial tcp 10.100.33.124:2802: connect: connection refused

**Comment by Issif** [comment]
It seems you have an issue with the falcosidekick-ui pods but I'm mostly surprised you don't have any log line about kafka output. Can you remove the `minimumpriority` just to be sure, by default it's `debug` anyway

**Comment by Susanta2000** [comment]
> It seems you have an issue with the falcosidekick-ui pods but I'm mostly surprised you don't have any log line about kafka output. Can you remove the `minimumpriority` just to be sure, by default it's `debug` anyway

Here is the logs:
2023/03/21 10:48:04 [INFO]  : Falco Sidekick version: 2.27.0
2023/03/21 10:48:04 [INFO]  : Enabled Outputs : [Kafka]
2023/03/21 10:48:04 [INFO]  : Falco Sidekick is up and listening on :2801

**Comment by Susanta2000** [comment]
> and no message in Kafka? are you sure some events have been triggered by Falco?

Look into these logs. These are generated by falco:
{"hostname":"falco-rkvpv","output":"11:05:27.618385925: Notice A shell was spawned in a container with an attached terminal (user=root user_loginuid=-1 k8s.ns=falco1 k8s.pod=falco-rkvpv container=ea02151f732e shell=bash parent=runc cmdline=bash pid=19783 terminal=34816 container_id=ea02151f732e image=docker.io/falcosecurity/falco-no-driver)","priority":"Notice","rule":"Terminal shell in container","source":"syscall","tags":["T1059","container","mitre_execution","shell"],"time":"2023-03-21T11:05:27.618385925Z", "output_fields": {"container.id":"ea02151f732e","container.image.repository":"docker.io/falcosecurity/falco-no-driver","evt.time":1679396727618385925,"k8s.ns.name":"falco1","k8s.pod.name":"falco-rkvpv","proc.cmdline":"bash","proc.name":"bash","proc.pid":19783,"proc.pname":"runc","proc.tty":34816,"user.loginuid":-1,"user.name":"root"}}
{"hostname":"falco-rkvpv","output":"11:06:41.218356694: Error File below /etc opened for writing (user=root user_loginuid=-1 command=touch bac.txt pid=20135 parent=bash pcmdline=bash file=/etc/falco/bac.txt program=touch gparent=<NA> ggparent=<NA> gggparent=<NA> container_id=ea02151f732e image=docker.io/falcosecurity/falco-no-driver) k8s.ns=falco1 k8s.pod=falco-rkvpv container=ea02151f732e","priority":"Error","rule":"Write below etc","source":"syscall","tags":["T1098","container","filesystem","host","mitre_persistence"],"time":"2023-03-21T11:06:41.218356694Z", "output_fields": {"container.id":"ea02151f732e","container.image.repository":"docker.io/falcosecurity/falco-no-driver","evt.time":1679396801218356694,"fd.name":"/etc/falco/bac.txt","k8s.ns.name":"falco1","k8s.pod.name":"falco-rkvpv","proc.aname[2]":null,"proc.aname[3]":null,"proc.aname[4]":null,"proc.cmdline":"touch bac.txt","proc.name":"touch","proc.pcmdline":"bash","proc.pid":20135,"proc.pname":"bash","user.loginuid":-1,"user.name":"root"}}
{"hostname":"falco-rkvpv","output":"11:08:00.823978011: Warning Shell history had been deleted or renamed (user=root user_loginuid=-1 type=openat command=bash pid=19783 fd.name=/root/.bash_history name=/root/.bash_history path=<NA> oldpath=<NA> k8s.ns=falco1 k8s.pod=falco-rkvpv container=ea02151f732e)","priority":"Warning","rule":"Delete or rename shell history","source":"syscall","tags":["T1070","container","filesystem","host","mitre_defense_evasion","process"],"time":"2023-03-21T11:08:00.823978011Z", "output_fields": {"container.id":"ea02151f732e","evt.arg.name":"/root/.bash_history","evt.arg.oldpath":null,"evt.arg.path":null,"evt.time":1679396880823978011,"evt.type":"openat","fd.name":"/root/.bash_history","k8s.ns.name":"falco1","k8s.pod.name":"falco-rkvpv","proc.cmdline":"bash","proc.pid":19783,"user.loginuid":-1,"user.name":"root"}}
{"hostname":"falco-rkvpv","output":"11:09:32.150469912: Notice A shell was spawned in a container with an attached terminal (user=root user_loginuid=-1 k8s.ns=falco1 k8s.pod=falco-rkvpv container=ea02151f732e shell=bash parent=runc cmdline=bash pid=20944 terminal=34816 container_id=ea02151f732e image=docker.io/falcosecurity/falco-no-driver)","priority":"Notice","rule":"Terminal shell in container","source":"syscall","tags":["T1059","container","mitre_execution","shell"],"time":"2023-03-21T11:09:32.150469912Z", "output_fields": {"container.id":"ea02151f732e","container.image.repository":"docker.io/falcosecurity/falco-no-driver","evt.time":1679396972150469912,"k8s.ns.name":"falco1","k8s.pod.name":"falco-rkvpv","proc.cmdline":"bash","proc.name":"bash","proc.pid":20944,"proc.pname":"runc","proc.tty":34816,"user.loginuid":-1,"user.name":"root"}}

**Comment by Susanta2000** [comment]
Am I missing something?

**Comment by Issif** [comment]
I tried on my side with your payloads, and it's OK:
```
2023/03/21 13:32:56 [INFO]  : Falco Sidekick version: devel
2023/03/21 13:32:56 [INFO]  : Enabled Outputs : [Kafka]
2023/03/21 13:32:56 [INFO]  : Falco Sidekick is up and listening on :2801
2023/03/21 13:32:56 [INFO]  : Debug mode : true
2023/03/21 13:33:03 [DEBUG] : Falco's payload : {"uuid":"725c0b2c-2419-4aba-b309-b7214e5a312c","output":"11:05:27.618385925: Notice A shell was spawned in a container with an attached terminal (user=root user_loginuid=-1 k8s.ns=falco1 k8s.pod=falco-rkvpv container=ea02151f732e shell=bash parent=runc cmdline=bash pid=19783 terminal=34816 container_id=ea02151f732e image=docker.io/falcosecurity/falco-no-driver)","priority":"Notice","rule":"Terminal shell in container","time":"2023-03-21T11:05:27.618385925Z","output_fields":{"akey_2":"AValue","bkey":"BValue","ckey":"CValue","container.id":"ea02151f732e","container.image.repository":"docker.io/falcosecurity/falco-no-driver","evt.time":1679396727618385925,"k8s.ns.name":"falco1","k8s.pod.name":"falco-rkvpv","proc.cmdline":"bash","proc.name":"bash","proc.pid":19783,"proc.pname":"runc","proc.tty":34816,"user.loginuid":-1,"user.name":"root"},"source":"syscall","tags":["T1059","container","mitre_execution","shell"],"hostname":"falco-rkvpv"}
2023/03/21 13:33:04 [INFO]  : Kafka (1) - Publish OK
```
My configuration is:
```yaml=
kafka:
  hostport: "localhost:9092"
  topic: "falco"
  async: true
```

I think your wrong config is `--set falcosidekick.config.kafka.hostport="http://3.226.98.61:9092/"` it should be:
```
--set falcosidekick.config.kafka.hostport="3.226.98.61:9092/"
```

The protocol to communicate with Kafka is not http.

**Comment by Susanta2000** [comment]
Thanks @Issif . Now falco's data is going to kafka.

**Comment by Issif** [comment]
Awesome, sorry it took me some time to spot the issue

**Comment by FedeDP** [comment]
Thanks both! Can we close this one then? :)
