### ISSUE TITLE
Add signatures to the official Falco images

### ISSUE THREAD

**Issue by LucaGuerra** [falcosecurity/falco#2455]
**Feature**

When releasing Falco, we publish the following images
- `falco`
- `falco-driver-loader`
- `falco-no-driver`

All can be deployed in users' environments and all can be signed. Note that this issue likely depends on https://github.com/falcosecurity/falco/issues/2454 

Note that the running binaries that are contained in those images are already signed (with the Falco public key) but this issue is to sign the container image as well.

The way we have picked across the org is by using cosign, in the same way we have implemented in falcosidekick (see: https://github.com/falcosecurity/falcosidekick/blob/master/.github/workflows/release.yml )

**Comment by FedeDP** [comment]
This is fixed as of latest master, right? :)

**Comment by FedeDP** [comment]
/close

Completed :)
