### ISSUE TITLE
Error error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded: No such file or directory

### ISSUE THREAD

**Issue by Jaideep1997** [falcosecurity/falco#2469]
**Describe the bug**

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by Jaideep1997** [comment]
i was writing this docker command for falco installation :
i wrote this:

docker run --rm -i -t     --privileged     -v /root/.falco:/root/.falco     -v /proc:/host/proc:ro     -v /boot:/host/boot:ro     -v /lib/modules:/host/lib/modules:ro     -v /usr:/host/usr:ro     -v /etc:/host/etc:ro     falcosecurity/falco:latest

but it gave me this error

* Setting up /usr/src links from host
* Running falco-driver-loader for: falco version=0.34.1, driver version=4.0.0+driver, arch=x86_64, kernel release=5.19.0-38-generic, kernel version=39
* Running falco-driver-loader with: driver=module, compile=yes, download=yes

================ Cleaning phase ================

* 1. Check if kernel module 'falco' is still loaded:
- OK! There is no 'falco' module loaded.

* 2. Check all versions of kernel module 'falco' in dkms:
- OK! There are no 'falco' module versions in dkms.

[SUCCESS] Cleaning phase correctly terminated.

================ Cleaning phase ================

* Looking for a falco module locally (kernel 5.19.0-38-generic)
* Filename 'falco_ubuntu-generic_5.19.0-38-generic_39.ko' is composed of:
 - driver name: falco
 - target identifier: ubuntu-generic
 - kernel release: 5.19.0-38-generic
 - kernel version: 39
* Found a prebuilt falco module at /root/.falco/4.0.0+driver/x86_64/falco_ubuntu-generic_5.19.0-38-generic_39.ko, loading it
* Success: falco module found and inserted
2023-04-04T10:29:22+0000: Falco version: 0.34.1 (x86_64)
2023-04-04T10:29:22+0000: Falco initialized with configuration file: /etc/falco/falco.yaml
2023-04-04T10:29:22+0000: Loading rules from file /etc/falco/falco_rules.yaml
2023-04-04T10:29:22+0000: Loading rules from file /etc/falco/falco_rules.local.yaml
2023-04-04T10:29:22+0000: The chosen syscall buffer dimension is: 8388608 bytes (8 MBs)
2023-04-04T10:29:22+0000: Starting health webserver with threadiness 8, listening on port 8765
2023-04-04T10:29:22+0000: Enabled event sources: syscall
2023-04-04T10:29:22+0000: Opening capture with Kernel module
2023-04-04T10:29:22+0000: Trying to inject the Kernel module and opening the capture again...
2023-04-04T10:29:22+0000: Unable to load the driver
2023-04-04T10:29:22+0000: An error occurred in an event source, forcing termination...
Events detected: 0
Rule counts by severity:
Triggered rules by rule name:
Error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded: No such file or directory

please help me to solve

**Comment by tspearconquest** [comment]
This is a duplicate of #2434

**Comment by Andreagit97** [comment]
Ei @Jaideep1997 thank you for reporting this!
The right command to run falco latest with the kernel module should be:

```bash
docker pull falcosecurity/falco:latest
docker run --rm -i -t \
    --privileged \
    -v /var/run/docker.sock:/host/var/run/docker.sock \
    -v /dev:/host/dev \
    -v /proc:/host/proc:ro \
    -v /boot:/host/boot:ro \
    -v /lib/modules:/host/lib/modules:ro \
    -v /usr:/host/usr:ro \
    -v /etc:/host/etc:ro \
    falcosecurity/falco:latest
```

It seems you missed `-v /dev:/host/dev`. 
This is the related docs https://falco.org/docs/getting-started/running/#docker-privileged
Let me know if it works :)

**Comment by Andreagit97** [comment]
can we close this :)?

**Comment by Andreagit97** [comment]
I will close this, please reopen if there are other issues :)

**Comment by asher-lab** [comment]
Hi All,

Below is my scenario in this case:

**Root Cause** : Installing falco in a KinD node is not possible

**Error Encountered:** 
Error error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded: No such file or directory

**Background of the issue:** I'm trying to install Falco in containerized environment. Using the steps here for debian installation I tried to install it https://falco.org/docs/install-operate/installation/. However, I encountered some issues when starting the falco service due to issue ensuring that the linux-header module is installed inside the node I am currently in. It returns the following errors:  

```
Unable to load the driver
Sat Sep 30 00:49:20 2023: An error occurred in an event source, forcing termination...
Events detected: 0
Rule counts by severity:
Triggered rules by rule name:
Error: error opening device /dev/falco0. Make sure you have root credentials and that the falco module is loaded: No such file or directory
```

Additionally, here are the errors encountered when I did performing the command to install the linux-headers

```
 apt install -y dkms make linux-headers-$(uname -r)
Reading state information... Done
E: Unable to locate package linux-headers-5.15.0-1047-azure
E: Couldn't find any package by glob 'linux-headers-5.15.0-1047-azure'

```


**Impact on the system:** Can't run Falco inside the worker node bootstrap using KinD (Kubernetes In Docker)

**Solutions and Next steps:** : Install Falco on a node that is independent (doesn't have an abstration just like in KinD where it doesn't really have its own Kernel)
```
 apt install -y dkms make linux-headers-$(uname **-r)
update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
Setting up build-essential (12.8ubuntu1.1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ... completed
root@cks:~/kind#

```

**Workaround**: N/A as we performed an action step to install falco node via kubeadm and not using KinD.

**Comment by Andreagit97** [comment]
Ei @asher-lab thank you for reporting! the best way to install Falco on a KinD cluster is to use the official helm chart with `driver.kind = modern-bpf` as explained here https://github.com/falcosecurity/charts/blob/master/falco/README.md#daemonset. The `modern-bpf` should work out of the box!

**Comment by roloff-it** [comment]
I have the same problem here, when i work with modern-ebpf.  It works with kmod,

root@k8s-worker-01:~# apt install -y dkms make linux-headers-$(uname -r)
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
make ist schon die neueste Version (4.3-4.1build1).
dkms ist schon die neueste Version (2.8.7-2ubuntu2.2).
linux-headers-5.15.0-91-generic ist schon die neueste Version (5.15.0-91.101).
linux-headers-5.15.0-91-generic wurde als manuell installiert festgelegt.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 34 nicht aktualisiert.
root@k8s-worker-01:~# whoami
root
root@k8s-worker-01:~# falco
Thu Jan 25 20:03:31 2024: Falco version: 0.36.2 (x86_64)
Thu Jan 25 20:03:31 2024: Falco initialized with configuration file: /etc/falco/falco.yaml
Thu Jan 25 20:03:31 2024: Loading rules from file /etc/falco/falco_rules.yaml
Thu Jan 25 20:03:31 2024: Loading rules from file /etc/falco/falco_rules.local.yaml
Thu Jan 25 20:03:31 2024: The chosen syscall buffer dimension is: 8388608 bytes (8 MBs)
Thu Jan 25 20:03:31 2024: Starting health webserver with threadiness 8, listening on port 8765
Thu Jan 25 20:03:31 2024: Loaded event sources: syscall
Thu Jan 25 20:03:31 2024: Enabled event sources: syscall
Thu Jan 25 20:03:31 2024: Opening 'syscall' source with Kernel module
Thu Jan 25 20:03:31 2024: Trying to inject the Kernel module and opening the capture again...
Thu Jan 25 20:03:31 2024: Unable to load the driver
Thu Jan 25 20:03:31 2024: An error occurred in an event source, forcing termination...
Events detected: 0
Rule counts by severity:
Triggered rules by rule name:
Error: error opening device /dev/falco0. Make sure you have root credentials and that the falco module is loaded: No such file or directory
