### ISSUE TITLE
[New Feature] Support partial rule overrides (merge rules of the same name)

### ISSUE THREAD

**Issue by tspearconquest** [falcosecurity/falco#2477]
**Motivation**

I came across the [rule exceptions](https://falco.org/docs/rules/exceptions/) page this evening and tried it out.

Falco is printing output against the `Contact K8S API Server From Container` rule and I want to make it less spammy in my environment. I wanted to add the container name to the output, in order to better identify the containers triggering the spammy messages; so I added this block to a new values file and did helm upgrade with this values file appended in addition to my normal values:

```
customRules:
## Add the container name to the output
  falco_rules.local.yaml: |-
    - rule: Contact K8S API Server From Container
      output: Unexpected connection to K8s API Server from container (command=%proc.cmdline pid=%proc.pid %container.info container.name=%container.name image=%container.image.repository:%container.image.tag connection=%fd.name)
```

When loading Falco with this config:

```
Error: /etc/falco/rules.d/falco_rules.local.yaml: Invalid
1 Errors:
In rules content: (/etc/falco/rules.d/falco_rules.local.yaml:0:0)
    rule 'Contact K8S API Server From Container': (/etc/falco/rules.d/falco_rules.local.yaml:14:2)
------
- rule: Contact K8S API Server From Container
  ^
------
LOAD_ERR_YAML_VALIDATE (Error validating internal structure of YAML file): Item has no mapping for key 'enabled'
```

When I added `enabled: true` and redeployed falco, I got:

```
Error: /etc/falco/rules.d/falco_rules.local.yaml: Invalid
1 Errors:
In rules content: (/etc/falco/rules.d/falco_rules.local.yaml:0:0)
    rule 'Contact K8S API Server From Container': (/etc/falco/rules.d/falco_rules.local.yaml:14:2)
------
- rule: Contact K8S API Server From Container
  ^
------
LOAD_ERR_YAML_VALIDATE (Error validating internal structure of YAML file): Item has no mapping for key 'condition'
```

I expected that Falco would read this override config file and realize that its an override for the rule with the same name, and because it already has a definition for the rule from the original rules yaml, it would merge the two together. As a Kubernetes user, I don't want to have to copy the entire rule from upstream to override part of the rule. Details on why this is are provided near the bottom.

**Feature**

It would be far more preferable if falco would do a YAML merge between the rule named in this override and the original content of the rule in `falco_rules.yaml` to produce the following in memory:

```
- rule: Contact K8S API Server From Container
  desc: Detect attempts to contact the K8S API Server from a container
  condition: >
    evt.type=connect and evt.dir=< and
    (fd.typechar=4 or fd.typechar=6) and
    container and
    not k8s_containers and
    k8s_api_server and
    not user_known_contact_k8s_api_server_activities
  output: Unexpected connection to K8s API Server from container (command=%proc.cmdline pid=%proc.pid %container.info container.name=%container.name image=%container.image.repository:%container.image.tag connection=%fd.name)
  priority: NOTICE
  tags: [network, k8s, container, mitre_discovery, T1565]
```

**Alternatives**

The only alternative is to just override the entire rule. IMO, this defeats the purpose of falcoctl's artifact follow features. If I want to always have the latest upstream rules, but want to make adjustments such as changing only the output, or adding an exception to allow certain known authorized activities, then I want to change as little as possible about the rule by simply adding an override containing the rule name and the field(s) to be overridden. If I have to override the whole rule, then I never get the benefits offered by falcoctl because my customizations completely changed the rule logic.

However, having said that, I feel I should clarify that having merges like this should still allow for completely changing the rule logic as well. By redefining the condition in an override, or by overriding a macro, we can still change the rule logic (such as in order to get rid of things that are allowed by default but you want to log an event on).

In order to build a complete rule, Falco should merge different fields from rules with the same name, and override fields defined earlier with those defined later when they are defined in multiple rules of the same name.

**Additional context**

Why this matters to kubernetes users in specific:

When a kubernetes manifest which has the same field defined twice is deployed to a cluster, if the twice-defined field is a map type field, the two fields are merged together. This is easily [demonstrated](https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key) by helm when it tries to merge 2 different livenessProbe fields together, which is why you have to explicitly set the field being overridden in that example as null.

This is what I'm requesting for Falco to do. When an update comes in from upstream, I want the updated rule to take effect without me needing to review the update and apply the same update to my local rules file unless the specific field that I've overridden is what has changed.

So, taking my original example above, let's say that the output field changes upstream. That would not take effect because my local rules has its own output defined. But let's say that I added an exception to this rule. Since upstream doesn't have an exception, my exception gets merged into the new rule from upstream and continues to apply without issue. If, later on, an exception is added upstream, then It'll be up to me to review that and take action.

There is also a really big bonus here in that this feature would make reviewing the rule changes from upstream for differences to incorporate far easier. Because we only add what needs to be overridden to the local rules file, we only need to compare that one line for changes, rather than having to review the whole rule and all of the lists and macros used in the condition.

**Comment by jasondellaluce** [comment]
Thanks for sharing this. I did some research on the flaws and pitfalls of our rule language and the notion of "merging" definitions instead of complete overrides is something that I thought about multiple times. To make it short, changing the current behavior would cause most rulesets currently existing to be broken, which is not practicable at all. What we can do in the future instead is adopting solid semantic versioning on the rule engine itself, and introduce a slight variant of the current language supporting concepts like this one. There has been no concrete conversation about this so far, but it's something I wish to discuss for our roadmap in the upcoming future.

**Comment by incertum** [comment]
This is related to https://github.com/falcosecurity/falco/issues/1340

Disclaimer: We are not talking about `append` mode at all and solely about overriding either the entire rule or a subset of properties when defining the same rule the second time. FYI: There are some open requests related to the `append` mode (that is be able to also append to either the output or tags property and not just the condition property) that I am starting to address.

Current state:

When adding a yaml rule object with a rule name that was used before it is a requirement to redefine all keys hence the entire rule which is a drawback for many use cases.

As discussed here https://github.com/falcosecurity/falco/issues/1340 if we allowed the override when using the same rules name, but define let's say only the condition field, the new behavior can be to override the condition key, but keep all the other keys definitions from when the rule was first defined.

From my perspective this won't break past behavior as in the past attempting partial overrides would not work in the first place, hence I look at it as a new feature that should be possible without complications (just would need docs updates as well)? Happy to be proven wrong if that is not true.

Regardless +1 on rules engine versions wrt the semantics

**Comment by incertum** [comment]
@tspearconquest let's track this in the related issue https://github.com/falcosecurity/falco/issues/1340, is this ok with you?
