### ISSUE TITLE
Add k8s.cluster.name as a field

### ISSUE THREAD

**Issue by c0ldb00t3r** [falcosecurity/falco#2482]
**Feature**
Hi, 
   If anyone is sending Falco logs from multiple clusters to a single dashboard like sidekick, it would be impossible to track where the alert came from based on only the namespace and container. I have the same request as @Donald-Sysdig. https://github.com/falcosecurity/falco/issues/423

Although the ticket was closed saying the field k8s namespace was added. But the feature is vastly different.

This will help a lot of teams manage alerts in a single dashboard.

**Comment by lumszy** [comment]
Same issue applies to me. We have 3 different eks clusters sending falco logs to same slack channel and it's a pain to get from which eks cluster the falco alerts are coming from.. Hopefully, this issue is given much attention.

**Comment by thelubomir** [comment]
Hey! Same issue to me, because we have a lot of different eks clusters. Our solution for now is plenty slack channels, but I really hope for cluster name in output. It would be really handy. So waiting for it as well.

**Comment by Issif** [comment]
Hi, 
you can install one falcosidekick per cluster and use its feature which allows to add fields in the output and then forward the event to the same falcosidekick-ui or slack channel. Since the last version of falcosidekick, you can also use an env var as value to add

**Comment by thelubomir** [comment]
@Issif Could you please provide link for documentation about it?

**Comment by Issif** [comment]
The docs of falcosidekick is directly in the [README](https://github.com/falcosecurity/falcosidekick).

```yaml
customfields: # custom fields are added to falco events, if the value starts with % the relative env var is used
  # Akey: "AValue"
  # Bkey: "BValue"
  # Ckey: "CValue"
```

If you use the falco helm chart, you need to set something like that for the [values](https://github.com/falcosecurity/charts/blob/master/falcosidekick/values.yaml):

```yaml
falcosidekick:
  config:
    customfields: "k8s.cluster.name=<my_cluster>"
```

**Comment by incertum** [comment]
Question: Does `spec.NodeName` reflect a  notation where the cluster name is part of the node name definition? It often does. If yes could you parse it out from the `hostname`?

If not since this is a constant we could do a similar env variable trick, check out https://github.com/falcosecurity/falco/issues/2506 and expose a new output field that way, e.g. maybe something more generic `evt.cluster` or similar.
