### ISSUE TITLE
couldn't run on fresh install: (kind) unable to find a prebuilt falco module (linuxkit_5.15.49) & (minikube) unable to load the driver

### ISSUE THREAD

**Issue by Dentrax** [falcosecurity/falco#2483]
**Describe the bug**

```
* Trying to download a prebuilt falco module from https://download.falco.org/driver/4.0.0%2Bdriver/x86_64/falco_ubuntu-linuxkit_5.15.49-linuxkit_1.ko
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to download.falco.org:443
Unable to find a prebuilt falco module
```

<details>
<summary>Full Logs</summary>

```
* Setting up /usr/src links from host
* Running falco-driver-loader for: falco version=0.34.1, driver version=4.0.0+driver, arch=x86_64, kernel release=5.15.49-linuxkit, kernel version=1
* Running falco-driver-loader with: driver=module, compile=yes, download=yes

================ Cleaning phase ================

* 1. Check if kernel module 'falco' is still loaded:
- OK! There is no 'falco' module loaded.

* 2. Check all versions of kernel module 'falco' in dkms:
- OK! There are no 'falco' module versions in dkms.

[SUCCESS] Cleaning phase correctly terminated.

================ Cleaning phase ================

* Looking for a falco module locally (kernel 5.15.49-linuxkit)
* Filename 'falco_ubuntu-linuxkit_5.15.49-linuxkit_1.ko' is composed of:
 - driver name: falco
 - target identifier: ubuntu-linuxkit
 - kernel release: 5.15.49-linuxkit
 - kernel version: 1
* Trying to download a prebuilt falco module from https://download.falco.org/driver/4.0.0%2Bdriver/x86_64/falco_ubuntu-linuxkit_5.15.49-linuxkit_1.ko
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to download.falco.org:443
Unable to find a prebuilt falco module
install: /usr/lib/gcc/x86_64-linux-gnu/5/
* Trying to dkms install falco module with GCC /usr/bin/gcc
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"

Creating symlink /var/lib/dkms/falco/4.0.0+driver/source ->
                 /usr/src/falco-4.0.0+driver

DKMS: add completed.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/4.0.0+driver/build/make.log (with GCC /usr/bin/gcc)
install: /usr/lib/gcc/x86_64-linux-gnu/5/
* Trying to dkms install falco module with GCC /usr/bin/gcc-5
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/4.0.0+driver/build/make.log (with GCC /usr/bin/gcc-5)
install: /usr/lib/gcc/x86_64-linux-gnu/6/
* Trying to dkms install falco module with GCC /usr/bin/gcc-6
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/4.0.0+driver/build/make.log (with GCC /usr/bin/gcc-6)
install: /usr/lib/gcc/x86_64-linux-gnu/8/
* Trying to dkms install falco module with GCC /usr/bin/gcc-8
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/4.0.0+driver/build/make.log (with GCC /usr/bin/gcc-8)
* Trying to load a system falco module, if present
Consider compiling your own falco driver and loading it or getting in touch with the Falco community
```

</details>

**How to reproduce it**

1. `kind create cluster --name test`
2. `helm repo add falcosecurity https://falcosecurity.github.io/charts`
3. `helm repo update`
4. `helm install falco falcosecurity/falco --namespace falco --create-namespace`
5. See the error

**Expected behaviour**

It should work on fresh Helm install?

**Screenshots**

**Environment**

- Falco version:
`falco-3.1.3/0.34.1`
- System info:
`macOS 13`
- Cloud provider or hardware configuration: `kind`
- OS: `Ubuntu 22.04.2 LTS`
- Kernel: `5.15.49-linuxkit`
`Linux test-control-plane 5.15.49-linuxkit #1 SMP Tue Sep 13 07:51:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Installation method:
`Helm`

**Additional context**

`-`

**Comment by Dentrax** [comment]
Just tried with `minikube --driver qemu` and got the following startup error:

```
Sat Apr  8 21:27:15 2023: Falco version: 0.34.1 (x86_64)
Sat Apr  8 21:27:15 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
Sat Apr  8 21:27:15 2023: Loading rules from file /etc/falco/falco_rules.yaml
Sat Apr  8 21:27:15 2023: The chosen syscall buffer dimension is: 8388608 bytes (8 MBs)
Sat Apr  8 21:27:15 2023: Starting health webserver with threadiness 2, listening on port 8765
Sat Apr  8 21:27:15 2023: Enabled event sources: syscall
Sat Apr  8 21:27:15 2023: Opening capture with Kernel module
Sat Apr  8 21:27:16 2023: Trying to inject the Kernel module and opening the capture again...
Sat Apr  8 21:27:16 2023: Unable to load the driver
Sat Apr  8 21:27:16 2023: An error occurred in an event source, forcing termination...
Error: Driver supports API version 1.0.0, but running version needs 3.0.0
Events detected: 0
Rule counts by severity:
Triggered rules by rule name:
```

**Comment by Andreagit97** [comment]
Uhm the issue is that there is no pre-built module `https://download.falco.org/driver/4.0.0%2Bdriver/x86_64/falco_ubuntu-linuxkit_5.15.49-linuxkit_1.ko` i think you need to compile it locally if you want to use the kernel module. Otherwise, you could try the `--modern-bpf` probe

**Comment by alacuku** [comment]
@Dentrax, what's the version of minikube?

**Comment by Dentrax** [comment]
> @Dentrax, what's the version of minikube?

```
minikube version: v1.30.1
commit: 08896fd1dc362c097c925146c4a0d0dac715ace0
```

> i think you need to compile it locally

@Andreagit97, I have tried to install headers with `sudo apt install linux-headers-$(uname -r)` but minikube uses `buildroot` ISO so I couldn't able to install headers. Tried to install on kind nodes but couldn't make it work (probably related with apt sources.d)

> you could try the --modern-bpf probe

I also have tried with the eBPF mode on both minikube and kind but the errors was quite similar (not found some required dependency or module smth):

```
helm install falco falcosecurity/falco --namespace falco --create-namespace --set ebpf.enabled=true
```

**Comment by alacuku** [comment]
Updated the commend with the option for the `modern-bpf` probe :point_up:

**Comment by Dentrax** [comment]
Thanks @alacuku! Now I can able to up & running the Falco. What did you do? Is there a change that we may still encounter in future releases of Falco (or Kernel)?

**Comment by alacuku** [comment]
I checked if `kmod & probe` were available for minikube `1.30.1` here: https://download.falco.org/driver/site/index.html?lib=4.0.0%2Bdriver&target=minikube&arch=x86_64&kind=all. It could take 1 week or so to discover and build the modules for new minikube releases. Before updating minikube make sure that the modules are available.

Otherwise, you can run Falco using the `modern bpf` probe which is shipped bundled in the Falco container and no external modules are needed to be built or downloaded.

**Comment by Andreagit97** [comment]
can we close this?

**Comment by Andreagit97** [comment]
i will close it, please reopen if there are other issues :)
