### ISSUE TITLE
Support for Bound Service Account Token projected volume

### ISSUE THREAD

**Issue by tspearconquest** [falcosecurity/falco#2485]
**Motivation**

As demonstrated in #2476, falco is not detecting a rotated service account token credential, and is therefore failing to connect to the api server once the credential has been rotated by the kubelet.

**Feature**

Falco needs to detect when the service account token has been rotated and begin using the new token so that it doesn't crash.

There are a few OSS repos where I can find fixes for this same issue. Datadog has a fix due to crashing, and Cert-Manager has an example helm chart values file for configuring cert-manager with this feature.

**Alternatives**

Turn off the feature and automount the service account token

**Additional context**

Best practices recommend disabling serviceaccount token automount, so we have used kustomize to add the `automountServiceAccountToken: false` field and added the service account token volume and volumeMount to the helm values.yaml file. Falco operates properly with this enabled, however when the token gets rotated, it doesn't detect the change, and continues to try to connect to the API server with a now-stale token, which causes falco to exit.

**Comment by Andreagit97** [comment]
hey @tspearconquest this is a known issue we are working on fixing all the issues related to the Kubernetes client here https://github.com/falcosecurity/libs/issues/987, thank you again @alacuku !

**Comment by tspearconquest** [comment]
/remove-lifecycle stale

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Speeddymon** [comment]
@jasondellaluce help?

Looks like the bot removed and re-added the same label...

**Comment by Andreagit97** [comment]
The new `k8smeta` plugin should solve this issue, give it a try with our dedicated helm chart and Falco 0.36.2 https://github.com/falcosecurity/falco/issues/2973#issuecomment-1876880587

**Comment by Andreagit97** [comment]
This should be solved by [Falco 0.37.0](https://github.com/falcosecurity/falco/releases/tag/0.37.0)! Feel free to reopen if this is still an issue
