### ISSUE TITLE
Falco installation an AWS EKS with Amazon Linux 2 image

### ISSUE THREAD

**Issue by ajinkya1986** [falcosecurity/falco#2488]
**Describe the bug**
We are trying to install Falco in Amazon EKS with Amazon Linux 2 image, but the ebpf probe is not getting installed and cannot be downloaded
```
Trying to download a prebuilt eBPF probe from https://download.falco.org/driver/39ae7d40496793cf3d3e7890c9bbdc202263836b/fal ││ curl: (22) The requested URL returned error: 404  
Unable to find a prebuilt falco eBPF probe                                                                                     
* Trying to compile the eBPF probe (falco_amazonlinux2_5.4.238-148.346.amzn2.x86_64_1.o)                                       
*  expr: syntax error: unexpected argument '1'                                                                                    
* make[1]: *** /lib/modules/5.4.238-148.346.amzn2.x86_64/build: No such file or directory.  Stop.                                
* make: *** [Makefile:38: all] Error 2                                                                                           
* mv: cannot stat '/usr/src/falco-39ae7d40496793cf3d3e7890c9bbdc202263836b/bpf/probe.o': No such file or directory               │Unable to load the falco eBPF probe 
```

**How to reproduce it**
Create a standard EKS cluster and install falco.

**Environment**

- Falco version: 0.32
- System info: 
- Cloud provider or hardware configuration:
- AWS
- OS: AL2_x86_64
- Kernel: 5.4.238-148.346
- Installation method: helm

**Comment by Andreagit97** [comment]
it seems like you miss kernel headers on your node :/ you can try something like `sudo yum install -y kernel-devel-$(uname -r)`

**Comment by ajinkya1986** [comment]
@Andreagit97  we do not have access to the node shell

**Comment by Andreagit97** [comment]
uhm ok, so the only way you have is to rely on a pre-built driver, it seems we already have an issue for that on test-infra repository https://github.com/falcosecurity/test-infra/issues/1093

**Comment by mpurusottamc** [comment]
@Andreagit97 thanks for reference. I can see that there's a pre-built driver (https://download.falco.org/driver/site/index.html?lib=4.0.0%2Bdriver&target=amazonlinux2&arch=x86_64&kind=kmod&search=falco_amazonlinux2_5.10.173-154.642.amzn2.x86_64_1.ko).

A follow up question, in our falco setup, it's looking for a `.o` file. but, i don't see the `.o` file. I only see `.ko` file. Any suggestions how to address this?

**Comment by mpurusottamc** [comment]
@Andreagit97 :(. My filter was incorrect. I can see the `.o` file when selected the ebpf filter.

I can see the file here - (https://download.falco.org/driver/site/index.html?lib=4.0.0%2Bdriver&target=amazonlinux2&arch=x86_64&kind=ebpf&search=falco_amazonlinux2_5.10.173-154.642.amzn2.x86_64_1.o)

But, still i see the error. Any suggestions?

**Comment by Andreagit97** [comment]
@mpurusottamc Could you share the Falco output?

**Comment by FedeDP** [comment]
Yep! You just need to update Falco to latest version :)
We only officially support latest 3 driver version. Thus we only provide updates for prebuilt drivers for them!

**Comment by mpurusottamc** [comment]
that explains it. Thanks for your help @FedeDP @Andreagit97

**Comment by ajinkya1986** [comment]
Thanks for the response @FedeDP and @Andreagit97

**Comment by ajinkya1986** [comment]
We are facing the same issue for kubernetes version 1.22 for falco versions 2.0.18,2.55.3.0.0 and 3.1.3. Below is the log for version 3.1.3
```falco-driver-loader * Setting up /usr/src links from host
falco-driver-loader * Running falco-driver-loader for: falco version=0.34.1, driver version=4.0.0+driver, arch=x86_64, kernel release=5.4.238-148.346.amzn2.x86_64, kernel version=1
falco-driver-loader * Running falco-driver-loader with: driver=bpf, compile=yes, download=yes
falco-driver-loader * Mounting debugfs
falco-driver-loader mount: /sys/kernel/debug: permission denied.
falco-driver-loader * Filename 'falco_amazonlinux2_5.4.238-148.346.amzn2.x86_64_1.o' is composed of:
falco-driver-loader  - driver name: falco
falco-driver-loader  - target identifier: amazonlinux2
falco-driver-loader  - kernel release: 5.4.238-148.346.amzn2.x86_64
falco-driver-loader  - kernel version: 1
falco-driver-loader * Trying to download a prebuilt eBPF probe from https://download.falco.org/driver/4.0.0%2Bdriver/x86_64/falco_amazonlinux2_5.4.238-148.346.amzn2.x86_64_1.o
falco-driver-loader curl: (22) The requested URL returned error: 404 
falco-driver-loader Unable to find a prebuilt falco eBPF probe
falco-driver-loader * Trying to compile the eBPF probe (falco_amazonlinux2_5.4.238-148.346.amzn2.x86_64_1.o)
falco-driver-loader expr: syntax error: unexpected argument '1'
falco-driver-loader make[1]: *** /lib/modules/5.4.238-148.346.amzn2.x86_64/build: No such file or directory.  Stop.
falco-driver-loader make: *** [Makefile:38: all] Error 2
falco-driver-loader mv: cannot stat '/usr/src/falco-4.0.0+driver/bpf/probe.o': No such file or directory
falco-driver-loader Unable to load the falco eBPF probe
stream logs failed container "falcoctl-artifact-follow" in pod "test-falco-w44pw" is waiting to start: PodInitializing for test/test-falco-w44pw (falcoctl-artifact-follow)
stream logs failed container "falco" in pod "test-falco-w44pw" is waiting to start: PodInitializing for test/test-falco-w44pw (falco)```

**Comment by ajinkya1986** [comment]
Hi just wanted to update. We have tested the falco versions 2.0.18, 2.5.5, 3.0.0 and 3.1.3 with EKS kubernetes versions 1.22, 1.23,1.24,1.25 and 1.26. The falco daemonset is working now as expected with successful loading of the ebpf probe and we are getting the threats data as well.
@mpurusottamc @FedeDP @Andreagit97

**Comment by FedeDP** [comment]
That's great! This is surely linked to https://github.com/falcosecurity/test-infra/issues/1093; please leave a comment there :)

**Comment by ajinkya1986** [comment]
Ok Sure @FedeDP

**Comment by Andreagit97** [comment]
can we close this?

**Comment by ajinkya1986** [comment]
@Andreagit97 Yes you can close it. Thank you for your support.
