### ISSUE TITLE
[Feature request] Support syscall event field k8s.node.name

### ISSUE THREAD

**Issue by tspearconquest** [falcosecurity/falco#2497]
**Motivation**

I have clusters which have requirements that certain pods can only be scheduled to certain nodes, so I use taints to separate those special nodes from the non-special nodes, and a node affinity rule on the pod to select a special label I've also applied on those nodes.

**Feature**

I want to configure my falco rules to generate an event when certain containers start on those nodes, or when those containers are started on the wrong node (say that someone removes the node affinity label and the pod restarts on an untainted node). Please consider adding an event field `k8s.node.name` which we can use in conditions.

**Alternatives**

I think maybe there isn't any?

**Additional context**

I have a node taint on a set of nodes which are large size, while untainted nodes are medium size, and in the medium ones some customer facing services run, so I want to prevent workloads which would consume a lot of resources from running on those medium nodes. It would be handy for an event to be fired about this.

**Comment by Andreagit97** [comment]
This seems a reasonable request! WDYT @alacuku? Do you see any easy way to implement it in the new design?

**Comment by incertum** [comment]
Hi @tspearconquest thank you, agree tainting nodes is a common practice and Falco should be smart about all k8s, and also be performant.

In the Falco docs https://falco.org/docs/reference/rules/supported-fields/#field-class-k8s you see that we aim to extract anything possible form the container runtime socket itself, as using the `-k` flag for Kubernetes metadata has a performance impact and can have scaling issues.


We have an existing FALCO_HOSTNAME env variable and in general more env variable can be introduced, and I just responded here https://github.com/falcosecurity/falco/issues/2506. Maybe trying to see how we can extend the tags filtering options?

**Comment by tspearconquest** [comment]
I think unfortunately that this won't work for my use-case. In our setup, Falco runs on all the nodes, both large and medium size, in a single daemonset. Since there's only one daemonset, I could only set one value across both types of nodes for the FALCO_HOSTNAME. Additionally, I'm not clear on how I would use this enviroment variable with tag filtering, as I also would have no way to separate the falco.yaml config file for each kind of node.

We do use -k flag, so the addition of this field being locked behind this flag would not be a concern for my use-case, as we know we can't do anything about dropped events, and we're not overly concerned with capturing *every* event in the cluster at this time.

**Comment by tspearconquest** [comment]
I realize now that I should have clarified in my OP that Falco is a "special snowflake" in the sense that we didn't set node selectors or affinity rules like we do for everything else.

**Comment by incertum** [comment]
Understood @tspearconquest. Opened a PR where I expose `evt.hostname`. Note, in Kubernetes daemonsets `hostname` usually returns the pod name, if this is not the behavior you want is there some env variable in your falco container that can assign its value to `FALCO_HOSTNAME`, something like `export FALCO_HOSTNAME=$K8S_NODE_NAME;` or at least fetch the true hostname value from the underlying host which often has similar naming conventions? That way `evt.hostname` would reflect the k8s node name from each node, respectively. A similar solution works for me. 

In case something like described above does not work, the PR solely addresses the other issue and is not a solution for your use case.

**Comment by incertum** [comment]
@tspearconquest here is an additional resource https://kubernetes.io/docs/concepts/workloads/pods/downward-api/ you should be able to directly assign `spec.nodeName` to an environment variable of your choice and then `evt.hostname` can solve your issue.

The PR for `evt.hostname` has been merged in libs and the feature will be available in master once we bump libs and then available in

/milestone 0.36.0

See https://github.com/falcosecurity/falco/issues/2506#issuecomment-1607883967
and https://github.com/falcosecurity/falco/issues/2660

What do you think? Could we close this issue and track possible future more efficient solutions in https://github.com/falcosecurity/falco/issues/2660?

**Comment by tspearconquest** [comment]
LGTM! I was following the updates, and I think it'll work better than my proposal since it won't cause event drops!

**Comment by incertum** [comment]
Thank you!
