### ISSUE TITLE
falco logs without k8s.ns.name and k8s.pod.name in EKS w/ docker runtime (works w/ containerd runtime which is among Falco's supported cri runtimes (containerd, cri-o))

### ISSUE THREAD

**Issue by alfredomagallon** [falcosecurity/falco#2498]
**Describe the bug**

I am writing a validation test for falco, at this time in AKS and EKS
We use the same falco deployment for both environments
The test is producing a "Write below etc" event
In the Azure logs, we can see the k8s.ns.name and k8s.pod.name are properly filled
In the AWS logs, those fileds are left with "null"

**How to reproduce it**

Deploy falco with the same configuration (standard helm config with slight modifications) in AKS and EKS
Produce a "Write below etc" event in a debian based pod in the same namespace
Read the logs

**Expected behaviour**

Fields should be properly filled in both environments

**Screenshots**

EKS logs:

```
k logs falco-gzkgf|grep "Write below etc"
{"hostname":"falco-gzkgf","output":"17:25:25.085409918: Error File below /etc opened for writing (user=root user_loginuid=-1 command=touch /etc/falco_e2e_test.txt pid=4406 parent=bash pcmdline=bash -c touch /etc/falco_e2e_test.txt; ls /etc/falco_e2e_test.txt file=/etc/falco_e2e_test.txt program=touch gparent=<NA> ggparent=<NA> gggparent=<NA> container_id=dbcec984abe0 image=<NA>) k8s.ns=<NA> k8s.pod=<NA> container=dbcec984abe0","priority":"Error","rule":"Write below etc","source":"syscall","tags":["T1098","container","filesystem","host","mitre_persistence"],"time":"2023-04-14T17:25:25.085409918Z", "output_fields": {"container.id":"dbcec984abe0","container.image.repository":null,"evt.time":1681493125085409918,"fd.name":"/etc/falco_e2e_test.txt","k8s.ns.name":null,"k8s.pod.name":null,"proc.aname[2]":null,"proc.aname[3]":null,"proc.aname[4]":null,"proc.cmdline":"touch /etc/falco_e2e_test.txt","proc.name":"touch","proc.pcmdline":"bash -c touch /etc/falco_e2e_test.txt; ls /etc/falco_e2e_test.txt","proc.pid":4406,"proc.pname":"bash","user.loginuid":-1,"user.name":"root"}}
```

AKS logs:

```
k logs falco-zshfp|grep "Write below etc"
{"hostname":"falco-zshfp","output":"17:25:46.550661386: Error File below /etc opened for writing (user=root user_loginuid=-1 command=touch /etc/falco_e2e_test.txt pid=2527144 parent=bash pcmdline=bash -c touch /etc/falco_e2e_test.txt; ls /etc/falco_e2e_test.txt file=/etc/falco_e2e_test.txt program=touch gparent=<NA> ggparent=<NA> gggparent=<NA> container_id=3e9b0a5021f8 image=upmdev.azurecr.io/upm-falco/debian) k8s.ns=upm-falco k8s.pod=upm-falco-e2e-4702329939 container=3e9b0a5021f8","priority":"Error","rule":"Write below etc","source":"syscall","tags":["T1098","container","filesystem","host","mitre_persistence"],"time":"2023-04-14T17:25:46.550661386Z", "output_fields": {"container.id":"3e9b0a5021f8","container.image.repository":"upmdev.azurecr.io/upm-falco/debian","evt.time":1681493146550661386,"fd.name":"/etc/falco_e2e_test.txt","k8s.ns.name":"upm-falco","k8s.pod.name":"upm-falco-e2e-4702329939","proc.aname[2]":null,"proc.aname[3]":null,"proc.aname[4]":null,"proc.cmdline":"touch /etc/falco_e2e_test.txt","proc.name":"touch","proc.pcmdline":"bash -c touch /etc/falco_e2e_test.txt; ls /etc/falco_e2e_test.txt","proc.pid":2527144,"proc.pname":"bash","user.loginuid":-1,"user.name":"root"}}
```

**Environment**

- Falco version:
```
Sat Apr 15 16:51:12 2023: Falco version: 0.34.1 (x86_64)
Sat Apr 15 16:51:12 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
{"default_driver_version":"4.0.0+driver","driver_api_version":"3.0.0","driver_schema_version":"2.0.0","engine_version":"16","falco_version":"0.34.1","libs_version":"0.10.4","plugin_api_version":"2.0.0"}
```
- System info:
- Cloud provider or hardware configuration: EKS v1.24.9
- OS: (Container where we fire the event) debian-slim:latest
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel 
Linux 1da85e65afd2 5.15.0-69-generic # 76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 GNU/Linux
- Installation method:
Helm chart 3.1.2

**Additional context**

It works fine in our AKS

**Comment by alfredomagallon** [comment]
Worarounds already tried:
enabling --disable-cri-async
disabling --k8s-node

**Comment by alacuku** [comment]
Hi @alfredomagallon: 
1. what are the container runtimes used on both clusters? 
2. what are the k8s.* fields you are using in your rules? just the k8s.ns.name and k8s.pod.name?

**Comment by alfredomagallon** [comment]
Hi @alacuku 

For AKS, containerd://1.6.18+azure-1
For EKS, docker://20.10.17

For the rules we are currently using:
k8s.pod.name
container.image.repository

But we are using
k8s.ns.name
k8s.pod.name

as relevant information for the event in our monitoring system

**Comment by alacuku** [comment]
Hi @alfredomagallon, could you try and disable the k8s metadata collector: https://github.com/falcosecurity/charts/blob/6fff4e1e75c43af742596f478bf86e7723aa08da/falco/values.yaml#L253-L257

> The set of fields k8s.ns.name and k8s.pod.* (e.g., k8s.pod.name) are populated with data fetched from the container runtime, so they don't require the Kubernetes Metadata Enrichment functionality to be enabled.

From here: https://falco.org/docs/reference/rules/supported-fields/#field-class-k8s

**Comment by alfredomagallon** [comment]
Hi @alacuku 

Thanks for the suggestion.

I tried that but the result is the same.

The only difference I see is that in the problematic nodes we are still running docker (we need to be in EKS 1.24 to run containerd here as well)

**Comment by alfredomagallon** [comment]
Seems like this is not an issue anymore since we updated to EKS 1.24, so the container runtime changed from docker to containerd.

**Comment by incertum** [comment]
@alfredomagallon this is great news, can we close the issue?

**Comment by alfredomagallon** [comment]
I think so, thanks.

**Comment by incertum** [comment]
Great -> resolution: does not work w/ docker runtime for Kubernetes, but does work w/ containerd runtime which is among Falco's supported cri runtimes (containerd, cri-o).
