### ISSUE TITLE
failed to install falco charts in minikube

### ISSUE THREAD

**Issue by dhcn** [falcosecurity/falco#2502]
**Describe the bug**

 ----     ------     ----                  ----               -------
  Normal   Scheduled  29m                   default-scheduler  Successfully assigned falco/falco-c8phs to minikube
  Normal   Pulling    29m                   kubelet            Pulling image "docker.io/falcosecurity/falco-driver-loader:0.34.1"
  Normal   Pulled     26m                   kubelet            Successfully pulled image "docker.io/falcosecurity/falco-driver-loader:0.34.1" in 3m48.88900126s (3m48.889015203s including waiting)
  Normal   Created    24m (x5 over 25m)     kubelet            Created container falco-driver-loader
  Normal   Started    24m (x5 over 25m)     kubelet            Started container falco-driver-loader
  Normal   Pulled     14m (x7 over 25m)     kubelet            Container image "docker.io/falcosecurity/falco-driver-loader:0.34.1" already present on machine
  Warning  BackOff    4m52s (x98 over 25m)  kubelet            Back-off restarting failed container falco-driver-loader in pod falco-c8phs_falco(77e4b324-130d-44ff-97a8-21782aefa873)

--------------------
[root@ecs-2556 ~]# kubectl logs falco-c8phs -n falco
Defaulted container "falco" out of: falco, falcoctl-artifact-follow, falco-driver-loader (init), falcoctl-artifact-install (init)
Error from server (BadRequest): container "falco" in pod "falco-c8phs" is waiting to start: PodInitializing

-------------------------
kubectl logs -l app.kubernetes.io/name=falco --all-containers
install: /usr/lib/gcc/x86_64-linux-gnu/6/
* Trying to dkms install falco module with GCC /usr/bin/gcc-6
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/4.0.0+driver/build/make.log (with GCC /usr/bin/gcc-6)
install: /usr/lib/gcc/x86_64-linux-gnu/8/
* Trying to dkms install falco module with GCC /usr/bin/gcc-8
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/4.0.0+driver/build/make.log (with GCC /usr/bin/gcc-8)
* Trying to load a system falco module, if present
Consider compiling your own falco driver and loading it or getting in touch with the Falco community
Error from server (BadRequest): container "falcoctl-artifact-install" in pod "falco-nnmmw" is waiting to start: PodInitializing

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by dhcn** [comment]
> Hi @dhcn, did you start your minikube cluster with one of the following drivers: `qemu, VirtualBox or kvm2`? Have a look here for more info on how to run falco on minikube: https://falco.org/docs/getting-started/third-party/learning/#minikube

success with this cmd:

```
helm install falco --set driver.kind=ebpf --set tty=true falcosecurity/falco
```

**Comment by alacuku** [comment]
Hi @dhcn, could you please close this issue?

**Comment by Andreagit97** [comment]
i will close it, please re-open if there are other issues
