### ISSUE TITLE
Unable to find a prebuilt falco module 5.15.96 version [missing]

### ISSUE THREAD

**Issue by sidharthkyn1491** [falcosecurity/falco#2503]
Describe the bug

Once Falco is deployed, i get the following error. I wanted to install Falco as a Helm Chart but after installing the Falco Pods panic because they are not able to download the generic module for the Kernel, as the download source is currently not available.

How to reproduce it

install Falco in a cluster as a Helm Chart with the latest Application Version

<img width="1098" alt="falco" src="https://user-images.githubusercontent.com/124236702/233537452-6105f506-bc08-4bb3-aa01-223c833ac1a6.png">

It is trying to download prebuilt falco module from "https://download.falco.org/driver/4.0.0%2Bdriver/aarch64/falco__5.15.96-0-virt_1.ko "
I checked the same but 5.15.96 version is not available in the download section.

Expected behaviour

Falco should just either download the fitting module or compile the right one by itself.

**Comment by FedeDP** [comment]
Hi, thanks for opening this issue!
So, on which host are you on?
It seems like the Falco driver loader is not able to load the target distro, hence the doubled undlescore in the name (should be "_$target_").
Thanks!

**Comment by Andreagit97** [comment]
@sidharthkyn1491 does the [`modern-bpf`](https://falco.org/docs/event-sources/kernel/#modern-ebpf-probe) probe work for you?
