### ISSUE TITLE
event in log is not send to http_output endpoint

### ISSUE THREAD

**Issue by dhcn** [falcosecurity/falco#2505]
**Describe the bug**
event in log is not send to http_output
I can see event info in falco pods log, but I can not receive log in http_output address

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by alacuku** [comment]
Did you enable the `http_output`? What are the logs in Falco? Could you please provide the Falco configuration (if you are using the helm charts, share the values.yaml file).

**Comment by alacuku** [comment]
Does Falco complain that it cannot send output to the HTTP endpoint? Could you share the Falco logs?

**Comment by Andreagit97** [comment]
any news?
