### ISSUE TITLE
 unable to fetch index "falcosecurity" with URL "https://falcosecurity.github.io/falcoctl/index.yaml"

### ISSUE THREAD

**Issue by ameggaoulou** [falcosecurity/falco#2526]
hey so i am trying to use falco on my k8s cluster and i am having this error ERRO: unable to fetch index "falcosecurity" with URL "https://falcosecurity.github.io/falcoctl/index.yaml": cannot fetch index: Get "https://falcosecurity.github.io/falcoctl/index.yaml": dial tcp: lookup falcosecurity.github.io on 10.96.0.10:53: server misbehaving

so i am using vm created by hyper v they running RHEL 8.7 (oopta)  with a k8s cluster using calico as CNI
steps  i followed first time : i only runned the cmd sudo yum install -y kernel-devel-$(uname -r) on my vms and then precided to installing by healm running this cmd from (https://falco.org/docs/getting-started/try-falco/try-falco-on-kubernetes/) it got me this error 
the second time i tried by installing falco first on the vms by following this (https://falco.org/docs/getting-started/installation/) i used the kmod as prefered driver and then i checked the status of falco it was running then i proceded into installing it on the cluster using helm got the same  error 
for the third time i tried with diffrent vm on diffrent network got the same error 
some images i hope they help 
https://imgur.com/a/x4xJA8X

**Comment by LucaGuerra** [comment]
Hey @ameggaoulou ! The error message points to a network issue in the cluster, specifically a DNS error when trying to query an internal (cluster internal) DNS server`10.96.0.10:53` to retrieve an index file that is used to update Falco rules from the Falco organization. This is not normally Falco related so I would advise trying to download the same file or connect to that URL from different pods and follow Kubernetes DNS troubleshooting steps to identify the issue as other workloads in your cluster might be experiencing similar problems, not just Falco.

> the second time i tried by installing falco first on the vms by following this (https://falco.org/docs/getting-started/installation/) i used the kmod as prefered driver and then i checked the status of falco it was running then i proceded into installing it on the cluster using helm got the same error
I believe you solved the issue already :) If you can install Falco directly on the VMs you do not need to install the Helm version at all!

In addition, in some cases you don't want the cluster to retrieve and update rules remotely but you prefer to use local rules so no DNS query needs to happen at all (even in the helm version). In that case you can take a look at the Helm chart documentation or this quick how-to guide https://falco.org/blog/rules-helm-chart-3-0-0/ .
