### ISSUE TITLE
Typo in the documentation (Falco installation)

### ISSUE THREAD

**Issue by Paken** [falcosecurity/falco#2536]
**What to document**

There's mistake in the second line of the picture in the installation page: https://falco.org/docs/getting-started/installation/. The second line is missing **deb** in the beginning.

![image](https://github.com/falcosecurity/falco/assets/16895035/096d7b5a-ab91-4100-bbc4-8121f37c5487)

**Comment by Paken** [comment]
Awesome, thanks for the quick reply. I'll close the issue.

**Comment by Andreagit97** [comment]
fixed https://github.com/falcosecurity/falco-website/pull/957 :)
