### ISSUE TITLE
Falco on k3s Init:CrashLoopBackOff

### ISSUE THREAD

**Issue by juju4** [falcosecurity/falco#2540]
**Describe the bug**

Falco not starting and staying in Init:CrashLoopBackOff state when installed on k3s on proxmox.
Likely kernel 5.15.107-1-pve is not supported (http://download.proxmox.com/debian/pve/dists/bullseye/pve-no-subscription/binary-amd64/pve-kernel-5.15.107-1-pve_5.15.107-1_amd64.deb; http://download.proxmox.com/debian/pve/dists/bullseye/pve-no-subscription/binary-amd64/pve-headers-5.15.107-1-pve_5.15.107-1_amd64.deb)
No pve kernel listed on https://download.falco.org/?prefix=driver/2.0.0%2Bdriver/x86_64/

Same if helm value driver.kind=modern-bpf as seen in another issue.

**How to reproduce it**

Not minimal but
1. Install proxmox (bare metal os or on top of debian)- https://www.proxmox.com/en/
2. Install k3s - https://github.com/CyVerse-Ansible/ansible-jupyterhub
3. Install falco with helm - coming support in https://github.com/juju4/ansible-falco/

**Expected behaviour**

Falco to be in running state

**Environment**

- Falco version:
latest from helm chart  https://falcosecurity.github.io/charts
falco cli not in running state
- System info:
```shell
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
# uname -a
Linux nodehostname 5.15.107-1-pve #1 SMP PVE 5.15.107-1 (2023-04-20T10:05Z) x86_64 x86_64 x86_64 GNU/Linux
# k3s --version
k3s version v1.26.4+k3s1 (8d0255af)
go version go1.19.8
```
- Cloud provider or hardware configuration: Falco on k3s on proxmox
- OS: Ubuntu jammy
- Kernel: 5.15.107-1-pve
- Installation method: Kubernetes helm chart

**Additional context**

```shell
# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                      READY   STATUS                  RESTARTS          AGE    IP           NODE       NOMINATED NODE   READINESS GATES
kube-system   coredns-59b4f5bbd5-n76gl                  1/1     Running                 1 (33h ago)       2d3h   10.42.0.13   nodehostname   <none>           <none>
kube-system   local-path-provisioner-76d776f6f9-95psp   1/1     Running                 1 (33h ago)       2d3h   10.42.0.15   nodehostname   <none>           <none>
kube-system   metrics-server-7b67f64457-sd47x           1/1     Running                 1 (33h ago)       2d     10.42.0.14   nodehostname   <none>           <none>
default       continuous-image-puller-qhfb4             1/1     Running                 0                 33h    10.42.0.18   nodehostname   <none>           <none>
default       user-scheduler-7ddf954bc9-tzjkl           1/1     Running                 0                 33h    10.42.0.21   nodehostname   <none>           <none>
default       user-scheduler-7ddf954bc9-6gp4p           1/1     Running                 0                 33h    10.42.0.20   nodehostname   <none>           <none>
kube-system   svclb-proxy-public-207b7caf-bgbvh         1/1     Running                 0                 33h    10.42.0.19   nodehostname   <none>           <none>
default       proxy-58c874d68-xskr5                     1/1     Running                 0                 28m    10.42.0.29   nodehostname   <none>           <none>
default       hub-587dcf9f84-rhx5d                      0/1     CrashLoopBackOff        8 (4m52s ago)     21m    10.42.0.30   nodehostname   <none>           <none>
falco         falco-nh77w                               0/2     Init:CrashLoopBackOff   348 (3m27s ago)   32h    10.42.0.26   nodehostname   <none>           <none>
root@nodehostname:~# kubectl logs falco-nh77w
Error from server (NotFound): pods "falco-nh77w" not found
# kubectl logs falco-nh77w -n falco
Defaulted container "falco" out of: falco, falcoctl-artifact-follow, falco-driver-loader (init), falcoctl-artifact-install (init)
Error from server (BadRequest): container "falco" in pod "falco-nh77w" is waiting to start: PodInitializing
root@nodehostname:~# kubectl logs daemonset/falco -n falco -c driver-loader
error: container driver-loader is not valid for pod falco-nh77w

```

**Comment by FedeDP** [comment]
Hi! Thanks for opening this issue.
We don't support proxmox right now; moreover our old toolchains included in the `falco-driver-loader` image are not able to build drivers for recent kernels (>= 5.x basically). Therefore i am pretty sure that the issue here is that we are failing to build the driver.
Can you share logs?

> root@nodehostname:~# kubectl logs daemonset/falco -n falco -c driver-loader

You need to use `-c falco-driver-loader` :)

**Comment by juju4** [comment]
```
# kubectl logs daemonset/falco -n falco -c falco-driver-loader
* Setting up /usr/src links from host
* Running falco-driver-loader for: falco version=0.34.1, driver version=4.0.0+driver, arch=x86_64, kernel release=5.15.107-1-pve, kernel version=1
* Running falco-driver-loader with: driver=module, compile=yes, download=yes

================ Cleaning phase ================

* 1. Check if kernel module 'falco' is still loaded:
- OK! There is no 'falco' module loaded.

* 2. Check all versions of kernel module 'falco' in dkms:
- OK! There are no 'falco' module versions in dkms.

[SUCCESS] Cleaning phase correctly terminated.

================ Cleaning phase ================

* Looking for a falco module locally (kernel 5.15.107-1-pve)
* Filename 'falco_ubuntu-pve_5.15.107-1-pve_1.ko' is composed of:
 - driver name: falco
 - target identifier: ubuntu-pve
 - kernel release: 5.15.107-1-pve
 - kernel version: 1
* Trying to download a prebuilt falco module from https://download.falco.org/driver/4.0.0%2Bdriver/x86_64/falco_ubuntu-pve_5.15.107-1-pve_1.ko
curl: (28) Connection timed out after 5000 milliseconds
Unable to find a prebuilt falco module
install: /usr/lib/gcc/x86_64-linux-gnu/5/
* Trying to dkms install falco module with GCC /usr/bin/gcc
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"

Creating symlink /var/lib/dkms/falco/4.0.0+driver/source ->
                 /usr/src/falco-4.0.0+driver

DKMS: add completed.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/4.0.0+driver/build/make.log (with GCC /usr/bin/gcc)
install: /usr/lib/gcc/x86_64-linux-gnu/5/
* Trying to dkms install falco module with GCC /usr/bin/gcc-5
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/4.0.0+driver/build/make.log (with GCC /usr/bin/gcc-5)
install: /usr/lib/gcc/x86_64-linux-gnu/6/
* Trying to dkms install falco module with GCC /usr/bin/gcc-6
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/4.0.0+driver/build/make.log (with GCC /usr/bin/gcc-6)
install: /usr/lib/gcc/x86_64-linux-gnu/8/
* Trying to dkms install falco module with GCC /usr/bin/gcc-8
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/4.0.0+driver/build/make.log (with GCC /usr/bin/gcc-8)
* Trying to load a system falco module, if present
Consider compiling your own falco driver and loading it or getting in touch with the Falco community
# gcc --version
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# /usr/bin/falco-driver-loader --compile
* Running falco-driver-loader for: falco version=0.34.1, driver version=4.0.0+driver, arch=x86_64, kernel release=5.15.107-1-pve, kernel version=1
* Running falco-driver-loader with: driver=module, compile=yes, download=no

================ Cleaning phase ================

* 1. Check if kernel module 'falco' is still loaded:
- OK! There is no 'falco' module loaded.

* 2. Check all versions of kernel module 'falco' in dkms:
- OK! There are no 'falco' module versions in dkms.

[SUCCESS] Cleaning phase correctly terminated.

================ Cleaning phase ================

* Looking for a falco module locally (kernel 5.15.107-1-pve)
* Filename 'falco_ubuntu-pve_5.15.107-1-pve_1.ko' is composed of:
 - driver name: falco
 - target identifier: ubuntu-pve
 - kernel release: 5.15.107-1-pve
 - kernel version: 1
install: /usr/lib/gcc/x86_64-linux-gnu/11/
* Trying to dkms install falco module with GCC /usr/bin/gcc
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
Creating symlink /var/lib/dkms/falco/4.0.0+driver/source -> /usr/src/falco-4.0.0+driver
* Running dkms build failed, couldn't find /var/lib/dkms/falco/4.0.0+driver/build/make.log (with GCC /usr/bin/gcc)
install: /usr/lib/gcc/x86_64-linux-gnu/11/
* Trying to dkms install falco module with GCC /usr/bin/gcc-11
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/4.0.0+driver/build/make.log (with GCC /usr/bin/gcc-11)
install: /usr/lib/gcc/x86_64-linux-gnu/12/
* Trying to dkms install falco module with GCC /usr/bin/gcc-12
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/4.0.0+driver/build/make.log (with GCC /usr/bin/gcc-12)
* Trying to load a system falco module, if present
Consider compiling your own falco driver and loading it or getting in touch with the Falco community
# ls /var/lib/dkms/falco/4.0.0+driver/build/
#
```
not clear why failing on not finding the make.log.
as you said likely more on pve kernel support and toolchain.


Was not modern-bpf option removing the need for module?
From a toolchain perspective, what's needed to allow compiling?

**Comment by FedeDP** [comment]
As i thought, the issue is on the toolchains provided by `falco-driver-loader` image.
We currently have a planned effort to bump falco-driver-loader image: https://github.com/falcosecurity/falco/issues/2489
Moreover, as you said, you can also use modern bpf; i think bpf too is worth trying.

> * Running falco-driver-loader with: driver=module, compile=yes, download=no

You are using falco-driver-loader in kmod (`module`) mode.

Can you share output of installing Falco with modern bpf? It should work out of the box since it does not need to build any artifact.

**Comment by mnafees** [comment]
I am facing the same issue with the latest Helm chart on `minikube+qemu` on my M1 Mac. Is there a quick solution to this that I can try?

**Comment by andreyolv** [comment]
I am with the same problem, but trying run Falco on Kind locally :(

**Comment by eeganlf** [comment]
Same issue. Any ETA on a fix?

**Comment by eeganlf** [comment]
I'm on a gke cluster and this is the command I ran and the output. I believe the kernel version is different than the output above but it is more or less the same output:
# kubectl logs daemonset/falco -n falco -c falco-driver-loader
Found 3 pods, using pod/falco-xjpxd
* Setting up /usr/src links from host
* Running falco-driver-loader for: falco version=0.35.1, driver version=5.0.1+driver, arch=x86_64, kernel release=5.15.107+, kernel version=1
* Running falco-driver-loader with: driver=module, compile=yes, download=yes

================ Cleaning phase ================

* 1. Check if kernel module 'falco' is still loaded:
- OK! There is no 'falco' module loaded.

* 2. Check all versions of kernel module 'falco' in dkms:
- OK! There are no 'falco' module versions in dkms.

[SUCCESS] Cleaning phase correctly terminated.

================ Cleaning phase ================

* Looking for a falco module locally (kernel 5.15.107+)
* Filename 'falco_cos_5.15.107+_1.ko' is composed of:
 - driver name: falco
 - target identifier: cos
 - kernel release: 5.15.107+
 - kernel version: 1
* Trying to download a prebuilt falco module from https://download.falco.org/driver/5.0.1%2Bdriver/x86_64/falco_cos_5.15.107%2B_1.ko
curl: (22) The requested URL returned error: 404 
Unable to find a prebuilt falco module
install: /usr/lib/gcc/x86_64-linux-gnu/5/
* Trying to dkms install falco module with GCC /usr/bin/gcc
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"

Creating symlink /var/lib/dkms/falco/5.0.1+driver/source ->
                 /usr/src/falco-5.0.1+driver

DKMS: add completed.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/5.0.1+driver/build/make.log (with GCC /usr/bin/gcc)
install: /usr/lib/gcc/x86_64-linux-gnu/5/
* Trying to dkms install falco module with GCC /usr/bin/gcc-5
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/5.0.1+driver/build/make.log (with GCC /usr/bin/gcc-5)
install: /usr/lib/gcc/x86_64-linux-gnu/6/
* Trying to dkms install falco module with GCC /usr/bin/gcc-6
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/5.0.1+driver/build/make.log (with GCC /usr/bin/gcc-6)
install: /usr/lib/gcc/x86_64-linux-gnu/8/
* Trying to dkms install falco module with GCC /usr/bin/gcc-8
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/5.0.1+driver/build/make.log (with GCC /usr/bin/gcc-8)
* Trying to load a system falco module, if present
Consider compiling your own falco driver and loading it or getting in touch with the Falco community

**Comment by Andreagit97** [comment]
@andreyolv @eeganlf could you try Falco with the `modern-bpf` probe? It should work... If you are using the helm chart this is almost all that you need https://github.com/falcosecurity/charts/blob/master/falco/README.md#daemonset (`driver.kind=modern-bpf`)

**Comment by Andreagit97** [comment]
any news?

**Comment by DevHerles** [comment]
> @andreyolv @eeganlf could you try Falco with the `modern-bpf` probe? It should work... If you are using the helm chart this is almost all that you need https://github.com/falcosecurity/charts/blob/master/falco/README.md#daemonset (`driver.kind=modern-bpf`)

It works for me, locally.

**Comment by andreyolv** [comment]
@Andreagit97 It's working now! Thanks!

**Comment by Andreagit97** [comment]
Thank you all for the feedback! I will close it, feel free to reopen it if you face other issues!

**Comment by eeganlf** [comment]
> > @andreyolv @eeganlf could you try Falco with the `modern-bpf` probe? It should work... If you are using the helm chart this is almost all that you need https://github.com/falcosecurity/charts/blob/master/falco/README.md#daemonset (`driver.kind=modern-bpf`)
> 
> It works for me, locally.
> 
> `helm install falco falcosecurity/falco --set driver.kind=modern-bpf`

This did indeed work for me on gcloud. Thank you!
