### ISSUE TITLE
Override Default Priority

### ISSUE THREAD

**Issue by ericjulien-okta** [falcosecurity/falco#2541]
**Motivation**
I'm not able to change the Priority of rules in falco_rules.yaml with 'append'.  To change the Priority I need to copy the entire rule, add it to my falco_rules.local.yaml file, and change just the Priority.

**Feature**
I would like to be able change just the Priority of a default rule, similar to the ability to enable a disabled default rule.

**Alternatives**
Either allow this with 'append' or make is similar to 'enable'.  For example:
- rule: some_default_rule
  priority: WARNING

**Comment by atmosx** [comment]
Same here. Looks like I have to re-write the rule :-/

**Comment by jasondellaluce** [comment]
Yeah, I can confirm that for now you need to re-write the whole rule. This is a known issue and I'm tracking this personally. Hopefully we'll find a way to solve this kind of issues. Just FYI, the reason why nobody gave all this a stab so far is that changing this behavior would be a breaking change for all existing rulesets, so when we'll tackle this problem we'll need to be cautious.

**Comment by incertum** [comment]
Please see https://github.com/falcosecurity/falco/issues/1340#issuecomment-1622563824 we would need a re-designed override feature instead of extending `append` here.

**Comment by incertum** [comment]
@ericjulien-okta I am closing this as we are tracking this effort in other issues already https://github.com/falcosecurity/falco/issues/1340. I will tag you in there, thanks!
