### ISSUE TITLE
Support Environment Variable Values in Configuration File

### ISSUE THREAD

**Issue by therealdwright** [falcosecurity/falco#2561]
**Motivation**

When setting up Falco in my cluster, I could not see a way to use environment variables in the config file to store sensitive values such as secrets.

**Feature**

When a sure specifies an environment variable using standard techniques such as `$SOME_ENV_VAR` or `${SOME_ENV_VAR}`, the configuration is parsed in the environment config.

**Alternatives**

Default environment variables for certain configuration options would be another option, I could find this on the docs after a cursory look.

**Additional context**

N/A

**Comment by lumszy** [comment]
I 'm facing the same challenge atm. I 'm not able to set/pass env variable to use k8s secrets (slack webhooks) and also, falcosidekick-ui user has 'username:password'. I 'm unable to pass env values for these.  Please kindly help look into this. Thanks
