### ISSUE TITLE
Falco container crashes on Amazon Linux 2 using 4.14 Kernel

### ISSUE THREAD

**Issue by andy-welsh-dwp** [falcosecurity/falco#2603]
**Describe the bug**

When using Amazon Linux 2 and running falco in a container, the container crashes with the error `Runtime error: failed to open event raw_syscalls/sys_enter. Exiting`. This can be resolved by upgrading the kernel to `5.10` however this is presently not an option open to me. If I understand the Falco documentation correctly kernel v4.14 is supported.

**How to reproduce it**

- Create a fresh EC2 instance running AL2 and kernel 4.14. For the avoidance of doubt the AMI ID here is `ami-053bef78866800cfa`.
- Install pre-req packages: `yum -y install epel-release docker "kernel-devel-$(uname -r)"`
- Build the ebpf driver: 

```bash
docker run --rm --privileged \
  -v /root/.falco:/root/.falco \
  -v /proc:/host/proc:ro  \
  -v /boot:/host/boot:ro  \
  -v /lib/modules:/host/lib/modules  \
  -v /usr:/host/usr:ro  \
  -v /etc:/host/etc:ro  \
    falcosecurity/falco-driver-loader:0.34.1. bpf --compile
```

- Attempt to start falco

```bash
docker run -d \
  --name falco \
  --restart=always \
  --cap-drop all --cap-add sys_admin --cap-add sys_resource --cap-add sys_ptrace \
  -p 5060:5060 \
  -v /var/run/docker.sock:/host/var/run/docker.sock \
  -e FALCO_BPF_PROBE="" \
  -v /root/.falco:/root/.falco \
  -v /etc:/host/etc \
  -v /proc:/host/proc:ro \
  -v $(pwd)/falco:/etc/falco \
    falcosecurity/falco-no-driver:0.34.1
```

**Expected behaviour**

Falco should show as running when running `sudo docker container ls`

**Environment**

- Falco version:
0.34.1. Cannot start container to pass `--version`
- System info:
Cannot start container to pass args
- Cloud provider or hardware configuration:
- OS:
```bash
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
- Kernel:
`Linux ip-10-123-212-173.eu-west-2.compute.internal 4.14.314-237.533.amzn2.x86_64 #1 SMP Thu May 4 09:55:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- Installation method:
Containerised. Pull from dockerhub

**Additional context**

During the course of debug iptables was flushed and selinux disabled using grubby to no effect.

Logs from `docker logs` for the sake of completeness

```bash
2023-06-01T12:02:22+0000: Falco initialized with configuration file /etc/falco/falco.yaml
2023-06-01T12:02:22+0000: Loading rules from file /etc/falco/falco_rules.yaml:
2023-06-01T12:02:22+0000: Loading rules from file /etc/falco/falco_rules.local.yaml:
Rules match ignored syscall: warning (ignored-evttype):
         loaded rules match the following events: access,brk,close,cpu_hotplug,drop,epoll_wait,eventfd,fcntl,fstat,fstat64,futex,getcwd,getdents,getdents64,getegid,geteuid,getgid,getpeername,getresgid,getresuid,getrlimit,getsockname,getsockopt,getuid,infra,k8s,llseek,lseek,lstat,lstat64,mesos,mmap,mmap2,mprotect,munmap,nanosleep,notification,page_fault,poll,ppoll,pread,preadv,procinfo,pwrite,pwritev,read,readv,recv,recvmmsg,select,semctl,semget,semop,send,sendfile,sendmmsg,setrlimit,shutdown,signaldeliver,splice,stat,stat64,switch,sysdigevent,timerfd_create,write,writev;
         but these events are not returned unless running falco with -A
2023-06-01T12:02:23+0000: Unable to load the driver.
```

The falco_rules files in question can be located at https://gitlab.com/gitlab-org/security-products/package-hunter/-/tree/main/falco. I do not believe these to be causing an issue but are included for the sake of completeness.

**Comment by Andreagit97** [comment]
ei @andy-welsh-dwp our documentation is not completely correct, if you are running a kernel version < `4.17` you need to add a volume to the docker command 

```bash
-v /sys/kernel/debug:/sys/kernel/debug:ro \
```

The documentation says this is the commad:

```bash
docker run --rm -i -t \
    --cap-drop all \
    --cap-add sys_admin \
    --cap-add sys_resource \
    --cap-add sys_ptrace \
    -v /var/run/docker.sock:/host/var/run/docker.sock \
    -e FALCO_BPF_PROBE="" \
    -v /root/.falco:/root/.falco \
    -v /etc:/host/etc \
    -v /proc:/host/proc:ro \
    falcosecurity/falco-no-driver:latest
```

But for kernel versions < 4.17 you need to type

```bash
docker run --rm -i -t \
    --cap-drop all \
    --cap-add sys_admin \
    --cap-add sys_resource \
    --cap-add sys_ptrace \
    -v /var/run/docker.sock:/host/var/run/docker.sock \
    -e FALCO_BPF_PROBE="" \
    -v /root/.falco:/root/.falco \
    -v /etc:/host/etc \
    -v /proc:/host/proc:ro \
    -v /sys/kernel/debug:/sys/kernel/debug:ro \
    falcosecurity/falco-no-driver:latest
```

Thank you for reporting this I will update the docs!

**Comment by andy-welsh-dwp** [comment]
That works great. I could have sworn I had tested this but I must have been tripping over my own debugging.

Can you explain the cause of the issue? I am guessing that `debugfs` is not being properly exposed to the container? This is handled somehow differently in kernels > 4.17?

**Comment by Andreagit97** [comment]
> Can you explain the cause of the issue? I am guessing that debugfs is not being properly exposed to the container? This is handled somehow differently in kernels > 4.17?

Yes, sure! As you said `debugfs` was not being properly exposed to the container, but we need it to load simple BPF `tracepoints`. More precisely we need to read under `"/sys/kernel/debug/tracing/events/<tracepoint_name>/id"` to find the id of the tracepoint. Starting from kernel versions >= 4.17 we use raw_tracepoints and we don't need anymore to read under this path we can directly use the `bpf` syscall. Not sure you want this level of detail but just to be super explicit these are the 2 involved functions:

```c
static int __attach_raw_tp(struct bpf_attached_prog* prog, char* last_err)
{
	union bpf_attr attr;
	memset(&attr, 0, sizeof(attr));
	attr.raw_tracepoint.name = (unsigned long)prog->name;
	attr.raw_tracepoint.prog_fd = prog->fd;

	prog->efd = syscall(__NR_bpf, BPF_RAW_TRACEPOINT_OPEN, &attr, sizeof(attr));
	if(prog->efd < 0)
	{
		return scap_errprintf(last_err, -prog->efd, "BPF_RAW_TRACEPOINT_OPEN: event %s", prog->name);
	}
	return SCAP_SUCCESS;
}

static int __attach_tp(struct bpf_attached_prog* prog, char* last_err)
{
	int efd = 0;
	int err = 0;
	char buf[SCAP_MAX_PATH_SIZE];
	snprintf(buf, sizeof(buf), "/sys/kernel/debug/tracing/events/%s/id", prog->name);
	efd = open(buf, O_RDONLY, 0);
	if(efd < 0)
	{
		if(strcmp(prog->name, "exceptions/page_fault_user") == 0 ||
		   strcmp(prog->name, "exceptions/page_fault_kernel") == 0)
		{
			return SCAP_SUCCESS;
		}

		return scap_errprintf(last_err, errno, "failed to open event %s", prog->name);
	}

	err = read(efd, buf, sizeof(buf));
	if(err < 0 || err >= sizeof(buf))
	{
		int err = errno;
		close(efd);
		return scap_errprintf(last_err, err, "read from '%s' failed", prog->name);
	}
	close(efd);

	buf[err] = 0;
	int id = atoi(buf);

	struct perf_event_attr attr = {};
	attr.type = PERF_TYPE_TRACEPOINT;
	attr.sample_type = PERF_SAMPLE_RAW;
	attr.sample_period = 1;
	attr.wakeup_events = 1;
	attr.config = id;

	efd = syscall(__NR_perf_event_open, &attr, -1, 0, -1, 0);
	if(efd < 0)
	{
		return scap_errprintf(last_err, -efd, "event %d", id);
	}

	if(ioctl(efd, PERF_EVENT_IOC_SET_BPF, prog->fd))
	{
		int err = errno;
		close(efd);
		return scap_errprintf(last_err, err, "PERF_EVENT_IOC_SET_BPF");
	}
	prog->efd = efd;
	return SCAP_SUCCESS;
}
```

As you can notice in `__attach_raw_tp` we directly use the `bpf` syscall to load tracepoints.
Hope this will be useful

**Comment by andy-welsh-dwp** [comment]
That is super useful yes, thank you! Always good to be as detailed as possible!

As we're working I'll mark as closed. Thanks for the help!
