### ISSUE TITLE
libpman failed to create dummy inner map in GKE COS

### ISSUE THREAD

**Issue by zestsg** [falcosecurity/falco#2626]
**Describe the bug**

Attempted upgrade from 0.34.1 ebpf to 0.35.0 modern-bpf on GKE COS but encountered a libpman error that caused falco to not start and terminate instead.

```
Thu Jun  8 06:09:38 2023: Falco version: 0.35.0 (x86_64) 
Thu Jun  8 06:09:38 2023: Falco initialized with configuration file: /etc/falco/falco.yaml 
Thu Jun  8 06:09:38 2023: Loading rules from file /etc/falco/falco_rules.yaml 
Thu Jun  8 06:09:39 2023: The chosen syscall buffer dimension is: 8388608 bytes (8 MBs) 
Thu Jun  8 06:09:39 2023: Starting health webserver with threadiness 8, listening on port 8765 
Thu Jun  8 06:09:39 2023: Enabled event sources: syscall 
Thu Jun  8 06:09:39 2023: Opening 'syscall' source with modern BPF probe. 
Thu Jun  8 06:09:39 2023: One ring buffer every '2' CPUs. 
libpman: failed to create the dummy inner map (errno: 1 | message: Operation not permitted) 
Thu Jun  8 06:09:39 2023: An error occurred in an event source, forcing termination... 
Events detected: 0 
Rule counts by severity: 
Triggered rules by rule name: 
Error:
```

**How to reproduce it**

Deploy using helm the following values file by performing a helm upgrade - [values_new_modern.txt](https://github.com/falcosecurity/falco/files/11685098/values_new_modern.txt)

**Expected behaviour**

Falco upgrade should be successful, modern-bpf should load without any issues.

**Screenshots**
![image](https://github.com/falcosecurity/falco/assets/5036703/fdb6100d-53e9-485c-b61b-1d94bdc36d7f)

**Environment**

- Falco version:
0.35.0 (x86_64)
- System info:
```
architecture: amd64
containerRuntimeVersion: containerd://1.6.18
kernelVersion: 5.10.162+
kubeProxyVersion: v1.24.10-gke.1000
kubeletVersion: v1.24.10-gke.1000
operatingSystem: linux
osImage: Container-Optimized OS from Google
```
- Cloud provider or hardware configuration: GCP GKE COS
- OS:
```
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
GOOGLE_METRICS_PRODUCT_ID=26
KERNEL_COMMIT_ID=3db1b2d6a249eff0e52d0964503af751941088d3
GOOGLE_CRASH_ID=Lakitu
VERSION=97
VERSION_ID=97
BUILD_ID=16919.235.30
```
- Kernel: 5.10.162+

- Installation method:
Helm chart

**Additional context**

No issues faced with ebpf on 0.34.1 but encountered error with modern-bpf on 0.35.0 in GCP GKE.
No issues faced with upgrading from ebpf on 0.34.1 to modern-bpf on 0.35.0 on AWS EKS

**Comment by jasondellaluce** [comment]
cc @Andreagit97

**Comment by Andreagit97** [comment]
Uhm weird thing here is that we had an issue with a very similar environment and Falco seems to work with the modern-bpf. See here for more info https://github.com/falcosecurity/falco/issues/2616
More in detail in your case it seems some privileges are missing :thinking: i will dig more into it

**Comment by zestsg** [comment]
Took a look at the other issue. Would it be due to not explicitly declaring the capabilities within the securitycontext and that having it as the automatically generated default "privileged: true" would not suffice/give enough permissions? That would be the difference in terms of configuration on top of the deployment method as I am using helm instead to do the deployment.

**Comment by Andreagit97** [comment]
uhm I would say no, it should always work with privileged... BTW just out of curiosity would you mind testing it with explicit capabilities? just to understand if there are some restrictions imposed by GKE that we don't know

**Comment by Andreagit97** [comment]
Ok i got it, we are facing the same issue reported here https://lore.kernel.org/netdev/20220610112648.29695-1-quentin@isovalent.com/T/

libbpf performs the following check:

```c
int bump_rlimit_memlock(void)
{
	struct rlimit rlim;

	/* if kernel supports memcg-based accounting, skip bumping RLIMIT_MEMLOCK */
	if (memlock_bumped || kernel_supports(NULL, FEAT_MEMCG_ACCOUNT))
		return 0;

	memlock_bumped = true;

	/* zero memlock_rlim_max disables auto-bumping RLIMIT_MEMLOCK */
	if (memlock_rlim == 0)
		return 0;

	rlim.rlim_cur = rlim.rlim_max = memlock_rlim;
	if (setrlimit(RLIMIT_MEMLOCK, &rlim))
		return -errno;

	return 0;
}
```

The issue described on the mailing list is that some enviroments backported the `BPF_FUNC_ktime_get_coarse_ns` helper, but not the memcg memory accounting... for this reason the code skips the `setrlimit` call and that is exactly the issue we are facing

```
libpman: failed to create the dummy inner map (errno: 1 | message: Operation not permitted)
```

More in detail:

```
libbpf: permission error while running as root; try raising 'ulimit -l'? current value: 64.0 KiB
```

So right now you cannot run the modern bpf probe on this kernel :/ BTW we will provide a workaround to call `setrlimit` in any case. Thank you for reporting it!

**Comment by zestsg** [comment]
Thanks so much for the prompt response! Will await for the workaround to be released before testing in GCP GKE further.

**Comment by zestsg** [comment]
@Andreagit97 i see that the fix has been pushed to the libs master branch. Any idea when this will be reflected in the main falco build so that i can proceed further to test if the issue persists after the fix in GKE?

**Comment by Andreagit97** [comment]
we will release a Falco 0.35.1probably next week :)

**Comment by zestsg** [comment]
@Andreagit97 thanks for the update. Will attempt to upgrade and check if the issue persists! Will report back once I have tested it!

**Comment by zestsg** [comment]
Can confirm that 0.35.1 fixes the issue and am able to run modern-bpf on gke cos images now. Thanks for the help!
