### ISSUE TITLE
<NA> output for %user.name

### ISSUE THREAD

**Issue by manojdeshmukh45** [falcosecurity/falco#2639]
Hello every one im facing issues with fetching the username its giving me <NA>, im not able to fetch user.

12:29:34.022226956: Notice Ingress remote file copy tool launched in container (**user=<NA>** user_loginuid=-1 command=curl -o /dev/null -w %{http_code} --max-time 3 -XGET -g -s -k -u elastic-internal-probe: http://127.0.0.1:9200/ pid=363194 parent_process=bash**

**How to reproduce it**
This is the command im running to install 
helm install falco-alert -n falco-alert --version 2.5.5 --set driver.kind=ebpf --set tty=true falcosecurity/falco --set falcosidekick.enabled=true --set falcosidekick.webui.enabled=true --set auditLog.enabled=true --set falco.jsonOutput=true --set falco.fileOutput.enabled=true --set falcosidekick.webui.user="admin:admin"

**Problem Screenshot**

![image](https://github.com/falcosecurity/falco/assets/35873736/d6dae835-30f1-4e05-a52d-79632151c8bf)

Running on GCP Kubernets

- Falco version: 0.33.1
- Chart Version : 2.5.5

**Comment by jasondellaluce** [comment]
> Running on GCP Kubernets
> 
> Falco version: 0.33.1
> Chart Version : 2.5.5

Did you try updating to the latest Falco version (v0.35.0)?

**Comment by manojdeshmukh45** [comment]
Yes, it is working in the 0.35.0 version, but I am not qualified to edit the default falco_rules. yalm, so I'm using the older version where I'm familiar with that version.
I tried to install the new version that's showing user.name, but I'm having difficulties editing the default Falco rules, where in 0.33.1 i can edit all rules using configmap > falco_rules.yalm, but not in new version.

**Comment by jasondellaluce** [comment]
What is the issue you're experiencing when editing the rules?

**Comment by manojdeshmukh45** [comment]
Im not able to find where do i need to edit falco_rules.yaml. previsoly it was in configmap i was editong in configmap and applying the edited ruls. now im not able to find where to edit them.

**Comment by jasondellaluce** [comment]
I assume you're referring to our Helm charts, right? cc @alacuku (just in case).

**Comment by Andreagit97** [comment]
I will close this, if this is still an issue please re-open
