### ISSUE TITLE
gcc compile error

### ISSUE THREAD

**Issue by cqrlhz** [falcosecurity/falco#2640]
Environment: arm version ubuntu 22.04 k8s:1.27.2
Installation Deployment Installation official website documentation: https://falco.org/docs/getting-started/try-falco/try-falco-on-kubernetes/
The log is as follows:
root@k8s-master-10:~# kubectl logs falco-2gnj5 -c falco-driver-loader -n falco
* Setting up /usr/src links from host
* Running falco-driver-loader for: falco version=0.35.0, driver version=5.0.1+driver, arch=aarch64, kernel release=5.15.0-41-generic, kernel version=44
* Running falco-driver-loader with: driver=module, compile=yes, download=yes

================ Cleaning phase ================

* 1. Check if kernel module 'falco' is still loaded:
- OK! There is no 'falco' module loaded.

* 2. Check all versions of kernel module 'falco' in dkms:
- OK! There are no 'falco' module versions in dkms.

[SUCCESS] Cleaning phase correctly terminated.

================ Cleaning phase ================

* Looking for a falco module locally (kernel 5.15.0-41-generic)
* Filename 'falco_ubuntu-generic_5.15.0-41-generic_44.ko' is composed of:
 - driver name: falco
 - target identifier: ubuntu-generic
 - kernel release: 5.15.0-41-generic
 - kernel version: 44
* Trying to download a prebuilt falco module from https://download.falco.org/driver/5.0.1%2Bdriver/aarch64/falco_ubuntu-generic_5.15.0-41-generic_44.ko
curl: (28) Resolving timed out after 5000 milliseconds
Unable to find a prebuilt falco module
install: /usr/lib/gcc/aarch64-linux-gnu/5/
* Trying to dkms install falco module with GCC /usr/bin/gcc
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"

Creating symlink /var/lib/dkms/falco/5.0.1+driver/source ->
                 /usr/src/falco-5.0.1+driver

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'/tmp/falco-dkms-make'...(bad exit status: 2)
* Running dkms build failed, dumping /var/lib/dkms/falco/5.0.1+driver/build/make.log (with GCC /usr/bin/gcc)
DKMS make.log for falco-5.0.1+driver for kernel 5.15.0-41-generic (aarch64)
Thu Jun 15 07:28:54 UTC 2023
'/tmp/falco-dkms-make' -C /lib/modules/5.15.0-41-generic/build M=/var/lib/dkms/falco/5.0.1+driver/build modules
make[1]: Entering directory '/host/usr/src/linux-headers-5.15.0-41-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
  You are using:           gcc (Debian 5.5.0-12) 5.5.0 20171010
  CC [M]  /var/lib/dkms/falco/5.0.1+driver/build/main.o
gcc: error: unrecognized command line option '-mbranch-protection=pac-ret+leaf+bti'
gcc: error: unrecognized command line option '-fpatchable-function-entry=2'
gcc: error: unrecognized command line option '-mstack-protector-guard=sysreg'
gcc: error: unrecognized command line option '-mstack-protector-guard-reg=sp_el0'
gcc: error: unrecognized command line option '-mstack-protector-guard-offset=1400'
make[2]: *** [scripts/Makefile.build:285: /var/lib/dkms/falco/5.0.1+driver/build/main.o] Error 1
make[1]: *** [Makefile:1875: /var/lib/dkms/falco/5.0.1+driver/build] Error 2
make[1]: Leaving directory '/host/usr/src/linux-headers-5.15.0-41-generic'
make: *** [Makefile:16: all] Error 2
install: /usr/lib/gcc/aarch64-linux-gnu/5/
* Trying to dkms install falco module with GCC /usr/bin/gcc-5
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'/tmp/falco-dkms-make'...(bad exit status: 2)
* Running dkms build failed, dumping /var/lib/dkms/falco/5.0.1+driver/build/make.log (with GCC /usr/bin/gcc-5)
DKMS make.log for falco-5.0.1+driver for kernel 5.15.0-41-generic (aarch64)
Thu Jun 15 07:28:54 UTC 2023
'/tmp/falco-dkms-make' -C /lib/modules/5.15.0-41-generic/build M=/var/lib/dkms/falco/5.0.1+driver/build modules
make[1]: Entering directory '/host/usr/src/linux-headers-5.15.0-41-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
  You are using:           gcc-5 (Debian 5.5.0-12) 5.5.0 20171010
  CC [M]  /var/lib/dkms/falco/5.0.1+driver/build/main.o
gcc-5: error: unrecognized command line option '-mbranch-protection=pac-ret+leaf+bti'
gcc-5: error: unrecognized command line option '-fpatchable-function-entry=2'
gcc-5: error: unrecognized command line option '-mstack-protector-guard=sysreg'
gcc-5: error: unrecognized command line option '-mstack-protector-guard-reg=sp_el0'
gcc-5: error: unrecognized command line option '-mstack-protector-guard-offset=1400'
make[2]: *** [scripts/Makefile.build:285: /var/lib/dkms/falco/5.0.1+driver/build/main.o] Error 1
make[1]: *** [Makefile:1875: /var/lib/dkms/falco/5.0.1+driver/build] Error 2
make[1]: Leaving directory '/host/usr/src/linux-headers-5.15.0-41-generic'
make: *** [Makefile:16: all] Error 2
install: /usr/lib/gcc/aarch64-linux-gnu/6/
* Trying to dkms install falco module with GCC /usr/bin/gcc-6
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'/tmp/falco-dkms-make'...(bad exit status: 2)
* Running dkms build failed, dumping /var/lib/dkms/falco/5.0.1+driver/build/make.log (with GCC /usr/bin/gcc-6)
DKMS make.log for falco-5.0.1+driver for kernel 5.15.0-41-generic (aarch64)
Thu Jun 15 07:28:55 UTC 2023
'/tmp/falco-dkms-make' -C /lib/modules/5.15.0-41-generic/build M=/var/lib/dkms/falco/5.0.1+driver/build modules
make[1]: Entering directory '/host/usr/src/linux-headers-5.15.0-41-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
  You are using:           gcc-6 (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
  CC [M]  /var/lib/dkms/falco/5.0.1+driver/build/main.o
gcc-6: error: unrecognized command line option '-mbranch-protection=pac-ret+leaf+bti'
gcc-6: error: unrecognized command line option '-fpatchable-function-entry=2'
gcc-6: error: unrecognized command line option '-mstack-protector-guard=sysreg'; did you mean '-fstack-protector-strong'?
gcc-6: error: unrecognized command line option '-mstack-protector-guard-reg=sp_el0'; did you mean '-fstack-protector-all'?
gcc-6: error: unrecognized command line option '-mstack-protector-guard-offset=1400'; did you mean '-fstack-protector-strong'?
make[2]: *** [scripts/Makefile.build:285: /var/lib/dkms/falco/5.0.1+driver/build/main.o] Error 1
make[1]: *** [Makefile:1875: /var/lib/dkms/falco/5.0.1+driver/build] Error 2
make[1]: Leaving directory '/host/usr/src/linux-headers-5.15.0-41-generic'
make: *** [Makefile:16: all] Error 2
install: /usr/lib/gcc/aarch64-linux-gnu/8/
* Trying to dkms install falco module with GCC /usr/bin/gcc-8
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'/tmp/falco-dkms-make'...(bad exit status: 2)
* Running dkms build failed, dumping /var/lib/dkms/falco/5.0.1+driver/build/make.log (with GCC /usr/bin/gcc-8)
DKMS make.log for falco-5.0.1+driver for kernel 5.15.0-41-generic (aarch64)
Thu Jun 15 07:28:56 UTC 2023
'/tmp/falco-dkms-make' -C /lib/modules/5.15.0-41-generic/build M=/var/lib/dkms/falco/5.0.1+driver/build modules
make[1]: Entering directory '/host/usr/src/linux-headers-5.15.0-41-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
  You are using:           gcc-8 (Debian 8.3.0-6) 8.3.0
  CC [M]  /var/lib/dkms/falco/5.0.1+driver/build/main.o
gcc-8: error: unrecognized command line option '-mbranch-protection=pac-ret+leaf+bti'
gcc-8: error: unrecognized command line option '-mstack-protector-guard=sysreg'; did you mean '-fstack-protector-strong'?
gcc-8: error: unrecognized command line option '-mstack-protector-guard-reg=sp_el0'; did you mean '-fstack-protector-all'?
gcc-8: error: unrecognized command line option '-mstack-protector-guard-offset=1400'; did you mean '-fstack-protector-strong'?
make[2]: *** [scripts/Makefile.build:285: /var/lib/dkms/falco/5.0.1+driver/build/main.o] Error 1
make[1]: *** [Makefile:1875: /var/lib/dkms/falco/5.0.1+driver/build] Error 2
make[1]: Leaving directory '/host/usr/src/linux-headers-5.15.0-41-generic'
make: *** [Makefile:16: all] Error 2
* Trying to load a system falco module, if present
Consider compiling your own falco driver and loading it or getting in touch with the Falco community
root@k8s-master-10:~#

**Comment by Andreagit97** [comment]
Ei @cqrlhz this is a known issue, your kernel is too recent to be compiled with old gcc versions like 5,6,8 that's the reason why the compilation is failing to see https://github.com/falcosecurity/falco/issues/2489, hopefully, we will put in place some improvements for next Falco version. In the meanwhile, you could try the `modern-bpf` probe which doesn't require compiling anything https://falco.org/docs/event-sources/kernel/#modern-ebpf-probe.

**Comment by cqrlhz** [comment]
According to the official documentation, replace helm install falco -n falco --set tty=true falcosecurity/falco with helm install falco falcosecurity/falco \
   --namespace falco \
   --set driver.kind=ebpf can be used to successfully start pods container is normal but cannot trigger rules, there is no trigger record in the log


```
root@k8s-master-10:~# sudo apt-get -y install linux-headers-$(uname -r)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
linux-headers-5.15.0-41-generic is already the newest version (5.15.0-41.44).
linux-headers-5.15.0-41-generic set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 360 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up grub-efi-arm64-signed (1.182~22.04.1+2.06-2ubuntu10) ...
Installing grub to /boot/efi.
Installing for arm64-efi platform.
Installation finished. No error reported.
Processing triggers for shim-signed (1.51+15.4-0ubuntu9) ...
Secure Boot not enabled on this system.
root@k8s-master-10:~# helm repo add falcosecurity https://falcosecurity.github.io/charts
"falcosecurity" has been added to your repositories
root@k8s-master-10:~# helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "falcosecurity" chart repository
Update Complete. ⎈Happy Helming!⎈
root@k8s-master-10:~# kubectl create namespace falco
namespace/falco created
root@k8s-master-10:~# helm install falco falcosecurity/falco \
  --namespace falco \
  --set driver.kind=ebpf
NAME: falco
LAST DEPLOYED: Fri Jun 16 11:24:04 2023
NAMESPACE: falco
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Falco agents are spinning up on each node in your cluster. After a few
seconds, they are going to start monitoring your containers looking for
security issues.


No further action should be required.


Tip:
You can easily forward Falco events to Slack, Kafka, AWS Lambda and more with falcosidekick.
Full list of outputs: https://github.com/falcosecurity/charts/tree/master/falcosidekick.
You can enable its deployment with `--set falcosidekick.enabled=true` or in your values.yaml.
See: https://github.com/falcosecurity/charts/blob/master/falcosidekick/values.yaml for configuration values.
root@k8s-master-10:~# kubectl get pods -n falco
NAME          READY   STATUS    RESTARTS   AGE
falco-hzrtt   2/2     Running   0          2m7s
falco-lbv4d   1/2     Running   0          2m7s
falco-p9htp   1/2     Running   0          2m7s
root@k8s-master-10:~# kubectl get pods -n falco
NAME          READY   STATUS    RESTARTS   AGE
falco-hzrtt   2/2     Running   0          2m20s
falco-lbv4d   1/2     Running   0          2m20s
falco-p9htp   2/2     Running   0          2m20s
root@k8s-master-10:~# kubectl get pods -n falco
NAME          READY   STATUS    RESTARTS   AGE
falco-hzrtt   2/2     Running   0          2m27s
falco-lbv4d   1/2     Running   0          2m27s
falco-p9htp   2/2     Running   0          2m27s
root@k8s-master-10:~# kubectl get pods -n falco
NAME          READY   STATUS    RESTARTS   AGE
falco-hzrtt   2/2     Running   0          2m42s
falco-lbv4d   2/2     Running   0          2m42s
falco-p9htp   2/2     Running   0          2m42s
root@k8s-master-10:~# kubectl exec -it falco-hzrtt -n falco -- sh -c "cat /etc/shadow"
Defaulted container "falco" out of: falco, falcoctl-artifact-follow, falco-driver-loader (init), falcoctl-artifact-install (init)
root:*:19499:0:99999:7:::
daemon:*:19499:0:99999:7:::
bin:*:19499:0:99999:7:::
sys:*:19499:0:99999:7:::
sync:*:19499:0:99999:7:::
games:*:19499:0:99999:7:::
man:*:19499:0:99999:7:::
lp:*:19499:0:99999:7:::
mail:*:19499:0:99999:7:::
news:*:19499:0:99999:7:::
uucp:*:19499:0:99999:7:::
proxy:*:19499:0:99999:7:::
www-data:*:19499:0:99999:7:::
backup:*:19499:0:99999:7:::
list:*:19499:0:99999:7:::
irc:*:19499:0:99999:7:::
gnats:*:19499:0:99999:7:::
nobody:*:19499:0:99999:7:::
_apt:*:19499:0:99999:7:::
root@k8s-master-10:~# kubectl logs -l app.kubernetes.io/name=falco -n falco
Defaulted container "falco" out of: falco, falcoctl-artifact-follow, falco-driver-loader (init), falcoctl-artifact-install (init)
Defaulted container "falco" out of: falco, falcoctl-artifact-follow, falco-driver-loader (init), falcoctl-artifact-install (init)
Defaulted container "falco" out of: falco, falcoctl-artifact-follow, falco-driver-loader (init), falcoctl-artifact-install (init)
Fri Jun 16 03:25:14 2023: Falco version: 0.35.0 (aarch64)
Fri Jun 16 03:25:14 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
Fri Jun 16 03:25:14 2023: Loading rules from file /etc/falco/falco_rules.yaml
Fri Jun 16 03:25:14 2023: The chosen syscall buffer dimension is: 8388608 bytes (8 MBs)
Fri Jun 16 03:25:14 2023: Starting health webserver with threadiness 3, listening on port 8765
Fri Jun 16 03:25:14 2023: Enabled event sources: syscall
Fri Jun 16 03:25:14 2023: Opening 'syscall' source with BPF probe. BPF probe path: /root/.falco/falco-bpf.o
Fri Jun 16 03:26:04 2023: Falco version: 0.35.0 (aarch64)
Fri Jun 16 03:26:04 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
Fri Jun 16 03:26:04 2023: Loading rules from file /etc/falco/falco_rules.yaml
Fri Jun 16 03:26:04 2023: The chosen syscall buffer dimension is: 8388608 bytes (8 MBs)
Fri Jun 16 03:26:04 2023: Starting health webserver with threadiness 3, listening on port 8765
Fri Jun 16 03:26:04 2023: Enabled event sources: syscall
Fri Jun 16 03:26:04 2023: Opening 'syscall' source with BPF probe. BPF probe path: /root/.falco/falco-bpf.o
Fri Jun 16 03:25:45 2023: Falco version: 0.35.0 (aarch64)
Fri Jun 16 03:25:45 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
Fri Jun 16 03:25:45 2023: Loading rules from file /etc/falco/falco_rules.yaml
Fri Jun 16 03:25:45 2023: The chosen syscall buffer dimension is: 8388608 bytes (8 MBs)
Fri Jun 16 03:25:45 2023: Starting health webserver with threadiness 3, listening on port 8765
Fri Jun 16 03:25:45 2023: Enabled event sources: syscall
Fri Jun 16 03:25:45 2023: Opening 'syscall' source with BPF probe. BPF probe path: /root/.falco/falco-bpf.o
```

**Comment by Andreagit97** [comment]
uhm strange I tried it with the following commands and it works

* deploy Falco

```bash
helm install falco falcosecurity/falco \
    --set driver.kind=ebpf \
    --set tty=true
```

* enter the falco pod from another terminal

```bash
k exec -it <falco-njfdn> -- /bin/bash
```
* see falco pod logs

```bash
k logs falco-njfdn
```

Output:
```
Fri Jun 16 11:25:03 2023: Falco version: 0.35.0 (x86_64)
Fri Jun 16 11:25:03 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
Fri Jun 16 11:25:03 2023: Loading rules from file /etc/falco/falco_rules.yaml
Fri Jun 16 11:25:03 2023: The chosen syscall buffer dimension is: 8388608 bytes (8 MBs)
Fri Jun 16 11:25:03 2023: Starting health webserver with threadiness 8, listening on port 8765
Fri Jun 16 11:25:03 2023: Enabled event sources: syscall
Fri Jun 16 11:25:03 2023: Opening 'syscall' source with BPF probe. BPF probe path: /root/.falco/falco-bpf.o
11:28:34.704973861: Notice A shell was spawned in a container with an attached terminal (user=root user_loginuid=-1 k8s.ns=default k8s.pod=falco-njfdn container=94e4167b2bac shell=bash parent=runc cmdline=bash pid=27371 terminal=34817 container_id=94e4167b2bac image=docker.io/falcosecurity/falco-no-driver)
```

Could you confirm that these steps don't work for you?

**Comment by Andreagit97** [comment]
any news?
