### ISSUE TITLE
No log output on Debian-based distros

### ISSUE THREAD

**Issue by johananl** [falcosecurity/falco#2643]
**Describe the bug**

In #1697 we set `StandardOutput=null` in `scripts/rpm/falco.service` to avoid logging to `/var/log/messages` in Red Hat-based distros. In #2242 we moved away from distro-specific unit files and added `scripts/systemd/falco-kmod.service`. This file has `StandardOutput=null`.

When running Falco using `scripts/systemd/falco-kmod.service` on Ubuntu, I'm getting no output in `journalctl -u falco-kmod`. Removing `StandardOutput=null` from the unit file fixes the problem.

Based on https://github.com/falcosecurity/falco/pull/1697#issuecomment-1281044891 I suspect the logging to `/var/log/messages` by default **doesn't affect Debian-based distros**. I'm not sure how to tackle this but IMO not seeing logs in `journalctl` is counterintuitive to Debian users. We may want to do one of the following:

- Provide a default which works for most common distros.
- Provide commented-out alternatives in the systemd unit files and document distor-specific configuration.
- Find a different way to handle the Red Hat-specific problem. Do all systemd units without `StandardOutput=null` log to `/var/log/messages` on Red Hat-based distros? 😕 

**How to reproduce it**

Run Falco using the provided `scripts/systemd/falco-kmod.service` on Ubuntu (I used `18.04.6` but I don't think the precise version matters).

**Expected behaviour**

Logs show up in `journalctl`.

**Screenshots**

**Environment**

- Falco version:
```
Thu Jun 15 14:03:01 2023: Falco version: 0.35.0 (x86_64)
Thu Jun 15 14:03:01 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
{"default_driver_version":"5.0.1+driver","driver_api_version":"4.0.0","driver_schema_version":"2.0.0","engine_version":"17","falco_version":"0.35.0","libs_version":"0.11.2","plugin_api_version":"3.0.0"}
```
- System info:

- Cloud provider or hardware configuration:
- OS:
```
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

- Kernel:
`Linux <redacted> 5.4.0-1109-azure #115~18.04.1-Ubuntu SMP Mon May 22 20:06:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

- Installation method:
DEB

**Additional context**

**Comment by Andreagit97** [comment]
Hi! thank you for reporting this, we will take a look ASAP!

**Comment by therealbobo** [comment]
@FedeDP, what a memory! I practically opened the same PR some time ago: https://github.com/falcosecurity/falco/pull/2499 **If** the common opinion is to keep `StandardOutput=null`, I strongly suggest to document somewhere the reason for it. 😄

**Comment by Andreagit97** [comment]
Sorry for the delay, I tried just now on an ubuntu machine:

```
6.2.0-1010-aws #10~22.04.1-Ubuntu
```

and with `StandardOutput=null` I can see logs in `journalctl`. So I would say that each distro has its own behavior. 

> Provide commented-out alternatives in the systemd unit files and document distor-specific configuration.

Probably this is the most reasonable solution at the moment :thinking:

**Comment by Andreagit97** [comment]
I was opening a PR to comment on our systemd units but probably the best place is our website, probably we should add something in our systemd section, this is what we know at the moment:
- Ubuntu 18.04: remove this line to see logs with `journalctl`
- Ubuntu 22.04: keep this line as it is to see logs with `journalctl`
- RHEL distros: keep this line as it is to avoid polluting `/var/log/messages`

**Comment by leogr** [comment]
> When running Falco using `scripts/systemd/falco-kmod.service` on Ubuntu, I'm getting no output in `journalctl -u falco-kmod`. Removing `StandardOutput=null` from the unit file fixes the problem.

IIRC, regardless of `StandardOutput=null`, alerts should directly forwarded by Falco's `syslog_output` which is enabled by default :point_down: 
https://github.com/falcosecurity/falco/blob/b2374b3c196cafb1bc2c2dce3b92b2d6db7af371/falco.yaml#L339-L343

So, I'd expect to see logs show up in `journalctl` event with `StandardOutput=null` in any distros. Does it make sense?
cc @Andreagit97 @johananl @FedeDP @therealbobo 


If this is not the case, the root cause may be somewhere else, and not a documentation problem :thinking:

**Comment by johananl** [comment]
I can't reproduce this now on Ubuntu 18.04.6, namely I **can** see logs in journalctl.
I *suspect* I may have used the wrong systemd unit name in the first instance 🙈 Since I can't tell for sure, let's assume a mistake on my end. I'll report here again in case I am certain there is an issue.

I'll leave it to you folks to decide whether to close the issue or update the docs just in case.

Thanks for your help anyway!

**Comment by vjjmiras** [comment]
Hey @johananl, I haven't been able to reproduce it either. I've observed the same behavior (despite a difference in the color of the journald entry) in both 18.04 and 22.04.

To achieve what you reported, we should disable the `syslog_output` as well, so it could be that when trying different options, one of them was misconfiguring Falco.

**Comment by Andreagit97** [comment]
Thank you all guys for the help, i will close this for the moment, feel free to reopen if you face new issues :)
