### ISSUE TITLE
SLSA Provenance Attestation for Falco

### ISSUE THREAD

**Issue by LucaGuerra** [falcosecurity/falco#2649]
**Motivation**

We have signatures with cosign, and our next step is to add provenance attestations to images and artifacts as well, in the same way we have in Falcoctl

cc @cpanato @developer-guy

**Comment by cpanato** [comment]
i can work on that, i will try to do this next week

**Comment by Andreagit97** [comment]
any news here?

**Comment by cpanato** [comment]
not yet, running behind, sorry, i will add this to my backlog for next week

**Comment by Andreagit97** [comment]
don't worry we are in no hurry :)

**Comment by developer-guy** [comment]
I can do it @cpanato, if you let me to do that 🫡

**Comment by cpanato** [comment]
this will require a bit more time, falco is not using goreleaser :) (i know this is in c++) and will require a bit more learning in the release pipeline before we start the implementation
