### ISSUE TITLE
[FEATURE] Enhance rules loading based on tags suitable to enable those rules only on certain host groups

### ISSUE THREAD

**Issue by incertum** [falcosecurity/falco#2660]
**Motivation**

Assess current `tags` options and derive what's currently possible vs what possible extensions are needed to support loading a subset of Falco rules only for a predefined host group. The goal is to manage one consolidated rules files and re-use it for different deployments.

**Additional context**

See https://github.com/falcosecurity/falco/issues/2506#issuecomment-1607502096

**Comment by incertum** [comment]
Do we still need this?

**Comment by Andreagit97** [comment]
in the long term i think yes, but IMO it's not a top priority now

**Comment by incertum** [comment]
Agreed.
