### ISSUE TITLE
Enable build CI for Windows/MacOS to improve multi-platform compatibility

### ISSUE THREAD

**Issue by LucaGuerra** [falcosecurity/falco#2672]
In https://github.com/falcosecurity/libs/ we are able to perform some basic builds on platforms that are not Linux, namely Windows and MacOS. While we don't provide specific artifacts for those platforms there's no reason why the main code shouldn't be multiplatform, especially since we can now build cross platform plugins. Of course kmod or ebpf are strictly Linux-only but the generic code should work. Given the fact that we're also working on WASM this effort might be much less than expected.

**Comment by therealbobo** [comment]
I think we can close this. cc @LucaGuerra
