### ISSUE TITLE
Deprecate falco-driver-loader

### ISSUE THREAD

**Issue by LucaGuerra** [falcosecurity/falco#2675]
This item keeps track of the effort for implementing this section of the artifact distribution proposal: https://github.com/falcosecurity/falco/blob/master/proposals/20221129-artifacts-distribution.md#deprecate-falco-driver-loader .

> At the time of writing, `falco-driver-loader` is a shell script shipped in a bundle with Falco that has the responsibility of installing a driver by either downloading it from our distribution channels or trying to build it on-the-fly.

> Our experience showed all the limitations of this approach, and it's now clear that such as script is hard to maintain. Furthermore, its responsibility overlaps with our aim to use falcoctl as the tool for managing artifacts.

A good candidate for its replacement is `falcoctl`. It is already bundled with Falco and would be then used to install the driver as well.

**Comment by FedeDP** [comment]
For the new falcoctl implementation deprecated functionalities, have a look at: https://github.com/falcosecurity/falco/issues/2763#issuecomment-1805453547
