### ISSUE TITLE
The impact of falco on system performance

### ISSUE THREAD

**Issue by cytianying** [falcosecurity/falco#2683]
Is there any software for falco performance testing? Want to test how much the default rules affect system performance. Can you post a link to the relevant software? Thanks.

**Comment by incertum** [comment]
In flight (it will take time), tracked here https://github.com/falcosecurity/falco/issues/2435.

In addition, the Falco `metrics` feature in `falco.yaml` is one way of getting Falco specific stats including resource utilization if you prefer having this information from Falco natively. The description of this feature might be of help as well.

Furthermore, https://falco.org/blog/adaptive-syscalls-selection/ or https://github.com/falcosecurity/libs/blob/master/proposals/20230530-driver-kernel-testing-framework.md#why-does-kernel-testing-matter provide some insights into the inner workings of Falco and what can affect performance.

**Comment by incertum** [comment]
Please keep in mind that your test results will be driven by the type of workload and general load of the server you choose for testing.  Results may not generalize well if you then choose to deploy Falco on servers with very diverse workloads and much higher overall load.

**Comment by incertum** [comment]
One more comment: Besides Falco's own utilization, I would check on general host system metrics, also related to network or I/O or just general contention or scheduling of workloads impact. Compare before and while deploying Falco while trying to keep most things as stable as possible.

**Comment by incertum** [comment]
Closing this in favor of the issue mentioned before https://github.com/falcosecurity/falco/issues/2435.
