### ISSUE TITLE
Improve `-pk` as needed by latest "Style Guide of Falco Rules"

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco#2699]
**Motivation**

See https://github.com/falcosecurity/falco-website/pull/1094#pullrequestreview-1550223503.

**Feature**

Change the `-p` behavior as follow:
   - when only `-pc`  :point_right:  `container_id=%container.id container_image=%container.image.repository container_image_tag=%container.image.tag container_name=%container.name`
   - when `-pk`  :point_right:  as above plus ` k8s_ns=%k8s.ns.name k8s_pod_name=%k8s.pod.name` 

**Alternatives**

:thinking: 

**Additional context**

cc @falcosecurity/falco-maintainers 

See https://github.com/falcosecurity/falco-website/pull/1094

https://github.com/falcosecurity/falco/blob/743c7c49d50bf392d96134484bb305580d7310e8/userspace/falco/app/actions/init_falco_engine.cpp#L23-L58

https://github.com/falcosecurity/falco/blob/743c7c49d50bf392d96134484bb305580d7310e8/userspace/engine/rule_loader_compiler.cpp#L302-L316

**Comment by incertum** [comment]
This is great, thank you!
