### ISSUE TITLE
falco & falcosidekick webui is not working - Azure AKS v1.25.6

### ISSUE THREAD

**Issue by zohebk8s** [falcosecurity/falco#2702]
Hi Team,

I've deployed Falco & Falcosidekick yesterday by using the below commands. It was working fine till yesterday, but now I am able to access the URL without events/content.

Below commands used for deployment: 

https://falco.org/docs/getting-started/try-falco/try-falcosidekick-on-kubernetes/  ( This URL itself is not available today)

helm repo add falcosecurity https://falcosecurity.github.io/charts
helm repo update
kubectl create namespace falco
helm install falco -n falco --set tty=true falcosecurity/falco   --set falcosidekick.enabled=true   --set falcosidekick.webui.enabled=true

Error/Output: Falco internal: syscall event drop. 192 system calls dropped in last second.

<img width="960" alt="image" src="https://github.com/falcosecurity/falco/assets/128701612/cd9ef295-68af-4b81-a18e-cd5fd7935d8a">

**Comment by Issif** [comment]
Hi,

Do you have any logs in the falcosidekick-ui pods?

**Comment by zohebk8s** [comment]
I've restarted Azure VMSS yesterday. Now I can see events in UI.

Just a question: What will be the retention of those events/data? How long it will be stored? or it's just a runtime events?

Logs from UI Pods:

shaik [ ~ ]$ kubectl logs falco-falcosidekick-ui-b69f8dcb7-dk5vx -n falco

Defaulted container "falco" out of: falco, falcoctl-artifact-follow, falco-driver-loader (init), falcoctl-artifact-install (init)
Fri Jul 28 08:16:57 2023: Falco version: 0.35.1 (x86_64)
Fri Jul 28 08:16:57 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
Fri Jul 28 08:16:57 2023: Loading rules from file /etc/falco/falco_rules.yaml
Fri Jul 28 08:16:57 2023: The chosen syscall buffer dimension is: 8388608 bytes (8 MBs)
Fri Jul 28 08:16:57 2023: Starting health webserver with threadiness 2, listening on port 8765
Fri Jul 28 08:16:57 2023: Loaded event sources: syscall
Fri Jul 28 08:16:57 2023: Enabled event sources: syscall
Fri Jul 28 08:16:57 2023: Opening 'syscall' source with Kernel module
{"hostname":"falco-dfzsp","output":"08:17:03.081435325: Notice Unexpected connection to K8s API Server from container (command=node-agent pid=2488 k8s.ns=kubescape k8s.pod=node-agent-w72fb container=72a0fa164f7f image=quay.io/kubescape/node-agent:v0.1.77 connection=10.224.1.97:36686->10.0.0.1:443)","priority":"Notice","rule":"Contact K8S API Server From Container","source":"syscall","tags":["T1565","container","k8s","mitre_discovery","network"],"time":"2023-07-28T08:17:03.081435325Z", "output_fields": {"container.id":"72a0fa164f7f","container.image.repository":"quay.io/kubescape/node-agent","container.image.tag":"v0.1.77","evt.time":1690532223081435325,"fd.name":"10.224.1.97:36686->10.0.0.1:443","k8s.ns.name":"kubescape","k8s.pod.name":"node-agent-w72fb","proc.cmdline":"node-agent","proc.pid":2488}}
shaik [ ~ ]$

**Comment by Issif** [comment]
I can't explain why it failed, let's wait and see if it happens again.

By default, the retention is infinite. You can set a TTL with `--set falcosidekick.webui.ttl` (in seconds). I'm planning to allow to set the TTL with `s`, `m`, `d` for next release.

**Comment by Andreagit97** [comment]
is this still an issue or we can close this?
