### ISSUE TITLE
what's the difference between in and intersects

### ISSUE THREAD

**Issue by chips79** [falcosecurity/falco#2707]
Hi Team,
I m studying about falco k8s_audit_rules. There is a problem that i can't uderstanding in and intersects.what's the difference between then when i use in condition operator? can you explain it?
![image](https://github.com/falcosecurity/falco/assets/23360311/6e790945-c641-4ea3-ac0e-d639d41cd519)

**Comment by Andreagit97** [comment]
ei @chips79 sorry we miss this :/

**in**
check if the provided set (could have just one element) is completely contained in another set:
**example**
```
(a) in (a,b,c) -> yes
(b,c) in (a,b,c) -> yes
(b,c,d) in (a,b,c) -> no
```

**intersect**
check if the provided set (could have just one element) has an intersection with another set:
**example**
```
(a) in (a,b,c) -> yes
(b,c) in (a,b,c) -> yes
(b,c,d) in (a,b,c) -> yes
```

@vjjmiras probably we need to improve the docs, @chips79 thank you for reporting!

**Comment by Andreagit97** [comment]
i will close this, feel free to re-open if needed :)
@vjjmiras do you think we can improve the docs here?
