### ISSUE TITLE
Trivy Azure Compliance Error

### ISSUE THREAD

**Issue by Susanta2000** [falcosecurity/falco#2712]
Hi there, I want to run compliance scan in Azure using trivy but it's giving me error. Is trivy support azure?
**My command is:** trivy k8s cluster --compliance=k8s-nsa --report all
**Error is:** " 2023-08-01T11:28:32.007+0530	FATAL	get k8s artifacts with node info error: running node-collector job: warning event received: Job has reached the specified backoff limit (BackoffLimitExceeded) "

**Comment by Andreagit97** [comment]
ei @Susanta2000 probably you have to open the issue here https://github.com/aquasecurity/trivy/issues, this page is used only for Falco issues

**Comment by Susanta2000** [comment]
> ei @Susanta2000 probably you have to open the issue here https://github.com/aquasecurity/trivy/issues, this page is used only for Falco issues

SORRY @Andreagit97 .
