### ISSUE TITLE
Gitlab registry does not support falco artifacts

### ISSUE THREAD

**Issue by eminaktas** [falcosecurity/falco#2714]
**Describe the bug**

I can't push the plugin and rules images to the Gitlab registry. Also, I created a ticket on the GitLab side [here](https://gitlab.com/gitlab-org/container-registry/-/issues/1089).

**How to reproduce it**

```
$ crane copy ghcr.io/falcosecurity/rules/falco-rules:1 registry.gitlab.com/x/falcosecurity/rules/k8saudit-rules:1
```

**Expected behaviour**

I was expecting to see the images were pushed to the Gitlab registry.

**Comment by jasondellaluce** [comment]
cc @alacuku @loresuso

**Comment by eminaktas** [comment]
Thanks to the @developer-guy(Batuhan)'s PR. It will be fixed. The PR has been approved last time we checked. https://gitlab.com/gitlab-org/container-registry/-/merge_requests/1375

**Comment by developer-guy** [comment]
The PR got merged and added one of the features will be supported 16.3, yay! We can close this issue if you want folks, or we can keep it to keep updates from GitLab's side.

**Comment by eminaktas** [comment]
This issue now fixed. So, I am closing this issue. Thanks for the effort :rocket:
