### ISSUE TITLE
No driver for kernel version 5.15.117-1_1.14.3

### ISSUE THREAD

**Issue by Ca20009** [falcosecurity/falco#2730]
Just updated our EKS to 1.24, nodes updated with it to latest bottle rocket OS. Has worked fine previously. Now  falco won't start, see attached - trying to download the driver. If you go to the driver location it is not available, latest version is 1_1.14.2. Hence falco won't start as it get's a 404 on the driver

Try to launch Falco on a linux Kernel version 5.15.117-1_1.14.3

(in our case) upgrade EKS to 1.24, use latest bottlerocket AMI as node group.  Launch falco with ebpf driver

Falco launches without error

![image](https://github.com/falcosecurity/falco/assets/134835628/d0d3a4a3-28fe-4fc5-9991-b8656e2a4830)

- Falco version:
0.35.0
- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel: 5.15.117-1_1.14.3

- Installation method: Helm/Kubernetes

**Additional context**

**Comment by Andreagit97** [comment]
ei @Ca20009 thank you for reporting, have you ever tried the `modern-bpf` probe?

**Comment by Ca20009** [comment]
I did not know that - I will look into this.

Thanks

**Comment by Andreagit97** [comment]
Let us know if it works :)

**Comment by FedeDP** [comment]
Also, now the drivers are available:
> 2023-08-23T10:53:31.000Z        1005.1 kB      [falco_bottlerocket_5.15.117_1_1.14.3-aws.ko](https://download.falco.org/driver/5.0.1%2Bdriver/x86_64/falco_bottlerocket_5.15.117_1_1.14.3-aws.ko)
2023-08-23T10:53:30.000Z        3.6 MB         [falco_bottlerocket_5.15.117_1_1.14.3-aws.o](https://download.falco.org/driver/5.0.1%2Bdriver/x86_64/falco_bottlerocket_5.15.117_1_1.14.3-aws.o)

**Comment by FedeDP** [comment]
/close
Since this is now solved.
