### ISSUE TITLE
Driver error while deploying Falco

### ISSUE THREAD

**Issue by prasho2009** [falcosecurity/falco#2734]
'/tmp/falco-dkms-make' -C /lib/modules/5.15.0-1042-azure/build M=/var/lib/dkms/falco/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/build modules
make[1]: Entering directory '/host/usr/src/linux-headers-5.15.0-1042-azure'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
  You are using:           gcc-5 (Debian 5.5.0-12) 5.5.0 20171010
  CC [M]  /var/lib/dkms/falco/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/build/main.o
gcc-5: error: unrecognized command line option '-mharden-sls=all'
make[2]: *** [scripts/Makefile.build:297: /var/lib/dkms/falco/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/build/main.o] Error 1
make[1]: *** [Makefile:1914: /var/lib/dkms/falco/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/build] Error 2
make[1]: Leaving directory '/host/usr/src/linux-headers-5.15.0-1042-azure'
make: *** [Makefile:16: all] Error 2
Consider compiling your own falco driver and loading it or getting in touch with the Falco community
Mon Aug 21 12:08:54 2023: Falco version 0.30.0 (driver version 3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4)
Mon Aug 21 12:08:54 2023: Falco initialized with configuration file /etc/falco/falco.yaml
Mon Aug 21 12:08:54 2023: Loading rules from file /etc/falco/falco_rules.yaml:
Mon Aug 21 12:08:54 2023: Loading rules from file /etc/falco/falco_rules.local.yaml:
Mon Aug 21 12:08:54 2023: Unable to load the driver.
Mon Aug 21 12:08:54 2023: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded.. Exiting.
PS C:\Users\SlocAdm>

**Comment by prasho2009** [comment]
I used below command to deploy Falco on AKS cluster.

helm repo add falcosecurity https://falcosecurity.github.io/charts
helm install falco falcosecurity/falco \
    --version 1.16.0 \
    --create-namespace \
    --namespace sec-falco-system

**Comment by Andreagit97** [comment]
Hi! thank you for reporting! Have you ever tried a recent Falco version like [`0.35.1`](https://github.com/falcosecurity/falco/releases/tag/0.35.1)? with you kernel version you should be able to use the [modern bpf probe](https://falco.org/docs/event-sources/kernel/#modern-ebpf-probe)

**Comment by Corollary-kor** [comment]
@Andreagit97 I have a same issue in Falco version 0.35.1

**Comment by prasho2009** [comment]
Hi @Andreagit97 , Yes I did. below are error and events

PS C:\Users\SlocAdm> kubectl -n sec-falco-system get po
NAME          READY   STATUS                  RESTARTS         AGE
falco-29l88   0/2     Init:CrashLoopBackOff   10 (2m16s ago)   28m
falco-2jrj5   0/2     Init:CrashLoopBackOff   10 (2m26s ago)   28m
falco-4jv7p   0/2     Init:CrashLoopBackOff   10 (2m11s ago)   28m
falco-6m5wk   0/2     Init:CrashLoopBackOff   10 (2m10s ago)   28m
falco-7sc77   0/2     Init:CrashLoopBackOff   10 (2m34s ago)   28m
falco-hvtdw   0/2     Init:CrashLoopBackOff   10 (2m14s ago)   28m
falco-k6tck   0/2     Init:CrashLoopBackOff   10 (2m3s ago)    28m
falco-qp2zs   0/2     Init:CrashLoopBackOff   10 (2m25s ago)   28m
falco-s8wft   0/2     Init:CrashLoopBackOff   10 (2m5s ago)    28m

                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  28m                    default-scheduler  Successfully assigned sec-falco-system/falco-s8wft to aks-default1-66400434-vmss000005
  Normal   Pulled     28m                    kubelet            Container image "docker.io/falcosecurity/falco-driver-loader:0.35.1" already present on machine
  Normal   Created    28m                    kubelet            Created container falco-driver-loader
  Normal   Started    28m                    kubelet            Started container falco-driver-loader
  Normal   Pulling    27m                    kubelet            Pulling image "docker.io/falcosecurity/falcoctl:0.5.1"
  Normal   Pulled     27m                    kubelet            Successfully pulled image "docker.io/falcosecurity/falcoctl:0.5.1" in 2.808042017s (2.808057317s including waiting)
  Normal   Created    26m (x5 over 27m)      kubelet            Created container falcoctl-artifact-install
  Normal   Started    26m (x5 over 27m)      kubelet            Started container falcoctl-artifact-install
  Normal   Pulled     26m (x4 over 27m)      kubelet            Container image "docker.io/falcosecurity/falcoctl:0.5.1" already present on machine
  Warning  BackOff    3m14s (x114 over 27m)  kubelet            Back-off restarting failed container

**Comment by prasho2009** [comment]
Init container failing


PS C:\Users\SlocAdm> kubectl -n sec-falco-system describe po falco-29l88 -c falco-driver-loader
error: unknown shorthand flag: 'c' in -c
See 'kubectl describe --help' for usage.
PS C:\Users\SlocAdm> kubectl -n sec-falco-system logs falco-29l88 -c falco-driver-loader
* Setting up /usr/src links from host
* Running falco-driver-loader for: falco version=0.35.1, driver version=5.0.1+driver, arch=x86_64, kernel release=5.15.0-1042-azure, kernel version=49
* Running falco-driver-loader with: driver=bpf, compile=yes, download=yes
* Mounting debugfs
mount: /sys/kernel/debug: cannot mount nodev read-only.
* Filename 'falco_ubuntu-azure_5.15.0-1042-azure_49.o' is composed of:
 - driver name: falco
 - target identifier: ubuntu-azure
 - kernel release: 5.15.0-1042-azure
 - kernel version: 49
* Trying to download a prebuilt eBPF probe from https://download.falco.org/driver/5.0.1%2Bdriver/x86_64/falco_ubuntu-azure_5.15.0-1042-azure_49.o
curl: (6) Could not resolve host: download.falco.org
Unable to find a prebuilt falco eBPF probe
* Trying to compile the eBPF probe (falco_ubuntu-azure_5.15.0-1042-azure_49.o)
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
  You are using:           gcc (Debian 5.5.0-12) 5.5.0 20171010
scripts/mod/modpost: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by scripts/mod/modpost)
scripts/mod/modpost: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by scripts/mod/modpost)
make[2]: *** [scripts/Makefile.modpost:133: /usr/src/falco-5.0.1+driver/bpf/Module.symvers] Error 1
make[1]: *** [Makefile:1829: modules] Error 2
make: *** [Makefile:38: all] Error 2
* eBPF probe located in /root/.falco/5.0.1+driver/x86_64/falco_ubuntu-azure_5.15.0-1042-azure_49.o
* Success: eBPF probe symlinked to /root/.falco/falco-bpf.o
PS C:\Users\SlocAdm> kubectl -n sec-falco-system logs falco-29l88 -c falcoctl-artifact-install
ERRO: unable to fetch index "falcosecurity" with URL "https://falcosecurity.github.io/falcoctl/index.yaml": cannot fetch index: Get "https://falcosecurity.github.io/falcoctl/index.yaml": EOF
PS C:\Users\SlocAdm>

**Comment by Andreagit97** [comment]
uhm this is not the `modern-bpf` probe, it is the legacy one. For the modern one you should type something like
```
helm install falco falcosecurity/falco  --set driver.kind=modern-bpf ...
```

**Comment by prasho2009** [comment]
I tried helm install falco falcosecurity/falco  --set driver.kind=modern-bpf   but no success

PS C:\Users\SlocAdm> kubectl -n sec-falco-system logs falco-2glld -c falco
Error from server (BadRequest): container "falco" in pod "falco-2glld" is waiting to start: PodInitializing
PS C:\Users\SlocAdm> kubectl -n sec-falco-system logs falco-2glld -c falcoctl-artifact-follow
Error from server (BadRequest): container "falcoctl-artifact-follow" in pod "falco-2glld" is waiting to start: PodInitializing
PS C:\Users\SlocAdm> kubectl -n sec-falco-system logs falco-2glld
Defaulted container "falco" out of: falco, falcoctl-artifact-follow, falcoctl-artifact-install (init)
Error from server (BadRequest): container "falco" in pod "falco-2glld" is waiting to start: PodInitializing
PS C:\Users\SlocAdm>

**Comment by Andreagit97** [comment]
thanks! Could you please provide the reason why Falco is failing?
So the usual Falco logs again otherwise I cannot understand what is going on :/

**Comment by prasho2009** [comment]
@Andreagit97  It is working now ! Thank you so much.

init container was failing because of internal DNS issue that solved by allowing the same.

So helm install falco falcosecurity/falco  --set driver.kind=modern-bpf  this worked fine for the reported error

**Comment by Andreagit97** [comment]
thank you, I will close this if there are other issues please feel free to re-open
