### ISSUE TITLE
download a prebuilt falco module : 404 error

### ISSUE THREAD

**Issue by Corollary-kor** [falcosecurity/falco#2735]
**Describe the bug**
no download a prebuilt falco module

**How to reproduce it**
helm install falco ./values.yaml

**Expected behaviour**
pod running state

**Screenshots**
![image](https://github.com/falcosecurity/falco/assets/79095735/56c91a03-7ece-4fba-acd2-9fe96a46e84f)
![image](https://github.com/falcosecurity/falco/assets/79095735/f5978b9e-82d8-4d80-a1e0-07189a63f323)

**Environment**

- Falco version: 0.35.1

- System info: amzn2.x86_64, AWS EKS(1.27, 1.26, 1.25,1.22)

- Cloud provider or hardware configuration:
- OS:

- Kernel: 5.10.186-179.751.amzn2.x86_64, kernel release=5.4.250-166.369.amzn2.x86_64

- Installation method: helm

**Additional context**
I tried to install falco with helm in aws eks 1.27, 1.26, 1.23, but I couldn't download a prebuilt falco module.

However, when I installed it after lowering it to version 1.22, it was installed normally and the pod state became running.

Previously, some users had it in 1.25, but I'm not sure if it's me or a version problem.

**Comment by Andreagit97** [comment]
ei, thank you for reporting, yes the issue is that actually we don't build your kernel -> https://falcosecurity.github.io/kernel-crawler/?arch=x86_64&target=AmazonLinux2&search=5.10.186-179.751.amzn2.x86_64. The kernel crawler should find it in the next days but in the meanwhile you could try the modern eBPF probe https://github.com/falcosecurity/charts/tree/master/falco#deploying-falco-in-kubernetes. It doesn't require any pre-built driver

**Comment by Corollary-kor** [comment]
@Andreagit97  Thanks, it worked out!
After operation, unlike the previous version, there are two pods. Why?
I tried to find it in the docs, but it's too hard to find.
Are there any related resources?

**Comment by Corollary-kor** [comment]
When I changed all the files in the template folder and values.yaml to those in the repo, it also worked with "kind: module".

**Comment by Andreagit97** [comment]
glad it helped! Yes I think that the other pod is `Falcoctl`, this is the chart version in which it was introduced https://github.com/falcosecurity/charts/blob/master/falco/BREAKING-CHANGES.md#300. There are also commands to disable it.
If you want to know more about `falcoctl` you can read something here https://github.com/falcosecurity/falcoctl
