### ISSUE TITLE
Rule to alert on file renaming, deletion

### ISSUE THREAD

**Issue by finid** [falcosecurity/falco#274]
Hello:

Want Falco to alert when a file is renamed or deleted from within a certain directory by a non-system user. So I set up this list:

```
- list: nonsystem_users
  items: [root, user1, user2]
```

Then this rule that references it:

```
- rule: Rename, delete files
  desc: a particular file has been renamed or deleted
  condition: part_dir and evt.type = rename and user.name in (nonsystem_users)
  output: "File below this dir has been renamed (user=%user.name command=%proc.cmdline file=%fd.name)"
  priority: ERROR
  tags: [filesystem]
```

part_dir is a macro that points to the particular directory. Falco did not spew an error after restarting, but the above rule never triggers an alert.

Is there something I'm missing here? In place of `evt.type = rename`, I also used `evt.type = unlink`. It too, did not work.

TIA

**Comment by mstemm** [comment]
I think the best way to debug this is to run sysdig creating a capture file while you perform the rm/mv/etc command that you want to capture. Then we can look at the trace file and see what specific system calls and arguments are used.

Can you attach a trace file that we can use for debugging?

**Comment by finid** [comment]
Thanks for responding @mstemm. I'll run the test again with Sysdig listening. Will report back in a couple of days.

**Comment by finid** [comment]
OK, after testing and debugging with `sysdig`, here's what I found:

For the `rm` command, the associated syscall is `unlinkat` instead of `unlink`, as suggested at [https://sysdig.com/blog/fascinating-world-linux-system-calls](https://sysdig.com/blog/fascinating-world-linux-system-calls).

```
61085 09:37:10.132974650 1 rm (11969) > unlinkat dirfd=4294967196 name=testfalco : rm the file
61086 09:37:10.133066968 1 rm (11969) < unlinkat res=0 
71659 09:37:28.372842760 3 rm (11973) > unlinkat dirfd=4294967196 name=testing 
71660 09:37:28.372935679 3 rm (11973) < unlinkat res=0
``
`
While the `mv` commands goes with the `rename` syscall:

```
19481 10:01:13.904800473 1 mv (12267) > rename 
19482 10:01:13.904858626 1 mv (12267) < rename res=0 oldpath=nofalcons(nofalcons) newpath=falconer(falconer)
```

For the `rmdir` command, here are the syscalls:

```
9317 10:12:26.836140519 1 rmdir (12390) < execve res=0 exe=rmdir args=testme. tid=12390(rmdir) pid=12390(rmdir) ptid=3908(bash) cwd= fdlimit=1024 pgft_maj=0 pgft_min=40 vm_size=360 vm_rss=4 vm_swap=0 comm=rmdir cgroups=cpuset=/.cpu=/.cpuacct=/.io=/.memory=/.devices=/user.slice.freezer=/.net_cls=... env=XDG_VTNR=8.SSH_AGENT_PID=2567.XDG_SESSION_ID=c1.QT_STYLE_OVERRIDE=gtk.TERM=xt... tty=34824 
9381 10:12:26.837341851 1 rmdir (12390) < rmdir res=0 path=testme(testme)
```


With those, I can actually write a single rule instead of 2 or 3 to track file activity under a target directory.

**Comment by mstemm** [comment]
Great, so it looks like you came up with some rules for your use case? If so, mind if I close this issue?

I'd also be curious to see what they were.

**Comment by finid** [comment]
OK, I'll try and update with the new rule over the weekend, then we can close this issue.

**Comment by finid** [comment]
I think I was too optimistic.

Even knowing that `unlinkat` is associated with `rm` operations, this rule does not fire when I delete a file:

```
rule: Delete WP files
  desc: a WP file has been deleted
  condition: wp_dir and evt.type = unlinkat and user.name in (nonsystem_users)
  output: "File below WP dir has been deleted (user=%user.name command=%proc.cmdline file=%fd.name)"
  priority: ERROR
  tags: [filesystem]
```

The thing `unlinkat` syscall is not documented with Falco, only `unlink`, but even that doesn't work with `rm` operatings.

So this remains open until I or someone else can figure out why.

**Comment by mstemm** [comment]
Can you also include the definition of your wp_dir macro? I'd like to see that as well.

**Comment by finid** [comment]
`wp_dir` simply points to a directory.

By the way, I have a rule that works when a file is copied or created using the same macro. It's just with a `rm` operating that it does not trigger. If I can get some free time this week I'll troubleshoot it further.

**Comment by mstemm** [comment]
Ok, remember that`fd.directory` only handles the immediate directory for a given file, and not all child directories. For example, if your web root were `/var/www`, and had files `/var/www/a` and `/var/www/subdir/b`, only a would have `fd.directory=/var/www`.

If you have a trace file I'd be happy to take a stab at the macro also. It's probably a useful one to include in the base rules file.

**Comment by finid** [comment]
Yes, I'll take a stab at this again, and make the trace file available. What I'm actually trying to do is implement a rule that gives me some of what OSSEC does, which would be nice to have in Falco's base rule.

And thanks for the pointer about `fd.directory`.
