### ISSUE TITLE
Adding the opportunity to select Falco webserver port in configuration file

### ISSUE THREAD

**Issue by art-mis** [falcosecurity/falco#2774]
**Motivation**

When I deploy Falco on our Linux infrastructure, I see that it starts listening on port: 8765/TCP on all host IPs (it also includes the external IP if there is one).
And we can get the Falco web server port available on the entire Internet on our servers if we do not prepare firewall rules. Perhaps now there are only two available endpoints, access to which will not give a potential attacker the opportunity to hack us, but we at least reveal to the world security tools we use, which is not very good.
I think I found responsible [line](https://github.com/falcosecurity/falco/blob/f7c628f6237d5a6f7a33e2ed053ced70386193e3/userspace/falco/webserver.cpp#L83) of code.

**Feature**

To add an option in **falco.yaml** configuration file to select IP address for Falco web server between 0.0.0.0 and 127.0.0.1 (with default 0.0.0.0)

**Alternative**

Give a user an opportunity to select an arbitrary IP address for the Falco web server and validate it through regular expression or compare with available network interfaces on host.

**Comment by sgaist** [comment]
@Andreagit97 Hi,

In the context of the hacktoberfest, I would like to tackle this feature. Can you assign it to me ?

**Comment by Andreagit97** [comment]
> @Andreagit97 Hi,
> 
> In the context of the hacktoberfest, I would like to tackle this feature. Can you assign it to me ?

Sure, thank you for this!
