### ISSUE TITLE
Can't open scap file from within a container (due to `HOST_ROOT=/host`)

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco#2784]
**Describe the bug**

Falco can read scap file with `-e` flag. It normally works, but not when it runs from its default container image `falcosecurity/falco`

**How to reproduce it**

Run `docker run --rm -i -t falcosecurity/falco:master sh`

Then, from inside the container, copy a file `.scap` and run:
`falco -e /path/to/your/file.scap`

You will get an error like this:

```
Could not open trace filename /path/to/your/file.scap for reading: 
```

**Expected behaviour**

Just work.

**Environment**

- Falco version: `Falco version: 0.36.0-169+513f122 (x86_64)`

**Additional context**

The root cause is due to the `HOST_ROOT` variable. By using `strace` I noticed:
```
openat(AT_FDCWD, "/host/proc/stat", O_RDONLY) = -1 ENOENT (No such file or directory)
```

The problem does not occur when `HOST_ROOT=""`

/milestone 0.36

**Comment by FedeDP** [comment]
I agree, makes sense!

**Comment by leogr** [comment]
> I agree, makes sense!

Before moving it, do we know if this problem is still present? 
cc @falcosecurity/core-maintainers @falcosecurity/libs-maintainers

**Comment by Andreagit97** [comment]
need to check but yes the problem should persist in Falco 0.37.0

**Comment by leogr** [comment]
> need to check but yes the problem should persist in Falco 0.37.0

I've tried and it seems to be fixed now :thinking: 

```sh
❯ docker run --rm -i -t falcosecurity/falco-no-driver:0.37.0 sh
# env
HOSTNAME=b9b7f64117a0
HOME=/root
HOST_ROOT=/host
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
# curl -O https://download.falco.org/fixtures/libs/scap_files/kexec_x86.scap
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30.4M  100 30.4M    0     0  64.8M      0 --:--:-- --:--:-- --:--:-- 65.0M
# falco -e kexec_x86.scap
2024-01-31T17:19:28+0000: Falco version: 0.37.0 (x86_64)
2024-01-31T17:19:28+0000: Falco initialized with configuration file: /etc/falco/falco.yaml
2024-01-31T17:19:28+0000: DEPRECATION NOTICE: the '-e' command line option is deprecated and will be removed in Falco 0.38! Set 'engine.kind: replay' and use 'engine.replay' config instead in falco.yaml
2024-01-31T17:19:28+0000: Loading rules from file /etc/falco/falco_rules.yaml
2024-01-31T17:19:28+0000: Loading rules from file /etc/falco/falco_rules.local.yaml
2024-01-31T17:19:28+0000: Replaying events from the capture file: kexec_x86.scap
Syscall event drop monitoring:
   - event drop detected: 0 occurrences
   - num times actions taken: 0
Events detected: 0
Rule counts by severity:
Triggered rules by rule name:
# 
```

I've also tried with `falcosecurity/falco` image and it works too.

So, I close this for now, but it would be nice to find out how this was fixed.
/close

**Comment by Andreagit97** [comment]
instead of `-e` you should use `falco -o engine.kind=replay -o engine.replay.capture_file=<path_to_the_scap_file>`. See the [`engine` key in `falco.yaml`](https://github.com/falcosecurity/falco/blob/19ce244b8a87e6476b4b74ab51b3c066be78c45a/falco.yaml#L344) config for more details
