### ISSUE TITLE
Falco Webhook getting an error - "http: request body too large"

### ISSUE THREAD

**Issue by antikilahdjs** [falcosecurity/falco#2808]
**Describe the bug**

**How to reproduce it**

- Install using the normal way to use k8s-audit. I used the official helm charts
- 

**Expected behaviour**

In my lab everything works perfecly because I dont have a large environment but in my production I am facing the error  about the body is too large then I had increased the 2 parameters to works correctly 

    maxEventSize: 134217728
    webhookMaxBatchSize: 268435456

Then the POD memory increased to 38gb or more and the cores either, so I would like to know it is a bug or not.

My environment is too large but is so weird because I tested other applications and works around 12gb.

I would like to fix the error or if I did something wrong please help me on it.

**Screenshots**

![image](https://github.com/falcosecurity/falco/assets/33559260/7a977462-6c06-4607-93aa-8bf953eca90c)

![image](https://github.com/falcosecurity/falco/assets/33559260/999fd1d1-b26f-4080-9c0d-f4b11f1c55da)

**Environment**

- Falco version:

  Thu Sep 14 15:17:25 2023: Falco version: 0.35.1 (x86_64)
  Thu Sep 14 15:17:25 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
  {"default_driver_version":"5.0.1+driver","driver_api_version":"4.0.0","driver_schema_version":"2.0.0","engine_version":"17","falco_version":"0.35.1","libs_version":"0.11.3","plugin_api_version":"3.0.0"}
- System info:

{
  "machine": "x86_64",
  "nodename": "falco-auditing-56bdb4c9b6-5wbjr",
  "release": "4.18.0-348.el8.0.2.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP Sun Nov 14 00:51:12 UTC 2021"
}

- Cloud provider or hardware configuration:
- OS: Redhat 8.5

- Kernel:

4.18.0-348.el8.0.2.x86_64 
- Installation method:

Officinal Helm Charts on https://github.com/falcosecurity/charts

**Additional context**

      2023/09/14 15:10:45 [k8saudit] bad request: http: request body too large

     2023/09/14 15:10:57 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:10:59 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:11:00 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:11:04 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:11:05 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:11:14 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:11:16 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:11:21 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:11:23 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:11:26 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:11:35 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:11:35 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:11:40 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:11:43 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:11:44 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:11:51 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:11:56 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:12:00 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:12:01 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:12:03 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:12:12 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:12:14 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:12:16 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:12:17 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:12:22 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:12:31 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:12:32 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:12:36 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:12:39 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:12:43 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:12:49 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:12:54 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:12:55 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:12:58 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:13:07 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:13:12 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:13:14 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:13:14 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:13:17 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:13:29 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:13:34 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:13:35 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:13:38 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:13:40 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:13:51 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:13:52 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:13:58 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:14:01 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:14:04 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:14:13 [k8saudit] bad request: http: request body too large
    
     2023/09/14 15:14:14 [k8saudit] bad request: http: request body too large

**Comment by Andreagit97** [comment]
ei thank you for reporting! 

> Then the POD memory increased to 38gb or more and the cores either, so I would like to know it is a bug or not.

Uhm it seems like a bug, we need to investigate more on this!

**Comment by antikilahdjs** [comment]
Thank you so much @Andreagit97. I will send below a screenshoot from real query in Prometheus. I included a resources limits 42gb but if remove the Falco reach more than 120gb

![image](https://github.com/falcosecurity/falco/assets/33559260/63d6eb31-9584-4cff-8510-7dbacadeba74)

**Comment by Andreagit97** [comment]
Thank you for the additional data, right now we are a little bit busy but we will come to it after the falco release!

**Comment by antikilahdjs** [comment]
Not fixed

**Comment by sboschman** [comment]
You increased max eventsize to 134Gb and max webhook batch size to 268Gb? In which case the memory usage is sort of expected I guess, as up to 268GB of json has to be processed at once...

A few things you might experiment with:
- limit the number of events in a single batch by setting the `--audit-webhook-batch-max-size` flag on your api server, you might need multiple falco instances to keep up with your audit event stream, as you mention having a large cluster
- use the falco tailored `audit-policy.yaml` ([docs](https://falco.org/docs/install-operate/third-party/learning/#falco-with-multiple-sources)) in case you are not already doing so, as the api server can generate massive amounts of audit events which are not all relevant to falco
- as some events include the `requestObject` (e.g. a ConfigMap), you might be able to find the event which includes some massive k8s object and consider dropping it using the `audit-policy.yaml`
