### ISSUE TITLE
falco exception not working

### ISSUE THREAD

**Issue by Jeph10** [falcosecurity/falco#2827]
customRules:
    default_custom_rules.yaml: |-

      - rule: Read environment variable from /proc files
        desc: An attempt to read process environment variables from /proc files
        condition: >
          open_read and container and (fd.name glob /proc/*/environ)
          and not proc.name in (known_binaries_to_read_environment_variables_from_proc_files)
        output: >
          Environment variables were retrieved from /proc files (user=%user.name user_loginuid=%user.loginuid program=%proc.name
          command=%proc.cmdline pid=%proc.pid file=%fd.name parent=%proc.pname gparent=%proc.aname[2] ggparent=%proc.aname[3] gggparent=%proc.aname[4] container_id=%container.id image=%container.image.repository)
        priority: WARNING
        tags: [container, filesystem, process, mitre_credential_access, mitre_discovery, T1083]
        exceptions:
        - name: proc_file_retrival_runner
          fields: [k8s.ns.name]
          comps: [=]
          values:
          - [jenkins]
      

result
```
---------
{"falco_load_results":[{"errors":[{"code":"LOAD_ERR_VALIDATE","codedesc":"Error validating rule/macro/list/exception objects","context":{"locations":[{"item_name":"","item_type":"rules content","position":{"column":0,"line":0,"name":"default_custom_rules.yaml","offset":0}},{"item_name":"Read environment variable from /proc files","item_type":"rule","position":{"column":2,"line":1,"name":"default_custom_rules.yaml","offset":3}},{"item_name":"","item_type":"condition expression","position":{"column":3,"line":2,"name":"\"open_read and con...\"","offset":3}}],"snippet":"open_read and container and (fd.name glob /proc/*/environ) and not proc.name in (...\n   ^\n"},"message":"Undefined macro 'open_read' used in filter."}],"name":"default_custom_rules.yaml","successful":false,"warnings":[]}]}
Error: default_custom_rules.yaml: Invalid
1 Errors:
In rules content: (default_custom_rules.yaml:0:0)
    rule 'Read environment variable from /proc files': (default_custom_rules.yaml:1:2)
    condition expression: ("open_read and con...":2:3)
------
open_read and container and (fd.name glob /proc/*/environ) and not proc.name in (...
   ^
------
LOAD_ERR_VALIDATE (Error validating rule/macro/list/exception objects): Undefined macro 'open_read' used in filter.
```

**Comment by Jeph10** [comment]
maybe I not writing added the default rule correctly to the exception

**Comment by Andreagit97** [comment]
ei @Jeph10 It seems like the `open_read` macro is not defined in your file, you need to add it somewhere if you want to redefine the whole rule in a new file

```yaml
- macro: open_read
  condition: (evt.type in (open,openat,openat2) and evt.is_open_read=true and fd.typechar='f' and fd.num>=0)
```

**Comment by Andreagit97** [comment]
i will close this, feel free to reopen if this is still an issue!
