### ISSUE TITLE
S3 packages/deb-dev and rpm-dev has surpassed 20GB, the GHA worker will not download it

### ISSUE THREAD

**Issue by LucaGuerra** [falcosecurity/falco#2862]
**Describe the bug**

![image](https://github.com/falcosecurity/falco/assets/35580196/b7ad1750-810b-434c-8aed-769ed1bde4e5)

Note that when the script `publish-deb` runs it will run out of space since the max disk space for the github worker is 20GB.

A potential fix would be to prune the list of packages to a max total size (something like 15GB maybe?)

**How to reproduce it**

Any package master/nightly package build or RC build will trigger this error.

**Expected behaviour**

The build succeeds

**Screenshots**

**Environment**

**Comment by leogr** [comment]
I'd propose putting a cap limit of 10GB (or even less) for dev builds. On the other hand, stable ones must be preserved.
