### ISSUE TITLE
[Legacy eBPF] Falco doesn't work on GKE cluster(v1.24) 

### ISSUE THREAD

**Issue by Andreagit97** [falcosecurity/falco#2874]
@EdikAndriasyan reposting your initial question https://github.com/falcosecurity/falco/issues/2869#issuecomment-1764119299

> Hey, I am deploying Falco in GKE cluster(v1.24) with helm chart(3.7.1). Using ebpf module and deploying Falco as DaemonSet. I am getting this error in Falco logs.
> 
> `-- BEGIN PROG LOAD LOG --
> processed 43798 insns (limit 1000000) max_states_per_insn 1 total_states 4061 peak_states 4061 mark_read 1921
> 
> -- END PROG LOAD LOG --
> Mon Oct 16 09:06:37 2023: An error occurred in an event source, forcing termination...
> Mon Oct 16 09:06:37 2023: Closing event source 'syscall'
> Events detected: 0
> Rule counts by severity:
> Triggered rules by rule name:
> Error: libscap: bpf_load_program() event=raw_tracepoint/filler/sys_procexit_e: Operation not permitted`

**Comment by EdikAndriasyan** [comment]
I guess the gke version is not the reason because I have tried to deploy it in anther cluster with GKE version v1.27.5-gke.200 and kernel version 5.15.120 and the same issue. But I have successfully deployed in third cluster with GKE version v1.25.5-gke.1500 and kernel version 5.15.65. Let me test with modern-bpf.

**Comment by Andreagit97** [comment]
> I guess the gke version is not the reason because I have tried to deploy it in anther cluster with GKE version v1.27.5-gke.200 and kernel version 5.15.120 and the same issue. But I have successfully deployed in third cluster with GKE version v1.25.5-gke.1500 and kernel version 5.15.65. Let me test with modern-bpf.

Uhm that's interesting yesterday I tried `1.27.3-gke.100` and it worked, so it seems only some versions are affected...Let us know if the modern probe works for you

**Comment by EdikAndriasyan** [comment]
I have tried moder-bpf in v1.27.5-gke.200 GKE cluster with Kernel version5.15.120+ and got **libpman: ring buffer map type is not supported (errno: 1 | message: Operation not permitted)** error . I have used this options in helm chart values.

`containerSecurityContext:
  capabilities:
    add:
    - CAP_SYS_RESOURCE
    - CAP_BPF
    - CAP_PERFMON
    - CAP_SYS_PTRACE

driver:
  enabled: true
  kind: modern-bpf`
