### ISSUE TITLE
Support a falco.local.yaml configuration file with local changes to support unattended upgrades

### ISSUE THREAD

**Issue by derSascha** [falcosecurity/falco#2880]
**Motivation**

I'm using the debian/ubuntu repository to install falco and upgrading falco on my servers. My `falco.yaml` contains local changes like the log level / priority and other things. Upgrading falco via apt always result in configuration file conflicts, as it contains local changes, and requires a manual merge.

**Feature**

There is already a `falco_rules.local.yaml`, what about having a `falco.local.yaml` that contains local configuration changes? This way, the upgrade of falco can be automated using unattended-upgrades without solving any configuration file conflicts.

**Alternatives**

Configuration options can also be provided using command-line arguments, but this means right now an additional systemd configuration or overwrite on systems using systemd. Not sure if there is a way to add custom command-line arguments to this.

**Additional context**

Not sure if this is already everything required to do automated upgrades, but it should at least support something like this, without any manual fixes:
`FALCO_FRONTEND=noninteractive apt-get install -y falco`

**Comment by FedeDP** [comment]
Hi!
> Not sure if this is already everything required to do automated upgrades, but it should at least support something like this, without any manual fixes:

We already support that: https://github.com/falcosecurity/falco/blob/master/scripts/debian/postinst.in#L39

> what about having a falco.local.yaml that contains local configuration changes? 

I quite like the idea indeed.
cc @falcosecurity/falco-maintainers , wdyt?

**Comment by incertum** [comment]
Supportive!

> There is already a falco_rules.local.yaml, what about having a falco.local.yaml that contains local configuration changes?

I like this callout.
