### ISSUE TITLE
Falco is not generating events for custom_rules

### ISSUE THREAD

**Issue by sureshbanyal** [falcosecurity/falco#2891]
**I have installed Falco on Eks cluster by using helm charts to use custom rules i have created custom_rules.yaml file in falco helm directory also included in values.yaml file like this
 461   rules_file:
 462     - /etc/falco/falco_rules.yaml
 463     - /etc/falco/falco_rules.local.yaml
 464     - /etc/falco/rules.d/custom_rules.yaml
 465   customRules:
 466   custom-rules.yaml: |-
 467     - rule: shell_in_container
 468       desc: Notice shell activity within a container
 469       condition: evt.type = execve and evt.dir = < and container.id != host and (proc.name in (bash, csh, ksh, sh, tcsh, zsh, dash))
 470       output: shell in a container (user=%user.name container_id=%container.id container_name=%container.name shell=%proc.name parent=%proc.pname cmdline     =%proc.cmdline)
 471       priority: WARNING
 472
 473     - rule: Monitor only a process named malicious
 474       desc: Another example of an overly broad rule
 475       condition: proc.name = malicious
 476       output: The process %proc.name has used the syscall %evt.type
 477       priority: CRITICAL
 
 Than i run helm command to install
 ``helm upgrade --install falco -f values.yaml --namespace falco --set falcosidekick.enabled=true --set auditLog.enabled=true --set falcosidekick.webui.enabled=true --set falco.jsonOutput=true falcosecurity/falco``
 
 Falco is up and running when i test it does this will work or not i have logged in to pod by using this command 
 kubectl exec -it nginx-deployment-7f456874f4-2bmsg -n autoscaler -- /bin/sh
 
 After i tested using this comand Falco is able to send alerts to Falco Web-Ui but for malicious rule its not detecting and few other k8s unexpected connections its generating alerts   **

**Falco is only detecting unexpected k8s connections and its only noticing shell in containers**

**For custom rules it should generate alerts to Falco web-Ui my requirement is lets say inside Eks Kubernetes cluster in any of the pod and namespaces any malicious code or malware code got uploaded any scripts got uploaded like inside pod any suspicious activity is running Falco should generate alerts to Web-Ui Please help me on this requirement as much as Falco can achive thank you so much.  **

**Same way as in screen shot should get alerts for my requirements:

![image](https://github.com/falcosecurity/falco/assets/109554129/bf556a0f-0b79-42a5-99bd-9ebcf65dc453)

**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration: AWS EKS
- OS: lINUX

- Kernel:

- Installation method:

**kubernetes
helm**

**Comment by Andreagit97** [comment]
ei @sureshbanyal if I understood well you want to add some custom rules to Falco and for some reason, they are not triggered when you deploy Falco, is this your issue?

**Comment by alacuku** [comment]
Hi @sureshbanyal, the following resources show you how to handle rules artifacts with the helm chart:
* https://falco.org/docs/rules/default-custom/
* https://falco.org/blog/gitops-your-falco-rules/
* https://falco.org/blog/falcoctl-install-manage-rules-plugins/
* https://github.com/falcosecurity/charts/tree/master/charts/falco#loading-custom-rules

Let us know if you are having troubles to load custom rule in falco using the helm chart.

**Comment by ariary** [comment]
Try to add `rule_matching: all` in your falco configuration, because by default one event can only match one rule. It is possible that the event you want to catch with custom rules is already catched by default rules.

cf [falco docs](https://falco.org/blog/falco-0-36-0/#multiple-rules-can-be-matched-on-each-event)

_(you can also try to disable default rules)_
