### ISSUE TITLE
Accessing Sensitives Files Under /etc/pam.d Via a Symlink Evades Detection With Default YAML Rules

### ISSUE THREAD

**Issue by agadient** [falcosecurity/falco#2916]
**Describe the bug**

Accessing a file under the /etc/pam.d directory via a symlink that doesn't include /etc/pam.d allows an attacker to evade detection by the standard ruleset.

**How to reproduce it**

Run the commands listed here: https://github.com/Vali-Cyber/ebpf-attacks/tree/main/symlink

**Expected behaviour**

The /etc/pam.d/cron file will be accessed without an alert being logged.

**Environment**

- Falco version: Falco version: 0.36.2 (x86_64)

- System info:

Linux hamden 5.15.0-87-generic #97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

- Cloud provider or hardware configuration: Local VMWare VM
- OS:

hamden@hamden:~$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"

- Kernel: Linux hamden 5.15.0-87-generic #97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

- Installation method:

The container run command provided here: https://github.com/Vali-Cyber/ebpf-attacks/tree/main/agents

**Additional context**

**Comment by Andreagit97** [comment]
Thank you for reporting, unfortunately, this is a known issue! we will try to solve it in the next releases
