### ISSUE TITLE
falco 0.36  kernel :rhel, falco-driver-loader unable to download

### ISSUE THREAD

**Issue by YanjiangChen** [falcosecurity/falco#2921]
**Describe the bug**

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by Andreagit97** [comment]
ei @YanjiangChen can you provide the error message of the `falco-driver-loader`?

**Comment by YanjiangChen** [comment]
* Trying to download a prebuilt falco module from https://download.falco.org/driver/6.0.1%2Bdriver/x86_64/falco_rhel_3.10.0-1160.95.1.el7.x86_64_1.ko        
curl: (22) The requested URL returned error: 404 Not Found
Unable to find a prebuilt falco module

**Comment by YanjiangChen** [comment]
I found that there is no rhel-related ko module on the download page. After I forced the code to change rhel to centos, it can be downloaded and used normally.

**Comment by FedeDP** [comment]
Hi! We don't support prebuilt drivers for rhel; so you must let `falco-driver-loader` build the driver for you.

**Comment by FedeDP** [comment]
/close
Closing as compelted. Feel free to reopen!
