### ISSUE TITLE
 I would like to know about the necessity of updating the kernel module in high kernel. Is there any detailed documentation? 

### ISSUE THREAD

**Issue by YanjiangChen** [falcosecurity/falco#2923]
**What to document**

**Comment by incertum** [comment]
https://falco.org/docs/install-operate/ plus run `falco --version` to see the compatible driver version. 

In addition, if you upgrade the Falco userspace binary typically you also need to unload the old kernel module and reload a newer kernel module that is compatible. Similar procedure when upgrading your kernel as the kernel module has to be specifically compiled for your `uname -r` kernelrelease.

**Comment by YanjiangChen** [comment]
What I want to know may not be this. I want to know the necessity of kernel modules existing in higher versions.
