### ISSUE TITLE
Emit a warning when trying to set a non-existing config key

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco#2924]
**Motivation**

Silently ignoring a non-existing config key in `falco.yaml` can hide problems and mislead users. A simple typo can make Falco completely ignore the value, which may be hard to spot. 

For example:

```yaml
stdout_output:
  enabled: false
```
vs.
```yaml
stduot_output:
  enabled: true
```
(N.B. the typo in _std**uo**t_output_)

Currently, Falco silently ignores the latter case.

**Feature**

Falco should emit a warning when the user sets a non-existent config key.

**Alternatives**

An alternative can be to emit an error and stop the Falco execution. Would this alternative be better? :thinking: 
On the other hand, a simple warning could help spot misconfiguration when upgrading to a new version without blocking the deployment.

**Additional context**

This idea came up while reviewing this PR https://github.com/falcosecurity/falco/pull/2413

**Comment by leogr** [comment]
> hey @leogr , i want to contribute on this issue, can you guide me to what changes required and how can i proceed in this. Thanks

Hey @h4l0gen 
Great! :star_struck: 

I haven't looked into code details, but I guess that we should look for the existence of an option while parsing the YAML here :point_down: 
https://github.com/falcosecurity/falco/blob/master/userspace/falco/configuration.cpp#L186

An alternative approach would be to create a YAML schema and validate the file before loading it (I wonder if it is worth keeping this approach). 

@jasondellaluce any suggestion in this regard?

@h4l0gen let me know if this is ok for you. In case you plan to work on this, please `/assign` this issue to yourself, thank you!

**Comment by h4l0gen** [comment]
hey @leogr , 
it would be really great if you assign me this issue. am starting looking on code details and soon come up with required changes.

**Comment by leogr** [comment]
I'd like to prioritize this tentatively for 
/milestone 0.39.0
