### ISSUE TITLE
Cannot run falco built from source

### ISSUE THREAD

**Issue by baosama999** [falcosecurity/falco#2925]
**Falco build from source cannot open BPF probe**

I built falco with the following commands

```
git clone https://github.com/falcosecurity/falco/
cd falco
mkdir build
cd build
cmake -DMINIMAL_BUILD=ON -DUSE_BUNDLED_DEPS=ON ..
```

The build was successful, but when I ran falco with sudo:

```
FALCO_BPF_PROBE=/root/.falco/falco-bpf.o sudo -E ./falco -c /home/ubuntu/falco/edr/falco/embedded/bpf/config.yaml -r /home/ubuntu/falco/edr/falco/embedded/bpf/rules/
```

The output was:
```
Events detected: 0
Rule counts by severity:
Triggered rules by rule name:
Error: SCAP_FILLERS_TABLE bpf_map_update_elem : Operation not permitted
```

I tried using the falco executable from docker image, and it ran fine.

Where was I wrong?

**Comment by incertum** [comment]
Which Falco commit were you using for your build from source? Did you just pull from the latest Falco master or did you mix it up with custom libs and driver commits? Did you also build the bpf driver from source?

Falco master is not considered stable. We recently bumped libs reference but not yet the driver reference (there is another bump of libs and driver references slated to happen in the next 1-2 days).

What is your `uname -r`?

https://falco.org/docs/install-operate/

Lastly, we are still working on improving docs and guidance for adopters who wish to build everything themselves. right now, however a certain degree of domain knowledge is required and the docs are not yet self sufficient.

**Comment by Andreagit97** [comment]
Yeah it seems like Falco expects a driver version that is different from the one you are using. Could you try something like
```bash
make bpf
```

and then use

```
FALCO_BPF_PROBE=<path-to-the-bpf-probe-just-built(you can find it under /build-folder/driver/bpf/probe.o)> in your command
```

I have the suspect that the probe in `/root/.falco/falco-bpf.o` is a wrong driver version

**Comment by incertum** [comment]
Falco master now has updated libs and driver references. @baosama999 could you try again (including building the driver) with latest Falco master?

**Comment by baosama999** [comment]
@Andreagit97 I used BPF probe downloaded from falco repository.

```
root@ip-172-31-13-44:/home/ubuntu/falco/edr/falco/embedded# ll /root/.falco/
total 16
drwxr-x--- 3 root root 4096 Nov  8 03:25 ./
drwx------ 9 root root 4096 Nov 17 08:54 ../
drwxr-x--- 3 root root 4096 Nov  6 10:47 6.0.1+driver/
lrwxrwxrwx 1 root root   77 Nov  8 03:25 falco-bpf.o -> /root/.falco/6.0.1+driver/x86_64/falco_ubuntu-aws_6.2.0-1015-aws_15~22.04.1.o
root@ip-172-31-13-44:/home/ubuntu/falco/edr/falco/embedded# 
```

```
root@ip-172-31-13-44:/home/ubuntu/falco/edr/falco/embedded# uname -a
Linux ip-172-31-13-44 6.2.0-1015-aws #15~22.04.1-Ubuntu SMP Fri Oct  6 21:37:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

@incertum It seems to work fine when I tried with the latest commit: https://github.com/falcosecurity/falco/commit/c5364be191f580a7a1edce3314ea7ace0cff8a86

**Comment by incertum** [comment]
Great and thanks for reporting back. 

I believe Falco master was in an unlucky state for just about a week, it should not happen all the time. Sorry about that.

Closing.
