### ISSUE TITLE
[Documentation] DEPRECATION NOTICE for FALCO_BPF_PROBE for Falco 0.38 -> add info around what to do instead of using the env variable

### ISSUE THREAD

**Issue by incertum** [falcosecurity/falco#2931]
**What to document**

The new deprecation warnings are awesome!

```
Wed Nov 29 01:44:29 2023: DEPRECATION NOTICE: 'syscall_drop_failed_exit' config is deprecated and will be removed in Falco 0.38! Use `engine.<driver>.drop_failed_exit' config instead
Wed Nov 29 01:44:29 2023: DEPRECATION NOTICE: 'syscall_buf_size_preset' config is deprecated and will be removed in Falco 0.38! Use `engine.<driver>.buf_size_preset' config instead
Wed Nov 29 01:44:29 2023: DEPRECATION NOTICE: 'modern_bpf.cpus_for_each_syscall_buffer' config is deprecated and will be removed in Falco 0.38! Use `engine.modern_ebpf.cpus_for_each_buffer' config instead
Wed Nov 29 01:44:29 2023: DEPRECATION NOTICE: the 'FALCO_BPF_PROBE' environment variable is deprecated and will be removed in Falco 0.38
```

One small request: Could we also tell end users what to do instead of using the 'FALCO_BPF_PROBE' environment variable? Thanks!

**Comment by Andreagit97** [comment]
> One small request: Could we also tell end users what to do instead of using the 'FALCO_BPF_PROBE' environment variable? 

Good point

if we all agree we can keep track of all the deprecation here https://github.com/falcosecurity/falco/issues/2840, i've update it :) 
Note that breaking change in Falco 0.38.0 means deprecation in `0.37.0`, this is done to avoid 2 issues with the same point

**Comment by Andreagit97** [comment]
can we close this in favor of https://github.com/falcosecurity/falco/issues/2840?
