### ISSUE TITLE
add file attributes to fields for conditions and outputs

### ISSUE THREAD

**Issue by artemNN** [falcosecurity/falco#2941]
Add file attributes to fields for conditions and outputs from file system: file owner, file permissions.
This can help track programs with the suid bit or animaly permissions and could be useful when tracing to execve/open/create/chmod syscalls (all syscalls with FD or FilePath as args).

auditd example:
"OGID": "root"
"OUID": "root"
"ogid": "0"
"ouid": "0"
"mode": "0104777"
"name": "/www/xbash"

**Comment by Andreagit97** [comment]
thank you for reporting, the request makes sense, I will add it to the backlog!
