### ISSUE TITLE
 mv file /etc/falco/rule.d/ will not cause falco to restart, but cp -r file /etc/falco/rule.d/file can

### ISSUE THREAD

**Issue by YanjiangChen** [falcosecurity/falco#2943]
**Describe the bug**

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by NitroCao** [comment]
Because Falco currently only monitors events with `IN_CREATE` and `IN_DELETE` type for rule directories, but `mv` command generates events with `IN_MOVE` type. I'll add a PR to fix it.
