### ISSUE TITLE
Publish checksums for .tar.gz archives

### ISSUE THREAD

**Issue by johananl** [falcosecurity/falco#2950]
**Motivation**

I couldn't find any checksums along with the archives published at https://download.falco.org/?prefix=packages/bin/x86_64/. I think it's important to let users verify the integrity of the binaries they download.

**Feature**

I suggest to update the Falco release process to compute and publish checkums for all .tar.gz archives (as far as I can tell, the DEB and RPM binaries already have `.asc` files which are cryptographic signatures).

**Alternatives**

None

**Additional context**

None

**Comment by Andreagit97** [comment]
thank you for reporting this, it makes a lot of sense!

**Comment by johananl** [comment]
Thanks for handling this!
