### ISSUE TITLE
Process to improve creating / updating Falco docs

### ISSUE THREAD

**Issue by mikegcoleman** [falcosecurity/falco#2951]
# Improving Falco’s Documentation Process

## Purpose:

The purpose of this document is to outline a new process to ensure Falco’s documentation is complete and current. 

## Problem:

Currently, there is no formally defined process to ensure that features that are released or updated have their corresponding documentation either created or revised. This leads to incomplete or outdated documentation. 

Note: Looking at the structure of the docs is out of scope for this particular document, but there is work happening on that front as well. 

While this updated process will help with Falco’s documentation, hopefully, it can also help attract new non-code contributors to the project by making docs issues easy to find and providing a nice onramp for new people. 

## Proposal

**Summary**:

Any customer-facing feature, whether it is a new feature or an update, will have a corresponding issue raised in GitHub for the necessary docs work. Additionally, there will now be a “docs” approval flag on any PRs that must be removed before the feature PR can be merged.  DevRel will own the process of creating/updating the docs, working with Engineering to ensure their technical accuracy. 

**Details:**

Currently, there is a flag that gets set whenever a feature needs to be added to the release notes. It is believed that this flag serves as a good proxy for whether or not the feature should be in the docs. 

When a PR has that flag, a new issue should be raised in the Falco website repository, and a flag should be set on the feature PR indicating that it needs a docs update.

From there someone will work to either create or update the required documentation working alongside the engineer(s) responsible for  featurePR to ensure the technical accuracy of the change. 

When the documentation PR is reviewed and approved, the corresponding GH issue can be closed. Closing the docs issue will be the action that clears the “docs update required” flag on the feature PR. 

All the documentation PRs will need to be held and merged whenever the feature PR is merged. 

**Challenges**

It’s not known how much of this process can be automated. The hope is we can do it all with GitHub actions. However, there is not enough time to do that before the next feature release, 

For the next release in early Q1 2024 Mike Coleman will work to manually implement the process to see if the flow is feasible and correct. 

After  everhone agrees with the final process, we can begin work on trying to automate it. Ideally for 2024’s 2nd release.

**Comment by Andreagit97** [comment]
Thank you for leading this workflow! can't wait to see the amazing results!
