### ISSUE TITLE
add real user id field

### ISSUE THREAD

**Issue by artemNN** [falcosecurity/falco#2952]
I found only the fields user.uid(euid) and user.loginuid(auid). 
Is it possible to add a uid/ruid field to an event?
This can help detect privilege escalation. 

old fields:
> "user.loginname": "<NA>",
> "user.loginuid": -1,
> "user.name": "root",
> "user.uid": 0

new field to adds:
> **"user.**realname**": "www-data",
> "user.**realuid**": 33**

**Comment by incertum** [comment]
We will look into it 👀 nice observation!

CC @Andreagit97 @FedeDP @gnosek

**Comment by Andreagit97** [comment]
thank you for pointing this out! it seems a reasonable request we will try to schedule it

**Comment by aberezovski** [comment]
Hello guys,

I would like to share more evidences regarding the improper handling of user's information in falco containers' outputs, when falco is deployed as DaemonSet into k8s clusters.

# Environment
- Falco installation: [Helm chart](https://falco.org/docs/install-operate/third-party/install-tools/#helm)
- K8s cluster: GKE

# Use Cases

Both use cases below use a custom rule that check for EXECVE event types for processes other than bash and sh.

## SSH to k8s node as `user_account_one (1001)` and run a non privileged command (non root user and w/o sudo)

```json
{
    "hostname": "falco-6q77l",
    "priority": "Warning",
    "rule": "Uncommon Process Execution",
    "source": "syscall",
    "tags": [],
    "time": "2023-12-11T15:35:25.817724482Z",
    "output_fields": {
        "container.id": "host",
        "container.image.repository": null,
        "container.image.tag": null,
        "container.name": "host",
        "evt.arg.flags": "0",
        "evt.time": 1702308925817724482,
        "evt.type": "execve",
        "fd.name": null,
        "k8s.ns.name": null,
        "k8s.pod.name": null,
        "proc.aname[2]": "sshd",
        "proc.aname[3]": "sshd",
        "proc.aname[4]": "sshd",
        "proc.cmdline": "cat --coreutils-prog-shebang=cat /bin/cat /etc/shadow",
        "proc.cwd": "/home/user_account_one/",
        "proc.exepath": "/usr/bin/coreutils",
        "proc.name": "cat",
        "proc.pname": "bash",
        "proc.tty": 34816,
        "user.loginname": "<NA>",
        "user.loginuid": -1,
        "user.name": "<NA>",
        "user.uid": 1001
    }
}
```
>**Conclusion**: Neither audit user's name and id, nor real/effective user's name were properly detected. Only effective user's id is correct e.g. `1001`. Effective user should be same as audit user.

## SSH to k8s node as `user_account_one (1001)` and run a privileged command using `sudo` 

- Event 1 

```json
{
    "hostname": "falco-6q77l",
    "priority": "Warning",
    "rule": "Uncommon Process Execution",
    "source": "syscall",
    "tags": [],
    "time": "2023-12-11T15:49:40.987496401Z",
    "output_fields": {
        "container.id": "host",
        "container.image.repository": null,
        "container.image.tag": null,
        "container.name": "host",
        "evt.arg.flags": "0",
        "evt.time": 1702309780987496401,
        "evt.type": "execve",
        "fd.name": null,
        "k8s.ns.name": null,
        "k8s.pod.name": null,
        "proc.aname[2]": "sshd",
        "proc.aname[3]": "sshd",
        "proc.aname[4]": "sshd",
        "proc.cmdline": "sudo cat /etc/shadow",
        "proc.cwd": "/home/user_account_one/",
        "proc.exepath": "/usr/bin/sudo",
        "proc.name": "sudo",
        "proc.pname": "bash",
        "proc.tty": 34816,
        "user.loginname": "<NA>",
        "user.loginuid": -1,
        "user.name": "<NA>",
        "user.uid": 0
    }
}
```
>**Conclusion**: Neither audit user's name and id, nor real/effective user's name and id were properly detected. For the executed command `sudo cat /etc/shadow` the effective user's id is `1001` and user's name `user_account_one`. 

- Event 2

```json
{
    "hostname": "falco-6q77l",
    "priority": "Warning",
    "rule": "Uncommon Process Execution",
    "source": "syscall",
    "tags": [],
    "time": "2023-12-11T15:49:40.995683814Z",
    "output_fields": {
        "container.id": "host",
        "container.image.repository": null,
        "container.image.tag": null,
        "container.name": "host",
        "evt.arg.flags": "0",
        "evt.time": 1702309780995683814,
        "evt.type": "execve",
        "fd.name": null,
        "k8s.ns.name": null,
        "k8s.pod.name": null,
        "proc.aname[2]": "bash",
        "proc.aname[3]": "sshd",
        "proc.aname[4]": "sshd",
        "proc.cmdline": "cat --coreutils-prog-shebang=cat /bin/cat /etc/shadow",
        "proc.cwd": "/home/user_account_one/",
        "proc.exepath": "/usr/bin/coreutils",
        "proc.name": "cat",
        "proc.pname": "sudo",
        "proc.tty": 34816,
        "user.loginname": "<NA>",
        "user.loginuid": -1,
        "user.name": "root",
        "user.uid": 0
    }
}
```
>**Conclusion**: The real/effective user's name and id, for the executed command `cat --coreutils-prog-shebang=cat /bin/cat /etc/shadow` with parent command `sudo`, were properly detected. **But the audit user's name and id are still wrong and should be `user_account_one` and `1001`.**

>**Note**: A completely different behaviour is noticed for case when falco is installed directly on Linux machine. Please check the issue [Miscorrelation between real/efective user's name and id for executed privileged command](https://github.com/falcosecurity/falco/issues/2962).

**Comment by ycaoT** [comment]
Once these are added, I would assume we shall see them here https://falco.org/docs/reference/rules/supported-fields/#field-class-user?

**Comment by aberezovski** [comment]
more context regarding the [above comment](https://github.com/falcosecurity/falco/issues/2952#issuecomment-1850464920).

The issue is **ONLY** reproduced on GKE based on default Node Image **Container-Optimized OS with containerd (cos_containerd) (default)**.
In case of GKE based on Node Image **Ubuntu with containerd (ubuntu_containerd)**, Falco output entry reflects appropriate value for the field `user.loginuid`.

>Important!
>More than that, the Auditd logs enabled on GKE Node (Container-Optimized OS with containerd (cos_containerd) (default)) reflected the real/audit/login user's info as expected.
![image](https://github.com/falcosecurity/falco/assets/23057751/26d7cac5-9be5-433a-aa11-24a915c739ce)

**Conclusion**
It appears Falco was not able to read the real/audit UID from GKE Node Image **Container-Optimized OS with containerd (cos_containerd)** Linux kernel, even Linux Auditd was able to read real UID info from sale Linux kernel.

**Comment by aberezovski** [comment]
With new Falco Helm Chart 4.1.1 and Falco version 0.37.0 the users' details are properly reflected in the falco pod's logs (both effective and audit users' identifiers).

**Comment by FedeDP** [comment]
Great to hear that! We fixed a small bug in the Falco helm chart: we did forget to mount etc-fs volume (needed to read users and groups info from /etc/passwd and /etc/group) in the past versions.
/close
