### ISSUE TITLE
Non-ASCII file paths/names are displayed as dots in the output

### ISSUE THREAD

**Issue by adsick** [falcosecurity/falco#2958]
**Describe the bug**

When falco prints it's output non-ascii filenames are displayed as dot symbols (`.`).

**How to reproduce it**

Trigger a falco event* that outputs a filename with a file that has some non-ASCII text, e.g. cyrilic "touch файл_file.txt" , you can use emoji as well: 
```bash
touch 😉.txt
```

- I can't provide you with a specific falco rule right now, but I may do if needed. 

**Expected behaviour**

filenames are displayed as they are or as their unicode codes equivalent (`\uXXX`)

**Examples:**
(parsed Rust struct, printed out:)
```
{
timestamp: "16:54:58.649737474",
user: "adsick",
uid: 1000,
process: "touch",
pid: 590591,
parent: "bash",
ppid: 513071,
command: "touch файл_file.txt",
file: "/home/adsick/work/tmp/........_file.txt",
syscall: "openat",
container_id: "host",
container_name: "host",
hash: None,
size: None
}
```
<details>
<summary>raw falco output: </summary>
"{\"hostname\":\"legion\",\"output\":\"16:54:58.649737474: Warning user=adsick uid=1000 process=touch pid=590591 parent=bash ppid=513071 command=touch \\u0444\\u0430\\u0439\\u043b_file.txt file=/home/adsick/work/tmp/........_file.txt syscall=openat  container_id=host container_name=host\",\"priority\":\"Warning\",\"rule\":\"created_files\",\"source\":\"syscall\",\"tags\":[\"create\",\"file\",\"write\"],\"time\":\"2023-12-08T14:54:58.649737474Z\", \"output_fields\": {\"container.id\":\"host\",\"container.name\":\"host\",\"evt.arg.name\":\"/home/adsick/work/tmp/........_file.txt\",\"evt.time\":1702047298649737474,\"evt.type\":\"openat\",\"proc.cmdline\":\"touch \\u0444\\u0430\\u0439\\u043b_file.txt\",\"proc.name\":\"touch\",\"proc.pid\":590591,\"proc.pname\":\"bash\",\"proc.ppid\":513071,\"user.name\":\"adsick\",\"user.uid\":1000}}"
</details>

notably the `command` is displayed correctly.

**Environment**

- Falco version:
```
❯ /falco/usr/bin/falco --version
Fri Dec  8 17:00:12 2023: Falco version: 0.36.2 (x86_64)
Fri Dec  8 17:00:12 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
Falco version: 0.36.2
Libs version:  0.13.4
Plugin API:    3.1.0
Engine:        26
Driver:
  API version:    5.0.0
  Schema version: 2.0.0
  Default driver: 6.0.1+driver
```
- System info:
```
{
  "machine": "x86_64",
  "nodename": "legion",
  "release": "6.5.12-300.fc39.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP PREEMPT_DYNAMIC Mon Nov 20 22:44:24 UTC 2023"
}
```
- OS:
Fedora 39 Workstation Edition
- Kernel:
`Linux legion 6.5.12-300.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Nov 20 22:44:24 UTC 2023 x86_64 GNU/Linux`

**Comment by incertum** [comment]
Nice catch!

Proposing a patch in an already open PR https://github.com/falcosecurity/libs/pull/1533 where we address some memory safety issues in some older hand-rolled approaches as std::filesystem is only now an option as we are adopting the C++17 standard.

Current Falco -> use `fs.path.name` instead

```
{"evt.res":"SUCCESS","evt.type":"openat","fd.name":"/root/....falco.txt","fd.nameraw":"\ud83d\ude09falco.txt","fs.path.name":"/root/\ud83d\ude09falco.txt","fs.path.nameraw":"\ud83d\ude09falco.txt","proc.cwd":"/root/"}
```

With patch in referenced PR

```
{"evt.res":"SUCCESS","evt.type":"openat","fd.name":"/root/\ud83d\ude09falco.txt","fd.nameraw":"\ud83d\ude09falco.txt","fs.path.name":"/root/\ud83d\ude09falco.txt","fs.path.nameraw":"\ud83d\ude09falco.txt","proc.cwd":"/root/"}
```

**Comment by adsick** [comment]
@incertum thanks a bunch for you help!
