### ISSUE TITLE
I upgraded my AKS cluster to version 1.26.1 and Falco stopped working properly

### ISSUE THREAD

**Issue by hkinjo2** [falcosecurity/falco#2982]
AKSクラスターのバージョンを1.26.1に上げたところFalcoがCrashLoopBackOffとなり正常に稼働しなくなりました。
再起動・再デプロイ・新しいバージョンのFlacoのデプロイ・割り当てcpuの変更など行いましたが事象は解決されませんでした。
こちらの事象についてご教示いただけると幸いです。
※現在のFalcoのバージョンは1.29.1です。

![画像 (4)](https://github.com/falcosecurity/falco/assets/130440853/e1eeb454-4281-4070-8dce-7844940a7d27)

**Comment by incertum** [comment]
My best bet is that there are issues with downloading and/or loading the kernel driver.

Incidentally we just added more info to the following 2 repos, perhaps useful as well:
- https://github.com/falcosecurity/deploy-kubernetes/tree/main/kubernetes
- https://github.com/falcosecurity/cncf-green-review-testing

Could you overwrite your Falco container entrypoint to something like?

```
command: ["/bin/sh"]
args:
  - -c
  - >-
    sleep 10000000
```

and after execing into the pod, launch Falco manually and tell us the error message? 
What kernel driver are you using? If you can try `--modern-bpf`.

**Comment by Andreagit97** [comment]
thank you for reporting, could you provide the Falco logs of one of the pods? Could you rewrite the issue in English, please?

**Comment by hkinjo2** [comment]
English translation.

I upgraded my AKS cluster to version 1.26.1 and Falco stopped working properly with CrashLoopBackOff.
I have rebooted, redeployed, deployed a new version of Flaco, changed the assigned cpu, etc., but the problem has not been resolved. We would appreciate any information you can give us on this issue. 
The current version of Falco is 1.29.1.

Confirmation.
Connect with the following command.
>kubectl exec -it <falco start pod name> -n falco

>service falco start
or
>systemctl start falco
and run this command (journalctl -fu falco) or is the understanding to provide logs output to /var/messages?

**Comment by hkinjo2** [comment]
I tried to connect to Falco with the previous recognition, but could not confirm it due to the CrashLoopBackOff status as shown in the operation log.

Am I correct in my understanding that the repository should be added before logging?

If so, I apologize. I do not know how to add a repository due to my limited knowledge.
I would appreciate it if you could tell me how to do this as well.
[sankou.txt](https://github.com/falcosecurity/falco/files/13729462/sankou.txt)
![画像 (5)](https://github.com/falcosecurity/falco/assets/130440853/3b48c5e7-9aca-4c11-93a9-8f21d7ae2a42)

**Comment by hkinjo2** [comment]
https://github.com/falcosecurity/falco/issues/2982#issuecomment-1863860540

>My best guess is that there is a problem downloading and/or loading the kernel drivers.
>
>BTW, I have added more information to the following two repositories. Perhaps they will be equally helpful.
>
>・https://github.com/falcosecurity/deploy-kubernetes/tree/main/kubernetes
>・https://github.com/falcosecurity/cncf-green-review-testing
>Could you please overwrite the Falco container entry point with something like

I am sorry. Please let me know the procedure again about the above.

**Comment by hkinjo2** [comment]
@incertum 
@Andreagit97 

Hello.

I apologize for my lack of knowledge.
Please let me know whatever information you need to solve the problem.
We will try to get it.

However, there are many operations that I do not know how to acquire and that is my issue.

Please help me. Please let me know how to acquire it along with the necessary information.

**Comment by Andreagit97** [comment]
As a first attempt, I would try to install Falco with the modern-bpf probe, which is the easiest method we have https://github.com/falcosecurity/charts/tree/master/charts/falco#daemonset. So you have to type:

```bash
# to update the helm chart to the latest version
helm repo update falcosecurity --fail-on-repo-update-fail
# to run Falco with modern ebpf
helm install falco falcosecurity/falco \
    --set driver.kind=modern-bpf
```

**Comment by Andreagit97** [comment]
Looking at your logs:
```
2024-01-15T10:20:47.7261752Z REVISION	UPDATED                 	STATUS    	CHART       	APP VERSION	DESCRIPTION     
2024-01-15T10:20:47.7262638Z 13      	Fri Jul 22 14:35:26 2022	superseded	falco-1.15.2	0.29.0     	Upgrade complete
2024-01-15T10:20:47.7266217Z 14      	Thu Jul 27 13:26:31 2023	superseded	falco-1.15.2	0.29.0     	Upgrade complete
2024-01-15T10:20:47.7267097Z 15      	Fri Aug  4 15:50:11 2023	superseded	falco-1.15.2	0.29.0     	Upgrade complete
2024-01-15T10:20:47.7268266Z 16      	Fri Aug  4 15:57:54 2023	superseded	falco-1.15.2	0.29.0     	Upgrade complete
2024-01-15T10:20:47.7269001Z 17      	Fri Aug  4 17:46:56 2023	superseded	falco-3.4.1 	0.35.1     	Upgrade complete
2024-01-15T10:20:47.7270362Z 18      	Tue Dec 12 18:27:52 2023	superseded	falco-3.4.1 	0.35.1     	Upgrade complete
2024-01-15T10:20:47.7271007Z 19      	Tue Dec 12 18:42:48 2023	superseded	falco-3.4.1 	0.35.1     	Upgrade complete
2024-01-15T10:20:47.7271644Z 20      	Thu Dec 14 16:40:31 2023	superseded	falco-1.15.2	0.29.0     	Upgrade complete
2024-01-15T10:20:47.7272280Z 21      	Wed Dec 20 11:29:21 2023	superseded	falco-1.15.2	0.29.0     	Upgrade complete
2024-01-15T10:20:47.7272964Z 22      	Mon Jan 15 19:11:44 2024	deployed  	falco-1.15.2	0.29.0     	Upgrade complete
2024-01-15T10:20:51.7628288Z Release "falco" has been upgraded. Happy Helming!
2024-01-15T10:20:51.7629087Z NAME: falco
2024-01-15T10:20:51.7630661Z LAST DEPLOYED: Mon Jan 15 19:20:49 2024
2024-01-15T10:20:51.7631105Z NAMESPACE: falco
2024-01-15T10:20:51.7631467Z STATUS: deployed
2024-01-15T10:20:51.7631804Z REVISION: 23
2024-01-15T10:20:51.7632196Z TEST SUITE: None
2024-01-15T10:20:51.7632611Z NOTES:
2024-01-15T10:20:51.7633104Z Falco agents are spinning up on each node in your cluster. After a few
2024-01-15T10:20:51.7633820Z seconds, they are going to start monitoring your containers looking for
2024-01-15T10:20:51.7634370Z security issues.
2024-01-15T10:20:51.7634619Z 
2024-01-15T10:20:51.7634633Z 
2024-01-15T10:20:51.7634867Z No further action should be required.
2024-01-15T10:20:51.7635178Z 
2024-01-15T10:20:51.7635189Z 
2024-01-15T10:20:51.7635330Z Tip: 
2024-01-15T10:20:51.7636551Z You can easily forward Falco events to Slack, Kafka, AWS Lambda and more with falcosidekick. 
2024-01-15T10:20:51.7637337Z Full list of outputs: https://github.com/falcosecurity/charts/tree/master/falcosidekick.
2024-01-15T10:20:51.7638085Z You can enable its deployment with `--set falcosidekick.enabled=true` or in your values.yaml. 
2024-01-15T10:20:51.7638735Z See: https://github.com/falcosecurity/charts/blob/master/falcosidekick/values.yaml for configuration values.
```

It seems like you are using the wrong Falco version

```
2024-01-15T10:20:47.7272964Z 22      	Mon Jan 15 19:11:44 2024	deployed  	falco-1.15.2	0.29.0     	Upgrade complete
```

Maybe you could try to delete the actual helm deployment with

```bash
helm uninstall falco
```

and then try again

```bash
# to update the helm chart to the latest version
helm repo update falcosecurity --fail-on-repo-update-fail
# to run Falco with modern ebpf
helm install falco falcosecurity/falco \
    --set driver.kind=modern-bpf
```

**Comment by hkinjo2** [comment]
@Andreagit97 
Sorry for the delay in implementation.
I tried to remove Falco using the command you provided, but the output was as follows.

Is it safe to delete the daemon from the Azure portal, delete and reinsert the deployed pod?

![image](https://github.com/falcosecurity/falco/assets/130440853/b602c05c-f5cd-453b-bba9-094ca57dd64d)

**Comment by Andreagit97** [comment]
What is the output after these 2 commands?

```bash
# to update the helm chart to the latest version
helm repo update falcosecurity --fail-on-repo-update-fail
helm show chart falcosecurity/falco
```

**Comment by hkinjo2** [comment]
@Andreagit97 

The result is as below.
![image](https://github.com/falcosecurity/falco/assets/130440853/74f6d86b-c95d-4f56-a95b-edd5e95e3baa)

By the way, the way to delete the daemon set is to delete the Falco daemon set from the portal screen below.
![image](https://github.com/falcosecurity/falco/assets/130440853/1d66eada-6942-4c2d-9d73-1ba208434247)

**Comment by Andreagit97** [comment]
ok, I don't know why you have Falco deployed through Azure but I think you can remove it. At the end of the cleanup, you should check that there are no Falco instances in the cluster:
```bash
kubectl get pods -A | grep falco
```
This should return nothing...

If you are in this situation now you can simply deploy Falco with:

```bash
helm install falco falcosecurity/falco \
    --set driver.kind=modern-bpf
```

**Comment by hkinjo2** [comment]
@Andreagit97 
Thank you for teaching.
I immediately installed the latest version of Falco.
The results are as follows.
The problem persists despite the latest versi
[20240126_開発環境_Falco最新Vserデプロイ.txt](https://github.com/falcosecurity/falco/files/14061312/20240126_._Falco.Vser.txt)
on.

I will also send you the entire log, so please check it.
![image](https://github.com/falcosecurity/falco/assets/130440853/e161ddb1-2188-4ac7-878c-2783e5f864d3)
![image](https://github.com/falcosecurity/falco/assets/130440853/8c30a9f1-9e5f-49cf-a70d-16b91bd2c907)

**Comment by hkinjo2** [comment]
P.S.
The command you provided didn't work, so I used the upgrade command.

**Comment by hkinjo2** [comment]
@Andreagit97 
Don't you know the cause of this problem?
We've been investigating this for the past two weeks, but we can't find the cause.
Please let me know if you have any advice.

**Comment by Andreagit97** [comment]
ei @hkinjo2 to help you we need the Falco startup logs, otherwise we cannot understand what is going on... 
These are the startup Falco logs:

```
Sep 11 08:46:08 localhost.localdomain falco[789]: Falco version: 0.37.1 (x86_64)
Sep 11 08:46:08 localhost.localdomain falco[789]: Falco initialized with configuration file: /etc/falco/falco.yaml
Sep 11 08:46:08 localhost.localdomain falco[789]: Loading rules from file /etc/falco/falco_rules.yaml
Sep 11 08:46:08 localhost.localdomain falco[789]: Loading rules from file /etc/falco/falco_rules.local.yaml
Sep 11 08:46:08 localhost.localdomain falco[789]: The chosen syscall buffer dimension is: 8388608 bytes (8 MBs)
Sep 11 08:46:08 localhost.localdomain falco[789]: Starting health webserver with threadiness 4, listening on port 8765
Sep 11 08:46:08 localhost.localdomain falco[789]: Loaded event sources: syscall
Sep 11 08:46:08 localhost.localdomain falco[789]: Enabled event sources: syscall
Sep 11 08:46:08 localhost.localdomain falco[789]: Opening 'syscall' source with modern BPF probe.
Sep 11 08:46:08 localhost.localdomain falco[789]: One ring buffer every '2' CPUs.
...
```

You can obtain them by running `kubectl logs <falco_pod_name>`

**Comment by alacuku** [comment]
Hi @hkinjo2, it seems that one of the `initContainers` is failing. Please provide the logs for those containers. To get the logs of a previous run for a given container use the `--previous` flag:
```bash
kubectl logs --previous -n falco  falco-7f5qx name-of-init-container-here
```

**Comment by hkinjo2** [comment]
@alacuku 
We become indebted to.
Sorry for my late reply.
I tried using the command you provided, but it still didn't work.
Please see the image.
![image](https://github.com/falcosecurity/falco/assets/130440853/18fd35e5-0285-46f6-81be-9d128764a92f)
![image](https://github.com/falcosecurity/falco/assets/130440853/5c4ce092-b3a5-4466-a9a5-f1928984ce13)

**Comment by hkinjo2** [comment]
@alacuku 

Hello
Can I investigate using the information you previously provided?
Please tell us about your current situation.
It's a no-brainer at my place of work.
We apologize for any inconvenience.
Thank you very much.

**Comment by hkinjo2** [comment]
@Andreagit97 

We upgraded the AKS cluster to a supported version yesterday, April 4, including the possibility of isolating whether the problem was caused by AKS or by Falco. (1.27.9)
The upgrade was successfully completed, but Falco is still not resolved.
We checked the events of the pods and found the following message.
 Preemption: 0/4 nodes are available: 4 No preemption victims found for incoming pod..."
 Please see the attached file for the actual screen of the above message.
Therefore, we would appreciate it if you could provide us with Falco's perspective on possible causes and solutions.
Thank you in advance.

![image](https://github.com/falcosecurity/falco/assets/130440853/3429227e-2268-4acc-9e02-2c0853f883d7)

**Comment by akirtanabe** [comment]
@Andreagit97
We become indebted to.
What do you think about the status of the investigation?
 
Due to the version upgrade of AKS equipped with Falco,
There was a difference in the container used with other normally operating Falcos, so we will cooperate.
Compared to an environment that is running normally, "falcoctl-artifact-follow" is added extra.
Originally, it was assumed that only a container called "Falco" was attached.
 
＝＝＝抜粋＝＝＝＝＝＝＝＝
NameSpace           NAME                                                      CONTAINERS
falco               falco-4t57h                                               falco,falcoctl-artifact-follow
falco               falco-f4h4s                                               falco,falcoctl-artifact-follow
falco               falco-xd9cz                                               falco,falcoctl-artifact-follow
falco               falco-z2s8l                                               falco,falcoctl-artifact-follow

**Comment by Andreagit97** [comment]
hi folks as we told you we can help you if Falco is not working but we need logs. Please clean all your Falco instances and try this

```bash
helm repo update falcosecurity
```

Then 

```bash
helm show chart falcosecurity/falco
```

the output should be something like 

```
apiVersion: v2
appVersion: 0.37.1
dependencies:
...
```

Then install Falco

```bash
helm install falco \
  --set driver.kind=modern_ebpf \
  --set falcoctl.artifact.install.enabled=false \
  --set falcoctl.artifact.follow.enabled=false \
  falcosecurity/falco
```

if Falco doesn't work and is in `CrashLoopBackOff` you should provide us with the logs 

```bash
kubectl logs <your-falco-instance-name>
```

**Comment by akirtanabe** [comment]
@Andreagit97
hello
Thank you for teaching me.
However, the result was not what I expected.
I will send it along with the execution log, so please check it.
 
Thank you for continuing to be with me.
thank you.
[falco.zip](https://github.com/falcosecurity/falco/files/15102121/falco.zip)

**Comment by Andreagit97** [comment]
Uhm it seems you have an already running Falco instance, you can try to delete it with 

```bash
helm uninstall falco  -n falco
```

and then retry

```bash
helm install falco \
  --set driver.kind=modern_ebpf \
  --set falcoctl.artifact.install.enabled=false \
  --set falcoctl.artifact.follow.enabled=false \
  falcosecurity/falco
```

**Comment by akirtanabe** [comment]
@Andreagit97
Hello,
 
Thank you for your guidance.
We recently conducted a reinstall of Falco.
Out of the four redeployed pods, three have successfully started up.
However, one remains in a pending state without starting up.
Attached is the event log for your review to assess if there are any functional implications.
Additionally, if there are any impacts, could you please advise on the appropriate course of action?
Thank you.
[falco-rg6n9.17d171d27601c9ec_Event.yaml.zip](https://github.com/falcosecurity/falco/files/15410104/falco-rg6n9.17d171d27601c9ec_Event.yaml.zip)

**Comment by akirtanabe** [comment]
@Andreagit97
Thank you for your help.
 
I understand that this may have impacted the AKS environment.
The pending pods recovered over time.
 
So I think reinstalling Falco resolved the issue.
 
Thank you for your support so far.
I'm going to close this issue now.
 
Thank you.

**Comment by Andreagit97** [comment]
great, I'm happy to hear that! I will close the issue

**Comment by akirtanabe** [comment]
@Andreagit97
Hello.
 
The event you requested also occurred in a different environment.
I reinstalled Falco but this also failed.
 
Could you please take a look at the log for details?
I want to solve it in a hurry.

[20240612_falco.txt](https://github.com/user-attachments/files/15814802/20240612_falco.txt)
[20240613_falco.txt](https://github.com/user-attachments/files/15814807/20240613_falco.txt)
