### ISSUE TITLE
Kmod compilation is failing on Debian

### ISSUE THREAD

**Issue by ShiroDN** [falcosecurity/falco#3001]
**Describe the bug**

I have attempted to install Falco on Debian 12, and it appears that the kmod compilation is failing.

```
[POST-INSTALL] Call 'falco-driver-loader --compile module':
* Running falco-driver-loader for: falco version=0.36.2, driver version=6.0.1+driver, arch=x86_64, kernel release=6.1.69-1-amd64, kernel version=1
* Running falco-driver-loader with: driver=module, compile=yes, download=no

================ Cleaning phase ================

* 1. Check if kernel module 'falco' is still loaded:
- OK! There is no 'falco' module loaded.

* 2. Check all versions of kernel module 'falco' in dkms:
- OK! There are no 'falco' module versions in dkms.

[SUCCESS] Cleaning phase correctly terminated.

================ Cleaning phase ================

* Looking for a falco module locally (kernel 6.1.69-1-amd64)
* Filename 'falco_debian_6.1.69-1-amd64_1.ko' is composed of:
 - driver name: falco
 - target identifier: debian
 - kernel release: 6.1.69-1-amd64
 - kernel version: 1
install: /usr/lib/gcc/x86_64-linux-gnu/12/
* Trying to dkms install falco module with GCC /usr/bin/gcc
Sign command: /usr/lib/linux-kbuild-6.1/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
Creating symlink /var/lib/dkms/falco/6.0.1+driver/source -> /usr/src/falco-6.0.1+driver
* Running dkms build failed, couldn't find /var/lib/dkms/falco/6.0.1+driver/build/make.log (with GCC /usr/bin/gcc)
install: /usr/lib/gcc/x86_64-linux-gnu/12/
* Trying to dkms install falco module with GCC /usr/bin/gcc-12
Sign command: /usr/lib/linux-kbuild-6.1/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
* Running dkms build failed, couldn't find /var/lib/dkms/falco/6.0.1+driver/build/make.log (with GCC /usr/bin/gcc-12)
* Trying to load a system falco module, if present
Consider compiling your own falco driver and loading it or getting in touch with the Falco community
dpkg: error processing package falco (--configure):
 installed falco package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 falco
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

After some debugging, it seems that the problem is caused by incorrect kernel version detection in the falco-driver-loader -> get_target_id() -> Debian section on line 169:

```
if [[ ${DRIVER_KERNEL_VERSION} =~ ([0-9]+\.[0-9]+\.[0-9]+\-[0-9]+) ]];`
```
**DRIVER_KERNEL_VERSION** is getting the version from the command **uname -v,** which results in the following output on Debian 12:

```
#1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30)
```
However, the correct parameter for dkms is that from **uname -r**, which in this case is:

```
6.1.0-17-amd64
```
So, if I replace **DRIVER_KERNEL_VERSION** with **DRIVER_KERNEL_RELEASE** on line 169 in falco-driver-loader, it will compile without a problem.

Tested on Debian 11 and 12.

**How to reproduce it**

1. Install falco acording to offic docs https://falco.org/docs/install-operate/installation/ on Debian 12
2. Select kmod
3. DKMS compilation will fail with an error above

**Expected behaviour**

Seccessfull installation and kmod compilation.

**Environment**

- Falco version:
```
Tue Jan  9 10:54:24 2024: Falco version: 0.36.2 (x86_64)
Tue Jan  9 10:54:24 2024: Falco initialized with configuration file: /etc/falco/falco.yaml
Falco version: 0.36.2
Libs version:  0.13.4
Plugin API:    3.1.0
Engine:        26
Driver:
  API version:    5.0.0
  Schema version: 2.0.0
  Default driver: 6.0.1+driver
```

- System info:
```
  "machine": "x86_64",
  "nodename": "debian",
  "release": "6.1.0-17-amd64",
  "sysname": "Linux",
  "version": "#1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30)"
```
- OS:
```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
```

- Kernel:
```
Linux debian 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux
```

- Installation method:
```
DEB
```

**Comment by FedeDP** [comment]
Hi! Thanks for opening this issue! Can you try using latest packages from Falco master?
Falco now makes use of the new driver loader implementation within falcoctl that should fix your issue!

**Comment by Andreagit97** [comment]
or maybe if you don't care about the driver used you can try to use the `modern-bpf` driver, it should work out of the box, without downloading anything

**Comment by cccsss01** [comment]
I strongly encourage the modern-bpf.  I wrote the docs for rpm kmod in uefi mode, just use the modern-bpf, i think it's a stable choice now.

**Comment by ShiroDN** [comment]
Yes, modern-bpf works fine. We are using kmod on centos/rocky linux in production, so it was the first thing that we tried. I suppose now, there shouldn't be much of a difference between kmod and bpf in terms of performance. We will test it on debian-based machines and might even switch to the bpf driver on rocky-based machines later. Thanks.

**Comment by Andreagit97** [comment]
The Kmod should be a little bit more efficient because there is no overhead from the BPF virtual machine, but the modern-bpf should work fine in many cases, maybe just give it a try and see if it can work for your use-case :)

**Comment by Andreagit97** [comment]
I will close this! Feel free to reopen if this is still an issue
