### ISSUE TITLE
Overlap with mgmtconfig?

### ISSUE THREAD

**Issue by purpleidea** [falcosecurity/falco#302]
There seems to be some plausible overlap with the event system over at https://github.com/purpleidea/mgmt/

I just figured I'd give a shout out over here in case you'd be interested in collaborating on the project or discussing event sources which are missing in current operating systems which we could both work on getting added.

Feel free to find me in #mgmtconfig on Freenode IRC as purpleidea, or at this years http://cfgmgmtcamp.eu/

Thanks!

**Comment by mstemm** [comment]
I think it could be feasible to add an integration of falco that would push events to mgmt. We have other integrations with event systems in the integrations subdirectory. We can continue the discussion on our public slack, and of course PRs are always welcome!

**Comment by purpleidea** [comment]
> of course PRs are always welcome!

@mstemm I actually just took another look (it's been a year) and I can't really sign any CLA's, so at this time, I can help out with code, sorry. If you change your mind, or if you're interesting in helping with mgmt, please feel free to ping me! Thanks!
