### ISSUE TITLE
Detect the insertion of a USB

### ISSUE THREAD

**Issue by andrewhowdencom** [falcosecurity/falco#311]
Hola All,

Doing some playing with this tool, and I'm curious -- is it possible to detect hardware changes? Things such as "inserted a keyboard" or "USB mass storage device" or whatever.

In playing with `sysdig`, I can see a bunch of reads to `/sys`, however I can't see it being written -- rather it just "appears" and udev appears to trigger some userland responses. 

Cheers,

**Comment by andrewhowdencom** [comment]
More generally, I can't figure out how to write rules that catch funny behaviour that the kernel is expressing. `read` catches some stuff (from the kernel pushing to syslog), but I think that's switched off in falco (also is kind of nuts to read *every read call* lol)

**Comment by mstemm** [comment]
This does sound like a great use case. However, our tap is system calls, which doesn't exactly track these kinds of events.

I haven't tried, but I think looking specifically at udev's activity is the way to go. I haven't looked in detail so no specific suggestions, though.
