### ISSUE TITLE
[TRACKING] New `anomalydetection` Plugin - Targeting First Release for Falco 0.39.0

### ISSUE THREAD

**Issue by incertum** [falcosecurity/falco#3117]
**Motivation**

This issue is to track the development progress for a new `anomalydetection` plugin, as outlined in the [Proposal](https://github.com/falcosecurity/falco/blob/master/proposals/20230620-anomaly-detection-framework.md). 

The objective is to provide updates on the progress of the development, ensuring alignment with the proposed framework. Additionally, it aims to identify any potential blockers that may hinder progress.

The initial scope will focus exclusively on "CountMinSketch Powered Probabilistic Counting and Filtering" for a subset of syscalls and a selection of options to define behavior profiles. The primary objective of this new framework is to offer tangible advantages in real-world production environments and substantially improve the usability of standard Falco rules. Essentially, this framework eliminates the requirement for meticulous tuning of individual rules and facilitates the utilization of probabilistic count estimates to alleviate the impact of noisy rules. Additionally, it enables the creation of broader Falco rules.

Edit: v1 PR can be found here: https://github.com/falcosecurity/plugins/pull/419

**Comment by incertum** [comment]
/remove-lifecycle stale

On track.

**Comment by incertum** [comment]
CC @@an1245

**Comment by incertum** [comment]
Just moved the PR out of Draft mode. It is now feature-complete and ready for review. The README has also been updated with more info.

Starting the testing on some more beefy test servers as we speak ... plus will also attempt to provide some useful initial use case guidelines (something that is missing right now).

The plugin will work with Falco >= 0.38.2.

**Comment by incertum** [comment]
After initial review let's setup the CI to publish some test artifacts @jasondellaluce.

**Comment by FedeDP** [comment]
Hey Melissa, is the plugin ready?
Otherwise can we move to 0.40.0? :D Thanks!

**Comment by leogr** [comment]
I moved this to 0.40. However, this should not be tied to the Falco release.

Anyway, just talked with @jasondellaluce and I guess we can merge the plugin PR soon.
