### ISSUE TITLE
Suggestion: Detect kernel modules inserted

### ISSUE THREAD

**Issue by andrewhowdencom** [falcosecurity/falco#312]
be possible to assert this in a couple of ways:

- freak out of there's a kernel module loaded from non-standard dir, and 
- freak out if non-scheduled process writes to module dir. 

Use case is smth like http://books.gigatux.nl/mirror/networksecuritytools/0596007949/networkst-CHP-7-SECT-3.html

**Comment by mstemm** [comment]
Seems reasonable. To handle the first case, we'll have to add support in sysdig for the `init_module` syscall first.
