### ISSUE TITLE
falcoSchema.json should be generated by Falco itself

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco#3149]
**Motivation**

Falco should be responsible for defining its supported rule syntax schema. Other tools can consume the schema, then.

For projects like falco-project, consuming this schema in JSON format is very useful. The project is currently using a static version of it https://github.com/falcosecurity/falco-playground/blob/main/src/components/Editor/falcoSchema.json

**Feature**

Make Falco generate the rule syntax schema in JSON format.

**Alternatives**

**Additional context**

Initially, I've filled this issue under the `falco-playground` project since we have a live example of what we need. The end goal is to transfer this issue to the `falco` repository and implement the feature in Falco.

I'm assigning this issue to me, but I need volunteers to help. :pray: 
/assign
/help

cc @falcosecurity/core-maintainers @falcosecurity/falco-playground-maintainers

**Comment by leogr** [comment]
/kind feature

Proposing
/milestone 0.38.0
cc @falcosecurity/falco-maintainers 

If anyone is willing to help, please let me know. :pray:

**Comment by FedeDP** [comment]
Implemented in https://github.com/falcosecurity/falco/pull/3313.
