### ISSUE TITLE
Add a way to view the final in-memory configuration

### ISSUE THREAD

**Issue by johananl** [falcosecurity/falco#3183]
**Motivation**

Falco configuration can grow complex, especially when using multiple rule files with overrides. As a user, I can't know for sure what configuration the Falco process uses in practice after parsing the config files and applying any overrides.

Of course, I can test Falco's *behavior* and try to infer the configuration, but that's a suboptimal solution, especially when there are multiple things which can cause some event to not be logged.

**Feature**

It could be useful for the Falco binary to expose its in-memory config state to the user somehow. There are many ways this can be done and Falco's attack surface should of course be taken into account (we don't want an attacker to know specifically what types of behavior we're watching for).

Personally I think it should be enough to just add a CLI flag which would print the "final" config to stdout and exit. This would be arguably safer than e.g. exposing the config as an HTTP endpoing in a *running* Falco process, although that option also has merit as it allows better observability into Falco deployments.

Implementing such an option should also be relatively simple assuming Falco must already have an in-memory representation of this "final" config (otherwise it couldn't do its job), so it's likely a matter of unmarshalling some data structure into YAML.

**Alternatives**

An alternative would be to have the main Falco process expose an HTTP endpoint which shows the config. This approach is sometimes taken by server applications, however it comes with an increased attack surface.

**Additional context**

The existing `--validate` flag seems related, however it seems to operate on a per-rule-file basis so I'm not sure it's the right place to put the proposed logic.

**Comment by FedeDP** [comment]
Hi! There is already a flag that prints out the final config, ie "--support".
I agree we could add a new flag just for that (ie: "--show-config"?).
But, given that, starting from Falco master and next Falco release (0.38) you will be able toleverage "jq" to extract the configs field, I am not sure whether that is worth.
Eg:
falco --support | jq -r '.config' | jq 

See here for more info: https://github.com/falcosecurity/falco/pull/3024#issuecomment-2044515001

**Comment by johananl** [comment]
@FedeDP AFAICT the `--support` command doesn't actually print the final, in-memory config, but rather the contents of the various config **files**.

Note that the two are different. For example, the former would print `override` directives whereas the latter would print the *modified* entry after applying an override.

**Comment by johananl** [comment]
Ah, great! Yes, I was testing with v0.37.1, not master. OK, then I guess this can be closed.

**Comment by FedeDP** [comment]
Yep! Thanks for coming up with this feat request though :)
/close

**Comment by johananl** [comment]
Thanks for consistently demonstrating excellent maintainership :slightly_smiling_face:
