### ISSUE TITLE
Execve always returns exit_code=0

### ISSUE THREAD

**Issue by MprBol** [falcosecurity/falco#3242]
**Describe the bug**

Falco logs non-zero exitcodes as succesful 

**How to reproduce it**

I created a custom rule with the following:

```
- rule: Commands ended by user mprbol
  desc: Log the end of all commands executed by user mprbol with detailed information
  condition: (user.uid=1000 or user.loginuid=1000) and evt.type=execve and evt.dir=<
  output: >
    Command ended:
    exe=%proc.exepath,
    pid=%proc.pid,
    ppid=%proc.ppid,
    args=%proc.args,
    cwd=%proc.cwd,
    uid=%user.uid,
    loginuid=%user.loginuid,
    user.name=%user.name,
    loginname=%user.loginname,
    shell=%user.shell,
    rawres=%evt.rawres
    res=%evt.res
  priority: INFO
  tags: [user, commands, exec]
```

And this generates the following logline:

```
Jun 07 13:51:05 testserver falco[4144884]: 13:51:05.466854073: Informational Command ended: exe=/usr/bin/cat, pid=4144971, ppid=4124471, args=/etc/shadow, cwd=/home/mprbol/, uid=1000, loginuid=1000, user.name=mprbol, loginname=mprbol, shell=/bin/bash, rawres=0 res=SUCCESS
```

specifically:
```
rawres=0 res=SUCCESS
```

**Expected behaviour**

```
[mprbol@testserver ~]$ cat /etc/shadow
cat: /etc/shadow: Permission denied
[mprbol@testserver ~]$ echo $?
1
```

The exit code is clearly 1, I expect Falco to log the rawres/res of the application to be  1 / Failure

**Screenshots**

**Environment**

- Falco version:

Fri Jun  7 13:54:53 2024: Falco version: 0.38.0 (x86_64)
Fri Jun  7 13:54:53 2024: CLI args: falco --version
Fri Jun  7 13:54:53 2024: Falco initialized with configuration files:
Fri Jun  7 13:54:53 2024:    /etc/falco/falco.yaml
Fri Jun  7 13:54:53 2024: System info: Linux version 4.18.0-513.24.1.el8_9.x86_64 (mockbuild@x86-64-01.build.eng.rdu2.redhat.com) (gcc version 8.5.0 20210514 (Red Hat 8.5.0-20) (GCC)) #1 SMP Thu Mar 14 14:20:09 EDT 2024
Falco version: 0.38.0
Libs version:  0.17.1
Plugin API:    3.5.0
Engine:        0.40.0
Driver:
  API version:    8.0.0
  Schema version: 2.0.0
  Default driver: 7.2.0+driver
Fri Jun  7 13:54:53 2024: closing inspectors

- System info:

{
  "machine": "x86_64",
  "nodename": "meh",
  "release": "4.18.0-513.24.1.el8_9.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP Thu Mar 14 14:20:09 EDT 2024"
}

- Cloud provider or hardware configuration:
- OS:
RHEL 8.9

- Kernel:

 4.18.0-513.24.1.el8_9.x86_64 #1 SMP Thu Mar 14 14:20:09 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux

- Installation method:
- 
RPM

**Additional context**
N/A

**Comment by Andreagit97** [comment]
@MprBol thank you for this!

Looking at what you posted everything seems fine.
Your shell will successfully exec `cat` command and that's the reason why you see `rawres=0 res=SUCCESS`. Why should the `execve` fail in this case?

What is falling is the `open/openat` operation when you are trying to access `/etc/passwd` without enough privileges.

**Comment by MprBol** [comment]
hi @Andreagit97 , thank you for your quick response! If you're saying this is expected behaviour, then perhaps this issue should be a support question or a feature request. 

What I'd functionally like to achieve is to capture the exit-code of the program being started. 

The underlying ask is to capture what a potential threat actor is trying to do, and ascertain if he was successful or not, in as least log-lines as possible. Preferably 1. For many use cases, capturing the command he's trying to execute and logging the exit-code should be sufficient.  At least to get a global overview of what he's trying to do. 

Is that possible in Falco currently ? 

I'd prefer avoid capturing the `open/openat`, as it is very specific and looking at the cmdline its already clear what the threat actor is trying to do.

**Comment by Andreagit97** [comment]
uhm got it! Yes you can do it with Falco! You should use the `procexit` event and its field `evt.arg.res`. This could be an example

```yaml
- rule: Commands ended by user mprbol
  desc: Log the end of all commands executed by user mprbol with detailed information
  condition: (user.uid=1000 or user.loginuid=1000) and evt.type=procexit and evt.dir=> and proc.name=cat
  output: >
    Command ended:
    exe=%proc.exepath,
    pid=%proc.pid,
    ppid=%proc.ppid,
    args=%proc.args,
    cwd=%proc.cwd,
    uid=%user.uid,
    loginuid=%user.loginuid,
    user.name=%user.name,
    loginname=%user.loginname,
    shell=%user.shell,
    res=%evt.arg.ret
  priority: INFO
  tags: [user, commands, exec]
```

Note the ` evt.type=procexit ` and `res=%evt.arg.ret`.
Now if you try again `cat /etc/shadow` you should see

```
10:52:17.256228904: Informational Command ended: exe=/usr/bin/cat, pid=23015, ppid=22775, ...,  res=1
```

**Comment by MprBol** [comment]
Thank you! Ill try it ASAP. Ill close it for now, but will re-open if I can't get it to work. Thank you for your quick & clear responses!

**Comment by MprBol** [comment]
(it works, awesome!)
