### ISSUE TITLE
Support multiple container runtime in one node

### ISSUE THREAD

**Issue by hitsub2** [falcosecurity/falco#3279]
**Motivation**
The bottlerocket OS has two containerd runtime with different sock file, one for k8s, one for host-containers(management), currently only the k8s containerd is monitored, but we need falco to monitor another containerd.

And also in some scenarios, like Docker in Docker, the CI pod would host another docker daemon for build purpose.

**Feature**
Support multiple container runtime in one node.

**Alternatives**
None.

**Additional context**

Bottlerocket uses host containers(exclude from the k8s containerd, called host-containerd) to run ssh server (admin-container) and aws ssm. And these host containers should be monitored because of all the privileges that host containers have can access the k8s pods.

**Comment by leogr** [comment]
Tentatively for 
/milestone 0.40.0

**Comment by leogr** [comment]
Update

short-term solution (tentatively for 0.40) :point_down: 
My PR https://github.com/falcosecurity/libs/pull/2141 is now ready for review and, once merged, will bring support to multiple CRI engines simultaneously. We also discovered that specific containerd support is specifically required to address the Bottlerocket use case. A fix is in the making https://github.com/falcosecurity/libs/pull/2195

long-term solution :point_right: https://github.com/falcosecurity/falco/issues/3403

**Comment by leogr** [comment]
Note: we still miss https://github.com/falcosecurity/libs/pull/2195 for full compatibility. 
We should have everything addressed for Falco 0.40
