### ISSUE TITLE
[Question] Can Falco prevent?

### ISSUE THREAD

**Issue by za** [falcosecurity/falco#3280]
From README

> It is designed to detect and alert on abnormal behavior and potential security threats in real-time.

Hi there, I'd like to know can Falco _prevent_ security threats? As in README, it's written: _detect and alert_.

**Comment by LucaGuerra** [comment]
That is correct. Falco does not block or prevent kernel operations from happening. However, you can try reaction/response engines based on Falco alerts, such as the up-and-coming community driven [Falco Talon](https://github.com/falco-talon/falco-talon) project.

**Comment by za** [comment]
Thanks for the answer @LucaGuerra 

Closing the issue now.
