### ISSUE TITLE
"Drop and execute new binary in container rule" not working using modern_ebpf driver on EKS 1.29

### ISSUE THREAD

**Issue by shugg** [falcosecurity/falco#3286]
**Describe the bug**

The [Drop and execute new binary in container rule](https://github.com/falcosecurity/rules/blob/main/rules/falco_rules.yaml#L1175) does not work when using _modern_ebpf_ as driver and Falco runs on EKS 1.29. Some other rules, for example [Read sensitive file untrusted](https://github.com/falcosecurity/rules/blob/main/rules/falco_rules.yaml#L398) do work.

The [Drop and execute new binary in container rule](https://github.com/falcosecurity/rules/blob/main/rules/falco_rules.yaml#L1175) rule does work when:
- the _ebpf_ driver is used instead of _modern_ebpf_ on EKS
-  _modern_ebpf_ driver is used and Flaco runs on AKS instead of EKS

The kernel version is 5.10.219-208.866.amzn2.x86_64. I have tested in both privileged mode and least privilege mode using CAP_SYS_PTRACE, CAP_SYS_RESOURCE, CAP_BPF, and CAP_PERFMON. I also tried CAP_SYS_ADMIN instead of CAP_BPF and CAP_PERFMON. Issue remains, the rule does not trigger.

**How to reproduce it**

1. Deploy Falco on EKS 1.29 using the [official Helm chart](https://github.com/falcosecurity/charts/tree/master/charts/falco) (set helm value tty=true)
2. Inside a container do `cp /usr/bin/echo my_echo  && ./my_echo hello!`
3. Falco does not emit log message "Executing binary not part of base image"

**Expected behaviour**

Falco does emit log message:
"Critical Executing binary not part of base image (proc_exe=./my_echo proc_sname=sh gparent=sh ...)

**Environment**

- Falco version:  0.38.1
default_driver_version : 7.2.0+driver
driver_api_version : 8.0.0
driver_schema_version : 2.0.0
engine_version : 40
engine_version_semver : 0.40.0
libs_version : 0.17.2
plugin_api_version : 3.6.0

- Cloud provider or hardware configuration: Amazon EKS 1.29
- OS: Amazon Linux 2
- Kernel: 5.10.219-208.866.amzn2.x86_64

- Installation method: official helm chart

**Comment by Andreagit97** [comment]
Thank you! We will take a look ASAP!

**Comment by FedeDP** [comment]
Was able to reproduce this issue on an ec2 node.

**Comment by FedeDP** [comment]
Put this in 
/milestone 0.39.0 
for now.

**Comment by LucaGuerra** [comment]
Falco 0.38.2 is now released! I have tested this flag on EC2 and GCP with kmod/modern_ebpf and it looks like it is detected properly. Hopefully this is fixed but if not please open another issue.
