### ISSUE TITLE
can't install falco in CentOS 7.9

### ISSUE THREAD

**Issue by yf-0dyssey** [falcosecurity/falco#3318]
**Describe the bug**

  I want to install falco in K8s using helm. I try the default and legacy driver but they all failed. 

**How to reproduce it**

  First I read the official document(https://falco.org/docs/event-sources/kernel/#requirements) . 
![image](https://github.com/user-attachments/assets/9c098bbf-1252-4456-a69d-01d1b3760c97)

Because kernal is 3.10.0 and default Kernel module is suit for me. I using the below command to install falco following official document (https://github.com/falcosecurity/charts/tree/master/charts/falco#daemonset).
 **_helm install falco falcosecurity/falco --create-namespace --namespace falco_**
 After helm install is Ok, I find the falco pod is failed. Below is the screenshot. I using the logs to check, it said "Error: error opening device /host/dev/falco0".

  I read the offical document and find that It suggest using  the legacy image if using an older kernel version.
  
![image](https://github.com/user-attachments/assets/97be753a-631b-4aeb-b616-4939e5ef62c7)

 So I tried using the command to install falco again. But after helm install finished I found that falco pod is still failed. 
_**helm install falco falcosecurity/falco --create-namespace --namespace falco --set driver.loader.initContainer.image.repository=falcosecurity/falco-driver-loader-legacy**_
![image](https://github.com/user-attachments/assets/5395280b-978d-4b01-afff-dd0bcfcb0b5d)
 I using to logs to check and find the error info is the same. Below is the screenshot.
![image](https://github.com/user-attachments/assets/a9716473-d7fe-475f-8e1a-e07cacef1e7d)

   Pls help me find out the problem. Thanks  a lot! I want to know which falco version I should use and which driver is suit for me. Because our production is using CentOS7.9 and kernal is  also 3.10.0-1160.108.1.el7.x86_64. It's impossible to update kernal version.

**PS:before install falco again I have helm uninstall it.**

**Environment**

- Falco version:
0.38.2
- System info:

- OS: CentOS 7.9

- Kernel:
3.10.0-1160.el7.x86_64.
- Installation method:
K8s using helm

**Additional context**

**Comment by yf-0dyssey** [comment]
I even tried other two driver mode（ebpf and modern ebpf），but they all failed. The falco pod can't start normally.

**Comment by yf-0dyssey** [comment]
@LucaGuerra @Andreagit97 @alacuku  hi ，can anyone help me to solve this？ It confused me a very long time. Thank you all very much！

**Comment by alacuku** [comment]
Hey @yf-0dyssey, could you share the logs of the init container? It seems that we provide a precompile module for your kernel version, check it out here: https://d20hasrqv82i0q.cloudfront.net/?prefix=driver/7.2.1%2Bdriver/x86_64/

**Comment by yf-0dyssey** [comment]
> Hey @yf-0dyssey, could you share the logs of the init container? It seems that we provide a precompile module for your kernel version, check it out here: https://d20hasrqv82i0q.cloudfront.net/?prefix=driver/7.2.1%2Bdriver/x86_64/

Thank your reply. I have just try again using the epbf driver but it seems also failed. Below is the screenshot. I'll helm uninstall it and try the default driver again.
![image](https://github.com/user-attachments/assets/3b96f5f5-12cf-482b-bdc0-79f02960b0a4)

**Comment by yf-0dyssey** [comment]
@alacuku yes . I using command(**helm install falco falcosecurity/falco --create-namespace --namespace falco**) and it's default driver(kernel module).  It's right ? But falco pod still doesn't work. Below is the screetshot.
![image](https://github.com/user-attachments/assets/0b7266d8-5bcd-4ab4-b63e-2db563589f7d)

 I also check the **falco-driver-loader**  container log and paste as bleow. Pls check it. But it seems  there is no  any error info.
![image](https://github.com/user-attachments/assets/11fe150b-994c-4e8f-adbc-e2c44d9d4b8f)
[root@falco ~]# kubectl logs falco-hn2ts -c falco-driver-loader -n falco
* Setting up /usr/src links from host
2024-09-11 07:26:27 INFO  Running falcoctl driver config
                      ├ name: falco
                      ├ version: 7.2.1+driver
                      ├ type: kmod
                      ├ host-root: /host
                      └ repos: https://download.falco.org/driver
2024-09-11 07:26:27 INFO  Committing driver config to k8s configmap
                      └ namespace: falco
2024-09-11 07:26:27 INFO  Storing falcoctl driver config
2024-09-11 07:26:27 INFO  Running falcoctl driver install
                      ├ driver version: 7.2.1+driver
                      ├ driver type: kmod
                      ├ driver name: falco
                      ├ compile: true
                      ├ download: true
                      ├ target: centos
                      ├ arch: x86_64
                      ├ kernel release: 3.10.0-1160.el7.x86_64
                      └ kernel version: #1 SMP Mon Oct 19 16:18:59 UTC 2020
2024-09-11 07:26:27 INFO  Check if kernel module is still loaded.
2024-09-11 07:26:27 INFO  OK! There is no module loaded.
2024-09-11 07:26:27 INFO  Check all versions of kernel module in dkms.
2024-09-11 07:26:27 INFO  OK! There are no module versions in dkms.
2024-09-11 07:26:27 INFO  Trying to download a driver.
                      └ url: https://download.falco.org/driver/7.2.1%2Bdriver/x86_64/falco_centos_3.10.0-1160.el7.x86_64_1.ko
2024-09-11 07:26:30 INFO  Driver downloaded.
                      └ path: /root/.falco/7.2.1+driver/x86_64/falco_centos_3.10.0-1160.el7.x86_64_1.ko
2024-09-11 07:26:30 INFO  Success: module found and loaded in dkms.
                      └ driver: /root/.falco/7.2.1+driver/x86_64/falco_centos_3.10.0-1160.el7.x86_64_1.ko
[root@falco ~]#

**Comment by yf-0dyssey** [comment]
> hey @yf-0dyssey, the kernel module has been correctly loaded.
> 
> Could you also share the Falco container logs?

Yes. I just paste the logs and upload the screenshot. Pls check them.

**Comment by alacuku** [comment]
Please uninstall falco and then install it running the following command: 
```
helm install falco falcosecurity/falco \
    --namespace falco \
    --create-namespace \
    --set driver.kind=kmod
```

**Comment by yf-0dyssey** [comment]
> Please uninstall falco and then install it running the following command:
> 
> ```
> helm install falco falcosecurity/falco \
>     --namespace falco \
>     --create-namespace \
>     --set driver.kind=kmod
> ```

Thanks you a lot ！ I really appreciate yours quick and patient instructions！ I tried using the _--set driver.kind=kmod_ options and it works. The  falco finally initialized normally.
![image](https://github.com/user-attachments/assets/abc4a459-8fe0-4977-9040-8a5f4018fdf7)

Btw, I really want to consult you. Why it must using the _--set driver.kind=kmod_ option explicitly. Does it use the kmod driver when using the _helm install falco falcosecurity/falco --create-namespace --namespace falco_ command? I didn't  find any description in official docs. :)
