### ISSUE TITLE
Alerts for mkdir should include mkdirat

### ISSUE THREAD

**Issue by jmcarp** [falcosecurity/falco#337]
In experimenting with falco, we noticed that the `write_binary_dir` rule works with python's `os.mkdir` but not golang's `os.Mkdir`. @wjwoodson did some sleuthing and found that python's `mkdir` uses the `mkdir` syscall, but golang's uses `mkdirat`. It would be helpful if rules based on `mkdir` checked for both syscalls to avoid false negatives.

**Comment by leodido** [comment]
Asking help to my rules magician friend @Kaizhe !
