### ISSUE TITLE
Make linux_hostinfo platform optional

### ISSUE THREAD

**Issue by jemag** [falcosecurity/falco#3411]
**Motivation**

After discussion in the following issue: https://github.com/falcosecurity/charts/issues/754 , what I could gather is that the new linux_hostinfo platform provides additional information to plugins should they need it.

However, Falco being a fairly general tool to process event streams and apply rules to them, plugins can be made to target event streams where the hostinfo of where Falco is running is irrelevant, or of very little concern.

I think it would be great if this could be optional, so that, when deployed to Kubernetes, `hostPath` is not required.

**Feature**
Make the new linux_hostinfo platform optional so that it can be turned off and `hostPath` isn't required.

**Alternatives**
Keep `hostPath` even though it is not required by plugin.

**Comment by jemag** [comment]
> Indeed, we could add a Falco config key to disable the default behavior of adding hostinfo to the plugin run, wdyt?

That would be great!

**Comment by FedeDP** [comment]
Opened https://github.com/falcosecurity/falco/pull/3412 to implement the new config key!
