### ISSUE TITLE
Add support for Ory (IAM)

### ISSUE THREAD

**Issue by mfreeman451** [falcosecurity/falco#3420]
**Motivation**
In addition to the native Okta integration, it would be nice if Falco supported one of the leading cloud-native kubernetes-centric IAM solutions, Ory (https://ory.sh)

**Feature**

Similar to the Okta integration, Ory events would be propagated to Falco and processed by the rule engine.

**Alternatives**

N/A

**Additional context**

**Comment by Issif** [comment]
Hi,

Can you re-open this issue in the plugins repository, please: https://github.com/falcosecurity/plugins

I was able to develop the plugin for Okta cause I have access to an instance, for Ory, it requires the same. If you have access and feel confident enough, you can develop the plugin yourself and propose it to the community. See our docs for more details: https://falco.org/docs/plugins/developers-guide/how-to-develop/

**Comment by mfreeman451** [comment]
yeah will do, thank you. I opened this intending to provide the PR, appreciate the links.
