### ISSUE TITLE
Condition support compare 2 fields

### ISSUE THREAD

**Issue by gccli** [falcosecurity/falco#3435]
**Motivation**

To write more flexible rules

**Feature**

Falco macro or rule condition can comparisons of two fields, such as for `setuid` syscall, we can fillter events with macro `user_known_non_sudo_setuid_conditions`:

```
- macro: user_known_non_sudo_setuid_conditions
  condition: (user.name=root or evt.arg.uid=user.uid)
```

**Additional context**

In alpine:3 image, when run grep process with non-root user can trigger "Non sudo setuid" rule.

```
{
  "hostname": "ec2",
  "output_fields": {
    "container.id": "65b387993dfc",
    "container.name": "modest_lamarr",
    "evt.arg.uid": "demo",
    "evt.time": 1734604992817250149,
    "evt.type": "setuid",
    "proc.cmdline": "grep localhost /etc/hosts",
    "proc.exepath": "/bin/busybox",
    "proc.name": "grep",
    "proc.pname": "sh",
    "proc.tty": 34816,
    "user.loginuid": -1,
    "user.name": "demo",
    "user.uid": 1000
  },
  "priority": "Notice",
  "rule": "Non sudo setuid",
  "source": "syscall",
  "tags": [
    "T1548.001",
    "container",
    "host",
    "maturity_incubating",
    "mitre_privilege_escalation",
    "users"
  ],
  "time": "2024-12-19T10:43:12.817250149Z"
}
```

When `strace`  grep we got:

```
ec2:~$ strace grep localhost /etc/hosts
...
setgid(1000)                            = 0
```

**Comment by Issif** [comment]
Hi,

This is already possible since Falco 0.38 with the operator `val()`

```
- macro: user_known_non_sudo_setuid_conditions
  condition: (user.name=root or evt.arg.uid=val(user.uid))
```

Regards

**Comment by gccli** [comment]
> Hi,
> 
> This is already possible since Falco 0.38 with the operator `val()`
> 
> ```
> - macro: user_known_non_sudo_setuid_conditions
>   condition: (user.name=root or evt.arg.uid=val(user.uid))
> ```
> 
> Regards

Thanks, I have verified. It would be more reasonable if `evt.arg.uid` returned a numeric value

```
... 
 "output_fields": {
    "evt.arg.uid": "demo",
    "user.name": "demo",
    "user.uid": 1000
...
  },
```

**Comment by gccli** [comment]
Already supported in Falco 0.38
