### ISSUE TITLE
Many rules don't work on recent glibc

### ISSUE THREAD

**Issue by teresaejunior** [falcosecurity/falco#377]
As discussed in the #falco Slack channel, recent glibc versions started using "openat" instead of "open" to write files. This causes `write_etc_common` to fail detecting events on recent systems.

Tested on Ubuntu 18.04 with libc6 2.27-3ubuntu1

**Comment by teresaejunior** [comment]
Possible duplicate of https://github.com/draios/falco/issues/337

**Comment by teresaejunior** [comment]
Possibly related: https://github.com/draios/sysdig/issues/979 and https://github.com/draios/sysdig/issues/162

**Comment by teresaejunior** [comment]
I have researched more into this issue and, not only write_etc_common doesn't work on recent glibc, but any event that depends on `fd.name` with `evt.is_open_write` or `evt.is_open_read`.

**Rules currently broken**:

* Read sensitive file trusted after startup
* Read sensitive file untrusted
* Write below binary dir
* Write below root
* Write below rpm database
* Write below etc
* All my personal rules depend on either `open_read` or `open_write`

**`evt.arg.name`** instead works with `evt.is_open_write` or `evt.is_open_read` on recent systems, but is not a valid filter on Falco, and doesn't give the full path name (only `.profile` here, not `/home/...`)

```sh
$ sudo sysdig 'evt.is_open_read=true and evt.arg.name=.profile'
25317 16:26:39.205428237 3 cat (22280) > openat dirfd=-100(AT_FDCWD) name=.profile flags=1(O_RDONLY) mode=0
```

The difference between the output of `sudo sysdig 'fd.name=/home/teresaejunior/.profile'` with `cat ~/.profile` on older and newer systems is the following:

```sh
# On older systems:
69523 21:09:43.837113280 0 cat (8402) < open fd=3(<f>/home/teresaejunior/.profile) name=.profile(/home/teresaejunior/.profile) flags=1(O_RDONLY) mode=0 
```

```sh
# On newer systems:
32430 16:08:48.343496149 0 cat (20168) < openat fd=3(<f>/home/teresaejunior/.profile) 
```

I will gladly follow up with any more information needed!

**Comment by mstemm** [comment]
Thanks, we have some pending changes to add openat support, but those were blocked in sysdig while we make changes to event handling for openat/etc. We're getting pretty close now, though--look at https://github.com/draios/sysdig/pull/1163. Part of that PR includes changes to openat/etc.

**Comment by teresaejunior** [comment]
Awesome!

**Comment by mstemm** [comment]
I believe we've addressed this now. The sysdig changes were merged beginning of August and were incorporated in falco 0.12.1. I tested this by Running falco 0.12.1 on both Ubuntu 16.04 and 18.04 and running `sudo touch /etc/hack`. In both cases the `Write below etc` rule fired:

```
11:34:07.140201950: Error File below /etc opened for writing (user=root command=touch /etc/hack parent=sudo pcmdline=sudo touch /etc/hack file=/etc/hack program=touch gparent=bash ggparent=emacs gggparent=bash)
```

 I'll close this for now, please re-open if you still are noticing problems.
