### ISSUE TITLE
How and where to whitelist processes and binaries in the local rule file?

### ISSUE THREAD

**Issue by srivastavaabhinav** [falcosecurity/falco#385]
Hi there,

We are exploring falco to protect our host and containers, and realized that the default rules only monitor known pre-installed system binaries such as ls/ps etc. for malicious network connections and file read/write. To be able to know if a new process is created or made network connections or performed malicious file access, we created some additional new rules in our local rule file. However, it soon started giving us lots of false positives. My question is -- where and how can we whitelist process/binaries and the network connections/files opened made by them in the local rule file? Also, where and how to whitelist remote IPs in the file?

Your response and help would be highly appreciated.

Thanks
Abhi

**Comment by mstemm** [comment]
If you'd like to attach the local rules file, we can take a look.

There isn't really a hook to globally whitelist the activity of a list of processes. We generally do this by adding conditions to a rule to address false positives. `write_etc_common` is an example of that, with many many exclusions for programs that write specific files below /etc.

**Comment by mstemm** [comment]
If you'd like to follow up on slack (https://sysdig.slack.com/messages/falco), we can continue the discussion there. For now, closing this issue.
