### ISSUE TITLE
Storing all events to firebase

### ISSUE THREAD

**Issue by cstayyab** [falcosecurity/falco#395]
I want to setup falco such that it's every event ( including which are not in rule files) are stored in Google  Firebase.

**Comment by palmerabollo** [comment]
You can use the `program_output` in your configuration (see [docs](https://github.com/draios/falco/wiki/Falco-Configuration#program_output)) and call the Firebase API or run a script that executes any logic you need.

Take a look at this [example that sends an email](https://github.com/draios/falco/blob/master/falco.yaml#L100-L103). You could replace the email submission with a call to Firebase.

**Comment by cstayyab** [comment]
OK. So as I thought this is the **only** way to do that. 
**But** I have another question related to this: How can I pass all the variables (e.g. every variable/value from `evt, fd,proc,thread` etc fields) Is there any switch/way to do it or I will have to write all the variable names manually in the `output` field of `rule` ?

**Comment by mstemm** [comment]
For a given system call, there are potentially hundreds of field values that can apply for a given system call once you include the context of the executing program, files on which the syscall might act, etc.

You can see the full field list on the sysdig wiki (https://github.com/draios/sysdig/wiki/Sysdig-User-Guide). You can see that there might be lots of different fields that you might be interested in.

I think you're better off paring down the conditions to ones you're interested in and then for each condition choose only the fields for the information you need.

We can follow up the discussion on our public slack if you'd like (https://sysdig.slack.com/messages/falco). But for now, closing this issue.
