### ISSUE TITLE
Falco does support Application monitoring

### ISSUE THREAD

**Issue by naren25** [falcosecurity/falco#404]
Hi 

I am new to Falco, i have read some documents, but i am not able to figure it.
my question is, Does falco  monitor application behaviour as well? suppose if i am using DVWA application running through docker and open the application in browser and performing some unwanted operation like trying to upload some unwanted files etc. 
Thanks & regards,
Naren

**Comment by mstemm** [comment]
This is a pretty general question, so let's track the conversation over in our public slack if you have additional questions. For now, closing this issue.
