### ISSUE TITLE
Consider moving to ALv2+DCO when in CNCF

### ISSUE THREAD

**Issue by caniszczyk** [falcosecurity/falco#427]
CLAs are optional in CNCF and you can just use ALv2+DCO

It's very easy to add a DCO checker to your repo/org: https://github.com/apps/dco

Let me know if you have any questions.

**Comment by fntlnz** [comment]
@caniszczyk we implemented this already in the test-infra and office-hours repo. This will be rolled out to the falco repo soon.

Here's an example on how it behaves, https://github.com/falcosecurity/test-infra/pull/5

Wdyt?

**Comment by caniszczyk** [comment]
LGTM but I also just enabled it via here: https://github.com/organizations/falcosecurity/settings/installations/1117117

**Comment by fntlnz** [comment]
Ok, we'll swap it once Prow is enabled in this repo. Thank you

**Comment by leodido** [comment]
Hey @caniszczyk we are now using the [dco](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/dco) plugin of [prow](https://github.com/kubernetes/test-infra/tree/master/prow) (the same tool, soon to be into the sigs, used by Kubernetes and others).

For this reason we deactivated the [dco app](github.com/apps/dco) you setup some days ago.
