### ISSUE TITLE
Getting docker image ID instead of name on container.image

### ISSUE THREAD

**Issue by cacedo** [falcosecurity/falco#431]
Hi,

I'm using the `container.image` field to whitelist containers running in Kubernetes pods, for example:
```
    - macro: trusted_containers
      condition: (container.image startswith "docker@" or
                    (container.image startswith sysdig/falco and not container.image startswith sysdig/falco-event-generator) or
                     container.image startswith quay.io/coreos/flannel or
  ....
```
The problem is that for some containers I get the image ID, for instance:
```
sha256:69c3e2ce9aeeb61aca4b8bfe3338991bbf0e5b907199ea1452611656fc4e3040
```
instead of `solsson/kafka`

`docker ps` command shows also the image ID instead of the name for the container, so could be a problem with docker. `docker images` shows the right name 

Interestingly enough, if I change the `imagePullPolicy` to `Always` for those pods in Kubernetes, the image name is picked up.

Is there any way of getting the image name in these cases?

Versions I'm using:
Kubernetes: 1.10.3
Docker: 17.03.2-ce
Falco: 0.10.0 (also tried 0.12.1)

Thank you.

**Comment by mattpag** [comment]
We recently added sysdig support for additional fields (`container.image.repository`, `container.image.tag`, `container.image.digest`) that are correct even in those cases - where k8s spawns the containers using only the imageID as image name.

We have in pipeline to patch the falco rules to take them into account as well.
In the meantime, you may want to do it yourself by modifying the `trusted_containers` macro to use them instead of just `container.image` (and even open a PR if you want to tackle it for the whole default rules set).

**Comment by cacedo** [comment]
Thanks @mattpag, do you know on what version was `container.image.repository` introduced? I couldn't find it in the changelog.

**Comment by cacedo** [comment]
Thanks mattpag just tested with `0.12.1` and `container.image.repository` it's working fine

**Comment by mstemm** [comment]
Closing this issue then.

**Comment by JPLachance** [comment]
Hello @mattpag,

I'm using Falco 0.13.1 and it looks like Falco rules where not updated yet. Do you need help to rework the entire rules file?

Thanks!

**Comment by mattpag** [comment]
Hi @JPLachance,

https://github.com/falcosecurity/falco/pull/513 contains the updated version of the rules you're looking for.

We're pretty confident about the changes so you can reasonably expect them to be included in the next release, but do you also want to try them and see if they resolve your use cases?

Thank you!

**Comment by JPLachance** [comment]
Hello @mattpag,

Thank for this. I've been running with those new rules since then without any issue.

Thanks for sharing! 😃

**Comment by mattpag** [comment]
No problem, happy to help!
