### ISSUE TITLE
Allow multiple program outputs

### ISSUE THREAD

**Issue by mstemm** [falcosecurity/falco#458]
Discussion originally brought up in https://github.com/falcosecurity/falco/issues/422. Filing as a new issue to track the new feature.

Currently, falco only supports a single program output. However, it would be nice to support multiple `program_output`s instead.

**Comment by Issif** [comment]
can be associated to #528

**Comment by fntlnz** [comment]
I think we can close this, #528 is already tracking improvements on outputs, I'm adding this bit of information there since it's likely that when that will be done we will reconsider how outputs are designed and tracking everything there seems a better option.
