### ISSUE TITLE
Prometheus and rule: Write below etc

### ISSUE THREAD

**Issue by openJT** [falcosecurity/falco#462]
Hi,

I just updated Falco now using the helm version, was previously running from the repo. I now have this issue with Prometheus. Is there a way to mute an Error? Is this a bug? See Error below. Any help appreciated.

Thanks

16:12:02.407902607: Error File below /etc opened for writing (user=<NA> command=prometheus-conf --log-format=logfmt --reload-url=http://127.0.0.1:9090/-/reload --config-file=/etc/prometheus/config/prometheus.yaml --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml parent=docker-containe pcmdline=docker-containe 36615f3560224e640bc6c8d2ce91807a8948d843056f554c3881e3d640afc629 /var/run/docker/libcontainerd/36615f3560224e640bc6c8d2ce91807a8948d843056f554c3881e3d640afc629 docker-runc file=/etc/prometheus/config_out/prometheus.env.yaml program=prometheus-conf gparent=docker-containe ggparent=dockerd gggparent=systemd) k8s.pod=prometheus-kube-prometheus-prometheus-prometheus-0 container=36615f356022 k8s.pod=prometheus-kube-prometheus-prometheus-prometheus-0 container=36615f356022

**Comment by mfdii** [comment]
Sounds like we should add `/etc/prometheus` to the [`safe_etc_dirs` list](https://github.com/falcosecurity/falco/blob/dev/rules/falco_rules.yaml#L751-L752).

To get rid of this you can add the below to your `falco_rules.local.yaml`.

```
- list: safe_etc_dirs
  append: true
  items: [ /etc/prometheus ]
```

If adding that to your local rules gets rid of the alert, would you mind submitting a PR changing the default rules to include the prometheus etc directory.

**Comment by openJT** [comment]
Thank you. It works!

Unfortunately after reading your contributor agreement I will not submit a pull request.

**Comment by mfdii** [comment]
I'd love to hear more about what you don't like about the contributor agreement. You can DM me on the Sysdig slack (@ducy).
