### ISSUE TITLE
Duplicate alerts 

### ISSUE THREAD

**Issue by ashishxooa** [falcosecurity/falco#482]
Hi Team,

I want to have a rule where by running apt-get inside the container should trigger the alert. 

now I have this in my rules file. 

- rule: apt-get_in_container
  desc: notice apt-get activity within a container
  condition: container.id != host and proc.name = apt-get
  output: apt-get in a container (user=%user.name container_id=%container.id container_name=%container.name shell=%proc.name parent=%proc.pname cmdline=%proc.cmdline)
  priority: ERROR

When I do apt-get inside the container, I 'm getting alerts but 100s of them unless I exit the container I keep getting alerts. 

Eg.
```
09:23:07.606947143: Error apt-get in a container (user=root container_id=ec715805d1c5 container_name=compassionate_wescoff shell=apt-get parent=sh cmdline=apt-get )
09:23:07.606952523: Error apt-get in a container (user=root container_id=ec715805d1c5 container_name=compassionate_wescoff shell=apt-get parent=sh cmdline=apt-get )
09:23:07.607246655: Error apt-get in a container (user=root container_id=ec715805d1c5 container_name=compassionate_wescoff shell=apt-get parent=sh cmdline=apt-get )
09:23:07.607263221: Error apt-get in a container (user=root container_id=ec715805d1c5 container_name=compassionate_wescoff shell=apt-get parent=sh cmdline=apt-get )
09:23:07.607394780: Error apt-get in a container (user=root container_id=ec715805d1c5 container_name=compassionate_wescoff shell=apt-get parent=sh cmdline=apt-get )
09:23:07.607398889: Error apt-get in a container (user=root container_id=ec715805d1c5 container_name=compassionate_wescoff shell=apt-get parent=sh cmdline=apt-get )
09:23:07.612646798: Error apt-get in a container (user=root container_id=ec715805d1c5 container_name=compassionate_wescoff shell=apt-get parent=sh cmdline=apt-get )
```

**Comment by mfdii** [comment]
You should always include an evt.type field to filter events on. Else you can see this behavior. See the docs:
https://github.com/falcosecurity/falco/wiki/Falco-Rules#rule-condition-best-practices
