### ISSUE TITLE
Add hostname to slack notification

### ISSUE THREAD

**Issue by ashishxooa** [falcosecurity/falco#483]
Hi, 

Is there a way where I can append the hostname to the messages I 'm getting on slack? 

Eg. I 've received the below alert. Which gives me the container id, now this container ID could be anywhere on my servers running docker. 

`10:19:08.010189604: Informational Container with sensitive mount started (user=root command=runc:[1:CHILD] init docker123321-mysql (id=c2feddeb9679) image=alpine:latest mounts=/etc:/mnt/etc::true:rprivate)
`

How do I know quickly the host from this alert? It could be variable like $Hostname or even hard-coded value but it's needed. Thanks.

**Comment by mfdii** [comment]
@mstemm Sysdig doesn't have a hostname field. I assume we should open this against sysdig?

**Comment by mstemm** [comment]
Yeah I guess handling it in sysdig would be fine. It's on the line between something that should be added in the event or something added to the alert.

**Comment by leodido** [comment]
@mfdii @mstemm could you please update the status of this?

**Comment by mstemm** [comment]
No changes yet. You could always add the hostname when creating the json that goes to the slack webhook, but there isn't anything automatic from falco.

**Comment by ashishxooa** [comment]
@mstemm so different web hook configuration for different hosts?

**Comment by mstemm** [comment]
What the fix for this would look like would be to add filtercheck fields something like %host.name to sysdig, and then using them in falco. Then the text of the falco alert would have the hostname.

What I meant by "add the hostname when creating the json" was that you could change the json however you wished before sending it to the slack webhook, including adding a hostname.

**Comment by fntlnz** [comment]
Closing in favor of https://github.com/falcosecurity/falco/issues/528
