### ISSUE TITLE
Create hardened systemd config for rpm and debian packages

### ISSUE THREAD

**Issue by juju4** [falcosecurity/falco#484]
Trying to reduce attack surface on falco with systemd
https://www.freedesktop.org/software/systemd/man/systemd.exec.html

For now, pushed in devel branch of my ansible role.
https://github.com/juju4/ansible-falco/blob/devel/templates/systemd-falco.service.j2

Feel free to comment and test!
(testing into containers is obviously limited...)

Thanks

**Comment by mfdii** [comment]
@juju4 is this something that needs to be added to the falco service if it's installed via RPM?

**Comment by juju4** [comment]
yes, to add to package and replace init file(for debian or redhat)
https://github.com/falcosecurity/falco/blob/32f8e304eb1bd0ee427b763cdd450fa7d66b27e7/scripts/debian/falco

**Comment by juju4** [comment]
any details on why wontfix?
change is not a complex one even if more testing is needed. Works fine on my side but obviously not representative.
Thanks

**Comment by fntlnz** [comment]
@juju4 the wontfix label had been removed, it was automatically added by our stale bot.

**Comment by juju4** [comment]
Thanks @fntlnz 
How to get forward with this?

**Comment by fntlnz** [comment]
So @juju4 if I understood correctly what you are suggesting is that we replace our initd files with systemd files in the two scripts folder we have for debian and rpm.

I agree that this is something that should be in our roadmap, we need to figure out two things: 

- If the output deb and rpm packages are used to install Falco on old machines (without systemd) we need to maintain both
- What are the exact systemd options we want, I also think that we need to setup capabilities as we will do for Kubernetes (https://github.com/falcosecurity/falco/issues/628) - https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Capabilities

**Comment by fntlnz** [comment]
@juju4 I'm adding this to the Main project board to prioritize it, hope you don't mind if I change this issue title to be more descriptive. Let me know if I got what you meant!

**Comment by fntlnz** [comment]
@juju4 hey! The current maintainers team can't work on this in the short term, would you like to send a PR with what you have ? It looks like you're very close with your definition and we'd like to have a contribution from you !

**Comment by leodido** [comment]
Hey @juju4 this is a really cool contribution. Do you mind submitting a PR for it? :)

**Comment by juju4** [comment]
It does not seem that quick

* if using normal debian packaging, that would go through rules file like
https://github.com/Ubuntu-Solutions-Engineering/openstack-deb/blob/master/debian/rules
https://github.com/lxc/lxd-pkg-ubuntu/blob/dpm-xenial/debian/rules
but you have no such file, nor control or changelog in debian dir which are required by dpkg-buildpackage

* It seems that you are using cpack debian generator but it has no systemd option that I see
https://cmake.org/cmake/help/v3.6/module/CPackDeb.html
digging more, found this, which might be an option
https://github.com/arangodb/arangodb/blob/master/Installation/debian/postinst.in

quick untested PR
