### ISSUE TITLE
Custom macro expansion issues in falco_rules.local.yaml

### ISSUE THREAD

**Issue by JPLachance** [falcosecurity/falco#504]
Greetings,

I an trying to define some custom conditions in the `user_read_sensitive_file_conditions` macro. That macro is defined in falco_rules.yaml and I'm overriding it in `falco_rules.local.yaml`.

To make my YAML file cleaner, I'm defining the following macro:
```YAML
- macro: puppet_access_sudoers
  condition: proc.name=puppet and proc.cmdline="puppet /usr/bin/puppet agent" and fd.name startswith "/etc/sudoers"
```

Then, I'm using the `puppet_access_sudoers` in the override of `user_read_sensitive_file_conditions`:
```YAML
- macro: user_read_sensitive_file_conditions
  condition: puppet_access_sudoers
```

The result is the following error:
```
Fri Jan 25 22:02:20 2019: Runtime error: Error loading rules: /usr/share/falco/lua/compiler.lua:78: Undefined macro 'puppet_access_sudoers' used in filter.. Exiting.
```

The `puppet_access_sudoers` is defined above the override `user_read_sensitive_file_conditions`, but the Lua compiler fails to find it.

A workaround is the following:
```YAML
- macro: user_read_sensitive_file_conditions
  condition: proc.name=puppet and proc.cmdline="puppet /usr/bin/puppet agent" and fd.name startswith "/etc/sudoers"
```

It works, but it will be more complicated to maintain. :)

Thanks for your help!

**Comment by mfdii** [comment]
@mstemm any thoughts on why the Lua compiler isn't working for this macro?

**Comment by JPLachance** [comment]
Hello! I think we need this one because it will allow users to make their rules cleaner 🙂

**Comment by mstemm** [comment]
Ok, reopening.

**Comment by leodido** [comment]
Related to #706

**Comment by fntlnz** [comment]
I think we can close this since it had been detailed a lot more in #706 - wdyt @JPLachance  ?

**Comment by JPLachance** [comment]
Have fun! :)
