### ISSUE TITLE
Add support for parameterized macros

### ISSUE THREAD

**Issue by mstemm** [falcosecurity/falco#510]
In some cases, there are repeated segments of condition text that differ only in a path, process name, etc. For example `container.image startswith <prefix> or container.image.repository contains <prefix>` is a way to check for a container name containing a prefix.

To address cases like this, it would be useful to have parameterized macros, for example:

```
- macro: container_image
       param: name
       condition: container.image startswith name or container.image.repository contains name
...
      condition: container_image(<prefix>) or ....
```

This would allow avoiding having repeated text for these common patterns.

**Comment by mstemm** [comment]
We should keep this on the roadmap.

**Comment by leodido** [comment]
Keep
