### ISSUE TITLE
kubectl get pods (Status: CrashLoopBackOff)

### ISSUE THREAD

**Issue by adrianmulyawan** [falcosecurity/falco#516]
Hello ...
I want to ask here I installed sysdig falco using daemonset. Here I am using Google Kubernetes Engine. I followed all the steps given. My question here is that when I run the Kubectl get pods command, the results displayed by my pods experience CrashLoopBackError, even though I use the latest git clone falcosecurity, so how do I get my pods running?
`kubectl get pods`
`NAME                    READY     STATUS             RESTARTS   AGE`
`falco-daemonset-t254c   0/1       CrashLoopBackOff   5          3m`
`falco-daemonset-vsh5k   0/1       CrashLoopBackOff   5          3m`
`falco-daemonset-899wg   0/1       Pending            0          0s`

**Comment by mfdii** [comment]
Sorry, are you still having this issue?
