### ISSUE TITLE
GPG key issue?

### ISSUE THREAD

**Issue by juju4** [falcosecurity/falco#525]
Since yesterday or so, seeing issue in travis for falcon install on debian/ubuntu

https://travis-ci.org/juju4/ansible-falco/jobs/491276736#L2540
```
   "stderr": "W: GPG error: http://download.draios.com/stable/deb stable-amd64/ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 026810B163535FC5\nE: The repository 'http://download.draios.com/stable/deb stable-amd64/ InRelease' is not signed.\n", 
    "stderr_lines": [
        "W: GPG error: http://download.draios.com/stable/deb stable-amd64/ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 026810B163535FC5", 
        "E: The repository 'http://download.draios.com/stable/deb stable-amd64/ InRelease' is not signed."
```

https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public was installed before.

**Comment by mstemm** [comment]
Sorry for that, we inadvertently signed the latest 0.14.0 release with an incorrect gpg key. We've re-published the packages and rpm/apt metadata signed with the right gpg key, so it should be working now.
