### ISSUE TITLE
ROADMAP: Prometheus Metrics Exporter

### ISSUE THREAD

**Issue by mfdii** [falcosecurity/falco#530]
**Description**: Export prometheus metrics via a `/metrics` endpoint. Metrics would include:

- Total rules triggered
- Events dropped
- Count of rules triggered by:
  - rule name
  - rule event source
  - rule tag
- Alerts sent
- Alerts failed to send
  - Total
  - by output

**Skills required:** C++, Familiar with prometheus metrics format (OpenMetrics).

**Comment by mfdii** [comment]
This needs to get added to Google SOC project ideas.

**Comment by JPLachance** [comment]
Creating a metrics endpoint for Falco was also proposed in issue #421.

**Comment by LoganSteinberg** [comment]
Hey, I was thinking of picking this up.
I was curious if anyone has an idea what progress, if any, was made before it was moved back to 'To do' incase there's a base I should be working off of?
@mfdii since you moved it back to 'To do'

**Comment by leodido** [comment]
Hey @LoganSteinberg thanks to @leogr we have an initial work done in this direction.

Look to the [falco-exporter](https://github.com/falcosecurity/falco-exporter) repo.

Would you mind contributing there? Contributions will be very welcome! :)

**Comment by Issif** [comment]
For those who use `falcosidekick`, the last release embbeds a prom exporter : https://github.com/falcosecurity/falcosidekick#prometheus

**Comment by leogr** [comment]
I believe we can say this is done since both [falco-exporter](https://github.com/falcosecurity/falco-exporter) and [falcosidekick](https://github.com/falcosecurity/falcosidekick#prometheus) can be used for metrics.
Likely, we will also get metrics about drops soon (see https://github.com/falcosecurity/falco/pull/1451).

/close
