### ISSUE TITLE
Is falco expected in Container-Optimised OS (cos) support?

### ISSUE THREAD

**Issue by ilcapone** [falcosecurity/falco#538]
Hey!
Trying to deploy the solution for k8, in GKE with Container-Optimised OS (cos), following the guide [k8-guide-with-RBAC](https://github.com/falcosecurity/falco/blob/dev/integrations/k8s-using-daemonset/README.md) and [sysgig gke](https://sysdig.com/blog/falco-gke-kubernetes-security/). looking for the requirements I found this [Host Requirements for Agent Installation](https://sysdigdocs.atlassian.net/wiki/spaces/Platform/pages/192151570/Host+Requirements+for+Agent+Installation#HostRequirementsforAgentInstallation-CloudPlatformsSupported)  that says that only ubuntu for GKE is supported.  Are you working on support for Container-Optimised OS (cos) in the short ,medium or large term? Additionally I add the error obtained when the falco container is deploy. 
```
lasas@asdgr$ kubectl logs falco-daemonset-v87fn
* Setting up /usr/src links from host
ls: cannot access '/host/usr/src': No such file or directory
* Unloading falco-probe, if present
* Running dkms install for falco
Error! echo
Your kernel headers for kernel 4.14.65+ cannot be found at
/lib/modules/4.14.65+/build or /lib/modules/4.14.65+/source.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/0.14.0/build/make.log
* Trying to load a system falco-probe, if present
* Trying to find precompiled falco-probe for 4.14.65+
Found kernel config at /proc/config.gz
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.14.
0-x86_64-4.14.65%2B-ad3fe2a2ff0bc98fa2a27b815b116fb6.ko
Download failed, consider compiling your own falco-probe and loading it or getting in touch with the sysdig community
Tue Feb 19 12:56:00 2019: Falco initialized with configuration file /etc/falco/falco.yaml
Tue Feb 19 12:56:00 2019: Loading rules from file /etc/falco/falco_rules.yaml:
Tue Feb 19 12:56:01 2019: Loading rules from file /etc/falco/falco_rules.local.yaml:
Tue Feb 19 12:56:01 2019: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Tue Feb 19 12:56:01 2019: Unable to load the driver. Exiting.
Tue Feb 19 12:56:01 2019: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco-p
robe module is loaded.. Exiting.
```

**Comment by mstemm** [comment]
Yes, to run on COS you can use falco with our ebpf program, which takes the place of the kernel module. We just announced that ebpf support is GA, you can read more about it in this blog post: https://sysdig.com/blog/sysdig-and-falco-now-powered-by-ebpf/

**Comment by mfdii** [comment]
This is also documented in the daemonset: 

https://github.com/falcosecurity/falco/blob/dev/integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap.yaml#L21
