### ISSUE TITLE
Note when alerts are correlated with system call drops

### ISSUE THREAD

**Issue by mstemm** [falcosecurity/falco#545]
Falco's internal state can get confused in the face of dropped system calls, and dropped system calls can be common when doing a fetch of container information. We should identify periods where there are dropped system calls and flag any falco events during that time as potentially tainted by the dropped system calls.

**Comment by justinzhf** [comment]
@mstemm hi! I am a graduate student of Nanjing University of Aeronautics and Astronautics. My major is data mining, to be exact, research on anomaly detection of complex system. I have finished a paper about power system anomaly detection. I am interested in this idea of GSoC 2019(https://github.com/cncf/soc/blob/master/README.md#falco-integration-with-aiml-platforms). I really want to do something about this idea, could you tell me how can I get started? Thanks you.

**Comment by justinzhf** [comment]
@mstemm @mstemm hi! I am a graduate student of Nanjing University of Aeronautics and Astronautics. My major is data mining, to be exact, research on anomaly detection of complex system. I have finished a paper about power system anomaly detection. I am interested in this idea of GSoC 2019(https://github.com/cncf/soc/blob/master/README.md#falco-integration-with-aiml-platforms). I really want to do something about this idea, could you tell me how can I get started? Thank you.

**Comment by mstemm** [comment]
@justinzhf your comment doesn't really have anything to do with this github issue. The way to apply for google summer of code projects is via https://summerofcode.withgoogle.com/. It looks like applications will be accepted between March 25 and April 9. 

I'll keep your comment and this reply up for a few days but I'll delete them afterward as it's not really related to this github issue.

**Comment by mstemm** [comment]
Fixed by https://github.com/falcosecurity/falco/pull/561.
