### ISSUE TITLE
Fluentd went mad after installing falco

### ISSUE THREAD

**Issue by Ashraf-Hassan** [falcosecurity/falco#565]
- fluentd version: v.2.3.2
- Environment information:
	- Operating system: `cat /etc/os-release` Centos7
	- Kernel version: `uname -r` : 3.10.0-957.5.1.el7.x86_64
- Your configuration:
I have a Kubernetes cluster on 3 masters, 2 infra nodes and 4 workers.
- Your problem explanation. If you have an error logs, write it together
I installed rge elasticsearch using the following helm command:

`helm install --name elasticsearch incubator/elasticsearch -f elsaticsearch-values.yaml --namespace monitoring-logging`
 
 where the config file has the info about the nodeselector and the persistent storage.
The I installed fluentd using the command : 

 `helm install --name fleuntd stable/fluentd-elasticsearch --namespace=monitoring-logging`

And this setup was working perfectly for days,
Then I installed falco using helm, where all of the sudden the cluster went mad, so I uninstalled flaco, and then fluentd, and the elastic search, then deleted all the pvc and pv, and deleted on every single the node 
the following: 

`rm -rf /var/log/fluentd*`

Then on every single node I ran:

`docker system prune`

But when I install the EFK again still find:
1- Old logstash's there once I reinstall the fluentd.
2- The cluster goes mad again the es-client keep crashing as if the falco is still there, honestly I do not want the falco, so I can I do proper uninstall and get back to the old state?

**Comment by mfdii** [comment]
I don't believe this would be a falco problem given the that you say that this behavior repeated itself once you removed Falco. 

You didn't mention how you uninstalled falco, I assume you used `helm delete --purge falco`. 

Also, you've mentioned having logstash and fluentd in this environment. You should probably only use one of these as they perform similar functions.

**Comment by Ashraf-Hassan** [comment]
I am using now fluent-bit and it solved the problem, but I do not believe that the falco can integrate with the fluent-bit correct?

**Comment by mfdii** [comment]
Fluent bit should work, you might need to update the templates provided for kubernetes logs but logging to a file and fluent-bit picking it up should work.
