### ISSUE TITLE
Change stats file writer to not use setitimer()

### ISSUE THREAD

**Issue by mstemm** [falcosecurity/falco#574]
Currently the stats file writer uses setitimer() to set up the periodic timer that controls when to write stats to the configured file. Given that sinsp::next() is called for every system call, we could use that as a more reliable clock source and avoid the overhead of the signal delivery + signal handler.

**Comment by mstemm** [comment]
no, still want to do this.

**Comment by mstemm** [comment]
We should keep this on the roadmap.

**Comment by leodido** [comment]
Keep

**Comment by leodido** [comment]
This is more important than it seems. And we need this mechanism also for PR #758. Keep on roadmap.
