### ISSUE TITLE
Multiple webhook server

### ISSUE THREAD

**Issue by prasenforu** [falcosecurity/falco#576]
In webhook-config.yaml file falco using own embeded webserver in server section.

How I can use additional server address in webhook-config.yaml file

Please edit subject as "Multiple webhook server"

**Comment by mfdii** [comment]
I tried to do some research on this and couldn't find a solution. The webhook-config.yaml is just a kubeconfig file, so I'd suggest just trying to add a new entry. Or you can try the new Audit Sink feature of kubenetes 1.13.

Closing this because it's a Kubernetes issue, not a Falco one.
