### ISSUE TITLE
falco is terminated abnormally in GKE.

### ISSUE THREAD

**Issue by Kairi** [falcosecurity/falco#583]
Hi, I am verifying falco in GKE environment.

There are times when falco is terminated with following message.
```
Runtime error: Socket handler (k8s_deployment_handler_event) an error occurred while connecting to https://kubernetes.default: Connection timed out. Exiting.
```

I think that GKE's master node may not be responsive to scaling or upgrading by Google.
Is it difficult to create code that assumes that the master node will not respond?

**Comment by mfdii** [comment]
What deployment method are you using, DaemonSet or Helm chart? 

We recently changed the [daemonSet](https://github.com/falcosecurity/falco/blob/dev/integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap.yaml#L28) to use the environment variable for the kubernetes master, but it looks like the Helm chart didn't get this change.

**Comment by Kairi** [comment]
I am using Helm chart.
I'll try changing args!

**Comment by Kairi** [comment]
It seems that I fixed it when I took in the update.
Thanks!
