### ISSUE TITLE
aws-cni emits excessive logs

### ISSUE THREAD

**Issue by whiskeyjimbo** [falcosecurity/falco#588]
aws-cni for eks hits rule `Change thread namespace - an attempt to change a program/thread\'s namespace (commonly done as a part of creating a container) by calling setns.` quite a bit causing an excessive amount of log messages.

Simple solution would be to add `aws-cni` to: https://github.com/falcosecurity/falco/blob/0e1c436d14fb468dd1530115ed19e43faa0a8331/rules/falco_rules.yaml#L1429 is that the correct solution though? or one could continue with an override.

**Comment by mfdii** [comment]
Yes, adding `aws-cni` there would be the correct solution to reduce the FPs. Would you be able to submit a PR, else we can get it into the next round of rule updates?

**Comment by mstemm** [comment]
Can you include a full alert example? I'd like to see the context include cmdline, etc.

**Comment by fntlnz** [comment]
@whiskeyjimbo can you provide more info on this?

**Comment by leodido** [comment]
Closing this since missing info. Comment (and we'll re-open) in case there are details about this.
