### ISSUE TITLE
Kubernetes: Node name/hostname and Kubernetes cluster name

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falco#596]
When receiving falco events related to a container there's no easy way to know the node that was hosting the pod or container generating that specific event.

Given that what we can do is to add more context to Falco events by adding the Node name (hostname) and the Kubernetes cluster name to them.

**Comment by prsimoes** [comment]
Is it possible to get the cluster name as well?

**Comment by fntlnz** [comment]
@prsimoes yes it's mentioned in the issue!
