### ISSUE TITLE
Document falco http output

### ISSUE THREAD

**Issue by mstemm** [falcosecurity/falco#601]
In https://github.com/falcosecurity/falco/pull/523 we added the ability to directly send events via http. We should update the falco docs to describe the config options and current limitations of this approach (namely, the fact that it's blocking).

**Comment by mohansd** [comment]
It's a usefull and pretty update. But I found a error with my nodejs programe (develop with express and body-parse). The midleware body-parse.json() can't work with such error:

**Comment by mstemm** [comment]
Can you paste the json that you’re sending to your middleware?

**Comment by mfdii** [comment]
@mohansd also, please make sure `json_output: true` is in your `falco.yaml` config file.

**Comment by mfdii** [comment]
Docs added in falcosecurity/falco-website#18
