### ISSUE TITLE
Docs: Supported fields

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falco#604]
The wiki page for supported fields hadn't been ported to the Falco website.

We need to make clear what are the fields one can use and how to understand when they are available, e.g: if you don't use the `--cri` flag you don't have the container runtime fields.

Wiki page: https://github.com/falcosecurity/falco/wiki/Supported-Fields
URL broken from the wiki page: https://falco.org/docs/rules/supported-fields/

**Comment by mfdii** [comment]
Fixed in falcosecurity/falco-website#18
