### ISSUE TITLE
Guidelines for Contributing Rules

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falco#605]
This issue is an open forum to discuss how this project want to handle upstream rules in order to build a guideline for the following areas:

- What are the quality criteria for a rule;
- How we deal rules for projects with different kind of license, OSS, Closed, everything in the middle;
- How rules are tested and how do we make sure that rules are kept relevant;

The output of the discussions here will be a collaborative document containing the proposed guidelines that will then be reviewed by Falco core contributors and committed back as the `CONTRIBUTING_RULES.md` file in the project root.

Personal note: This is only an introduction from me, I'll add my ideas as soon as I develop them.

**Comment by mstemm** [comment]
I think some good guidelines to follow are:

1. If there is an exception for a process related rule, it should be as specific as possible, including the process name, action, and target.
Most of the exceptions in the write_below_etc macro are good examples of this.

2. For container exceptions, which mostly refer to privileged containers and containers with sensitive mounts, check the docs for the container to see if they mandate running privileged or having the sensitive mount. If they do, allow the exception.

3. Only add exceptions for software that is in public use, and not one-off packages or ones we can’t find publically.

**Comment by leodido** [comment]
An important part of the process is the classification of rules.

An initial classification is between default rules and available but not default rules.

Thus we can set an higher bar for a rule (and its context) to be default.

Then we could also think to other classifications like: scoring and/or ratings.

**Comment by leodido** [comment]
We definitely want to keep this open.

**Comment by leodido** [comment]
Up 🔝
