### ISSUE TITLE
Integration with OPA (Open Policy Agent)

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falco#607]
[OPA](https://www.openpolicyagent.org/) - Open Policy Agent can be used at different levels of the stack and is not intended only for application business logic but also for other levels.

Said that, we want to find ways to integrate OPA with Falco by farming off policy decisions that can then be converted to falco rules.

For example, an OPA policy might be "limit what Kubernetes users can instruct the cluster to use  specific image", Falco can read that policy and put in place the action with a Rule.

**Comment by amuniz** [comment]
I might be wrong, but I think @kris-nova just demoed something like this today at FOSDEM. Is this about a deeper integration?

**Comment by wilf1rst** [comment]
> I might be wrong, but I think @kris-nova just demoed something like this today at FOSDEM. Is this about a deeper integration?

Here's the talk
http://bofh.nikhef.nl/events/FOSDEM/2020/K.1.105/kubernetes.webm
