### ISSUE TITLE
Getting runtime error on latest update

### ISSUE THREAD

**Issue by budbay** [falcosecurity/falco#610]
I am running falco on ubuntu 18.04 installed through apt.  After latest update I am getting the following error when starting falco: "Runtime error: LargestUInt out of Int range. Exiting"  I have tried removing my .local rules and even a fresh install with the same results.  If i downgrade to previous version it starts back up fine.  I have about 21 containers running, managed with docker-compose.  If I bring down all containers I can start falso just fine, but when containers are started it produces the same error again.  Not sure what else I can look for but I will gladly provide any additional details as needed.

```
● falco.service - LSB: Falco syscall activity monitoring agent
   Loaded: loaded (/etc/init.d/falco; generated)
   Active: active (exited) since Wed 2019-05-15 22:22:49 CDT; 2s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 12654 ExecStop=/etc/init.d/falco stop (code=exited, status=0/SUCCESS)
  Process: 13100 ExecStart=/etc/init.d/falco start (code=exited, status=0/SUCCESS)

May 15 22:22:46  falco[13123]: Loading rules from file /etc/falco/falco_rules.yaml:
May 15 22:22:47  falco[13123]: Loading rules from file /etc/falco/falco_rules.local.yaml:
May 15 22:22:47  falco[13100]: Wed May 15 22:22:47 2019: Loading rules from file /etc/falco/falco_rules.local.yaml:
May 15 22:22:47  falco[13123]: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
May 15 22:22:47  falco[13100]: Wed May 15 22:22:47 2019: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
May 15 22:22:48  falco[13123]: Loading rules from file /etc/falco/rules.d/rules-traefik.yaml:
May 15 22:22:48  falco[13100]: Wed May 15 22:22:48 2019: Loading rules from file /etc/falco/rules.d/rules-traefik.yaml:
May 15 22:22:49 falco[13144]: Runtime error: LargestUInt out of Int range. Exiting.

```

**Comment by budbay** [comment]
well after update to 15.1 everything is now working again. whatever bugfixes were present solved the issue for me.

**Comment by fntlnz** [comment]
Hi @budbay  thanks for reporting! Do you still see this?

**Comment by budbay** [comment]
@fntInz not since upgrading to v15.1.  Falco has been up and running like normal on latest version.

**Comment by fntlnz** [comment]
Ok thanks for confirming @budbay
