### ISSUE TITLE
Falco won't load macro containing macro reference

### ISSUE THREAD

**Issue by mstemm** [falcosecurity/falco#614]
If you try to load the following as falco_rules.local.yaml:

```
- macro: sh_writing_resolv_conf
  condition: (proc.name=sh and fd.name=/etc/resolv.conf)

- macro: user_known_write_etc_conditions
  condition: sh_writing_resolv_conf
```

You get this error:
```
$ sudo falco -r /mnt/sf_mstemm/work/src/falco/rules/falco_rules.yaml -r /mnt/sf_mstemm/local_rules.yaml
Mon May 20 21:14:28 2019: Falco initialized with configuration file /etc/falco/falco.yaml
Mon May 20 21:14:28 2019: Loading rules from file /mnt/sf_mstemm/work/src/falco/rules/falco_rules.yaml:
Mon May 20 21:14:28 2019: Loading rules from file /mnt/sf_mstemm/local_rules.yaml:
Mon May 20 21:14:28 2019: Runtime error: Error loading rules: /usr/share/falco/lua/compiler.lua:65: Undefined macro 'sh_writing_resolv_conf' used in filter.. Exiting.
```

However, moving the contents of sh_writing_resolv_conf directly into user_known_write_etc_conditions works:

```
#- macro: sh_writing_resolv_conf
#  condition:

- macro: user_known_write_etc_conditions
  condition: (proc.name=sh and fd.name=/etc/resolv.conf)
```

I think the problem is that the macro user_known_write_etc_conditions is being loaded before sh_writing_resolv_conf has been loaded--rules/macros are generally loaded in the order in which they are found in the files. In this case, the bug is that user_known_write_etc_conditions is being read from its first reference in falco_rules.yaml and not the second reference in falco_rules.local.yaml.

**Comment by Kaizhe** [comment]
I think I figured it out. This might not be an issue.

macro `user_known_write_etc_conditions` has been defined in right before macro `write_below_etc_common`. 

If I put macro ` sh_writing_resolv_conf` before the original macro `user_known_write_etc_conditions`, it worked, if I put it after, the it won't work. I guess falco only load macro once and ignore the duplicated one later on?

**Comment by mstemm** [comment]
Right--I think it's (mistakenly) sensitive to the position of the original macro in the original file, when it should really use the position in the second file.

**Comment by mstemm** [comment]
We should still work on a better fix for this.

**Comment by leodido** [comment]
This seems related to #706 findings (ordering / positioning of macros) imho.

**Comment by leogr** [comment]
keep
