### ISSUE TITLE
Pod Error: CrashLoopBackOff Deployment to K8s with RBAC enabled

### ISSUE THREAD

**Issue by tanvir1990** [falcosecurity/falco#626]
I followed the instructions but the Pod could not run. I was getting CrashLoopBackOff error

**NAME                    READY   STATUS             RESTARTS   AGE**
falco-daemonset-xqmc8   0/1     CrashLoopBackOff   4          2m40s

Here are the logs

```
**@linux:**~/falco/integrations/k8s-using-daemonset$ kubectl logs falco-daemonset-xqmc8
ls: cannot access '/host/usr/src': No such file or directory
* Setting up /usr/src links from host
* Unloading falco-probe, if present
* Running dkms install for falco
Error! echo
Your kernel headers for kernel 4.14.106+ cannot be found at
/lib/modules/4.14.106+/build or /lib/modules/4.14.106+/source.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/0.15.0/build/make.log
* Trying to load a system falco-probe, if present
* Trying to find precompiled falco-probe for 4.14.106+
Found kernel config at /proc/config.gz
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.15.0-x86_64-4.14.106%2B-59782263d3699cdb67e5e115f34d2e12.ko
curl: (22) The requested URL returned error: 404 Not Found
Download failed, consider compiling your own falco-probe and loading it or getting in touch with the sysdig community
Mon May 27 20:43:03 2019: Falco initialized with configuration file /etc/falco/falco.yaml
Mon May 27 20:43:03 2019: Loading rules from file /etc/falco/falco_rules.yaml:
Mon May 27 20:43:03 2019: Loading rules from file /etc/falco/falco_rules.local.yaml:
Mon May 27 20:43:03 2019: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Mon May 27 20:43:04 2019: Unable to load the driver. Exiting.
Mon May 27 20:43:04 2019: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco-probe module is loaded.. Exiting.

```

**Comment by tanvir1990** [comment]
Instructions followed from this link 
https://github.com/falcosecurity/falco/tree/dev/integrations/k8s-using-daemonset

**Comment by tanvir1990** [comment]
So, the error the log file is talking about a Kernel header missing. So I ran the following commands to find out my kernel version and if the header file exists. I am running a Debian version 9 instance on Google Cloud Platform.

**@linux**:~$ uname -r
4.9.0-9-amd64
**@linux**:~$ apt search linux-headers-$(uname -r)
linux-headers-4.9.0-9-amd64/stable,now 4.9.168-1+deb9u2 amd64 [installed,automatic]
  Header files for Linux 4.9.0-9-amd64
**@linux:**~$ ls -l /usr/src/linux-headers-$(uname -r)
total 1268
drwxr-xr-x 3 root root    4096 May 23 18:34 arch
drwxr-xr-x 4 root root    4096 May 23 18:34 include
-rw-r--r-- 1 root root     304 May 13 20:59 Makefile
-rw-r--r-- 1 root root 1282502 May 13 20:59 Module.symvers
lrwxrwxrwx 1 root root      34 May 13 20:59 scripts -> ../../lib/linux-kbuild-4.9/scripts

Now, 
What I am guessing is my kernel version is older than the one is required by Falco, is that correct? Can I just upgrade my kernel version?

**Comment by CuriousUndeadCat** [comment]
Any news on this?
We're having problem deploying it on GKE.
It's trying to [download a file that doesn't exist.](https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.15.0-x86_64-4.14.106%2B-59782263d3699cdb67e5e115f34d2e12.ko)

**Comment by tanvir1990** [comment]
> Any news on this?
> We're having problem deploying it on GKE.
> It's trying to [download a file that doesn't exist.](https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.15.0-x86_64-4.14.106%2B-59782263d3699cdb67e5e115f34d2e12.ko)

I don't have anything from me yet. I am waiting for anyone from Falco to help. :/

**Comment by fntlnz** [comment]
@tanvir1990 Thanks for reporting. 
I'm a bit confused by the outputs you posted here.
It seems that the Kubernetes node where you are trying to run Falco has kernel `4.14.106+` but then you post the kernel headers from the node where you are running the kubectl that is running with kernel `4.9.0-9-amd64`.

Can you confirm that the kernel headers are in the target machine and not just in the machine you are using as a client?

**Comment by tanvir1990** [comment]
@fntlnz Thanks for opening my eyes! :D My target machine (K8s node) had restricted access. Hence, Falco couldn't read the Kernel Headers during the installation process even though the header files were there. Once I changed the access privilege of K8s nodes, everything seems to be working fine. :)

**Comment by fntlnz** [comment]
Oh cool @tanvir1990 glad to have been of help! I'm closing this but feel free to reopen if you feel that something is wrong.

:) 

/close
