### ISSUE TITLE
falco-sns crashing on start

### ISSUE THREAD

**Issue by arminc** [falcosecurity/falco#627]
I am using falco-sns to send alerts to SNS. When I deploy a Falco daemon set on a new fresh EKS cluster (version 1.12), Falco starts properly but falco-sns doesn't. What happens is that I get the following error:

```
Opened pipe /var/run/falco/nats
Scanning /var/run/falco/nats
invalid character 'b' after top-level value
```

But it can be variations like: `invalid character 'o' looking for beginning of value` or `invalid character '/' in exponent of numeric literal`. 

The problem seems to be that the file /var/run/falco/nats indeed contains wrong data like:

```
6a469556704869f41cbe/diff","proc.pcmdline":"dockerd","proc.pname":"dockerd"}}
```

After some time, minutes, the initial data in /var/run/falco/nats is gone and new data comes in which is correct. If I restart/delete the pod then falco-sns works. If I wait longer it seems falco-sns recovers as well.

Eventually, everything works but it does mean that in the first 10 to 20 minutes I am not receiving alerts on what is happening inside the cluster.

EDIT:
It doesn't always recover: 
```
falco-xx-falco-2tfvz   1/2     CrashLoopBackOff   16         60m
falco-xx-falco-4fkbm 1/2     CrashLoopBackOff   16         60m
```

**Comment by iverberk** [comment]
Can anyone of the Falco maintainers comment on this? It makes the alerting basically useless and it seems that this has never worked properly?

**Comment by mfdii** [comment]
@nestorsalceda can you help troubleshoot what is going on?

**Comment by arminc** [comment]
We used the latest falco version (15) and the problem seems to be resolved. I am not 100% sure but the problem might be caused by #560

**Comment by fntlnz** [comment]
Since this seems to be good and no one else reported the issue I'm closing this one.
