### ISSUE TITLE
Provide macro to whitelist "Clear Log Activities" Rule

### ISSUE THREAD

**Issue by natalysheinin** [falcosecurity/falco#632]
https://github.com/falcosecurity/falco/blob/dev/rules/falco_rules.yaml#L2212

The new `Clear Log Activities` rule is alerting a lot of log lines that we expect to be cleared.
There is currently no way to provide an `allowed_clear_log_files` macro that defines logs that you want to whitelist (aside from outright overriding the rule itself) 

## Potential Solution

Re-write local rule as:
```
- rule: Clear Log Activities
  desc: Detect clearing of critical log files
  condition: >
    open_write
    and access_log_files
    and evt.arg.flags contains "O_TRUNC"
    and not allowed_clear_log_files

- macro: allowed_clear_log_files
  condition: >
    # not sure what to put here
```

**Comment by fntlnz** [comment]
@mstemm @Kaizhe wdyt?

**Comment by mstemm** [comment]
That approach looks good. I’ll try to do it this week, if @Kaizhe has time before he can tackle it too.

**Comment by Kaizhe** [comment]
lgtm

**Comment by Kaizhe** [comment]
-
