### ISSUE TITLE
Unable to install falco on CentOS 7.5 - add fallback mechanism if DKMS fails

### ISSUE THREAD

**Issue by devdua** [falcosecurity/falco#638]
Hi

I am unable to install Falco on CentOS 7.5, here's the output of the script - 

```
* Detecting operating system
* Installing falco public key
* Installing falco repository
* Installing kernel headers
Error: Nothing to do
Unable to find kernel development files for the current kernel version 3.10.0-862.14.4.el7.x86_64
This usually means that your system is not up-to-date or you installed a custom kernel version.
The installation will continue but you'll need to install these yourself in order to use falco.
Please write to the mailing list at https://groups.google.com/forum/#!forum/sysdig
if you need further assistance.
* Installing falco
Warning: RPMDB altered outside of yum.

Creating symlink /var/lib/dkms/falco/0.15.0/source ->
                 /usr/src/falco-0.15.0

DKMS: add completed.

Module build for the currently running kernel was skipped since the
kernel source for this kernel does not seem to be installed. 
```

**Comment by devdua** [comment]
According to the installation doc, the script should fallback to downloading kernel modules from s3 if DKMS fails - 

![image](https://user-images.githubusercontent.com/3139249/58869210-6f03f180-86db-11e9-988f-adbe7af18280.png)

However the current script has no such functionality. The pre-built kernel module does exist for the kernel I have on the machine.

```2019-05-14 02:00:54     677392 falco-probe-0.15.0-x86_64-3.10.0-862.14.4.el7.x86_64-1795864c4b1e0fcf3350aec1a299aabe.ko```

@lssif helped me on falco's Slack and sent me the link to download the .ko file above. He suggested to use ```insmod``` to insert this kernel module and then run falco. falco runs after this.

![image](https://user-images.githubusercontent.com/3139249/58869547-197c1480-86dc-11e9-8f60-aab6e0fdd491.png)


But if the server is restarted, the kernel object gets unloaded.

I would request that the script be modified to add the fallback mechanism as well as a persistence method for the kernel module.

**Comment by fntlnz** [comment]
Hi @devdua - do you have the kernel headers package in your machine?

```
yum install kernel-headers
```

**Comment by devdua** [comment]
> Hi @devdua - do you have the kernel headers package in your machine?
> 
> ```
> yum install kernel-headers
> ```

Hi @fntlnz when I am attempting to install both ```kernel-headers``` and ```kernel-devel``` packages, they're getting installed for kernel ```3.10.0-957.12.2.el7.x86_64```. However, ```uname -r``` shows the kernel to be ```3.10.0-862.14.4.el7.x86_64``` which is not supported any more and all packages pertaining to this kernel version have been taken down from the official repo.

As in my last comment, if I use the pre-built probe from S3 for kernel ```3.10.0-862.14.4.el7.x86_64```, falco works. I believe the script should have resorted to the fallback and downloaded the pre build probe from S3?

**Comment by devdua** [comment]
Hi team, will this be addressed in an upcoming release?

**Comment by devdua** [comment]
@fntlnz RUNBPF

**Comment by fntlnz** [comment]
Hi @devdua , we definitely want to sort this out, I'm adding this as a discussion point for the next Repo planning to see what others think about this.


```
RUNBPF contest

Send me an email `lo at linux.com` with your full name and address for the sticker! (I also accept encrypted emails if you have privacy concerns. You can get my public key here https://fntlnz.wtf/downloads/pubkey-0xD624DE73B2400EE4.asc)
```

**Comment by fntlnz** [comment]
In the meanwhile @devdua can you please fill the issue template for us? Would make easier for contributors to get this.

**Comment by devdua** [comment]
> In the meanwhile @devdua can you please fill the issue template for us? Would make easier for contributors to get this.


name | about | labels
-- | -- | --
Bug Report | Falco does not pull pre-built kernel module from S3 if DKMS fails. | kind/bug

**What happened:** I am unable to install Falco on CentOS 7.5, as the kernel is outdated (out of my control). The kernel headers and dev packages are no longer supported and because of that the kernel probe is not being built by Falco.

**What you expected to happen:** Falco should have downloaded the pre build probe from S3 as mentioned in the documentation.

**How to reproduce it (as minimally and precisely as possible):** Try to install Falco on a system without the packages required to build the module. Falco does not automatically download the pre-built probe.

**Anything else we need to know?:** N.A.

**Environment:** 

**Falco version (use falco --version):** 0.15.3
**OS (e.g: cat /etc/os-release):** CentOS 7.5
**Kernel (e.g. uname -a):** 3.10.0-862.14.4.el7.x86_64
**Install tools (e.g. in kubernetes, rpm, deb, from source):** rpm

**Comment by fntlnz** [comment]
I debugged this and other similar issues, I think here is happening the same thing as commented here: https://github.com/falcosecurity/falco/issues/846#issuecomment-532606189

**Comment by fntlnz** [comment]
Hi @devdua can you test this with 0.17.1 ?

**Comment by devdua** [comment]
Hi @fntlnz I am afraid the same problem persists, the installer does not download the pre-built module.

![image](https://user-images.githubusercontent.com/3139249/65738847-f2b97200-e100-11e9-8267-b553e4af8362.png)

**Comment by fntlnz** [comment]
@devdua I see that we have the pre-built kernel module for your kernel in the s3 bucket.

https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.17.1-x86_64-3.10.0-862.14.4.el7.x86_64-1795864c4b1e0fcf3350aec1a299aabe.ko

Can you try dowloading it and installing it manually? I'm not sure that Falco is the problem here, I've seen this kind of things happening when there was a difference between the installed kernel headers and running kernel in the past.

**Comment by devdua** [comment]
@fntlnz as mentioned earlier, that works. I have tried it with the probe that you have sent the link to and it's working.

![image](https://user-images.githubusercontent.com/3139249/65869317-d71bc900-e397-11e9-9597-6153eb03414d.png)

**Comment by fntlnz** [comment]
Ok, I don't think I know how to help out then. If your distribution doesn't ship the headers anymore for the kernel you are running at.

Did you try to checkout the centos archives?

I think what you are looking for is here: https://people.centos.org/arrfab/shim/results/kernel/20180926150836/3.10.0-862.14.4.el7.x86_64/

**Comment by devdua** [comment]
> According to the installation doc, the script should fallback to downloading kernel modules from s3 if DKMS fails -
> 
> ![image](https://user-images.githubusercontent.com/3139249/58869210-6f03f180-86db-11e9-988f-adbe7af18280.png)
> 
> However the current script has no such functionality. The pre-built kernel module does exist for the kernel I have on the machine.
> 
> `2019-05-14 02:00:54 677392 falco-probe-0.15.0-x86_64-3.10.0-862.14.4.el7.x86_64-1795864c4b1e0fcf3350aec1a299aabe.ko`
> 
> @[issif](https://github.com/issif) helped me on falco's Slack and sent me the link to download the .ko file above. He suggested to use `insmod` to insert this kernel module and then run falco. falco runs after this.
> 
> ![image](https://user-images.githubusercontent.com/3139249/58869547-197c1480-86dc-11e9-8f60-aab6e0fdd491.png)
> 
> But if the server is restarted, the kernel object gets unloaded.
> 
> I would request that the script be modified to add the fallback mechanism as well as a persistence method for the kernel module.

@fntlnz I do understand that it's a difficult thing to support. I wanted to know why the installer behavior is inconsistent with the documentation.. is there a way for the pre-built probes to be fetched in cases like this, since they're already available?

**Comment by fntlnz** [comment]
Pre-built kernel modules are the default when installing Falco using a container, we have a script that fetches them and lazy laod them when yous tart the container. 
For rhel and debian packages we use dkms so if your distro fails to provide the headers for your actual setup you can install them yourself and then install falco.

I'm not sure where you found that documentation page but it seems wrong to me.

**Comment by devdua** [comment]
@fntlnz thanks for clearing this out, I will have to rethink the deployment strategy. Appreciate your help on this. The paragraph was from the installation doc - https://falco.org/docs/installation/

But it seems to have been removed now. However the content was the same thing as here - https://github.com/falcosecurity/falco/wiki/Install-Falco-(Minikube)
