### ISSUE TITLE
Falco service "active (exited)" on Ubuntu 16.04 (systemd)

### ISSUE THREAD

**Issue by JPLachance** [falcosecurity/falco#640]
Hello!

I am currently running Falco 0.14.0 on production instances and I noticed Falco stopped running on multiple Ubuntu 16.04 hosts.

```
root@some-host:/var/run# service falco status
● falco.service - LSB: Falco syscall activity monitoring agent
   Loaded: loaded (/etc/init.d/falco; bad; vendor preset: enabled)
   Active: active (exited) since Mon 2019-05-27 05:58:49 UTC; 4 days ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 0
   Memory: 0B
      CPU: 0
```

After discussing with @fntlnz, the issue is most likely caused by the lack of systemd Unit definition and [systemd doesn't know what he needs to do](https://unix.stackexchange.com/questions/241970/what-does-status-active-exited-mean-for-a-systemd-service).

Issue #484 related to this one but in my case, Falco stopping and not restarting looks more like a bug. 🙂 

Thanks for the help!

**Comment by JPLachance** [comment]
Hello again!

The current systemd falco.service file (/run/systemd/generator.late/falco.service) content is:
```
# Automatically generated by systemd-sysv-generator

[Unit]
Documentation=man:systemd-sysv-generator(8)
SourcePath=/etc/init.d/falco
Description=LSB: Falco syscall activity monitoring agent
Before=multi-user.target
Before=multi-user.target
Before=multi-user.target
Before=graphical.target
Before=shutdown.target
After=remote-fs.target
After=systemd-journald-dev-log.socket
Conflicts=shutdown.target

[Service]
Type=forking
Restart=no
TimeoutSec=5min
IgnoreSIGPIPE=no
KillMode=process
GuessMainPID=no
RemainAfterExit=yes
ExecStart=/etc/init.d/falco start
ExecStop=/etc/init.d/falco stop
```

The one suggested by @juju4 is:
```
[Unit]
Description=Falco: Container Native Runtime Security

[Service]
Type=simple
User=root
ExecStart=/usr/bin/falco --pidfile=/var/run/falco.pid
UMask=0077
TimeoutSec=30
RestartSec=15s
#Restart=always
Restart=on-failure
PrivateTmp=true
NoNewPrivileges=yes
PrivateTmp=true
ProtectHome=read-only
ProtectSystem=full
ProtectKernelTunables=true
RestrictRealtime=true
#RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
RestrictAddressFamilies=~AF_PACKET
SystemCallFilter=~@debug @mount @cpu-emulation @obsolete @privileged
# FIXME!
#   PANIC: unprotected error in call to Lua API (runtime code generation failed, restricted kernel?)
#   ?https://www.freelists.org/post/luajit/luajit-crashes-with-grsec-kernel,1
#MemoryDenyWriteExecute=true
#PrivateMounts=true

[Install]
WantedBy=multi-user.target
```

The `Type` change (from `Type=forking` to `Type=simple`) and the `Restart=on-failure` should help!

**Comment by fntlnz** [comment]
@JPLachance that seems like a good idea, would you like to contribute that change? Let me know otherwise I'll do it.

**Comment by JPLachance** [comment]
Unfortunately, I'm totally clueless about how we build, package and publish a DEB package 🙂 I could try something, but it won't be in the next few days. Can you handle it? I'll be happy to test it!

**Comment by fntlnz** [comment]
@mstemm to do this we just edit the files in the scripts folder? I see those there but I don’t understand where the actual build is done and when.

**Comment by mstemm** [comment]
We don't currently include a systemd unit file, so we'd have to figure out where it should be within the binary packages to get installed properly.

**Comment by mfdii** [comment]
Discussed on office hours. We will start shipping the systemd unit file.

**Comment by mstemm** [comment]
We should keep this on the roadmap.

**Comment by JPLachance** [comment]
That bot is a little bit annoying 😄

**Comment by leodido** [comment]
I planned to create a smarter one (with prow) time ago (see
https://github.com/falcosecurity/test-infra/issues/40) ..

I just need some spare time! :) Or maybe someone implementing and
contributing it (I can give directions about it) :)
L.

**Comment by JPLachance** [comment]
Again, we should keep this on the roadmap :)

**Comment by JPLachance** [comment]
This issue was not fixed. We should address it...

**Comment by JPLachance** [comment]
Hello @mfdii,

Did we progress on this issue? Or is it just that bot again? :) 

Thanks!

**Comment by leogr** [comment]
Hey @JPLachance 

re-opening this as discussed

**Comment by leogr** [comment]
Link here as ref https://github.com/falcosecurity/falco/pull/1448
