### ISSUE TITLE
Failure to build Falco with builder

### ISSUE THREAD

**Issue by dom-lgtm** [falcosecurity/falco#660]
**What happened**:

Building Falco with the instructions provided on the website fails with the following error:

```make[3]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
make[3]: *** No rule to make target `/build/Release/grpc-prefix/src/grpc/objs/opt/third_party/zlib/adler32.o', needed by `/build/Release/grpc-prefix/src/grpc/libs/opt/libz.a'.  Stop.
make[2]: *** [grpc-prefix/src/grpc-stamp/grpc-build] Error 2
make[1]: *** [CMakeFiles/grpc.dir/all] Error 2
make: *** [all] Error 2```

[log_falco_package.txt](https://github.com/falcosecurity/falco/files/3277396/log_falco_package.txt)

**What you expected to happen**:

Falco builds successfully.

**How to reproduce it (as minimally and precisely as possible)**:

``` 
docker build -t myfalcobuilder .
 FALCO_VERSION=0.1.2-test docker run --user $(id -u):$(id -g) -v /etc/passwd:/etc/passwd:ro -e MAKE_JOBS=4 -e FALCO_VERSION=${FALCO_VERSION} -it -v /Users/dom/Dev/repos:/source -v /Users/dom/Dev/falco/:/build myfalcobuilder cmake
 FALCO_VERSION=0.1.2-test docker run --user $(id -u):$(id -g) -v /etc/passwd:/etc/passwd:ro -e MAKE_JOBS=4 -e FALCO_VERSION=${FALCO_VERSION} -it -v /Users/dom/Dev/repos:/source -v /Users/dom/Dev/falco/:/build myfalcobuilder package
```

**Anything else we need to know?**:

Falco and sysdig repos on dev branch and pulled right before running the above commands.

**Environment**:
- Others: OSX Mojave, Docker Desktop 2.0.0.3

**Comment by leodido** [comment]
The line `No rule to make target /build/Release/grpc-prefix/src/grpc/objs/opt/third_party/zlib/adler32.o, needed by /build/Release/grpc-prefix/src/grpc/libs/opt/libz.a. Stop.` suggests a missing/wrong dependency (`zlib`).

@mstemm PTAL

**Comment by mstemm** [comment]
Did you try with the falco-builder image we distribute? https://cloud.docker.com/u/falcosecurity/repository/docker/falcosecurity/falco-builder

**Comment by dom-lgtm** [comment]
Yes, this was my first try before I rebuilt the builder.

**Comment by dom-lgtm** [comment]
I can confirm I don't get the same error on a linux (Debian) docker install.

However I get another error at the end:

```
[100%] Built target falco
Run CPack packaging tool...
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: falco
CPack: - Install project: falco
CPack: Create package
CMake Error at /build/cmake/Modules/CPackDeb.cmake:472 (message):
  CPackDeb: Debian package requires a package version
Call Stack (most recent call first):
  /build/cmake/Modules/CPackDeb.cmake:650 (cpack_deb_prepare_package_vars)


CPack Error: Error while execution CPackDeb.cmake
CPack Error: Problem compressing the directory
CPack Error: Error when generating package: falco
make: *** [package] Error 1
```

I used the same commands as above.

**Comment by mstemm** [comment]
What was your complete command line? You need to resolve ${FALCO_VERSION} with whatever version you'd like to use for the build.

**Comment by dom-lgtm** [comment]
As mentioned in my comment, it's above:

``` 
FALCO_VERSION=0.1.2-test docker run --user $(id -u):$(id -g) -v /etc/passwd:/etc/passwd:ro -e MAKE_JOBS=4 -e FALCO_VERSION=${FALCO_VERSION} -it -v /Users/dom/Dev/repos:/source -v /Users/dom/Dev/falco/:/build myfalcobuilder cmake
 FALCO_VERSION=0.1.2-test docker run --user $(id -u):$(id -g) -v /etc/passwd:/etc/passwd:ro -e MAKE_JOBS=4 -e FALCO_VERSION=${FALCO_VERSION} -it -v /Users/dom/Dev/repos:/source -v /Users/dom/Dev/falco/:/build myfalcobuilder package
```

**Comment by mstemm** [comment]
What happens if you put the version directly e.g. -e FALCO_VERSION=0.1.2-test? Maybe the environment variable isn’t being passed properly

**Comment by dom-lgtm** [comment]
I think I did and it didn't work either, but I'm not sure so I will test again tomorrow and get back to you.
