### ISSUE TITLE
Documentation around Rule Operators

### ISSUE THREAD

**Issue by nebi-frame** [falcosecurity/falco#670]
**What am I asking**:
I'm asking to documentate rule operators and their meaning,
for example what does `icontains` mean and what is the difference between `contains` and `icontains` ?
**Why is this needed**:
Without proper understanding of operators, it's hard to write rules.

**Comment by hexsel** [comment]
can we reopen this? I am also struggling to find any documentation about the operators allowed on falco rules.  Also, anything related to built-in values like null (I have some weird case where proc name is null).

**Comment by holyspectral** [comment]
For those who found this issue from google, `icontains` is a case-insensitive `contains`.
