### ISSUE TITLE
Falco doesn't seem to populate some fields when using OpenShift 4.0 / CRI-O containers

### ISSUE THREAD

**Issue by mateobur** [falcosecurity/falco#672]
**What happened**: Using Falco over OpenShift4 with CRI-O containers, the falco runtime rule fired correctly but there were some missing parameters in the output.

**What you expected to happen**: Having the falco filters `container.image` and `container.image.repository` correctly populated in this environment.

**How to reproduce it (as minimally and precisely as possible)**:

The rule I used was this one

```

- list: nginx_allowed_file_prefixes_readwrite
  items: ["/var/log/nginx", "/var/run"]
# Remember to add your nginx cache path


- rule: Unexpected file access readwrite for nginx
        desc: Detect an attempt to access a file readwrite other than below an expected list of directories
        condition: (open_write) and not fd.name pmatch (nginx_allowed_file_prefixes_readwrite) and app_nginx
        output: Unexpected file accessed readwrite for nginx (command=%proc.cmdline pid=%proc.pid file=%fd.name %container.info image=%container.image repository=%container.image.repository)
        priority: NOTICE
```

You can fire it just doing `touch /foo` inside the container

The result was

`20:25:54.629547534: Notice Unexpected file accessed readwrite for nginx (command=bash pid=91601 file=/dev/tty k8s.ns=falco-operator k8s.pod=nginx-5c7588df-42d8g container=a7c1ca7791ea image=<NA> repository=<NA>)
`

Notice the "`<NA>`" fields.

**Anything else we need to know?**:

**Environment**:
- Falco version (use `falco --version`): falco version 0.15.0

- System info 
- Cloud provider or hardware configuration: AWS instances
- OS (e.g: `cat /etc/os-release`): CoreOS / OpenShift
- Kernel (e.g. `uname -a`): 4.18.0-80.el8.x86_64
- Install tools (e.g. in kubernetes, rpm, deb, from source): Falco operator in OpenShift 4.0
- Others:

**Comment by leodido** [comment]
Hey @mateobur can you please give us information about the CNI plugin in use? Is it `multus`?

**Comment by Kaizhe** [comment]
what is the `CRI`? is it `CRI-O` or `Docker`, and also please check the mounting directories of falco. I suspect if it `CRI-O`, you need to configure falco to mount to the right place before reading the image metadata.

**Comment by Kaizhe** [comment]
Please check whether `/var/run/crio/crio.sock` is mounted

**Comment by leodido** [comment]
Anybody has updates on this?
L.
