### ISSUE TITLE
Exception for fluentd in 'Clear Log Activities' rule

### ISSUE THREAD

**Issue by nuala33** [falcosecurity/falco#684]
Hi there,

My logs are flooded with false positives for the 'Clear Log Activities' rule from what I believe to be expected fluentd behavior. Example:

```
23:21:58.690267392: Warning Log files were tampered (user=root command=pos_writer.rb:* -Eascii-8bit:ascii-8bit /usr/sbin/google-fluentd --under-supervisor file=/var/log/gcp-journald-kubelet.pos container_id=2b3bcfdfaf75 image=gcr.io/stackdriver-agents/stackdriver-logging-agent) k8s.ns=kube-system k8s.pod=fluentd-gcp-v3.2.0-j2rsq container=2b3bcjbjaf75 k8s.ns=kube-system k8s.pod=fluentd-gcp-v3.2.0-j2rsq container=2b3bcjbjaf75
```

I saw this recent commit which I think is meant to address a similar issue: https://github.com/falcosecurity/falco/commit/cfaa52f522e1368b4c05ca436a35d0bee8c6bc16, but I pulled all the latest code and re-created my deployment and am still seeing these false positives in the logs.

**What would you like to be added**:
An exception for fluentd (maybe it needs to be specified in the k8s.pod field instead of the container or image fields)?

**Why is this needed**:
Fluentd is not doing anything malicious and shouldn't be triggering this rule. Thanks for your help.

**Comment by nuala33** [comment]
nvm, found the part where i need to add input to the macro :)

**Comment by leodido** [comment]
Glad to hear that you figured out yourself. 

Could you please report your solution here for future reference?

It can be useful to other people too 😃

**Comment by nuala33** [comment]
Absolutely! I corrected the issue by changing `condition: (never_true)` to a condition that would match the false positive loglines I was seeing for the rule 'Clear Log Activities' like so:

```
- macro: allowed_clear_log_files
  condition: (k8s.pod.name startswith fluentd)
```

Then I recreated the configmap and the daemonset and the false positives stopped coming in.

**Comment by metalsong** [comment]
Hi @nuala33, Happy to hear that you've overcomes it! 
Could you please describe a little bit more your solution?
I've added such macro, but wondering which rules should I update and how - in order to get rid off false positives.

Thank you in advance!
