### ISSUE TITLE
Error opening device on /host/dev/falco0

### ISSUE THREAD

**Issue by UsamaMehboob** [falcosecurity/falco#690]
**What happened**: 
```
kubectl logs falco-hmk8n
* Setting up /usr/src links from host
ls: cannot access '/host/usr/src': No such file or directory
* Unloading falco-probe, if present
* Running dkms install for falco
Error! echo
Your kernel headers for kernel 4.9.125-linuxkit cannot be found at
/lib/modules/4.9.125-linuxkit/build or /lib/modules/4.9.125-linuxkit/source.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/0.15.3/build/make.log
* Trying to load a system falco-probe, if present
* Trying to find precompiled falco-probe for 4.9.125-linuxkit
Found kernel config at /proc/config.gz
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.15.3-x86_64-4.9.125-linuxkit-598c2d809165b47f38383b83b6ff4798.ko
curl: (22) The requested URL returned error: 404 Not Found
Download failed, consider compiling your own falco-probe and loading it or getting in touch with the sysdig community
2019-06-25T12:51:34+0000: Falco initialized with configuration file /etc/falco/falco.yaml
2019-06-25T12:51:34+0000: Loading rules from file /etc/falco/falco_rules.yaml:
2019-06-25T12:51:35+0000: Loading rules from file /etc/falco/falco_rules.local.yaml:
2019-06-25T12:51:35+0000: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
2019-06-25T12:51:35+0000: Unable to load the driver. Exiting.
2019-06-25T12:51:35+0000: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco-probe module is loaded.. Exiting.
```

**What you expected to happen**: falco pod should not go into `error`

**How to reproduce it (as minimally and precisely as possible)**:
I installed daemonsets without rbac on mac os mojave.
` sudo kubectl create -f falco-daemonset.yaml`
**Anything else we need to know?**:

**Environment**:
- Falco version (use `falco --version`): I cloned `dev` branch and this is the image in 
daemonsets `falcosecurity/falco:latest`
- System info 
- Cloud provider or hardware configuration: mac book pro
- OS (e.g: `cat /etc/os-release`): mac os mojave
- Kernel (e.g. `uname -a`): Darwin usamas-mbp.lan 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
- Install tools (e.g. in kubernetes, rpm, deb, from source): I am running minikube on macbook pro
- Others: I tried to run this on aws ec2 ubuntu 18.04 and it worked but not here on my machine. i think its probably kernel error. can someone give some pointer?

**Comment by fntlnz** [comment]
Hi @UsamaMehboob - multiple users reported the same problem you have, it is related to the fact that docker for mac is using linuxkit and you don't have kernel headers in it.

There is a way to load it described in this comment: https://github.com/falcosecurity/falco/issues/657#issuecomment-506303851

We are discussing on whether to include that in the installation procedure or docs.

I'm closing this as a duplicate but feel free to reopen in case you think that is not.

/triage duplicate
