### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by leodido** [falcosecurity/falco#691]
**What would you like to be added**:

Unit tests.

- [ ] #854 

**Why is this needed**:

Do I really need to explain why?

**Comment by leodido** [comment]
Reopening this because we still want this.

Also we need a better stale bot (I should have one almost complete implemented with Prow jobs - https://github.com/falcosecurity/test-infra/issues/40).

**Comment by fntlnz** [comment]
No no no stalebot! We need this

**Comment by leogr** [comment]
keep, pls
