### ISSUE TITLE
Opening any connection causes falco to abort when built in debug mode

### ISSUE THREAD

**Issue by leodido** [falcosecurity/falco#693]
**What happened**:

Assuming a falco build with `CMAKE_BUILD_TYPE=Debug`, opening any connection causes the sinsp parser to abort the process.

**What you expected to happen**:

Falco to behave normally.

**How to reproduce it (as minimally and precisely as possible)**:

Build a debug version of Falco.

```bash
mkdir -p build && cd build
cmake -DCMAKE_BUILD_TYPE=Debug ..
make
```

Execute it and then open any connection, eg.:

```
curl localhost:8765
```

**Anything else we need to know?**:

Me and @fntlnz already investigated a bit: the cause is the assertion at sinsp [`parser:2550`](https://github.com/draios/sysdig/blob/d9fa2dd3b7fa901feedc315f9fe3e451c0fab09d/userspace/libsinsp/parsers.cpp#L2550).

**Environment**:
- Falco version (use `falco --version`):

v0.15.3

- OS (e.g: `cat /etc/os-release`):

```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

- Kernel (e.g. `uname -a`):

```
Linux l13o1 5.1.4-arch1-1-ARCH #1 SMP PREEMPT Wed May 22 08:06:56 UTC 2019 x86_64 GNU/Linux
```

- Install tools (e.g. in kubernetes, rpm, deb, from source):

From source.

**Comment by leodido** [comment]
We still want to fix this.

**Comment by fntlnz** [comment]
Still want this!
