### ISSUE TITLE
[UMBRELLA] Reach adequacy of automated testing

### ISSUE THREAD

**Issue by leodido** [falcosecurity/falco#704]
**What would you like to be added**:

- Unit tests (UMBRELLA: #691)
- Review of currently existing integration tests (#854, ..)
- Acceptance tests
- Code coverage (establishing a min threshold for acceptance)
- Reproducible framework able to check the performance gains (establishing a min threshold for acceptance)
- Automatically check and enforce that changes follow the coding guidelines

**Why is this needed**:

To improve and ensure a good code quality of the project we need to perform the steps listed above.

**Comment by leodido** [comment]
We still want this.

**Comment by leodido** [comment]
@kris-nova's additions about this matter are at https://github.com/falcosecurity/falco/issues/819

**Comment by fntlnz** [comment]
Why why stalebot ! Let’s keep this

**Comment by leogr** [comment]
keep keep keep

**Comment by fntlnz** [comment]
/label roadmap
adding the roadmap label so that stalebot doesn't deal with this

**Comment by leogr** [comment]
/remove-lifecycle stale

cc @LucaGuerra :eyes:

**Comment by leogr** [comment]
/assign @jasondellaluce 
(I know you are working on this)
