### ISSUE TITLE
Extend filterchecks to use container labels with k8s metadata in falco rules

### ISSUE THREAD

**Issue by KnoxAnderson** [falcosecurity/falco#720]
**What would you like to be added**:

Selectively apply secure policies for the falco rule Launch Privileged Container to specific parts of a k8s environment. They want the image to be privileged, but only want it to be run in specific namespaces, etc. 

To fix this, we'll have to modify the oss sysdig code to add filtercheck fields to access container labels, perhaps with some processing to make things like the k8s namespace more readily available.

**Why is this needed**:

To better provide kubernetes context that can be used on falco rules before metadata from the K8s API service is available.

**Comment by Issif** [comment]
Falco rules can use same filter than Sysig, so we can already filter by labels :

```
k8s.pod.label   Kubernetes pod label. E.g. 'k8s.pod.label.foo'.
k8s.pod.labels  Kubernetes pod comma-separated key/value labels. E.g. 'foo1:bar
k8s.rc.label    Kubernetes replication controller label. E.g. 'k8s.rc.label.foo
k8s.rc.labels   Kubernetes replication controller comma-separated key/value lab
k8s.svc.label   Kubernetes service label. E.g. 'k8s.svc.label.foo' (can return
k8s.svc.labels  Kubernetes service comma-separated key/value labels. E.g. 'foo1
k8s.ns.label    Kubernetes namespace label. E.g. 'k8s.ns.label.foo'.
k8s.ns.labels   Kubernetes namespace comma-separated key/value labels. E.g. 'fo
k8s.rs.label    Kubernetes replica set label. E.g. 'k8s.rs.label.foo'.
k8s.rs.labels   Kubernetes replica set comma-separated key/value labels. E.g. '
k8s.deployment.label
                Kubernetes deployment label. E.g. 'k8s.rs.label.foo'.
k8s.deployment.labels
                Kubernetes deployment comma-separated key/value labels. E.g. 'f
```

I agree this is not already set up in default rules but you can easily use them.

**Comment by fntlnz** [comment]
Stalebot we still want this !
