### ISSUE TITLE
cmake -DSYSDIG_DIR should resolve "~"

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falco#724]
Currently this command does not work:

```console
[nova@nova build]$ cmake -DSYSDIG_DIR=~/go/src/github.com/draios/sysdig ..
```

But this one does

```console
[nova@nova build]$ cmake -DSYSDIG_DIR=$HOME/go/src/github.com/draios/sysdig ..
```

**Comment by leodido** [comment]
AFAIK there is no reliable way to process tilde in CMake while making all of the others cases work at the same time (an user can provide absolute paths, symlinks, relative paths, home directory containing spaces, ... different platforms etc.).

The point is that tilde expansion is a shell feature. Which is interpreted differently on different shells (eg., csh).

BTW, I'll investigate further whether there is an elegant way to support this in CMake.
I'm also wondering, in that case, what we should do with the various combinations of tilde (not present on all the shells).
Namely,
```
~              $HOME
~nova          (nova home dir)

~+             $PWD   (same effect as ./)
~-             $OLDPWD (your previous directory)
~1             `dirs +1`
~2             `dirs +2`
~-1            `dirs -1`
```

**Comment by kris-nova** [comment]
I mean we need to have a discussion about the build in general - so maybe we can just track this and use it as a use case to refactor the build some ;)
