### ISSUE TITLE
Use deployment instead of daemonset for k8s audit

### ISSUE THREAD

**Issue by benjaminhuo** [falcosecurity/falco#725]
**What would you like to be added**:
Use deployment instead of daemonset for k8s audit

**Why is this needed**:
Daemonset is more than enough for just monitoring k8s audit event, a deployment should be enough. 
Just wondering if it's possible to use deployment for k8s audit event monitoring with falco?

**Comment by fntlnz** [comment]
@benjaminhuo  You are totally right, for those that only wants to use audit events using a deployment only is enough.

It will require:
- A specific yaml file for the deployment
- Make clear in the docs that for those that only want the audit they should use that one
- Make clear in the docs to only load rules for audit events since syscalls will be from the current machine only.


This would also open the point of whether we should make the syscall collection optional.

**Comment by benjaminhuo** [comment]
I'll see I can help on this

**Comment by leodido** [comment]
At the moment we **cannot** remove `/host` since Falco needs the module by default.

Infact we are in the process of providing a flag to disable this behaviour.

**Comment by benjaminhuo** [comment]
A flag will be great to switch between these two features 👍

**Comment by fntlnz** [comment]
Can't wait to see that flag in place,  having only audits is a very common use case many people are reporting.

**Comment by fntlnz** [comment]
This can be done now that #779 is in place !

**Comment by quanvuminh** [comment]
I still got the error with the latest version (0.18.0). I used the same manifest [here](https://github.com/falcosecurity/falco/tree/dev/integrations/k8s-using-deployment)

`# kubectl logs falco-k8s-audit-6f674995f4-ts46w
Fri Nov  8 04:21:01 2019: Falco initialized with configuration file /etc/falco/falco.yaml
Fri Nov  8 04:21:01 2019: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Fri Nov  8 04:21:01 2019: Unable to load the driver. Exiting.
Fri Nov  8 04:21:01 2019: Runtime error: error creating the process list. Make sure you have root credentials.. Exiting.` 

Please help.

**Comment by fntlnz** [comment]
@quanvuminh can you please open an your own issue with this? This particular work had been done and it's easier for us to help you with a specific issue on that.

**Comment by quanvuminh** [comment]
@fntlnz Thanks, I created new issue #936
