### ISSUE TITLE
Falco not able to capture errors related to file operation

### ISSUE THREAD

**Issue by subrnath** [falcosecurity/falco#727]
**What happened**:

I would like to capture the error "chmod 0777 test.txt
chmod: changing permissions of 'test.txt': Operation not permitted"  inside my container.
I have written the condition -
condition: open_write and <container condition> and evt.category=file and fd.type=file and evt.res=EPERM". Same is written for open_read also.

**What you expected to happen**:

Falco to log this event but Falco is not capturing the event.

**How to reproduce it (as minimally and precisely as possible)**: 

**Anything else we need to know?**:

I debugged it by removing the evt.res=EPERM from the condition so that it captures all the file read and file write events and there i am printing all the details of evt. I can see it's not capturing any error and reporting as error is NIL.

 (user=<NA> proc=chmod pid=18902 command=chmod 0777 test.txt file=/lib/x86_64-linux-gnu/libc.so.6 k8s.ns=default k8s.pod=<pod name> container=f7cfa6e35686 image=gcr.io/google_containers/<container>-slim@sha256:8b4501fe0fe221df663c22e16539f399e89594552f400408303c42f3dd8d0e52  evt.failed=false evt.count.error=<NA> and evt.count.error.file=<NA> evt.res=SUCCESS evt.count.error.net=<NA> evt.count.error.memory=<NA> evt.count.error.other=<NA> evt.args=fd=3(<f>/lib/x86_64-linux-gnu/libc.so.6) name=/lib/x86_64-linux-gnu/libc.so.6 flags=4097(O_RDONLY|O_CLOEXEC) mode=0 dev=801  )

Question 1 - why evt.failed=false? Same for the other parameters evt.count.error as well as evt.res? As per the documentation, "https://falco.org/docs/rules/supported-fields/", 
"evt.res         event return value, as a string. If the event failed, the resul
                t is an error code string (e.g. 'ENOENT'), otherwise the result
                 is the string 'SUCCESS'."
But it seems not to be working as expected.

Question 2 - In case of root use, user is reported fine but for the other users than, it's reported as user=<NA>.

**Environment**:
- Falco version (use `falco --version`): 0.15.3
- System info 

"system_info": {
    "machine": "x86_64",
    "nodename": "falco-9wb7b",
    "release": "4.15.0-50-generic",
    "sysname": "Linux",
    "version": "#54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019"
  },
  "version": "0.15.3"

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Kernel (e.g. `uname -a`):
Linux falco-9wb7b 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 GNU/Linux

- Install tools (e.g. in kubernetes, rpm, deb, from source):

Kubernetes 1.15
- Others:

**Comment by subrnath** [comment]
it's fixed. Closing the isse.

**Comment by aleksf** [comment]
hey @subrnath how did you fix it? I am having same issue using latest falco in eBPF probe  mode.
```
Falco version: 0.26.2                                                                                                                                                                                      
Driver version: 2aa88dcf6243982697811df4c1b484bcbe9488a
```
strace:
```
openat(3, "proc/hwloc-nofile-info", O_RDONLY) = -1 ENOENT (No such file or directory)                                                                                                                       
```
using rule below
```
condition: (evt.category=file and evt.failed=true and container.name contains xui) or (evt.type=execve and container.name contains xui)                                                                     |
```

It does not seem to capture ENOENT for the openat()

**Comment by m4wh6k** [comment]
For anyone else coming across this issue, I was confused at first but was able to get this working for my needs. I suggest debugging with a super simple, very inefficient rule condition, like `evt.res != SUCCESS` and then optimizing the condition. Put lots of fields into into the `output` to see what's going on.
