### ISSUE TITLE
Flag to enable/disable event sources (syscalls, k8s_audit)

### ISSUE THREAD

**Issue by leodido** [falcosecurity/falco#730]
**What would you like to be added**:

A flag to disable the kernel module loading.

**Why is this needed**:

There are use cases in which the user does not need the module (eg., only k8s audit #725).

**Comment by fntlnz** [comment]
I would correct this:
The flag should disable the feature of collecting the Syscalls, whether it is with the kernel module or the bpf probe loader.

**Comment by mfdii** [comment]
This needs to cover any event source. I've updated the title to reflect that. In theory the k8s_audit source is configurable via enabling or disabling the webserver.
