### ISSUE TITLE
Add Netdata to whitelist

### ISSUE THREAD

**Issue by ntimo** [falcosecurity/falco#732]
It would be amazing if Netdata (image: netdata/netdata) could be added to the whitelist. 

The following rules are currently triggered by netdata:
- Launch Suspicious Network Tool in Container
- Launch Sensitive Mount Container

**Comment by Kaizhe** [comment]
@ntimo may I know what network tools were baked into `netdata/netdata`?

**Comment by Kaizhe** [comment]
I've added `netdata/netdata` in the white list in #733 for rule `Launch Sensitive Mount Container`, but will need more info for the rule `Launch Suspicious Network Tool in Container`. 

I would say maybe we can separate it into two issues and close this one.

**Comment by leodido** [comment]
I agree.

**Comment by leodido** [comment]
Reopening since needs more info for the rule `Launch Suspicious Network Tool in Container`.

/triage needs-information

**Comment by fntlnz** [comment]
@ntimo can you provide information about the required tools?

**Comment by fntlnz** [comment]
I'm closing this since no new information came on how to integrate netdata to `Launch Suspicious Network Tool in Container` - @ntimo feel free to reopen this when you will have more information or if you submit a PR.
