### ISSUE TITLE
Add node exporter and cadvisor to whitelist

### ISSUE THREAD

**Issue by ntimo** [falcosecurity/falco#735]
The Docker Images for node exporter (prometheus) and cAdvisor both trigger the sensitive mount rule. It would be nice if those could be whitelisted.

Images:
  - docker.io/prom/node-exporter
  - docker.io/google/cadvisor

Rule: Launch Sensitive Mount Container

**Comment by leodido** [comment]
Hey @ntimo what do you think of contributing them via a PR? :)

**Comment by ntimo** [comment]
@leodido Sure going to create one later today :)
