### ISSUE TITLE
Suffix match operator

### ISSUE THREAD

**Issue by Kaizhe** [falcosecurity/falco#741]
**What would you like to be added**:
we have operator `pmatch` works really well on the prefix match against a list of strings, similarly, I would like to have `smatch` (suffix-match) to do suffix match against a list of string.

**Why is this needed**:
This works well in the scenarios of image matching, for example, we have `quay.io/sysdig/agent` and `docker.io/sysdig/agent`, if we have the suffix match operator, we can create a condition like `container.image.repository smatch [sysdig/agent]` without caring about the image hub.

**Comment by Kaizhe** [comment]
cc @mstemm ^^

**Comment by leodido** [comment]
👍 ⬆️

**Comment by fntlnz** [comment]
Would be useful to avoid things like this https://github.com/falcosecurity/falco/blob/03fbf432f1fddc8e4708271e18cd79aada31d615/rules/falco_rules.yaml#L2388-L2400

**Comment by leodido** [comment]
🆙

**Comment by fntlnz** [comment]
I'm not sure that having this kind of operator will be a good use case for docker images.

if you don't put the FQDN of the image one can bypass the image check by pushing their malicious image on another registry or with a prefix.

E.g

```
container.image.repository smatch [sysdig/agent]
```

matches

- docker.io/sysdig/agent


but also

- docker.io/myevilsysdig/agent
- quay.io/anothersysdig/agent

**Comment by leodido** [comment]
Clearly it depends on how you use such operator while composing your rules.

By the way the situation you describe is possible also **without** this operator.
