### ISSUE TITLE
Falco Fails with the error "PERF_EVENT_IOC_SET_BPF: File exists"

### ISSUE THREAD

**Issue by DannyPat44** [falcosecurity/falco#764]
**What happened**:
We are working to roll out a deliver pipe line for Falco on our production cluster. As part of our pipeline, we were originally planning to have two Falco Dameonset sets running on the cluster. One being “pre-release” firing to a Slack channel, and one being “stable” firing to our actual instrumentation (Pagerduty, etc.). This would have allowed us to develop alerting and system improvements with out causing many false positives. Unfortunately, we ran into the error “PERF_EVENT_IOC_SET_BPF: File exists”. Which from my understanding is caused by the kernel not supporting multiple eBPF programs as per https://github.com/draios/sysdig/issues/1241 on the Sysdig project. 

The error caused one of the Daemonsets to fail on startup and exit, having the containers just sit in a boot cycle when GKE realized it failed. 

**What you expected to happen**:
I would have expected that both Daemonsets would have been able to run within one cluster.

**How to reproduce it (as minimally and precisely as possible)**:
Configure and launch either two Falco Daemonsets on a GKE cluster running COS or launch one Falco Daemon set and attempt to use Sysdig on the same cluster. 

**Anything else we need to know?**:
Not sure if this is a bug or a feature request. But I labelled as Bug because I don't think this is expected behaviour. 

**Environment**:
- Falco version (use `falco --version`): falco 0.15.3
- System info 
root@falco-daemonset-5qjg8:/# falco --support | jq .systen_info
Wed Aug  7 12:54:14 2019: Falco initialized with configuration file /etc/falco/falco.yaml
Wed Aug  7 12:54:14 2019: Loading rules from file /etc/falco/falco_rules.yaml:
Wed Aug  7 12:54:15 2019: Loading rules from file /etc/falco/falco_rules.local.yaml:
Wed Aug  7 12:54:16 2019: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`)
root@falco-daemonset-5qjg8:/# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
- Kernel (e.g. `uname -a`):
Linux falco-daemonset-5qjg8 4.14.127+ #1 SMP Tue Jun 18 18:32:10 PDT 2019 x86_64 GNU/Linux
- Install tools (e.g. in kubernetes, rpm, deb, from source):
- Google Kubernetes Engine (1.13.7-gke.8)
- Deployed using Customize 
- Node OS: Container-Optimized OS (cos)

**Comment by fntlnz** [comment]
Related to: https://github.com/draios/sysdig/issues/1241

**Comment by fntlnz** [comment]
Ok read this a bit better and understood that this problem only happens in Falco because it happens in Sysdig, so since the problem is actually in  draios/sysdig#1241 I'm closing this.

Thanks for taking the time to open @DannyPat44 this was still useful to bring to our attention that this affects falco too, I'm escalating this issue to the maintainers fo the bpf support for sysdig.
