### ISSUE TITLE
Error running in Kubernetes

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falco#769]
**What happened**: 

Following this documentation - when install from a static manifest the pods go into error status. Here are the logs from one of the pods in the DS

```
* Setting up /usr/src links from host
ls: cannot access '/host/usr/src': No such file or directory
* Unloading falco-probe, if present
* Running dkms install for falco
Error! echo
Your kernel headers for kernel 4.14.127+ cannot be found at
/lib/modules/4.14.127+/build or /lib/modules/4.14.127+/source.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/0.16.0/build/make.log
* Trying to load a system falco-probe, if present
* Trying to find precompiled falco-probe for 4.14.127+
Found kernel config at /proc/config.gz
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.16.0-x86_64-4.14.127%2B-e589e4c246c6d662d28ec30f4f32ecf8.ko
curl: (22) The requested URL returned error: 404 Not Found
Download failed, consider compiling your own falco-probe and loading it or getting in touch with the sysdig community
Tue Aug 13 22:44:30 2019: Falco initialized with configuration file /etc/falco/falco.yaml
Tue Aug 13 22:44:30 2019: Loading rules from file /etc/falco/falco_rules.yaml:
Tue Aug 13 22:44:30 2019: Loading rules from file /etc/falco/falco_rules.local.yaml:
Tue Aug 13 22:44:30 2019: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Tue Aug 13 22:44:30 2019: Unable to load the driver. Exiting.
Tue Aug 13 22:44:30 2019: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco-probe module is loaded.. Exiting.
```

**What you expected to happen**:

Pods in the ready state

**How to reproduce it (as minimally and precisely as possible)**:

Follow the `DaemonSet Manifests` section [here](https://falco.org/docs/installation/)

**Anything else we need to know?**:

**Environment**:
- Falco version (use `falco --version`): 0.16.0
- System info  Tue Aug 13 22:55:39 2019: Falco initialized with configuration file /etc/falco/falco.yaml
Tue Aug 13 22:55:39 2019: Loading rules from file /etc/falco/falco_rules.yaml:
Tue Aug 13 22:55:39 2019: Loading rules from file /etc/falco/falco_rules.local.yaml:
Tue Aug 13 22:55:39 2019: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
{
  "machine": "x86_64",
  "nodename": "falco-daemonset-c5n4m",
  "release": "4.14.127+",
  "sysname": "Linux",
  "version": "#1 SMP Tue Jun 18 23:08:40 PDT 2019"
}
- OS (e.g: `cat /etc/os-release`): 

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Cloud provider or hardware configuration: GKE cluster

clientVersion:
  buildDate: "2019-07-28T11:38:32Z"
  compiler: gc
  gitCommit: 4485c6f18cee9a5d3c3b4e523bd27972b1b53892
  gitTreeState: archive
  gitVersion: v1.15.1
  goVersion: go1.12.7
  major: "1"
  minor: "15"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-06-19T20:48:40Z"
  compiler: gc
  gitCommit: f53039cc1e5295eed20969a4f10fb6ad99461e37
  gitTreeState: clean
  gitVersion: v1.12.8-gke.10
  goVersion: go1.10.8b4
  major: "1"
  minor: 12+
  platform: linux/amd64

- Kernel (e.g. `uname -a`): Linux falco-daemonset-c5n4m 4.14.127+ #1 SMP Tue Jun 18 23:08:40 PDT 2019 x86_64 GNU/Linux

- Install tools (e.g. in kubernetes, rpm, deb, from source): 
- Others:

---

**Comment by mfdii** [comment]
Would you please use the issue template, filling out the requested info? We need some info such as the OS and the template tells you how to get that info. 

Thanks!

**Comment by kris-nova** [comment]
Yep! Will do!

**Comment by kris-nova** [comment]
Updated!

**Comment by mfdii** [comment]
We backchannelled on this, but were you able to install the headers for buster and build the kernel module at container start?

**Comment by kris-nova** [comment]
I changed the Deployment code to use the BPF program. I think we need to modify the Dockerfile

**Comment by karthikc911** [comment]
Hi @kris-nova , @mfdii  , 
Even we are facing the same issue on kubernetes with latest version v0.17.0. 
When can we expect the fix for this issue to be rolled-out ?
As a temporary fix can we use the older version of falco container which doe snot have this issue ?

**Comment by arthurk** [comment]
Same problem with Falco 0.17.0 running on GKE cluster version 1.13. Is there a going to be a fix?

**Comment by karthikc911** [comment]
Hi @mfdii , @kris-nova , @tmaior , @arthurk ,

I may have found the bug. 

**Bug** : Falco Docker image name falcosecurity/falco:**latest** is still tagged to older version falcosecurity/falco:**0.16.0** and not newer falcosecurity/falco:**0.17.0**

**Work-Around**: Use docker image falcosecurity/falco:0.17.0 to fix this issue.

**Context :** As per the following doc : https://falco.org/docs/event-sources/kernel-module/ , the kernel module with filename **falco-probe-{falco version}-{arch}-{kernel release}-{kernel config hash>}.ko** is downloaded from S3 Bucket. Since falcosecurity/falco:latest still had falco version 0.16.0 it was trying to download **falco-probe-0.16.0-{arch}-{kernel release}-{kernel config hash>}.ko** which is not present in this List : https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/index.html.

**Comment by fntlnz** [comment]
Thanks for the feedback @karthikc911 - definitely need to bring this up in repo planning

**Comment by rodricarvalho** [comment]
* Setting up /usr/src links from host
* Mounting debugfs
Found kernel config at /proc/config.gz
* Minikube detected (v1.6.0), using linux kernel sources for minikube kernel
* Downloading http://mirrors.edge.kernel.org/pub/linux/kernel/v4.x/linux-4.19.81.tar.gz
* Extracting kernel sources
* Configuring kernel
/bin/sh: 1: bison: not found
make[1]: *** [scripts/Makefile.lib:196: scripts/kconfig/zconf.tab.c] Error 127
make: *** [Makefile:534: olddefconfig] Error 2
/bin/sh: 1: bison: not found
make[2]: *** [scripts/Makefile.lib:196: scripts/kconfig/zconf.tab.c] Error 127
make[1]: *** [Makefile:534: syncconfig] Error 2
Makefile:621: include/config/auto.conf.cmd: No such file or directory
make: *** [Makefile:633: include/config/auto.conf.cmd] Error 2
* Trying to compile BPF probe falco-probe-bpf (falco-probe-bpf-0.17.0-x86_64-4.19.81-6b1f95f8b14210605f7dc14241b2262d.o)

  ERROR: Kernel configuration is invalid.
         include/generated/autoconf.h or include/config/auto.conf are missing.
         Run 'make oldconfig && make prepare' on kernel src to fix it.

Makefile:590: include/config/auto.conf: No such file or directory
make[1]: *** [Makefile:641: include/config/auto.conf] Error 1
make: *** [Makefile:18: all] Error 2
mv: cannot stat '/usr/src/falco-0.17.0/bpf/probe.o': No such file or directory
* Trying to download precompiled BPF probe from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-bpf-0.17.0-x86_64-4.19.81-6b1f95f8b14210605f7dc14241b2262d.o
curl: (22) The requested URL returned error: 404 Not Found
* Failure to find a BPF probe
Tue Mar 10 17:45:04 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Tue Mar 10 17:45:04 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Tue Mar 10 17:45:04 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Tue Mar 10 17:45:04 2020: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Tue Mar 10 17:45:04 2020: Runtime error: Compilation error when compiling "(ka.req.pod.volumes.hostpath intersects (/proc, /var/run/docker.sock, /, /etc, /root, /var/run/crio/crio.sock, /home/admin, /var/lib/kubelet, /var/lib/kubelet/pki, /etc/kubernetes, /etc/kubernetes/manifests))
": 30: syntax error, unexpected 'intersects', expecting 'pmatch', 'in', 'endswith', 'startswith', 'glob', 'icontains', 'contains', '>', '<', '>=', '<=', '!=', '==', '=', 'exists'
---
- macro: sensitive_vol_mount
  condition: >
    (ka.req.pod.volumes.hostpath intersects (/proc, /var/run/docker.sock, /, /etc, /root, /var/run/crio/crio.sock, /home/admin, /var/lib/kubelet, /var/lib/kubelet/pki, /etc/kubernetes, /etc/kubernetes/manifests))
---. Exiting.
