### ISSUE TITLE
Add ability to read trace files over network conns

### ISSUE THREAD

**Issue by mstemm** [falcosecurity/falco#78]
Suggestion from rez410 on /r/netsec--add the ability to read trace files over network connections. The original comment was asking for reading all kinds of logs and not specifically sysdig trace files, but the network read idea is worth considering.

**Comment by mathieuk** [comment]
Part of that question was "can I use this in a centralised manner". You could consider a Falco plugin to http://github.com/facebook/osquery of some sort: receive Falco rules from OSQuery infrastructure, deliver messages through an osquery table. Doesn't centralise analysis but does centralise configuration and reporting.

**Comment by mstemm** [comment]
That looks like a good potential integration. Of course, we'd also probably want to support more general mechanisms for others who didn't want to adopt OSQuery, but I'm sure it would be useful for those that do.
