### ISSUE TITLE
Install script is failing for s390x

### ISSUE THREAD

**Issue by prankkelkar** [falcosecurity/falco#787]
**What happened**:
Trying to install falco on host using scripted install method.  Got following error while doing so.
Command:- ` root@prasanna:~# bash install-falco.sh`

Output:-

``` * Detecting operating system

------------
WARNING: A Docker container is the only officially supported platform on s390x
------------
* Installing Sysdig public key
OK
* Installing falco repository
* Installing kernel headers
* Installing falco
E: Unable to locate package falco 
```

**What you expected to happen**:
Successful completion of the script.

**How to reproduce it (as minimally and precisely as possible)**:
`curl -o install-falco.sh -s https://s3.amazonaws.com/download.draios.com/stable/install-falco
sudo bash install-falco.sh`

**Anything else we need to know?**:
Tried debugging little further. Looks like falco binaries are missing in remote repositories.

**Environment**:

- OS (e.g: `cat /etc/os-release`):

```NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

- Kernel (e.g. `uname -a`):
```Linux prasanna 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:32:27 UTC 2019 s390x s390x s390x GNU/Linux```

- Install tools (e.g. in kubernetes, rpm, deb, from source):
  Scripted install on host.

**Comment by fntlnz** [comment]
Thanks for opening this @prankkelkar - we will discuss about it at the next office hours.

**Comment by prankkelkar** [comment]
@fntlnz  Yes Thank you. Do let me know if you need more details.

**Comment by mfdii** [comment]
As stated by the install script, the script does not support s390.
