### ISSUE TITLE
Consider moving to Kubernetes slack

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falco#790]
**What would you like to be added**:

This is an issue for thought. 

We have the ability to create a Kubernetes official slack channel, but we need to consider if this makes sense for Falco.

**Why is this needed**:

This could help drive contribution to Falco, as well as make it easier for folks to get involved.

The problem is that we already have an OSS slack, and moving it might take work and frustrate users. We are looking for thoughts and opinions here.

**Comment by leodido** [comment]
Thanks fro bringing this up Kris!

I have an initial question. Would this channel in the k8s slack substitute the current one in the public sysdig slack?

I think we should decide for one channel and go for it.

I fear that having more than one channel would generate confusion in the community: in which channel to ask for topic X, in which for topic Y, what if the same best practices/fixes/answers have already been put in the other slack channel?

Ideally I would like to **move** the existing one into the k8s slack, in case this is possible (not a slack superhero so I don't know if it's possible), so to not lose any history.

Aside from this personal consideration I think it's a good idea.

**Comment by fntlnz** [comment]
I see that there's a kubernetes slack now.
What are the actual plans for it @kris-nova

**Comment by leodido** [comment]
We have to move it to the CNCF slack.

So
/close
