### ISSUE TITLE
Scary Container

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falco#794]
**What would you like to be added**:

On TGIK I demo'd what I was calling a "scary pod" or "scary container" but we can please start to imagine what an invasive/privleged test pod would look like in Kubernetes. Ideally this would be a use case that we could demo Falco with.

**Why is this needed**:

So we have an easy way to demonstrate that Falco alerts in various situations

**Comment by mstemm** [comment]
We have the falco event generator container (https://falco.org/docs/event-sources/sample-events/), is that what you mean?

Most of the activity it does is host-oriented, but that works very well in a container as all the bad stuff it does is ephemeral.
