### ISSUE TITLE
Security assessment via CNCF sig-security 

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falco#807]
**What would you like to be added**:

A plan/milestone for a security assessment with the SIG, so we can schedule time with the SIG.

**Why is this needed**:

**Comment by fntlnz** [comment]
We still want to do this

**Comment by fntlnz** [comment]
/close
closing this in favor of #886

**Comment by ultrasaurus** [comment]
The assessment is different from an audit -- I talked to @mfdii who said he would talk to @kris-nova about kicking this off

**Comment by fntlnz** [comment]
@ultrasaurus @kris-nova we need to open this again then.

/reopen

**Comment by fntlnz** [comment]
Looks like there is some activity on this in the sig-security repo.
Linking https://github.com/cncf/sig-security/issues/273
