### ISSUE TITLE
Falco dynamic audit configuration

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falco#809]
# **What would you like to be added**:

Right now in order to use the `k8s-audit` input stream with Falco there are changes that need to be done to the Kubernetes control plane, particularly the API server.

The original goal of the Dynamic Audit feature with the API server was to enable a program running in Kubernetes to turn on the audit stream without having to restart the API server.

As it stands today, [the Dynamic Audit feature](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-dev/6sAvnBxu1sg/EdlgNFqLAAAJ) is in `alpha` which means it's turned *off* by default. In order to enable the feature a user needs to manipulate these 3 flags

`--audit-dynamic-configuration`: the primary switch. When the feature is at GA, the only required flag.
`--feature-gates=DynamicAuditing=true`: feature gate at alpha and beta.
`--runtime-config=auditregistration.k8s.io/v1alpha1=true`: enable API.

which is done by changing the definition of the API server and killing the pod. Kubernetes of course then restarts the pod with the new configuration and we can now dynamically configure audit output streams.

## The Falco Operator

In order to" tell the Kubernetes story" we need to make it easy to get a falco installation up an running. By using an operator instead of a static manifest or a helm chart, this allows us as engineers the ability to build in logic during the setup process. This is going to be critical as we start to mature falco with Kubernetes. Thus, I believe we should prefer the operator to *all other* installation methods.

By using the operator as the preferred installation method, we would be able to configure the API server, register `AuditSink` objects and have Falco configure the API server to talk to Falco. This would be a critical step in making Falco desirable for Kubernetes consumers. No other software currently is doing this (to my knowledge) 

## Enabling Audit Streaming by default in Kubernetes

As a secondary step, we could make the process even more robust by pushing the Dynamic Audit feature into Beta and ultimately into GA with the Kube API server. After this is done we can harden our installation logic and advertise that we are no longer restarting the API server to begin securing Kubernetes.

The change would be driven through `SIG API Machinery` and would need to be proposed in upstream Kubernetes. 

The source code can be found here: https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/apiserver/plugin/pkg/audit/dynamic

# **Why is this needed**:

Contributing this change would be a good first step for getting Falco into Kubernetes by default, and driving adoption of Falco.

After this feature is complete, and we can install Falco in 5 minutes or less we can start to look at very uninvasive and lightweight changes to add `--security=falco` to tools like:

 - kops 
 - kubicorn
 - kubeadm
 - eksctl
 - aks-connector
 - etc... 

All of which would require upstream contributes in Kubernetes.

**Comment by kris-nova** [comment]
We have the most ownership over Kubicorn - I think that would be a good first place to look at installing falco with a cluster

**Comment by fntlnz** [comment]
This is exactly the kind of thing Falco needs to be adopted and have a way of "controlling" the environment in which it's installed. By controllibg the environment in which it is installed falco could have more insights on the environment itself.

There's not much to add, I love this idea .

**Comment by kris-nova** [comment]
Then let's get it planned and coded!

**Comment by leodido** [comment]
This is THE missing piece. Lovely idea. +1

**Comment by stealthybox** [comment]
This is where you would document a user add these apiserver flags in the kubeadm config:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#apiserver-flags

We are working on making add-ons more extensible.

**Comment by kris-nova** [comment]
Thanks @stealthybox and good to see you hanging out here. I will probably lurk in sig-cluster-LIFESTYLE from time to time as we get farther along here

**Comment by kris-nova** [comment]
Also I reviewed the falco operator and currently I think it's more of an operator that exposes rules via CRD and less of an installation operator that will actually provision falco in a cluster

So this begs the question - do we combine these two concepts - or have multiple operators?

**Comment by stealthybox** [comment]
> sig-cluster-LIFESTYLE

+💯 supporting this name-change

**Comment by kris-nova** [comment]
open an issue and ill +1 it
