### ISSUE TITLE
Allow access to process file descriptor table when a rule fires (flight data recorder?)

### ISSUE THREAD

**Issue by gnosek** [falcosecurity/falco#81]
If I find e.g. php doing suspicious things, it doesn't really help me find the source of the attack (except for the uid). What I'd love would be to see the open file list at the time a rule fires to see what the vulnerable script was.

Maybe instead of putting this exact feature into falco (which would probably lead to a slippery slope of storing more and more data, e.g. syscall history before rule fired) a flight data recorder would be good enough. I.e. keep recording all the traced data a'la sysdig -W and remove the files that were recorded during no rule triggers (or maybe keep a couple _before_ a rule fired etc.) -- then the user could simply sysdig -r the relevant file.

The sad thing is, I'd probably love to see the incoming request, which means _not_ excluding read/write calls, at least for network I/O over a bunch of ips/ports.

Come to think of it, as long as falco is detect-only, maybe sysdig flight data recorder + falco reading from scaps (e.g. a minute delay) would be sufficient (it wouldn't stop the attack anyway).

**Comment by henridf** [comment]
Thanks for the feedback. This is totally on the radar (and at one point I even wanted to get this in to the initial release... ).

The good news is that the excluded syscalls are excluded wrt falco filtering. We can still capture everything from falco.

An easy first step is to capture things *after* a rule fires. A little more work to be able to capture activity *before* a rule fires (via some sort of continuous capture).
