### ISSUE TITLE
Building with stable/Dockerfile failed

### ISSUE THREAD

**Issue by spaceportpw** [falcosecurity/falco#814]
file: `docker/stable/Dockerfile`

error:
```
dpkg: dependency problems prevent configuration of libgcc-6-dev:amd64:
 libgcc-6-dev:amd64 depends on libmpx2 (>= 6.3.0-18); however:
  Package libmpx2 is not installed.
```

requirement:
```
libmpx2
```

**Comment by leodido** [comment]
@spaceportpw thanks for reporting this.

Yes, this is similar to a fix we deployed for the CI.

Would you like to submit a PR with a fix for it? This sounds like a good first contribution.
