### ISSUE TITLE
Create Falco terraform provider

### ISSUE THREAD

**Issue by markyjackson-taulia** [falcosecurity/falco#815]
What would you like to be added:

A new Falco terraform provider.

Why is this needed:

Currently a sysdig provider exist but relies on sysdig secure. This work would rely solely on Falco via terraform

**Comment by kris-nova** [comment]
I have contributed to Terraform in the past - I don't know if I have time to code all of this, but I am happy to guide someone into the space and mentor them through coding a provider if needed. 

Let us know if you are interested and we can get in touch!

**Comment by markyjackson-taulia** [comment]
I figured this would be a cool side project and would love to contribute.
Thanks @kris-nova
