### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falco#819]
**What would you like to be added**:

A testing system.

I know we all hate this, but if we will be supporting CVE's and other vulnerabilities opened up we *must* have tests.

There are a few things we are interested in testing, and proving. 

 - Vulnerabilities against `falco`
 - Vulnerabilities against `kubernetes`
 - Vulnerabilities against `linux` 

**Why is this needed**:

So we can prove, concretely, that our tool can not only audit itself, but also audit the environment we wan't to run in. 

We furthermore need an easy way to add future vulnerabilities into our testing system with little overhead (5 minutes or less to prove, `N` hours to code)

**Comment by leodido** [comment]
Somewhat related to #691 (unit tests).

**Comment by leodido** [comment]
This is the umbrella issue about testing: https://github.com/falcosecurity/falco/issues/704
