### ISSUE TITLE
RFC1918 excluded from outbound macro but not inbound_outbound

### ISSUE THREAD

**Issue by shane-lawrence** [falcosecurity/falco#820]
A new list, which contains the private IPv4 ranges in RFC1918, was added and that list has been excluded from the `outbound` macro: 
https://github.com/falcosecurity/falco/blob/39b51562ed88b9ee1700c4811aa1911d4467a450/rules/falco_rules.yaml#L321-L328

The RFC1918 ranges have not been excluded from the `inbound_outbound` macro, so it is no longer a combination of the `inbound` and `outbound` macros:
https://github.com/falcosecurity/falco/blob/39b51562ed88b9ee1700c4811aa1911d4467a450/rules/falco_rules.yaml#L330-L337

**Comment by shane-lawrence** [comment]
I was going to PR a fix to exclude just the private IP ranges, but it looks like this is not the only change to the `inbound` and `outbound` macros that didn't lead to a corresponding change to the `inbound_outbound` macro. #470 was also applied to only the separate rules. Should I incorporate the improvements from that PR into the `inbound_outbound` macro as well?

**Comment by fntlnz** [comment]
/assign @Kaizhe 

@Kaizhe WDYT?

**Comment by Kaizhe** [comment]
@shane-lawrence thanks for bringing it up. It's a good call.  And please assign me as the reviewer :)
