### ISSUE TITLE
Remove stale docs content from Github wiki

### ISSUE THREAD

**Issue by mfdii** [falcosecurity/falco#838]
**What would you like to be removed**:
Back in May we  officially moved the falco docs to falco.org/docs. As part of this we put notices on the existing GH wiki docs that the wiki was deprecated and replaced with the docs site. We also linked each wiki page to the new corresponding docs site page.

It's time to remove all the content from the wiki, leaving only links to the docs site and the new page for the respective topic.

**Why is this needed**:
Google still indexes these pages, and currently the top 3 results for a search of `falco install` sends users to the wiki. Removing the content should hopefully reduce the page rank for the wiki docs, get our current documentation ranking higher, and eventually we can delete the wiki. 

I prefer the slow approach rather than "just delete the wiki now", as we don't know where on the internet people are linking to the wiki.

**Comment by mfdii** [comment]
Content has been removed, with redirect notices. When the stale bot tries to close this again, we should check page rank of the wiki docs and then disable the wiki. Hopefully the falco.org/docs will be ranked higher over the next 30 days.

**Comment by fntlnz** [comment]
We can close this

**Comment by leodido** [comment]
30 days have passed, remove the wiki pages definitely

/assign @kris-nova
