### ISSUE TITLE
Release Falco 0.17.1

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falco#849]
**What happened**:
When we released Falco 0.17.0 we targeted a Sysdig version as dependency which did not contain a fix tu support newer kernels >5.0 .

Because of this and because of the fact that our build script is procedural, when an error is encountered for a new kernel also the subsequent are not built. This leads to the s3 bucket to lack a lot of prebuilt modules and bpf probes.

We discussed and voted this among different solutions  with the community on slack and here's the proposed one.

The solution would be to tag a new falco release, 0.17.1 targeting the same falco code as 0.17.0 but using the latest tagged commit  from Sysdig  and tagging it again for falco 0.17.1 (Sysdig contains a tag for every falco release now)

**What you expected to happen**:
All the probes are built and pushed.

**How to reproduce it (as minimally and precisely as possible)**:

See related issues #846 #638 

**Anything else we need to know?**:

**Environment**:
- Falco version (use `falco --version`):
- System info 
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools (e.g. in kubernetes, rpm, deb, from source):
- Others:

**Comment by fntlnz** [comment]
Part of this release will also be documenting how we do the releases. All that knowledge is still internal to Sysdig as a company and we need to make sure to have it in described in an open document so that we can then think on how to automate it.

We also need to inform the mailing list of new releases as well the slack channel and twitter account.

**Comment by leodido** [comment]
Please note that the umbrella issue about the release process is #726.

**Comment by leodido** [comment]
Not completed.

For issues in the internal CI we have not been able to complete the steps about the artifacts (packages, docker images, and their publishing).

Nevertheless we understood the first step we'll need to achieve in order to have a new more automated and robust release process:
- rename `master` branch to something like `old-master` to do not lose the old tags
- rename `dev` into `master` branch
- make the new `master` the default repo branch

**Comment by fntlnz** [comment]
This is done

/close
