### ISSUE TITLE
Unit and integration tests the gRPC server

### ISSUE THREAD

**Issue by leodido** [falcosecurity/falco#854]
**What would you like to be added**:

Unit and integration tests for:
- [ ] gRPC server
- [ ] gRPC outputs service

**Why is this needed**:

Do I really need to explain the reason we need this? :)

**Comment by kris-nova** [comment]
Connecting to https://github.com/falcosecurity/falco/pull/822

**Comment by fntlnz** [comment]
We still want this! Thanks stalebot

**Comment by leodido** [comment]
Partially fixed by #1245

**Comment by leodido** [comment]
Leave this open.

/help
