### ISSUE TITLE
Add tags in the response message of outputs.proto

### ISSUE THREAD

**Issue by leodido** [falcosecurity/falco#855]
**What would you like to be added**:

A (repeated) field in the `response` message `output.proto` protobuf definition aimed at tagging the outputs that the gRPC output server emits.

Also we probably want the `tags` field to be in the `request` message too for filtering.

**Why is this needed**:

To provide a mechanism to filter/tag output events. Ref #822.

**Comment by fntlnz** [comment]
I still like this !

**Comment by fntlnz** [comment]
Please keep stalebot!

**Comment by leodido** [comment]
Keep
