### ISSUE TITLE
GRPC Output: Also support unix domain sockets

### ISSUE THREAD

**Issue by mstemm** [falcosecurity/falco#858]
**What would you like to be added**:
When we add GRPC Support to falco, it would be good to have an option to support connecting to the grpc server via a unix domain socket in addition to a tcp connection.

**Why is this needed**:
This allows for more security for use cases where clients can be colocated with falco and allows for a slightly smoother process when developing with falco, where you might not want to generate tls certificates.

**Comment by kris-nova** [comment]
The more I think about this, the more I REALLY agree with using Unix domain sockets in favor of mutually encrypted TLS for any inter process communication.

As a community driven project I think we obviously should support both, but this is just a good idea.

**Comment by fntlnz** [comment]
Wait wait wait stalebot!

**Comment by leodido** [comment]
Keep this open

/cc @kris-nova
L.
