### ISSUE TITLE
404 falco probe binary not found

### ISSUE THREAD

**Issue by zetaab** [falcosecurity/falco#869]
**What happened**: I have been using image `falcosecurity/falco:0.17.0` for long time inside k8s. However, now when containers will restart (for some another reason like node restart) the containers are not working anymore.

```
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.17.0-x86_64-4.19.0-6-cloud-amd64-486fcbba5749a5d27d9a60ee37d925d3.ko
curl: (22) The requested URL returned error: 404 Not Found
```

I tried also to update newer version 0.17.1:
```
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.17.1-x86_64-4.19.0-6-cloud-amd64-486fcbba5749a5d27d9a60ee37d925d3.ko
curl: (22) The requested URL returned error: 404 Not Found
```

**What you expected to happen**: I expect that modules should be available in S3

**Comment by fntlnz** [comment]
Can you fill the issue template?

**Comment by brentlassi** [comment]
Likewise, my fresh install is failing to install falco from this link: 
Log messages upon attempted start:

* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.17.0-x86_64-4.14.137%2B-2714396731b5add325bfe08e0bb8e6c1.ko

"curl: (22) The requested URL returned error: 404 Not Found

"Download failed, consider compiling your own falco-probe and loading it or getting in touch with the sysdig community

**Comment by brentlassi** [comment]
**What happened**:
Upon executing the HELM-based install the falco DaemonSet goes into CrashLoopBackOff state.

Log messages:
- Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.17.0-x86_64-4.14.137%2B-2714396731b5add325bfe08e0bb8e6c1.ko
- curl: (22) The requested URL returned error: 404 Not Found
- Download failed, consider compiling your own falco-probe and loading it or getting in touch with the sysdig community

**What you expected to happen**:
Expected Falco to start running as usual.

**How to reproduce it (as minimally and precisely as possible)**:
helm install --name sysdig-falco-1 -f falco-helm.yaml stable/falco

**Environment**:
- Falco version (use `falco --version`): falco-probe-0.17.0-x86_64-4.14.137
- Cloud provider or hardware configuration: GKE running Istio, 1.14.3-gke.11
- Kernel: 
  Kernel version	4.14.137+
  OS image	Container-Optimized OS from Google
  Container runtime version	docker://18.9.7
  kubelet version	v1.14.3-gke.11
  kube-proxy version	v1.14.3-gke.11

- Install tools (e.g. in kubernetes, rpm, deb, from source): HELM

**Comment by bjoernw** [comment]
This is still an issue. Just did a vanilla install via helm-generated templates and im seeing the same 404. Is there any way to get a container with the falco-probe binary already included? I'm a bit concerned that i'm installing a security auditing tool and the first thing it does is try to download a binary from an s3 bucket outside of my domain or whitelisted repos.

**Comment by rodricarvalho** [comment]
* Setting up /usr/src links from host
* Mounting debugfs
Found kernel config at /proc/config.gz
* Minikube detected (v1.6.0), using linux kernel sources for minikube kernel
* Downloading http://mirrors.edge.kernel.org/pub/linux/kernel/v4.x/linux-4.19.81.tar.gz
* Extracting kernel sources
* Configuring kernel
/bin/sh: 1: bison: not found
make[1]: *** [scripts/Makefile.lib:196: scripts/kconfig/zconf.tab.c] Error 127
make: *** [Makefile:534: olddefconfig] Error 2
/bin/sh: 1: bison: not found
make[2]: *** [scripts/Makefile.lib:196: scripts/kconfig/zconf.tab.c] Error 127
make[1]: *** [Makefile:534: syncconfig] Error 2
Makefile:621: include/config/auto.conf.cmd: No such file or directory
make: *** [Makefile:633: include/config/auto.conf.cmd] Error 2
* Trying to compile BPF probe falco-probe-bpf (falco-probe-bpf-0.17.0-x86_64-4.19.81-6b1f95f8b14210605f7dc14241b2262d.o)

  ERROR: Kernel configuration is invalid.
         include/generated/autoconf.h or include/config/auto.conf are missing.
         Run 'make oldconfig && make prepare' on kernel src to fix it.

Makefile:590: include/config/auto.conf: No such file or directory
make[1]: *** [Makefile:641: include/config/auto.conf] Error 1
make: *** [Makefile:18: all] Error 2
mv: cannot stat '/usr/src/falco-0.17.0/bpf/probe.o': No such file or directory
* Trying to download precompiled BPF probe from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-bpf-0.17.0-x86_64-4.19.81-6b1f95f8b14210605f7dc14241b2262d.o
curl: (22) The requested URL returned error: 404 Not Found
* Failure to find a BPF probe
Tue Mar 10 17:45:04 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Tue Mar 10 17:45:04 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Tue Mar 10 17:45:04 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Tue Mar 10 17:45:04 2020: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Tue Mar 10 17:45:04 2020: Runtime error: Compilation error when compiling "(ka.req.pod.volumes.hostpath intersects (/proc, /var/run/docker.sock, /, /etc, /root, /var/run/crio/crio.sock, /home/admin, /var/lib/kubelet, /var/lib/kubelet/pki, /etc/kubernetes, /etc/kubernetes/manifests))
": 30: syntax error, unexpected 'intersects', expecting 'pmatch', 'in', 'endswith', 'startswith', 'glob', 'icontains', 'contains', '>', '<', '>=', '<=', '!=', '==', '=', 'exists'
---
- macro: sensitive_vol_mount
  condition: >
    (ka.req.pod.volumes.hostpath intersects (/proc, /var/run/docker.sock, /, /etc, /root, /var/run/crio/crio.sock, /home/admin, /var/lib/kubelet, /var/lib/kubelet/pki, /etc/kubernetes, /etc/kubernetes/manifests))
---. Exiting.

**Comment by dzoellner** [comment]
+ 1 Happening here too. Looks like a binary was moved but the paths not updated.

**Comment by ArjonBu** [comment]
Why was issue closed? I am still getting this.

**Comment by leogr** [comment]
> Why was issue closed? I am still getting this.

The issue was closed by the stale bot due to inactivity. Since this relates to a very old version of Falco (the prebuilt download mechanism has changed) if you are still encountering this problem with the latest Falco version I'd suggest filing a new issue.
