### ISSUE TITLE
v0.17.1 git tag is wrong

### ISSUE THREAD

**Issue by AkihiroSuda** [falcosecurity/falco#875]
https://github.com/falcosecurity/falco/commit/2439873a967b5aea6431a33691f4967addad83e9 is tagged as both `v0.17.0` and `v0.17.1`

Probably https://github.com/falcosecurity/falco/commit/b08341644ae9312fb8c1d47b1a0a276eceb41fea is the right commit for `v0.17.1`

**Comment by leodido** [comment]
Hello Akihiro, no this is intentional!

0.17.1 is the same Falco source code as 0.17.0, the patch was only about a different sysdig code.
