### ISSUE TITLE
Add ability to generate lists of items dynamically

### ISSUE THREAD

**Issue by mstemm** [falcosecurity/falco#88]
Based on experiences with writing rulesets to restrict activities of pipe installer programs. It'd be nice if you could generate a list of files/items/etc on the fly from a script or similar, and use that list in rules.

For example, you could find all the locations listed in apt source files below /etc/apt/sources.list.d, and write a rule that warns when any outbound connection is made to a host not in that list.

**Comment by PerkinTahmaz** [comment]
This is necessary.
