### ISSUE TITLE
Publish security audit

### ISSUE THREAD

**Issue by caniszczyk** [falcosecurity/falco#886]
Can you publish the security audit for falcon in an easy to find place?

https://github.com/envoyproxy/envoy#security-audit

**Comment by fntlnz** [comment]
Yes, we are planning to do this before releasing 0.18.0 - we are waiting for an update from the auditors to add the fixed PR links to the document, if they don't reply promptly we'll find another way to have such information in the same place.

**Comment by fntlnz** [comment]
Ready to publish!

**Comment by fntlnz** [comment]
Please drop a note in slack when it's published! And a blogpost on it!

**Comment by caniszczyk** [comment]
where is it published?

can you also create advisories for the issues via the github security tool?
https://github.com/falcosecurity/falco/security/advisories

cc: @leodido

**Comment by fntlnz** [comment]
It's not published yet @caniszczyk - @mfdii was assigned at the last Repo planning call

**Comment by leodido** [comment]
@mfdii is in charge of publishing the reports.

me and/or @fntlnz are going to create the advisories soon.

**Comment by caniszczyk** [comment]
friendly ping on this @mfdii :)

**Comment by mfdii** [comment]
Yep yep. Working on the blog drafts now.

**Comment by mfdii** [comment]
Draft done. Will publish 2019/12/16
