### ISSUE TITLE
Release Falco 0.17.2 / 0.18.0?

### ISSUE THREAD

**Issue by dnwe** [falcosecurity/falco#889]
(somewhat related to #851, so feel free to close this, but without a known timeline I thought I'd query this via an issue)

**What would you like to be added**:

A new official falco release with a tagged version of the common code from sysdig containing the fix for #740

**Why is this needed**:

We were consistently hitting OOMKilled due to the memory leak described in #740 in production on 0.16.0 and 0.17.0. Currently we mitigated this by rolling our own compile based on:
```
# XXX: temporarily using dev revision of sysdig source to pull in unreleased fix
# for https://github.com/falcosecurity/falco/issues/740. Switch back to
# SYSDIG_VERSION=falco/0.18.0.tar.gz when falco 0.18.0 bundle is released
ENV SYSDIG_VERSION=586e8fcdaa3d139204fec7c9e4e103432ee9b72f \
    FALCO_VERSION=0.17.0
```

As the memory leak was fixed in the sysdig code on the 29th Aug, it feels like having an official release tag that contains it would be beneficial

**Comment by fntlnz** [comment]
I agree we need to release, we are finalizing the milestone for 0.18.0 - there's only one PR left, if everything goes right we can release early next week.

You can always look at milestones to see how fare things are: https://github.com/falcosecurity/falco/milestones?direction=asc&sort=due_date

That doesn't give a date (yet) but tells how much work there's to do at least.

**Comment by fntlnz** [comment]
Closing this since falco 0.18.0 is released!!

/close
