### ISSUE TITLE
Falco probeloader failed to download kernel module for KERNEL_VERSION: 4.14.137-0414137-generic

### ISSUE THREAD

**Issue by natchaphon-r** [falcosecurity/falco#890]
**What happened**:
I used `falcosecurity:probeloader` to download Falco kernel probe. The container failed with the following message:

```
root@ip-10-97-131-8:/home/ubuntu# docker run --rm --privileged=true -v /boot:/host/boot falcosecurity/probeloader:latest
2019-10-16T14:16:54Z [✿]  FALCO_VERSION: 0.17.1
2019-10-16T14:16:54Z [✿]  FALCO_PROBE_URL: 
2019-10-16T14:16:54Z [✿]  FALCO_PROBE_REPO: https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/
2019-10-16T14:16:54Z [✿]  KERNEL_VERSION: 4.14.137-0414137-generic
2019-10-16T14:16:54Z [✿]  KERNEL_CONFIG_HASH: 206cc09c72e13f25a8653ca9ec9454d1
2019-10-16T14:16:54Z [✿]  Downloading kernel module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.17.1-x86_64-4.14.137-0414137-generic-206cc09c72e13f25a8653ca9ec9454d1.ko
2019-10-16T14:16:54Z [✿]  Recevied HTTP Status Code: 404
2019-10-16T14:16:54Z [✖]  Non-200 Status code received 404
2019-10-16T14:16:54Z [✖]  Error opening kernel module: /falco-probe.ko
2019-10-16T14:16:54Z [✖]  Error loading module: open /falco-probe.ko: no such file or directory
```
The kernel module https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.17.1-x86_64-4.14.137-0414137-generic-206cc09c72e13f25a8653ca9ec9454d1.ko is not available

**Questions**:
1) Last time I synced up with Falco developers, there is an issue with kernel build CI/CD. Is there a github issue to track this?
2) I regularly update kernel version to pick up security patches. The way the URL is [constructed](https://github.com/falcosecurity/falcoctl/blob/master/cmd/probe_install.go#L100), it seems like Falco needs to build kernel probe fro all w.x.yy-zzz Linux version.

Does Falco plan to build kernel probe for every w.x.yy-zzz Linux version and how frequent is the build? Falco kernel probe can block me from upgrading kernel versions.

**How to reproduce it (as minimally and precisely as possible)**:
`docker run --rm --privileged=true -v /boot:/host/boot falcosecurity/probeloader:latest`
**Anything else we need to know?**:

**Environment**:
```
root@ip-10-97-131-8:/home/ubuntu# uname -a
Linux ip-10-97-131-8 4.14.137-0414137-generic #201908061439 SMP Tue Aug 6 18:43:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mfdii** [comment]
@natchaphon-r we need to know the OS (`cat /etc/os-release`).

Unfortunately, we don't compile the kernel probe for every single distribution/kernel, combination.

**Comment by natchaphon-r** [comment]
Thanks @mfdii! 
Here is the requested info:
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
Would you say that the best alternative to getting falco kernel probe is to build from source by following the instructions [here](https://falco.org/docs/source/) if the kernel probe for my specific distribution/kernel combination is not available in https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/?

**Comment by mfdii** [comment]
It's actually a bit easier than that. You can run falco as a container (the full image) on a 18.04.3 host [like so](https://falco.org/docs/running/#running-falco-in-a-container). The only difference is to make `/lib/modules` rw (readwrite) instead of ro (readonly). The falco container will then move the module into the host's `/lib/modules` and you can copy it to a object store from there.

**Comment by natchaphon-r** [comment]
Thanks @mfdii! That's much easier and faster than building from source.

The installation you recommended seems like a good approach. I am trying to avoid running the full falco container just to install kernel probe, terminate the full falco container, and then run the minimal falco container.

What inside the full falco image is responsible for downloading/building the kernel probe? My understanding is it's the /usr/bin/falco-probe-loader call [here](https://github.com/falcosecurity/falco/blob/dev/docker/stable/docker-entrypoint.sh), which then calls falcoctl install [probe](https://github.com/falcosecurity/falco/blob/dev/docker/kernel/probeloader/Dockerfile)

However, if that was the case, it should have failed due to the original issue.

**Comment by natchaphon-r** [comment]
Wanted to close this thread by pasting the workaround I have based on @mfdii's help.

`sudo docker run --privileged --tty --name falco-probe-installer --volume /var/run/docker.sock:/host/var/run/docker.sock --volume /dev:/host/dev --volume /proc:/host/proc:ro --volume /boot:/host/boot:ro --volume /lib/modules:/host/lib/modules:rw --volume /usr:/host/usr:ro falcosecurity/falco:0.18.0 echo Exiting`

This installs falco kernel module in host's /lib/modules by invoking `/usr/bin/falco-probe-loader` within the full falco container and exits the container once installation is complete.

Load the falco kernel module and then you will be able to falcosecurity/falco:0.18.0-minimal.

**Comment by nebed** [comment]
Hey @natchaphon-r  i tried this for AKS in Azure. inside a Virtual machine attached to vmss, so i could get the probe-loader and then continue with installing for the entire cluster. but seems /lib/modules folder does not contain the probe-loader
