### ISSUE TITLE
Build out the new Falco infrastructure

### ISSUE THREAD

**Issue by markyjackson-taulia** [falcosecurity/falco#892]
**What would you like to be added**:
Build out the new Falco infrastructure
**Why is this needed**:
N/A

**Comment by markyjackson-taulia** [comment]
We are in current talk to understand moving the infrastructure to the CNCF infra.. There are a lot of questions and work to be done.
Please use this comment as my +1 for using the CNCF infra.. @lucperkins this is in regards to the CNCF slack conversation I started. I would like to move that to a more public audience for transparency.

**Comment by fntlnz** [comment]
@markyjackson-taulia we already have an issue on this in test-infra https://github.com/falcosecurity/test-infra/issues/48

Building the infrastructure is not a matter in this specific repo while it is in test-infra. Can we keep the discussion there? We can re-open an issue here when there's an actual infrastructure to migrate this repo to.

**Comment by markyjackson-taulia** [comment]
Totally fine and thank you
