### ISSUE TITLE
[integrations/k8s-using-deployment] deprecated APIs removed in k8s 1.16

### ISSUE THREAD

**Issue by oke-py** [falcosecurity/falco#894]
**What happened**:

In k8s v1.16 some APIs are deprecated and removed.
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

As a result, installation failed.
```
kubectl create -f k8s-with-rbac/falco-k8s-audit-deployment.yaml
error: unable to recognize "k8s-with-rbac/falco-k8s-audit-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
```

**What you expected to happen**:
Deployment is successfully deployed.

**How to reproduce it (as minimally and precisely as possible)**:
In k8s 1.16 cluster, run commands described in this page.
https://github.com/falcosecurity/falco/tree/dev/integrations/k8s-using-deployment

**Anything else we need to know?**:

**Environment**:
- Falco version (use `falco --version`):
- System info 
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools (e.g. in kubernetes, rpm, deb, from source):
- Others:

**Comment by fntlnz** [comment]
Thanks for reporting this @oke-py ! 

This must also be changed in tests files

- test/trace_files/k8s_audit/delete_deployment.json 
- test/trace_files/k8s_audit/create_deployment.json

**Comment by oke-py** [comment]
The same is true of [integrations/k8s-using-daemonset].
https://github.com/falcosecurity/falco/tree/dev/integrations/k8s-using-daemonset
