### ISSUE TITLE
Falco versions other than 0.17.1 fail to launch Amazon Linux 2

### ISSUE THREAD

**Issue by jrobersonaquent** [falcosecurity/falco#919]
**What happened**:

Falco containers using versions other than 0.17.1 (tested with 0.17.0 and 0.18.0) immediately crash because the kernel module can't be downloaded.

Logs from falco container:

```
* Setting up /usr/src links from host
* Unloading falco-probe, if present
* Running dkms install for falco
Error! echo
Your kernel headers for kernel 4.14.146-119.123.amzn2.x86_64 cannot be found at
/lib/modules/4.14.146-119.123.amzn2.x86_64/build or /lib/modules/4.14.146-119.123.amzn2.x86_64/source.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/0.17.0/build/make.log
* Trying to load a system falco-probe, if present
* Trying to find precompiled falco-probe for 4.14.146-119.123.amzn2.x86_64
Found kernel config at /host/boot/config-4.14.146-119.123.amzn2.x86_64
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.17.0-x86_64-4.14.146-119.123.amzn2.x86_64-2a8e59358e4477733a8a706f1784f316.ko
curl: (22) The requested URL returned error: 404 Not Found
Download failed, consider compiling your own falco-probe and loading it or getting in touch with the sysdig community
Tue Nov  5 20:12:11 2019: Falco initialized with configuration file /etc/falco/falco.yaml
Tue Nov  5 20:12:11 2019: Loading rules from file /etc/falco/falco_rules.yaml:
Tue Nov  5 20:12:12 2019: Loading rules from file /etc/falco/falco_rules.local.yaml:
Tue Nov  5 20:12:12 2019: Unable to load the driver. Exiting.
Tue Nov  5 20:12:12 2019: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco-probe module is loaded.. Exiting.
```

**What you expected to happen**:

The falco module should have been built or
The pre-built module should exist at `https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-FALCO_VERSION-x86_64-4.14.146-119.123.amzn2.x86_64-2a8e59358e4477733a8a706f1784f316.ko` for versions other than 0.17.1

Log output for version 0.17.1:

```
* Setting up /usr/src links from host
* Unloading falco-probe, if present
* Running dkms install for falco
Error! echo
Your kernel headers for kernel 4.14.146-119.123.amzn2.x86_64 cannot be found at
/lib/modules/4.14.146-119.123.amzn2.x86_64/build or /lib/modules/4.14.146-119.123.amzn2.x86_64/source.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/0.17.1/build/make.log
* Trying to load a system falco-probe, if present
* Trying to find precompiled falco-probe for 4.14.146-119.123.amzn2.x86_64
Found kernel config at /host/boot/config-4.14.146-119.123.amzn2.x86_64
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.17.1-x86_64-4.14.146-119.123.amzn2.x86_64-2a8e59358e4477733a8a706f1784f316.ko
Download succeeded, loading module
Tue Nov  5 20:31:06 2019: Falco initialized with configuration file /etc/falco/falco.yaml
Tue Nov  5 20:31:06 2019: Loading rules from file /etc/falco/falco_rules.yaml:
Tue Nov  5 20:31:07 2019: Loading rules from file /etc/falco/falco_rules.local.yaml:
...
```

**How to reproduce it (as minimally and precisely as possible)**:

Launch Falco container in an EKS cluster or Amazon EKS-Optimized Linux AMI instance using image `falcosecurity/falco:0.18.0` or `falcosecurity/falco:0.17.0`

**Anything else we need to know?**:

This is a similar issue to #912 but building the module doesn't work because the headers don't seem to be present, necessitating using a precompiled module. 

**Environment**:
- Falco version (use `falco --version`): 0.17.0 and 0.18.0
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): [Amazon EKS-Optimized Linux AMI](https://docs.aws.amazon.com/en_pv/eks/latest/userguide/eks-optimized-ami.html) (Amazon Linux 2 based)
- Kernel (e.g. `uname -a`): `4.14.146-119.123.amzn2.x86_64`
- Install tools (e.g. in kubernetes, rpm, deb, from source): AWS EKS
- Kubernetes version: 1.12
- AMI ID: `ami-0ee9e136178176e29`

**Comment by karthikc911** [comment]
@kris-nova  , @fntlnz , @leodido , 

I see that there are repeatedly more issues related to pre-compiled Falco Probe KO files in https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/index.html in every Falco release. 

I think it is better for us if we can build the required ko files on our own for kernels we use. 

Can you please point me to the document/code which provides steps to build the .ko files ?

**Comment by frankreno** [comment]
@fntlnz - was just on a call and we are running into this, seems related to what was fixed before with https://github.com/falcosecurity/falco/issues/846

**Comment by fntlnz** [comment]
@karthikc911 - I agree that building your own kernel module is the best solution in general.

Building the module from source is documented [here](https://falco.org/docs/source/), be careful to look at the previous steps, not just `make driver`.

@frankreno In general the precompiled modules are a subset of what's available out there. We are in the process of making the build script and infrastructure to other contributors out there so that one can just make a PR to add support for a new kernel. Follow more here https://github.com/falcosecurity/test-infra/issues/53

**Comment by krishnan-ramkumar** [comment]
Hi All, a fix for this has been found and will be merged soon, but in the meanwhile, the falco probe for the latest falco version has been uploaded. 
```
upload: output/falco-probe-0.18.0-x86_64-4.14.146-119.123.amzn2.x86_64-2a8e59358e4477733a8a706f1784f316.ko to s3://download.draios.com/stable/sysdig-probe-binaries/falco-probe-0.18.0-x86_64-4.14.146-119.123.amzn2.x86_64-2a8e59358e4477733a8a706f1784f316.ko
```

**Comment by karthikc911** [comment]
@jrobersonaquent , 

I have uploaded the pre-compiled falco kernel modules of falco versions 0.17.0 , 0.17.1 , 0.18.0 for amazon Linux 2 OS to S3 Bucket : https://falco-kernel-modules.s3-us-west-1.amazonaws.com/ .

I have tested all the ko files and everything seems to be working as expected. You can directly use these files with respective falco docker image. 

@fntlnz , @krishnan-ramkumar  : We use Amazon Linux 2 AMI for running Kubernetes Clusters. Hence I will be building Falco KO files for latest 3 versions of Falco each time there is a newer kernel version. How can I upload these files to Falco S3 Bucket ? (https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/index.html).
