### ISSUE TITLE
Expose the node metadata in the Falco outputs API

### ISSUE THREAD

**Issue by palmerabollo** [falcosecurity/falco#923]
**What would you like to be added**:

Falco should expose the "node" metadata (host that originated an alert) to third-party consumers.

**Why is this needed**:

It would be really useful to solve use cases such as https://github.com/falcosecurity/falco-exporter/issues/10, where third-party services need to act every time an alarm is raised on a node. For example, to cordon a node if running in a Kubernetes cluster, or just take the affected node down using draino.

The "node" metadata should be propagated to [falco-exporter](https://github.com/falcosecurity/falco-exporter), that communicates with falco via gRPC, to be able to consume that info as a label in the Prometheus metrics.

**Comment by leodido** [comment]
Thanks for opening it! :)

**Comment by palmerabollo** [comment]
Hi @leodido. Do you think this is a good issue for a first-time contributor?

We have been taking a look at https://github.com/falcosecurity/falco/blob/dev/userspace/falco/falco_outputs.cpp#L300 and https://github.com/falcosecurity/falco/blob/dev/userspace/falco/lua/output.lua#L170-L173 and it looks doable (not trivial). We'd like to know if you are open to contributions or if we should fork the repository.

Some questions:
- In the [output.proto](https://github.com/falcosecurity/falco/blob/dev/userspace/falco/output.proto#L37), should the "hostname" be a new attribute or just a new key/value in the existing `output_fields` map?
- Is the hostname a new concept in falco (i.e. should we calculate it) or is it already available somewhere?
- Should the "hostname" be added to all the outputs (json, etc)? Do you think "hostname" is a good name our would you rather use "host"/"node"/...?

Thank you.

**Comment by leodido** [comment]
Hi @palmerabollo did not see this comment, I replied on the open slack.

However yes this would be an awesome first contribution! 🎉 

I'd prefer having "hostname" as a new attribute (`output_fields` can sometime contain that information but that's another story).

Regarding whether "hostname" is the correct name or not I would suggest to also involve other people talking/voting about such choice in the slack thread :)
