### ISSUE TITLE
Remove references to Sysdig

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falco#924]
**What would you like to be added**:

Can we rename some of the Sysdig references in code for architectural vanity? We are trying to decouple this for vendor independence and this is confusing for users. 

**Why is this needed**:

Clarify the separation of the technology

---

We can see work started https://github.com/falcosecurity/falco/pull/910 but [still needs work.](https://github.com/falcosecurity/falco/search?q=sysdig&unscoped_q=sysdig)

**Comment by kris-nova** [comment]
I am working on a PR for this and can have something open during the Falco hackathon this week! Woo!

**Comment by fntlnz** [comment]
There's anything more than what we have in this?

https://github.com/falcosecurity/falco/pull/922

I'm a bit confused about what you want to do.

**Comment by leodido** [comment]
#922 fixes the majority of those references btw :)

**Comment by leodido** [comment]
This is done. Closing
