### ISSUE TITLE
Can't disable syscall event source while deploying on Kubernetes

### ISSUE THREAD

**Issue by quanvuminh** [falcosecurity/falco#936]
**What happened**:

I can not disable **syscall** event source as announced in new release 0.18.0 changelog. I still got errors during container startup while applying the Kubernete deployment.

```
# kubectl logs falco-k8s-audit-5dd687df6b-4mvbr
* Setting up /usr/src links from host
ls: cannot access '/host/usr/src': No such file or directory
* Unloading falco-probe, if present
* Running dkms install for falco
Error! echo
Your kernel headers for kernel 4.9.0-5-amd64 cannot be found at
/lib/modules/4.9.0-5-amd64/build or /lib/modules/4.9.0-5-amd64/source.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/0.18.0/build/make.log
* Trying to load a system falco-probe, if present
* Trying to find precompiled falco-probe for 4.9.0-5-amd64
Cannot find kernel config
Fri Nov  8 04:32:04 2019: Falco initialized with configuration file /etc/falco/falco.yaml
Fri Nov  8 04:32:04 2019: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Fri Nov  8 04:32:04 2019: Unable to load the driver. Exiting.
Fri Nov  8 04:32:04 2019: Runtime error: error creating the process list. Make sure you have root credentials.. Exiting.
```

**What you expected to happen**:

Container can start and run.

**How to reproduce it (as minimally and precisely as possible)**:

 I applied the same manifest [here](https://github.com/falcosecurity/falco/tree/dev/integrations/k8s-using-deployment).

**Anything else we need to know?**:

**Environment**:
- Falco version: 0.18.0
- Install tools: Kubernetes 1.12

**Comment by fntlnz** [comment]
This still needs investigation.
/reopen

**Comment by quanvuminh** [comment]
I tried with the newest release 0.20.0, the container can start and run now but there still are error messages about syscall event source activation
```bash
~$ kubectl logs falco-k8s-audit-5f58b69b55-7wvvq
* Setting up /usr/src links from host
ln: failed to create symbolic link '/usr/src//host/usr/src/*': No such file or directory
* Unloading falco-probe, if present
* Running dkms install for falco
Error! echo
Your kernel headers for kernel 4.9.0-5-amd64 cannot be found at
/lib/modules/4.9.0-5-amd64/build or /lib/modules/4.9.0-5-amd64/source.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/0.20.0+d77080a/build/make.log
* Trying to load a system falco-probe, if present
* Trying to find precompiled falco-probe for 4.9.0-5-amd64
Cannot find kernel config
Wed Feb 26 11:31:32 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Wed Feb 26 11:31:32 2020: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Wed Feb 26 11:31:32 2020: Starting internal webserver, listening on port 8765
```

**Comment by fntlnz** [comment]
No stalebot! We want to keep this

**Comment by fntlnz** [comment]
/help

labeling as help needed, we need someone to look at why this does not work.

**Comment by leogr** [comment]
I think this has been solved here :point_right: https://github.com/falcosecurity/evolution/tree/master/deploy/kubernetes/k8s-audit-only

The above "k8s-audit-only" example works with 0.23.0, without `--privileged` and with syscall event source disabled :point_down: 
https://github.com/falcosecurity/evolution/blob/master/deploy/kubernetes/k8s-audit-only/deployment.yaml

Btw, it works because is using the `falco-no-driver` image (on the other hand, the normal `falco` image will try the driver anyway).

Please, can you confirm that?

**Comment by leogr** [comment]
I believe this has been fixed (even within the helm chart).
/close
Please, feel free to reopen the issue if I'm wrong :)
