### ISSUE TITLE
Missing BPF probe for Amazon Linux 2

### ISSUE THREAD

**Issue by danmx** [falcosecurity/falco#937]
**What happened**:
Falco failed to deploy using helm stable chart with custom parameters:
```
ebpf:
  # Enable eBPF support for Falco
  enabled: true
cri:
  enabled: false
```
Because of a missing precompiled probe:
```
* Trying to download precompiled BPF probe from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-bpf-0.17.1-x86_64-4.14.138-114.102.amzn2.x86_64-c62c9c7d342c26dbac88ad04bc036848.o
curl: (22) The requested URL returned error: 404 Not Found
```

**What you expected to happen**:
Falco to start
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Falco version (use `falco --version`): `0.17.1`
- System info 
- Cloud provider or hardware configuration: `AWS`
- OS (e.g: `cat /etc/os-release`): `Amazon Linux 2`
- Kernel (e.g. `uname -a`): `4.14.138-114.102.amzn2.x86_64`
- Install tools (e.g. in kubernetes, rpm, deb, from source): `stable helm chart`
- Others:

```
* Setting up /usr/src links from host
* Mounting debugfs
Found kernel config at /host/boot/config-4.14.138-114.102.amzn2.x86_64
* Trying to compile BPF probe falco-probe-bpf (falco-probe-bpf-0.17.1-x86_64-4.14.138-114.102.amzn2.x86_64-c62c9c7d342c26dbac88ad04bc036848.o)
make[1]: *** /lib/modules/4.14.138-114.102.amzn2.x86_64/build: No such file or directory.  Stop.
make: *** [Makefile:18: all] Error 2
mv: cannot stat '/usr/src/falco-0.17.1/bpf/probe.o': No such file or directory
* Trying to download precompiled BPF probe from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-bpf-0.17.1-x86_64-4.14.138-114.102.amzn2.x86_64-c62c9c7d342c26dbac88ad04bc036848.o
curl: (22) The requested URL returned error: 404 Not Found
* Failure to find a BPF probe
Tue Nov 26 14:40:06 2019: Falco initialized with configuration file /etc/falco/falco.yaml
Tue Nov 26 14:40:06 2019: Loading rules from file /etc/falco/falco_rules.yaml:
Tue Nov 26 14:40:06 2019: Loading rules from file /etc/falco/falco_rules.local.yaml:
Tue Nov 26 14:40:07 2019: Unable to load the driver. Exiting.
Tue Nov 26 14:40:07 2019: Runtime error: can't open BPF probe '/root/.sysdig/falco-probe-bpf.o': No such file or directory. Exiting.
```

**Comment by fntlnz** [comment]
We are not providing precompiled BPF probes (Yet, we are working on a proposal to do a compile once run everywhere BPF probe using BTF). I think that the script shouldn’t even try to go get them.

What you can do is to install the kernel headers on your nodes so that they can compile it themselves. On amazon Linux it should be :

```
yum install kernel-headers
```

**Comment by leogr** [comment]
> ```
> yum install kernel-headers
> ```

Please note that the correct package should be:
```
yum install kernel-devel-$(uname -r)
```

**Comment by agusgonzaleznic** [comment]
Together with @augustonf we are having the same issue with version 0.30.0-slim deployed as helm chart.

`Fri Nov 19 18:45:51 2021: Falco version 0.30.0 (driver version 3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4)
Fri Nov 19 18:45:51 2021: Falco initialized with configuration file /etc/falco/falco.yaml
Fri Nov 19 18:45:51 2021: Loading rules from file /etc/falco/falco_rules.yaml:
Fri Nov 19 18:45:51 2021: Loading rules from file /etc/falco/falco_rules.local.yaml:
Fri Nov 19 18:45:51 2021: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Fri Nov 19 18:45:52 2021: Unable to load the driver.
Fri Nov 19 18:45:52 2021: Runtime error: can't open BPF probe '/root/.falco/falco-bpf.o': No such file or directory. Exiting.`

**Comment by leogr** [comment]
> Together with @augustonf we are having the same issue with version 0.30.0-slim deployed as helm chart.

What do you mean by `0.30.0-slim`? Are you using the `falco-no-driver` image?

The reported error is just saying the bpf probe does not exist in the expected location. But there are several ways to provide it. 
So your issue may be similar, though not exactly the same. Please open another issue with all installation details and the full log, we will try to help :)
