### ISSUE TITLE
Add chisel-like aggregations at falco level

### ISSUE THREAD

**Issue by mstemm** [falcosecurity/falco#94]
Within sysdig, chisels are really useful as they allow for lua-driven aggregations across multiple events. It'd be nice to have the same type of functionality where you could define a chisel to perform aggregation and expose the chisel's outputs to make them available in falco rules.

One example might be duplicating the functionality of topprocs_\* chisels, and use that for a rule similar to "alert when a process is sending excess network traffic" or similar.

**Comment by avestalea** [comment]
+1
