### ISSUE TITLE
Build improvements: Dynamic builds

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falco#963]
**What would you like to be added**:

At the moment, the main Falco `CMakeLists.txt` and its children have hard-coded compilation flags to always compile falco as a static binary.

While has its advantages (no extra dependencies), using static binaries as a packaging medium can be cause of any sort of issues, like:

- Big final binary size 
- Difficulties in statically building/linking all the dependencies in various operating systems/kernels/glibc versions
- We don't rely on distributions to take care of patches, and most importantly, security patches in our dependencies (because we don't use OS packages for them)
- The previous point is particularly important, since we have a webserver and a gRPC server. Both need an SSL implementation. We are statically linking OpenSSL to a version that is > 1year old
- It's difficult to keep dependencies updated in general, we would rather declare the versions we work with
- Building is extremely slow and this is BAD contributor experience

Of course, one might say: "Yes but packaging becomes more difficult"

I would argue with that, we have three main distribution mediums:

- rpm packge
- deb package
- container image (aka. docker image)

For the rpm and deb package we can easily declare their dependencies in them instead.

For the container image we can install the needed dependencies directly in the container.

This **does not affect** the kernel module and the bpf probe. FTR I'm trying to refactor the bpf probe in a "compile once and run everywhere" fashion in issue #942 . 

**Why is this needed**:

Because we all deserve better builds.

**Comment by fntlnz** [comment]
Here's the action plan in form of the dependencies we have.

Dates in the european format.

| name          | current used version         | latest available version | current used release date | latest available release date | project status  | ubuntu packages | fedora packages | centos packages | rhel packages | debian packages | arch linux packages |
|---------------|------------------------------|--------------------------|---------------------------|-------------------------------|-----------------|-----------------|-----------------|-----------------|---------------|-----------------|---------------------|
| libscap       | tagged with falco on release |                          |                           |                               | maintained      |                 |                 |                 |               |                 |                     |
| libsinsp      | tagged with falco on release |                          |                           |                               | maintained      |                 |                 |                 |               |                 |                     |
| zlib          | 1.2.11                       | 1.2.11                   | 15/01/2017                | 15/01/2017                    | maintained      |                 |                 |                 |               |                 |                     |
| jq            | 1.5                          | 1.6                      | 16/08/2015                | 02/11/2018                    | maintained      |                 |                 |                 |               |                 |                     |
| nlohmann-json | 3.3.0                        | 3.7.3                    | 05/10/2018                | 17/11/2019                    | maintained      |                 |                 |                 |               |                 |                     |
| ncurses       | 6.0                          | 6.1                      | 08/08/2015                | 27/01/2018                    | maintained      |                 |                 |                 |               |                 |                     |
| libb64        | 1.2                          | 1.2                      | 28/06/2013                | 28/06/2013                    | unmaintained    |                 |                 |                 |               |                 |                     |
| yamlcpp       | 0.6.2                        | 0.6.3                    | 06/03/2018                | 25/09/2019                    | maintained      |                 |                 |                 |               |                 |                     |
| OpenSSL       | 1.0.2n                       | 1.1.1c                   | 27/03/2018                | 10/09/2019                    | maintained      |                 |                 |                 |               |                 |                     |
| libcurl       | 7.61.0                       | 7.67.0                   | 16/07/2018                | 06/11/2019                    | maintained      |                 |                 |                 |               |                 |                     |
| LuaJIT        | 2.0.3                        | 2.0.5                    | 19/02/2013                | 01/05/2017                    | maintained      |                 |                 |                 |               |                 |                     |
| lpeg          | 1.0                          | 1.2                      | can't determine           | can't determine               | can't determine |                 |                 |                 |               |                 |                     |
| Libyaml       | 0.1.4                        | 0.2.2                    | 24/12/2012                | 13/03/2019                    | maintained      |                 |                 |                 |               |                 |                     |
| lyaml         | 6.0                          |                          |                           |                               |                 |                 |                 |                 |               |                 |                     |
| civetweb      | 1.11                         |                          |                           |                               |                 |                 |                 |                 |               |                 |                     |
| cares         | 1.13.0                       |                          |                           |                               |                 |                 |                 |                 |               |                 |                     |
| protobuf      | 3.8.0                        |                          |                           |                               |                 |                 |                 |                 |               |                 |                     |
| gRPC          | 1.25.0                       |                          |                           |                               |                 |                 |                 |                 |               |                 |                     |

Appendix
1. I also added release dates to emphasize the fact that having the OS dealing with dependencies and dependencies dependencies is a better idea than doing it ourselves, we even have dependencies as old as 2012.


2. `libscap` and `libsinsp` will still be compiled into Falco but their dependencies will be not. As an alternative in future we can look into installing the Sysdig package as a whole but doesn't seem convenient from a user point of view because they will then have all the other sysdig tooling while they only wanted Falco. A better alternative would be to split libsinsp and libscap from the Sysdig repository and let them have their own packages.



3. **IMPORTANT**: It's important to note that OpenSSL has different release series, the LTS we use now, `1.0.2`  is EOL on Dec 31th 2019 - [read here](https://www.openssl.org/policies/releasestrat.html) - this is why in the list I went with the `1.1.1c` as latest available.

4. Talking with @leodido - we acknowledge that when we are ready with the Inputs API (can replace civetweb with an HTTP external Input), we do a gRPC output Webhook, and the new rules engine we can drop: `civetweb`, `lyaml`, `libyaml`, `lpeg`, `LuaJIT`, `cURL`.

5. Not sure if we need `b64` still, and we can send a patch to `libscap` to avoid `ncurses` in builds that don't use that feature

**Comment by fntlnz** [comment]
For future documentation purposes, to build, Falco also requires the openssl binary to be available in the system when using the new dynamic configuraiton.

**Comment by kris-nova** [comment]
We might want to check out the AUR as well once this is simplified

**Comment by fntlnz** [comment]
Another dependency we need to have is the `cpack` binary whenever the user want to create deb and rpm packages.
