### ISSUE TITLE
Connection error running Falco on Azure (aks-engine) master nodes 

### ISSUE THREAD

**Issue by palmerabollo** [falcosecurity/falco#985]
**Describe the bug**

Falco pods running on Kubernetes master nodes don't work in clusters created with [Azure AKS engine](https://github.com/Azure/aks-engine/).

This is the error shown in the falco logs of those pods:

```
[...]
2019-12-13T10:24:45+0000: Loading rules from file /etc/falco/falco_rules.yaml:
2019-12-13T10:24:56+0000: Runtime error: Socket handler (k8s_pod_handler_state), error 5 (Connection reset by peer) while connecting to kubernetes.default.svc.cluster.local:443. Exiting.
```

This is the root issue that causes failures connecting to kubernetes api server from the master nodes https://github.com/Azure/aks-engine/issues/622. It is a known limitation of the current Kubernetes + Azure implementation.

**How to reproduce it**

1. Create a cluster with 3 master nodes with [aks-engine](https://github.com/Azure/aks-engine/).
2. Deploy falco as a daemonset so it runs in all nodes, including masters.
3. Pods running in the master nodes will crash.

**Expected behaviour**

Pods running in the master nodes should work as if they were running in any other worker node.

**Environment**

- Falco version:
0.18.0
- Cloud provider or hardware configuration: Azure
- Installation method: Kubernetes daemonset

**Additional context**

Even if it's an issue with Kubernetes + Azure implementation, I've opened this issue to track it  and see if something can be done from falco's side.

Original report in slack https://sysdig.slack.com/archives/C19S3J21F/p1576233140152500

**Comment by palmerabollo** [comment]
Not stale.

**Comment by palmerabollo** [comment]
Not stale. I no longer use aks-engine so I guess this issue will eventually be closed by the stale bot.

**Comment by palmerabollo** [comment]
@fntlnz I won't be able to test it in the short term because we have migrated from aks-engine to AKS (as a service, where the master nodes are part of the control plane managed by Azure).

**Comment by mvandewouw** [comment]
just a heads up, when switching from k8s 1.16.10 -> 1.18.8 falco started to work normally

**Comment by fntlnz** [comment]
@mvandewouw interesting, did you have a chance to understand why that happens?

**Comment by palmerabollo** [comment]
@fntlnz This change/fix https://github.com/Azure/aks-engine/pull/2953 could be the cause. Now, each apiserver instance listens on the local IP address, instead of sitting behind a LB.
