### ISSUE TITLE
End Users Tracking

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falco#986]
**Motivation**

Right now we have documented [a lot of production users of Falco](https://github.com/falcosecurity/falco/blob/dev/ADOPTERS.md). 

The CNCF was generous enough to vote the project into incubation but we have a LOT of work yet to do. For example, there is very valid [concern about Falco end users](https://lists.cncf.io/g/cncf-toc/message/3970). 

**Feature**

Can we start exploring ways to track our end users, and contact information for them? Right now this seems to be undocumented and the relationships should be available for the entire community. 

**Alternatives**

None

**Additional context**

None

**Comment by KnoxAnderson** [comment]
Really cool compliance company I've been tracking for a while has an offering that automates installing falco on the EC2 instances. I'm not sure how many end users are consuming falco through their offering https://www.shujinko.io/

<img width="1071" alt="Screen Shot 2019-12-20 at 12 08 36 PM" src="https://user-images.githubusercontent.com/13387594/71289255-904bc880-2321-11ea-9546-e45ed904c26f.png">

**Comment by kris-nova** [comment]
Closing in favor of tracking in a google spreadsheet. Reach out to the myself or other maintainers in the Falco slack for access.

**Comment by kris-nova** [comment]
Reopening so that we can share
