### ISSUE TITLE
Implement pep8 / flake8 for python code in falco

### ISSUE THREAD

**Issue by rmitr** [falcosecurity/falco#991]
**Motivation**
Long back in the community call we discussed to standerize python code, so that it remains or follows same pattern of code. In python this can be done by checking flake and pep8 rules in ci pipeline. 

**Feature**
1. Flake8 
2. pylint

**Alternatives**

**Additional context**

**Comment by rajibmitra** [comment]
It would be better if its added as part of ci in the infra provided by cncf, so that during each build we get one report.

**Comment by rajibmitra** [comment]
As @leodido  mentioned in the call yesterday that this has to be part of regression test suite which needs to be rewritten as it broken write now. marking it hold for now. 
If we all agree to add pytest at some later point as our test suite , we can easily call these flake8 and pylist as part of our pipeline. 



/hold
