### ISSUE TITLE
Update the yaml files.

### ISSUE THREAD

**Issue by rmitr** [falcosecurity/falco#993]
**Describe the bug**
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals
we have to use apps/v1 places like here 
https://github.com/falcosecurity/falco/blob/dev/integrations/k8s-using-daemonset/k8s-with-rbac/falco-daemonset-configmap.yaml#L1

**How to reproduce it**
1. use latest k8s 
2. apply the yaml files 

You will get below error 
 kubectl apply -f k8s-with-rbac/falco-daemonset-configmap.yaml
error: unable to recognize "k8s-with-rbac/falco-daemonset-configmap.yaml": no matches for kind "DaemonSet" in version "extensions/v1beta1"

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by rajibmitra** [comment]
We should be having at least one branch created from dev that has the updated yaml files to support latest k8s api.
